### ISSUE TITLE
[Parent][MessageChannel] Error: (msgtype=0x2C001F,name=PContent::Msg_PreferenceUpdate) Channel error: cannot send/recv

### ISSUE THREAD

**Issue by johno1985** [mozilla/geckodriver#1177] opened 2018-02-14 21:25 UTC
## System

* Version: 0.19.1-win64
* Platform: Windows Server 2012 64bit
* Firefox: 58.0.2 64 bit
* Selenium: 3.9.1
* Jenkins: 2.95
* Java: 
java version "1.8.0_161"
Java(TM) SE Runtime Environment (build 1.8.0_161-b12)
Java HotSpot(TM) 64-Bit Server VM (build 25.161-b12, mixed mode)
* Maven:
Apache Maven 3.3.9 (bb52d8502b132ec0a5a3f4c09453c07478323dc5; 2015-11-10T16:41:47+00:00)
Maven home: C:\Users\Jonathan\Downloads\apache-maven-3.3.9-bin\apache-maven-3.3.9
Java version: 1.8.0_151, vendor: Oracle Corporation
Java home: C:\Program Files\Java\jdk1.8.0_151\jre
Default locale: en_GB, platform encoding: Cp1252
OS name: "windows 10", version: "10.0", arch: "amd64", family: "dos"

## Testcase

When running a Java Selenium test via Jenkins, the test fails with the following Jenkins console output

## Stacktrace

[jenkins-console.log](https://github.com/mozilla/geckodriver/files/1725684/jenkins-console.log)

**Comment by whimboo** [comment] 2018-02-15 08:55
You experience crashes of the currently active tab. Would you mind running a debug build and report another trace log? I would appreciate that. A recent x64 Nightly debug build can be found here: https://queue.taskcluster.net/v1/task/XyrYBlxXRyakvdY8xGkhVw/runs/0/artifacts/public/build/target.zip. Just unzip and run firefox.exe as usual. Thanks.

**Comment by johno1985** [comment] 2018-02-15 22:32
Hi Henrik,

Thank you for your prompt response. I'll give that a try. Is there a way to
easily switch between two installations of Firefox when running Gecko? I
don't want to have to uninstall/reinstall.

Kind regards,

Jonathan

**Comment by whimboo** [comment] 2018-02-16 09:14
Just unzip the target.zip file as I linked to in my last comment. There is no need to install Firefox. It will just run out of the box. Once testing is done you also only have to remove the folder, and it will be gone.

**Comment by johno1985** [comment] 2018-02-16 21:44
OK, I'll give that a go. I presume the Gecko driver will know to look for
the most reason version of Firefox on the file system.

Kind regards,

Jonathan

**Comment by lepik1108** [comment] 2018-02-20 10:46
Getting same problem. Running geckodriver by vagrant provision script.
Looks like Firefox can't start, while geckodriver running as background task.
When I run geckodriver as foreground process problem disappears.

**Comment by johno1985** [comment] 2018-02-21 16:08
@whimboo how will GeckoDriver know to look for the nightly version of firefox as opposed to the version already installed?

**Comment by andreastt** [comment] 2018-02-21 16:12
geckodriver doesn’t know how to look for Firefox Nightly on your machine. You can examine the code for finding Firefox in https://searchfox.org/mozilla-central/rev/47cb352984bac15c476dcd75f8360f902673cb98/testing/mozbase/rust/mozrunner/src/runner.rs#307-409.

To select Nightly you need to use [`moz:firefoxOptions` as documented in the README](https://github.com/mozilla/geckodriver#mozfirefoxoptions). Your client maybe has a wrapper for this, but the final JSON input should look something like `{"moz:firefoxOptions": {"bin": "/path/to/nightly"}}`.

**Comment by johno1985** [comment] 2018-02-21 18:28
OK, so I need to set the following capability JSON:

{
	"capabilities": {
		"alwaysMatch": {
			"moz:firefoxOptions": {
				"binary": "~/Downloads/target/firefox/firefox.exe",
				"log": {
					"level": "trace"
				}
			}
		}
	}
}

But I don't know how to set these capabilities. Do I set them via the
command line, in the maven pom or in my Selenium test code?

Kind regards,

Jonathan

**Comment by andreastt** [comment] 2018-02-21 19:12
That JSON body looks correct. I don’t know how to set them in your language. Did you not find it in 
https://searchfox.org/mozilla-central/source/testing/geckodriver/doc/TraceLogs.md that I linked?

**Comment by johno1985** [comment] 2018-02-21 19:17
Ah, I see, thanks. I was looking at this file -
https://searchfox.org/mozilla-central/source/testing/geckodriver/README.md
so couldn't see any examples.

**Comment by cgoldberg** [comment] 2018-02-21 19:22
to specify firefox location from selenium java client:

```
FirefoxOptions options = new FirefoxOptions();
options.setBinary('/path/to/firefox');
WebDriver driver = new FirefoxDriver(options);
```

**Comment by johno1985** [comment] 2018-02-21 22:04
Hi @whimboo, it appears that running my tests against the nightly build seems to have resolved the issue

[new 3.txt](https://github.com/mozilla/geckodriver/files/1745883/new.3.txt)

**Comment by johno1985** [comment] 2018-02-21 23:54
@whimboo is there an ETA on the next release?

**Comment by lepik1108** [comment] 2018-02-22 08:48
@whimboo, @johno1985 thanks guys. Nightly build works fine.

**Comment by whimboo** [comment] 2018-02-22 16:43
@johno1985, hm ok. Can you also please test the latest beta release of Firefox 59? You can find it here: https://www.mozilla.org/en-US/firefox/channel/desktop/#beta. Is it also fixed for this version?

**Comment by lepik1108** [comment] 2018-02-22 17:30
Reprodused in latest beta release of Firefox 59.

[gecko_log_ff_beta.txt](https://github.com/mozilla/geckodriver/files/1748882/gecko_log_ff_beta.txt)

**Comment by whimboo** [comment] 2018-02-23 10:05
@lepik1108 I see the following in the log, so I doubt that the 59 beta release is used?

> 2018/02/22 17:28:29 Using default version: 58.0
> 2018/02/22 17:28:29 [2] [USING_DRIVER] [firefox-58.0]

**Comment by lepik1108** [comment] 2018-02-23 17:22
@whimboo this lines left from my selenoid browser settings. I changed binary path for Firefox firefox beta 59 in capabilities, so it run needed version.

**Comment by whimboo** [comment] 2018-02-26 09:45
So it seems that the problem is still there in 59 beta. At least for @lepik1108. From @johno1985 we haven't got a reply yet.

Please note that Firefox Nightly has some specific preferences set which only are active for those builds. As such it could always be that it is working fine, while other builds are not. Most likely it is related to the sandbox preference (`security.sandbox.content.level`). You should play around with lower levels, and maybe set `security.sandbox.logging.enabled` to `true` for more logging output.

**Comment by lepik1108** [comment] 2018-02-26 16:02
Tried out all possible values for `security.sandbox.content.level`. Firefox Nightly works well on both.
Firefox Beta doesn't work. Looks like this preference is not related with issue.

**Comment by whimboo** [comment] 2018-02-27 09:09
@johno1985 can you please try the following. Try to keep the used Firefox profile around. geckodriver usually deletes it. Maybe use a custom one. Inside the profile there is a `minidump` folder, which should contain files. Please zip those up and send them to me. I can then have a look what kind of crash it is. Thanks.

**Comment by lepik1108** [comment] 2018-02-27 09:58
[minidumps.zip](https://github.com/mozilla/geckodriver/files/1762100/minidumps.zip)

**Comment by johno1985** [comment] 2018-02-27 17:07
Hi @whimboo I'm not sure how to keep the profile, please can you advise?

**Comment by lepik1108** [comment] 2018-02-27 18:22
@johno1985, looks like profile deletes on session close. You can insert sleep(300) (for Java -  Thread.sleep(300000); or TimeUnit.MINUTES.sleep(5);) in your test's sourcecode, this will give you 5 minutes to copy `minidump` folder from profile (C:\Users\ADMINI~1\AppData\Local\Temp\rust_mozprofile.************).

**Comment by johno1985** [comment] 2018-02-27 19:49
@lepik1108 I'm not sure why but there were 3 profiles, so I've attached all
three minidump files. Also, it appears that the rust profiles do not get
deleted when the tests finish.

**Comment by johno1985** [comment] 2018-02-28 19:01
@lepik1108 apologies, my last comment was posted by email and I just noticed that the files I attached to the email did not get attached to the comment, please find the files below
[minidumps.zip](https://github.com/mozilla/geckodriver/files/1768460/minidumps.zip)
[minidumps2.zip](https://github.com/mozilla/geckodriver/files/1768461/minidumps2.zip)
[minidumps3.zip](https://github.com/mozilla/geckodriver/files/1768462/minidumps3.zip)

**Comment by whimboo** [comment] 2018-03-07 20:14
@lepik1108 thank you for the minidump files! So your crashes look like https://crash-stats.mozilla.com/report/index/c6ba08c5-b815-41dd-823b-4c22a0180307#tab-details. Which means that you see https://bugzilla.mozilla.org/show_bug.cgi?id=1400637. Check if you have some external software running which might influence Firefox.

**Comment by whimboo** [comment] 2018-03-07 20:20
@johno1985 you have the exact same crash reason as I mentioned in my last comment.

**Comment by lepik1108** [comment] 2018-03-07 22:15
@whimboo I'm using vagrant box with Windows10 guest, so i have no software except Windows Defender which might influence Firefox and I'm sure I've disabled Windows Defender.
Problem reproduces only when I running geckodriver with Firefox58 or Firefox59 using Powershell's "Start-Process" in my provision file.

**Comment by johno1985** [comment] 2018-03-08 16:46
Hi @whimboo, I'm not aware of any external software that might be influencing Firefox. I had a look at the link to the Mozilla ticket that you sent me and it looks like WebRoot was mentioned several times, but we do not have WebRoot installed on our Jenkins VMWare virtual machine. I did however, set the "security.sandbox.content.level" to 5 and that seemed to fix the problem. I don't understand why this fixes the problem as I'm not familiar with Firefox/Geckodriver architecture/inner workings. I also do not understand why using the nightly build worked but the beta build did not work.

**Comment by whimboo** [comment] 2018-03-09 09:24
@johno1985 that is good to hear. So mind answering me some more questions for clarification? It might help us to reproduce and fix the crash. So feedback would be kinda welcoming.

1) How often do you see the crash for your tests?
2) Are you using headless mode of Firefox?
3) Are you running the tests with a full desktop or as Windows task or service?
4) Do all versions of Firefox fail to start up to the latest Firefox 59.0 beta?
5) Is there any other kind of additional software installed for the Windows VMs?
6) Do you see the same crash for Firefox when using a 32bit version of the Firefox installer?
7) When setting the sandbox level, which versions of Firefox do not crash anymore?
8) Are any sandbox levels below 5 cause the crash?

Thanks.

**Comment by whimboo** [comment] 2018-03-09 16:17
Ok, some updates here. As it looks like this crash should be fixed with the upcoming Firefox 60.0 beta release, and is already fixed on Nightly. The reason is that Firefox were processing native events in the content processes. This has been turned off on Windows with the preference `dom.ipc.useNativeEventProcessing.content` set to `false`.

@johno1985 and @lepik1108 can you both please try to run Nightly with the preferences turned on? Does this crash in that case, and doesn't crash with the pref turned off?

**Comment by whimboo** [comment] 2018-03-09 16:19
Well, it's actually a dupe of issue #1134. Please respond over there. Thanks.

**Comment by lepik1108** [comment] 2018-03-09 16:43
@whimboo Nightly works fine with both values of `dom.ipc.useNativeEventProcessing.content`.
[dom.ipc.useNativeEventProcessing.content_false.txt](https://github.com/mozilla/geckodriver/files/1797633/dom.ipc.useNativeEventProcessing.content_false.txt)
[dom.ipc.useNativeEventProcessing.content_true.txt](https://github.com/mozilla/geckodriver/files/1797634/dom.ipc.useNativeEventProcessing.content_true.txt)

**Comment by lepik1108** [comment] 2018-03-09 17:21
> 1. How often do you see the crash for your tests?
Every time I run tests.
> 2. Are you using headless mode of Firefox?
No, executable installers were downloaded from https://www.mozilla.org or installed as chocolately package.
> 3. Are you running the tests with a full desktop or as Windows task or service?
I use firefox as remote browser in tests and tests runs Firefox over geckodriver, which work as Windows Background Task.
> 4. Do all versions of Firefox fail to start up to the latest Firefox 59.0 beta?
I used just versions 58 and above. And Firefox 58 and 59 fails to start up.
> 5. Is there any other kind of additional software installed for the Windows VMs?
No.
> 6. Do you see the same crash for Firefox when using a 32bit version of the Firefox installer?
Yes, I've tried out Firefox 58 32bit and got the same crash.
> 7. When setting the sandbox level, which versions of Firefox do not crash anymore?
Setting sandbox level value from 0 to 5 on Firefox58 or Firefox59 and getting crash.
Setting sandbox level value from 0 to 5 on Firefox60 and browser works fine.
> 8. Are any sandbox levels below 5 cause the crash?
Looks like sandbox levels does not affect the crash

**Comment by whimboo** [comment] 2018-03-12 17:00
Thanks @lepik1108. It's helpful. @johno1985 mind also having a look at my questions and reply to them? Especially if you are running the tests as Windows task or as service. Thanks.

**Comment by johno1985** [comment] 2018-03-13 20:56
Hi @whimboo here are my answers:

**How often do you see the crash for your tests?**
Every time
**Are you using headless mode of Firefox?**
No
**Are you running the tests with a full desktop or as Windows task or service?**
I think they run as a task as they are executed by Jenkins
**Do all versions of Firefox fail to start up to the latest Firefox 59.0 beta?**
Yes, but the nightly build worked fine
**Is there any other kind of additional software installed for the Windows VMs?**
Apart from the Jenkins server and Log Me In client, nothing comes to mind
**Do you see the same crash for Firefox when using a 32bit version of the Firefox installer?**
I haven't tried the 32bit installer
**When setting the sandbox level, which versions of Firefox do not crash anymore?**
All of them
**Are any sandbox levels below 5 cause the crash?**
All levels except for level 5 cause the crash

**Comment by whimboo** [comment] 2018-03-26 09:15
Thank you both @lepik1108 and @johno1985 for your answers. Now that 60 is available as beta version can you both please try the latest beta release: https://www.mozilla.org/en-US/firefox/channel/desktop/#beta

**Comment by whimboo** [comment] 2018-05-03 20:27
Good to hear. Marking as dupe of issue #1134.

**Closed by whimboo** 2018-05-03 20:27 UTC
Labels: duplicate, firefox
