### ISSUE TITLE
sendkeys not working in selenium 3.4

### ISSUE THREAD

**Issue by hmkmnv** [mozilla/geckodriver#819] opened 2017-07-11 20:44 UTC
In order to help us efficiently investigate your issue, please provide the following information:

## Platform and application details
* Platform< Windows10 -->
* Firefox: < 54.0.1 --(64bit)>
* Selenium: < 3.4 + java1.8u -->

## Steps to reproduce
<!--SendKeys not working in selenium3.4>
 package seleniumjar;

import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;

public class SeljarClass {

	public static void main(String[] args) {
		// TODO Auto-generated method stu
System.setProperty("webdriver.gecko.driver", "C:\\Program Files\\Java\\geckodriver.exe");

 WebDriver driver = new FirefoxDriver();
 
 
 driver.get("https://www.google.nl/?gfe_rd=cr&ei=PjBlWanEIO2A8Qflr4Ao");
 driver.findElement(By.id("lst-ib")).sendKeys("display google search");
}
}
- [#  error-499804017301	Marionette	WARN	Deprecated preference marionette.defaultPrefs.enabled detected, please use marionette.enabled
[GPU 12580] WARNING: pipe error: 109: file c:/builds/moz2_slave/m-rel-w64-00000000000000000000/build/src/ipc/chromium/src/chrome/common/ipc_channel_win.cc, line 346
1499804022993	Marionette	INFO	Listening on port 59338
1499804023619	Marionette	DEBUG	loaded listener.js
Jul 11, 2017 10:13:43 PM org.openqa.selenium.remote.ProtocolHandshake createSession
INFO: Detected dialect: W3C
1499804023811	Marionette	DEBUG	Received DOM event "beforeunload" for "about:blank"
1499804024083	Marionette	DEBUG	Received DOM event "pagehide" for "about:blank"
1499804024085	Marionette	DEBUG	Received DOM event "unload" for "about:blank"
1499804024421	Marionette	DEBUG	Received DOM event "DOMContentLoaded" for "https://www.google.nl/?gfe_rd=cr&ei=PjBlWanEIO2A8Qflr4Ao"
1499804025285	Marionette	DEBUG	Received DOM event "pageshow" for "https://www.google.nl/?gfe_rd=cr&ei=PjBlWanEIO2A8Qflr4Ao"
Exception in thread "main" org.openqa.selenium.InvalidArgumentException: Expected [object Undefined] undefined to be a string
Build info: version: 'unknown', revision: 'unknown', time: 'unknown'
System info: host: 'DESKTOP-EA120B8', ip: '192.168.178.11', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_131'
Driver info: org.openqa.selenium.firefox.FirefoxDriver
Capabilities [{moz:profile=C:\Users\achi838\AppData\Local\Temp\rust_mozprofile.bdA8LJ4HG9nv, rotatable=false, timeouts={implicit=0.0, pageLoad=300000.0, script=30000.0}, pageLoadStrategy=normal, platform=ANY, specificationLevel=0.0, moz:accessibilityChecks=false, acceptInsecureCerts=false, browserVersion=54.0.1, platformVersion=10.0, moz:processID=11612.0, browserName=firefox, javascriptEnabled=true, platformName=windows_nt}]
Session ID: a18b49a7-76ca-42ee-afe2-0b98b70b808e
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
	at java.lang.reflect.Constructor.newInstance(Unknown Source)
	at org.openqa.selenium.remote.http.W3CHttpResponseCodec.createException(W3CHttpResponseCodec.java:150)
	at org.openqa.selenium.remote.http.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:115)
	at org.openqa.selenium.remote.http.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:45)
	at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:164)
	at org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:82)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:637)
	at org.openqa.selenium.remote.RemoteWebElement.execute(RemoteWebElement.java:272)
	at org.openqa.selenium.remote.RemoteWebElement.sendKeys(RemoteWebElement.java:96)
	at seleniumjar.SeljarClass.main(SeljarClass.java:18)

-

**Comment by pilfro** [comment] 2017-07-12 13:46
I'm seeing this issue in Windows 7- No errors, test just completes. 
ChromeDriver 2.30.0.1
Selenium 3.4
C#
string bfirstname = DateTime.Now + "Billy";

wait.Until(ExpectedConditions.ElementToBeClickable(By.Id("BFirstName")));
driver.FindElement(By.Id("BFirstName")).Click();
SendKeys.SendWait(bfirstname);

(not a developer- BA trying to learn a little to be more useful)

**Comment by whimboo** [comment] 2017-07-22 11:47
What is `SendWait` actually doing here? This looks something specific for the C# binding.

Also please provide a trace level log as requested by default when creating a new issue. Thanks.

**Comment by AutomatedTester** [comment] 2017-07-24 15:04
from https://github.com/mozilla/geckodriver/issues/819#issuecomment-314774122 it looks like a chromedriver issue. There is also no actionable steps to reproduce so closing.

**Closed by AutomatedTester** 2017-07-24 15:04 UTC
