### ISSUE TITLE
Wrong exception from missing window

### ISSUE THREAD

**Issue by titusfortner** [mozilla/geckodriver#1770] opened 2020-08-27 04:50 UTC
Note - it is possible it's the same root cause as #1769 but I'll post full details of my investigation here:

## System

* Version: geckodriver 0.27.0 (7b8c4f32cdde 2020-07-28 18:16 +0000)
* Platform: macOS 10.15.5 (19F101)
* Firefox: 79.0 (64-bit)
* Selenium: 3.142.7 (Ruby)

## Testcase
This is a race condition of some kind.

Note that [this spec](https://github.com/watir/watir/blob/master/spec/watirspec/window_switching_spec.rb#L308)
 in the Watir repo reproduces it very well because the server is on the local machine with short and exact js timings.

This test case I created below uses a public URL with larger js timings and is therefore is inconsistent in failing
```
    require 'selenium-webdriver'

    Selenium::WebDriver.logger.level = :debug
    options = Selenium::WebDriver::Firefox::Options.new(log_level: :trace)
    driver = Selenium::WebDriver.for :firefox, options: options

    driver.get "http://watir.com/examples/window_switching.html"
    original_window = driver.window_handle

    driver.find_element(id: 'open').click
    sleep 1
    new_window = driver.window_handles.reject { |wh| wh == original_window }.first
    driver.switch_to.window(new_window)
    driver.find_element(id: 'close-delay').click

    driver.switch_to.window(original_window) {
      sleep 4.965
    }
```

## Stack Trace & Trace log

https://gist.github.com/titusfortner/a5fd85ffc5e086d97c4a6bf5507b32f7

**Comment by whimboo** [comment] 2020-08-27 05:23
So you are actually using Firefox 80.0 and not 79.0 as described above. I will have a look today, and I assume that this will be fixed with my upcoming patches for https://bugzilla.mozilla.org/show_bug.cgi?id=1493108.

**Comment by titusfortner** [comment] 2020-08-27 05:38
I got the error with 79, and started this bug report. In the process of recording the version it updated. Then I re-ran the test with a better reproducible test case. :)

**Comment by titusfortner** [comment] 2020-08-27 05:39
oh, and I didn't notice the other ticket was specifically 81+ so I guess not related, we just both happened to find window-related issues.

**Comment by whimboo** [comment] 2020-08-27 09:16
So what is the actual expected result vs. failure here? I tried to replicate with the Python bindings but I don't know what I have to look out for. Maybe the second sleep is wrongly placed?

```
def test_usercase(driver):
    original_window = driver.current_window_handle

    driver.get("http://watir.com/examples/window_switching.html")
    driver.find_element_by_id('open').click()
    time.sleep(1)

    handles = driver.window_handles
    new_window = filter(lambda h: h != original_window, handles)[0]
    driver.switch_to.window(new_window)

    driver.find_element_by_id('close-delay').click()
    time.sleep(4)
    driver.switch_to.window(original_window)
    time.sleep(10)
```

After 4s it correctly switches to the original window, and then a second later the newly opened tab gets closed due to the delay.

**Comment by whimboo** [comment] 2020-08-27 09:19
The only change which seem to be related here and which landed in 79 is https://bugzilla.mozilla.org/show_bug.cgi?id=1519335. But I would need the details to know what I have to look out for.

**Comment by whimboo** [comment] 2020-08-27 20:54
Actually I missed the trace log. :/ Here are the details:

```
1598503621569	Marionette	DEBUG	0 <- [1,14,{"error":"unknown error","message":"TypeError: this.mm is null","stacktrace":"WebElementEventTarget@chrome://marionette/content/dom.js:46:5\nswitchToTab@chrome://marionette/content/browser.js:525:26\n"},null]
Marionette threw an error: TypeError: this.mm is null
WebElementEventTarget@chrome://marionette/content/dom.js:46:5
switchToTab@chrome://marionette/content/browser.js:525:26
```

Could you please test if the failure is also present in this [Nightly build of Firefox 80](https://archive.mozilla.org/pub/firefox/nightly/2020/07/2020-07-14-21-47-02-mozilla-central/firefox-80.0a1.en-US.mac.dmg)?

**Comment by titusfortner** [comment] 2020-08-27 22:21
@whimboo I'm getting this error now:
```
Selenium::WebDriver::Error::UnknownError: TypeError: can't access property "addMessageListener", this.mm is null
     # WebElementEventTarget@chrome://marionette/content/dom.js:46:5
     # switchToTab@chrome://marionette/content/browser.js:505:26
```

I added the full trace/logs: https://gist.github.com/titusfortner/a5fd85ffc5e086d97c4a6bf5507b32f7#file-firefox_window_switching_bug_80_0a1-txt

Note that this new run is not the public intermittently-reproducible example but the completely reproducible test from the Watir suite.

**Comment by whimboo** [comment] 2020-08-31 08:11
Maybe my latest finding on https://bugzilla.mozilla.org/show_bug.cgi?id=1661495#c11 could explain that. It actually shows the regression with Firefox 80. I should have a patch later today for testing.

**Comment by whimboo** [comment] 2020-08-31 15:56
@titusfortner how does https://firefox-ci-tc.services.mozilla.com/api/queue/v1/task/Mn9AB66TQn6383MrTZ5GzA/runs/0/artifacts/public/build/target.dmg work for you? It's a Firefox 82 Nightly build. Thanks.

**Comment by whimboo** [comment] 2020-09-07 12:22
I finally had a chance to catch this problem. It's very timing dependent, and as such interesting to see that the Watir tests can hit it that frequently. I filed https://bugzilla.mozilla.org/show_bug.cgi?id=1663429 to get it fixed.

**Comment by whimboo** [comment] 2020-09-07 12:22
Also note that this isn't a new issue but already exists for a while...

**Comment by whimboo** [comment] 2020-09-07 14:13
@titusfortner can you please check this test build of Firefox Nightly if it fixes the problem for you? I cannot reproduce the failure anymore with Watir.

https://firefox-ci-tc.services.mozilla.com/api/queue/v1/task/eC8kILV7TwaVPmF0ySLMaQ/runs/0/artifacts/public/build/target.dmg

Thanks

**Comment by whimboo** [comment] 2020-09-08 06:51
This will be fixed in the next Firefox Nightly build.

**Closed by whimboo** 2020-09-08 06:51 UTC
Labels: awaiting reporter feedback

**Comment by titusfortner** [comment] 2020-09-08 07:14
Sorry, I've been out of town most of the past couple weeks. I haven't run the Watir tests for a while, so it isn't super surprising that it isn't something new. Thanks for fixing it!
