### ISSUE TITLE
Selenium 3.12 shows an error on driver.quit() @ FireFox 60 / Win 7 Home Premium / Java 10.0.1 / GeckoDriver 0.20.1

### ISSUE THREAD

**Issue by JoeStoner** [mozilla/geckodriver#1272] opened 2018-05-15 09:11 UTC
## System

* Version: 0.20.1 / 64 Bit
* Platform: Win 7 / 64 Bit - all updates installed
* Firefox: 60.0 / 64 Bit
* Selenium: 3.12

## Testcase / JAVA-Sourcecode:

public class SeleniumFireFoxMinimal1 {                                                             
    public static void main(String[] args) throws InterruptedException {                           
        System.setProperty("webdriver.gecko.driver", "e:\\geckodriverwrapper.bat");                       
        WebDriver driver = new FirefoxDriver();                 
        driver.get("http://www.toolsqa.com");                                                      
        driver.quit();                                                                             
    }                                                                                              
}

## Stacktrace / Eclipse 4.7.3a Console Output:

Starting geckodriver: E:\geckodriverwrapper.bat --port=27751 -b "C:\Program Files (x86)\Mozilla Firefox\firefox.exe"
Mai 12, 2018 1:14:15 VORM. org.openqa.selenium.remote.ProtocolHandshake createSession
INFORMATION: Detected dialect: W3C

THE FOLLOWING LINES ARE SHOWN 15 SECONDS AFTER THE FIREFOX-WINDOW IS CLOSED:
============================================================================

Mai 12, 2018 1:14:37 VORM. org.openqa.selenium.os.OsProcess destroy
INFORMATION: Unable to drain process streams. Ignoring but the exception being swallowed follows.
org.apache.commons.exec.ExecuteException: The stop timeout of 2000 ms was exceeded (Exit value: -559038737)
    at org.apache.commons.exec.PumpStreamHandler.stopThread(PumpStreamHandler.java:295)
    at org.apache.commons.exec.PumpStreamHandler.stop(PumpStreamHandler.java:181)
    at org.openqa.selenium.os.OsProcess.destroy(OsProcess.java:135)
    at org.openqa.selenium.os.CommandLine.destroy(CommandLine.java:153)
    at org.openqa.selenium.remote.service.DriverService.stop(DriverService.java:222)
    at org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:95)
    at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:543)
    at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:600)
    at org.openqa.selenium.remote.RemoteWebDriver.quit(RemoteWebDriver.java:443)
    at at.xxxxxxxx.work.SeleniumFireFoxMinimal1.main(SeleniumFireFoxMinimal1.java:40)

Mai 12, 2018 1:14:37 VORM. org.openqa.selenium.os.OsProcess destroy
SCHWERWIEGEND: Unable to kill process Process[pid=4320, exitValue=1]

## geckodriverwrapper.bat:                                                                                                  

@ECHO OFF
ECHO Starting geckodriver: %0 %*
E:\geckodriver.exe --log trace %* > NUL 2>&1

## Other Selenium commands like these work perfectly well:

element = driver.findElement(By.id("sinp"));              
element.clear();                                                
element.sendKeys("black");                                      
element.submit();                                                                                                                                                           

## More info:

Is this just a problem on my PC ?                                                                                                     
 
driver.quit() is working on my InternetExplorer without a problem. 

My entry @ Stackoverflow.com:

https://stackoverflow.com/questions/50305819/selenium-3-12-shows-an-error-on-driver-quit-firefox-60-win-7-home-premium

.
Do you have a hint for me please?

Thanks a lot in advance.

**Comment by whimboo** [comment] 2018-05-15 09:32
There is nothing we can do without a trace log. Please create one and attach it here. By default Selenium should write it as geckodriver.log in the current working directory when you let it start geckodriver. 

So far I could only imagine that this might be related to https://bugzilla.mozilla.org/show_bug.cgi?id=1443520.

**Comment by JoeStoner** [comment] 2018-05-15 10:57
**Here is my tracelog:**

1526381530185	geckodriver	INFO	geckodriver 0.20.1
1526381530196	geckodriver	INFO	Listening on 127.0.0.1:41869
1526381531034	mozrunner::runner	INFO	Running command: "C:\\Program Files (x86)\\Mozilla Firefox\\firefox.exe" "-marionette" "-profile" "C:\\Users\\xxxxxxxxx\\AppData\\Local\\Temp\\rust_mozprofile.1XQepc1XK2mM"
1526381531039	geckodriver::marionette	DEBUG	Waiting 60s to connect to browser
1526381532147	Marionette	DEBUG	Received observer notification profile-after-change
1526381532677	Marionette	DEBUG	Received observer notification command-line-startup
1526381532678	Marionette	DEBUG	Received observer notification nsPref:changed
1526381535693	Marionette	DEBUG	Received observer notification sessionstore-windows-restored
1526381535879	Marionette	DEBUG	Setting recommended pref toolkit.cosmeticAnimations.enabled to false
1526381535879	Marionette	DEBUG	Setting recommended pref datareporting.policy.dataSubmissionPolicyAccepted to false
1526381535879	Marionette	DEBUG	Setting recommended pref extensions.shield-recipe-client.api_url to 
1526381536169	Marionette	DEBUG	New connections are accepted
1526381536169	Marionette	INFO	Listening on port 49219
1526381536398	geckodriver::marionette	DEBUG	Connected to Marionette on localhost:49219
1526381536416	Marionette	DEBUG	Accepted connection 0 from 127.0.0.1:49236
1526381536416	geckodriver::marionette	TRACE	<- {"applicationType":"gecko","marionetteProtocol":3}
1526381536417	geckodriver::marionette	TRACE	-> 163:[0,1,"newSession",{"acceptInsecureCerts":true,"browserName":"firefox","capabilities":{"desiredCapabilities":{"acceptInsecureCerts":true,"browserName":"firefox"}}}]
1526381536609	Marionette	TRACE	0 -> [0,1,"newSession",{"acceptInsecureCerts":true,"browserName":"firefox","capabilities":{"desiredCapabilities":{"acceptInsecureCerts":true,"browserName":"firefox"}}}]
1526381536610	Marionette	WARN	TLS certificate errors will be ignored for this session
1526381536800	Marionette	DEBUG	Register listener.js for window 4294967297
1526381536808	Marionette	TRACE	0 <- [1,1,null,{"sessionId":"b031f595-48fc-4fa6-9316-a218730b6ea9","capabilities":{"browserName":"firefox","browserVersion":"60.0" ... AppData\\Local\\Temp\\rust_mozprofile.1XQepc1XK2mM","moz:useNonSpecCompliantPointerOrigin":false,"moz:webdriverClick":true}}]
1526381536809	geckodriver::marionette	TRACE	<- [1,1,null,{"sessionId":"b031f595-48fc-4fa6-9316-a218730b6ea9","capabilities":{"browserName":"firefox","browserVersion":"60.0","platformName":"windows_nt","platformVersion":"6.1","pageLoadStrategy":"normal","acceptInsecureCerts":true,"timeouts":{"implicit":0,"pageLoad":300000,"script":30000},"rotatable":false,"moz:accessibilityChecks":false,"moz:headless":false,"moz:processID":4640,"moz:profile":"C:\\Users\\xxxxxxxxx\\AppData\\Local\\Temp\\rust_mozprofile.1XQepc1XK2mM","moz:useNonSpecCompliantPointerOrigin":false,"moz:webdriverClick":true}}]
1526381536810	webdriver::server	DEBUG	<- 200 OK {"value": {"sessionId":"b031f595-48fc-4fa6-9316-a218730b6ea9","capabilities":{"acceptInsecureCerts":true,"browserName":"firefox","browserVersion":"60.0","moz:accessibilityChecks":false,"moz:headless":false,"moz:processID":4640,"moz:profile":"C:\\Users\\xxxxxxxxx\\AppData\\Local\\Temp\\rust_mozprofile.1XQepc1XK2mM","moz:useNonSpecCompliantPointerOrigin":false,"moz:webdriverClick":true,"pageLoadStrategy":"normal","platformName":"windows_nt","platformVersion":"6.1","rotatable":false,"timeouts":{"implicit":0,"pageLoad":300000,"script":30000}}}}
Mai 15, 2018 12:52:16 NACHM. org.openqa.selenium.remote.ProtocolHandshake createSession
INFORMATION: Detected dialect: W3C
1526381537074	webdriver::server	DEBUG	-> POST /session/b031f595-48fc-4fa6-9316-a218730b6ea9/url {"url":"http://www.toolsqa.com"}
1526381537074	geckodriver::marionette	TRACE	-> 44:[0,2,"get",{"url":"http://www.toolsqa.com"}]
1526381537225	Marionette	TRACE	0 -> [0,2,"get",{"url":"http://www.toolsqa.com"}]
1526381537248	Marionette	DEBUG	Received DOM event beforeunload for about:blank
1526381538848	Marionette	DEBUG	Received DOM event pagehide for about:blank
1526381543902	Marionette	DEBUG	Received DOM event DOMContentLoaded for http://toolsqa.com/
1526381548266	Marionette	DEBUG	Received DOM event pageshow for http://toolsqa.com/
1526381548267	Marionette	TRACE	0 <- [1,2,null,{}]
1526381548268	geckodriver::marionette	TRACE	<- [1,2,null,{}]
1526381548268	webdriver::server	DEBUG	<- 200 OK {"value": {}}
1526381548276	webdriver::server	DEBUG	-> DELETE /session/b031f595-48fc-4fa6-9316-a218730b6ea9 
1526381548278	geckodriver::marionette	TRACE	-> 37:[0,3,"quit",{"flags":["eForceQuit"]}]
1526381548280	Marionette	TRACE	0 -> [0,3,"quit",{"flags":["eForceQuit"]}]
1526381548280	Marionette	DEBUG	New connections will no longer be accepted
1526381548592	Marionette	TRACE	0 <- [1,3,null,{"cause":"shutdown"}]
1526381548617	geckodriver::marionette	TRACE	<- [1,3,null,{"cause":"shutdown"}]
1526381548692	webdriver::server	DEBUG	Deleting session
1526381548692	geckodriver::marionette	TRACE	-> 37:[0,4,"quit",{"flags":["eForceQuit"]}]
Unable to read VR Path Registry from C:\Users\xxxxxxxxx\AppData\Local\openvr\openvrpaths.vrpath
[Child 4484, Chrome_ChildThread] WARNING: pipe error: 109: file z:/build/build/src/ipc/chromium/src/chrome/common/ipc_channel_win.cc, line 346
[Child 4484, Chrome_ChildThread] WARNING: pipe error: 109: file z:/build/build/src/ipc/chromium/src/chrome/common/ipc_channel_win.cc, line 346
1526381548736	Marionette	TRACE	0 -> [0,4,"quit",{"flags":["eForceQuit"]}]
1526381548737	Marionette	TRACE	0 <- [1,4,{"error":"invalid session id","message":"","stacktrace":"WebDriverError@chrome://marionette/content/error.js:178:5\nInva ... et@chrome://marionette/content/server.js:241:8\n_onJSONObjectReady/<@chrome://marionette/content/transport.js:500:9\n"},null]
1526381548749	Marionette	DEBUG	Closed connection 0
Unable to read VR Path Registry from C:\Users\xxxxxxxxx\AppData\Local\openvr\openvrpaths.vrpath
[Child 4260, Chrome_ChildThread] WARNING: pipe error: 109: file z:/build/build/src/ipc/chromium/src/chrome/common/ipc_channel_win.cc, line 346
[Child 4260, Chrome_ChildThread] WARNING: pipe error: 109: file z:/build/build/src/ipc/chromium/src/chrome/common/ipc_channel_win.cc, line 346
Unable to read VR Path Registry from C:\Users\xxxxxxxxx\AppData\Local\openvr\openvrpaths.vrpath
[Parent 4640, Gecko_IOThread] WARNING: pipe error: 109: file z:/build/build/src/ipc/chromium/src/chrome/common/ipc_channel_win.cc, line 346
Unable to read VR Path Registry from C:\Users\xxxxxxxxx\AppData\Local\openvr\openvrpaths.vrpath
[Child 4020, Chrome_ChildThread] WARNING: pipe error: 109: file z:/build/build/src/ipc/chromium/src/chrome/common/ipc_channel_win.cc, line 346
*** UTM:SVC TimerManager:registerTimer called after profile-before-change notification. Ignoring timer registration for id: telemetry_modules_ping
1526381554199	Marionette	DEBUG	Received observer notification xpcom-will-shutdown
1526381554199	Marionette	DEBUG	Resetting recommended pref toolkit.cosmeticAnimations.enabled
1526381554200	Marionette	DEBUG	Resetting recommended pref datareporting.policy.dataSubmissionPolicyAccepted
1526381554200	Marionette	DEBUG	Resetting recommended pref extensions.shield-recipe-client.api_url
Unable to read VR Path Registry from C:\Users\xxxxxxxxx\AppData\Local\openvr\openvrpaths.vrpath
[GPU 5300, Chrome_ChildThread] WARNING: pipe error: 109: file z:/build/build/src/ipc/chromium/src/chrome/common/ipc_channel_win.cc, line 346

###!!! [Child][MessageChannel::SendAndWait] Error: (msgtype=0x4A0006,name=PImageBridge::Msg_WillClose) Channel error: cannot send/recv

1526381554733	geckodriver::marionette	DEBUG	Browser process stopped with exit status exit code: 0
1526381555043	webdriver::server	DEBUG	<- 200 OK {"value": {}}

**Comment by whimboo** [comment] 2018-05-15 14:47
So yes, it's a duplicate of issue #1235.

**Closed by whimboo** 2018-05-15 14:47 UTC
Labels: waiting for reporter feedback
