### ISSUE TITLE
no stdio handle error

### ISSUE THREAD

**Issue by titusfortner** [mozilla/geckodriver#48] opened 2016-02-29 02:49 UTC
@AutomatedTester, I'm not sure if this is a wires issue, a Marionette issue or a Ruby ChildProcess issue. It is only a problem on Windows; Linux & Mac work fine.

```
-> POST session
   >>> http://127.0.0.1:4444/session | {"desiredCapabilities":{"browserName":"firefox","browserVersion":null,"platformName":null,"platformVersion":"any","acceptSslCerts":false,"takesScreenshot":false,"takesElementScreenshot":false,"pageLoadStrategy":"normal","marionette":true}}
<- {"error":"unknown error","message":"no stdio handle available for this process"}
```

I'm not sure why, but I don't get this error if I set `@process.io.inherit!` on the ChildProcess instance that executes wires. While this works, it also fills stdout with all of the marionette debug information, so if I can figure out a better way to solve this, that would be great.

@p0deje - I'm not very familiar with I/O or ChildProcess class; the server_command array sent to `ChildProcess#build` is: 
`["C:\drivers/wires.exe", "--binary=c:\firefoxes\beta\App\Firefox\firefox.exe", "--webdriver-port=4444"]`
Do you have any idea what the issue might be, or should I see if Jari has insight?

**Comment by p0deje** [comment] 2016-02-29 07:41
I'm pretty sure that is because of [this](https://github.com/jgraham/rust_mozrunner/blob/master/src/runner.rs#L60). Since there are not stdio handlers we use for process, try to inherit them throws an error. When you add `@process.io.inherit!`, process get stdio and everything works fine.

I believe wires/mozrunner should not depend on stdio, even though we can work this around by passing some fake ones.

**Comment by jgraham** [comment] 2016-02-29 15:59
I can remove those lines, but since we call `spawn` on the command, I think it will inherit the stdio from the parent process anyway [1], so I don't think it's going to allow you to run without any stdio. But if I am wrong about this please let me know.

[1] http://doc.rust-lang.org/std/process/struct.Command.html#method.spawn

**Comment by jgraham** [comment] 2016-02-29 17:06
I can remove those lines, but since we call `spawn` on the command, I think it will inherit the stdio from the parent process anyway [1], so I don't think it's going to allow you to run without any stdio. But if I am wrong about this please let me know.

[1] http://doc.rust-lang.org/std/process/struct.Command.html#method.spawn

**Comment by titusfortner** [comment] 2016-02-29 18:13
It works fine on Linux & Mac, but again, I'm not familiar enough to know the difference between OS. @p0deje can we set something up in the Se code that doesn't require actual stdout output (unless $DEBUG is actually set)?

**Comment by p0deje** [comment] 2016-03-01 08:50
On Linux & Mac this works correctly because ChildProcess [reopens](https://github.com/jarib/childprocess/blob/d9986577c64d4fd8dfcd4fdd595c9369332cb170/lib/childprocess/unix/fork_exec_process.rb#L32-L33) stdio for `/dev/null`, while nothing like this happens in [Windows implementation](https://github.com/jarib/childprocess/blob/d9986577c64d4fd8dfcd4fdd595c9369332cb170/lib/childprocess/windows/process_builder.rb#L104).

I guess there are few options to resolve this:

1. Report an issue to ChildProcess to try and reopen stdio to `File::NULL`.
2. Wires can explicitly define its own stdio if it can't be inherited.
3. selenium-webdriver gem can pass its own stdio.

I think the first option is preferred, but I cannot really test it now (or at least provide and test to reproduce for bug in ChildProcess). Something went completely wrong with my Windows VM and I can't start wires anyway.

**Comment by p0deje** [comment] 2016-03-13 06:59
@titusfortner Can you try to apply this patch and see if it workarounds the problem (without messing with output):

```diff
diff --git a/rb/lib/selenium/webdriver/firefox/service.rb b/rb/lib/selenium/webdriver/firefox/service.rb
index dfbb53b..025be23 100644
--- a/rb/lib/selenium/webdriver/firefox/service.rb
+++ b/rb/lib/selenium/webdriver/firefox/service.rb
@@ -95,7 +95,13 @@ module Selenium
           server_command = [@executable_path, "--binary=#{Firefox::Binary.path}", "--webdriver-port=#{@port}", *@extra_args]
           @process       = ChildProcess.build(*server_command)

-          @process.io.inherit! if $DEBUG || Platform.os == :windows
+          if $DEBUG
+            @process.io.inherit!
+          elsif Platform.windows?
+            # workaround for https://github.com/jgraham/wires/issues/48
+            @process.io.stdout = @process.io.stderr = File.new(Platform.null_device, 'w')
+          end
+
           @process.start
         end
```

**Comment by jgraham** [comment] 2016-06-28 15:08
Did you fix this on the ruby side?

**Comment by p0deje** [comment] 2016-06-28 15:10
It is worked around in
https://github.com/SeleniumHQ/selenium/blob/master/rb/lib/selenium/webdriver/firefox/service.rb#L39
On Вт, 28 июня 2016 г. at 21:08, jgraham <notifications@github.com> wrote:

> Did you fix this on the ruby side?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/mozilla/geckodriver/issues/48#issuecomment-229078938>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AAoo9kpTY-AXZyU8m1psZXs5hzqmf9UOks5qQTjXgaJpZM4HlDA1>
> .
>
-- 
Alex

**Comment by kdmurthy** [comment] 2016-12-04 05:51
I am facing an issue on OSX Sierra with JRuby. When $DEBUG is set to true, it works - otherwise I get the following error:


```
irb(main):002:0> d = Selenium::WebDriver.for :ff
Selenium::WebDriver::Error::WebDriverError: unexpected response, code=500, content-type=""
	from /Users/dakshinamurthykarra/Projects/marathonitev4/marathonv4/marathon-core/ruby-selenium-webdriver/src/main/resources/gems/selenium-webdriver-3.0.3/lib/selenium/webdriver/remote/http/common.rb:88:in `create_response'
	from /Users/dakshinamurthykarra/Projects/marathonitev4/marathonv4/marathon-core/ruby-selenium-webdriver/src/main/resources/gems/selenium-webdriver-3.0.3/lib/selenium/webdriver/remote/http/default.rb:86:in `request'
	from /Users/dakshinamurthykarra/Projects/marathonitev4/marathonv4/marathon-core/ruby-selenium-webdriver/src/main/resources/gems/selenium-webdriver-3.0.3/lib/selenium/webdriver/remote/http/common.rb:59:in `call'
	from /Users/dakshinamurthykarra/Projects/marathonitev4/marathonv4/marathon-core/ruby-selenium-webdriver/src/main/resources/gems/selenium-webdriver-3.0.3/lib/selenium/webdriver/remote/w3c_bridge.rb:640:in `raw_execute'
	from /Users/dakshinamurthykarra/Projects/marathonitev4/marathonv4/marathon-core/ruby-selenium-webdriver/src/main/resources/gems/selenium-webdriver-3.0.3/lib/selenium/webdriver/remote/w3c_bridge.rb:114:in `create_session'
	from /Users/dakshinamurthykarra/Projects/marathonitev4/marathonv4/marathon-core/ruby-selenium-webdriver/src/main/resources/gems/selenium-webdriver-3.0.3/lib/selenium/webdriver/remote/w3c_bridge.rb:69:in `initialize'
	from /Users/dakshinamurthykarra/Projects/marathonitev4/marathonv4/marathon-core/ruby-selenium-webdriver/src/main/resources/gems/selenium-webdriver-3.0.3/lib/selenium/webdriver/firefox/w3c_bridge.rb:35:in `initialize'
	from /Users/dakshinamurthykarra/Projects/marathonitev4/marathonv4/marathon-core/ruby-selenium-webdriver/src/main/resources/gems/selenium-webdriver-3.0.3/lib/selenium/webdriver/common/driver.rb:52:in `for'
	from /Users/dakshinamurthykarra/Projects/marathonitev4/marathonv4/marathon-core/ruby-selenium-webdriver/src/main/resources/gems/selenium-webdriver-3.0.3/lib/selenium/webdriver.rb:82:in `for'
	from (irb):2:in `<eval>'
	from org/jruby/RubyKernel.java:998:in `eval'
	from org/jruby/RubyKernel.java:1299:in `loop'
	from org/jruby/RubyKernel.java:1118:in `catch'
	from org/jruby/RubyKernel.java:1118:in `catch'
	from uri:classloader:/META-INF/jruby.home/bin/jirb:13:in `<main>'

```

**Comment by andreastt** [comment] 2017-01-04 01:41
Closing this as it is an issue in Selenium.

**Closed by andreastt** 2017-01-04 01:41 UTC
