### ISSUE TITLE
Memory leak in Marionette commands that call the frame script

### ISSUE THREAD

**Issue by aplicacionamedida** [mozilla/geckodriver#181] opened 2016-08-15 11:00 UTC
I am using geckodriver in windows 8. There is a memory leak using this driver because the memory used is contantly increasing.  I am using selenium to create spiders and I am navigating to several websites for extracting data. For example, now the memory used is more than 1700 MB, and it doesnt stop.

**Comment by jgraham** [comment] 2016-08-15 11:46
Memory usage of which process? geckodriver or Firefox itself?

**Comment by aplicacionamedida** [comment] 2016-08-15 12:59
Firefox process. I was using firefox 47.1

**Comment by aplicacionamedida** [comment] 2016-08-15 16:06
I have just discovered that if I use this other request, it works:
 GET
http://127.0.0.1:51881/session/87e2fede-7be4-47b8-b6de-027639a63723/element/7498fc31-9e44-4197-91a3-1a50a0cded39/property/textContent

I am not sure whether this is a bug or whether the semantics of this RESTFUL method changed

**Comment by andreastt** [comment] 2016-08-17 11:37
This could be related to [bug 1272653](https://bugzilla.mozilla.org/show_bug.cgi?id=1272653), which made _Get Element Attribute_ spec compatible.

Using `/session/{session id}/property/textContent` as you mention is the correct command to call for returning _properties_ in WebDriver, but calling `/session/{session id}/attribute/textContent` should not cause memory leak issues.

**Comment by aplicacionamedida** [comment] 2016-08-18 19:35
mmmm.... I think that they are different problems. I don't know exactly the origin of this memory leak. But I suppose that it's affected by the interaction with geckodriver.

**Comment by andreastt** [comment] 2016-08-19 17:45
I can see the pattern you describe by calling _Get URL_ (or `GET /session/{session id}/url`) many, in this case 100,000, times:

![Get URL](https://sny.no/2016/08/geturl.png)

Interestingly I can’t seem to reproduce this if the browser/tab is reloaded, for example by navigating to another webpage. I suspect this is because the Marionette frame script is removed and added again.

![Navigate](https://sny.no/2016/08/navigate.png)

This is some initial and very crude measurements of the virtual memory size (VSZ) of the Firefox process. I don’t exactly know where to proceed from here. How exactly does one debug memory leak problems in chrome JS?

**Comment by andreastt** [comment] 2016-08-19 18:08
I notice that the memory consumption does not increase if the command called does not call down to the frame script ([_testing/marionette/listener.js_](https://github.com/mozilla/gecko-dev/blob/master/testing/marionette/listener.js)). Since the listener [makes a call to a web platform API](https://github.com/mozilla/gecko-dev/blob/master/testing/marionette/listener.js#L1078), this could indicate the problem lies with the IPC and message handling stuff we do in [testing/marionette/proxy.js](https://github.com/mozilla/gecko-dev/blob/master/testing/marionette/proxy.js).

**Comment by DanielPettersson** [comment] 2016-10-20 10:20
I also experience memory leaks using geckodriver. But for me the process leaking memory is "Plugin Container For Firefox" plugin-container.exe. After maybe a thousand page loads, and a lot of called commands used memory was about 3500mb. And performance of selenium tests became very bad.

**Comment by aplicacionamedida** [comment] 2016-11-15 22:53
Hi, I am using Linux Mint 18 MATE 32-bit, firefox 49 and geckodriver v0.11.1, and I continue with the memory leak.

**Comment by whimboo** [comment] 2016-11-17 09:53
@andreastt best is to use a debug build of Firefox for leak measurement. It will automatically print out statistics via the gecko log in some intervals. I'm aware of that in some cases we get a message like "you are leaking the world" with lots of remaining references to websites / urls. So I could believe that this issue might be the same thing. I would propose to reopen [bug 1317823](https://bugzilla.mozilla.org/show_bug.cgi?id=1317823) for further investigation.

**Comment by dionysiose** [comment] 2018-09-13 11:32
Using geckodriver 0.21.0 and Firefox 60.0.2 and observe huge memory increase which eventually makes the process Firefox to blow up. Any suggestions how to further investigate this issue?

**Comment by whimboo** [comment] 2018-09-13 13:57
@dionysiose your question doesn't provide any information. Please show some code, trace log, or graphs which show what you are doing and how memory usage is growing.

**Comment by JanVomlel** [comment] 2019-05-24 10:37
I have similar problem:

## System

* Version: v0.24.0-win64
* Platform: Windows 10
* Firefox: 60.7.0esr
* Selenium: 3.141.59

## Testcase
This simple code causes firefox consume more and more memory. That is why our long running tests crashe.

    package cz.aipsafe.safe.test.www.tests;

    import org.openqa.selenium.By;
    import org.openqa.selenium.WebDriver;
    import org.openqa.selenium.firefox.FirefoxDriver;
    import org.testng.annotations.Test;

    public class RepeatSimpleTest {
        @Test
        public void repeat() {
            System.setProperty("webdriver.gecko.driver", "....\\gecko-driver-64\\geckodriver.exe");
            WebDriver driver = new FirefoxDriver();
            while(true) {
                driver.get("https://google.com");
                driver.findElements(By.xpath("//body"));
            }
        }
    }

Without findElements, firefox memory is increasing too, but after some time, when it has about 1GB, it is decreasing back to 200MB. With findElements firefox memory is increasing more and more, when it had 3GB I stopped the test.

Workarround is to close driver and firefox window during long tests.

**Comment by zeit200** [comment] 2019-05-25 14:20
The same happens on Firefox 67.0 when simply navigating to a page with a lot of elements:

## System
* Version: v0.24.0-win64
* Platform: Windows 10
* Firefox: 67.0
* Selenium: 3.141.0

## Testcase
```
using OpenQA.Selenium.Firefox;

namespace Test
{
    public class Launcher
    {
        public static int Main()
        {
            var webDriver = new FirefoxDriver(@"..\geckodriver", new FirefoxOptions() { BrowserExecutableLocation = @"..\firefox\firefox.exe" });
            while (true) webDriver.Navigate().GoToUrl("https://forum.xda-developers.com/");
        }
    }
}
```

**Comment by Tschipp** [comment] 2019-12-02 22:32
This seems to still be a problem, not even by loading the page over and over again but even just by making calls to the JavascriptExecutor of the website.

**Comment by mk2016a** [comment] 2020-02-28 04:07
This problem solved by using Chrome instead.

**Comment by Tschipp** [comment] 2020-02-28 10:44
Using Chrome is sadly not a solution with my system.

**Comment by mk2016a** [comment] 2020-03-03 18:55
Try diver.quit(). 
chrome has same problem as well.

**Comment by whimboo** [comment] 2020-03-03 20:36
@Tschipp would you mind running your test with Firefox Nightly and creating a gecko profile for us? Therefore set the environment variables `MOZ_PROFILER_STARTUP` and `MOZ_PROFILER_SHUTDOWN`, and upload the generated profile JSON file to https://profiler.firefox.com/. Please publish and share the profile here. Thanks.

See more at https://developer.mozilla.org/en-US/docs/Mozilla/Performance/Profiling_with_the_Built-in_Profiler#Profiling_Firefox_Startup.

**Comment by whimboo** [comment] 2020-11-16 20:22
So this leak should have been [fixed with the upcoming Firefox 84 beta](https://bugzilla.mozilla.org/show_bug.cgi?id=1669169), which is about to be released soon. Can you all please check again, if you see an improvement when running your specific test cases? 

If you still see problems please let me know by supplying a minimized test to run. I would appreciate.

Thanks!

**Comment by Tschipp** [comment] 2020-11-17 08:27
This is great news, I will try this as soon as I get the time to test.

**Comment by whimboo** [comment] 2020-11-25 13:24
Was anyone able to check that? If not I'm going to close this issue by early next week. Thanks.

**Comment by whimboo** [comment] 2020-12-02 09:26
Closing as fixed. If you notice other memory leaking behavior please file a new issue. Thanks.

**Closed by whimboo** 2020-12-02 09:26 UTC
Labels: marionette
