### ISSUE TITLE
Geckodriver 0.19.0 fails to close correctly

### ISSUE THREAD

**Issue by mikevika** [mozilla/geckodriver#956] opened 2017-09-18 15:18 UTC
## System
* Version: 19.0
* Platform: windows 10
* Firefox: 55.03
* Selenium: 3.53

This happens for all test cases at the end of a test run

## Stacktrace

Sep 18, 2017 11:06:23 AM org.openqa.selenium.os.UnixProcess destroy
SEVERE: Unable to kill process with PID 12476

## Trace-level log

this error is due to improper closure of fire fox through driver.close. It was supposedly fixed in version 14.0 of the geckodriver and is now back

**Comment by andreastt** [comment] 2017-09-18 15:20
Impossible to tell why this is without a trace-level log.

**Comment by 600rob** [comment] 2017-09-19 14:55
This looks like the same issue i reported in #961

**Comment by andreastt** [comment] 2017-09-19 15:22
True. I’m still waiting for a trace-level geckodriver log. It also looks like you are both using Firefox 55, and it would be helpful if you tried reproducing it with Firefox Nightly (57).

**Comment by 600rob** [comment] 2017-09-19 20:30
Hi Andreas, if you could point me in the direction of how i can get the trace level gecko driver log i will gladly post it for you (sorry, im new to all this but happy to learn)
Thanks rob

**Comment by andreastt** [comment] 2017-09-19 21:05
This information is in the README. The gist is that you either need to pass `{"moz:firefoxOptions": {"log": {"level": "trace"}}}` as a capability, or use the `-vv` flag when starting geckodriver.

**Comment by wx7614140** [comment] 2017-09-20 01:30
hi andreastt, here are some trace log. It looks like the 'shutdown' command is gone  
  
1505870690830	webdriver::server	DEBUG	-> DELETE /session/33a8470f-400f-4517-8d96-27fd660cc01b 
1505870690830	geckodriver::marionette	TRACE	-> 37:[0,6,"quit",{"flags":["eForceQuit"]}]
1505870690828	Marionette	TRACE	0 -> [0,6,"quit",{"flags":["eForceQuit"]}]
1505870690829	Marionette	INFO	New connections will no longer be accepted
1505870690895	Marionette	TRACE	0 <- [1,6,null,{"cause":"shutdown"}]
1505870690914	geckodriver::marionette	TRACE	<- [1,6,null,{"cause":"shutdown"}]
1505870690915	webdriver::server	DEBUG	Deleting session
1505870690915	geckodriver::marionette	DEBUG	Stopping browser process
1505870691193	webdriver::server	DEBUG	<- 200 OK {"value": {}}
1505870691234	webdriver::server	DEBUG	-> GET /shutdown 
1505870691235	webdriver::server	DEBUG	<- 404 Not Found {"value":{"error":"unknown command","message":"GET /shutdown did not match a known command","stacktrace":"stack backtrace:\n   0:   0x4e6bd4 - <no info>\n   1:   0x43e83c - <no info>\n   2:   0x438a45 - <no info>\n   3:   0x404310 - <no info>\n   4:   0x40bf30 - <no info>\n   5:   0x69d92b - <no info>\n   6:   0x42061e - <no info>\n   7:   0x6989e1 - <no info>\n   8: 0x7547338a - BaseThreadInitThunk\n   9: 0x7793a242 - RtlInitializeExceptionChain"}}

**Comment by wx7614140** [comment] 2017-09-20 06:18
And I started a server with ./geckodriver -b "/usr/bin/firefox" in centos7 ,  
visit http://127.0.0.1:4444/ and got some logs  
{"value":{"error":"unknown command","message":"GET / did not match a known command","stacktrace":"stack backtrace:\n   0:           0x5787ed - backtrace::backtrace::trace::h59229d13f6a8837d\n   1:           0x578942 - backtrace::capture::Backtrace::new::h23089c033eded8f0\n   2:           0x4463cc - webdriver::error::WebDriverError::new::hd11f864b1fdf4510\n   3:           0x438eb8 - <webdriver::server::HttpHandler<U> as hyper::server::Handler>::handle::hd20f6e9e0a69e2b4\n   4:           0x42c9af - hyper::server::listener::spawn_with::{{closure}}::h8fa3cf343f537777\n   5:           0x4092d7 - std::panicking::try::do_call::h649be53a713433eb\n   6:           0x5dc20a - panic_unwind::__rust_maybe_catch_panic\n                        at /checkout/src/libpanic_unwind/lib.rs:98\n   7:           0x41c43e - <F as alloc::boxed::FnBox<A>>::call_box::hf41feb3b2b67541e\n   8:           0x5d48a4 - alloc::boxed::{{impl}}::call_once<(),()>\n                        at /checkout/src/liballoc/boxed.rs:650\n                         - std::sys_common::thread::start_thread\n                        at /checkout/src/libstd/sys_common/thread.rs:21\n                         - std::sys::imp::thread::{{impl}}::new::thread_start\n                        at /checkout/src/libstd/sys/unix/thread.rs:84"}}

**Comment by whimboo** [comment] 2017-09-22 11:24
Sadly this issue misses any test code, and more context around the failing lines from the trace log. Maybe this is a dupe of issue #957?

**Comment by 600rob** [comment] 2017-09-22 11:32
Hi whimbo, i posted the code i was attempting to run when experiencing the issue in my original ticket #961.

here it is again:
```
@Test
public void startWebDriver(){




    WebDriver driver = new MarionetteDriver();
    driver.navigate().to("http://seleniumsimplified.com");

    Assert.assertTrue("title should start differently",
            driver.getTitle().startsWith("Selenium Simplified"));

    driver.close();
    driver.quit();
	}
	
}

```


Let me know if you require any further info

**Comment by whimboo** [comment] 2017-09-22 11:35
@600rob your problem is issue #957. So your issue was wrongly duped here.

I keep this open for feedback from @mikevika.

**Comment by 600rob** [comment] 2017-09-22 14:32
@whimboo many thanks for your help

**Comment by whimboo** [comment] 2017-09-26 07:09
Closing issue given no response from the reporter has been received within a week.

**Closed by whimboo** 2017-09-26 07:09 UTC
Labels: waiting for reporter feedback
