### ISSUE TITLE
Missing support for user prompt handler

### ISSUE THREAD

**Issue by DOlllDb** [mozilla/geckodriver#990] opened 2017-10-03 14:03 UTC
## System
* Version: 0.19 (win x64)
* Platform: Windows 7 x64
* Firefox: 56.0 (x64)
* Selenium: 3.5.3

## Testcase

    public static void main(String[] args) {
        DesiredCapabilities caps = DesiredCapabilities.firefox();
        caps.setCapability(CapabilityType.UNEXPECTED_ALERT_BEHAVIOUR, UnexpectedAlertBehaviour.IGNORE);
        WebDriver driver = new FirefoxDriver(caps);
        driver.get("http://google.com/");
}

## Stacktrace

1507038362271 geckodriver       INFO     geckodriver 0.19.0
1507038362271 geckodriver       INFO     Listening on 127.0.0.1:15816
Exception in thread "main" org.openqa.selenium.InvalidArgumentException: ignore was not a valid unhandledPromptBehavior value
Build info: version: '3.5.3', revision: 'a88d25fe6b', time: '2017-08-29T12:42:44.417Z'
System info: host: …, ip: …, os.name: 'Windows 7', os.arch: 'amd64', os.version: '6.1', java.version: '1.8.0_92'
Driver info: driver.version: FirefoxDriver
remote stacktrace: stack backtrace:
   0:           0x4821c4 - <no info>
   1:           0x482933 - <no info>
   2:           0x47a13a - <no info>
   3:           0x46dbc3 - <no info>
   4:           0x405822 - <no info>
   5:           0x445d06 - <no info>
   6:           0x43026a - <no info>
   7:           0x40ba4e - <no info>
   8:           0x4119b9 - <no info>
   9:           0x6d2c89 - <no info>
  10:           0x426006 - <no info>
  11:           0x6cd490 - <no info>
  12:         0x773d59cd - BaseThreadInitThunk
                at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
                at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
                at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
                at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
                at org.openqa.selenium.remote.W3CHandshakeResponse.lambda$new$0(W3CHandshakeResponse.java:57)
                at org.openqa.selenium.remote.W3CHandshakeResponse.lambda$getResponseFunction$2(W3CHandshakeResponse.java:104)
                at org.openqa.selenium.remote.ProtocolHandshake.lambda$createSession$24(ProtocolHandshake.java:359)
                at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
                at java.util.Spliterators$ArraySpliterator.tryAdvance(Spliterators.java:958)
                at java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:126)
                at java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:498)
                at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:485)
                at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
                at java.util.stream.FindOps$FindOp.evaluateSequential(FindOps.java:152)
                at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
                at java.util.stream.ReferencePipeline.findFirst(ReferencePipeline.java:464)
                at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:362)
                at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:136)
                at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:142)
                at org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:82)
                at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:646)
                at org.openqa.selenium.remote.RemoteWebDriver.startSession(RemoteWebDriver.java:255)
                at org.openqa.selenium.remote.RemoteWebDriver.startSession(RemoteWebDriver.java:237)
                at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:138)
                at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:191)
                at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:103)
                at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:137)
                at ru.sbt.qa.nikelman.selenium.TestSelenium.createDriver(TestSelenium.java:69)
                at ru.sbt.qa.nikelman.selenium.TestSelenium.main(TestSelenium.java:34)

**Comment by DOlllDb** [comment] 2017-10-03 15:03
Additional info: also tried setting up like this:
DesiredCapabilities caps = new DesiredCapabilities();
caps  = new FirefoxOptions().setUnhandledPromptBehavior(UnexpectedAlertBehavior.IGNORE).addTo(caps);
WebDriver drv = new FirefoxDriver(caps);

Got exactly the same result;

**Comment by andreastt** [comment] 2017-10-03 16:12
geckodriver does not support the user prompt handler yet.

**Comment by andreastt** [comment] 2017-10-03 16:13
We can leave this open for tracking. The Marionette bug is https://bugzilla.mozilla.org/show_bug.cgi?id=1264259.

**Comment by whimboo** [comment] 2017-10-05 18:41
Basically a dupe of issue #617.

**Closed by whimboo** 2017-10-05 18:41 UTC
Labels: marionette
