### ISSUE TITLE
Net::ReadTimeout while trying to download file by opening direct link

### ISSUE THREAD

**Issue by ShockwaveNN** [mozilla/geckodriver#1301] opened 2018-06-19 09:41 UTC
## System

* Version: geckodriver-v0.21.0-linux64
* Platform: Kubunut 18.04 x64
* Firefox: 60.0.2
* Selenium: Ruby 2.5 + 'selenium-webdriver' '3.12.0'

## Testcase
```
require 'selenium-webdriver'

profile = Selenium::WebDriver::Firefox::Profile.new
profile['browser.download.folderList'] = 2
profile['browser.helperApps.neverAsk.saveToDisk'] = 'application/vnd.openxmlformats-officedocument.wordprocessingml.document'
profile['browser.download.dir'] = '/tmp'
Selenium::WebDriver.logger.level = :debug
options = Selenium::WebDriver::Firefox::Options.new(profile: profile, log_level: :trace)
driver = Selenium::WebDriver.for :firefox, driver_path: '/tmp/geckodriver-v0.21.0-linux64/geckodriver', options: options

driver.navigate.to('https://s3.us-west-2.amazonaws.com/nct-data-share/docx/0+(1).docx')
driver.quit
```

## Stacktrace

File downloaded successfully, no "File Download" window is shown as intended, but next step is failed with 
```
Uncaught exception: Net::ReadTimeout
	/home/ubuntuuser/.rvm/rubies/ruby-2.5.1/lib/ruby/2.5.0/net/protocol.rb:181:in `rbuf_fill'
	/home/ubuntuuser/.rvm/rubies/ruby-2.5.1/lib/ruby/2.5.0/net/protocol.rb:157:in `readuntil'
	/home/ubuntuuser/.rvm/rubies/ruby-2.5.1/lib/ruby/2.5.0/net/protocol.rb:167:in `readline'
	/home/ubuntuuser/.rvm/rubies/ruby-2.5.1/lib/ruby/2.5.0/net/http/response.rb:40:in `read_status_line'
	/home/ubuntuuser/.rvm/rubies/ruby-2.5.1/lib/ruby/2.5.0/net/http/response.rb:29:in `read_new'
	/home/ubuntuuser/.rvm/rubies/ruby-2.5.1/lib/ruby/2.5.0/net/http.rb:1494:in `block in transport_request'
	/home/ubuntuuser/.rvm/rubies/ruby-2.5.1/lib/ruby/2.5.0/net/http.rb:1491:in `catch'
	/home/ubuntuuser/.rvm/rubies/ruby-2.5.1/lib/ruby/2.5.0/net/http.rb:1491:in `transport_request'
	/home/ubuntuuser/.rvm/rubies/ruby-2.5.1/lib/ruby/2.5.0/net/http.rb:1464:in `request'
	/home/ubuntuuser/.rvm/rubies/ruby-2.5.1/lib/ruby/2.5.0/net/http.rb:1457:in `block in request'
	/home/ubuntuuser/.rvm/rubies/ruby-2.5.1/lib/ruby/2.5.0/net/http.rb:910:in `start'
	/home/ubuntuuser/.rvm/rubies/ruby-2.5.1/lib/ruby/2.5.0/net/http.rb:1455:in `request'
	/home/ubuntuuser/.rvm/gems/ruby-2.5.1/gems/selenium-webdriver-3.12.0/lib/selenium/webdriver/remote/http/default.rb:121:in `response_for'
	/home/ubuntuuser/.rvm/gems/ruby-2.5.1/gems/selenium-webdriver-3.12.0/lib/selenium/webdriver/remote/http/default.rb:76:in `request'
	/home/ubuntuuser/.rvm/gems/ruby-2.5.1/gems/selenium-webdriver-3.12.0/lib/selenium/webdriver/remote/http/common.rb:62:in `call'
	/home/ubuntuuser/.rvm/gems/ruby-2.5.1/gems/selenium-webdriver-3.12.0/lib/selenium/webdriver/remote/bridge.rb:164:in `execute'
	/home/ubuntuuser/.rvm/gems/ruby-2.5.1/gems/selenium-webdriver-3.12.0/lib/selenium/webdriver/remote/w3c/bridge.rb:535:in `execute'
	/home/ubuntuuser/.rvm/gems/ruby-2.5.1/gems/selenium-webdriver-3.12.0/lib/selenium/webdriver/remote/w3c/bridge.rb:57:in `get'
	/home/ubuntuuser/.rvm/gems/ruby-2.5.1/gems/selenium-webdriver-3.12.0/lib/selenium/webdriver/common/navigation.rb:30:in `to'
	/home/ubuntuuser/sources/onlyoffice_webdriver_wrapper/test.rb:11:in `<top (required)>'
```

## Trace-level log
Attached as file
[trace.log](https://github.com/mozilla/geckodriver/files/2114687/trace.log)

**Comment by whimboo** [comment] 2018-06-19 14:32
This is a dupe of issue #1065.

**Closed by whimboo** 2018-06-19 14:32 UTC

**Comment by ShockwaveNN** [comment] 2018-06-19 14:44
@whimboo Sorry for bother you, I saw this bug before posting this and seems there is currently no workaround for this problem? I tried different ways to perform download direct link and it just don't work (bug work great in Chrome).
Maybe this problem should be escalated? I think it's pretty common scenario in testing web to download direct links.

**Comment by whimboo** [comment] 2018-06-26 10:09
No, it's not a common scenario that people use Selenium to check if download links are correct. That's why it also has no priority at the moment. Sorry. 

If you have to download files use whatever Ruby provides you for HTTP(s) connections.

**Comment by ShockwaveNN** [comment] 2018-06-26 10:11
@whimboo ok I will, thanks for idea, forgot about Ruby http download :)
