### ISSUE TITLE
unhandledPromptBehavior capability is not honored

### ISSUE THREAD

**Issue by barancev** [mozilla/geckodriver#617] opened 2017-04-07 21:33 UTC
## Firefox Version
55.0a1 (2017-04-06) (64-bit)
geckodriver 0.15

## Platform
Windows 7

## Steps to reproduce
Try to set this capability and execute any command while an alert is opened. It's expected that the alert will be automatically accepted or dismissed, but it does not happen.

**Comment by andreastt** [comment] 2017-04-07 21:38
Thanks for the bug report. `unhandledPromptBehavior` and the unhandled prompt handler isn’t implemented in Marionette at all.

**Comment by whimboo** [comment] 2017-04-12 11:49
The bug Andreas is referring to here is https://bugzilla.mozilla.org/show_bug.cgi?id=1279211.

**Comment by bswhb** [comment] 2017-04-28 04:10
@andreastt Is there a plan `unhandledPromptBehavior` will be implemented so that the JS alert handling will be the same as legacy Firefox? As for now, if a JS alert prompted, geckodriver will depress it without throwing an `UnhandledAlertException` as before.

**Comment by whimboo** [comment] 2017-04-28 08:41
@bswhb with [bug 1359004](https://bugzilla.mozilla.org/show_bug.cgi?id=1359004) being fixed 2 days ago for Firefox Nightly we at least return the Error now. For closing it automatically we would still have to work on the bug I mentioned before.

**Comment by schmidtkp** [comment] 2017-05-03 13:58
I have similar if not same issue if I set

`capabilities.setCapability(CapabilityType.UNEXPECTED_ALERT_BEHAVIOUR, UnexpectedAlertBehaviour.IGNORE);
`

This will produce

`org.openqa.selenium.InvalidArgumentException: unhandledPromptBehavior was not a the name of a known capability or a valid extension capability`

**Comment by andreastt** [comment] 2017-05-03 14:56
As I say in https://github.com/mozilla/geckodriver/issues/617#issuecomment-292658271, the `unhandledPromptBehavior` capability has not been implemented yet. You can track the work on this in https://bugzilla.mozilla.org/show_bug.cgi?id=1264259.

**Comment by Yash-777** [comment] 2017-09-21 14:02
I am facing the same problem, when i migrate the code to use GeckoDriver.

Java:
```
String firefoxVersion = "55", FF_DriverPack = "v0.19.0";
capabilities.setCapability(CapabilityType.UNEXPECTED_ALERT_BEHAVIOUR, UnexpectedAlertBehaviour.IGNORE);
```

Exception:

```
Exception in thread "main" org.openqa.selenium.InvalidArgumentException: 
	ignore was not a valid unhandledPromptBehavior value
Build info: version: '3.5.1', revision: '9c21bb67ef', time: '2017-08-17T15:26:08.955Z'
System info: os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_144'
```

**Comment by Yash-777** [comment] 2017-09-21 14:02
I am facing the same problem, when I migrate the code to use GeckoDriver.

Java:
```
String firefoxVersion = "55", FF_DriverPack = "v0.19.0";
capabilities.setCapability(CapabilityType.UNEXPECTED_ALERT_BEHAVIOUR, 
                                          UnexpectedAlertBehaviour.IGNORE);
```

Exception:
```
Exception in thread "main" org.openqa.selenium.InvalidArgumentException: 
	ignore was not a valid unhandledPromptBehavior value
Build info: version: '3.5.1', revision: '9c21bb67ef', time: '2017-08-17T15:26:08.955Z'
System info: os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_144'
```

**Comment by codingphil** [comment] 2018-03-19 10:58
It seems that with Firefox 59 the default behavior changed from `ignore` to `dismiss`.

When specifying the capability `CapabilityType.UNEXPECTED_ALERT_BEHAVIOUR` still there is an `org.openqa.selenium.InvalidArgumentException` exception thrown.

Our scripts depend on the `ignore` behavior so it would be important to have the `UNEXPECTED_ALERT_BEHAVIOUR` capability.

**Comment by andreastt** [comment] 2018-03-19 11:10
Yes, keen observation @codingphil. We changed Firefox to match the default behaviour of IEDriver in 59.

Unfortunately we do still not support implement the user prompt handler and the `unhandledPromptBehavior` capability.

**Comment by rahmansa2010** [comment] 2018-05-22 13:32
Is there any expected date to get UNEXPECTED_ALERT_BEHAVIOUR supported by Firefox Capabilities or by Firefox Options? Thanks.

**Comment by chamara-madusanka** [comment] 2018-05-30 11:53
Could you please provide a way to set UNEXPECTED_ALERT_BEHAVIOUR capability as **ignore**.

Caused by: org.openqa.selenium.InvalidArgumentException: ignore was not a valid unhandledPromptBehavior value.

**Comment by sajithatharaka** [comment] 2018-05-30 12:01
Tried setting capabilities, but it didn't work. Can you please provide some suggestions to ignore closing the alerts when unhandled exception is thrown?
Thanks

**Comment by saluk** [comment] 2018-06-12 21:22
Dismiss is poor default behavior for testing purposes. Target site requires me to accept an alert to complete an operation - dismiss cancels said operation. This is going to be the most common pattern for confirm() dialogs. While dismiss might be acceptable for alert(), where dismiss and accept would have similar results, it boggles my mind why this was chosen as the default for confirm() dialogs as well. 

Really, it should go back to ignore as the default setting. The user should be forced to choose whether to confirm or cancel the operation. 

IEDriver should have matched Firefox, not the other way around.

Besides my opinions on what the default values should be, enabling setting of the behavior would at least provide a workaround. (Chrome seems to still be using "ignore" as the default behavior on all prompts)

**Comment by whimboo** [comment] 2018-06-13 22:31
I'm currently working on the implementation of `unhandledPromptBehavior` support. Please note that before we can add it in Firefox/Marionette, a new geckodriver release is necessary which will include https://bugzilla.mozilla.org/show_bug.cgi?id=1468185. Soon this is out it shouldn't take that long to have it available in Firefox Nightly.

**Comment by kovalev007** [comment] 2018-08-18 14:52
1) I take geckodriver-v0.21.0-win64.zip (rel note - The unhandledPromptBehavior capability now accepts accept and notify, dismiss and notify, and ignore options.)
and firefox nightly 63.0a1 (2018-08-18) (64-bit) (https://bugzilla.mozilla.org/show_bug.cgi?id=1264259 should already include in this release?)
and try following code on java (selenium 3.14.0):
FirefoxOptions options = new FirefoxOptions();
options.setUnhandledPromptBehaviour(UnexpectedAlertBehaviour.IGNORE)
options.setCapability(CapabilityType.UNEXPECTED_ALERT_BEHAVIOUR, UnexpectedAlertBehaviour.IGNORE);
options.setCapability(CapabilityType.UNHANDLED_PROMPT_BEHAVIOUR, UnexpectedAlertBehaviour.IGNORE);
or
options.setUnhandledPromptBehaviour(UnexpectedAlertBehaviour.DISMISS_AND_NOTIFY);
options.setCapability(CapabilityType.UNEXPECTED_ALERT_BEHAVIOUR, UnexpectedAlertBehaviour.DISMISS_AND_NOTIFY);
options.setCapability(CapabilityType.UNHANDLED_PROMPT_BEHAVIOUR, UnexpectedAlertBehaviour.DISMISS_AND_NOTIFY);

but it is not working. Firefox close alert silently.

**Comment by whimboo** [comment] 2018-08-22 10:00
Sorry I forgot to close this issue given that this capability is now available starting with Firefox 63 which is currently the Nightly build.  We are not going to uplift this to Firefox 62, so it will ride the trains. If you need this capability you will have to make use of the Nightly build.

**Closed by whimboo** 2018-08-22 10:00 UTC
Labels: geckodriver, marionette

**Comment by kovalev007** [comment] 2018-08-22 13:31
It is not working for me. geckodriver-v0.21.0-win64.zip and firefox nightly 63.0a1 (2018-08-18) (64-bit).
See previous comment.

**Comment by whimboo** [comment] 2018-08-22 20:07
@kovalev007 I'm sure the capability isn't correctly passed to geckodriver. Please attach a trace log so we can verify that. See https://firefox-source-docs.mozilla.org/testing/geckodriver/geckodriver/TraceLogs.html in how to do that.

**Comment by kovalev007** [comment] 2018-08-23 04:41
I investigated my problem.
It is related with onbeforeunload event.
In our web application there is window.onbeforeunload with promt when user close window.

When I start firefox manually and open about:config and search dom.disable_beforeunload
dom.disable_beforeunload = false in firefox 61, 62 beta and 63 nightly.
it is value by default.

But when I run test with geckodriver 0.21.0 and firefox 63 nightly
and open about:config
dom.disable_beforeunload = true
it is changed value.

Why dom.disable_beforeunload is changed?

If I write
FirefoxProfile profile = new FirefoxProfile();
profile.setPreference("dom.disable_beforeunload", false);
all will be working correctly.

**Comment by kovalev007** [comment] 2018-08-23 05:30
Additional info:
geckodriver 0.21.0 and firefox 60 = working correctly = dom.disable_beforeunload = false
geckodriver 0.21.0 and firefox 61 = working not correctly = dom.disable_beforeunload = true
geckodriver 0.21.0 and firefox 62beta = working not correctly = dom.disable_beforeunload = true
geckodriver 0.21.0 and firefox 63nightly = working not correctly = dom.disable_beforeunload = true

**Comment by whimboo** [comment] 2018-08-23 10:41
Please see https://w3c.github.io/webdriver/#user-prompts. As the WebDriver spec says:
> User prompts that are spawned from beforeunload event handlers, are dismissed implicitly upon navigation or close window, regardless of the defined user prompt handler.

So if there is a problem with that file a WebDriver spec issue. But given that our implementation is spec compliant, there is nothing wrong with geckodriver here.

**Comment by kovalev007** [comment] 2018-08-23 11:47
Is mistake there in w3c spec?

Usual users (which open firefox by hand) should interact with promt of onbeforeunload event.
dom.disable_beforeunload = false by default in firefox.

But in automated test with geckodriver we have different behavior.
dom.disable_beforeunload = true

May be behaviour from automated test should be same as usual users?
