### ISSUE TITLE
Window does not resize if the width has the same value

### ISSUE THREAD

**Issue by kalumpiwarra** [mozilla/geckodriver#873] opened 2017-08-15 12:31 UTC
## System
* Version: 0.18.0
* Platform: WINDOWS 10
* Firefox: 55.0.1
* Selenium: 3.4.0

## Testcase

```
public class TestResize {
    @Test(description = "Check FF 55 resize issue")
    public void checkResizeIssue() throws MalformedURLException {
        FirefoxOptions opts = new FirefoxOptions().setLogLevel(Level.ALL);
        DesiredCapabilities capabilities = DesiredCapabilities.firefox();
        WebDriver driver = new RemoteWebDriver(new URL("{YOUR_BROWSER_URL}"), opts.addTo(capabilities));
        SoftAssert softAssert = new SoftAssert();
        driver.manage().window().maximize();

        Dimension dimension1 = new Dimension(800, 600);
        driver.manage().window().setSize(dimension1);
        softAssert.assertEquals(dimension1, driver.manage().window().getSize(), "Step 1: 800x600");

        Dimension dimension2 = new Dimension(800, 800);
        driver.manage().window().setSize(dimension2);
        softAssert.assertEquals(dimension2, driver.manage().window().getSize(), "Step 2: 800x800");

        Dimension dimension3 = new Dimension(800, 700);
        driver.manage().window().setSize(dimension3);
        softAssert.assertEquals(dimension3, driver.manage().window().getSize(), "Step 3: 800x700");

        Dimension dimension4 = new Dimension(1000, 700);
        driver.manage().window().setSize(dimension4);
        softAssert.assertEquals(dimension4, driver.manage().window().getSize(), "Step 4: 1000x700");

        Dimension dimension5 = new Dimension(1000, 800);
        driver.manage().window().setSize(dimension5);
        softAssert.assertEquals(dimension5, driver.manage().window().getSize(), "Step 5: 1000x800");

        Dimension dimension6 = new Dimension(800, 800);
        driver.manage().window().setSize(dimension6);
        softAssert.assertEquals(dimension6, driver.manage().window().getSize(), "Step 6: 800x800");

        driver.quit();
        
        softAssert.assertAll();
    }
}
```

Result:

The following asserts failed:
	Step 2: 800x800 expected [(800, 600)] but found [(800, 800)],
	Step 3: 800x700 expected [(800, 600)] but found [(800, 700)],
	Step 5: 1000x800 expected [(1000, 700)] but found [(1000, 800)]

## Stacktrace

Have no error

## Trace-level log

[ff55.txt](https://github.com/mozilla/geckodriver/files/1225002/ff55.txt)

**Comment by whimboo** [comment] 2017-08-16 15:50
@andreastt is that already covered by any of your patches? As we have seen already earlier it could be that the set window rect command returns too early, and the window has not the expected dimensions.

**Comment by andreastt** [comment] 2017-08-18 18:32
This is still a persistent issue.

**Comment by whimboo** [comment] 2017-08-21 06:42
@andreastt do we have a current bug filed for it? I lost focus for all those actually over the last weeks.

**Comment by andreastt** [comment] 2017-08-21 18:54
If we do, I can’t find it. Filed https://bugzilla.mozilla.org/show_bug.cgi?id=1392368 to track this.

**Comment by andreastt** [comment] 2017-08-22 12:19
With the following tests ran against Firefox Nightly, I’m unable to reproduce this issue:

```py
def test_move_to_same_position(session):
    original_position = session.window.position
    position = session.window.position = original_position
    assert position == original_position


def test_move_to_same_x(session):
    original_x = session.window.position[0]
    position = session.window.position = (original_x, 345)
    assert position == (original_x, 345)


def test_move_to_same_y(session):
    original_y = session.window.position[1]
    position = session.window.position = (456, original_y)
    assert position == (456, original_y)


def test_resize_to_same_size(session):
    original_size = session.window.size
    size = session.window.size = original_size
    assert size == original_size


def test_resize_to_same_width(session):
    original_width = session.window.size[0]
    size = session.window.size = (original_width, 345)
    assert size == (original_width, 345)


def test_resize_to_same_height(session):
    original_height = session.window.size[1]
    size = session.window.size = (456, original_height)
    assert size == (456, original_height)
```

Could you try running your test against Firefox Nightly (57 or greater)?

**Comment by andreastt** [comment] 2017-08-22 12:19
@kalumpiwarra

**Comment by kalumpiwarra** [comment] 2017-08-23 04:33
@andreastt it's not reproduced on Firefox 57.0a1 (2017-08-22) (32-bit).
But it's still reproduced on the latest stable release 55.0.2 (32-bit).

**Comment by andreastt** [comment] 2017-08-23 23:34
@kalumpiwarra Right, thanks. I’m closing this because it is working in the development version of Firefox.

**Closed by andreastt** 2017-08-23 23:34 UTC
Labels: marionette, waiting for reporter feedback
