### ISSUE TITLE
Hosting binary request: binaries located on a separate site

### ISSUE THREAD

**Issue by cnishina** [mozilla/geckodriver#1207] opened 2018-03-08 21:14 UTC
When [webdriver-manager](https://github.com/angular/webdriver-manager) downloads other binaries like selenium server or chromedriver, it hits a google storage api xml file and grabs the latest version matching the OS type.

When downloading GeckoDriver releases, we parse out the json from a GitHub API to find the latest or the user specified version. Unfortunately there is a GitHub rate limit. When calling for a list of releases. This becomes much more difficult on something like Travis or CircleCI where many users are trying to download the same binary from possibly same IP address causing a rate limit to be hit. Could this be hosted elsewhere where we are not limited by the GitHub API rate limit?

**Comment by damencho** [comment] 2018-03-08 23:24
We are using https://github.com/bonigarcia/webdrivermanager, where you can pass wdm.gitHubTokenName and wdm.gitHubTokenSecret to avoid this problem. There is no rate-limit when using a token.
Isn't there something similar for webdriver-manager?

**Comment by whimboo** [comment] 2018-03-09 08:58
Please do not download the binary for each and every test. Cache it locally to prevent test failures as caused by network latency, or really use a tool like puppet to install it once.

Dupe of issue #840.

**Closed by whimboo** 2018-03-09 08:58 UTC

**Comment by cnishina** [comment] 2018-03-09 09:26
Reading through the duped issue, it sounds like this not going to be fixed. Not everyone has a set up using puppet and not every CI will allow you to use it. That's too bad... I was really hoping something could have been done to make the process easier.

**Comment by whimboo** [comment] 2018-03-09 09:49
There is no specific requirement to just put the geckodriver installer to a local file share from where it can be installed.
