### ISSUE TITLE
executing pseudoelement javascript -> selenium.common.exceptions.JavascriptException: Message: Cyclic object value

### ISSUE THREAD

**Issue by fenchu** [mozilla/geckodriver#1859] opened 2021-03-16 13:27 UTC
## System

* Version:  0.29.0
* Platform:  windows10/ubuntu16.04lts in container / python 3.9.2
* Firefox:  86.0.1
* Selenium:  python 4.0.0a7

## Testcase

Most recent react apps have shadow-root pseudo elements, this is code that do not show in webdriver , but the code snippet must be executed and then parsed as css-elements:
 

```
def expand_shadow_element(driver, el):
    """ expand shadow root """
    shadow_root = driver.execute_script('return arguments[0].shadowRoot', el)
    return shadow_root

And in the code I calls it like this:
            el = wd.find_element(By.XPATH, "//bp-navbar")
            shadow_root = expand_shadow_element(wd, el)
            shadow_root.find_elements(By.CSS_SELECTOR, "span#lang-icon")[0].click()
```

## Stacktrace

```
tests\test_13_user_admin_no.py:123: in test02_user_admin
    shadow_root = expand_shadow_element(wd, el)
tests\test_13_user_admin_no.py:55: in expand_shadow_element
    shadow_root = driver.execute_script('return arguments[0].shadowRoot', el)
..\..\venvs\hso-fullstack-test\lib\site-packages\selenium\webdriver\remote\webdriver.py:759: in execute_script
    return self.execute(command, {
..\..\venvs\hso-fullstack-test\lib\site-packages\selenium\webdriver\remote\webdriver.py:368: in execute
    self.error_handler.check_response(response)
..\..\venvs\hso-fullstack-test\lib\site-packages\selenium\webdriver\remote\errorhandler.py:240: in check_response
    raise exception_class(message, screen, stacktrace)
E   selenium.common.exceptions.JavascriptException: Message: Cyclic object value
E   Stacktrace:
E   WebDriverError@chrome://marionette/content/error.js:181:5
E   JavaScriptError@chrome://marionette/content/error.js:360:5
E   assert.acyclic@chrome://marionette/content/assert.js:52:11
E   evaluate.toJSON@chrome://marionette/content/evaluate.js:363:12
E   receiveMessage@chrome://marionette/content/actors/MarionetteCommandsChild.jsm:158:31
```

## Trace-level log

```
1615900763466	webdriver::server	DEBUG	-> POST /session/fd2bc77f-640c-4106-8a1b-bc82ab20392a/element {"using": "xpath", "value": "//bp-navbar"}
1615900763468	Marionette	DEBUG	0 -> [0,5,"WebDriver:FindElement",{"using":"xpath","value":"//bp-navbar"}]
1615900763470	Marionette	TRACE	[15] MarionetteCommands actor created for window id 2147483650
1615900763477	Marionette	DEBUG	0 <- [1,5,null,{"value":{"element-6066-11e4-a52e-4f735466cecf":"0cfebaba-257c-4646-b6e5-1b260172d360"}}]
1615900763477	webdriver::server	DEBUG	<- 200 OK {"value":{"element-6066-11e4-a52e-4f735466cecf":"0cfebaba-257c-4646-b6e5-1b260172d360"}}
1615900763479	webdriver::server	DEBUG	-> POST /session/fd2bc77f-640c-4106-8a1b-bc82ab20392a/execute/sync {"script": "return arguments[0].shadowRoot", "args": [{"ELEMENT": "0cfebaba-257c-4646-b6e5-1b260172d360", "element-6066-11e4-a52e-4f735466cecf": "0cfebaba-257c-4646-b6e5-1b260172d360"}]}
1615900763481	Marionette	DEBUG	0 -> [0,6,"WebDriver:ExecuteScript",{"args":[{"ELEMENT":"0cfebaba-257c-4646-b6e5-1b260172d360","element-6066-11e4-a52e-4f735466cecf":"0cfebaba-257c-4646-b6e5-1b260172d360"}],"script":"return arguments[0].shadowRoot"}]
1615900763492	Marionette	DEBUG	0 <- [1,6,{"error":"javascript error","message":"Cyclic object value","stacktrace":"WebDriverError@chrome://marionette/content/err ... te/content/evaluate.js:363:12\nreceiveMessage@chrome://marionette/content/actors/MarionetteCommandsChild.jsm:158:31\n"},null]
1615900763492	webdriver::server	DEBUG	<- 500 Internal Server Error {"value":{"error":"javascript error","message":"Cyclic object value","stacktrace":"WebDriverError@chrome://marionette/content/error.js:181:5\nJavaScriptError@chrome://marionette/content/error.js:360:5\nassert.acyclic@chrome://marionette/content/assert.js:52:11\nevaluate.toJSON@chrome://marionette/content/evaluate.js:363:12\nreceiveMessage@chrome://marionette/content/actors/MarionetteCommandsChild.jsm:158:31\n"}}
```

This work flawlessly in chrome, so I'm currently stuck on chrome :-(

**Comment by fenchu** [comment] 2021-09-02 14:42
Could you please add some more debugging to the execute_script, because we are unable to workaround. I have more than 100 of those preusdo-elements and they all fail exactly the same.

**Comment by whimboo** [comment] 2021-09-28 10:55
With the current implementation the `shadowRoot` element is not serializable. As such you see this failure. With https://bugzilla.mozilla.org/show_bug.cgi?id=1700073 we will add the `Get Element Shadow Root` end-point, which will allow you to not have to rely on `Execute Script` anymore. If `Execute Script` would still not be able to serialize it afterward, we would need a follow-up patch. But lets wait for now.

**Comment by fenchu** [comment] 2022-02-11 13:58
This should be fixed with firefox 96, I will try :-)

**Comment by zacwang89** [comment] 2022-05-24 00:36
I still got the `Cyclic object value` error when getting the shadow element. 
Firefox: 100.0.2
geckodriver: 0.31.0

```
root1 = driver.find_element(By.TAG_NAME, 'amplify-sign-in')
shadow_root1 = driver.execute_script('return arguments[0].shadowRoot', root1)
```

Error message:
```
selenium.common.exceptions.JavascriptException: Message: Cyclic object value
Stacktrace:
WebDriverError@chrome://remote/content/shared/webdriver/Errors.jsm:183:5
JavaScriptError@chrome://remote/content/shared/webdriver/Errors.jsm:362:5
evaluate.assertAcyclic@chrome://remote/content/marionette/evaluate.js:52:11
evaluate.toJSON@chrome://remote/content/marionette/evaluate.js:359:14
receiveMessage@chrome://remote/content/marionette/actors/MarionetteCommandsChild.jsm:177:31
````

Also, I tried to use `Get Element Shadow Root` end-point, but it did not work either. Not sure if I called it in the right way.
```
root1 = driver.find_element(By.TAG_NAME, 'amplify-sign-in')
shadow_root1 = driver.getShadowRoot(root1)
```
Error message:
`AttributeError: 'WebDriver' object has no attribute 'getShadowRoot'`

**Comment by whimboo** [comment] 2022-05-24 06:42
> root1 = driver.find_element(By.TAG_NAME, 'amplify-sign-in')
> shadow_root1 = driver.execute_script('return arguments[0].shadowRoot', root1)

As a workaround use `execute_async_script()`, which will return the ShadowRoot correctly.

> AttributeError: 'WebDriver' object has no attribute 'getShadowRoot'

This is an error message from the Selenium binding. So you want to check it's API documentation and since which version it is available.

**Comment by fenchu** [comment] 2022-07-08 13:48
I tried execute_async_script(), but it then just timesout:
```
  File "C:\dist\work\multitenant-fullstack-test\bin\manual_enroll_for_fido_testing.py", line 235, in <module>
    shadow_root = expand_shadow_element(wd, el)
  File "C:\dist\work\multitenant-fullstack-test\bin\manual_enroll_for_fido_testing.py", line 32, in expand_shadow_element
    shadow_root = driver.execute_async_script('return arguments[0].shadowRoot', el)
  File "C:\dist\venvs\multitenant-fullstack-test\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 906, in execute_async_script
    return self.execute(command, {
  File "C:\dist\venvs\multitenant-fullstack-test\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 430, in execute
    self.error_handler.check_response(response)
  File "C:\dist\venvs\multitenant-fullstack-test\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 247, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: Timed out after 30000 ms
Stacktrace:
WebDriverError@chrome://remote/content/shared/webdriver/Errors.jsm:186:5
ScriptTimeoutError@chrome://remote/content/shared/webdriver/Errors.jsm:448:5
evaluate.sandbox/timeoutPromise</scriptTimeoutID<@chrome://remote/content/marionette/evaluate.js:128:16
notify@resource://gre/modules/Timer.jsm:62:17
```
The old version still give: 
```
Traceback (most recent call last):
  File "C:\dist\work\multitenant-fullstack-test\bin\manual_enroll_for_fido_testing.py", line 235, in <module>
    shadow_root = expand_shadow_element(wd, el)
  File "C:\dist\work\multitenant-fullstack-test\bin\manual_enroll_for_fido_testing.py", line 32, in expand_shadow_element
    shadow_root = driver.execute_script('return arguments[0].shadowRoot', el)
  File "C:\dist\venvs\multitenant-fullstack-test\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 884, in execute_script
    return self.execute(command, {
  File "C:\dist\venvs\multitenant-fullstack-test\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 430, in execute
    self.error_handler.check_response(response)
  File "C:\dist\venvs\multitenant-fullstack-test\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 247, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.JavascriptException: Message: Cyclic object value
Stacktrace:
WebDriverError@chrome://remote/content/shared/webdriver/Errors.jsm:186:5
JavaScriptError@chrome://remote/content/shared/webdriver/Errors.jsm:365:5
evaluate.assertAcyclic@chrome://remote/content/marionette/evaluate.js:52:11
evaluate.toJSON@chrome://remote/content/marionette/evaluate.js:359:14
receiveMessage@chrome://remote/content/marionette/actors/MarionetteCommandsChild.jsm:177:31
```

**Comment by whimboo** [comment] 2022-07-08 19:54
You will have to use `driver.execute_async_script('const [el, resolve] = arguments; resolve(el.shadowRoot)', el)` to get the async script working. Otherwise the command will never return that's correct.

**Comment by fenchu** [comment] 2022-07-09 05:22
thanks whimboo, I will test it on monday.

**Comment by whimboo** [comment] 2022-07-13 09:52
Sure, but note that you don't have to use script execution anymore given that all the recent Selenium bindings should actually support the [`Get Element Shadow Root` command](https://w3c.github.io/webdriver/#get-element-shadow-root).

**Comment by whimboo** [comment] 2022-07-13 09:53
Nevertheless this is actually a dupe of issue #1711.

**Closed by whimboo** 2022-07-13 09:53 UTC
Labels: marionette
