### ISSUE TITLE
Component not initialized - get window - no

### ISSUE THREAD

**Issue by kovalev007** [mozilla/geckodriver#1623] opened 2019-09-27 04:40 UTC
## System

* Version: geckodriver 0.23.0 and/or geckodriver 0.24.0 and/or geckodriver 0.25.0
* Platform: aws linux and/or windows 10
* Firefox: 69.0.1 (64-bit) and/or nightly 71.0a1 (2019-09-26) (64-bit)
* Selenium: java 3.141.59

## Stacktrace
Marionette threw an error: [Exception... "Component not initialized"  nsresult: "0xc1f30001 (NS_ERROR_NOT_INITIALIZED)"  location: "JS frame :: chrome://marionette/content/modal.js :: get window :: line 199"  data: no]
get window@chrome://marionette/content/modal.js:199:11
get tabModal@chrome://marionette/content/modal.js:207:15
get ui@chrome://marionette/content/modal.js:220:14
GeckoDriver.prototype._handleUserPrompts@chrome://marionette/content/driver.js:3370:23
GeckoDriver.prototype.findElement@chrome://marionette/content/driver.js:2078:14
despatch@chrome://marionette/content/server.js:305:40
execute@chrome://marionette/content/server.js:275:16
onPacket/<@chrome://marionette/content/server.js:248:20
onPacket@chrome://marionette/content/server.js:249:9
_onJSONObjectReady/<@chrome://marionette/content/transport.js:503:20

## Notes
chromedriver 77.0.3865.40 and chrome 77.0.3865.90 - works good
geckodriver 0.23.0 and firefox 66.0 - works good
error occurs after some time test running
error occurs in headless

## Trace-level log

[log.txt](https://github.com/mozilla/geckodriver/files/3660903/log.txt)
[log_with_trace.txt](https://github.com/mozilla/geckodriver/files/3660904/log_with_trace.txt)

**Comment by whimboo** [comment] 2019-09-27 07:56
What about Firefox 67 and 68? With which version of Firefox does it start exactly? Also providing a small testcase and HTML snippet would be great.

**Comment by kovalev007** [comment] 2019-09-28 14:57
firefox 67.0.4 with geckodriver 0.25.0 - works good
(https://download-installer.cdn.mozilla.net/pub/firefox/releases/67.0.4/win64/en-US/)
firefox 68.0.2 with geckodriver 0.25.0 - works good
(https://download-installer.cdn.mozilla.net/pub/firefox/releases/68.0.2/win64/en-US/)
firefox 69.0 with geckodriver 0.25.0 - bug
(https://download-installer.cdn.mozilla.net/pub/firefox/releases/69.0/win64/en-US/)
firefox 69.0.1 with geckodriver 0.25.0 - bug
(https://download-installer.cdn.mozilla.net/pub/firefox/releases/69.0.1/win64/en-US/)

[69.0_without_trace.txt](https://github.com/mozilla/geckodriver/files/3665591/69.0_without_trace.txt)
[69.0.1_without_trace.txt](https://github.com/mozilla/geckodriver/files/3665592/69.0.1_without_trace.txt)

I tested only on one test.
Provide HTML it is very hard job.
On each HTML page we have thousand js files. On each test we open many modal windows. etc. It is very hard to investigate which web components affect this error.

Сould be easier
What about create individual version for firefox?
Example: if between 69.0 and 69.0.1 - 1000 commits. May be create some firefox versions with 250 commits since 69.0, with 500 commits since 69,0 and with 750 commits since 69,0 to try investigate which changes influenced the tests?

**Comment by kovalev007** [comment] 2019-09-29 03:33
Firefox 69.0 also have error (but failed tests count on 69.0 less than on 69.0.1).
I will return later with results from full test suite (1500 tests) from different firefox versions.

**Comment by whimboo** [comment] 2019-09-30 09:08
Ok, so that means the regression started while 69 was in Nightly. Based on the fact that it is too hard for you to create a minimized testcase, we would depend on your help to find out which change might have caused this problem. 

Actually for the Firefox 69 release I got [bug 1477977](https://bugzilla.mozilla.org/show_bug.cgi?id=1477977) and [bug 1487358](https://bugzilla.mozilla.org/show_bug.cgi?id=1487358) landed. Maybe one of those caused a problem.

Here the steps to do:

1) Check if bug 1477977 has an influence here, by openening https://hg.mozilla.org/mozilla-central/rev/e9e20d087e33, and grabbing the builds from the `last release without` and `first release with` links based on your platform.

2) If the builds above behave identically please do the same for https://hg.mozilla.org/mozilla-central/rev/9c28135106d3

3) If those builds also behave the same something else caused the regression, which would need a bisecting of builds. I can give instructions once it's known that this has to be done.

Thanks in advance!

**Comment by kovalev007** [comment] 2019-09-30 11:50
Problem appeared after fix bug 1477977.
I checked two different tests on "last release without" and "first release with".

first_test_first_release_without.txt - 28 MB file :(
[first_test_first_release_with.txt](https://github.com/mozilla/geckodriver/files/3670836/first_test_first_release_with.txt)
[second_test_last_release_without.txt](https://github.com/mozilla/geckodriver/files/3670808/second_test_last_release_without.txt)
[second_test_first_release_with.txt](https://github.com/mozilla/geckodriver/files/3670810/second_test_first_release_with.txt)



I overview your changes and can collect compressed info for logger.trace = "Received observer notification".
[Received observer notification.txt](https://github.com/mozilla/geckodriver/files/3670834/Received.observer.notification.txt)

**Comment by whimboo** [comment] 2019-09-30 14:01
Ok, so we have at least more details now. What kind of user prompt is it which gets opened here, and Marionette fails to detect? Maybe you could create a screenshot, show some HTML code, or explain it? It would also help to see some test code from where it's failing.

**Comment by kovalev007** [comment] 2019-09-30 14:56
Can you provide line numbers from my log file(s)?
I spent all day in attempts to localize problem in code. But not getting results. And got confused.


1) I can record video in non headless browser. It is easy.
2) I can discuss about provide test account for test site for you and create one test without any not needed code (on java or create executable JAR file). It's a little harder.
3) I can miting with you and run test on real time.

**Comment by kovalev007** [comment] 2019-10-01 05:09
Additional details about this:
Main problem with this - this bug appears time to time.
And this bug appears on different line numbers in my test.

Example:
I run one test 6 times with "last release without" version
and 6 times with "first release with" version

6 launches with "last release without" version works good
2 launches with "first release with" version works good
4 launches with "first release with" version - bug

I don't have any ideas from my side.
What about add adiitional trace log to chrome://marionette/content/modal.js or any other marionette files?
Or any other ideas?
May be I can execute some method on marionette via selenium in my test to collect additional info before marionette will throw error.

[after_1.txt](https://github.com/mozilla/geckodriver/files/3674493/after_1.txt) bug
[after_2.txt](https://github.com/mozilla/geckodriver/files/3674494/after_2.txt) good
[after_3.txt](https://github.com/mozilla/geckodriver/files/3674495/after_3.txt) bug
[after_4.txt](https://github.com/mozilla/geckodriver/files/3674496/after_4.txt) bug
[after_5.txt](https://github.com/mozilla/geckodriver/files/3674497/after_5.txt) bug
[after_6.txt](https://github.com/mozilla/geckodriver/files/3674498/after_6.txt) good

**Comment by whimboo** [comment] 2019-10-25 06:55
Sorry for being late with my reply, but due to project shifts I don't have that much time for investigating this failure. But I would still be happy to help with suggestions.

@kovalev007 could you imagine to join IRC eg the selenium channel on Freenode, and ping me there? I think what would be best here is if you build Firefox yourself and add those logging statements locally which would allow best flexibility. I'm absolutely happy to help you with any of the steps.

**Comment by whimboo** [comment] 2019-11-08 09:22
Sorry, looks like we just missed each other on IRC. Please ping me again and maybe wait a bit longer to let me answer.

**Comment by whimboo** [comment] 2019-11-11 08:45
Just for reference this is the list of changes as identified in an earlier comment:
https://hg.mozilla.org/mozilla-central/pushloghtml?fromchange=e93ecdda786c4e168323b099ec38c5f098bc1911&tochange=6c5b432d7460f7ffd715e988fa179a93d4f7e4ae

**Comment by whimboo** [comment] 2019-11-12 14:50
As it has been turned out the problem here is that with the Java bindings the preference `prompts.tab_modal.enabled` gets set to false. With that the test enters an unsupported mode with geckodriver and Firefox.

@kovalev007 please continue to test with the preference set to `true`, and let me know if that makes the test always passing now. At least that's what I would expect. If that is the case we can close this issue.

**Comment by whimboo** [comment] 2019-11-12 14:51
Also thanks a lot for your help in investigating this problem! Positive is that you now know how to build Firefox and debug failures. Maybe it's something which will help us in the future again.

**Comment by whimboo** [comment] 2019-11-12 15:06
As @kovalev007 asked me to close this issue I'm doing it on his behalf now.

**Closed by whimboo** 2019-11-12 15:06 UTC
Labels: selenium, waiting for reporter feedback

**Comment by mscrivo** [comment] 2019-12-09 21:32
@whimboo  running into this as well after upgrading Firefox 68 to 71.  The problem is, that pref cannot be changed with the C# Selenium Web Driver + GeckoDriver 0.26.  I get this error:

> System.ArgumentException : Preference prompts.tab_modal.enabled may not be overridden: frozen value=False, requested value=True

**Comment by ali0646** [comment] 2020-01-02 22:34
I am also running into the same issue after upgrading Firefox from 68 to 71. 

firefox, browserVersion: 71.0
geckodriverVersion: 0.26.0
selenium-java --3.141.59

Please help!!!

**Comment by whimboo** [comment] 2020-01-03 07:58
It's not helpful to report `me too`. For everyone the issue could be different. So please don't hijack this already closed issue. If a problem exists file your own issue and provide ALL the information as requested.
