### ISSUE TITLE
key down is not working

### ISSUE THREAD

**Issue by wengoooooooo** [mozilla/geckodriver#1024] opened 2017-10-23 06:50 UTC
## System
* Version: geckodriver 0.19
* Platform: windows 7
* Firefox: firefox 56.0.1
* Selenium: 3.6

## Testcase

```python
from selenium import webdriver
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.common.keys import Keys

driver = webdriver.Firefox()

# open responsive design mode is not work, but if geckodriver 0.16.1 with firefox 53.0.1 is work
ActionChains(driver).key_down(Keys.LEFT_CONTROL).key_down(Keys.LEFT_SHIFT).send_keys("m").key_up(Keys.LEFT_SHIFT).key_up(Keys.LEFT_CONTROL).perform()
```

## Trace-level log

1508740625563	geckodriver	INFO	geckodriver 0.18.0
1508740625576	geckodriver	INFO	Listening on 127.0.0.1:12755
1508740626094	geckodriver::marionette	INFO	Starting browser C:\Program Files (x86)\Mozilla Firefox\firefox.exe with args ["-marionette"]
1508740626679	addons.xpi	WARN	Error parsing extensions state: [Exception... "Component returned failure code: 0x80520012 (NS_ERROR_FILE_NOT_FOUND) [amIAddonManagerStartup.readStartupData]"  nsresult: "0x80520012 (NS_ERROR_FILE_NOT_FOUND)"  location: "JS frame :: resource://gre/modules/addons/XPIProvider.jsm :: loadExtensionState :: line 1554"  data: no] Stack trace: loadExtensionState()@resource://gre/modules/addons/XPIProvider.jsm:1554 < getInstallState()@resource://gre/modules/addons/XPIProvider.jsm:1589 < checkForChanges()@resource://gre/modules/addons/XPIProvider.jsm:3109 < startup()@resource://gre/modules/addons/XPIProvider.jsm:2188 < callProvider()@resource://gre/modules/AddonManager.jsm:269 < _startProvider()@resource://gre/modules/AddonManager.jsm:739 < startup()@resource://gre/modules/AddonManager.jsm:906 < startup()@resource://gre/modules/AddonManager.jsm:3090 < observe()@jar:file:///C:/Program%20Files%20(x86)/Mozilla%20Firefox/omni.ja!/components/addonManager.js:65
1508740626982	Marionette	DEBUG	Received observer notification "profile-after-change"
1508740627126	Marionette	DEBUG	Received observer notification "command-line-startup"
1508740627127	Marionette	INFO	Enabled via --marionette
1508740627129	geckodriver::marionette	TRACE	  connection attempt 0/600
1508740628322	geckodriver::marionette	TRACE	  connection attempt 1/600
1508740629433	geckodriver::marionette	TRACE	  connection attempt 2/600
1508740630444	Marionette	DEBUG	Received observer notification "sessionstore-windows-restored"
1508740630540	geckodriver::marionette	TRACE	  connection attempt 3/600
1508740630589	Marionette	DEBUG	Setting recommended pref toolkit.cosmeticAnimations.enabled to false
1508740630589	Marionette	DEBUG	Setting recommended pref datareporting.policy.dataSubmissionPolicyAccepted to false
1508740630590	Marionette	DEBUG	Setting recommended pref dom.file.createInChild to true
1508740630591	Marionette	INFO	Listening on port 12760
1508740630641	geckodriver::marionette	DEBUG	Connected to Marionette on localhost:12760
1508740630653	Marionette	DEBUG	Accepted connection 0 from 127.0.0.1:12785
1508740630659	geckodriver::marionette	TRACE	<- {"applicationType":"gecko","marionetteProtocol":3}
1508740630660	geckodriver::marionette	TRACE	-> 163:[0,1,"newSession",{"acceptInsecureCerts":true,"browserName":"firefox","capabilities":{"desiredCapabilities":{"acceptInsecureCerts":true,"browserName":"firefox"}}}]
1508740630668	Marionette	TRACE	0 -> [0,1,"newSession",{"acceptInsecureCerts":true,"browserName":"firefox","capabilities":{"desiredCapabilities":{"acceptInsecureCerts":true,"browserName":"firefox"}}}]
1508740630673	Marionette	CONFIG	Matched capabilities: {"browserName":"firefox","browserVersion":"56.0.1","platformName":"windows_nt","platformVersion":"6.1","pageLoadStrategy":"normal","acceptInsecureCerts":true,"timeouts":{"implicit":0,"pageLoad":300000,"script":30000},"rotatable":false,"specificationLevel":0,"moz:processID":12376,"moz:profile":"C:\\Users\\lenovo\\AppData\\Local\\Temp\\rust_mozprofile.A141qkVi5nKn","moz:accessibilityChecks":false,"moz:headless":false}
1508740630673	Marionette	WARN	TLS certificate errors will be ignored for this session
1508740630739	Marionette	DEBUG	Register listener.js for window 4294967297
1508740630768	Marionette	TRACE	0 <- [1,1,null,{"sessionId":"4418d92b-1417-4939-a4b1-4815ff1a5c34","capabilities":{"browserName":"firefox","browserVersion":"56.0.1","platformName":"windows_nt","platformVersion":"6.1","pageLoadStrategy":"normal","acceptInsecureCerts":true,"timeouts":{"implicit":0,"pageLoad":300000,"script":30000},"rotatable":false,"specificationLevel":0,"moz:processID":12376,"moz:profile":"C:\\Users\\lenovo\\AppData\\Local\\Temp\\rust_mozprofile.A141qkVi5nKn","moz:accessibilityChecks":false,"moz:headless":false}}]
1508740630771	geckodriver::marionette	TRACE	<- [1,1,null,{"sessionId":"4418d92b-1417-4939-a4b1-4815ff1a5c34","capabilities":{"browserName":"firefox","browserVersion":"56.0.1","platformName":"windows_nt","platformVersion":"6.1","pageLoadStrategy":"normal","acceptInsecureCerts":true,"timeouts":{"implicit":0,"pageLoad":300000,"script":30000},"rotatable":false,"specificationLevel":0,"moz:processID":12376,"moz:profile":"C:\\Users\\lenovo\\AppData\\Local\\Temp\\rust_mozprofile.A141qkVi5nKn","moz:accessibilityChecks":false,"moz:headless":false}}]
1508740630771	webdriver::server	DEBUG	<- 200 OK {"value": {"sessionId":"4418d92b-1417-4939-a4b1-4815ff1a5c34","capabilities":{"acceptInsecureCerts":true,"browserName":"firefox","browserVersion":"56.0.1","moz:accessibilityChecks":false,"moz:headless":false,"moz:processID":12376,"moz:profile":"C:\\Users\\lenovo\\AppData\\Local\\Temp\\rust_mozprofile.A141qkVi5nKn","pageLoadStrategy":"normal","platformName":"windows_nt","platformVersion":"6.1","rotatable":false,"specificationLevel":0,"timeouts":{"implicit":0,"pageLoad":300000,"script":30000}}}}
1508740657066	webdriver::server	DEBUG	-> POST /session/4418d92b-1417-4939-a4b1-4815ff1a5c34/actions {"sessionId": "4418d92b-1417-4939-a4b1-4815ff1a5c34", "actions": [{"parameters": {"pointerType": "mouse"}, "type": "pointer", "id": "mouse", "actions": [{"duration": 0, "type": "pause"}, {"duration": 0, "type": "pause"}]}, {"type": "key", "id": "key", "actions": [{"type": "keyDown", "value": "\ue009"}, {"type": "keyDown", "value": "\ue008"}, {"type": "keyDown", "value": "m"}, {"type": "keyUp", "value": "m"}]}]}
1508740657068	geckodriver::marionette	TRACE	-> 341:[0,2,"performActions",{"actions":[{"actions":[{"duration":0,"type":"pause"},{"duration":0,"type":"pause"}],"id":"mouse","parameters":{"pointerType":"mouse"},"type":"pointer"},{"actions":[{"type":"keyDown","value":""},{"type":"keyDown","value":""},{"type":"keyDown","value":"m"},{"type":"keyUp","value":"m"}],"id":"key","type":"key"}]}]
1508740657068	Marionette	TRACE	0 -> [0,2,"performActions",{"actions":[{"actions":[{"duration":0,"type":"pause"},{"duration":0,"type":"pause"}],"id":"mouse","parameters":{"pointerType":"mouse"},"type":"pointer"},{"actions":[{"type":"keyDown","value":""},{"type":"keyDown","value":""},{"type":"keyDown","value":"m"},{"type":"keyUp","value":"m"}],"id":"key","type":"key"}]}]
1508740657091	Marionette	TRACE	0 <- [1,2,null,{}]
1508740657093	geckodriver::marionette	TRACE	<- [1,2,null,{}]
1508740657093	webdriver::server	DEBUG	<- 200 OK {"value": {}}

**Comment by andreastt** [comment] 2017-10-24 14:52
Duplicate of https://github.com/mozilla/geckodriver/issues/646, I believe.

**Closed by andreastt** 2017-10-24 14:52 UTC
