### ISSUE TITLE
Request for gecodriver to work with linux aarch64 systems.

### ISSUE THREAD

**Issue by dipesh2002** [mozilla/geckodriver#1927] opened 2021-09-03 06:33 UTC

**Comment by whimboo** [comment] 2021-09-06 18:07
It's a self-serving build. For instructions see https://firefox-source-docs.mozilla.org/testing/geckodriver/ARM.html.

Marking as dupe of issue #1515.

**Closed by whimboo** 2021-09-06 18:07 UTC

**Comment by whimboo** [comment] 2022-01-24 12:44
See also issue #1956.
