### ISSUE TITLE
Provide a LICENSE file available for download

### ISSUE THREAD

**Issue by bloudraak** [mozilla/geckodriver#1120] opened 2018-01-03 05:36 UTC
## System
* Version: N/A
* Platform: N/A
* Firefox: N/A
* Selenium: N/A

## Testcase

Download any version of geckodriver.  Notice that there is no license file in the archive, nor is there a LICENSE in the GitHub repository that has the releases. There is also no LICENSE file in the MDN repository inside the project.

I have a Windows Installer package that installs Selenium and geckodriver. I'd like to make sure the user has access to the license under which the geckodriver is distributed.  In many organizations, this is a big deal and the absence of a license (or reference to it) causes churn. 

## Stacktrace

N/A

## Rationale

* Licenses do change from time to time and it can reduce "churn" if the license in effect accompanies the release or archives that are available for download.
* There are often additional licensing requirements when redistributing the binary, in that it is required that the license is made available to the end user.
* Give credit where credit is due.

**Comment by andreastt** [comment] 2018-01-03 11:15
geckodriver’s canonical repository is https://hg.mozilla.org/mozilla-central/file and that contains all the licensing information. You can read an HTML rendered license at https://www.mozilla.org/en-US/MPL/2.0/.

Duplicate of https://github.com/mozilla/geckodriver/issues/1053.

**Closed by andreastt** 2018-01-03 11:15 UTC

**Comment by bloudraak** [comment] 2018-01-03 19:35
Licenses do change over time, so the reference to a link doesn't help when MPL 3.0 is released. 

Does the license need to be displayed to the user when they run the installer that installs the geckodriver?

**Comment by andreastt** [comment] 2018-01-03 19:49
Like I said, mozilla-central contains all the relevant licensning and trademark information in the LEGAL, LICENSE, and toolkit/content/license.html files.

geckodriver doesn’t come with an installer.

**Comment by bloudraak** [comment] 2018-01-03 20:21
Per the original issue, I created an installer for selenium and the web drivers and the licensing question were within that context.  I looked at the licensing, still trying to figure out how it pertains to binaries like geckodriver and any restrictions on redistribution.
