### ISSUE TITLE
Python, selenium and headless firefox - Broken pipe error

### ISSUE THREAD

**Issue by gius-italy** [mozilla/geckodriver#1321] opened 2018-07-04 06:35 UTC
## System

* Version: 0.21.0 (64-Bit)
* Platform: Ubuntu 16.04.4 LTS
* Firefox: 60.0.2
* Selenium: selenium-3.13.0

## Testcase
Trying to open a webpage with a headless firefox browser in python throws a BrokenPipeError, but everything goes fine if the command is rapidly given again. 
(Issue already submitted to https://github.com/SeleniumHQ/selenium/issues/6108)

Code to reproduce
~~~~
import time
from selenium import webdriver

fox_opt=webdriver.FirefoxOptions()
fox_opt.add_argument('--headless')
#fox_opt.log.level = "trace"
with webdriver.Firefox(firefox_options=fox_opt) as browser:
    time.sleep(10)
    browser.get("https://www.google.com")   #Here you get a broken pipe error
    browser.get("https://www.google.com")   #But now everything goes fine
~~~~

## Output

~~~~
Traceback (most recent call last):
  File "<stdin>", line 3, in <module>
  File "/usr/local/lib/python3.5/dist-packages/selenium/webdriver/remote/webdriver.py", line 332, in get
    self.execute(Command.GET, {'url': url})
  File "/usr/local/lib/python3.5/dist-packages/selenium/webdriver/remote/webdriver.py", line 318, in execute
    response = self.command_executor.execute(driver_command, params)
  File "/usr/local/lib/python3.5/dist-packages/selenium/webdriver/remote/remote_connection.py", line 472, in execute
    return self._request(command_info[0], url, body=data)
  File "/usr/local/lib/python3.5/dist-packages/selenium/webdriver/remote/remote_connection.py", line 495, in _request
    self._conn.request(method, parsed_url.path, body, headers)
  File "/usr/lib/python3.5/http/client.py", line 1106, in request
    self._send_request(method, url, body, headers)
  File "/usr/lib/python3.5/http/client.py", line 1151, in _send_request
    self.endheaders(body)
  File "/usr/lib/python3.5/http/client.py", line 1102, in endheaders
    self._send_output(message_body)
  File "/usr/lib/python3.5/http/client.py", line 936, in _send_output
    self.send(message_body)
  File "/usr/lib/python3.5/http/client.py", line 908, in send
    self.sock.sendall(data)
BrokenPipeError: [Errno 32] Broken pipe
~~~~

## Trace-level log
[geckodriver.log](https://github.com/mozilla/geckodriver/files/2162070/geckodriver.log)

**Comment by andreastt** [comment] 2018-07-04 14:13
I can’t see anything unusual in the log. The session is created, then the client ends the session. Could this be a fallout from the `Keep-Alive` change referenced in https://github.com/mozilla/geckodriver/issues/1304?

**Comment by gius-italy** [comment] 2018-07-05 07:55
Yes, it looks like the two issues are correlated. 
As suggested by another user in https://github.com/mozilla/geckodriver/issues/1304, I tried with geckodriver 0.20.1 version and everything goes fine, same if I set the timer on less than 5 seconds.

**Comment by andreastt** [comment] 2018-07-05 10:39
Thanks for confirming!

Closing this as a duplicate of https://github.com/mozilla/geckodriver/issues/1304. I believe @AutomatedTester has a patch for the Selenium Python client in the pipes.

**Closed by andreastt** 2018-07-05 10:39 UTC
