### ISSUE TITLE
Actions.sendKeys(Keys.ENTER) on browser window does not trigger key events

### ISSUE THREAD

**Issue by codingphil** [mozilla/geckodriver#1419] opened 2018-11-05 13:30 UTC
## System

* Version: 0.23.0
* Platform: Windows 10 Version 1809 Build 10.0.17763.1
* Firefox: 63.0.1 (64-bit)
* Selenium: 3.13.0

## Testcase
The test case below sends an ENTER keystroke to the browser window and then checks if the keydown event was fired (checkbox on web page is expected to be checked). 

```java
@Test
public void testSendEnterToBody_actionsApiSendKeys_eventFired() {
  webDriver.navigate().to("https://philipl-micro-focus.github.io/webdriver-testpages/specialKeys.html");
  WebElement enterIndicator = webDriver.findElementById("enter");
  assertFalse("ENTER checkbox expected to be NOT checked", enterIndicator.isSelected());

  new Actions(webDriver).sendKeys(Keys.ENTER).perform();

  assertTrue("ENTER checkbox expected to be checked", enterIndicator.isSelected()); // FAILS
}
```

Adding a click on the H1 tag before the call of Actions.sendKeys() did not help.

Tested also with Firefox Nightly 65.0a1 (2018-11-05) (64-bit).
Same result (failing test) as with Firefox 63.0.1.

## Stacktrace
```java
java.lang.AssertionError: ENTER checkbox expected to be checked
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.assertTrue(Assert.java:41)
	at SendKeysTests.testSendEnterToBody_actionsApiSendKeys_eventFired(SendKeysTests.java:328)
```

## Trace-level log

[geckodriver-log.txt](https://github.com/mozilla/geckodriver/files/2548522/geckodriver-log.txt)

**Comment by whimboo** [comment] 2018-11-05 13:51
Dupe of #985?

**Comment by andreastt** [comment] 2018-11-05 17:50
@whimboo I would expect so, yes. We really should prioritise fixing this, but I guess this is depending on converting the Element Send Keys command to using action primitives?

**Comment by andreastt** [comment] 2018-11-05 17:50
Closing as duplicate of https://github.com/mozilla/geckodriver/issues/985.

**Closed by andreastt** 2018-11-05 17:50 UTC
