### ISSUE TITLE
Selenium 3.4.0-GeckoDriver 0.17.0 : GeckoDriver producing logs through Chromium/Chrome modules 

### ISSUE THREAD

**Issue by Debanjan-B** [mozilla/geckodriver#787] opened 2017-06-16 04:58 UTC
## Meta
GeckoDriver producing logs through Chromium/Chrome modules as /**chromium**/src/**chrome**/common/ipc_channel_win.cc, line 346

	[GPU 5344] WARNING: pipe error: 109: file c:/builds/moz2_slave/m-rel-w64-00000000000000000000/build/src/ipc/chromium/src/chrome/common/ipc_channel_win.cc, line 346

## Platform and application details
* Platform: Windows 8 Pro, 64 bit OS, x64-based processor
* Firefox: Mozilla Firefox 53.0 (64 bit)
* Selenium: Selenium-Server-Standalone-3.4.0 / Java bindings
* GeckoDriver Version: v0.17.0 (64 bit)

## Steps to reproduce
Here is the minimal code block to reproduce the issue:

	package demo;

	import org.openqa.selenium.WebDriver;
	import org.openqa.selenium.firefox.FirefoxDriver;

	public class FIREFOX_GECKO_SIMPLE_TEST {

		public static void main(String[] args) 
		{

			System.setProperty("webdriver.gecko.driver", "C:\\Utility\\BrowserDrivers\\geckodriver.exe");
			WebDriver driver =  new FirefoxDriver();

		}

	}

- [ ] Reproducable testcase:

- [ ] A trace level log:

Here is the complete console log on Eclipse Neon 2:

	1497588495853	geckodriver	INFO	Listening on 127.0.0.1:23433
	1497588496655	geckodriver::marionette	INFO	Starting browser C:\Program Files\Mozilla Firefox\firefox.exe with args ["-marionette"]
	1497588518780	Marionette	INFO	Listening on port 2624
	[GPU 5344] WARNING: pipe error: 109: file c:/builds/moz2_slave/m-rel-w64-00000000000000000000/build/src/ipc/chromium/src/chrome/common/ipc_channel_win.cc, line 346
	Jun 16, 2017 10:18:39 AM org.openqa.selenium.remote.ProtocolHandshake createSession
	INFO: Detected dialect: W3C

**Comment by andreastt** [comment] 2017-06-16 13:59
Duplicate of https://github.com/mozilla/geckodriver/issues/285.

**Closed by andreastt** 2017-06-16 13:59 UTC

**Comment by Debanjan-B** [comment] 2017-06-16 15:37
@andreastt Can you consider to go through my Issue Description again? IMO, you have merged and closed this Issue with #285 without proper analysis. I am not concerned about facing **WARNING: pipe error: 109: file c:/builds/moz2_slave/m-rel-w64-00000000000000000000** any way. I am discarding the WARNING without any weight. What I am more concerned is about **GeckoDriver producing logs through Chromium/Chrome modules** as in: 

`/src/ipc/chromium/src/chrome/common/ipc_channel_win.cc, line 346`

where the words **`chromium`** and **`chrome`** are clearly visible within the log messages.

May be someone else from your team either @AutomatedTester or may be @shs96c can help us to understand if this issue of log message can have any negative impact. Thanks

**Comment by andreastt** [comment] 2017-06-16 16:08
That warning is likely not a problem for the overall result of the WebDriver implementation.

You didn’t say anything in your original issue about exactly what error you’re getting from the client, you didn’t include a stacktrace, no trace-level geckodriver log, and no crash log (if it crashes Firefox). All of this is requested in the issue template, so before you feel justified to call out that I need to investigate the issue in more detail, you should do me the courtesy of filing a good bug report.

Thanks.

**Comment by AutomatedTester** [comment] 2017-06-16 20:02
These errors are nothing to worry about. Mozilla uses different open source projects to build Firefox for different reasons. It showing Chrome errors means nothing in the big picture.
