### ISSUE TITLE
What have you done, boobies??

### ISSUE THREAD

**Issue by T-Shilov** [mozilla/geckodriver#1799] opened 2020-10-24 17:50 UTC
What have you done, boobies??

With geckodriver 0.26 Firefox 78.4.0esr (64-bit) in Debian 10 works fine, and with 0.27 it gives an error:

Fix it, boobies!

~/bin$ python3 test.py Traceback (most recent call last):   
File "test.py", line 7, in <module>     driver = webdriver.Firefox(executable_path=r'/home/first/bin/geckodriver')   
File "/home/first/.local/lib/python3.7/site-packages/selenium/webdriver/firefox/webdriver.py", line 174, in __init__     keep_alive=True)   
File "/home/first/.local/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 157, in __init__     self.start_session(capabilities, browser_profile)   
File "/home/first/.local/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 252, in start_session     response = self.execute(Command.NEW_SESSION, parameters)   
File "/home/first/.local/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute     self.error_handler.check_response(response)   
File "/home/first/.local/lib/python3.7/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response     raise exception_class(message, screen, stacktrace) selenium.common.exceptions.SessionNotCreatedException: Message: Unable to find a matching set of capabilities

**Comment by whimboo** [comment] 2020-10-26 09:27
Dupe of issue #1756.

**Closed by whimboo** 2020-10-26 09:27 UTC
