### ISSUE TITLE
Target window opened by clicking link not included in window handles

### ISSUE THREAD

**Issue by Debanjan-B** [mozilla/geckodriver#929] opened 2017-09-06 10:39 UTC
## Summary: GeckoDriver v0.18.0 with Selenium 3.5.0 through Python 3.6.1 bindings shows wrong number of window_handles. 

When 2 tabs(window handles) are open, geckodriver shows only 1 (one) window handle.

ChromeDriver & IEDriverServer seems to show exactly 2 window handles as expected.

## System
* Version: 0.18.0
* Platform: Windows 8, Pro
* Firefox: 55.0.3 (64-bit)
* Selenium: 3.5.0 (Python 3.6.1 Bindings)

## Testcase

Minimum Code Block:

```
from selenium import webdriver
from selenium.webdriver.firefox.options import Options

binary = r'C:\Program Files\Mozilla Firefox\firefox.exe'
options = Options()
options.binary = binary
driver = webdriver.Firefox(firefox_options=options, executable_path=r'C:\Utility\BrowserDrivers\geckodriver.exe')
print ("Firefox Experiment")
driver.get('https://www.google.co.in')
print("Page Title is : %s" %driver.title)
link = driver.find_element_by_link_text('Gmail')
win_handles_1 = driver.window_handles
print ("Number of Window Handles : %i" %(len(win_handles_1)))
print ("Current Window Handle is : %s" %(driver.current_window_handle))
driver.execute_script('arguments[0].target="_blank";', link)
link.click()
win_handles_2 = driver.window_handles
print ("Number of Window Handles : %i" %(len(win_handles_2)))
print ("Window Handles are : %s" %win_handles_2)
```

## Stacktrace

```
Firefox Experiment
Page Title is : Google
Number of Window Handles : 1
Current Window Handle is : 4294967297
Number of Window Handles : 1
Window Handles are : ['4294967297']
```

## Console Output : 

```
Firefox Experiment
Page Title is : Google
Number of Window Handles : 1
Current Window Handle is : 4294967297
Number of Window Handles : 1
Window Handles are : ['4294967297']
```

--------------------------------------------------------------------------

Chrome Behavior :
--------------------

Code:

```
from selenium import webdriver

driver = webdriver.Chrome(executable_path=r'C:\Utility\BrowserDrivers\chromedriver.exe')
print ("Chrome Experiment")
driver.get('https://www.google.co.in')
print("Page Title is : %s" %driver.title)
link = driver.find_element_by_link_text('Gmail')
win_handles_1 = driver.window_handles
print ("Number of Window Handles : %i" %(len(win_handles_1)))
print ("Current Window Handle is : %s" %(driver.current_window_handle))
driver.execute_script('arguments[0].target="_blank";', link)
link.click()
win_handles_2 = driver.window_handles
print ("Number of Window Handles : %i" %(len(win_handles_2)))
print ("Window Handles are : %s" %win_handles_2)
```
 Console Output : 

```
Chrome Experiment
Page Title is : Google
Number of Window Handles : 1
Current Window Handle is : CDwindow-cb7d035c-c3c0-4a5b-b059-24866c819fc2
Number of Window Handles : 2
Window Handles are : ['CDwindow-cb7d035c-c3c0-4a5b-b059-24866c819fc2', 'CDwindow-0bd3fc76-5229-42f0-be51-c94ed6cdde68']
```

----------------------------------------------------------------

IE Behavior :

Code:

```
from selenium import webdriver

driver = webdriver.Ie(executable_path=r'C:\Utility\BrowserDrivers\IEDriverServer.exe')
print ("IE Experiment")
driver.get('https://www.google.co.in')
print("Page Title is : %s" %driver.title)
link = driver.find_element_by_link_text('Gmail')
win_handles_1 = driver.window_handles
print ("Number of Window Handles : %i" %(len(win_handles_1)))
print ("Current Window Handle is : %s" %(driver.current_window_handle))
driver.execute_script('arguments[0].target="_blank";', link)
link.click()
win_handles_2 = driver.window_handles
print ("Number of Window Handles : %i" %(len(win_handles_2)))
print ("Window Handles are : %s" %win_handles_2)
```

Console Output : 

```
IE Experiment
Page Title is : Google
Number of Window Handles : 1
Current Window Handle is : 10b46d2a-033a-4ef2-9947-c1cd2a83f0c9
Number of Window Handles : 2
Window Handles are : ['10b46d2a-033a-4ef2-9947-c1cd2a83f0c9', 'a0209a88-7275-44c5-a749-0cefa0e84887']
```

**Comment by andreastt** [comment] 2017-09-06 11:05
Known problem that is tracked by https://bugzilla.mozilla.org/show_bug.cgi?id=marionette-window-tracking.

**Comment by whimboo** [comment] 2017-09-07 14:34
> Known problem that is tracked by https://bugzilla.mozilla.org/show_bug.cgi?id=marionette-window-tracking.

@andreastt I don't understand! Why should this be a problem with window tracking and a changing window id? Here we have the fact that the click doesn't immediately open the window, so the expectation fails. Using `Wait.until` or whatever is possible in the Selenium binding should fix that.

I wonder if click doesn't wait long enough, even we make use of the animation frame injection, or the window opens after all events have been processed.

**Comment by Debanjan-B** [comment] 2017-09-09 14:41
@whimboo I think @andreastt directed us to the root cause [here](https://bugzilla.mozilla.org/show_bug.cgi?id=marionette-window-tracking) because I carried out a simple test with the Java Client (3.5.3) as follows:

```
package demo;

import java.util.ArrayList;
import java.util.Set;

import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.remote.DesiredCapabilities;

public class WINDOW_HANDLE_ITERATE_ArrayList_Firefox 
{
	public static void main(String[] args) throws Exception 
	{
	    System.setProperty("webdriver.gecko.driver", "C:\\Utility\\BrowserDrivers\\geckodriver.exe");
	    WebDriver driver =  new FirefoxDriver();
	    driver.get("http://www.google.com");
	    System.out.println("Page Title is : "+driver.getTitle());
	    String parent_window = driver.getWindowHandle();
	    System.out.println("First Window Handle is : "+driver.getWindowHandle());
	    ((JavascriptExecutor) driver).executeScript("window.open('http://facebook.com/');");
	    Thread.sleep(3000);
	    ((JavascriptExecutor) driver).executeScript("window.open('https://accounts.google.com');");
	    Thread.sleep(3000);
	    Set<String> allWindows_1 = driver.getWindowHandles();
	    System.out.println("Total Windows : "+allWindows_1.size());
	    ArrayList<String> tabs = new  ArrayList<>(allWindows_1);
	    System.out.println(tabs);
	    System.out.println("Still now focus on : "+driver.getWindowHandle());
	    System.out.println("Shifting focus to : "+tabs.get(1));
	    driver.switchTo().window(tabs.get(1));
	    Thread.sleep(5000);
	    System.out.println("First Child Handle : "+driver.getTitle()+ " : "+driver.getWindowHandle());
	    System.out.println("Closing First Child Handle : "+driver.getWindowHandle());
	    System.out.println("Still now focus on : "+driver.getWindowHandle());
	    driver.close();
	    System.out.println("Focus now on : "+driver.getWindowHandle());
	    System.out.println("Shifting focus to : "+tabs.get(2));
	    driver.switchTo().window(tabs.get(2));
	    Thread.sleep(5000);
	    System.out.println("Second Child Handle : "+driver.getTitle()+ " : "+driver.getWindowHandle());
	    System.out.println("Closing Second Child Handle : "+driver.getWindowHandle());
	    driver.close();
	    System.out.println("Focus now on : "+driver.getWindowHandle());
	    System.out.println("Shifting focus to : "+parent_window);
	    driver.switchTo().window(parent_window);
	    driver.quit();
	}
}

```

The Console Output is:

```
1504967227409	geckodriver	INFO	geckodriver 0.18.0
1504967227427	geckodriver	INFO	Listening on 127.0.0.1:17889
1504967227858	geckodriver::marionette	INFO	Starting browser C:\Program Files\Mozilla Firefox\firefox.exe with args ["-marionette"]
1504967229762	addons.xpi	WARN	Error parsing extensions state: [Exception... "Component returned failure code: 0x80520012 (NS_ERROR_FILE_NOT_FOUND) [amIAddonManagerStartup.readStartupData]"  nsresult: "0x80520012 (NS_ERROR_FILE_NOT_FOUND)"  location: "JS frame :: resource://gre/modules/addons/XPIProvider.jsm :: loadExtensionState :: line 1596"  data: no] Stack trace: loadExtensionState()@resource://gre/modules/addons/XPIProvider.jsm:1596 < getInstallState()@resource://gre/modules/addons/XPIProvider.jsm:1631 < checkForChanges()@resource://gre/modules/addons/XPIProvider.jsm:3152 < startup()@resource://gre/modules/addons/XPIProvider.jsm:2246 < callProvider()@resource://gre/modules/AddonManager.jsm:271 < _startProvider()@resource://gre/modules/AddonManager.jsm:741 < startup()@resource://gre/modules/AddonManager.jsm:908 < startup()@resource://gre/modules/AddonManager.jsm:3122 < observe()@jar:file:///C:/Program%20Files/Mozilla%20Firefox/omni.ja!/components/addonManager.js:65
1504967231743	Marionette	INFO	Enabled via --marionette
Unable to read VR Path Registry from C:\Users\AtechM_03\AppData\Local\openvr\openvrpaths.vrpath
[GPU 1916] WARNING: pipe error: 109: file c:/builds/moz2_slave/m-rel-w64-00000000000000000000/build/src/ipc/chromium/src/chrome/common/ipc_channel_win.cc, line 346
Unable to read VR Path Registry from C:\Users\AtechM_03\AppData\Local\openvr\openvrpaths.vrpath
[Child 3648] WARNING: pipe error: 109: file c:/builds/moz2_slave/m-rel-w64-00000000000000000000/build/src/ipc/chromium/src/chrome/common/ipc_channel_win.cc, line 346
1504967244440	Marionette	INFO	Listening on port 36307
1504967244448	Marionette	INFO	Listening on port 36307
1504967246659	Marionette	DEBUG	loaded listener.js
Sep 09, 2017 7:57:30 PM org.openqa.selenium.remote.ProtocolHandshake createSession
INFO: Detected dialect: W3C
1504967252712	Marionette	DEBUG	Received DOM event "beforeunload" for "about:blank"
1504967255919	Marionette	DEBUG	Received DOM event "pagehide" for "about:blank"
1504967255920	Marionette	DEBUG	Received DOM event "unload" for "about:blank"
1504967256205	Marionette	DEBUG	Received DOM event "DOMContentLoaded" for "https://www.google.co.in/?gfe_rd=cr&dcr=0&ei=UvqzWfjvLdP08wfxh7ToDg&gws_rd=ssl"
1504967257486	Marionette	DEBUG	Received observer notification "outer-window-destroyed" for "4294967301"
1504967257499	Marionette	DEBUG	Received DOM event "DOMContentLoaded" for "https://www.google.co.in/?gfe_rd=cr&dcr=0&ei=UvqzWfjvLdP08wfxh7ToDg&gws_rd=ssl"
1504967257505	Marionette	DEBUG	Received DOM event "pageshow" for "https://www.google.co.in/?gfe_rd=cr&dcr=0&ei=UvqzWfjvLdP08wfxh7ToDg&gws_rd=ssl"
1504967258072	Marionette	DEBUG	Received DOM event "pageshow" for "https://www.google.co.in/?gfe_rd=cr&dcr=0&ei=UvqzWfjvLdP08wfxh7ToDg&gws_rd=ssl"
Page Title is : Google
First Window Handle is : 4294967297
1504967259311	Marionette	DEBUG	loaded listener.js
1504967262622	Marionette	DEBUG	loaded listener.js
Total Windows : 3
[4294967297, 4294967305, 4294967312]
Still now focus on : 4294967297
Shifting focus to : 4294967305
First Child Handle : Facebook – log in or sign up : 4294967305
Closing First Child Handle : 4294967305
Still now focus on : 4294967305
Exception in thread "main" org.openqa.selenium.NoSuchWindowException: Current window does not have a content browser
Build info: version: '3.5.3', revision: 'a88d25fe6b', time: '2017-08-29T12:54:15.039Z'
System info: host: 'ATECHM-03', ip: '192.168.0.105', os.name: 'Windows 8', os.arch: 'amd64', os.version: '6.2', java.version: '1.8.0_144'
Driver info: org.openqa.selenium.firefox.FirefoxDriver
Capabilities [{moz:profile=C:\Users\ATECHM~1\AppData\Local\Temp\rust_mozprofile.LEe0mvCJwYYP, rotatable=false, timeouts={implicit=0, pageLoad=300000, script=30000}, pageLoadStrategy=normal, platform=XP, specificationLevel=0, moz:accessibilityChecks=false, acceptInsecureCerts=false, browserVersion=55.0.3, platformVersion=6.2, moz:processID=936, browserName=firefox, javascriptEnabled=true, platformName=XP}]
Session ID: df2123cb-1c86-43b6-8642-e01e77e954fd
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
	at java.lang.reflect.Constructor.newInstance(Unknown Source)
	at org.openqa.selenium.remote.http.W3CHttpResponseCodec.createException(W3CHttpResponseCodec.java:185)
	at org.openqa.selenium.remote.http.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:120)
	at org.openqa.selenium.remote.http.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:49)
	at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:164)
	at org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:82)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:646)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:703)
	at org.openqa.selenium.remote.RemoteWebDriver.getWindowHandle(RemoteWebDriver.java:563)
	at demo.WINDOW_HANDLE_ITERATE_ArrayList_Firefox.main(WINDOW_HANDLE_ITERATE_ArrayList_Firefox.java:37)

```

It is pretty clear from here, once the **first child window handle** is `Closed`, geckodriver is unable to hang-on with any content browser. Hence throws **`org.openqa.selenium.NoSuchWindowException: Current window does not have a content browser`**

This issue seems to have no relation with `Selenium`'s `click()` or `wait long enough`

**Comment by whimboo** [comment] 2017-09-11 07:03
The problem is on your side here. After closing a window you have to explicitly select another window to be able to continue. Otherwise, as you have seen here, you get the `NoSuchWindowException` which is expected.

That means in your example above the faulty line is `driver.getWindowHandle()` which is failing because it tries to operate on an invalid handle.

Also please note that your initial issue was around opening a new window/tab, but now you are trying to explain brokenness for closing a window/tab. So for `window.open` do not use `sleep(3000)` but a wait helper method which checks each eg 100ms if a new window handle has been opened. 

Lets make sure that we keep the focus on the initial issue. Thanks.

**Comment by Debanjan-B** [comment] 2017-09-11 10:34
@whimboo Thanks a ton !!!
That was my bad. I have rewritten the above mentioned code as per your guidelines and seems to work perfect.

```
package demo;

import java.util.ArrayList;
import java.util.Set;

import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;

public class WINDOW_HANDLE_ITERATE_ArrayList_Firefox 
{
	public static void main(String[] args) throws Exception 
	{
	    System.setProperty("webdriver.gecko.driver", "C:\\Utility\\BrowserDrivers\\geckodriver.exe");
	    WebDriver driver =  new FirefoxDriver();
	    driver.get("http://www.google.com");
	    System.out.println("Page Title is : "+driver.getTitle());
	    String parent_window = driver.getWindowHandle();
	    System.out.println("First Window Handle is : "+driver.getWindowHandle());
	    ((JavascriptExecutor) driver).executeScript("window.open('http://facebook.com/');");
	    ((JavascriptExecutor) driver).executeScript("window.open('https://accounts.google.com');");
	    WebDriverWait wait = new WebDriverWait(driver,3);
	    wait.until(ExpectedConditions.numberOfWindowsToBe(3));
	    Set<String> allWindows_1 = driver.getWindowHandles();
	    System.out.println("Total Windows : "+allWindows_1.size());
	    ArrayList<String> tabs = new  ArrayList<>(allWindows_1);
	    System.out.println(tabs);
	    System.out.println("Still now focus on : "+driver.getWindowHandle());
	    System.out.println("Shifting focus to : "+tabs.get(1));
	    driver.switchTo().window(tabs.get(1));
	    wait.until(ExpectedConditions.titleContains("Facebook"));
	    System.out.println("First Child Handle : "+driver.getTitle()+ " : "+driver.getWindowHandle());
	    System.out.println("Closing First Child Handle : "+driver.getWindowHandle());
	    driver.close();
	    System.out.println("Shifting focus to : "+tabs.get(2));
	    driver.switchTo().window(tabs.get(2));
	    wait.until(ExpectedConditions.titleContains("Google"));
	    System.out.println("Second Child Handle : "+driver.getTitle()+ " : "+driver.getWindowHandle());
	    System.out.println("Closing Second Child Handle : "+driver.getWindowHandle());
	    driver.close();
	    System.out.println("Shifting focus to : "+parent_window);
	    driver.switchTo().window(parent_window);
	    System.out.println("Parent Wundow Handle : "+driver.getTitle()+ " : "+driver.getWindowHandle());
	    System.out.println("Closing Parent Window Handle : "+driver.getWindowHandle());
	    driver.quit();
	}
}

```

Console Output:

```
Page Title is : Google
First Window Handle is : 2147483652
Total Windows : 3
[2147483652, 2147483660, 2147483663]
Still now focus on : 2147483652
Shifting focus to : 2147483660
First Child Handle : Facebook – log in or sign up : 2147483660
Closing First Child Handle : 2147483660
Shifting focus to : 2147483663
Second Child Handle : Sign in - Google Accounts : 2147483663
Closing Second Child Handle : 2147483663
Shifting focus to : 2147483652
Parent Wundow Handle : Google : 2147483652
Closing Parent Window Handle : 2147483652
```

**Comment by whimboo** [comment] 2017-09-11 12:27
Right, so all fine here. I'm going to close this issue.

**Closed by whimboo** 2017-09-11 12:27 UTC
Labels: marionette

**Comment by andreastt** [comment] 2017-09-11 14:02
> I don't understand! Why should this be a problem with window tracking and a changing window id? Here we have the fact that the click doesn't immediately open the window, so the expectation fails. Using Wait.until or whatever is possible in the Selenium binding should fix that.
>
> I wonder if click doesn't wait long enough, even we make use of the animation frame injection, or the window opens after all events have been processed.

I see, that is a better explanation.

**Comment by Debanjan-B** [comment] 2017-09-11 15:15
@whimboo @andreastt Thanks. With a suitable clause in `expected_conditions`, things seems to be working fine.
