### ISSUE TITLE
regression: geckodriver hung after interact with prompt from beforeunload event

### ISSUE THREAD

**Issue by kovalev007** [mozilla/geckodriver#1653] opened 2019-11-14 05:40 UTC
## System
* Version: geckodriver-v0.26.0-win64
* Platform: windows 10
* Selenium: java 3.141.59

## Testcase
https://output.jsbin.com/fixoxun
1. click on button with text "open"
2. wait new window opened
3. click on button with text "close"
4. accept user promt
5. wait new window closed

## mozregression
firefox 2019-06-13 - test works without problem
firefox 2019-06-14 - test hung

https://hg.mozilla.org/mozilla-central/pushloghtml?fromchange=d72ab884f0394d6e9ab723f03bd43c90a84d7e5b&tochange=b3a69dff7e25f1c1107520c238dd282405afaf92

[mozregression_log_from_2019-06-13_to_2019-06-14.txt](https://github.com/mozilla/geckodriver/files/3844735/mozregression_log_from_2019-06-13_to_2019-06-14.txt)
[test.zip](https://github.com/mozilla/geckodriver/files/3844739/test.zip) - archive with test on java and jar for execute via mozregression

**Comment by kovalev007** [comment] 2019-11-14 05:43
@whimboo we discussed about it on IRC. Should I provide more information?

**Comment by whimboo** [comment] 2019-11-14 08:33
@kovalev007 the mozregression log only contains the beginning of the output. Would you mind to paste the last lines where it outputs the exact regressor? That would be important.

As talked about yesterday even we do not support enabling the `beforeunload` events right now, this is a newer regression in Firefox 69. As such it is not a dupe of issue #1563.

Also please attach that part of the geckodriver log which shows the interaction with the prompt, means when it gets opened, closed, and then failed. Thanks.

**Comment by kovalev007** [comment] 2019-11-14 08:57
@whimboo the mozregression log contains the full output. after last line I wait 5 - 10 minutes and nothing happens. geckodriver hung.

Please see additional example with 2019-06-13 and 2019-06-15.

[mozregression_log_2019-06-13_good_and_2019-06-15_bad.txt](https://github.com/mozilla/geckodriver/files/3845537/mozregression_log_2019-06-13_good_and_2019-06-15_bad.txt)

**Comment by whimboo** [comment] 2019-11-19 09:35
In that situation can you just kill the browser process or close it yourself? That should also mark the test as failed, which instructs mozregression that it is a broken build. We really have to get further into that merge commit to figure out what has been causing it. Thanks.

**Comment by kovalev007** [comment] 2019-11-19 22:55
@whimboo you're right.

Full log now available.
[full_mozregression_log_from_2019-06-13_to_2019-06-14.txt](https://github.com/mozilla/geckodriver/files/3866453/full_mozregression_log_from_2019-06-13_to_2019-06-14.txt)

Last good revision: 09614cb3a896ab3be71ccc44d7663eb5454cf5cf
First bad revision: 4651b31ffe5c012b5112fc3047c29d0d4a8f9594
https://hg.mozilla.org/integration/autoland/pushloghtml?fromchange=09614cb3a896ab3be71ccc44d7663eb5454cf5cf&tochange=4651b31ffe5c012b5112fc3047c29d0d4a8f9594

**Comment by whimboo** [comment] 2019-11-21 16:30
So it's the same patch again. Would you mind doing the `hg up -r` dance again and check which of the two first changesets are causing that for you?

**Comment by kovalev007** [comment] 2019-11-22 03:18
Second changeset caused this. [5d6397e990cbc374be49baaa4fc6622dfed18119](https://hg.mozilla.org/integration/autoland/rev/5d6397e990cbc374be49baaa4fc6622dfed18119)

**Comment by whimboo** [comment] 2019-12-03 15:20
Ok, that's good to know. Would you mind filing a bug in Bugzilla so that we can continue the investigation over there? As such we can also set the above bug as the regressor. Thanks!

**Comment by kovalev007** [comment] 2019-12-04 03:03
https://bugzilla.mozilla.org/show_bug.cgi?id=1601160

**Comment by whimboo** [comment] 2021-02-22 07:31
That one got actually fixed already a while ago for Firefox 77.

**Closed by whimboo** 2021-02-22 07:31 UTC
Labels: marionette
