### ISSUE TITLE
Why there is no w32 version to download in v.19.0 release ?

### ISSUE THREAD

**Issue by boquedron** [mozilla/geckodriver#969] opened 2017-09-22 10:07 UTC
## Documentation issue ?

There is **no w32** (windows 32 bits) version to download for version v.19.0. You can check it  in https://github.com/mozilla/geckodriver/releases/tag/v0.19.0 in Downloads section. Is that OK ? I see no references in the release notes.

Thanks in advance

**Comment by andreastt** [comment] 2017-09-22 10:31
Duplicate of https://github.com/mozilla/geckodriver/issues/951.

**Closed by andreastt** 2017-09-22 10:31 UTC
