### ISSUE TITLE
Failed to decode response from marionette when trying to getWindowHandles

### ISSUE THREAD

**Issue by mukunduashok** [mozilla/geckodriver#1609] opened 2019-09-02 12:02 UTC
## System

* Version: 0.24.0 (geckodriver version)
* Platform: Windows 10
* Firefox: 70.0b2 (Firefox developer edition)
* Selenium: 3.141.0 (Python). Error occurs with in 3.14 (older one) too.

## Testcase
The error happens only when run in a in-house server VM (Not using the docker). Works well in local. 
Steps:
1. Install Firefox
2. Launch Firefox with extension using geckodriver (URL - https://www.google.com)
3. Open a web page in new tab
<Some web socket calls to extension happens>
4. Get Window handles to switch context to the new tab (The error occurs)
(Few previous results suggested for a sleep time before sending the command. I've tried adding a sleep time of up to 30 seconds but in vein)

**Note:** 
1. I've seen this issue occurring during getCurrentUrl calls too apart from getWindowHandles
2. The issue is not happening every time
3. Nearly 10-15 runs fail out of the 45 runs that trigger as part of daily schedule

I've seen this error in many google results and most of them are related to docker runs. And the scenarios I read are different from the one I see (And few of them are marked as duplicate of https://github.com/mozilla/geckodriver/issues/1559 which is also a docker use case). So raised this as a separate bug. 

Driver Capabilities:
{ 'moz:geckodriverVersion': '0.24.0', 'browserName': 'firefox', 'acceptInsecureCerts': True, 'moz:headless': False, 'moz:buildID': '20190830040415', 'moz:accessibilityChecks': False, 'platformName': 'windows', 'rotatable': False, 'moz:profile': 'C:\\Users\\automation\\AppData\\Local\\Temp\\rust_mozprofile.qFqM77i7lrOl', 'moz:useNonSpecCompliantPointerOrigin': False, 'moz:webdriverClick': True, 'strictFileInteractability': False, 'platformVersion': '10.0', 'timeouts': { 'implicit': 0, 'pageLoad': 300000, 'script': 30000 }, 'moz:processID': 10944, 'browserVersion': '70.0', 'setWindowRect': True, 'unhandledPromptBehavior': 'dismiss and notify', 'pageLoadStrategy': 'normal', 'moz:shutdownTimeout': 60000 }

## Stacktrace from geckodriver.log

###!!! [Child][MessageChannel::SendAndWait] Error: Channel error: cannot send/recv

1567423345606	webdriver::server	DEBUG	-> GET /session/563179a8-7712-4b46-858f-14b79104b7ed/window/handles 
1567423345606	webdriver::server	DEBUG	Deleting session
1567423346684	geckodriver::marionette	DEBUG	Browser process stopped: exit code: 0
1567423346856	webdriver::server	DEBUG	<- 500 Internal Server Error {"value":{"error":"unknown error","message":"Failed to decode response from marionette","stacktrace":""}}
1567423348903	webdriver::server	DEBUG	-> DELETE /session/563179a8-7712-4b46-858f-14b79104b7ed 
1567423348903	webdriver::server	DEBUG	<- 404 Not Found {"value":{"error":"invalid session id","message":"Tried to run command without establishing a connection","stacktrace":""}}

## Trace-level log
Attached - geckodriver.log
[geckodriver.log](https://github.com/mozilla/geckodriver/files/3565918/geckodriver.log)

Please help and let me know if more info is required.

**Comment by whimboo** [comment] 2019-09-04 13:21
The reason here is that the tab you are switching to has crashed. Please check https://firefox-source-docs.mozilla.org/testing/geckodriver/CrashReports.html in how to extract a crash report. It will help me to diagnose the problem. Thanks.

**Comment by mukunduashok** [comment] 2019-09-04 18:59
Hi @whimboo 
I already create an automation profile for my tests. Piece of code below

`driver_profile = webdriver.FirefoxProfile(profile_path)
driver_profile.set_preference("plugins.load_appdir_plugins", True)
driver_profile.set_preference("intl.accept_languages", self._lang)
driver_profile.set_preference("browser.helperApps.neverAsk.saveToDisk", "application/zip;")
driver_options = Options()
driver_options.set_preference("browser.link.open_newwindow.restriction", 0)
driver_options.set_preference("browser.link.open_newwindow", 3)

driver_options.log.level = "trace"
self._driver = webdriver.Firefox(firefox_profile=driver_profile, firefox_binary=binary, 
capabilities=caps, options=driver_options, service_log_path=self._geckodriver_log, 
service_args=["--marionette-port", "2828"], timeout=120)`

The profile is created. But I don't see the crash logs in minidumps folder. Have compressed and attached the entire profile directory (Removed the test extension before upload)
[rauo24qk.automation_ff_profile.zip](https://github.com/mozilla/geckodriver/files/3576067/rauo24qk.automation_ff_profile.zip)

If the steps are incorrect or if you require more info, please let me know.

**Comment by mukunduashok** [comment] 2019-09-05 05:49
To add more, attaching one more instance of such failure with different trace. 
Two attachments - 1. geckodriver.log and 2.automation_profile directory
[geckodriver.log](https://github.com/mozilla/geckodriver/files/3577603/geckodriver.log)
[u4cldtml.automation_ff_profile.zip](https://github.com/mozilla/geckodriver/files/3577605/u4cldtml.automation_ff_profile.zip)

@whimboo  - In conflict to the geckodriver.log, I still see the second tab existing and the screenshot shows the tab is active. (The screenshot is taken before script exit)

**Comment by whimboo** [comment] 2019-09-09 08:17
> I already create an automation profile for my tests. Piece of code below
> 
> `driver_profile = webdriver.FirefoxProfile(profile_path)

That's not what the documentation is referencing. As said geckodriver will remove a profile (including the minidump files) as generated by Selenium. Instead use the Firefox options, and specify a path to the given profile.

> @whimboo - In conflict to the geckodriver.log, I still see the second tab existing and the screenshot shows the tab is active. (The screenshot is taken before script exit)

There is a crash when the click command is performed. Indeed a new tab could have been opened, but it should have been crashed immediately. 

So please check the referenced documentation again. I'm still interested on this crash report. Thanks!

**Comment by mukunduashok** [comment] 2019-09-10 11:00
@whimboo I've followed the same steps as mentioned in the https://firefox-source-docs.mozilla.org/testing/geckodriver/CrashReports.html.
Below is the code snippet

```
# Setup the Firefox driver
binary = FirefoxBinary(self._browser_path)

# Initialize FF profile prefs
user_prefs = (
            'user_pref("browser.shell.checkDefaultBrowser", false);',
            'user_pref("xpinstall.signatures.required", false);',
            'user_pref("browser.tabs.remote.force-enable", true);',
            'user_pref("toolkit.startup.max_resumed_crashes", 99999999);',
            'user_pref("browser.usedOnWindows10", true);',
            'user_pref("datareporting.healthreport.service.firstRun", false);',
            'user_pref("toolkit.telemetry.reportingpolicy.firstRun", false);',
            'user_pref("browser.reader.detectedFirstArticle", false);',
            'user_pref("browser.startup.homepage_override.mstone", "ignore");',
            'user_pref("startup.homepage_welcome_url",  "about:blank");',
            'user_pref("startup.homepage_welcome_url.additional",  "about:blank");',
            'user_pref("app.update.enabled", false);',
            'user_pref("dom.webnotifications.enabled", false);',
            'user_pref("app.update.disabledForTesting", true);',
            'user_pref("browser.link.open_newwindow.restriction", 0);',
            'user_pref("browser.link.open_newwindow", 3);',
        )        
with open(os.path.join(profile_path, 'prefs.js'), 'w') as prefs:
    prefs.write('\n'.join(user_prefs))

# Set Firefox Options
driver_options = Options()
driver_options.add_argument("-profile")
driver_options.add_argument(self.profile_path)  # /Users/ashok_mb/Desktop/Working/Output/automation_ff_profile
driver_options.log.level = "trace"

# Launch Firefox webdriver
self._driver = webdriver.Firefox(firefox_binary=binary, capabilities=caps, options=driver_options, service_log_path=self._geckodriver_log, service_args=["--marionette-port", "2828"], timeout=120)

# Install extensions
for extn in self._extn_list:  # [<path_of_the_extension>]
    self._driver.install_addon(extn)
```

Please let me know if you still see something wrong with the code snippet.
I still do not see the crash logs in minidumps folder. 
I'm again attaching the recent logs - automation profile directory (Compressed without test extension) and the geckodriver.log.

Let me know if any. Please help. Thanks!

[geckodriver.log](https://github.com/mozilla/geckodriver/files/3595305/geckodriver.log)

[automation_ff_profile.zip](https://github.com/mozilla/geckodriver/files/3595303/automation_ff_profile.zip)

**Comment by whimboo** [comment] 2019-09-13 11:10
When I search for `A content process crashed and MOZ_CRASHREPORTER_SHUTDOWN is set, shutting down` in the recently attached `geckodriver.log` file I cannot find any instance of it. So I assume that the crash actually did not happen. But something else caused Firefox to exit. Maybe the crash information hasn't been caught. Would you mind running the attached code a couple of times, and check for each iteration if the above crash message is contained in the log file? If it is, then minidump files will be present. Otherwise not.

Feel free to also use a debug version of Firefox Nightly to verify that. It will also output way more details, which might give us an idea what it could be. Here details for downloading it:

Go to: https://treeherder.mozilla.org/#/jobs?repo=mozilla-central&searchStr=windows%2Cbuild%2Cdebug

Select on of the `B` jobs for your platform. Not sure if you have 32bit or 64bit Firefox versions running. In the opening lower pane you will see `job details`. Click on it, and find the target.zip file, which only needs to be extracted.

**Comment by whimboo** [comment] 2019-09-13 11:24
I just noticed that there is also the `MOZ_CRASHREPORTER_DATA_DIRECTORY` environment variable. Would you mind trying to set this one to a custom path on your disk for running your original code with a profile as generated by geckodriver? Maybe it's not necessary to have a custom profile.

**Comment by mukunduashok** [comment] 2019-09-14 15:55
@whimboo - Have made few runs with nightly debug builds. I'm attaching the geckodriver.log along with the respective automation profiles (4 Sample with MOZ_CRASHREPORTER_SHUTDOWN text).

The file is too big now. So sharing the google drive link
[https://drive.google.com/file/d/1a7n3vySa6coh1-DDXVbaabUaoWsiVQsV/view?usp=sharing](url)

I noticed few logs which sounded alarming to me. Just FYR below
```
[GPU 8700, Main Thread] WARNING: Shutting down GPU process early due to a crash!: file z:/build/build/src/gfx/ipc/GPUParent.cpp, line 494
[Socket 7644, Main Thread] WARNING: Shutting down Socket process early due to a crash!: file z:/build/build/src/netwerk/ipc/SocketProcessChild.cpp, line 102
```

And one more info that none of the nightly build logs has this trace. I saw these in the FF dev builds
```
568389922666	geckodriver::marionette	DEBUG	Browser process stopped: exit code: 0
1568389922671	webdriver::server	DEBUG	<- 500 Internal Server Error {"value":{"error":"unknown error","message":"Failed to decode response from marionette","stacktrace":""}}
1568390667833	webdriver::server	DEBUG	-> GET /session/a7cab798-7fbb-4a85-80f2-f90a22b4697c/window/handles 
1568390667833	webdriver::server	DEBUG	<- 404 Not Found {"value":{"error":"invalid session id","message":"Tried to run command without establishing a connection","stacktrace":""}}
```

Regarding - MOZ_CRASHREPORTER_DATA_DIRECTORY, Should I just have to set it like (Say JAVA_HOME) other environment variables in Windows or it is different. Could you please help if there is a command line way to do this. 

Please help. Thanks!

**Comment by whimboo** [comment] 2019-09-16 09:47
Yes, set `MOZ_CRASHREPORTER_DATA_DIRECTORY` inside the environmental settings of Windows to a path outside of your testing environment. If that ENV works, it would make it much more easier to grab the minidump files, and I will update our docs. Thanks.

**Comment by whimboo** [comment] 2019-09-16 09:48
Also regarding the GFX output, please check the version of your graphics driver. What exactly is it? Are there updates available for it which haven't been installed yet? Please check that. Maybe we need to blacklist a specific version of the driver. But make sure to remember which version fails.

**Comment by mukunduashok** [comment] 2019-09-18 09:44
Hi @whimboo 

Bad news again. Have added the MOZ_CRASHREPORTER_DATA_DIRECTORY environment variable. But still didn't see the crash logs in this folder. Power-shell snippet used to add environment variable is below.

```
# Setting MOZ_CRASHREPORTER_DATA_DIRECTORY
New-Item -ItemType directory -Path "C:\Working\Output\MOZ_CRASHREPORTER"
[environment]::SetEnvironmentVariable("MOZ_CRASHREPORTER_DATA_DIRECTORY", "C:\Working\Output\MOZ_CRASHREPORTER", "Machine")

# Getting MOZ_CRASHREPORTER_DATA_DIRECTORY
Write-Output "MOZ_CRASHREPORTER_DATA_DIRECTORY is set to:" | Add-Content $LOG_FILE
[environment]::GetEnvironmentVariable("MOZ_CRASHREPORTER_DATA_DIRECTORY", "Machine") | Add-Content $LOG_FILE
```
**Output:**
"C:\Working\Output\MOZ_CRASHREPORTER" directory is empty.

Attaching the geckodriver logs for recent runs (Same as before) 
[geckodriver_logs.zip](https://github.com/mozilla/geckodriver/files/3625601/geckodriver_logs.zip)
[powershell_autologs_tc_logs_removed.log](https://github.com/mozilla/geckodriver/files/3625606/powershell_autologs_tc_logs_removed.log)

Regarding GFX, the automations run in the VMWare ESX servers. And doesn't run with graphics card itself. Should this be a problem for recent Firefox versions, can I try with any workarounds like setting any FF prefs ?

Please help. Thanks!

**Comment by mukunduashok** [comment] 2019-09-24 13:54
@whimboo - Did u get any chance to look in to this item ? Please help!

**Comment by whimboo** [comment] 2019-09-30 09:23
Where do you exactly set this environment variable? Does that happen before Firefox gets started? We have to be sure that Firefox knows about it. Maybe you can set it manually on the VM before running your tests?

Do you know which version of Firefox had this problem first? Maybe it's a regression which we would have to find out.

**Comment by mukunduashok** [comment] 2019-10-05 04:46
@whimboo  I've tried setting the environment variable manually too. Also using the power-shell snippet  above. I'm already setting this just before the tests begin.
I remember until Firefox 65, the tests ran without any issues. This behavior should be from version 66.

**Comment by whimboo** [comment] 2019-10-08 12:48
Could you please test Firefox 65 again please? If it works please have a look at the [Firefox 66 devedition build 1](https://archive.mozilla.org/pub/devedition/releases/66.0b1/win64/en-US/). If that fails we might have to do some more checks to figure out when it started failing.

**Comment by whimboo** [comment] 2019-10-25 06:56
No further reply from the reporter. Closing the issue for now.

**Closed by whimboo** 2019-10-25 06:56 UTC
Labels: firefox, waiting for reporter feedback

**Comment by get2suren** [comment] 2019-10-31 09:28
@whimboo 
Could we re-open this issue again ? i can provide the necessary information needed.

**Comment by whimboo** [comment] 2019-11-01 08:46
@get2suren your issue might be different. So please create your own issue with all the requested details. Thanks!

**Comment by mukunduashok** [comment] 2019-11-01 09:30
@whimboo  - @get2suren is working on the same issue and he has findings about the browser version for the same issue. Request to re-open the ticket if possible. Thanks!

**Comment by whimboo** [comment] 2019-11-01 10:01
Well, update the issue with your findings and we can consider to reopen the issue.

**Comment by get2suren** [comment] 2019-11-01 16:55
@whimboo  I have tested with different browsers to reproduce the issue.
Geko driver version used - 0.26.0
Ran the execution starting with browser version 65, but the above mentioned issue occurs only from Firefox developer edition 69.0b16.Please revert if you need more information.
Thanks

**Comment by whimboo** [comment] 2019-11-01 21:07
So you are saying that 69.0b15 is still fine?

**Comment by get2suren** [comment] 2019-11-04 09:04
Hi @whimboo ,
I have not tested all the minor versions, May be i will track down the minor version's too, to find out the exact build number which cause this issue , if that is what you wanted to find out ?

**Comment by get2suren** [comment] 2019-11-05 10:53
Hi @whimboo ,
Tried with version 69.b01 and the issue is reproducible whereas 68.b014 it is not , So we can say that the issue is from build 69.b01

**Comment by whimboo** [comment] 2019-11-05 12:06
So your last comment somewhat conflicts with the one from 4 days ago. Does it start late in the 69 beta cycle, or already with the 69.0b1? If it is the latter more work would be necessary to nail that down.

**Comment by get2suren** [comment] 2019-11-06 14:16
@whimboo am not conflicting am trying to find out from which build the issue actually started to occur , we tested and found out that it started from 69.b01

**Comment by get2suren** [comment] 2019-11-11 05:28
@whimboo Should i try running in any other builds to repro ?

**Comment by whimboo** [comment] 2019-11-11 09:11
Sorry for being late in my reply. Yes, you should as best do a regression test with Nightly builds. There are 6 weeks of work to trim down. 

Given the [release calendar](https://wiki.mozilla.org/RapidRelease/Calendar) version 69 was available as Nightly between the dates 2019-05-13 and 2019-07-01. I would propose you to install [mozdownload](https://pypi.org/project/mozdownload/) for retrieving the different versions of Firefox. For the Nightly from June 1st run the following:

> mozdownload -t daily --date 2019-06-01 --ext zip

As best use the zip file because it only requires you to unzip the files, and you can start directly. It won't make changes to the Windows registry.

If that build failed go on with May 22nd, or otherwise June 15th. Continue with that until you hit a specific day. 

Let me know if you have problems.

**Comment by get2suren** [comment] 2019-11-14 10:47
@whimboo Am doing all possible test to narrow down build no from when the actual issue started, Please bear with me

**Comment by whimboo** [comment] 2019-11-19 09:10
Sorry, but I don't understand your last comment. Maybe you can clarify?
