### ISSUE TITLE
Driver doesn't execute api commands

### ISSUE THREAD

**Issue by AliakseiBychyk** [mozilla/geckodriver#413] opened 2017-01-03 10:07 UTC
Firefox version 50.1.0
Platform Windows 10
geckodriver 0.11.1 w64
selenium-server-standalone-jar v.3.0.1

I have faced some troubles with execution such code with Nightwatch on Firefox: 

        this.api.element('css selector', this.elements.submitButton.selector, result => {
          this.api.moveTo(result.value.ELEMENT, 5, 5, () => {
            this.api.mouseButtonClick('left');
          });
        });

The browser has completely ignored these commands.

**Comment by AutomatedTester** [comment] 2017-01-03 11:59
duplicate of #233

**Closed by AutomatedTester** 2017-01-03 11:59 UTC
