### ISSUE TITLE
help me on Mac geckodriver

### ISSUE THREAD

**Issue by Demidof** [mozilla/geckodriver#2129] opened 2023-08-16 16:04 UTC
## System

* Version: 
* Platform: 
* Firefox: 
* Selenium: 

Can you tell me how to install it on a mac? I installed tbselenium, but I can't install geckodriver. I ask for help

**Comment by whimboo** [comment] 2023-08-16 16:09
Duplicate of #2128.

**Closed by whimboo** 2023-08-16 16:09 UTC
