### ISSUE TITLE
Firefox browser remains minimised when Windows is locked/disconnected 

### ISSUE THREAD

**Issue by realfaisalk** [mozilla/geckodriver#872] opened 2017-08-15 11:30 UTC
**Firefox Version**
55.0 (32-bit)

**Platform**
Windows 10 version - 1703, build 15063.138

**Other**
geckodriver 0.18.0
Selenium WebDriver 3.4.0 (C# DotNet)

## Testcase
Could be related to #703?
If I run my test cases on a Windows 10 VM via Test City, If I am not physically logged into the machine, then Firefox is started minimised (even though I have the code `driver.Manage().Window.Maximize();`

If I log in part way through the tests then I can see that FF is open but in minimise mode. The only way I can bring the browser up is by having to go to the Firefox process in Task Manager, right-click and select "Maximise"
![ff_maximise](https://user-images.githubusercontent.com/23498757/29314315-5ea85d4e-81b5-11e7-8c1b-52c0729367b7.png)

**As a consequence all tests fail with a Timeout exception**

If I am logged in then FF browser is maximised.

This was not an issue with FF v54 and geckodriver 0.16.0
## Stacktrace

N/A

## Trace-level log

When I can figure out how to change the logging level in C# from Debug....

**Comment by whimboo** [comment] 2017-08-16 15:43
Does a test before minimizes the window? Or is that visible when starting the first test? The latter I cannot believe because it doesn't happen in all of our cases.

So is that a problem with geckodriver 0.18 and Firefox 54? Or did it start with Firefox 55? If the latter is the case could you check the beta releases and tell us which version first showed this behavior? The builds can be found here: http://archive.mozilla.org/pub/firefox/releases/. Thanks.

**Comment by eugenedani** [comment] 2017-08-17 08:49
I suppose we have the same issue. FF window is not open at all from the begging of test script. Our test error screenshot looks like this
![ff55_issue](https://user-images.githubusercontent.com/30838245/29403472-b32add40-8338-11e7-805f-fe240904460c.png)

We run it like this
We run Selenium HUB on one VM (virtual machine)  and Selenium Node on another VM with Windows 10.  If I connected to Selenium Node VM by Remote Desktop test is run as expected. I can see it.
When I close Remote Desktop without log off, just close it, test is failed and FF window is not open (see screenshot).  If I connected to VM by Remote Desktop during test running I can see FF icon in Windows task bar but no FF window is open and I cannot open it by mouse

Hope it will help to reproduce it

**Comment by eugenedani** [comment] 2017-08-17 09:36
Also I checked the beta releases. It work as expected with FF 54.0.1 but stop working from FF55.0b1

**Comment by eugenedani** [comment] 2017-08-18 14:10
Hi @whimboo, any updates?
Looks like the same issue is with FF55 headless mode on linux. in our case Ubuntu16.

**Comment by eugenedani** [comment] 2017-08-24 09:40
Ok, if someone has the same issue and  is still looking for solution. 
The issue appears if you use webDriver.manage().window().maximize();
Firefox reaction on maximize() method was changed. More information is here [https://bugzilla.mozilla.org/show_bug.cgi?id=1391691](url)

If you use WebDriver like this
`WebDriver webDriver = FirefoxDriver();
webDriver.manage().window().maximize();`
when if you run tests on locked/disconnected Windows virtual machine Firefox will be minimized and Firefox behavior will be as I described in previous posts.

So there are 2 ways how to resolve the issue.
1. do not use maximize() method
2. check browser window size and  use maximize() when window is not maximized. Something like this
`int widthBeforeMaximize = webDriver.manage().window().getSize().width;
webDriver.manage().window().maximize();
if (webDriver.manage().window().getSize().width < widthBeforeMaximize) {
    webDriver.manage().window().maximize();
 }`
because in FF55 and 56 maximize() method will return the window to normal window state if the window is already maximized.

It should be fixed in FF57 [https://bugzilla.mozilla.org/show_bug.cgi?id=1391691](url)

**Comment by andreastt** [comment] 2017-08-25 14:48
If this is the problem:

> ```
> int widthBeforeMaximize = webDriver.manage().window().getSize().width;
> webDriver.manage().window().maximize();
> if (webDriver.manage().window().getSize().width < widthBeforeMaximize) {
> webDriver.manage().window().maximize();
> }
> ```

Then https://bugzilla.mozilla.org/show_bug.cgi?id=1391691 will have fixed this.

**Closed by andreastt** 2017-08-25 14:48 UTC
Labels: waiting for reporter feedback
