### ISSUE TITLE
 WebDriver permission denied with geckodriver

### ISSUE THREAD

**Issue by barcmoehm** [mozilla/geckodriver#1408] opened 2018-10-25 12:21 UTC
Hi,
I currently face problems when trying to run my tests in headless mode. The test suite stops execution and I do get a WebDriverException with message 'permission denied'. 

When googling this issue, I found that this used to be a problem with firefox security settings. This is why I included the profile for firefox. I also thought that it could have to do with insufficient permissions on the driver executable but I verified that the geckodriver.exe can be executed from within java.

Running headless mode in chrome does work, and running the tests in a non-headless firefox it works too. 

## System

* Version: 0.23.0
* Platform: Windows 10
* Firefox: 63 + Nightly
* Selenium: 3.14.0

## Testcase
(Note: I did assume that if there was something wrong with my test cases, the exception would occur in them and not when creating a new WebDriver instance)
```
FirefoxOptions options = new FirefoxOptions();
options.setProfile(createFirefoxProfile());
options.setHeadless(true);
options.addArguments("-silent");
options.setLogLevel(FirefoxDriverLogLevel.TRACE);
return new FirefoxDriver(options); <<< Exception

  private FirefoxProfile createFirefoxProfile() {
        FirefoxProfile profile = new FirefoxProfile();
        profile.setPreference("capability.policy.default.HTMLDocument.readyState", "allAccess");
        profile.setPreference("capability.policy.default.HTMLDocument.compatMode", "allAccess");
        profile.setPreference("capability.policy.default.Document.compatMode", "allAccess");
        profile.setPreference("capability.policy.default.Location.href", "allAccess");
        profile.setPreference("capability.policy.default.Window.pageXOffset", "allAccess");
        profile.setPreference("capability.policy.default.Window.pageYOffset", "allAccess");
        profile.setPreference("capability.policy.default.Window.frameElement", "allAccess");
        profile.setPreference("capability.policy.default.Window.frameElement.get", "allAccess");
        profile.setPreference("capability.policy.default.Window.QueryInterface", "allAccess");
        profile.setPreference("capability.policy.default.Window.mozInnerScreenY", "allAccess");
        profile.setPreference("capability.policy.default.Window.mozInnerScreenX", "allAccess");
        return profile;
    }
```

## Stacktrace

```
org.openqa.selenium.WebDriverException: permission denied
Build info: version: '3.14.0', revision: 'aacccce0', time: '2018-08-02T20:19:58.91Z'
System info: host: 'ITEM-S71517', ip: '172.16.10.1', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_181'
Driver info: driver.version: FirefoxDriver
remote stacktrace: 

	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.openqa.selenium.remote.W3CHandshakeResponse.lambda$new$0(W3CHandshakeResponse.java:57)
	at org.openqa.selenium.remote.W3CHandshakeResponse.lambda$getResponseFunction$2(W3CHandshakeResponse.java:104)
	at org.openqa.selenium.remote.ProtocolHandshake.lambda$createSession$0(ProtocolHandshake.java:122)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
	at java.util.Spliterators$ArraySpliterator.tryAdvance(Spliterators.java:958)
	at java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:126)
	at java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:498)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:485)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.FindOps$FindOp.evaluateSequential(FindOps.java:152)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.findFirst(ReferencePipeline.java:464)
	at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:125)
	at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:73)
	at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:136)
	at org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:83)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:548)
	at org.openqa.selenium.remote.RemoteWebDriver.startSession(RemoteWebDriver.java:212)
	at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:130)
	at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:125)
	at com.project.test.selenium.SeleniumBase.setUp(SeleniumBase.java:184)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:564)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:213)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:138)
	at org.testng.internal.TestMethodWorker.invokeBeforeClassMethods(TestMethodWorker.java:175)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:107)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1198)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1123)
	at org.testng.TestNG.run(TestNG.java:1031)
	at org.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:72)
	at org.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:123)

```

## Trace-level log

[tracelog.txt](https://github.com/mozilla/geckodriver/files/2514696/tracelog.txt)

**Comment by andreastt** [comment] 2018-10-25 20:15
You are also modifying a whole lot of preferences that I can’t speak to what do… does it work _without_ modifying those prefs?

**Comment by whimboo** [comment] 2018-10-26 07:09
Could you please attach a [trace-level log] from geckodriver? Read more about reporting actionable bugs in our [contribution guidelines].

[trace-level log]: https://firefox-source-docs.mozilla.org/testing/geckodriver/geckodriver/TraceLogs.html
[contribution guidelines]: https://firefox-source-docs.mozilla.org/testing/geckodriver/geckodriver/Bugs.html

**Comment by barcmoehm** [comment] 2018-10-26 08:41
@andreastt: Regarding your first comment: yes I'am using a official build (the trace log is from ff63 btw). You can look at the [tracelog.txt](https://github.com/mozilla/geckodriver/files/2518379/tracelog.txt) for the nightly build, it has the same error.

And to answer your second comment: they do not change anything. In fact, I'm not even sure these preferences exist anymore. They were once a fix for similar error types (see [this issue](https://github.com/seleniumhq/selenium-google-code-issue-archive/issues/2863#issuecomment-191967813)). Deleting them has no effect, the error stays the same. I just included them for completeness sake.

Some further information: I'am behind a corporate proxy

@whimboo I'm sorry, but it seems that there are no trace informations for the erroneous run. What you see in the log is all that was printed. I did set the log level to trace and I do see trace information in non headless mode. The first trace information in a successful run seems to beinformation about the created session and the error seems to be failing to create a new session.

**Comment by whimboo** [comment] 2018-10-29 13:52
@barcmoehm that referenced trace log in your last comment is interesting! It shows that Marionette doesn't see the `sessionstore-windows-restored` notification during the startup of Firefox. As such it continues to wait, and it finally fails to create the session.

Note that we also see this problem in our CI more or less: https://bugzilla.mozilla.org/show_bug.cgi?id=1382162. Sadly we haven't been able yet to constantly reproduce the issue.

Can you please clearly describe your system setup, and which version of tools you are using (including if those are 32bit or 64bits)? Maybe we can narrow down what might cause it. Thanks!

**Comment by barcmoehm** [comment] 2018-10-30 08:53
| Tool|      Version|  |
|----------|-------------|----|
| Windows |10.0.17134 |  64bit |
| Firefox |    63   |   64bit |
| Firefox  Nightly | 65.0a1| 64bit|
| Geckodriver | 0.23.0 | 32bit |
| Java Bindings Client | 3.14.0 | |
| Java Bindings Server | 3.14.0 | | 
| Java |  1.8.0_191 | 64bit |
| Maven | 3.5.4 |  32bit |
| TestNG | 6.8 | | 

If something of interest is missing, let me know. 
There are also some more lines in the tracelog of the newest nightly build: 

```
1540830568357   mozrunner::runner       DEBUG   Killing process 120780
1540830568357   webdriver::server       DEBUG   <- 500 Internal Server Error {"value":{"error":"unknown error","message":"permission denied","stacktrace":""}}
```
[20182910_tracelog.txt](https://github.com/mozilla/geckodriver/files/2528651/20182910_tracelog.txt)

**Comment by whimboo** [comment] 2018-10-30 13:23
Is the attached log from the last comment of a Firefox Nightly build? I tried to check the failure in `AboutPrivateBrowsingHandler.jsm` but that file doesn't have that many lines as listed in the log. Can you please try to run again in a recent Nightly build?

Btw. when this problem occurs, what does Firefox display? Is it just an empty page? Also what happens when you resize Firefox at this time?

**Comment by barcmoehm** [comment] 2018-11-01 10:02
Yes, that was form a Nightly build.  The most recent build (i.e. the one that I updated just minutes ago) does generate the same log.

I do not know what it displays because it runs headless. And since the problem happens when the driver is instantiated, I can't do anything like resizing, screenshotting etc.

**Comment by barcmoehm** [comment] 2018-11-01 12:49
Yes, this only happens in headless mode. Thank you for investigating this btw.

Logfile for FF debug build: [log.txt](https://github.com/mozilla/geckodriver/files/2538500/20181101_debuglog.txt).
Logfile of successful non-headless run: [log.txt](https://github.com/mozilla/geckodriver/files/2538501/20181101_successlog.txt).

**Comment by whimboo** [comment] 2018-11-01 14:33
Thanks for testing the build. Sadly it doesn't really offer more details. For now I have at least filed the private browsing Javascript error as: https://bugzilla.mozilla.org/show_bug.cgi?id=1503881. But I doubt that this is the problem here.

One question through. Did you had this problem all the time or did it start recently for you, like with Firefox 63?

**Comment by barcmoehm** [comment] 2018-11-06 12:01
I've found this to be a problem with the flag "-silent". I'm not sure if this is a problem with the java bindings or with geckodriver itself, but if I pass "-silent" as an argument, I get the "permission denied". 

This also explains why it only happens in headless mode: I pass that argument only in there.

**Comment by whimboo** [comment] 2018-11-06 17:00
Oh, thanks! I can see this myself now, and filed https://bugzilla.mozilla.org/show_bug.cgi?id=1505089.

It surely should come from the Java bindings or one of your tests. This option is not supported, so I wonder how this can have an effect. geckodriver clearly doesn't set it.

See also https://github.com/SeleniumHQ/selenium/blob/d54ebd709a3454e94c2a137c1b06d20f92a73784/java/CHANGELOG#L869 which removed it for the version 2.47.0 bindings. So I wonder why you see that still with 3.14.0. @barancev, do you have an idea?

**Comment by whimboo** [comment] 2018-11-06 17:00
Actually we can close this issue because it's not related to geckodriver.

**Closed by whimboo** 2018-11-06 17:00 UTC
Labels: firefox, waiting for reporter feedback

**Comment by barancev** [comment] 2018-11-06 17:16
@whimboo Yes, we don't use -silent option since 2.47 because it was a source of instability.

@barcmoehm Why do you need this option? What's the use case?

**Comment by barcmoehm** [comment] 2018-11-07 06:45
I think this was some sort of brain lag from me where I thought that this was silencing diagnostic output (even after reading the documentation). So there is basically no use case, I just forgot to remove it from my code.

Still it would be nice for the driver to not fail with some cryptic message, especially when using command line options that are known to cause problems.

Anyways, thank you guys a lot for your work!
