### ISSUE TITLE
geckodriver does not work with snap packaged firefox?

### ISSUE THREAD

**Issue by ngladitz** [mozilla/geckodriver#2010] opened 2022-04-27 13:59 UTC
## System

* Version: 0.31.0 (b617178ef491 2022-04-06 11:57 +0000)
* Platform: Ubuntu 22.04 LTS
* Firefox: 99.0.1 (snap Version: 99.0.1-1 Rev: 1232 Publisher: mozilla)
* Selenium: selenium-webdriver 4.1.1 (Javascript)

## Stacktrace

Partial output from geckodriver; I think the command and arguments may be relevant:
```
26: 1651066926069	geckodriver	INFO	Listening on 127.0.0.1:39397
26: 1651066926080	mozrunner::runner	INFO	Running command: "/usr/bin/firefox" "--marionette" "-no-remote" "-profile" "/tmp/rust_mozprofileEmz3JC"
```

Firefox starts and shows this dialog:
![image](https://user-images.githubusercontent.com/4358176/165534762-85db3bee-5d90-4d7b-83e6-b061d409baa0.png)

Not sure what might be the cause or if this is really a geckodriver issue; not too familiar with snap either.
Maybe the geckodriver generated(?) profile in /tmp/ (see trace above) is not accessible via the snap packaged firefox binary(?)

**Comment by whimboo** [comment] 2022-04-27 18:34
This has also been filed as https://bugzilla.mozilla.org/show_bug.cgi?id=1766125.

@ngladitz is that a new issue for you and started recently? Maybe you could check some older geckodriver and Firefox releases? Thanks.

**Comment by ngladitz** [comment] 2022-04-27 18:54
@whimboo it started right after I upgraded my Ubuntu installation from 21.10 to 22.04 (was just released April 21).

With 21.10 my firefox installation was .deb based (also version 99.0 apparently). Since 22.04 Ubuntu itself apparently no longer provides the .deb and uses the snap build which is why I figured this to be most likely snap related.

geckodriver also used to be provided by the "firefox-geckodriver" .deb (version 0.30.0) with 21.10 but is no longer available with 22.04 (and not included in the firefox snap) which is why I switched to a release build (0.31.0) from github.

I tried using the previous geckodriver 0.30.0 release but see the same error.

**Comment by oSoMoN** [comment] 2022-04-27 19:11
> Maybe the geckodriver generated(?) profile in /tmp/ (see trace above) is not accessible via the snap packaged firefox binary(?)

That is most likely the problem, indeed. Firefox packaged as a snap is strictly confined, and it is not permitted to access files in the system-wide `/tmp`. Is there a way to instruct geckodriver to use an alternative location for the temporary profile?

**Comment by oSoMoN** [comment] 2022-04-27 19:19
According to [the documentation](https://firefox-source-docs.mozilla.org/testing/geckodriver/Profiles.html#default-locations-for-temporary-profiles), setting `TMPDIR` to some location the snap can access (e.g. `$HOME/snap/firefox/common/tmp`) might help.

**Comment by ngladitz** [comment] 2022-04-28 05:34
@oSoMoN thank you!

I've got to create the directory first (so geckodriver does not complain with `No such file or directory`) but then setting `TMPDIR`
as suggested does seem to work around the issue.

Complicates things slightly since I suppose I'll have to somehow detect how firefox was packaged first and limit setting `TMPDIR` as far as possible (other applications (started during testing) might unintentionally write into the same `TMPDIR` which may or may not be fine) and there might be issues with cleanup so I'd still appreciate an upstream fix assuming there is something sensible that can be done.

**Comment by oSoMoN** [comment] 2022-04-28 07:46
So if I understand correctly how things work, geckodriver picks a temporary directory, and launches firefox with that directory passed as a command-line parameter to use for profiles. How about adding an option to firefox to ask it to pick that temporary directory itself? It sounds like that would solve the problem at hand, but I'm not sure whether geckodriver wants control over that directory, to read/write things there too?

**Comment by ngladitz** [comment] 2022-04-28 07:55
And / or package geckodriver with the firefox snap so both share / use the same temporary directory (not sure if / how that works on the snap side e.g. if this is implicit or the binaries have to be modified but presumably what ever is required already happens for firefox)?

The chromium snap that Ubuntu provides does itself package chromedriver (don't know if this happens for similar reasons) which is somewhat convenient since manually providing and keeping the chrome-/geckodriver in sync with the browser version is a little bothersome too.

**Comment by oSoMoN** [comment] 2022-04-28 07:58
Yes, I agree that would be best. I had a go at packaging geckodriver with the firefox snap a while ago, but because geckodriver tries to execute the firefox binary itself, and because this capability is denied by the strict confinement that's inherent to snaps, it wasn't working.

**Comment by jgraham** [comment] 2022-04-28 08:32
> I'm not sure whether geckodriver wants control over that directory, to read/write things there too?

Yes, geckodriver needs to be able to set prefs in the profile, so they are avaiable at Firefox startup, and (more avoidably) needs to read the MarionetteActivePort file from the profile so that it can work out which port to connect to.

> The chromium snap that Ubuntu provides does itself package chromedriver (don't know if this happens for similar reasons) which is somewhat convenient since manually providing and keeping the chrome-/geckodriver in sync with the browser version is a little bothersome too.

Chromedriver has a 1:1 relationship with a specific version of Chrome, whereas geckodriver is expected to work across multiple Firefox releases. So packaging geckodriver and Firefox together makes less sense than it does for Chrome (we don't want to have to ship a new geckodriver release for every Firefox release, even when there are no geckodriver changes).

> because geckodriver tries to execute the firefox binary itself, and because this capability is denied by the strict confinement that's inherent to snaps, it wasn't working.

Hmm. I don't know a lot about snaps, but it seems like there must be some way to allow launching a child process, otherwise almost nothing would work.

Altogether the short term fix here is probably:
* Improve the error message when we can't write to the profile dir
* Allow specifying the profile directory as a geckodriver command line argument

That at least makes it possible to work around the issue relatively easily.

**Comment by oSoMoN** [comment] 2022-05-03 14:49
I had a go again at [packaging geckodriver in the firefox snap](https://code.launchpad.net/~osomon/+git/firefox-snap/+ref/geckodriver). After installation, this requires setting up a manual alias: `snap alias firefox.geckodriver geckodriver` ([per documentation](https://snapcraft.io/docs/commands-and-aliases) this can be automated in the snap store).

However when running a test script that uses selenium and geckodriver, I'm getting this error: "`binary is not a Firefox executable`".

This error is raised when geckodriver tries to ascertain the version of the firefox executable, by first looking for `application.ini` or `platform.ini` in the directory of the executable (in this case `/snap/bin/firefox`, and none of these files exist in `/snap/bin/`), and falling back to executing the binary with the `--version` parameter and parsing the standard output.

The corresponding apparmor denial I'm seeing is:

    may 03 16:38:51 jammyvm audit[8837]: AVC apparmor="DENIED" operation="exec" profile="snap.firefox.geckodriver" name="/snap/snapd/15534/usr/bin/snap" pid=8837 comm=776562647269766572206469737061 requested_mask="x" denied_mask="x" fsuid=1000 ouid=0

(`/snap/bin/firefox` is a symlink to `/usr/bin/snap`)

For reference, this is the test script I'm using:

```python
#!/usr/bin/python3
# -*- coding: utf-8 -*-

from selenium import webdriver

if __name__ == "__main__":
    options = webdriver.firefox.options.Options()
    options.log.level = "trace"
    options.binary_location = "/snap/bin/firefox"
    options.add_argument("-headless")
    driver = webdriver.Firefox(options=options, service_args=["-v"])
    print(driver.capabilities["browserVersion"])
    driver.quit()
```

**Comment by DavidBerdik** [comment] 2022-05-06 21:02
Canonical's insistence on shipping Firefox via snap not only breaks the geckodriver, but even if/when this gets resolved, it won't be possible for those of using Firefox headlessly in Docker containers to continue doing so, as snap applications don't work in Docker.

**Comment by whimboo** [comment] 2022-05-10 18:39
For a workaround see our just updated release notes for the 0.31.0 release:
https://github.com/mozilla/geckodriver/releases/tag/v0.31.0

With the next geckodriver release we will provide a `--profile-root` argument to customize the location of the temporary profile.

**Comment by oSoMoN** [comment] 2022-05-13 13:36
I rewrote my patch to override the binary path only when running under snap confinement, thus making it hopefully suitable for merging, and I submitted it at https://phabricator.services.mozilla.com/D146303.

**Comment by matt32106** [comment] 2022-05-26 12:09
FWIW, I had the same issue but I launch my python prog from the spyder IDE in a venv and it would not see the TMPDIR envt variable. 
`export TMPDIR=$HOME/tmp geckodriver` fixed it for me

**Comment by whimboo** [comment] 2022-09-07 05:53
Thanks to @oSoMoN who added [Snap support in geckodriver](https://bugzilla.mozilla.org/show_bug.cgi?id=1769991). The feature will be part of the next geckodriver 0.32.0 release, but note that we do not have an ETA yet.

For testing purposes you might already want to try it out via a nightly build that can be found at:
https://treeherder.mozilla.org/jobs?repo=mozilla-central&searchStr=gd

Just click on one of the green `gd-s` jobs and download the binary from within the pane that gets opened at the bottom.

**Closed by whimboo** 2022-09-07 05:53 UTC

**Comment by joeyparrish** [comment] 2022-10-06 16:19
Unfortunately, I can't do that with the current lab setup.  WebDriver executables are pulled from their official release locations and those are the binaries we run.  It's all automated and the same process used for chromedriver, edgedriver, and geckodriver.

It's possible to eventually add special cases for geckodriver, but that would have to include checks for a snap installation of firefox, too, so that we could still use the external geckodriver binaries for non-snap installs.

So at some point, we might be forced to write code for that.  But I'd prefer to wait for the 0.32 release, if that's coming any time in the next few months.

**Comment by whimboo** [comment] 2022-10-06 17:30
Yes, the 0.32.0 release will be most likely shipped in October. Right now there is still some work left to do.

**Comment by joeyparrish** [comment] 2022-10-06 18:58
Thanks!  That is very helpful.

**Comment by pykereaper** [comment] 2022-10-17 21:57
From the 0.32.0 changelog:
> - The sandboxed Firefox binary is now automatically detected when geckodriver is used from within a Snap confinement.

Does this mean, that with gecko driver 0.32.0, Selenium should work as-is in combination with a Firefox installation via snap? Or is it still required to use the new `--profile-root` option?

Because I still get the `Your Firefox profile cannot be loaded...` error message.

---
- Firefox 105.0.3 installed via Snap
- Ubuntu 22.04.1 LTS
- Selenium 4.5.0

**Comment by joeyparrish** [comment] 2022-10-17 23:56
I was under the impression that with 0.32.0, running geckodriver from outside snap would work with Firefox from inside snap.  Is that not the case?  If it's not the case, could we please have this issue reopened?

**Comment by jgraham** [comment] 2022-10-18 13:12
You still need to specify where you want to put the profile, because the snap doesn't share `/tmp` with the host. We could perhaps pick a different default in this case, but that would be a different issue.

**Comment by joeyparrish** [comment] 2022-10-18 20:41
> We could perhaps pick a different default in this case, but that would be a different issue.

I'll file one, then.  I don't want to have to have my test infrastructure be intelligent enough to differentiate between snap and non-snap versions of Firefox and locate geckodriver in different places based on that.

**Comment by minhadona** [comment] 2022-10-28 15:03
I'm truly sorry if I'm being too dumb but I see the issue was close and I keep receiving a similar error. 
(Ubuntu 22.04.1 LTS)

## Error:

```
/snap/firefox/1943/usr/lib/firefox/geckodriver: error: Unable to write to temporary directory; consider --profile-root with a writeable directory
geckodriver 0.31.0 ( 2022-10-07) 
WebDriver implementation for Firefox
USAGE:
    geckodriver [OPTIONS]
etc
```
   
Plus the classic :
![image](https://user-images.githubusercontent.com/49408880/198665374-37e1d483-4042-4c97-ae83-bbcdb0ed58c3.png)

**((I tried to let geckodriver inside of Downloads/drivers/geckodriver because I just need to test something fast in this computer then delete geckodriver file))**

Code:
---------------------------------------
```
!geckodriver --profile-root=~/Downloads/drivers
!export PATH=$PATH:~/Downloads/drivers
!export PATH=$PATH:~/Downloads/drivers/geckodriver

from selenium import webdriver
from selenium.webdriver.common.keys import Keys
browser = webdriver.Firefox(executable_path="./drivers/geckodriver")
browser.get('https://www.linuxhint.com')
```



### Shouldn't geckodriver be seen from out of snap already? Am I missing some required statement for that ?

**Comment by joeyparrish** [comment] 2022-10-28 18:05
> geckodriver 0.31.0 ( 2022-10-07)

The change referred to in this issue was released in 0.32.0.

**Comment by minhadona** [comment] 2022-10-28 18:09
@joeyparrish it's exactly the version i'm using: 

=(

![image](https://user-images.githubusercontent.com/49408880/198703930-737d057c-3e15-414b-a846-3c7e425a20b0.png)

**Comment by joeyparrish** [comment] 2022-10-28 18:15
I mentioned it because in [your message](https://github.com/mozilla/geckodriver/issues/2010#issuecomment-1295109804), you had output showing 0.31:

> ```
> /snap/firefox/1943/usr/lib/firefox/geckodriver: error: Unable to write to temporary directory; consider --profile-root with a writeable directory
> geckodriver 0.31.0 ( 2022-10-07) 
> ```

**Comment by minhadona** [comment] 2022-10-28 18:22
Nice, now I don't know anymore what version my program is trying to use. Guess I tried to install from different sources and messed it all. But, considering the message mentioning 0.32.0 is from when I execute the PATH exports, and the code mentions executable path to Downloads/drivers/geckodriver, I really think it's trying to use the 0.32.0 version. 
If I figure this out, I come back here to tell what I did to solve.

**Comment by beliaev-maksim** [comment] 2023-06-28 21:27
Hi all,
we believe that the issue is solved with the latest Selenium version and the latest firefox snap 

see https://bugs.launchpad.net/ubuntu/+source/firefox/+bug/2025268 for more details

**Comment by PC-Admin** [comment] 2023-08-07 13:48
Sorry to re-open this, but I'm running Ubuntu 22 and it seems like I have the latest version of these packages:
```
$ geckodriver --version
geckodriver 0.33.0 ( 2023-07-10)
$ firefox --version
Mozilla Firefox 115.0.2
```

But I'm running into the same error when trying to use Selenium: https://stackoverflow.com/questions/76846675/selenium-ubuntu22-bug-message-binary-is-not-a-firefox-executable

**Comment by PC-Admin** [comment] 2023-08-07 14:10
@beliaev-maksim thank you for the quick response, I was able to adjust your code to get Firefox/Selenium working:
```
$ cat ./open_firefox.py
from selenium import webdriver
from selenium.webdriver.firefox.options import Options
from selenium.webdriver.firefox.service import Service

def open_firefox():
    """Open Firefox and navigate to google.com."""
    options = Options()
    options.add_argument('--no-sandbox')
    options.add_argument('--disable-dev-shm-usage')

    service = Service(executable_path="/snap/bin/geckodriver") # specify the path to your geckodriver
    driver = webdriver.Firefox(options=options, service=service)
    driver.set_window_size(1920, 1080)
    driver.maximize_window()
    driver.implicitly_wait(10)

    driver.get("https://www.google.com") # navigate to Google

if __name__ == "__main__":
    open_firefox()
```

Cheers! :)
