### ISSUE TITLE
KeyboardEvent key property is unassigned when sendKeys()

### ISSUE THREAD

**Issue by volnoboy** [mozilla/geckodriver#496] opened 2017-02-27 14:10 UTC
## Firefox Version
any

## Platform
any

Keyboard event key property:

https://developer.mozilla.org/en-US/docs/Web/API/KeyboardEvent/key

is already supported by all desktop browsers except Safari. A lot of developers starting to use it.
I just had an issue it was very hard to find out why sendKeys() method wasn't working. The problem was that selenium generated keyboard event had this property "key" empty and because of it validation didn't work. 
Please consider assigning this property on every keyboard events with selenium.

**Comment by andreastt** [comment] 2017-02-27 17:51
Duplicate of https://github.com/mozilla/geckodriver/issues/440.

**Closed by andreastt** 2017-02-27 17:51 UTC

**Comment by volnoboy** [comment] 2017-02-28 09:21
I am sorry, I have searched for duplicates  and didn't find it. Just want to point out, that  in issue 440 has a label "marionette". Is it going to be implemented in regular gecko driver?

**Comment by andreastt** [comment] 2017-02-28 10:59
geckodriver is an HTTP frontend that speaks to the [Marionette remote control protocol](https://developer.mozilla.org/en-US/docs/Mozilla/QA/Marionette) inside Firefox. This and #440 is a bug in Marionette that needs to be fixed in Firefox.
