### ISSUE TITLE
Window and Chrome detect virus in Geckodriver

### ISSUE THREAD

**Issue by TruongQToan** [mozilla/geckodriver#1264] opened 2018-04-25 12:11 UTC
## System

* Version: 0.20.1
* Platform: Window
* Firefox: 
* Selenium: 

## Stacktrace

Window delete the geckodriver.exe file that I downloaded because of Window detected it as virus. In addition to that, I cannot redownload the file because Chrome detected it as virus. I am using geckodriver 64 bit for Window.

**Comment by Mikerollins89** [comment] 2018-04-25 13:44
I also ran into this issue. It thinks the gecko driver is a possible trojan.

**Comment by TruongQToan** [comment] 2018-04-25 14:58
I doubt that because it is written by mozilla.

**Comment by andreastt** [comment] 2018-04-25 15:27
Duplicate of https://github.com/mozilla/geckodriver/issues/1116. Tracked in https://bugzilla.mozilla.org/show_bug.cgi?id=1442340.

**Closed by andreastt** 2018-04-25 15:27 UTC
