### ISSUE TITLE
geckodriver does not close the browser after quit() when "Are you Sure ? Leave Page .. Stay On Page" alert appears

### ISSUE THREAD

**Issue by jpyati** [mozilla/geckodriver#970] opened 2017-09-22 10:58 UTC
## System
* Version: <0.18.0>
* Platform: <Windows 7>
* Firefox: <55.0>
* Selenium: <3.5.3>
* Selenium: <Selenium-Java>

**Comment by jpyati** [comment] 2017-09-22 12:07
When we use driver.close(), the alert message is also handled, but in a selenium grid, it does not execute the next testcase once close() is executed. So we cannot use close() either.

**Comment by andreastt** [comment] 2017-09-22 12:35
I expect this is the same as https://github.com/mozilla/geckodriver/issues/966, although I don’t understand your last comment. Alas there is nothing in this bug that is reproducible since you didn’t even add a trace-level log.

**Comment by whimboo** [comment] 2017-09-27 12:34
So this is a tab-modal alert what you are seeing here. And you are right that `close` handles it correctly. Are you sure that Marionette/geckodriver is used in the Selenium Grid, or does that still use the old FirefoxDriver?

Please note that this is not a dupe of issue #966. So lets wait for some feedback from the reporter.

**Comment by Zeloslaw** [comment] 2017-10-17 10:15
Try this:
`try {
				driver.close();
				driver.quit();
			} catch (SessionNotCreatedException e) {}`

**Comment by whimboo** [comment] 2017-10-19 11:07
No response from reporter for 22 days. We are happy to reopen the issue if you can provide the necessary information and a trace level log. Thanks.

**Closed by whimboo** 2017-10-19 11:07 UTC
Labels: waiting for reporter feedback

**Comment by DavidGWheeler** [comment] 2018-03-23 19:17
This is a serious defect and we can't find a reasonable work-around for it. Neither driver.quit nor driver.close() does not close Firefox browser if the "Are you Sure ? Leave Page .. Stay On Page" alert is present.  Instead it is just hanging.

Our After test method looks like this: 
```
    public void afterTest(ITestResult result) throws Exception {

        String resultStr = result.getStatus() == 1 ? "PASSED" :
                result.getStatus() == 2 ? "FAILED" : "IGNORED";
        System.out.println(String.format(resultInformation, resultStr));
        System.out.println("before quit");
        driver.quit();
        System.out.println("after quit");
        if (driver != null)
            driver.quit();
    }
```


Here is our stacktrace: 
```
12:12:55.468 [DEBUG] [TestEventLogger] Gradle suite > Gradle test STANDARD_OUT
12:12:55.468 [DEBUG] [TestEventLogger]     --------------------------------------------
12:12:55.468 [DEBUG] [TestEventLogger]     || Result:                           FAILED
12:12:55.468 [DEBUG] [TestEventLogger]     --------------------------------------------
12:12:55.468 [DEBUG] [TestEventLogger]     before quit
12:12:55.469 [DEBUG] [TestEventLogger]
12:12:55.469 [DEBUG] [TestEventLogger] Gradle suite > Gradle test STANDARD_ERROR
12:12:55.469 [DEBUG] [TestEventLogger]     1521832375452        webdriver::server       DEBUG   -> DELETE /session/78a76ec2-faec-4160-8f1c-6b32503af893
12:12:55.469 [DEBUG] [TestEventLogger]     1521832375453        geckodriver::marionette TRACE   -> 39:[0,116,"quit",{"flags":["eForceQuit"]}]
12:12:55.469 [DEBUG] [TestEventLogger]     1521832375454        Marionette      TRACE   0 -> [0,116,"quit",{"flags":["eForceQuit"]}]
12:12:55.469 [DEBUG] [TestEventLogger]     1521832375454        Marionette      DEBUG   New connections will no longer be accepted
12:12:59.417 [null] [org.gradle.process.internal.health.memory.MemoryManager]
12:12:59.417 [DEBUG] [org.gradle.process.internal.health.memory.MemoryManager] Emitting OS memory status event {Total: 17054658560, Free: 7149973504}
12:12:59.417 [DEBUG] [org.gradle.launcher.daemon.server.health.LowMemoryDaemonExpirationStrategy] Received memory status update: {Total: 17054658560, Free: 7149973504}
12:12:59.417 [DEBUG] [org.gradle.process.internal.health.memory.MemoryManager] Emitting JVM memory status event {Maximum: 954728448, Committed: 491257856}
12:13:03.110 [DEBUG] [org.gradle.launcher.daemon.server.Daemon] DaemonExpirationPeriodicCheck running
12:13:03.111 [DEBUG] [org.gradle.cache.internal.DefaultFileLockManager] Waiting to acquire shared lock on daemon addresses registry.
12:13:03.111 [DEBUG] [org.gradle.cache.internal.DefaultFileLockManager] Lock acquired on daemon addresses registry.
12:13:03.111 [DEBUG] [org.gradle.cache.internal.DefaultFileLockManager] Releasing lock on daemon addresses registry.
12:13:03.112 [DEBUG] [org.gradle.cache.internal.DefaultFileLockManager] Waiting to acquire shared lock on daemon addresses registry.
12:13:03.112 [DEBUG] [org.gradle.cache.internal.DefaultFileLockManager] Lock acquired on daemon addresses registry.
12:13:03.112 [DEBUG] [org.gradle.cache.internal.DefaultFileLockManager] Releasing lock on daemon addresses registry.
12:13:04.416 [DEBUG] [org.gradle.process.internal.health.memory.MemoryManager] Emitting OS memory status event {Total: 17054658560, Free: 7154057216}
12:13:04.417 [DEBUG] [org.gradle.launcher.daemon.server.health.LowMemoryDaemonExpirationStrategy] Received memory status update: {Total: 17054658560, Free: 7154057216}
12:13:04.417 [DEBUG] [org.gradle.process.internal.health.memory.MemoryManager] Emitting JVM memory status event {Maximum: 954728448, Committed: 491257856}
12:13:09.417 [DEBUG] [org.gradle.process.internal.health.memory.MemoryManager] Emitting OS memory status event {Total: 17054658560, Free: 7159971840}
12:13:09.417 [DEBUG] [org.gradle.launcher.daemon.server.health.LowMemoryDaemonExpirationStrategy] Received memory status update: {Total: 17054658560, Free: 7159971840}
12:13:09.417 [DEBUG] [org.gradle.process.internal.health.memory.MemoryManager] Emitting JVM memory status event {Maximum: 954728448, Committed: 491257856}
12:13:13.110 [DEBUG] [org.gradle.launcher.daemon.server.Daemon] DaemonExpirationPeriodicCheck running
12:13:13.111 [DEBUG] [org.gradle.cache.internal.DefaultFileLockManager] Waiting to acquire shared lock on daemon addresses registry.
12:13:13.111 [DEBUG] [org.gradle.cache.internal.DefaultFileLockManager] Lock acquired on daemon addresses registry.
12:13:13.111 [DEBUG] [org.gradle.cache.internal.DefaultFileLockManager] Releasing lock on daemon addresses registry.
12:13:13.113 [DEBUG] [org.gradle.cache.internal.DefaultFileLockManager] Waiting to acquire shared lock on daemon addresses registry.
12:13:13.113 [DEBUG] [org.gradle.cache.internal.DefaultFileLockManager] Lock acquired on daemon addresses registry.
12:13:13.113 [DEBUG] [org.gradle.cache.internal.DefaultFileLockManager] Releasing lock on daemon addresses registry.
12:13:14.417 [DEBUG] [org.gradle.process.internal.health.memory.MemoryManager] Emitting OS memory status event {Total: 17054658560, Free: 7163797504}
12:13:14.417 [DEBUG] [org.gradle.launcher.daemon.server.health.LowMemoryDaemonExpirationStrategy] Received memory status update: {Total: 17054658560, Free: 7163797504}
12:13:14.417 [DEBUG] [org.gradle.process.internal.health.memory.MemoryManager] Emitting JVM memory status event {Maximum: 954728448, Committed: 491257856}
12:13:19.417 [DEBUG] [org.gradle.process.internal.health.memory.MemoryManager] Emitting OS memory status event {Total: 17054658560, Free: 7164284928}
12:13:19.417 [DEBUG] [org.gradle.launcher.daemon.server.health.LowMemoryDaemonExpirationStrategy] Received memory status update: {Total: 17054658560, Free: 7164284928}
12:13:19.417 [DEBUG] [org.gradle.process.internal.health.memory.MemoryManager] Emitting JVM memory status event {Maximum: 954728448, Committed: 491257856}
12:13:23.110 [DEBUG] [org.gradle.launcher.daemon.server.Daemon] DaemonExpirationPeriodicCheck running
12:13:23.111 [DEBUG] [org.gradle.cache.internal.DefaultFileLockManager] Waiting to acquire shared lock on daemon addresses registry.
12:13:23.111 [DEBUG] [org.gradle.cache.internal.DefaultFileLockManager] Lock acquired on daemon addresses registry.
12:13:23.111 [DEBUG] [org.gradle.cache.internal.DefaultFileLockManager] Releasing lock on daemon addresses registry.
12:13:23.112 [DEBUG] [org.gradle.cache.internal.DefaultFileLockManager] Waiting to acquire shared lock on daemon addresses registry.
12:13:23.112 [DEBUG] [org.gradle.cache.internal.DefaultFileLockManager] Lock acquired on daemon addresses registry.
12:13:23.112 [DEBUG] [org.gradle.cache.internal.DefaultFileLockManager] Releasing lock on daemon addresses registry.
12:13:24.417 [DEBUG] [org.gradle.process.internal.health.memory.MemoryManager] Emitting OS memory status event {Total: 17054658560, Free: 7165337600}
12:13:24.417 [DEBUG] [org.gradle.launcher.daemon.server.health.LowMemoryDaemonExpirationStrategy] Received memory status update: {Total: 17054658560, Free: 7165337600}
12:13:24.417 [DEBUG] [org.gradle.process.internal.health.memory.MemoryManager] Emitting JVM memory status event {Maximum: 954728448, Committed: 491257856}
12:13:29.417 [DEBUG] [org.gradle.process.internal.health.memory.MemoryManager] Emitting OS memory status event {Total: 17054658560, Free: 7166312448}
12:13:29.417 [DEBUG] [org.gradle.launcher.daemon.server.health.LowMemoryDaemonExpirationStrategy] Received memory status update: {Total: 17054658560, Free: 7166312448}
12:13:29.417 [DEBUG] [org.gradle.process.internal.health.memory.MemoryManager] Emitting JVM memory status event {Maximum: 954728448, Committed: 491257856}
12:13:33.110 [DEBUG] [org.gradle.launcher.daemon.server.Daemon] DaemonExpirationPeriodicCheck running
12:13:33.111 [DEBUG] [org.gradle.cache.internal.DefaultFileLockManager] Waiting to acquire shared lock on daemon addresses registry.
12:13:33.111 [DEBUG] [org.gradle.cache.internal.DefaultFileLockManager] Lock acquired on daemon addresses registry.
12:13:33.111 [DEBUG] [org.gradle.cache.internal.DefaultFileLockManager] Releasing lock on daemon addresses registry.
12:13:33.112 [DEBUG] [org.gradle.cache.internal.DefaultFileLockManager] Waiting to acquire shared lock on daemon addresses registry.
12:13:33.112 [DEBUG] [org.gradle.cache.internal.DefaultFileLockManager] Lock acquired on daemon addresses registry.
12:13:33.112 [DEBUG] [org.gradle.cache.internal.DefaultFileLockManager] Releasing lock on daemon addresses registry.
12:13:34.416 [DEBUG] [org.gradle.process.internal.health.memory.MemoryManager] Emitting OS memory status event {Total: 17054658560, Free: 7168372736}
12:13:34.417 [DEBUG] [org.gradle.launcher.daemon.server.health.LowMemoryDaemonExpirationStrategy] Received memory status update: {Total: 17054658560, Free: 7168372736}
12:13:34.417 [DEBUG] [org.gradle.process.internal.health.memory.MemoryManager] Emitting JVM memory status event {Maximum: 954728448, Committed: 491257856}
12:13:39.417 [DEBUG] [org.gradle.process.internal.health.memory.MemoryManager] Emitting OS memory status event {Total: 17054658560, Free: 7182888960}
12:13:39.417 [DEBUG] [org.gradle.launcher.daemon.server.health.LowMemoryDaemonExpirationStrategy] Received memory status update: {Total: 17054658560, Free: 7182888960}
12:13:39.417 [DEBUG] [org.gradle.process.internal.health.memory.MemoryManager] Emitting JVM memory status event {Maximum: 954728448, Committed: 491257856}
12:13:43.110 [DEBUG] [org.gradle.launcher.daemon.server.Daemon] DaemonExpirationPeriodicCheck running
12:13:43.111 [DEBUG] [org.gradle.cache.internal.DefaultFileLockManager] Waiting to acquire shared lock on daemon addresses registry.
12:13:43.112 [DEBUG] [org.gradle.cache.internal.DefaultFileLockManager] Lock acquired on daemon addresses registry.
12:13:43.112 [DEBUG] [org.gradle.cache.internal.DefaultFileLockManager] Releasing lock on daemon addresses registry.
12:13:43.114 [DEBUG] [org.gradle.cache.internal.DefaultFileLockManager] Waiting to acquire shared lock on daemon addresses registry.
12:13:43.114 [DEBUG] [org.gradle.cache.internal.DefaultFileLockManager] Lock acquired on daemon addresses registry.
12:13:43.114 [DEBUG] [org.gradle.cache.internal.DefaultFileLockManager] Releasing lock on daemon addresses registry.
12:13:44.417 [DEBUG] [org.gradle.process.internal.health.memory.MemoryManager] Emitting OS memory status event {Total: 17054658560, Free: 7185358848}
12:13:44.417 [DEBUG] [org.gradle.launcher.daemon.server.health.LowMemoryDaemonExpirationStrategy] Received memory status update: {Total: 17054658560, Free: 7185358848}
12:13:44.417 [DEBUG] [org.gradle.process.internal.health.memory.MemoryManager] Emitting JVM memory status event {Maximum: 954728448, Committed: 491257856}
12:13:49.418 [DEBUG] [org.gradle.process.internal.health.memory.MemoryManager] Emitting OS memory status event {Total: 17054658560, Free: 7185387520}
12:13:49.418 [DEBUG] [org.gradle.launcher.daemon.server.health.LowMemoryDaemonExpirationStrategy] Received memory status update: {Total: 17054658560, Free: 7185387520}
12:13:49.418 [DEBUG] [org.gradle.process.internal.health.memory.MemoryManager] Emitting JVM memory status event {Maximum: 954728448, Committed: 491257856}
12:13:53.110 [DEBUG] [org.gradle.launcher.daemon.server.Daemon] DaemonExpirationPeriodicCheck running
12:13:53.112 [DEBUG] [org.gradle.cache.internal.DefaultFileLockManager] Waiting to acquire shared lock on daemon addresses registry.
12:13:53.112 [DEBUG] [org.gradle.cache.internal.DefaultFileLockManager] Lock acquired on daemon addresses registry.
12:13:53.113 [DEBUG] [org.gradle.cache.internal.DefaultFileLockManager] Releasing lock on daemon addresses registry.
12:13:53.114 [DEBUG] [org.gradle.cache.internal.DefaultFileLockManager] Waiting to acquire shared lock on daemon addresses registry.
12:13:53.115 [DEBUG] [org.gradle.cache.internal.DefaultFileLockManager] Lock acquired on daemon addresses registry.
12:13:53.115 [DEBUG] [org.gradle.cache.internal.DefaultFileLockManager] Releasing lock on daemon addresses registry.
```

**Comment by whimboo** [comment] 2018-03-26 08:31
Please note that this is actually a dupe of issue #1151.
