### ISSUE TITLE
Element "<span>" is not clickable at point (..) because another element "<div>" obscures it

### ISSUE THREAD

**Issue by jonasSel** [mozilla/geckodriver#1441] opened 2018-11-27 08:57 UTC
## System

* Version: 23.0
* Platform: CentOS/Windows10 (independent
* Firefox: 60.3esr
* Selenium: 3.141.59

## Testcase
This is one of the biggest problems I have currently and it prevents me from updating to the new geckodriver/FF60esr and selenium!!
Element <span class="glyphicon glyphicon-calendar"> is not clickable at point (373,961.0833129882812) because another element <div id="completion-buttons-panel-sticky-wrapper" class="sticky"> obscures it

Here is the minimal HTML element

## Stacktrace example (a bit modified)

This shows how far it scrolled and it misses the underneath input field.
![screenshot59](https://user-images.githubusercontent.com/27417150/49069738-509fd380-f22a-11e8-9380-29dd098b3167.png)

**Comment by jonasSel** [comment] 2018-11-27 09:01
Here is part if the stacktrace:
[RemoteTestNG] detected TestNG version 6.11.0
1543308933475	mozrunner::runner	INFO	Running command: "/local0/jonas/browsers/firefox60.22esr/firefox" "-marionette" "-foreground" "-no-remote" "-profile" "/tmp/rust_mozprofile.gdEF99mp93Jf"
...
(firefox:12162): GLib-GObject-CRITICAL **: g_object_unref: assertion 'object->ref_count > 0' failed
...
(/local0/jonas/browsers/firefox60.22esr/firefox:12243): GLib-GObject-CRITICAL **: g_object_unref: assertion 'object->ref_count > 0' failed
1543308934495	Marionette	INFO	Listening on port 46203
1543308934579	Marionette	WARN	TLS certificate errors will be ignored for this session
Nov 27, 2018 9:55:34 AM org.openqa.selenium.remote.ProtocolHandshake createSession
INFO: Detected dialect: W3C
geckodriver 0.23.0 ( 2018-10-04)
Mozilla Firefox 60.2.2
Starting Test: compagny.setest.entities.pp.ppt.specific.EntityTest123s.testCreateLineBatchFromTest123
SingleTest/ScrShot-compagny.setest.entities.pp.ppt.specific.EntityTest123s.testCreateLineBatchFromTest1233221675526627213458.png
console.log: Accessibility service init or shutdown observer does not exist.
*** UTM:SVC TimerManager:registerTimer called after profile-before-change notification. Ignoring timer registration for id: telemetry_modules_ping

(firefox:12162): GLib-GObject-CRITICAL **: g_object_ref: assertion 'object->ref_count > 0' failed

(firefox:12162): GLib-GObject-CRITICAL **: g_object_unref: assertion 'object->ref_count > 0' failed
FAILED: testCreateLineBatchFromTest123
        Creates a cell line batch from aliquot group
org.openqa.selenium.ElementClickInterceptedException: Element <span class="glyphicon glyphicon-calendar"> is not clickable at point (373,899.0833129882812) because another element <div id="completion-buttons-panel-sticky-wrapper" class="sticky"> obscures it
Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:25:53'
System info: host: 'coruscant.ch.compagny.com', ip: '172.20.33.212', os.name: 'Linux', os.arch: 'amd64', os.version: '3.10.0-514.26.2.el7.x86_64', java.version: '1.8.0_66'
Driver info: org.openqa.selenium.firefox.FirefoxDriver
Capabilities {acceptInsecureCerts: true, browserName: firefox, browserVersion: 60.2.2, javascriptEnabled: true, moz:accessibilityChecks: false, moz:geckodriverVersion: 0.23.0, moz:headless: false, moz:processID: 12162, moz:profile: /tmp/rust_mozprofile.gdEF99..., moz:useNonSpecCompliantPointerOrigin: false, moz:webdriverClick: true, pageLoadStrategy: normal, platform: LINUX, platformName: LINUX, platformVersion: 3.10.0-514.26.2.el7.x86_64, rotatable: false, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}}
Session ID: b38d9d24-e056-4730-a26b-d5dde978f684
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:422)
	at org.openqa.selenium.remote.http.W3CHttpResponseCodec.createException(W3CHttpResponseCodec.java:187)
	at org.openqa.selenium.remote.http.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:122)
	at org.openqa.selenium.remote.http.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:49)
	at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:158)
	at org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:83)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:552)
	at org.openqa.selenium.remote.RemoteWebElement.execute(RemoteWebElement.java:285)
	at org.openqa.selenium.remote.RemoteWebElement.click(RemoteWebElement.java:84)
	at compagny.setest.util.DatePicker.ouvertDatePicker(DatePicker.java:183)
	at compagny.setest.util.DatePicker.setDateToday(DatePicker.java:67)
	at compagny.setest.base.AbstractEditPage.setDateToday(AbstractEditPage.java:299)
	at compagny.setest.base.pp.ppt.CreateLineBatchFromTest123Page.fillFirstRow(CreateLineBatchFromTest123Page.java:47)
	at compagny.setest.entities.pp.ppt.specific.EntityTest123s.testCreateLineBatchFromTest123(EntityTest123s.java:33)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)

**Comment by whimboo** [comment] 2018-11-27 11:13
Sadly a screenshot isn't a way to present a minimized HTML example. The above doesn't help at all because the element contains way more sub elements, and then it's also not clear which CSS styles/properties are assigned to them. 

One question through... Is any element below this `div` a block-level element?

**Comment by jonasSel** [comment] 2018-11-27 14:03
Yes, there are several div block level elements after.

I have attached the body of the full html page in a file: relevant are:
line 602 (the input element I want to click on)
line 873 (div id="completion-buttons-panel-sticky-wrapper")

[PageElement.body.txt](https://github.com/mozilla/geckodriver/files/2620269/PageElement.body.txt)

**Comment by whimboo** [comment] 2018-11-28 08:36
I don't mean that block level elements should appear after that wanted element in the DOM tree, but underneath the element you want to click. That doesn't seem to be the case here.

If you could do the following I would appreciate it:

1) Create minimized test in your Selenium binding which loads the local web page (as attached here) in the browser, retrieves the element, and tries to click on it

2) Reduce the HTML page as much as possible, until the problem cannot be reproduced anymore.

Thanks

**Comment by jonasSel** [comment] 2018-11-29 12:43
Here is the code. I have attached the two minimal pages. But it was kind of clear. As soon as it does not have to scroll anymore, it works!

[ShowsObscured.txt](https://github.com/mozilla/geckodriver/files/2629108/ShowsObscured.txt)
[Working.txt](https://github.com/mozilla/geckodriver/files/2629109/Working.txt)


Java:
`package genedata.setest.scripts;

import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.firefox.FirefoxOptions;
import org.openqa.selenium.firefox.FirefoxProfile;
import org.testng.Reporter;
import org.testng.annotations.BeforeClass;
import org.testng.annotations.Test;

import genedata.setest.util.Links;

public class SimpleRunTest2 {
	public SimpleRunTest2() {
		Reporter.log("++> Start " + this.getClass().getSimpleName());
	}
	WebDriver driver;

	@BeforeClass(alwaysRun = true)
	public void setUp() throws Exception {
		FirefoxProfile profile = new FirefoxProfile();
		profile.setPreference("browser.download.folderList", 2);
		profile.setPreference("browser.download.manager.showWhenStarting", false);
		profile.setPreference("pdfjs.disabled", true); // as of FF19, pdf viewer default has to be disabled
		profile.setPreference("browser.download.dir", System.getProperty("download.dir"));

		FirefoxOptions options = new FirefoxOptions();
		// options.setHeadless(true);
		options.setBinary("/local0/jonas/browsers/firefox60.22esr/firefox");
		options.setProfile(profile);

		System.setProperty("webdriver.gecko.driver", "lib/geckodriver");
		System.setProperty(FirefoxDriver.SystemProperty.BROWSER_LOGFILE, "/dev/null");

		driver = new FirefoxDriver(options);

		// maximize the browser
		driver.manage().window().maximize();
	}

	@Test(description = "Loads a saved html page")
	public void loadPageForTest() throws Exception {
		String file = "//u/jonas/Desktop/savedPage/ShowsObscured.html";
		driver.get("file:\\" + file);
		String selectCalendarIcon = "div[id*='property_datePerformed'][id*=':0:'] ";
		By datePopupImg = By.cssSelector(selectCalendarIcon + "span[class*='glyphicon-calendar']");
		driver.findElement(datePopupImg).click();
		Thread.sleep(5000);
	}
}
`
Thanks for looking at it.

**Comment by whimboo** [comment] 2018-11-30 08:15
Again, this is not a minimized HTML testcase, but just a saved copy of the page. Anyway I had a look...

The element you are referring to here is an empty `<span>` which means that it's size is 0x0 pixels. As such it is not visible, and as consequence cannot be interacted with. I don't see why this should be different.

Also note that the element to interact with doesn't concur with the screenshot from the initial comment. So this is very confusing, and I cannot see that this is a valid report.

**Closed by whimboo** 2018-11-30 08:15 UTC
Labels: waiting for reporter feedback

**Comment by jonasSel** [comment] 2018-12-03 15:03
This is definitively not invalid! But I give you that: badly reported from my side. Sorry.

The html page below works since it does not have to scroll. If you add lots of `<tr><td><span title="">Name1</span></td><td><input value=""></td></tr>` (until it needs to scroll), you will get above error message with obscured element. If you do a debug round and scroll down or if you execute a javascript which scrolls to the point it works in firefox. Remember, I have had no problems  with Firefox 52esr and geckodriver 17.

`<STYLE type="text/css">
#completion-buttons-panel {
	background-color:  white;
	text-align:right;
	padding: 0px 10px 0px 10px;
	min-height:20px;
	vertical-align: middle;
}

/* {{{ Sticky completions buttons */
#completion-buttons-panel-sticky-wrapper > #completion-buttons-panel {
	width: 820px;
	box-sizing: border-box;
	padding: 0;
}

#completion-buttons-panel-sticky-wrapper.sticky {
	position: fixed;
	bottom: 0;
	top: auto;
	box-shadow: 0 -4px 8px 0 rgba(0,0,0,.3);
}

/* }}} Sticky completions buttons */
</STYLE>

<head>
</head>
<body>
<table class="section-table ">
<tr><td><span title="">Name1</span></td><td><input value=""></td></tr>
<tr><td><span title="">Name1</span></td><td><input value=""></td></tr>
</table>
<table>
<thead >
<tr><td>selection</td><td class="property_cultureProcessingAction" size="1"><select class="property_cultureProcessingAction">
	<option value="org.jboss.seam.ui.NoSelectionConverter.noSelectionValue"> </option>
	<option value="127">Seeding</option>
	<option value="128">Freezing</option>
	<option value="129" selected="selected">Thawing</option>
	<option value="130">Passaging</option>
</select>
<tr><td><span title="">Name1</span></td><td><input value=""></td></tr>
<tr><td><span title="">Name1</span></td><td><input value=""></td></tr>
</tbody>
</table>
<div id="completion-buttons-panel-sticky-wrapper" class="sticky">
<input id="finishButton"type="submit"></td>
</div>
</body>`

**Comment by jonasSel** [comment] 2018-12-03 15:06
[minimized_page2_html.txt](https://github.com/mozilla/geckodriver/files/2639977/minimized_page2_html.txt)

**Comment by whimboo** [comment] 2018-12-03 20:58
Ok, so which element should be clicked in the new minimized testcase?

**Comment by jonasSel** [comment] 2018-12-04 07:53
The SELECT element. (I changed it because, actually, the empty span element was empty because of a missing icon I had not included)

```@BeforeClass(alwaysRun = true)
	public void setUp() throws Exception {
		FirefoxProfile profile = new FirefoxProfile();
		profile.setPreference("browser.download.folderList", 2);
		profile.setPreference("browser.download.manager.showWhenStarting", false);
		profile.setPreference("pdfjs.disabled", true);
		profile.setPreference("browser.download.dir", System.getProperty("download.dir"));
		FirefoxOptions options = new FirefoxOptions();
		options.setBinary("/local0/jonas/browsers/firefox60.22esr/firefox");
		options.setProfile(profile);
		System.setProperty("webdriver.gecko.driver", "lib/geckodriver");
		System.setProperty(FirefoxDriver.SystemProperty.BROWSER_LOGFILE, "/dev/null");
		driver = new FirefoxDriver(options);
		driver.manage().window().maximize();
	}

	@Test(description = "Loads a saved html page")
	public void loadPageForTest() throws Exception {
		String file = "//local0/jonas/Downloads_Selenium/minimized_page2.html";
		driver.get("file:/" + file);
		By cultureAct = By.cssSelector("select[class*='property_cultureProcessingAction']");
		Select culture = new Select(driver.findElement(cultureAct));
		culture.selectByIndex(1);
		Thread.sleep(5000);
	}
```

Here's the new log:

> FAILED: loadPageForTest
        Loads a saved html page
org.openqa.selenium.ElementClickInterceptedException: Element <select class="property_cultureProcessingAction"> is not clickable at point (143.5,890.5) because another element <input id="finishButton" type="submit"> obscures it
Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:25:53'
System info: host: 'coruscant.ch.genedata.com', ip: '172.20.33.212', os.name: 'Linux', os.arch: 'amd64', os.version: '3.10.0-514.26.2.el7.x86_64', java.version: '1.8.0_66'
Driver info: org.openqa.selenium.firefox.FirefoxDriver
Capabilities {acceptInsecureCerts: true, browserName: firefox, browserVersion: 60.2.2, javascriptEnabled: true, moz:accessibilityChecks: false, moz:geckodriverVersion: 0.23.0, moz:headless: false, moz:processID: 29675, moz:profile: /tmp/rust_mozprofile.c0440B..., moz:useNonSpecCompliantPointerOrigin: false, moz:webdriverClick: true, pageLoadStrategy: normal, platform: LINUX, platformName: LINUX, platformVersion: 3.10.0-514.26.2.el7.x86_64, rotatable: false, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}}
Session ID: d66c1cb3-776c-48f6-b0d6-5e1e3677db4b
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:422)
	at org.openqa.selenium.remote.http.W3CHttpResponseCodec.createException(W3CHttpResponseCodec.java:187)
	at org.openqa.selenium.remote.http.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:122)
	at org.openqa.selenium.remote.http.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:49)
	at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:158)
	at org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:83)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:552)
	at org.openqa.selenium.remote.RemoteWebElement.execute(RemoteWebElement.java:285)
	at org.openqa.selenium.remote.RemoteWebElement.click(RemoteWebElement.java:84)
	at org.openqa.selenium.support.ui.Select.setSelected(Select.java:311)
	at org.openqa.selenium.support.ui.Select.setSelectedByIndex(Select.java:293)
	at org.openqa.selenium.support.ui.Select.selectByIndex(Select.java:172)
	at genedata.setest.scripts.SimpleRunTest2.loadPageForTest(SimpleRunTest2.java:48)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)

Here's a screenshot with the sticky element:
![screenshot_ff60esr](https://user-images.githubusercontent.com/27417150/49426682-89e3c080-f7a1-11e8-8f72-5b027af5eaa6.png)

**Comment by whimboo** [comment] 2018-12-04 08:37
I have the feeling you are modifying the testcase at will. Originally it was a span element, and now it should be a select element. Please note that both are completely different things. Also I have no idea what `selectByIndex` is doing. You didn't attach a trace log (please don't add log entries inline, thanks!).

The best here would be to revert the testcase to the span element, and have eg. some placeholder text. 

If I use the testcase locally and add `style="margin-top:110vh"` to the table, it works all fine. Clicking the select opens the menu as expected.

**Comment by jonasSel** [comment] 2018-12-04 16:00
It is not really a problem of what kind of element is under the sticky element. The problem stays the same, the application can not click or interact with it. It scrolls just until the element is in the viewport. But there is the sticky element. What it should do is, scroll a bit more! Since with FF60esr, it can not click on something like this anymore.
I have had no problem with FF52esr and geckodriver17. Unfortunately, I have this problem at several other places and therefore I can not update to FF60. It tried scroll via javascript to scroll into the middle of the viewport. That works, but screws up other places.

Anyway, I went back to the span element and created the page you requested:
Here's the code:
```
    @BeforeClass(alwaysRun = true)
	public void setUp() throws Exception {
		FirefoxProfile profile = new FirefoxProfile();
		profile.setPreference("browser.download.folderList", 2);
		profile.setPreference("browser.download.manager.showWhenStarting", false);
		profile.setPreference("pdfjs.disabled", true);
		profile.setPreference("browser.download.dir", System.getProperty("download.dir"));
		profile.setPreference("marionette.logging", "TRACE");
		FirefoxOptions options = new FirefoxOptions();
		options.setBinary("/local0/jonas/browsers/firefox60.3esr/firefox");
		options.setProfile(profile);
		System.setProperty("webdriver.gecko.driver", "lib/geckodriver");
		//System.setProperty(FirefoxDriver.SystemProperty.BROWSER_LOGFILE, "/dev/null");
		driver = new FirefoxDriver(options);
		driver.manage().window().maximize();
	}

	@Test(description = "Loads a saved html page")
	public void loadPageForTest() throws Exception {
		String file = "//local0/jonas/Downloads_Selenium/minimized_page2.html";
		driver.get("file:/" + file);
		String selectCalendarIcon = "div[id='datePerformed_date'] ";
		By datePopupImg = By.cssSelector(selectCalendarIcon + "span[class*='glyphicon-calendar']");
		driver.findElement(datePopupImg).click();
		Thread.sleep(5000);
	}
```
and I attached the log and the page (which throws the exception):
[minimized_page2.log.txt](https://github.com/mozilla/geckodriver/files/2644734/minimized_page2.log.txt)

[minimized_page2.html.txt](https://github.com/mozilla/geckodriver/files/2644746/minimized_page2.html.txt)

Adding the styles tag: ```<div id="completion-buttons-panel-sticky-wrapper" class="sticky" style="margin-top:110vh">``` Should not work and even if, moving the element a bit lower? Moves the problem just to another element staying underneath there. Remember, the problem is that it scrolls, but only to the viewport, where unfortunately, there is this sticky element.
