### ISSUE TITLE
Error messages from "actions" end point do not provide enough information to fix bugs in local end implementations

### ISSUE THREAD

**Issue by shs96c** [mozilla/geckodriver#427] opened 2017-01-09 10:23 UTC
* geckodriver 0.13
* DragAndDropTest#testDragAndDropToElement from Selenium at 147349edb9cc20e843b5350fb77ba5ebf1983167

Steps to reproduce:

* Run the test (you may need to do this from an IDE)

Expected result:

* Either for the test to pass or for useful debug information.

Actual result:

An `IllegalArgumentException` with the message `Missing or invalid type argument for pointer action`

This message is insufficient to determine where the problem lies, and therefore to fix it. This part of the spec has multiple properties called "action" and "type" so a very specific error message would be much appreciated.

**Comment by vladimir-konnov** [comment] 2017-02-18 15:55
I have the same issue with geckodriver starting from v.0.12.0 to the (current) v.0.14.0, firefox v.51.0.1 (64bit), selenium-webdriver gem v.3.1.0. I'm calling `source.drag_to target` capybara method, which is in its turn translated to selenium `driver.browser.action.drag_and_drop(native, element.native).perform`. Here I'm getting the following error: 
```
Selenium::WebDriver::Error::InvalidArgumentError: Missing or invalid type argument for pointer action
.../rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/selenium-webdriver-3.1.0/lib/selenium/webdriver/remote/response.rb:69:in `assert_ok'
.../rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/selenium-webdriver-3.1.0/lib/selenium/webdriver/remote/response.rb:32:in `initialize'
.../rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/selenium-webdriver-3.1.0/lib/selenium/webdriver/remote/http/common.rb:85:in `new'
.../rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/selenium-webdriver-3.1.0/lib/selenium/webdriver/remote/http/common.rb:85:in `create_response'
.../rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/selenium-webdriver-3.1.0/lib/selenium/webdriver/remote/http/default.rb:107:in `request'
.../rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/selenium-webdriver-3.1.0/lib/selenium/webdriver/remote/http/common.rb:63:in `call'
.../rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/selenium-webdriver-3.1.0/lib/selenium/webdriver/remote/w3c_bridge.rb:625:in `raw_execute'
.../rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/selenium-webdriver-3.1.0/lib/selenium/webdriver/remote/w3c_bridge.rb:600:in `execute'
.../rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/selenium-webdriver-3.1.0/lib/selenium/webdriver/remote/w3c_bridge.rb:399:in `send_actions'
.../rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/selenium-webdriver-3.1.0/lib/selenium/webdriver/common/w3c_action_builder.rb:164:in `perform'
```
I have no idea what is the root cause of the problem, so I can't fix it. Also there's no additional info which may help to find the root cause of the error.
P.S. Previously with geckodriver v.0.11.0 and 0.11.1 the error was `POST session/:ID/actions did not match a known command`. So it seems that they have implemented actions but still something is going wrong with interoperation between client/server.

**Comment by Valkenvania** [comment] 2017-02-21 13:01
Similar issue here - Mac 10.12.3, Firefox 51.0.1 (64-bit), geckodriver 0.14.0, selenium-webdriver 3.1.0, watir 6.2.0
The specific action below is right-clicking on an element

```
Missing or invalid type argument for pointer action
/Users/egbert/.rbenv/versions/2.0.0-p648/lib/ruby/gems/2.0.0/gems/selenium-webdriver-3.1.0/lib/selenium/webdriver/remote/response.rb:69:in `assert_ok'
/Users/egbert/.rbenv/versions/2.0.0-p648/lib/ruby/gems/2.0.0/gems/selenium-webdriver-3.1.0/lib/selenium/webdriver/remote/response.rb:32:in `initialize'
/Users/egbert/.rbenv/versions/2.0.0-p648/lib/ruby/gems/2.0.0/gems/selenium-webdriver-3.1.0/lib/selenium/webdriver/remote/http/common.rb:85:in `new'
/Users/egbert/.rbenv/versions/2.0.0-p648/lib/ruby/gems/2.0.0/gems/selenium-webdriver-3.1.0/lib/selenium/webdriver/remote/http/common.rb:85:in `create_response'
/Users/egbert/.rbenv/versions/2.0.0-p648/lib/ruby/gems/2.0.0/gems/selenium-webdriver-3.1.0/lib/selenium/webdriver/remote/http/default.rb:107:in `request'
/Users/egbert/.rbenv/versions/2.0.0-p648/lib/ruby/gems/2.0.0/gems/selenium-webdriver-3.1.0/lib/selenium/webdriver/remote/http/common.rb:63:in `call'
/Users/egbert/.rbenv/versions/2.0.0-p648/lib/ruby/gems/2.0.0/gems/selenium-webdriver-3.1.0/lib/selenium/webdriver/remote/w3c_bridge.rb:625:in `raw_execute'
/Users/egbert/.rbenv/versions/2.0.0-p648/lib/ruby/gems/2.0.0/gems/selenium-webdriver-3.1.0/lib/selenium/webdriver/remote/w3c_bridge.rb:600:in `execute'
/Users/egbert/.rbenv/versions/2.0.0-p648/lib/ruby/gems/2.0.0/gems/selenium-webdriver-3.1.0/lib/selenium/webdriver/remote/w3c_bridge.rb:399:in `send_actions'
/Users/egbert/.rbenv/versions/2.0.0-p648/lib/ruby/gems/2.0.0/gems/selenium-webdriver-3.1.0/lib/selenium/webdriver/common/w3c_action_builder.rb:164:in `perform'
/Users/egbert/.rbenv/versions/2.0.0-p648/lib/ruby/gems/2.0.0/gems/watir-6.2.0/lib/watir/elements/element.rb:160:in `block in right_click'
/Users/egbert/.rbenv/versions/2.0.0-p648/lib/ruby/gems/2.0.0/gems/watir-6.2.0/lib/watir/elements/element.rb:640:in `element_call'
/Users/egbert/.rbenv/versions/2.0.0-p648/lib/ruby/gems/2.0.0/gems/watir-6.2.0/lib/watir/elements/element.rb:160:in `right_click'
```

**Comment by pjanik** [comment] 2017-02-27 11:45
Same here, `.drag_to` implementation seems to be broken. When I switch to chromedriver, everything works.

I'm using geckodriver 0.14.0 and selenium-webdriver 3.1.0.

**Comment by andreastt** [comment] 2017-02-27 17:27
This would originate from https://github.com/mozilla/webdriver-rust/blob/master/src/command.rs#L1514-L1522, which means exactly what the error message says: For a pointer-action, the `type` field is missing.

@jgraham recently fixed `pointedMove` and `pointerCancel`, which may have caused this problem if you were implementing the specification correctly. It is hard to tell without a trace-level log.

If this is correct, the problem should disappear with the next release of geckodriver (0.15.0).

cc @mjzffr

**Comment by IohWD** [comment] 2017-03-29 05:58
Same issue still with Selenium jar 3.3 , Gecko 0.15 , Firefox 52.  Drag and drop is not happening.

**Comment by IohWD** [comment] 2017-04-05 12:30
Still facing the same issue with Gecko .15, FF52 and Se jar 3.3.1.

**Comment by whimboo** [comment] 2019-01-30 08:38
@shs96c how does it look like for the 0.24.0 release of geckodriver? Given that we are using Serde for serialization and deserialization (since the 0.22.0 release) the details should be clear now.

Please let us know.

**Comment by whimboo** [comment] 2020-01-03 08:10
No further feedback from @shs96c within a year. So I'm going to close the issue and assume that the changes with Serde were helpful.

**Closed by whimboo** 2020-01-03 08:10 UTC
Labels: waiting for reporter feedback, webdriver-rust
