### ISSUE TITLE
webdriver.Firefox() hangs , using multi-thread test

### ISSUE THREAD

**Issue by neliqian** [mozilla/geckodriver#1222] opened 2018-03-19 11:42 UTC
geckodriver 0.19.0
Mozilla Firefox 56.0.1
selenium 3.11.0
python 2.7.11

I use browsermob-proxy and webdriver.Firefox() , running multiple Firefox browser test, and i find the func block at 'webdriver.Firefox()', no return and no exception, at this time i exec 'netstat':

[root@localhost ~]# netstat -apn |grep geckodriver
tcp        0      0 127.0.0.1:49762         0.0.0.0:*               LISTEN      3542/geckodriver    
tcp        0      0 127.0.0.1:49762         127.0.0.1:36852         ESTABLISHED 3542/geckodriver    
tcp        0      0 127.0.0.1:52819         127.0.0.1:52819         ESTABLISHED 3542/geckodriver 
[root@localhost ~]# 

Look above output, selenium remoteserver create a socket and connect to geckodriver, then geckodriver  
use port 52819  connect to Firefox(not find this at log, just my opinion), obvious last connection use the same src/dst port . so how can I handle this problem, this error is inevitable in period of time.

I check the geckodriver log, and not find any usefull comment.

Thanks!

Here is another 'netstat' output when fun hangs:
[root@localhost ~]# netstat -apn |grep geckodriver
tcp        0      0 127.0.0.1:46528         0.0.0.0:*               LISTEN      30412/geckodriver   
tcp        0      0 127.0.0.1:45253         0.0.0.0:*               LISTEN      32019/geckodriver   
tcp        0      0 127.0.0.1:45253         127.0.0.1:57798         ESTABLISHED 32019/geckodriver   
tcp        0      0 127.0.0.1:37795         127.0.0.1:37795         ESTABLISHED 32019/geckodriver   
tcp        0      0 127.0.0.1:60314         127.0.0.1:60314         ESTABLISHED 30412/geckodriver   
tcp        0      0 127.0.0.1:46528         127.0.0.1:47114         ESTABLISHED 30412/geckodriver   
[root@localhost ~]#

**Comment by andreastt** [comment] 2018-03-19 12:03
If you could attach a [trace-level log] from geckodriver, I would be much obliged.

[trace-level log]: https://searchfox.org/mozilla-central/source/testing/geckodriver/doc/TraceLogs.md

**Comment by neliqian** [comment] 2018-03-20 01:08
[firefox.log](https://github.com/mozilla/geckodriver/files/1827506/firefox.log)

**Comment by neliqian** [comment] 2018-03-20 01:24
@andreastt My test use Chrome driver ( webdriver.Chrome() ) at the same time, and no error occured. I use 20 threads execute test process. every thread has same procedure. 
`
display = Display()
display.start()
server = Server("/usr/local/browsermob-proxy-2.1.4/bin/browsermob-proxy")
server.start() 

#following is every thread's process code
profile = webdriver.FirefoxProfile()
profile.set_proxy(proxy.selenium_proxy())

try:
    driver = webdriver.Firefox(firefox_profile=profile, log_path="firefox.log")
except Exception as e:
    proxy.close()
    return

driver.get(url)
proxy.close()
driver.quit()
return
`

**Comment by neliqian** [comment] 2018-03-20 02:19
@andreastt 
[root@localhost ~]# netstat -apn|grep geckodriver
tcp        0      0 127.0.0.1:52975         0.0.0.0:*               LISTEN      28229/geckodriver   
tcp        0      0 127.0.0.1:58921         127.0.0.1:58921         ESTABLISHED 28229/geckodriver   
tcp        0      0 127.0.0.1:52975         127.0.0.1:58730         ESTABLISHED 28229/geckodriver   
[root@localhost ~]# 

[root@localhost ~]# ps ax|grep geckodriver
28229 pts/4    Sl+    0:00 geckodriver --port 52975

If I kill the process 28229 , then the test process can raise a exception and my process can continue.

**Comment by whimboo** [comment] 2018-03-20 14:32
Please also note the failure line at the very end of the attached log:

> (/usr/lib64/firefox/firefox:32578): Gdk-WARNING **: /usr/lib64/firefox/firefox: Fatal IO error 11 (Resource temporarily unavailable) on X server :1001.

This indicates that something is wrong with your X server, and as such Firefox doesn't work as expected. geckodriver will try to connect but should fail after 60s.

**Comment by neliqian** [comment] 2018-03-21 02:43
@whimboo Thank you for your help, but I run the test again right now, and the log not write info 
"(/usr/lib64/firefox/firefox:32578): Gdk-WARNING **: /usr/lib64/firefox/firefox: Fatal IO error 11 (Resource temporarily unavailable) on X server :1001." when the error occurred.
And geckodriver not return any status or raise exception , just hangs forever.

**Comment by whimboo** [comment] 2018-03-21 12:02
Can you please check again by using geckodriver 0.20, and a latest Firefox Nightly debug build? You can grab one from here: https://queue.taskcluster.net/v1/task/PRhLFHNlSV6ul0tvMNZ_kQ/runs/0/artifacts/public/build/target.tar.bz2. Just untar, and use it.

It has way more log output, so make sure to only upload the relevant part as trace log to this issue. Thanks.

**Comment by neliqian** [comment] 2018-03-22 02:08
@whimboo I just run the test using geckodriver 0.20 and given firefox version,and error still exists. I think when something has problem and cause socket connect to invalid address(connect to itself). So I have to write a shell script and run as cycle task to kill the block process.
kill -9 `netstat -apn |grep geckodriver|awk '{if($4 == $5) print strtonum($7)}'`

**Comment by whimboo** [comment] 2018-03-26 08:46
@neliqian I cannot say for sure what's going on because you didn't upload a trace log. Please make sure to upload such one, and if possible only those parts at the end given that it is huge.

Your latest attached log actually contains a crash of Firefox. It's all starting at line 121210 with some IPC channel warnings. Then in line 121240 we force a crash. Later in line 121416 gdb is keeping the process active for debugging purposes, and that is where you see the hang because it waits 300s.

If you are familiar with gdb it would be great if you could fetch the stack of the crashing thread and report it here. Otherwise we might have to go back to a regular Nightly build, to be able to retrieve the crash details. The stacks as already printed are not that helpful.

**Comment by andreastt** [comment] 2018-03-28 14:08
@neliqian I will close this unless you provide the details necessary to reproduce the issue.

**Closed** 2018-05-15 14:51 UTC
Labels: waiting for reporter feedback
