### ISSUE TITLE
WebDriverException: Failed to decode response from marionette Selenium + Java

### ISSUE THREAD

**Issue by Gudzo** [mozilla/geckodriver#1372] opened 2018-09-14 11:44 UTC
* Version: geckodriver version 0.21
* Platform  Linux/CodeBuild AWS
* Firefox: 61.0.2
* Selenium: 3.6

I am trying to run headless Firefox on AWS Codebuild linux. I am using selenium 3.6, gecko-driver 0.21.0, Firefox version 61.0.2. When I run the tests locally everything works fine, when I run it on Codebuild I get an error. The error on line 126 is when I am trying to click on an element. My code:

Code:

      public static WebDriver getFirefoxHeadless(Map map) throws IOException {
        System.setProperty("webdriver.gecko.driver","/root/firefox_driver/geckodriver");

        DesiredCapabilities capabilities = 
        DesiredCapabilities.firefox();

        FirefoxOptions options = new FirefoxOptions();
        options.setHeadless(true);

        GeckoDriverService service;
        GeckoDriverService.Builder builder = new 
        GeckoDriverService.Builder();
        service = builder.usingAnyFreePort()
                .withEnvironment(map)
                .build();

        service.start();

        options.merge(capabilities);

        return new FirefoxDriver(service, options);
    }

@BeforeTest
    public void setUp() throws IOException, InterruptedException {
        driver = Helpers.getFirefoxHeadless(MozLog.getMozLogMap());
        driver.manage().window().setSize(new Dimension(1920, 1080));

        driver.get(getUrl());
        Thread.sleep(4000);
    }

    @Test
    public void clickoutTestFirefox() throws IOException, InterruptedException, SQLException {
        driver.findElement(By.cssSelector(".popup-close-button-slim")).click(); 

Error:
org.openqa.selenium.WebDriverException: Failed to decode response from marionette Build info: version: '3.13.0', revision: '2f0d292', time: '2018-06-25T15:24:21.231Z' System info: host: 'ip-172-32-0-217.eu-west-1.compute.internal', ip: '172.32.0.217', os.name: 'Linux', os.arch: 'amd64', os.version: '4.14.59-64.43.amzn1.x86_64', java.version: '1.8.0_171' Driver info: org.openqa.selenium.firefox.FirefoxDriver Capabilities {acceptInsecureCerts: true, browserName: firefox, browserVersion: 62.0, javascriptEnabled: true, moz:accessibilityChecks: false, moz:headless: true, moz:processID: 2393, moz:profile: /tmp/rust_mozprofile.AD0yj8..., moz:useNonSpecCompliantPointerOrigin: false, moz:webdriverClick: true, pageLoadStrategy: normal, platform: LINUX, platformName: LINUX, platformVersion: 4.14.59-64.43.amzn1.x86_64, rotatable: false, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}} Session ID: f0ea1950-77fe-463b-a8a1-e0dc5458800f *** Element info: {Using=css selector, value=.popup-close-button-slim} at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) at java.lang.reflect.Constructor.newInstance(Constructor.java:423) at org.openqa.selenium.remote.http.W3CHttpResponseCodec.createException(W3CHttpResponseCodec.java:187) at org.openqa.selenium.remote.http.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:122) at org.openqa.selenium.remote.http.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:49) at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:158) at org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:83) at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:548) at org.openqa.selenium.remote.RemoteWebDriver.findElement(RemoteWebDriver.java:322) at org.openqa.selenium.remote.RemoteWebDriver.findElementByCssSelector(RemoteWebDriver.java:416) at org.openqa.selenium.By$ByCssSelector.findElement(By.java:431) at org.openqa.selenium.remote.RemoteWebDriver.findElement(RemoteWebDriver.java:314) at com.clickout.apitesting.waUITest.E2ECNTestFirefox.clickoutTestFirefox(E2ECNTestFirefox.java:126)

**Comment by andreastt** [comment] 2018-09-14 11:51
Could you please attach a [trace-level log] from geckodriver? Read more about reporting actionable bugs in our [contribution guidelines].

[trace-level log]: https://searchfox.org/mozilla-central/source/testing/geckodriver/doc/TraceLogs.md
[contribution guidelines]: https://searchfox.org/mozilla-central/source/testing/geckodriver/CONTRIBUTING.md#reporting-bugs

**Comment by andreastt** [comment] 2018-09-14 12:26
I don’t know what Codebuild is, but the logs are printed to stdout by geckodriver. You could potentially intercept that and print it to a file.

**Comment by Gudzo** [comment] 2018-09-14 12:30
@andreastt AWS Codebuild, it's a docker which is used only for the duration of the test, then it erases itself and shuts down.

**Comment by Gudzo** [comment] 2018-09-14 12:42
@andreastt Here it is:

Sep 14, 2018 12:37:58 PM org.openqa.selenium.remote.DesiredCapabilities firefox
    INFO: Using `new FirefoxOptions()` is preferred to `DesiredCapabilities.firefox()`
    1536928678371	geckodriver	INFO	geckodriver 0.21.0
    1536928678378	geckodriver	INFO	Listening on 127.0.0.1:11495
    1536928678887	mozrunner::runner	INFO	Running command: "/usr/bin/firefox" "-marionette" "-headless" "-foreground" "-no-remote" "-profile" "/tmp/rust_mozprofile.RQINSsu7gPih"
    1536928678888	geckodriver::marionette	DEBUG	Waiting 60s to connect to browser on 127.0.0.1:41189
    *** You are running in headless mode.
6 XSELINUXs still allocated at reset
SCREEN: 0 objects of 256 bytes = 0 total bytes 0 private allocs
DEVICE: 0 objects of 96 bytes = 0 total bytes 0 private allocs
CLIENT: 0 objects of 136 bytes = 0 total bytes 0 private allocs
WINDOW: 0 objects of 32 bytes = 0 total bytes 0 private allocs
PIXMAP: 1 objects of 16 bytes = 16 total bytes 0 private allocs
GC: 4 objects of 16 bytes = 64 total bytes 0 private allocs
CURSOR: 1 objects of 8 bytes = 8 total bytes 0 private allocs
TOTAL: 6 objects, 88 bytes, 0 allocs
1 PIXMAPs still allocated at reset
PIXMAP: 1 objects of 16 bytes = 16 total bytes 0 private allocs
GC: 4 objects of 16 bytes = 64 total bytes 0 private allocs
CURSOR: 1 objects of 8 bytes = 8 total bytes 0 private allocs
TOTAL: 6 objects, 88 bytes, 0 allocs
4 GCs still allocated at reset
GC: 4 objects of 16 bytes = 64 total bytes 0 private allocs
CURSOR: 1 objects of 8 bytes = 8 total bytes 0 private allocs
TOTAL: 5 objects, 72 bytes, 0 allocs
1 CURSORs still allocated at reset
CURSOR: 1 objects of 8 bytes = 8 total bytes 0 private allocs
TOTAL: 1 objects, 8 bytes, 0 allocs
1 CURSOR_BITSs still allocated at reset
TOTAL: 0 objects, 0 bytes, 0 allocs
    1536928679544	Marionette	DEBUG	Received observer notification profile-after-change
    1536928680425	Marionette	DEBUG	Received observer notification command-line-startup
    1536928680425	Marionette	DEBUG	Received observer notification nsPref:changed
    1536928680425	Marionette	DEBUG	Init aborted (running=false, enabled=true, finalUIStartup=false)
    1536928681122	Marionette	DEBUG	Received observer notification sessionstore-windows-restored
    1536928681122	Marionette	DEBUG	Waiting for delayed startup...
    1536928681344	Marionette	DEBUG	Setting recommended pref apz.content_response_timeout to 60000
    1536928681344	Marionette	DEBUG	Setting recommended pref browser.download.panel.shown to true
    1536928681344	Marionette	DEBUG	Setting recommended pref browser.pagethumbnails.capturing_disabled to true
    1536928681345	Marionette	DEBUG	Setting recommended pref browser.search.update to false
    1536928681345	Marionette	DEBUG	Setting recommended pref toolkit.cosmeticAnimations.enabled to false
    1536928681345	Marionette	DEBUG	Setting recommended pref browser.tabs.disableBackgroundZombification to false
    1536928681346	Marionette	DEBUG	Setting recommended pref browser.tabs.warnOnCloseOtherTabs to false
    1536928681346	Marionette	DEBUG	Setting recommended pref browser.tabs.warnOnOpen to false
    1536928681346	Marionette	DEBUG	Setting recommended pref browser.usedOnWindows10.introURL to 
    1536928681346	Marionette	DEBUG	Setting recommended pref browser.urlbar.suggest.searches to false
    1536928681346	Marionette	DEBUG	Setting recommended pref datareporting.policy.dataSubmissionPolicyAccepted to false
    1536928681346	Marionette	DEBUG	Setting recommended pref dom.disable_beforeunload to true
    1536928681346	Marionette	DEBUG	Setting recommended pref dom.disable_open_during_load to false
    1536928681346	Marionette	DEBUG	Setting recommended pref dom.file.createInChild to true
    1536928681347	Marionette	DEBUG	Setting recommended pref dom.max_chrome_script_run_time to 0
    1536928681347	Marionette	DEBUG	Setting recommended pref dom.max_script_run_time to 0
    1536928681347	Marionette	DEBUG	Setting recommended pref extensions.getAddons.cache.enabled to false
    1536928681347	Marionette	DEBUG	Setting recommended pref extensions.webservice.discoverURL to http://%(server)s/dummy/discoveryURL
    1536928681347	Marionette	DEBUG	Setting recommended pref network.http.prompt-temp-redirect to false
    1536928681347	Marionette	DEBUG	Setting recommended pref network.http.speculative-parallel-limit to 0
    1536928681347	Marionette	DEBUG	Setting recommended pref security.fileuri.strict_origin_policy to false
    1536928681347	Marionette	DEBUG	Setting recommended pref security.notification_enable_delay to 0
    1536928681348	Marionette	DEBUG	Setting recommended pref signon.autofillForms to false
    1536928681348	Marionette	DEBUG	Setting recommended pref signon.rememberSignons to false
    1536928681385	Marionette	INFO	Listening on port 41189
    1536928681386	Marionette	DEBUG	Remote service is active
    1536928681393	geckodriver::marionette	DEBUG	Connected to Marionette on 127.0.0.1:41189
    1536928681403	Marionette	DEBUG	Accepted connection 0 from 127.0.0.1:39124
    1536928681404	Marionette	TRACE	0 -> [0,1,"WebDriver:NewSession",{"acceptInsecureCerts":true,"browserName":"firefox","capabilities":{"desiredCapabilities":{"acceptInsecureCerts":true,"browserName":"firefox"}}}]
    1536928681405	Marionette	WARN	TLS certificate errors will be ignored for this session
    1536928681461	Marionette	DEBUG	[2147483649] Frame script loaded
    1536928681463	Marionette	DEBUG	[2147483649] Frame script registered
    1536928681476	Marionette	TRACE	0 <- [1,1,null,{"sessionId":"59d695e8-ad73-40fe-876b-523cf01ce07a","capabilities":{"browserName":"firefox","browserVersion":"62.0" ... 0,"moz:profile":"/tmp/rust_mozprofile.RQINSsu7gPih","moz:useNonSpecCompliantPointerOrigin":false,"moz:webdriverClick":true}}]
    1536928681479	webdriver::server	DEBUG	<- 200 OK {"value": {"sessionId":"59d695e8-ad73-40fe-876b-523cf01ce07a","capabilities":{"acceptInsecureCerts":true,"browserName":"firefox","browserVersion":"62.0","moz:accessibilityChecks":false,"moz:headless":true,"moz:processID":2470,"moz:profile":"/tmp/rust_mozprofile.RQINSsu7gPih","moz:useNonSpecCompliantPointerOrigin":false,"moz:webdriverClick":true,"pageLoadStrategy":"normal","platformName":"linux","platformVersion":"4.14.59-64.43.amzn1.x86_64","rotatable":false,"timeouts":{"implicit":0,"pageLoad":300000,"script":30000}}}}
    Sep 14, 2018 12:38:01 PM org.openqa.selenium.remote.ProtocolHandshake createSession
    INFO: Detected dialect: W3C
    1536928685537	webdriver::server	DEBUG	-> POST /session/59d695e8-ad73-40fe-876b-523cf01ce07a/window/rect {
      "width": 1920,
      "height": 1080
    }
    1536928685539	Marionette	TRACE	0 -> [0,2,"WebDriver:SetWindowRect",{"height":1080,"width":1920,"x":null,"y":null}]
    1536928685556	Marionette	TRACE	0 <- [1,2,null,{"x":0,"y":0,"width":1920,"height":1080,"state":"normal"}]
    1536928685556	webdriver::server	DEBUG	<- 200 OK {"value": {"height":1080,"width":1920,"x":0,"y":0}}
    1536928693561	webdriver::server	DEBUG	-> POST /session/59d695e8-ad73-40fe-876b-523cf01ce07a/url {
      "url": "https:\\cuponation.com.au"
    }
    1536928693563	Marionette	TRACE	0 -> [0,3,"WebDriver:Navigate",{"url": "https:\\cuponation.com.au"}]
    1536928693570	Marionette	DEBUG	[2147483649] Received DOM event beforeunload for about:blank
    1536928693920	Marionette	DEBUG	[2147483649] Received DOM event pagehide for about:blank
    1536928694288	Marionette	DEBUG	[2147483649] Received DOM event DOMContentLoaded for https:\\cuponation.com.au/
    [Parent 2470, Gecko_IOThread] WARNING: pipe error: Broken pipe: file /build/firefox-xSCEJa/firefox-62.0+build2/ipc/chromium/src/chrome/common/ipc_channel_posix.cc, line 726

    ###!!! [Parent][MessageChannel] Error: (msgtype=0x4A0017,name=PHttpChannel::Msg_DeleteSelf) Channel error: cannot send/recv


    ###!!! [Parent][MessageChannel] Error: (msgtype=0x4A0017,name=PHttpChannel::Msg_DeleteSelf) Channel error: cannot send/recv


    ###!!! [Parent][MessageChannel] Error: (msgtype=0x4A0017,name=PHttpChannel::Msg_DeleteSelf) Channel error: cannot send/recv


    ###!!! [Parent][MessageChannel] Error: (msgtype=0x4A0017,name=PHttpChannel::Msg_DeleteSelf) Channel error: cannot send/recv


    ###!!! [Parent][MessageChannel] Error: (msgtype=0x4A0017,name=PHttpChannel::Msg_DeleteSelf) Channel error: cannot send/recv


    ###!!! [Parent][MessageChannel] Error: (msgtype=0x4A0017,name=PHttpChannel::Msg_DeleteSelf) Channel error: cannot send/recv


    ###!!! [Parent][MessageChannel] Error: (msgtype=0x4A0017,name=PHttpChannel::Msg_DeleteSelf) Channel error: cannot send/recv


    ###!!! [Parent][MessageChannel] Error: (msgtype=0x4A0017,name=PHttpChannel::Msg_DeleteSelf) Channel error: cannot send/recv


    ###!!! [Parent][MessageChannel] Error: (msgtype=0x4A0017,name=PHttpChannel::Msg_DeleteSelf) Channel error: cannot send/recv


    ###!!! [Parent][MessageChannel] Error: (msgtype=0x4A0017,name=PHttpChannel::Msg_DeleteSelf) Channel error: cannot send/recv


    ###!!! [Parent][MessageChannel] Error: (msgtype=0x4A0017,name=PHttpChannel::Msg_DeleteSelf) Channel error: cannot send/recv


    ###!!! [Parent][MessageChannel] Error: (msgtype=0x4A0017,name=PHttpChannel::Msg_DeleteSelf) Channel error: cannot send/recv


    ###!!! [Parent][MessageChannel] Error: (msgtype=0x4A0017,name=PHttpChannel::Msg_DeleteSelf) Channel error: cannot send/recv


    ###!!! [Parent][MessageChannel] Error: (msgtype=0x4A0017,name=PHttpChannel::Msg_DeleteSelf) Channel error: cannot send/recv


    ###!!! [Parent][MessageChannel] Error: (msgtype=0x4A0017,name=PHttpChannel::Msg_DeleteSelf) Channel error: cannot send/recv


    ###!!! [Parent][MessageChannel] Error: (msgtype=0x4A0017,name=PHttpChannel::Msg_DeleteSelf) Channel error: cannot send/recv


    ###!!! [Parent][MessageChannel] Error: (msgtype=0x4A0017,name=PHttpChannel::Msg_DeleteSelf) Channel error: cannot send/recv


    ###!!! [Parent][MessageChannel] Error: (msgtype=0x4A0017,name=PHttpChannel::Msg_DeleteSelf) Channel error: cannot send/recv


    ###!!! [Parent][MessageChannel] Error: (msgtype=0x4A0017,name=PHttpChannel::Msg_DeleteSelf) Channel error: cannot send/recv


    ###!!! [Parent][MessageChannel] Error: (msgtype=0x4A0017,name=PHttpChannel::Msg_DeleteSelf) Channel error: cannot send/recv


    ###!!! [Parent][MessageChannel] Error: (msgtype=0x4A0017,name=PHttpChannel::Msg_DeleteSelf) Channel error: cannot send/recv


    ###!!! [Parent][MessageChannel] Error: (msgtype=0x4A0017,name=PHttpChannel::Msg_DeleteSelf) Channel error: cannot send/recv


    ###!!! [Parent][MessageChannel] Error: (msgtype=0x4A0017,name=PHttpChannel::Msg_DeleteSelf) Channel error: cannot send/recv


    ###!!! [Parent][MessageChannel] Error: (msgtype=0x4A0017,name=PHttpChannel::Msg_DeleteSelf) Channel error: cannot send/recv


    ###!!! [Parent][MessageChannel] Error: (msgtype=0x170080,name=PBrowser::Msg_Destroy) Channel error: cannot send/recv

    1536928694617	Marionette	DEBUG	[23] Frame script loaded
    1536928694618	Marionette	DEBUG	[23] Frame script registered
    A content process crashed and MOZ_CRASHREPORTER_SHUTDOWN is set, shutting down
    1536928694661	Marionette	DEBUG	[23] Check readyState uninitialized for about:blank
    1536928694687	Marionette	DEBUG	Received DOM event unload for [object XULDocument]
    1536928694694	Marionette	DEBUG	Received observer notification message-manager-disconnect
    1536928694694	Marionette	TRACE	0 <- [1,3,null,{"value":null}]
    1536928695167	webdriver::server	DEBUG	<- 200 OK {"value": null}
    1536928695183	Marionette	DEBUG	Closed connection 0
    1536928695282	Marionette	DEBUG	Received observer notification xpcom-will-shutdown
    1536928695282	Marionette	DEBUG	Resetting recommended pref apz.content_response_timeout
    1536928695283	Marionette	DEBUG	Resetting recommended pref browser.download.panel.shown
    1536928695283	Marionette	DEBUG	Resetting recommended pref browser.pagethumbnails.capturing_disabled
    1536928695283	Marionette	DEBUG	Resetting recommended pref browser.search.update
    1536928695283	Marionette	DEBUG	Resetting recommended pref toolkit.cosmeticAnimations.enabled
    1536928695283	Marionette	DEBUG	Resetting recommended pref browser.tabs.disableBackgroundZombification
    1536928695284	Marionette	DEBUG	Resetting recommended pref browser.tabs.warnOnCloseOtherTabs
    1536928695284	Marionette	DEBUG	Resetting recommended pref browser.tabs.warnOnOpen
    1536928695284	Marionette	DEBUG	Resetting recommended pref browser.usedOnWindows10.introURL
    1536928695284	Marionette	DEBUG	Resetting recommended pref browser.urlbar.suggest.searches
    1536928695285	Marionette	DEBUG	Resetting recommended pref datareporting.policy.dataSubmissionPolicyAccepted
    1536928695285	Marionette	DEBUG	Resetting recommended pref dom.disable_beforeunload
    1536928695285	Marionette	DEBUG	Resetting recommended pref dom.disable_open_during_load
    1536928695285	Marionette	DEBUG	Resetting recommended pref dom.file.createInChild
    1536928695285	Marionette	DEBUG	Resetting recommended pref dom.max_chrome_script_run_time
    1536928695285	Marionette	DEBUG	Resetting recommended pref dom.max_script_run_time
    1536928695286	Marionette	DEBUG	Resetting recommended pref extensions.getAddons.cache.enabled
    1536928695286	Marionette	DEBUG	Resetting recommended pref extensions.webservice.discoverURL
    1536928695286	Marionette	DEBUG	Resetting recommended pref network.http.prompt-temp-redirect
    1536928695286	Marionette	DEBUG	Resetting recommended pref network.http.speculative-parallel-limit
    1536928695286	Marionette	DEBUG	Resetting recommended pref security.fileuri.strict_origin_policy
    1536928695286	Marionette	DEBUG	Resetting recommended pref security.notification_enable_delay
    1536928695286	Marionette	DEBUG	Resetting recommended pref signon.autofillForms
    1536928695286	Marionette	DEBUG	Resetting recommended pref signon.rememberSignons
    1536928695287	Marionette	INFO	Stopped listening on port 41189
    1536928695287	Marionette	DEBUG	Remote service is inactive

UI Clickout test > UI Clickout test > com.clickout.apitesting.waUITest.E2ECNTestFirefox.clickoutTestFirefox STANDARD_ERROR
    1536928703191	webdriver::server	DEBUG	-> POST /session/59d695e8-ad73-40fe-876b-523cf01ce07a/element {
      "value": ".popup-close-button-slim",
      "using": "css selector"
    }
    1536928703191	webdriver::server	DEBUG	Deleting session
    1536928703191	geckodriver::marionette	DEBUG	Browser process stopped: exit code: 0
    1536928703196	webdriver::server	DEBUG	<- 500 Internal Server Error {"value":{"error":"unknown error","message":"Failed to decode response from marionette","stacktrace":""}}

UI Clickout test > UI Clickout test > com.clickout.apitesting.waUITest.E2ECNTestFirefox.clickoutTestFirefox FAILED
    org.openqa.selenium.WebDriverException: Failed to decode response from marionette
    Build info: version: '3.13.0', revision: '2f0d292', time: '2018-06-25T15:24:21.231Z'
    System info: host: 'ip-172-32-0-201.eu-west-1.compute.internal', ip: '172.32.0.201', os.name: 'Linux', os.arch: 'amd64', os.version: '4.14.59-64.43.amzn1.x86_64', java.version: '1.8.0_171'
    Driver info: org.openqa.selenium.firefox.FirefoxDriver
    Capabilities {acceptInsecureCerts: true, browserName: firefox, browserVersion: 62.0, javascriptEnabled: true, moz:accessibilityChecks: false, moz:headless: true, moz:processID: 2470, moz:profile: /tmp/rust_mozprofile.RQINSs..., moz:useNonSpecCompliantPointerOrigin: false, moz:webdriverClick: true, pageLoadStrategy: normal, platform: LINUX, platformName: LINUX, platformVersion: 4.14.59-64.43.amzn1.x86_64, rotatable: false, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}}
    Session ID: 59d695e8-ad73-40fe-876b-523cf01ce07a
    *** Element info: {Using=css selector, value=.popup-close-button-slim}
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
        at org.openqa.selenium.remote.http.W3CHttpResponseCodec.createException(W3CHttpResponseCodec.java:187)
        at org.openqa.selenium.remote.http.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:122)
        at org.openqa.selenium.remote.http.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:49)
        at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:158)
        at org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:83)
        at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:548)
        at org.openqa.selenium.remote.RemoteWebDriver.findElement(RemoteWebDriver.java:322)
        at org.openqa.selenium.remote.RemoteWebDriver.findElementByCssSelector(RemoteWebDriver.java:416)
        at org.openqa.selenium.By$ByCssSelector.findElement(By.java:431)
        at org.openqa.selenium.remote.RemoteWebDriver.findElement(RemoteWebDriver.java:314)
        at com.clickout.apitesting.waUITest.E2ECNTestFirefox.clickoutTestFirefox(E2ECNTestFirefox.java:129)

**Comment by whimboo** [comment] 2018-09-17 11:02
This is a crash of Firefox. Could you check please if it is possible for you to extract the minidump file? See https://firefox-source-docs.mozilla.org/testing/geckodriver/geckodriver/CrashReports.html in how to do it.

Btw. is this running in a Selenium docker image?

**Comment by Gudzo** [comment] 2018-09-17 11:36
@whimboo It's a docker instance which comes with Linux and Java installed. I am having a hard-time finding an example with Java to retrieve the minidump file, some help maybe?

**Comment by whimboo** [comment] 2018-09-17 12:08
@Gudzo in that case please try to increase the SHM size first. See https://github.com/SeleniumHQ/docker-selenium/pull/485 for details. Maybe this already helps. Please let me know.

**Comment by Gudzo** [comment] 2018-09-17 13:32
@whimboo Unfortunately AWS CodeBuild doesn't support changing the shm size on it's docker instances.

**Comment by whimboo** [comment] 2018-09-17 15:59
To which size it is set?

**Comment by Gudzo** [comment] 2018-09-17 18:54
@whimboo 64mb, but the funny thing is if I run the same test with chrome headless on the same docker instance, everything works fine.

**Comment by whimboo** [comment] 2018-09-18 06:12
Yes, so that is too less memory. There is https://bugzilla.mozilla.org/show_bug.cgi?id=1245239 still open and as long it is not fixed Firefox won't really work in such an environment. Best bet for you is to reach out to maintainers of AWS CodeBuild, and ask if they could increase the size.

I will mark this issue as dupe of #285.

**Closed by whimboo** 2018-09-18 06:12 UTC
Labels: waiting for reporter feedback
