### ISSUE TITLE
Net::ReadTimeout after trying to resize browser to the size it already is

### ISSUE THREAD

**Issue by sjieg** [mozilla/geckodriver#791] opened 2017-06-21 14:02 UTC
## Platform and application details
* Platform: Windows (probably all)
* Firefox:  54
* Selenium: Ruby Selenium 3.4.3

## Steps to reproduce

1) Open the browser
2) Get the browser window dimensions
3) Resize the browser to the same dimensions

- [x] Reproducable testcase:
```
# Open browser and navigate to google
width, height = driver.window.size
dimension = Selenium::WebDriver::Dimension.new(Integer(width), Integer(height))
driver.manage.window.size = dimension
# Errror and unable to send new browser commands.
```

- [x] A trace level log:
https://gist.github.com/lmtierney/4f6e4085ab80688a251a53a1f7b5cc02

**Comment by davehunt** [comment] 2017-06-21 14:23
I suspect this is a duplicate or at least same root cause as https://github.com/mozilla/geckodriver/issues/703

**Comment by andreastt** [comment] 2017-06-21 18:14
This is, I think, not the same issue as #703. This particular issue is about setting the window size to the existing size, and has been fixed in https://bugzilla.mozilla.org/show_bug.cgi?id=1357878.

**Closed by andreastt** 2017-06-21 18:14 UTC
