### ISSUE TITLE
driver.quit() throwing "org.openqa.selenium.os.UnixProcess destroy" error

### ISSUE THREAD

**Issue by 600rob** [mozilla/geckodriver#961] opened 2017-09-19 09:16 UTC
## System
* GeckoDriver Version: <0.19.0-win 64>
* Platform: <Windows 7 professional sp1>
* Firefox: <FF55.0.3 (32 bit)>
* Selenium: < 3.5.3>
* Java: < 1.8>
* Maven: < 4.11>

## Details

<Im learning to use selenium with java and attempting to run some basic tests to get me up and running.

Actual results:

When trying to run a test which should open a browser in firefox, verify the title, then close the browser and quit the driver. The browser appears to open and close as expected. 
However the test code that i am running fails and the following error is returned in my java console:

**“Sep 19, 2017 9:52:52 AM org.openqa.selenium.os.UnixProcess destroy
SEVERE: Unable to kill process with PID 4488”**

On inspecting the active processes on my machine via task manager, the process            
“geckodriver.exe” is still running and must be manually stopped in order to quit the process

Test environment details:
Windows 7
Java version: 1.8
Browser: FF55.0.3 (32 bit)
GeckoDriver 0.19.0-win64
Selenium 3.53
Maven 4.11

>

## Stacktrace

<1505811159766	geckodriver	INFO	geckodriver 0.19.0
1505811159935	geckodriver	INFO	Listening on 127.0.0.1:46288
1505811160587	mozrunner::runner	INFO	Running command: "C:\\Program Files (x86)\\Mozilla Firefox\\firefox.exe" "-marionette" "-profile" "C:\\Users\\ROBERT~1.HOP\\AppData\\Local\\Temp\\rust_mozprofile.1z0XM1csCWW2"
1505811161137	addons.xpi	WARN	Error parsing extensions state: [Exception... "Component returned failure code: 0x80520012 (NS_ERROR_FILE_NOT_FOUND) [amIAddonManagerStartup.readStartupData]"  nsresult: "0x80520012 (NS_ERROR_FILE_NOT_FOUND)"  location: "JS frame :: resource://gre/modules/addons/XPIProvider.jsm :: loadExtensionState :: line 1596"  data: no] Stack trace: loadExtensionState()@resource://gre/modules/addons/XPIProvider.jsm:1596 < getInstallState()@resource://gre/modules/addons/XPIProvider.jsm:1631 < checkForChanges()@resource://gre/modules/addons/XPIProvider.jsm:3152 < startup()@resource://gre/modules/addons/XPIProvider.jsm:2246 < callProvider()@resource://gre/modules/AddonManager.jsm:271 < _startProvider()@resource://gre/modules/AddonManager.jsm:741 < startup()@resource://gre/modules/AddonManager.jsm:908 < startup()@resource://gre/modules/AddonManager.jsm:3122 < observe()@jar:file:///C:/Program%20Files%20(x86)/Mozilla%20Firefox/omni.ja!/components/addonManager.js:65
1505811161741	Marionette	INFO	Enabled via --marionette
1505811164358	Marionette	INFO	Listening on port 54565
1505811164366	Marionette	INFO	Listening on port 54565
1505811164450	Marionette	WARN	TLS certificate errors will be ignored for this session
1505811164511	Marionette	DEBUG	loaded listener.js
Sep 19, 2017 9:52:44 AM org.openqa.selenium.remote.ProtocolHandshake createSession
INFO: Detected dialect: W3C
1505811164656	Marionette	DEBUG	Received DOM event "beforeunload" for "about:blank"
1505811165471	Marionette	DEBUG	Received DOM event "pagehide" for "about:blank"
1505811165471	Marionette	DEBUG	Received DOM event "unload" for "about:blank"
1505811166612	Marionette	DEBUG	Received DOM event "DOMContentLoaded" for "http://seleniumsimplified.com/"
1505811167668	Marionette	DEBUG	Received DOM event "DOMContentLoaded" for "https://www.youtube.com/embed/Qf9up6t1U34"
1505811168044	Marionette	DEBUG	Received DOM event "DOMContentLoaded" for "https://www.youtube.com/embed/VtcMvcC28oc?rel=0"
1505811168048	Marionette	DEBUG	Received DOM event "DOMContentLoaded" for "https://www.youtube.com/embed/QkSbisJjqpk?rel=0"
1505811168595	Marionette	DEBUG	Received observer notification "outer-window-destroyed" for "2147483662"
1505811168737	Marionette	DEBUG	Received observer notification "outer-window-destroyed" for "2147483664"
1505811168832	Marionette	DEBUG	Received observer notification "outer-window-destroyed" for "2147483666"
1505811169033	Marionette	DEBUG	Received DOM event "pageshow" for "https://www.youtube.com/embed/Qf9up6t1U34"
1505811169045	Marionette	DEBUG	Received DOM event "pageshow" for "https://www.youtube.com/embed/VtcMvcC28oc?rel=0"
1505811169053	Marionette	DEBUG	Received DOM event "pageshow" for "https://www.youtube.com/embed/QkSbisJjqpk?rel=0"
1505811169061	Marionette	DEBUG	Received DOM event "pageshow" for "http://seleniumsimplified.com/"
**Sep 19, 2017 9:52:52 AM org.openqa.selenium.os.UnixProcess destroy
SEVERE: Unable to kill process with PID 4488**

org.openqa.selenium.SessionNotCreatedException: Tried to run command without establishing a connection
Build info: version: '3.5.3', revision: 'a88d25fe6b', time: '2017-08-29T12:42:44.417Z'
System info: host: 'LT-LGC07999', ip: '10.44.22.27', os.name: 'Windows 7', os.arch: 'amd64', os.version: '6.1', java.version: '1.8.0_131'
Driver info: org.openqa.selenium.firefox.MarionetteDriver
Capabilities [{moz:profile=C:\Users\ROBERT~1.HOP\AppData\Local\Temp\rust_mozprofile.1z0XM1csCWW2, rotatable=false, timeouts={implicit=0, pageLoad=300000, script=30000}, pageLoadStrategy=normal, platform=XP, specificationLevel=0, moz:accessibilityChecks=false, acceptInsecureCerts=true, browserVersion=55.0.3, platformVersion=6.1, moz:processID=10004, browserName=firefox, javascriptEnabled=true, platformName=XP}]
Session ID: 21d3608a-2037-4d61-ad77-db02c90d71e6

	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.openqa.selenium.remote.http.W3CHttpResponseCodec.createException(W3CHttpResponseCodec.java:185)
	at org.openqa.selenium.remote.http.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:120)
	at org.openqa.selenium.remote.http.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:49)
	at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:164)
	at org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:82)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:646)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:703)
	at org.openqa.selenium.remote.RemoteWebDriver.quit(RemoteWebDriver.java:542)
	at com.eviltester.webdriver.MyFirstTestFF48.startWebDriver(MyFirstTestFF48.java:40)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:47)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:44)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:271)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:70)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:50)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:63)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:236)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:53)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:229)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:309)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:160)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:47)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)

Process finished with exit code -1
>

##Steps to reproduce: - Using the above config settings, attempt to run the following code:

<package com.eviltester.webdriver;

import org.junit.Assert;
import org.junit.Test;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.MarionetteDriver;

public class MyFirstTestFF48 {

    @Test
    public void startWebDriver(){

    

        WebDriver driver = new MarionetteDriver();
        driver.navigate().to("http://seleniumsimplified.com");

        Assert.assertTrue("title should start differently",
                driver.getTitle().startsWith("Selenium Simplified"));

        driver.close();
        driver.quit();
		}
		
	}
>

**Comment by wx7614140** [comment] 2017-09-19 10:42
The same Exception occured in my programe with "Platform: Windows 7". It worked well in win10.

**Comment by 600rob** [comment] 2017-09-19 10:47
Unfortunately i can only use windows 7 as i am doing this on a company machine.
Does anyone know of a workaround/solution for windows 7?

**Comment by andreastt** [comment] 2017-09-19 15:21
Duplicate of https://github.com/mozilla/geckodriver/issues/956.

**Closed by andreastt** 2017-09-19 15:21 UTC
