### ISSUE TITLE
geckodriver always hangs in headless mode

### ISSUE THREAD

**Issue by pyfreyr** [mozilla/geckodriver#1719] opened 2020-05-07 07:20 UTC
Sometime in the for-loop, the geckodriver and firefox process sleep forever.

## System

* Version: 0.26.0
* Platform: CentOS 7.4
* Firefox: 75
* Selenium: 3.141.0 python3.7.6

## Testcase

```python
import logging
from selenium.webdriver import Firefox
from selenium.webdriver.firefox.options import Options

options = Options()
options.headless = True
service_args = ['--log=trace']

logging.basicConfig(level=logging.DEBUG)

for i in range(30):
    driver = Firefox(options=options, service_args=service_args)
    print('*'*20)
    print(i, driver.service.process.pid)
    driver.quit()
```

## Stacktrace

[clientlog.txt](https://github.com/mozilla/geckodriver/files/4591340/clientlog.txt)

## Trace-level log

[geckodriver.log](https://github.com/mozilla/geckodriver/files/4591331/geckodriver.log)

**Comment by whimboo** [comment] 2020-05-07 12:34
It looks to be a hang in `WebDriver:NewSession`. Does the same happen in non-headless mode for you? Btw I cannot reproduce it on my Mac.

**Comment by pyfreyr** [comment] 2020-05-08 02:00
No hang in non-headless mode, and I found NO hang in ubuntu:20.04 docker image.

**Comment by whimboo** [comment] 2020-05-12 11:27
Ok, would you mind using a debug build of Firefox Nightly for testing that on a broken Linux system? To do that those simple steps are enough:

1. Goto our [CI dashboard](https://treeherder.mozilla.org/#/jobs?repo=mozilla-central&tier=1%2C2%2C3&searchStr=build%2Clinux64%2Cdebug&selectedTaskRun=QfYDOO74SUKKitei90TqFw-0) and click the `job details` pane below
2. Find the target.tar.bz2 archive. Download and extract it
3. Run your script against this Firefox binary with trace logs in geckodriver enabled

**Comment by pyfreyr** [comment] 2020-05-26 01:46
I am sorry that I cannot do step 1 and 2 correctly, can you help me for more details?

**Comment by whimboo** [comment] 2020-05-26 11:24
The debug build you can download from https://firefox-ci-tc.services.mozilla.com/api/queue/v1/task/WHwMwn8mQACnAt13Ck4oOQ/runs/0/artifacts/public/build/target.tar.bz2.

**Comment by whimboo** [comment] 2020-09-28 10:31
@pyfreyr any update from your side? Does it work meanwhile? When you test make sure to check with the most recent versions of geckodriver and Firefox. Thanks.

**Comment by pyfreyr** [comment] 2020-09-28 11:06
Very thanks for your help, but now I change a job and develop on mac. I have no win10 in hand to deal with it again.

**Comment by whimboo** [comment] 2020-09-28 14:40
Ok, thanks. Given that we don't have a chance to reproduce I'm going to close this issue.

**Closed by whimboo** 2020-09-28 14:40 UTC
Labels: awaiting reporter feedback
