### ISSUE TITLE
Permission denied to access property "apply" - using JavascriptExecutor.executeAsyncScript of MarionetteDriver (v0.9.0) with Firefox 48+

### ISSUE THREAD

**Issue by mgavilan** [mozilla/geckodriver#147] opened 2016-07-15 14:32 UTC
Dear Mozilla Geckodriver team,

I have recently already faced a similar issue by using JavascriptExecutor.executeScript(), which also lead to "Permission Denied to access property" error. Finally I found out, the issue [had been reported already](https://bugzilla.mozilla.org/show_bug.cgi?id=1123506) and in the meantime is fixed for Firefox 48+, which I was able to verify successfully.

Now that this is working, I'm facing the same symptoms resulting in "Permissions Denied to access property" when executing asynchronous script using JavascriptExecutor.executeAsyncScript(). Unfortunately I was not yet able to reduce this issue to a simplified example, which I could share and the scenario which is failing is behind a firewall, so I cannot provide direct access to our code.

What I can say, is we are using promises as part of the asynchronous callback, maybe this helps. Also the very same code is running successful, when using FirefoxDriver in Firefox 47-. That's why I think it must be somehow related to the new MarionetteDriver.

The above mentioned issue also contains lots of information related to the fix that had been provided for executeScript() method.

Would you please check, whether a similar fix also needs to be applied to executeAsyncScript() method?

Thanks and regards
mgavilan

**Comment by jgraham** [comment] 2016-07-21 17:48
A reduced testcase would be really useful in understanding this problem. If you have any luck producing one, please add it :)

**Comment by mgavilan** [comment] 2016-07-22 14:48
Dear jgraham,

finally I was able to create a short selenium script reproducing the reported issue with Firefox > 47 and MarionetteDriver. For details have a look into the attached file.

Here some more background about my assumptions:

1. The script is designed to run either with Firefox <=47 (using FirefoxDriver) or Firefox >47 (using MarionetteDriver)

1. The script assumes that the wires.exe is located in a known folder to PATH environment variable

1. The script provides a way to switch easily between standard Firefox and Beta Firefox by commenting/uncommenting the corresponding lines 20 and 21.

1. The script accesses a freely available testsuite of OPENUI5 framework and tries to find a certain test using executeAsyncScript() method.

While this is working fine with FirefoxDriver, it leads to a "Permissions Denied to access" issue, when using Firefox > 47 (actually I use Firefox 48.0b09) with wires.exe (v0.9.0).

I hope you are also able to run and reproduce the same issue from your end, so it helps you to verify the root cause of the issue.

Best regards
mgavilan

[Example_to_reproduce.txt](https://github.com/mozilla/geckodriver/files/378436/Example_to_reproduce.txt)

**Comment by andreastt** [comment] 2016-07-22 16:00
The following should be able to reproduce the issue, but I have not run the code:

```py
driver.get("data:text/html;charset=utf-8,%3Cscript%3Ewindow.foo %3D 42%3C%2Fscript%3E")
assert driver.execute_script("return window.foo") == 42
assert driver.execute_async_script("arguments[0](window.foo)") == 42
```

**Comment by vladikoff** [comment] 2016-08-03 16:08
Also getting this permissions errors: 

```
org.openqa.selenium.WebDriverException: Permission denied to access property "__raven_wrapper__" (WARNING: The server did not provide any stacktrace information)
```

**Comment by vladikoff** [comment] 2016-08-03 16:09
More stack:

```
× firefox on any platform - complete_sign_up with expired link and click resend - open expired email verification link (1.487s)
JavaScriptError: [POST http://localhost:4444/wd/hub/session/5d5e3ece-e59e-4c72-998b-a7f4283dbe17/execute / {"script":"return arguments[0].getAttribute(arguments[1]);","args":[{"ELEMENT":"30"},"type"]}] Permission denied to access property "__raven_wrapper__" (WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 9 milliseconds
Build info: version: '3.0.0-beta2', revision: '2aa21c1', time: '2016-08-02 15:03:28 -0700'
System info: host: 'vladikoff-2', ip: '192.168.1.174', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.11.6', java.version: '1.8.0_92'
Driver info: org.openqa.selenium.firefox.FirefoxDriver
Capabilities [{rotatable=false, raisesAccessibilityExceptions=false, appBuildId=20160726073904, version=48.0, platform=MAC, proxy={}, command_id=1, specificationLevel=0, acceptSslCerts=false, browserVersion=48.0, platformVersion=15.6.0, name=tests/intern, XULappId={ec8030f7-c20a-464f-9b0e-13a3a9e97384}, browserName=Firefox, takesScreenshot=true, idle-timeout=60, takesElementScreenshot=true, platformName=Darwin, device=desktop, firefox_profile=UEsDBBQACAAIALOAA0kAAAAAAAAAA...}]
Session ID: 17e0952d-6525-f345-8372-7466a166aeae
  at runRequest  <node_modules/intern/node_modules/leadfoot/Session.js:88:40>
  at <node_modules/intern/node_modules/leadfoot/Session.js:109:39>
  at new Promise  <node_modules/intern/node_modules/dojo/Promise.ts:411:3>
  at ProxiedSession._post  <node_modules/intern/node_modules/leadfoot/Session.js:63:10>
  at ProxiedSession.Session.execute  <node_modules/intern/node_modules/leadfoot/Session.js:643:21>
  at Element.getAttribute  <node_modules/intern/node_modules/leadfoot/Element.js:353:23>
  at Command.<anonymous>  <node_modules/intern/node_modules/leadfoot/Command.js:680:19>
  at <node_modules/intern/node_modules/dojo/Promise.ts:393:15>
  at run  <node_modules/intern/node_modules/dojo/Promise.ts:237:7>
  at <node_modules/intern/node_modules/dojo/nextTick.ts:44:3>
  at Command.target.(anonymous function) [as getAttribute]  <node_modules/intern/node_modules/leadfoot/Command.js:674:11>
  at Command.<anonymous>  <tests/functional/lib/helpers.js:1269:12>
  at Command.<anonymous>  <tests/functional/lib/helpers.js:652:51>
  at runCallback  <node_modules/intern/node_modules/leadfoot/Command.js:526:31>
  at Command.<anonymous>  <node_modules/intern/node_modules/leadfoot/Command.js:543:11>
  at <node_modules/intern/node_modules/dojo/Promise.ts:393:15>
  at run  <node_modules/intern/node_modules/dojo/Promise.ts:237:7>
  at <node_modules/intern/node_modules/dojo/nextTick.ts:44:3>
  at nextTickCallbackWith0Args  <node.js:420:9>
  at process._tickCallback  <node.js:349:13>
  at Command.then  <node_modules/intern/node_modules/leadfoot/Command.js:542:10>
  at Object.fillOutSignUp  <tests/functional/lib/helpers.js:650:8>
  at Command.<anonymous>  <tests/functional/complete_sign_up.js:184:36>
  at runCallback  <node_modules/intern/node_modules/leadfoot/Command.js:526:31>
  at Command.<anonymous>  <node_modules/intern/node_modules/leadfoot/Command.js:543:11>
  at <node_modules/intern/node_modules/dojo/Promise.ts:393:15>
  at run  <node_modules/intern/node_modules/dojo/Promise.ts:237:7>
  at <node_modules/intern/node_modules/dojo/nextTick.ts:44:3>
  at nextTickCallbackWith0Args  <node.js:420:9>
  at process._tickCallback  <node.js:349:13>
  at Command.then  <node_modules/intern/node_modules/leadfoot/Command.js:542:10>
  at Test.registerSuite.open expired email verification l
```

**Comment by andreastt** [comment] 2017-01-04 01:46
I believe this is a duplicate of https://github.com/mozilla/geckodriver/issues/389.

**Closed by andreastt** 2017-01-04 01:46 UTC
Labels: marionette
