### ISSUE TITLE
Selenium 3.3 and Gecko 0.15 cant start Firefox

### ISSUE THREAD

**Issue by lvlmd** [mozilla/geckodriver#526] opened 2017-03-10 04:20 UTC
## Firefox Version
52, 53-54-55 (Dev)

## Platform
OSX 10.12.3

## Steps to reproduce -
I want to run the next code:

```
public class TestSelenium3JavaGeckoDriver {

    public static void main(String[] args) {
        System.setProperty("webdriver.gecko.driver", "/Users/lvlmd/SeleniumTestTrainign/geckodriver");
        DesiredCapabilities capabilities = DesiredCapabilities.firefox();
        WebDriver driver = new FirefoxDriver(capabilities);
        driver.get("http://seleniumhq.org");
        driver.quit();
    }
}
```

but i get error:

```
`1489119243350	geckodriver	INFO	Listening on 127.0.0.1:21925
1489119243742	mozprofile::profile	INFO	Using profile path /var/folders/0m/kmxmf5vn1y741ld9wvpgmhvh0000gn/T/rust_mozprofile.KBBWExK89FyK
1489119243743	geckodriver::marionette	INFO	Starting browser /Applications/Firefox.app/Contents/MacOS/firefox-bin with args []
1489119243746	geckodriver::marionette	INFO	Connecting to Marionette on localhost:62038
1489119244617	Marionette	INFO	Listening on port 62038
Mar 09, 2017 11:14:06 PM org.openqa.selenium.remote.ProtocolHandshake createSession
INFO: Detected dialect: W3C
2017-03-09 23:14:06.451 plugin-container[84436:9270374] *** CFMessagePort: bootstrap_register(): failed 1100 (0x44c) 'Permission denied', port = 0x9527, name = 'com.apple.tsm.portname'
See /usr/include/servers/bootstrap_defs.h for the error codes.
2017-03-09 23:14:06.455 plugin-container[84436:9270374] *** CFMessagePort: bootstrap_register(): failed 1100 (0x44c) 'Permission denied', port = 0x9803, name = 'com.apple.CFPasteboardClient'
See /usr/include/servers/bootstrap_defs.h for the error codes.
1489119247553	Marionette	INFO	New connections will no longer be accepted
[GFX1]: [Tiling:Client] Failed to allocate a TextureClient
** Unknown exception behavior: -2147483647
```

**Comment by linkinek** [comment] 2017-03-10 08:13
Use:
Windows 7
Selenium 3.3.0
Firefox 52 (x64)

Error:
`org.openqa.selenium.SessionNotCreatedException: Unable to create new remote session. desired capabilities = Capabilities [{marionette=true, browserName=firefox, moz:firefoxOptions=org.openqa.selenium.firefox.FirefoxOptions@6470ab8b, version=, platform=ANY, firefox_profile=org.openqa.selenium.firefox.FirefoxProfile@21723961, unexpectedAlertBehaviour=ignore}], required capabilities = Capabilities [{}]
Build info: version: '3.2.0', revision: '8c03df6', time: '2017-03-02 09:34:51 -0800'
System info: host: 'WSM3-750', ip: '10.246.10.62', os.name: 'Windows 7', os.arch: 'amd64', os.version: '6.1', java.version: '1.8.0_121'
Driver info: driver.version: FirefoxDriver
Command duration or timeout: 4.74 seconds

	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.openqa.selenium.remote.ErrorHandler.createThrowable(ErrorHandler.java:216)
	at org.openqa.selenium.remote.ErrorHandler.throwIfResponseFailed(ErrorHandler.java:168)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:638)
	at org.openqa.selenium.remote.RemoteWebDriver.startSession(RemoteWebDriver.java:244)
	at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:131)`

**Comment by leventgo** [comment] 2017-03-11 20:33
I'm getting the same error

**Comment by AutomatedTester** [comment] 2017-03-15 17:25
This was fixed in Selenium 3.3.1

**Closed by AutomatedTester** 2017-03-15 17:25 UTC

**Comment by lvlmd** [comment] 2017-03-15 17:41
i think this issue did't fix.
See log:

`/Library/Java/JavaVirtualMachines/jdk1.8.0_31.jdk/Contents/Home/bin/java -Didea.launcher.port=7533 "-Didea.launcher.bin.path=/Applications/IntelliJ IDEA CE.app/Contents/bin" -Dfile.encoding=UTF-8 -classpath "/Library/Java/JavaVirtualMachines/jdk1.8.0_31.jdk/Contents/Home/jre/lib/charsets.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_31.jdk/Contents/Home/jre/lib/deploy.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_31.jdk/Contents/Home/jre/lib/ext/cldrdata.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_31.jdk/Contents/Home/jre/lib/ext/dnsns.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_31.jdk/Contents/Home/jre/lib/ext/jfxrt.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_31.jdk/Contents/Home/jre/lib/ext/localedata.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_31.jdk/Contents/Home/jre/lib/ext/nashorn.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_31.jdk/Contents/Home/jre/lib/ext/sunec.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_31.jdk/Contents/Home/jre/lib/ext/sunjce_provider.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_31.jdk/Contents/Home/jre/lib/ext/sunpkcs11.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_31.jdk/Contents/Home/jre/lib/ext/zipfs.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_31.jdk/Contents/Home/jre/lib/javaws.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_31.jdk/Contents/Home/jre/lib/jce.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_31.jdk/Contents/Home/jre/lib/jfr.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_31.jdk/Contents/Home/jre/lib/jfxswt.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_31.jdk/Contents/Home/jre/lib/jsse.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_31.jdk/Contents/Home/jre/lib/management-agent.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_31.jdk/Contents/Home/jre/lib/plugin.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_31.jdk/Contents/Home/jre/lib/resources.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_31.jdk/Contents/Home/jre/lib/rt.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_31.jdk/Contents/Home/lib/ant-javafx.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_31.jdk/Contents/Home/lib/dt.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_31.jdk/Contents/Home/lib/javafx-mx.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_31.jdk/Contents/Home/lib/jconsole.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_31.jdk/Contents/Home/lib/sa-jdi.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_31.jdk/Contents/Home/lib/tools.jar:/Users/lvlmd/SeleniumTestTrainign/Selenium3JavaGeckoDriver/target/test-classes:/Users/lvlmd/.m2/repository/org/seleniumhq/selenium/selenium-java/3.3.1/selenium-java-3.3.1.jar:/Users/lvlmd/.m2/repository/org/seleniumhq/selenium/selenium-chrome-driver/3.3.1/selenium-chrome-driver-3.3.1.jar:/Users/lvlmd/.m2/repository/org/seleniumhq/selenium/selenium-remote-driver/3.3.1/selenium-remote-driver-3.3.1.jar:/Users/lvlmd/.m2/repository/org/seleniumhq/selenium/selenium-api/3.3.1/selenium-api-3.3.1.jar:/Users/lvlmd/.m2/repository/cglib/cglib-nodep/3.2.4/cglib-nodep-3.2.4.jar:/Users/lvlmd/.m2/repository/org/apache/commons/commons-exec/1.3/commons-exec-1.3.jar:/Users/lvlmd/.m2/repository/com/google/code/gson/gson/2.8.0/gson-2.8.0.jar:/Users/lvlmd/.m2/repository/com/google/guava/guava/21.0/guava-21.0.jar:/Users/lvlmd/.m2/repository/org/apache/httpcomponents/httpclient/4.5.2/httpclient-4.5.2.jar:/Users/lvlmd/.m2/repository/org/apache/httpcomponents/httpcore/4.4.4/httpcore-4.4.4.jar:/Users/lvlmd/.m2/repository/net/java/dev/jna/jna-platform/4.1.0/jna-platform-4.1.0.jar:/Users/lvlmd/.m2/repository/net/java/dev/jna/jna/4.1.0/jna-4.1.0.jar:/Users/lvlmd/.m2/repository/org/seleniumhq/selenium/selenium-edge-driver/3.3.1/selenium-edge-driver-3.3.1.jar:/Users/lvlmd/.m2/repository/org/seleniumhq/selenium/selenium-firefox-driver/3.3.1/selenium-firefox-driver-3.3.1.jar:/Users/lvlmd/.m2/repository/org/seleniumhq/selenium/selenium-ie-driver/3.3.1/selenium-ie-driver-3.3.1.jar:/Users/lvlmd/.m2/repository/org/seleniumhq/selenium/selenium-opera-driver/3.3.1/selenium-opera-driver-3.3.1.jar:/Users/lvlmd/.m2/repository/org/seleniumhq/selenium/selenium-safari-driver/3.3.1/selenium-safari-driver-3.3.1.jar:/Users/lvlmd/.m2/repository/com/codeborne/phantomjsdriver/1.4.0/phantomjsdriver-1.4.0.jar:/Users/lvlmd/.m2/repository/org/seleniumhq/selenium/htmlunit-driver/2.24/htmlunit-driver-2.24.jar:/Users/lvlmd/.m2/repository/org/seleniumhq/selenium/selenium-support/3.3.1/selenium-support-3.3.1.jar:/Users/lvlmd/.m2/repository/org/hamcrest/hamcrest-library/1.3/hamcrest-library-1.3.jar:/Users/lvlmd/.m2/repository/net/sourceforge/htmlunit/htmlunit/2.24/htmlunit-2.24.jar:/Users/lvlmd/.m2/repository/xalan/xalan/2.7.2/xalan-2.7.2.jar:/Users/lvlmd/.m2/repository/xalan/serializer/2.7.2/serializer-2.7.2.jar:/Users/lvlmd/.m2/repository/org/apache/commons/commons-lang3/3.5/commons-lang3-3.5.jar:/Users/lvlmd/.m2/repository/org/apache/httpcomponents/httpmime/4.5.2/httpmime-4.5.2.jar:/Users/lvlmd/.m2/repository/commons-codec/commons-codec/1.10/commons-codec-1.10.jar:/Users/lvlmd/.m2/repository/net/sourceforge/htmlunit/htmlunit-core-js/2.23/htmlunit-core-js-2.23.jar:/Users/lvlmd/.m2/repository/net/sourceforge/htmlunit/neko-htmlunit/2.24/neko-htmlunit-2.24.jar:/Users/lvlmd/.m2/repository/xerces/xercesImpl/2.11.0/xercesImpl-2.11.0.jar:/Users/lvlmd/.m2/repository/xml-apis/xml-apis/1.4.01/xml-apis-1.4.01.jar:/Users/lvlmd/.m2/repository/net/sourceforge/cssparser/cssparser/0.9.21/cssparser-0.9.21.jar:/Users/lvlmd/.m2/repository/org/w3c/css/sac/1.3/sac-1.3.jar:/Users/lvlmd/.m2/repository/commons-io/commons-io/2.5/commons-io-2.5.jar:/Users/lvlmd/.m2/repository/commons-logging/commons-logging/1.2/commons-logging-1.2.jar:/Users/lvlmd/.m2/repository/org/eclipse/jetty/websocket/websocket-client/9.2.20.v20161216/websocket-client-9.2.20.v20161216.jar:/Users/lvlmd/.m2/repository/org/eclipse/jetty/jetty-util/9.2.20.v20161216/jetty-util-9.2.20.v20161216.jar:/Users/lvlmd/.m2/repository/org/eclipse/jetty/jetty-io/9.2.20.v20161216/jetty-io-9.2.20.v20161216.jar:/Users/lvlmd/.m2/repository/org/eclipse/jetty/websocket/websocket-common/9.2.20.v20161216/websocket-common-9.2.20.v20161216.jar:/Users/lvlmd/.m2/repository/org/eclipse/jetty/websocket/websocket-api/9.2.20.v20161216/websocket-api-9.2.20.v20161216.jar:/Users/lvlmd/.m2/repository/org/testng/testng/6.8/testng-6.8.jar:/Users/lvlmd/.m2/repository/junit/junit/4.10/junit-4.10.jar:/Users/lvlmd/.m2/repository/org/hamcrest/hamcrest-core/1.1/hamcrest-core-1.1.jar:/Users/lvlmd/.m2/repository/org/beanshell/bsh/2.0b4/bsh-2.0b4.jar:/Users/lvlmd/.m2/repository/com/beust/jcommander/1.27/jcommander-1.27.jar:/Users/lvlmd/.m2/repository/org/yaml/snakeyaml/1.6/snakeyaml-1.6.jar:/Applications/IntelliJ IDEA CE.app/Contents/lib/idea_rt.jar" com.intellij.rt.execution.application.AppMain TestSelenium3JavaGeckoDriver
1489599669136	geckodriver	INFO	Listening on 127.0.0.1:12920
1489599669485	mozprofile::profile	INFO	Using profile path /var/folders/0m/kmxmf5vn1y741ld9wvpgmhvh0000gn/T/rust_mozprofile.yHOzBB4sdPEN
1489599669486	geckodriver::marionette	INFO	Starting browser /Applications/Firefox.app/Contents/MacOS/firefox-bin with args []
1489599669508	geckodriver::marionette	INFO	Connecting to Marionette on localhost:51365
1489599671817	Marionette	INFO	Listening on port 51365
Mar 15, 2017 1:41:12 PM org.openqa.selenium.remote.ProtocolHandshake createSession
INFO: Detected dialect: W3C
2017-03-15 13:41:12.293 plugin-container[67734:7956054] *** CFMessagePort: bootstrap_register(): failed 1100 (0x44c) 'Permission denied', port = 0x983b, name = 'com.apple.tsm.portname'
See /usr/include/servers/bootstrap_defs.h for the error codes.
2017-03-15 13:41:12.294 plugin-container[67734:7956054] *** CFMessagePort: bootstrap_register(): failed 1100 (0x44c) 'Permission denied', port = 0x9b03, name = 'com.apple.CFPasteboardClient'
See /usr/include/servers/bootstrap_defs.h for the error codes.
1489599673245	Marionette	INFO	New connections will no longer be accepted
** Unknown exception behavior: -2147483647

Process finished with exit code 0`

**Comment by AutomatedTester** [comment] 2017-03-15 17:54
I can't seem to reproduce this error. Could you help narrow it down further for us.

**Comment by lvlmd** [comment] 2017-03-15 17:56
How can i help ? which logs can i share?

**Comment by lvlmd** [comment] 2017-03-15 17:59
i use maven.
this is my pom file 
```
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>WebDriverBasics</groupId>
    <artifactId>WebDriverBasics</artifactId>
    <packaging>pom</packaging>
    <version>1.0-SNAPSHOT</version>
    <dependencies>
        <dependency>
            <groupId>org.seleniumhq.selenium</groupId>
            <artifactId>selenium-java</artifactId>
            <version>3.3.1</version>
        </dependency>
        <dependency>
            <groupId>org.testng</groupId>
            <artifactId>testng</artifactId>
            <version>6.8</version>
            <scope>test</scope>
        </dependency>
    </dependencies>
```

**Comment by lvlmd** [comment] 2017-03-15 18:00
i reintalled FF 52

```
/Library/Java/JavaVirtualMachines/jdk1.8.0_31.jdk/Contents/Home/bin/java -Didea.launcher.port=7534 "-Didea.launcher.bin.path=/Applications/IntelliJ IDEA CE.app/Contents/bin" -Dfile.encoding=UTF-8 -classpath "/Library/Java/JavaVirtualMachines/jdk1.8.0_31.jdk/Contents/Home/jre/lib/charsets.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_31.jdk/Contents/Home/jre/lib/deploy.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_31.jdk/Contents/Home/jre/lib/ext/cldrdata.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_31.jdk/Contents/Home/jre/lib/ext/dnsns.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_31.jdk/Contents/Home/jre/lib/ext/jfxrt.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_31.jdk/Contents/Home/jre/lib/ext/localedata.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_31.jdk/Contents/Home/jre/lib/ext/nashorn.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_31.jdk/Contents/Home/jre/lib/ext/sunec.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_31.jdk/Contents/Home/jre/lib/ext/sunjce_provider.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_31.jdk/Contents/Home/jre/lib/ext/sunpkcs11.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_31.jdk/Contents/Home/jre/lib/ext/zipfs.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_31.jdk/Contents/Home/jre/lib/javaws.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_31.jdk/Contents/Home/jre/lib/jce.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_31.jdk/Contents/Home/jre/lib/jfr.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_31.jdk/Contents/Home/jre/lib/jfxswt.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_31.jdk/Contents/Home/jre/lib/jsse.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_31.jdk/Contents/Home/jre/lib/management-agent.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_31.jdk/Contents/Home/jre/lib/plugin.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_31.jdk/Contents/Home/jre/lib/resources.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_31.jdk/Contents/Home/jre/lib/rt.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_31.jdk/Contents/Home/lib/ant-javafx.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_31.jdk/Contents/Home/lib/dt.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_31.jdk/Contents/Home/lib/javafx-mx.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_31.jdk/Contents/Home/lib/jconsole.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_31.jdk/Contents/Home/lib/sa-jdi.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_31.jdk/Contents/Home/lib/tools.jar:/Users/lvlmd/SeleniumTestTrainign/Selenium3JavaGeckoDriver/target/test-classes:/Users/lvlmd/.m2/repository/org/seleniumhq/selenium/selenium-java/3.3.1/selenium-java-3.3.1.jar:/Users/lvlmd/.m2/repository/org/seleniumhq/selenium/selenium-chrome-driver/3.3.1/selenium-chrome-driver-3.3.1.jar:/Users/lvlmd/.m2/repository/org/seleniumhq/selenium/selenium-remote-driver/3.3.1/selenium-remote-driver-3.3.1.jar:/Users/lvlmd/.m2/repository/org/seleniumhq/selenium/selenium-api/3.3.1/selenium-api-3.3.1.jar:/Users/lvlmd/.m2/repository/cglib/cglib-nodep/3.2.4/cglib-nodep-3.2.4.jar:/Users/lvlmd/.m2/repository/org/apache/commons/commons-exec/1.3/commons-exec-1.3.jar:/Users/lvlmd/.m2/repository/com/google/code/gson/gson/2.8.0/gson-2.8.0.jar:/Users/lvlmd/.m2/repository/com/google/guava/guava/21.0/guava-21.0.jar:/Users/lvlmd/.m2/repository/org/apache/httpcomponents/httpclient/4.5.2/httpclient-4.5.2.jar:/Users/lvlmd/.m2/repository/org/apache/httpcomponents/httpcore/4.4.4/httpcore-4.4.4.jar:/Users/lvlmd/.m2/repository/net/java/dev/jna/jna-platform/4.1.0/jna-platform-4.1.0.jar:/Users/lvlmd/.m2/repository/net/java/dev/jna/jna/4.1.0/jna-4.1.0.jar:/Users/lvlmd/.m2/repository/org/seleniumhq/selenium/selenium-edge-driver/3.3.1/selenium-edge-driver-3.3.1.jar:/Users/lvlmd/.m2/repository/org/seleniumhq/selenium/selenium-firefox-driver/3.3.1/selenium-firefox-driver-3.3.1.jar:/Users/lvlmd/.m2/repository/org/seleniumhq/selenium/selenium-ie-driver/3.3.1/selenium-ie-driver-3.3.1.jar:/Users/lvlmd/.m2/repository/org/seleniumhq/selenium/selenium-opera-driver/3.3.1/selenium-opera-driver-3.3.1.jar:/Users/lvlmd/.m2/repository/org/seleniumhq/selenium/selenium-safari-driver/3.3.1/selenium-safari-driver-3.3.1.jar:/Users/lvlmd/.m2/repository/com/codeborne/phantomjsdriver/1.4.0/phantomjsdriver-1.4.0.jar:/Users/lvlmd/.m2/repository/org/seleniumhq/selenium/htmlunit-driver/2.24/htmlunit-driver-2.24.jar:/Users/lvlmd/.m2/repository/org/seleniumhq/selenium/selenium-support/3.3.1/selenium-support-3.3.1.jar:/Users/lvlmd/.m2/repository/org/hamcrest/hamcrest-library/1.3/hamcrest-library-1.3.jar:/Users/lvlmd/.m2/repository/net/sourceforge/htmlunit/htmlunit/2.24/htmlunit-2.24.jar:/Users/lvlmd/.m2/repository/xalan/xalan/2.7.2/xalan-2.7.2.jar:/Users/lvlmd/.m2/repository/xalan/serializer/2.7.2/serializer-2.7.2.jar:/Users/lvlmd/.m2/repository/org/apache/commons/commons-lang3/3.5/commons-lang3-3.5.jar:/Users/lvlmd/.m2/repository/org/apache/httpcomponents/httpmime/4.5.2/httpmime-4.5.2.jar:/Users/lvlmd/.m2/repository/commons-codec/commons-codec/1.10/commons-codec-1.10.jar:/Users/lvlmd/.m2/repository/net/sourceforge/htmlunit/htmlunit-core-js/2.23/htmlunit-core-js-2.23.jar:/Users/lvlmd/.m2/repository/net/sourceforge/htmlunit/neko-htmlunit/2.24/neko-htmlunit-2.24.jar:/Users/lvlmd/.m2/repository/xerces/xercesImpl/2.11.0/xercesImpl-2.11.0.jar:/Users/lvlmd/.m2/repository/xml-apis/xml-apis/1.4.01/xml-apis-1.4.01.jar:/Users/lvlmd/.m2/repository/net/sourceforge/cssparser/cssparser/0.9.21/cssparser-0.9.21.jar:/Users/lvlmd/.m2/repository/org/w3c/css/sac/1.3/sac-1.3.jar:/Users/lvlmd/.m2/repository/commons-io/commons-io/2.5/commons-io-2.5.jar:/Users/lvlmd/.m2/repository/commons-logging/commons-logging/1.2/commons-logging-1.2.jar:/Users/lvlmd/.m2/repository/org/eclipse/jetty/websocket/websocket-client/9.2.20.v20161216/websocket-client-9.2.20.v20161216.jar:/Users/lvlmd/.m2/repository/org/eclipse/jetty/jetty-util/9.2.20.v20161216/jetty-util-9.2.20.v20161216.jar:/Users/lvlmd/.m2/repository/org/eclipse/jetty/jetty-io/9.2.20.v20161216/jetty-io-9.2.20.v20161216.jar:/Users/lvlmd/.m2/repository/org/eclipse/jetty/websocket/websocket-common/9.2.20.v20161216/websocket-common-9.2.20.v20161216.jar:/Users/lvlmd/.m2/repository/org/eclipse/jetty/websocket/websocket-api/9.2.20.v20161216/websocket-api-9.2.20.v20161216.jar:/Users/lvlmd/.m2/repository/org/testng/testng/6.8/testng-6.8.jar:/Users/lvlmd/.m2/repository/junit/junit/4.10/junit-4.10.jar:/Users/lvlmd/.m2/repository/org/hamcrest/hamcrest-core/1.1/hamcrest-core-1.1.jar:/Users/lvlmd/.m2/repository/org/beanshell/bsh/2.0b4/bsh-2.0b4.jar:/Users/lvlmd/.m2/repository/com/beust/jcommander/1.27/jcommander-1.27.jar:/Users/lvlmd/.m2/repository/org/yaml/snakeyaml/1.6/snakeyaml-1.6.jar:/Applications/IntelliJ IDEA CE.app/Contents/lib/idea_rt.jar" com.intellij.rt.execution.application.AppMain TestSelenium3JavaGeckoDriver
1489600811293	geckodriver	INFO	Listening on 127.0.0.1:46606
1489600811677	mozprofile::profile	INFO	Using profile path /var/folders/0m/kmxmf5vn1y741ld9wvpgmhvh0000gn/T/rust_mozprofile.mZKv82Y1yZGO
1489600811679	geckodriver::marionette	INFO	Starting browser /Applications/Firefox.app/Contents/MacOS/firefox-bin with args []
1489600811703	geckodriver::marionette	INFO	Connecting to Marionette on localhost:52350
1489600812606	Marionette	INFO	Listening on port 52350
Mar 15, 2017 2:00:14 PM org.openqa.selenium.remote.ProtocolHandshake createSession
INFO: Detected dialect: W3C
2017-03-15 14:00:14.331 plugin-container[68164:8076083] *** CFMessagePort: bootstrap_register(): failed 1100 (0x44c) 'Permission denied', port = 0x933b, name = 'com.apple.tsm.portname'
See /usr/include/servers/bootstrap_defs.h for the error codes.
2017-03-15 14:00:14.334 plugin-container[68164:8076083] *** CFMessagePort: bootstrap_register(): failed 1100 (0x44c) 'Permission denied', port = 0x9603, name = 'com.apple.CFPasteboardClient'
See /usr/include/servers/bootstrap_defs.h for the error codes.
1489600815584	Marionette	INFO	New connections will no longer be accepted
[Child 68164] ###!!! ABORT: Aborting on channel error.: file /builds/slave/m-rel-m64-00000000000000000000/build/src/ipc/glue/MessageChannel.cpp, line 2143
[Child 68164] ###!!! ABORT: Aborting on channel error.: file /builds/slave/m-rel-m64-00000000000000000000/build/src/ipc/glue/MessageChannel.cpp, line 2143
```

**Comment by AutomatedTester** [comment] 2017-03-15 18:36
As was requested in issue template, we will need a verbose geckodriver log. Each client does this different so check their API docs on how to do it.

**Comment by lvlmd** [comment] 2017-03-15 18:51
you mean, i need find Gecko driver log? how to find it?

**Comment by martijnhjk** [comment] 2017-03-16 13:25
I seem to get the exact same error:

plugin-container[68164:8076083] *** CFMessagePort: bootstrap_register(): failed 1100 (0x44c) 'Permission denied', port = 0x9603, name = 'com.apple.CFPasteboardClient'
See /usr/include/servers/bootstrap_defs.h for the error codes.

When I run this with the integrated runner in Eclipse, the result of my test is still a pass. However, if I use ant to run it from command line the ant build outputs a FAIL.

Both methods print the permission denied error in the console logs.

**Comment by martijnhjk** [comment] 2017-03-16 13:45
@AutomatedTester @lvlmd OK I am getting the error above possibly because of using depricated fluent wait, multiple threads on this e.g. https://groups.google.com/forum/#!msg/selenium-users/3DtgzhmBqCA/IpD-1xW1AgAJ

**Comment by MiteshTambi** [comment] 2017-03-20 11:35
The issue is still not resolved. I am using geckodriver v0.15.0
My POM 
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>
  <groupId>com.mitesh</groupId>
  <artifactId>selenium3Test</artifactId>
  <version>0.0.1-SNAPSHOT</version>
  
  <dependencies>
  		<dependency>
            <groupId>org.seleniumhq.selenium</groupId>
            <artifactId>selenium-java</artifactId>
            <version>3.3.1</version>
        </dependency>
  </dependencies>
</project>

I am getting following error" :
Mar 20, 2017 4:51:46 PM org.openqa.selenium.remote.ProtocolHandshake createSession
INFO: Detected dialect: W3C
2017-03-20 16:51:46.494 plugin-container[12889:554838] *** CFMessagePort: bootstrap_register(): failed 1100 (0x44c) 'Permission denied', port = 0x983b, name = 'com.apple.tsm.portname'
See /usr/include/servers/bootstrap_defs.h for the error codes.
2017-03-20 16:51:46.494 plugin-container[12889:554838] *** CFMessagePort: bootstrap_register(): failed 1100 (0x44c) 'Permission denied', port = 0x9b03, name = 'com.apple.CFPasteboardClient'
See /usr/include/servers/bootstrap_defs.h for the error codes.

**Comment by MiteshTambi** [comment] 2017-03-20 11:37
And My test code is:
package selenium3Test;

import org.junit.Test;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.firefox.FirefoxOptions;
import org.openqa.selenium.firefox.FirefoxProfile;
import org.openqa.selenium.remote.DesiredCapabilities;

public class AppTest {
	String driverPath = "/Users/sprinklr/Downloads/";
	public WebDriver driver;
	
	@Test
	public void launchBrowser() {
		System.out.println("launching firefox browser"); 
		System.setProperty("webdriver.gecko.driver", driverPath+"geckodriver");
		DesiredCapabilities caps = new FirefoxOptions()
			       // For example purposes only
			      .setProfile(new FirefoxProfile())
			      .addTo(DesiredCapabilities.firefox());
	    WebDriver driver = new FirefoxDriver(caps);
		//driver = new FirefoxDriver();
		if(driver!=null)
			driver.navigate().to("http://www.facebook.com");
		if(driver!=null) {
			driver.close();
		}
	}

}

**Comment by enver-haase** [comment] 2017-03-21 20:48
Bitten by the same problem. Didn't use the infrastructure for quite some time, so cannot help with when the problem started I am afraid.

**Comment by andreastt** [comment] 2017-03-23 07:40
Locking this issue as “me too” comments are completely useless to us trying to reproduce the problem. Please do us the decency of not wasting our time, but instead help us help you by providing reproducible issue reports with trace-level logs. The information on how to crank up the logging level is provided in the README.
