### ISSUE TITLE
Unable to close browser using Gecko driver 0.16 

### ISSUE THREAD

**Issue by snpanigrahi9** [mozilla/geckodriver#672] opened 2017-04-22 04:30 UTC
In order to help us efficiently investigate your issue, please provide the following information:

firefox 54.0b1

## Platform
Windows 10

##Selenium version

Selenium-java-3.4.0

## Steps to reproduce -

Use below code

package sel;

import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.firefox.FirefoxOptions;
import org.openqa.selenium.firefox.FirefoxProfile;
import org.openqa.selenium.remote.DesiredCapabilities;

public class Close {

	public static void main(String[] args) {
		// TODO Auto-generated method stub
		DesiredCapabilities caps = new FirefoxOptions()
			       // For example purposes only
			      .setProfile(new FirefoxProfile())
			      .addTo(DesiredCapabilities.firefox());
		      caps.setCapability("acceptInsecureCerts", true);
		      caps.setCapability("marionette", true);
		      String path = System.getProperty("user.dir");
		      String DriverPath = path+"//geckodriver.exe";
		      System.setProperty("webdriver.gecko.driver", DriverPath );
			  WebDriver driver = new FirefoxDriver(caps);
			  driver.get("https://www.healthkart.com/");
			  driver.close();
			  
			  
			  
			  
	}

}

Find below logs for above code..

```
1492835029039	geckodriver	INFO	Listening on 127.0.0.1:22195
1492835029712	geckodriver::marionette	INFO	Starting browser \\?\C:\Program Files (x86)\Mozilla Firefox\firefox.exe with args ["-marionette"]
1492835031527	addons.manager	DEBUG	Application has been upgraded
1492835031528	addons.manager	ERROR	startup failed: [Exception... "Component returned failure code: 0x80070057 (NS_ERROR_ILLEGAL_VALUE) [nsIFile.create]"  nsresult: "0x80070057 (NS_ERROR_ILLEGAL_VALUE)"  location: "JS frame :: resource://gre/modules/FileUtils.jsm :: FileUtils_getDir :: line 70"  data: no] Stack trace: FileUtils_getDir()@resource://gre/modules/FileUtils.jsm:70 < FileUtils_getFile()@resource://gre/modules/FileUtils.jsm:42 < validateBlocklist()@resource://gre/modules/AddonManager.jsm:674 < startup()@resource://gre/modules/AddonManager.jsm:837 < startup()@resource://gre/modules/AddonManager.jsm:3145 < observe()@resource://gre/components/addonManager.js:65
1492835031530	addons.manager	DEBUG	Completed startup sequence
JavaScript error: resource://gre/modules/AddonManager.jsm, line 1657: NS_ERROR_NOT_INITIALIZED: AddonManager is not initialized
*** Blocklist::_preloadBlocklistFile: blocklist is disabled
1492835036455	Marionette	INFO	Listening on port 51604
JavaScript error: resource://gre/modules/AddonManager.jsm, line 2572: NS_ERROR_NOT_INITIALIZED: AddonManager is not initialized
1492835036523	Marionette	WARN	TLS certificate errors will be ignored for this session
Apr 22, 2017 9:53:56 AM org.openqa.selenium.remote.ProtocolHandshake createSession
INFO: Detected dialect: W3C
```

**Comment by andreastt** [comment] 2017-04-22 11:50
I suspect this is a duplicate of https://github.com/mozilla/geckodriver/issues/672. Let’s continue the discussion there.

**Closed by andreastt** 2017-04-22 11:50 UTC

**Comment by govindchakri** [comment] 2017-05-01 14:18
I too getting the same problem....

please look at below code........

import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;

public class sample {

	public static void main(String[] args) throws InterruptedException {
		// TODO Auto-generated method stub
		System.setProperty("webdriver.gecko.driver", "C:\\Users\\govin_000\\Downloads\\geckodriver-v0.16.0-win64\\geckodriver.exe");
		WebDriver driver=new FirefoxDriver();
		Thread.sleep(20000);
		driver.get("https://www.tutorialspoint.com");
		driver.close();
	}

}

**Comment by NicoHaase** [comment] 2017-05-02 12:49
@andreastt how can this be a duplicate of itself?

**Comment by straris** [comment] 2017-05-03 08:09
Can we please re-open this?

**Comment by StephenCavender** [comment] 2017-05-03 12:32
I think @andreastt meant this is a duplicate of #613

**Comment by andreastt** [comment] 2017-05-03 14:02
Sorry, yes, I meant https://github.com/mozilla/geckodriver/issues/613.

**Comment by Shehroyas** [comment] 2017-06-14 06:46
package automationFramework;

import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.firefox.FirefoxOptions;
import org.openqa.selenium.firefox.FirefoxProfile;
import org.openqa.selenium.remote.DesiredCapabilities;

public class FirstTestCase {

public static void main(String[] args) {
	// TODO Auto-generated method stub

	DesiredCapabilities caps = new FirefoxOptions()
		       // For example purposes only
			
		      .setProfile(new FirefoxProfile())
		      .addTo(DesiredCapabilities.firefox());

	      caps.setCapability("acceptInsecureCerts", true);
	      caps.setCapability("marionette", true);
	      String path = System.getProperty("user.dir");
	      
	      String DriverPath = path+"//geckodriver.exe";
	   
		  System.setProperty("webdriver.gecko.driver","D:\\Firefox\\geckodriver.exe");//path set of geco driver
		  WebDriver driver = new FirefoxDriver(caps);

		  driver.get("https://www.healthkart.com/");
		  driver.close();
		  
		  
		  
		  
}


    }

**Comment by andreastt** [comment] 2017-06-14 11:42
@Shehroyas You did not provide an error, a stacktrace, a trace-level log from geckodriver, or information about what versions of the respective software you’re using. Please also don’t comment on closed issues unless they are directly related.
