### ISSUE TITLE
Setting window size to same as current doesn't return

### ISSUE THREAD

**Issue by webtoman** [mozilla/geckodriver#675] opened 2017-04-24 09:48 UTC
When setting the window size to same size as the current size, the call never returns.

selenium 3.4.0 (python and Java server)
geckodriver 0.16
Firefox 53

## Steps to reproduce -

```
driver = webdriver.Firefox()
driver.set_window_size(1366, 768)
drivet.get('http://www.example.org/')
driver.set_window_size(1366, 768)
# Never returns

```

**Comment by andreastt** [comment] 2017-04-24 10:55
Duplicate of https://github.com/mozilla/geckodriver/issues/643. Will be fixed with https://bugzilla.mozilla.org/show_bug.cgi?id=1357878.

**Closed by andreastt** 2017-04-24 10:55 UTC
