### ISSUE TITLE
Unable to close browser window

### ISSUE THREAD

**Issue by snpanigrahi9** [mozilla/geckodriver#503] opened 2017-03-01 05:16 UTC
In order to help us efficiently investigate your issue, please provide the following information:

## Firefox 

52.0b8 32bit

## Platform
Window7 64 bit

Gecko driver ##
0.14

## Steps to reproduce -
package demo1;

import org.openqa.selenium.firefox.FirefoxDriver;

public class Executer2 {

	public static void main(String[] args){
		
		
		System.out.println(System.getProperty("user.dir") + "/geckodriver.exe");
		System.setProperty("webdriver.gecko.driver", System.getProperty("user.dir") + "/geckodriver.exe");
		
		FirefoxDriver wd = new FirefoxDriver();
		
			wd.get("http://www.google.com");
			wd.close();
			
		
	}

}

**Comment by andreastt** [comment] 2017-03-01 09:38
This is a bit surprising, since it should be fixed by https://bugzilla.mozilla.org/show_bug.cgi?id=1311350. Possibly you have a build of Firefox 52 that is just too old for the change to have made it in?

Can you please retry with Firefox Nightly (which you should have done in the first place) and attach a trace-level log (which you were also asked to do when filing an issue)?

**Comment by andreastt** [comment] 2017-03-06 13:29
Closing this since not enough reproducible information has been added. Happy to re-open once it is.

**Closed by andreastt** 2017-03-06 13:29 UTC
Labels: needinfo

**Comment by caifara** [comment] 2017-03-07 10:09
I tried but it didn't help:

* firefox nightly 54a1
* gecko driver 0.14 on mac os 10.11
* reproduced in ruby through capybara with `page.driver.browser.close` (.quit did work however)

**Comment by abhishekjn** [comment] 2017-03-07 10:28
Hey!!
I am also facing the same issue, unable to close firefox browser with close().
Browser: Firefox 55.0a1 32bit
Platform
Window7 64 bit

Gecko driver ## 0.14-64bit

Code: 
System.setProperty("webdriver.gecko.driver", "location of GeckoDriver");
DesiredCapabilities dc=DesiredCapabilities.firefox();
FirefoxProfile profile = new FirefoxProfile();
dc.setCapability(FirefoxDriver.PROFILE, profile);
dc.setCapability("marionette", true);
driver = new firefoxDriver(dc);

driver.close() - Not able to close firefox browser. 
However, browser is getting closed with the help of driver.quit();

**Comment by 123qweas** [comment] 2018-08-13 22:25
After updating to Gekko v0.6.5 I get the same issue.
I can't reload or close any window without that the gekko is cashing.
The error I get ist:
events.js:183
      throw er; // Unhandled 'error' event
      ^

Error: read ECONNRESET
    at _errnoException (util.js:992:11)
    at TCP.onread (net.js:618:25)
Maybe someone can help.
