### ISSUE TITLE
System.InvalidOperationException: TypeError: this.tabModal is null

### ISSUE THREAD

**Issue by kwilson-93** [mozilla/geckodriver#1571] opened 2019-06-07 11:43 UTC
## System

* Version: 0.24.0
* Platform: Win 7
* Firefox: 67.0.1
* Selenium: 3.4.0
* Programming Language: C#

## Issue

We have some automation tests which are failing with Firefox v67+ only (worked in previous versions e.g. v66.0.5).
The issue occurs when we browse to a page that displays a Windows Authentication prompt (_note the issue does not occur if a Windows Authentication prompt is not displayed during the test_).
We enter our credentials and hit enter (_using SendKeys.SendWait()_) which successfully logs in.
But any interaction with the driver object here after results in the following exception being thrown:

System.InvalidOperationException: TypeError: this.tabModal is null

![image](https://user-images.githubusercontent.com/51480361/59101739-de6b2280-8921-11e9-8b5d-42bd8ae6d2fd.png)

**Comment by whimboo** [comment] 2019-06-07 13:41
Could you please attach a [trace-level log] from geckodriver? Read more about reporting actionable bugs in our [contribution guidelines].

[trace-level log]: https://firefox-source-docs.mozilla.org/testing/geckodriver/geckodriver/TraceLogs.html
[contribution guidelines]: https://firefox-source-docs.mozilla.org/testing/geckodriver/geckodriver/Bugs.html

**Comment by kwilson-93** [comment] 2019-06-07 15:33
hi whimboo,

For whatever reason I cannot generate a trace-level log when I follow the instructions you sent.
The stdout is empty.

![image](https://user-images.githubusercontent.com/51480361/59115649-a07df680-8941-11e9-8f11-edd206b1616a.png)

**Comment by whimboo** [comment] 2019-06-07 17:35
Did you only run those lines or your whole test? It shouldn't be empty.

**Comment by kwilson-93** [comment] 2019-06-07 23:50
I ran the whole test till failiure :)
I've repro'd both issues with a simple project.
Open the project, edit URL (_must display the "Authentication Required" prompt when browsed_), Username and Password respectively within TestMethod1, and run the test method.

I've made it available to you (_I hope !!_):
https://github.com/kwilson-93/TestingSolution/invitations

**Comment by whimboo** [comment] 2019-06-11 08:46
If you could open up (means make it public) the simple project, that would be great. Thanks

**Comment by kwilson-93** [comment] 2019-06-11 08:51
@whimboo Done :)

**Comment by xTaZzGithub** [comment] 2019-06-13 09:31
I have the exact same issue. For me it was possible to attach a trace-level log to the geckodriver. The output was: 

`1560416864553   webdriver::server       DEBUG   -> POST /session/c51a3e2c-6880-452c-840f-c7a42dec4abd/execute/sync {"script":"return document.readyState","args":[]}`

`1560416864557   webdriver::server       DEBUG   <- 500 Internal Server Error {"value":{"error":"unknown error","message":"TypeError: this.tabModal is null","stacktrace":"get ui@chrome://marionette/content/modal.js:159:5\nGeckoDriver.prototype._handleUserPrompts@chrome://marionette/content/driver.js:3256:23\nGeckoDriver.prototype.execute_@chrome://marionette/content/driver.js:991:14\nGeckoDriver.prototype.executeScript@chrome://marionette/content/driver.js:911:29\ndespatch@chrome://marionette/content/server.js:289:40\nexecute@chrome://marionette/content/server.js:262:16\nonPacket/<@chrome://marionette/content/server.js:235:20\nonPacket@chrome://marionette/content/server.js:236:9\n_onJSONObjectReady/<@chrome://marionette/content/transport.js:492:20\n"}}`

**Comment by whimboo** [comment] 2019-06-13 11:53
Do you have a screenshot, so that I know which kind of dialog that is? Maybe you also have a minimized testcase which I could use to reproduce myself?

**Comment by kwilson-93** [comment] 2019-06-13 12:22
Thanks @xTaZzGithub !

@whimboo here's the dialog:
![image](https://user-images.githubusercontent.com/51480361/59431979-2684bc00-8dde-11e9-984d-fc5454206938.png)

**Comment by xTaZzGithub** [comment] 2019-06-13 13:21
I'm using this site as a test site : 'https://jigsaw.w3.org/HTTP/Basic/' but it's the same for every other site that request a Basic Authentication. 
The dialog looks as follows:
![Basic_Authentication_Window_Firefox](https://user-images.githubusercontent.com/51782080/59435732-8a16e580-8dee-11e9-9205-a8b230fa06c8.png)

The test case is to open the page, perform the login and then perform any actions with the driver.

**Comment by andreastt** [comment] 2019-06-15 09:29
That is not a Windows authentication prompt, but an HTTP Basic Auth prompt from Firefox. WebDriver doesn’t support basic auth yet (tracked in https://github.com/w3c/webdriver/issues/385), so I don’t understand how this could’ve worked in in Firefox 66.

@kwilson-93 Did something change in your test environment/application?

**Comment by kwilson-93** [comment] 2019-06-15 10:40
hi @andreastt , I've just verified a test with v66.0.5 of Firefox and it is the same prompt shown above that is displayed. The issue **does actually replicate**, apologies but I made a mistake saying this version number. I'm unsure what the last version of Firefox was when the issue did not reproduce with, but it is somewhere between v65 & v66.0.5.

The only difference in the whole scenario is the version of Firefox :) Definitely when using v67+ I can reproduce the issue. Note that we're handling the prompt inputs and confirmation by calling SendKeys.SendWait(), not a WebDriver action.

@xTaZzGithub do you experience the same? What version of Firefox are you using when you cannot reproduce the issue?

**Comment by andreastt** [comment] 2019-06-15 11:42
Without knowing what `SendKeys.SendWait()` does by looking at a trace-level log it’s hard to say anything about what circumstances might have changed (it could be a change in basic auth/site origin behaviour in Firefox, in the Marionette server related to keyboard interaction, or in both).

Since HTTP basic auth is not officially supported by WebDriver, I’m inclined to close this on the grounds that we don’t know what the correct behaviour _should_ be. It’s unfortunate that there has been a regression with geckodriver, but again, without more data it’s near impossible to tell.

**Closed by andreastt** 2019-06-15 11:42 UTC
Labels: waiting for reporter feedback

**Comment by whimboo** [comment] 2019-06-21 14:24
This should have actually been fixed by https://bugzilla.mozilla.org/show_bug.cgi?id=1538782 for Firefox 68 which is currently in beta.

**Comment by kwilson-93** [comment] 2019-07-10 10:08
hi @whimboo @xTaZzGithub, v68 of Firefox has now resolved this issue for me. Thanks for your help !
