### ISSUE TITLE
###!!! ABORT: Aborting on channel when attempting driver.close() action

### ISSUE THREAD

**Issue by jodigithub** [mozilla/geckodriver#434] opened 2017-01-16 14:45 UTC
In order to help us efficiently investigate your issue, please provide the following information:

## Firefox Version
50.1.0

## Platform
Windows 7

## Other installs/configs
java jdk 1.8.0_111
maven 3.3.9
selenium-java 3.0.1
intellij 2016.3.2
gecko driver 0.13.0-win64

## Steps to reproduce -
Please provide a description of how to reproduce the problem, including the following essential elements:

## my simple file(just opens and closes)

package com.joditest.webdriver;

import org.junit.Assert;
import org.junit.Test;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.support.ui.WebDriverWait;

/**
 * Created by jcha on 1/12/2017.
 */
public class MyFirstTest2 {
    @Test
    public void startWebdriver() {
        System.setProperty("webdriver.gecko.driver", "C:\\SeleniumDrivers\\geckodriver.exe");
        //System.setProperty("webdriver.firefox.marionette", "C:\\SeleniumDrivers\\geckodriver.exe");
        System.out.println("BEFORE NEW DRIVER. SETTING SYSTEM PROPERTY");
        System.out.println("STILL BEFORE NEW DRIVER");
        WebDriver driver = new FirefoxDriver();
        //WebDriver driver = new ChromeDriver();
        System.out.println("AFTER NEW DRIVER");
        driver.navigate().to("http://www.seleniumhq.org/download/");
        //driver.get("http://www.seleniumhq.org/download/");
        WebDriverWait wait = new WebDriverWait(driver,12);
        System.out.println("AFTER NAVIGATE TO WEBSITE");
        Assert.assertTrue("title should say download",
                driver.getTitle().startsWith("Downloads"));
        System.out.println("AFTER ASSERT");
        driver.close();
        System.out.println("AFTER CLOSE");
        driver.quit();
        System.out.println("AFTER QUIT");
    }
}

## POM.xml
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>MyFirsttest1</groupId>
    <artifactId>Mytest</artifactId>
    <version>1.0-SNAPSHOT</version>
<dependencies>
    
    <dependency>
        <groupId>org.seleniumhq.selenium</groupId>
        <artifactId>selenium-java</artifactId>
        <version>3.0.1</version>
    </dependency>

    <dependency>
        <groupId>junit</groupId>
        <artifactId>junit</artifactId>
        <version>4.11</version>
        <scope>test</scope>
    </dependency>
    
    <dependency>
        <groupId>org.testng</groupId>
        <artifactId>testng</artifactId>
        <version>6.10</version>
    </dependency>
    

</dependencies>

</project>

## Error console
"C:\Program Files\Java\jdk1.8.0_111\bin\java" -ea -Didea.launcher.port=7533 "-Didea.launcher.bin.path=C:\Program Files (x86)\JetBrains\IntelliJ IDEA Community Edition 2016.3.2\bin" -Dfile.encoding=UTF-8 -classpath "C:\Program Files (x86)\JetBrains\IntelliJ IDEA Community Edition 2016.3.2\lib\idea_rt.jar;C:\Program Files (x86)\JetBrains\IntelliJ IDEA Community Edition 2016.3.2\plugins\junit\lib\junit-rt.jar;C:\Program Files\Java\jdk1.8.0_111\jre\lib\charsets.jar;C:\Program Files\Java\jdk1.8.0_111\jre\lib\deploy.jar;C:\Program Files\Java\jdk1.8.0_111\jre\lib\ext\access-bridge-64.jar;C:\Program Files\Java\jdk1.8.0_111\jre\lib\ext\cldrdata.jar;C:\Program Files\Java\jdk1.8.0_111\jre\lib\ext\dnsns.jar;C:\Program Files\Java\jdk1.8.0_111\jre\lib\ext\jaccess.jar;C:\Program Files\Java\jdk1.8.0_111\jre\lib\ext\jfxrt.jar;C:\Program Files\Java\jdk1.8.0_111\jre\lib\ext\localedata.jar;C:\Program Files\Java\jdk1.8.0_111\jre\lib\ext\nashorn.jar;C:\Program Files\Java\jdk1.8.0_111\jre\lib\ext\sunec.jar;C:\Program Files\Java\jdk1.8.0_111\jre\lib\ext\sunjce_provider.jar;C:\Program Files\Java\jdk1.8.0_111\jre\lib\ext\sunmscapi.jar;C:\Program Files\Java\jdk1.8.0_111\jre\lib\ext\sunpkcs11.jar;C:\Program Files\Java\jdk1.8.0_111\jre\lib\ext\zipfs.jar;C:\Program Files\Java\jdk1.8.0_111\jre\lib\javaws.jar;C:\Program Files\Java\jdk1.8.0_111\jre\lib\jce.jar;C:\Program Files\Java\jdk1.8.0_111\jre\lib\jfr.jar;C:\Program Files\Java\jdk1.8.0_111\jre\lib\jfxswt.jar;C:\Program Files\Java\jdk1.8.0_111\jre\lib\jsse.jar;C:\Program Files\Java\jdk1.8.0_111\jre\lib\management-agent.jar;C:\Program Files\Java\jdk1.8.0_111\jre\lib\plugin.jar;C:\Program Files\Java\jdk1.8.0_111\jre\lib\resources.jar;C:\Program Files\Java\jdk1.8.0_111\jre\lib\rt.jar;C:\Jodi\2017_Auto\Mytest\target\test-classes;C:\Jodi\2017_Auto\Mytest\target\classes;C:\Users\JCha\.m2\repository\org\seleniumhq\selenium\selenium-java\3.0.1\selenium-java-3.0.1.jar;C:\Users\JCha\.m2\repository\org\seleniumhq\selenium\selenium-chrome-driver\3.0.1\selenium-chrome-driver-3.0.1.jar;C:\Users\JCha\.m2\repository\org\seleniumhq\selenium\selenium-remote-driver\3.0.1\selenium-remote-driver-3.0.1.jar;C:\Users\JCha\.m2\repository\org\seleniumhq\selenium\selenium-api\3.0.1\selenium-api-3.0.1.jar;C:\Users\JCha\.m2\repository\cglib\cglib-nodep\3.2.4\cglib-nodep-3.2.4.jar;C:\Users\JCha\.m2\repository\org\apache\commons\commons-exec\1.3\commons-exec-1.3.jar;C:\Users\JCha\.m2\repository\com\google\code\gson\gson\2.3.1\gson-2.3.1.jar;C:\Users\JCha\.m2\repository\com\google\guava\guava\19.0\guava-19.0.jar;C:\Users\JCha\.m2\repository\net\java\dev\jna\jna-platform\4.1.0\jna-platform-4.1.0.jar;C:\Users\JCha\.m2\repository\net\java\dev\jna\jna\4.1.0\jna-4.1.0.jar;C:\Users\JCha\.m2\repository\org\seleniumhq\selenium\selenium-edge-driver\3.0.1\selenium-edge-driver-3.0.1.jar;C:\Users\JCha\.m2\repository\org\seleniumhq\selenium\selenium-firefox-driver\3.0.1\selenium-firefox-driver-3.0.1.jar;C:\Users\JCha\.m2\repository\org\seleniumhq\selenium\selenium-ie-driver\3.0.1\selenium-ie-driver-3.0.1.jar;C:\Users\JCha\.m2\repository\org\seleniumhq\selenium\selenium-opera-driver\3.0.1\selenium-opera-driver-3.0.1.jar;C:\Users\JCha\.m2\repository\org\seleniumhq\selenium\selenium-safari-driver\3.0.1\selenium-safari-driver-3.0.1.jar;C:\Users\JCha\.m2\repository\io\netty\netty\3.5.7.Final\netty-3.5.7.Final.jar;C:\Users\JCha\.m2\repository\org\seleniumhq\selenium\selenium-support\3.0.1\selenium-support-3.0.1.jar;C:\Users\JCha\.m2\repository\net\sourceforge\htmlunit\htmlunit\2.23\htmlunit-2.23.jar;C:\Users\JCha\.m2\repository\xalan\xalan\2.7.2\xalan-2.7.2.jar;C:\Users\JCha\.m2\repository\xalan\serializer\2.7.2\serializer-2.7.2.jar;C:\Users\JCha\.m2\repository\org\apache\commons\commons-lang3\3.4\commons-lang3-3.4.jar;C:\Users\JCha\.m2\repository\org\apache\httpcomponents\httpclient\4.5.2\httpclient-4.5.2.jar;C:\Users\JCha\.m2\repository\org\apache\httpcomponents\httpcore\4.4.4\httpcore-4.4.4.jar;C:\Users\JCha\.m2\repository\org\apache\httpcomponents\httpmime\4.5.2\httpmime-4.5.2.jar;C:\Users\JCha\.m2\repository\commons-codec\commons-codec\1.10\commons-codec-1.10.jar;C:\Users\JCha\.m2\repository\net\sourceforge\htmlunit\htmlunit-core-js\2.23\htmlunit-core-js-2.23.jar;C:\Users\JCha\.m2\repository\net\sourceforge\htmlunit\neko-htmlunit\2.23\neko-htmlunit-2.23.jar;C:\Users\JCha\.m2\repository\xerces\xercesImpl\2.11.0\xercesImpl-2.11.0.jar;C:\Users\JCha\.m2\repository\xml-apis\xml-apis\1.4.01\xml-apis-1.4.01.jar;C:\Users\JCha\.m2\repository\net\sourceforge\cssparser\cssparser\0.9.20\cssparser-0.9.20.jar;C:\Users\JCha\.m2\repository\org\w3c\css\sac\1.3\sac-1.3.jar;C:\Users\JCha\.m2\repository\commons-io\commons-io\2.5\commons-io-2.5.jar;C:\Users\JCha\.m2\repository\commons-logging\commons-logging\1.2\commons-logging-1.2.jar;C:\Users\JCha\.m2\repository\com\codeborne\phantomjsdriver\1.3.0\phantomjsdriver-1.3.0.jar;C:\Users\JCha\.m2\repository\org\eclipse\jetty\websocket\websocket-client\9.2.15.v20160210\websocket-client-9.2.15.v20160210.jar;C:\Users\JCha\.m2\repository\org\eclipse\jetty\jetty-util\9.2.15.v20160210\jetty-util-9.2.15.v20160210.jar;C:\Users\JCha\.m2\repository\org\eclipse\jetty\jetty-io\9.2.15.v20160210\jetty-io-9.2.15.v20160210.jar;C:\Users\JCha\.m2\repository\org\eclipse\jetty\websocket\websocket-common\9.2.15.v20160210\websocket-common-9.2.15.v20160210.jar;C:\Users\JCha\.m2\repository\org\eclipse\jetty\websocket\websocket-api\9.2.15.v20160210\websocket-api-9.2.15.v20160210.jar;C:\Users\JCha\.m2\repository\junit\junit\4.11\junit-4.11.jar;C:\Users\JCha\.m2\repository\org\hamcrest\hamcrest-core\1.3\hamcrest-core-1.3.jar;C:\Users\JCha\.m2\repository\org\testng\testng\6.10\testng-6.10.jar;C:\Users\JCha\.m2\repository\com\beust\jcommander\1.48\jcommander-1.48.jar" com.intellij.rt.execution.application.AppMain com.intellij.rt.execution.junit.JUnitStarter -ideVersion5 com.joditest.webdriver.MyFirstTest2
BEFORE NEW DRIVER. SETTING SYSTEM PROPERTY
STILL BEFORE NEW DRIVER
1484576900160	geckodriver	INFO	Listening on 127.0.0.1:23330
Jan 16, 2017 7:28:20 AM org.openqa.selenium.remote.ProtocolHandshake createSession
INFO: Attempting bi-dialect session, assuming Postel's Law holds true on the remote end
1484576900872	mozprofile::profile	INFO	Using profile path C:\Users\JCha\AppData\Local\Temp\rust_mozprofile.CayB6kVUpjhX
1484576900897	geckodriver::marionette	INFO	Starting browser C:\Program Files (x86)\Mozilla Firefox\firefox.exe
1484576900919	geckodriver::marionette	INFO	Connecting to Marionette on localhost:63241
1484576903288	Marionette	INFO	Listening on port 63241
Jan 16, 2017 7:28:27 AM org.openqa.selenium.remote.ProtocolHandshake createSession
INFO: Detected dialect: W3C
AFTER NEW DRIVER
AFTER NAVIGATE TO WEBSITE
AFTER ASSERT
AFTER CLOSE
[Child 2872] ###!!! ABORT: Aborting on channel error.: file c:/builds/moz2_slave/m-rel-w32-00000000000000000000/build/src/ipc/glue/MessageChannel.cpp, line 2056
Jan 16, 2017 7:28:31 AM org.openqa.selenium.os.UnixProcess destroy
SEVERE: Unable to kill process with PID 3776
AFTER QUIT

Process finished with exit code 0

**Comment by xyngfei** [comment] 2017-01-17 09:05
I have encountered similar issue. Anyone looking into this issue? 


Firefox Version: 50.1.0

Platform: Windows Server 2012 R2

Other installs/configs
java jre 1.8.0_111
robotframework-selenium2library 1.8.0
gecko driver 0.13.0-win32 / gecko driver 0.13.0-win64

**Comment by AutomatedTester** [comment] 2017-01-18 17:09
duplicate of #285

**Closed by AutomatedTester** 2017-01-18 17:09 UTC

**Comment by jodigithub** [comment] 2017-01-18 17:55
I disagree that this is a duplicate of 285.  The action actually does close the browser window but it is also throwing this error.  Please consider reopening it.

**Comment by AutomatedTester** [comment] 2017-01-18 18:10
The underlying issue is exactly the same and has to do with the remoteness of frames from within Firefox.
