### ISSUE TITLE
Selenium 3.0: Unsupported Command Exception

### ISSUE THREAD

**Issue by EktaChoudhary23** [mozilla/geckodriver#296] opened 2016-10-23 14:59 UTC
When trying to use Action class for mouseover, it says Unsupported command exception. 
Also opening browser and navigating to url works but with some error stating 

```
1477234762250	addons.xpi-utils	ERROR	Failed to write add-ons list to profile directory: [Exception... "Component returned failure code: 0x8052000e (NS_ERROR_FILE_IS_LOCKED) [nsIFile.moveTo]"  nsresult: "0x8052000e (NS_ERROR_FILE_IS_LOCKED)"  location: "JS frame :: resource://gre/modules/addons/XPIProvider.jsm -> resource://gre/modules/addons/XPIProviderUtils.js :: this.XPIDatabase.writeAddonsList :: line 1525"  data: no] Stack trace: this.XPIDatabase.writeAddonsList()@resource://gre/modules/addons/XPIProvider.jsm -> resource://gre/modules/addons/XPIProviderUtils.js:1525 < this.XPIProvider.checkForChanges()@resource://gre/modules/addons/XPIProvider.jsm:3657 < this.XPIProvider.startup()@resource://gre/modules/addons/XPIProvider.jsm:2622 < callProvider()@resource://gre/modules/AddonManager.jsm:227 < _startProvider()@resource://gre/modules/AddonManager.jsm:755 < AddonManagerInternal.startup()@resource://gre/modules/AddonManager.jsm:938 < this.AddonManagerPrivate.startup()@resource://gre/modules/AddonManager.jsm:2773 < amManager.prototype.observe()@resource://gre/components/addonManager.js:57
1477234763089	Marionette	INFO	Listening on port 53719
```

**Comment by andreastt** [comment] 2016-10-24 13:05
Duplicate of https://github.com/mozilla/geckodriver/issues/233.

**Closed by andreastt** 2016-10-24 13:05 UTC
