### ISSUE TITLE
doubleClick with selenium-html-runner-3.6.0 doesn't work on firefox 53 or 56

### ISSUE THREAD

**Issue by jeirgino** [mozilla/geckodriver#1031] opened 2017-10-25 10:26 UTC
## System
* Version:  0.19.0
* Platform: Windows 8.1
* Firefox: 53.0 and 56.0
* Selenium: selenium-html-runner-3.6.0.jar

Hello, thank you for helping me.

## Testcase
doubleClick | //div[@id='x-auto-21']/div[2]/div/table/tbody[2]/tr/td/div |

In selenium-IDE-2.9.1 it works but when I launch the script with html-runner-3.6.0 and a htmlSuite
the log said that the command passed but nothing happened on firefox.
It works for chrome.

java -jar selenium-html-runner-3.6.0.jar -htmlSuite *firefox @baseurl testSuite.html log.html

## Stacktrace
There is no stack trace because the command passed but the doubleClick didn't perform.

**Comment by lmtierney** [comment] 2017-10-25 12:03
Sounds like a duplicate of #661

**Comment by andreastt** [comment] 2017-10-25 13:43
Sure does!

**Closed by andreastt** 2017-10-25 13:43 UTC

**Comment by jeirgino** [comment] 2017-10-25 14:15
So this is not possible??

**Comment by andreastt** [comment] 2017-10-25 14:24
Selenium IDE isn’t supported for Firefox post 47.

**Comment by whimboo** [comment] 2017-11-15 14:30
As a note beside... the old Selenium IDE should still work up to Firefox 54.
