### ISSUE TITLE
go back not working

### ISSUE THREAD

**Issue by metareven** [mozilla/geckodriver#815] opened 2017-07-10 07:47 UTC
## Platform and application details
* Platform: Windows 10
* Firefox: 53
* Selenium: 3.40
* Geckodriver 0.17

Whenever I try to use browser.navigate().back() on the javascript selenium bindings the test case times out with the following stack trace:

```
09:08:57.744 INFO - Executing: [go back])
09:13:57.848 WARN - Exception thrown
org.openqa.selenium.TimeoutException: Timeout loading page after 300000ms
Build info: version: '3.4.0', revision: 'unknown', time: 'unknown'
System info: host: 'NRKLT59921', ip: '160.67.0.124', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_121'
Driver info: org.openqa.selenium.firefox.FirefoxDriver
Capabilities [{moz:profile=C:\Users\n635412\AppData\Local\Temp\rust_mozprofile.OKQjVXePMYEk, rotatable=false, timeouts={implicit=0.0, pageLoad=300000.0, script=30000.0}, pageLoadStrategy=normal, platform=ANY, specificationLevel=0.0, moz:accessibilityChecks=false, acceptInsecureCerts=false, browserVersion=53.0.2, platformVersion=10.0, moz:processID=25340.0, browserName=firefox, javascriptEnabled=true, platformName=windows_nt}]
Session ID: cec4b46d-6513-467d-a6e3-ff66f09a9235
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
        at java.lang.reflect.Constructor.newInstance(Unknown Source)
        at org.openqa.selenium.remote.http.W3CHttpResponseCodec.createException(W3CHttpResponseCodec.java:150)
        at org.openqa.selenium.remote.http.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:115)
        at org.openqa.selenium.remote.http.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:45)
        at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:164)
        at org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:82)
        at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:637)
        at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:694)
        at org.openqa.selenium.remote.RemoteWebDriver$RemoteNavigation.back(RemoteWebDriver.java:937)
        at org.openqa.selenium.support.events.EventFiringWebDriver$EventFiringNavigation.back(EventFiringWebDriver.java:484)
        at org.openqa.selenium.remote.server.handler.GoBack.call(GoBack.java:30)
        at org.openqa.selenium.remote.server.handler.GoBack.call(GoBack.java:22)
        at java.util.concurrent.FutureTask.run(Unknown Source)
        at org.openqa.selenium.remote.server.DefaultSession$1.run(DefaultSession.java:176)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.lang.Thread.run(Unknown Source)
```

It works on every other browser I have tried, including Internet Explorer

**Comment by andreastt** [comment] 2017-07-10 17:40
Firefox 53 is fairly old and we have made a number of improvements to the Go Back command since then. Can you please try again with Firefox Nightly?

**Comment by metareven** [comment] 2017-07-11 10:07
Tried using firefox 54 and had the same issues there. I am running my tests from a selenium node that is hosted remotely and I am not entirely sure how to make the tests run on the nightly build as it is installed as a seperate executable instead of replacing my old firefox. Is there a way to specify the path of firefox in the node config in selenium or some other trick to be able to test this in the nightly build?

**Comment by andreastt** [comment] 2017-07-11 12:37
Firefox 54 is stable. Could you test with Firefox 56 (Nightly)? It would also be good if you attached a trace-level log from geckodriver.

See the README for how to configure a specific Firefox binary through capabilities.

**Comment by metareven** [comment] 2017-07-11 13:34
Seems to have the exact same issue on the nightly build.

`15:17:55.531 INFO - Executing: [go back])
15:22:55.572 WARN - Exception thrown
org.openqa.selenium.TimeoutException: Timeout loading page after 300000ms
Build info: version: '3.4.0', revision: 'unknown', time: 'unknown'
System info: host: 'NRKLT59921', ip: '160.67.0.124', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_121'
Driver info: org.openqa.selenium.firefox.FirefoxDriver
Capabilities [{moz:profile=C:\Users\n635412\AppData\Local\Temp\rust_mozprofile.dzbK1E4mPjte, rotatable=false, timeouts={implicit=0.0, pageLoad=300000.0, script=30000.0}, pageLoadStrategy=normal, platform=ANY, specificationLevel=0.0, moz:accessibilityChecks=false, acceptInsecureCerts=false, browserVersion=56.0a1, platformVersion=10.0, moz:processID=11780.0, browserName=firefox, javascriptEnabled=true, platformName=windows_nt}]
Session ID: 56534698-7c2d-40a3-92f7-5d1aaf361807
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
        at java.lang.reflect.Constructor.newInstance(Unknown Source)
        at org.openqa.selenium.remote.http.W3CHttpResponseCodec.createException(W3CHttpResponseCodec.java:150)
        at org.openqa.selenium.remote.http.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:115)
        at org.openqa.selenium.remote.http.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:45)
        at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:164)
        at org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:82)
        at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:637)
        at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:694)
        at org.openqa.selenium.remote.RemoteWebDriver$RemoteNavigation.back(RemoteWebDriver.java:937)
        at org.openqa.selenium.support.events.EventFiringWebDriver$EventFiringNavigation.back(EventFiringWebDriver.java:484)
        at org.openqa.selenium.remote.server.handler.GoBack.call(GoBack.java:30)
        at org.openqa.selenium.remote.server.handler.GoBack.call(GoBack.java:22)
        at java.util.concurrent.FutureTask.run(Unknown Source)
        at org.openqa.selenium.remote.server.DefaultSession$1.run(DefaultSession.java:176)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.lang.Thread.run(Unknown Source)
`

After doing some visual inspection I can see that the browser does in fact navigate back, but it seems to timeout once it's done navigating back

**Comment by andreastt** [comment] 2017-07-11 14:03
And the trace log?

**Comment by metareven** [comment] 2017-07-12 06:54
That there was the trace log after the `15:17:55.450 INFO - Executing: [go back])` and it looks pretty much identical to the one I got on firefox 53

**Comment by andreastt** [comment] 2017-07-12 10:38
That log line doesn’t originate from geckodriver, but from Selenium. To have any chance at diagnosing this issue, you need to provide a trace-level log from geckodriver. See the README for how to configure it.

You can either pass `-vv` to the geckodriver binary, or a `{"moz:firefoxOptions": {"log": {"level: "trace"}}}` capability.

**Comment by metareven** [comment] 2017-07-12 12:46
I couldn't find out how to make selenium pass the `-vv` parameter to the geckodriver binary so I went with the capability route. Couldn't see any trace level logs, so I'll just send you the entire log from my test that uses the go back functionality in case you see something interesting
```
14:37:56.978 INFO - Executing: [new session: Capabilities [{browserName=firefox, moz:firefoxOptions={log={level=trace}}}]])
14:37:56.978 INFO - Creating a new session for Capabilities [{browserName=firefox, moz:firefoxOptions={log={level=trace}}}]
14:37:56.993 INFO - Preferring the firefox binary in these options (C:\Program Files\Nightly\firefox.exe rather than C:/Program Files/Nightly/firefox.exe)
14:37:56.993 INFO - Preferring the firefox binary in these options (C:\Program Files\Nightly\firefox.exe rather than C:/Program Files/Nightly/firefox.exe)
1499863077325   geckodriver     INFO    Listening on 127.0.0.1:38911
1499863077662   geckodriver::marionette INFO    Starting browser C:\Program Files\Nightly\firefox.exe with args ["-marionette"]
1499863078663   Marionette      INFO    Enabled via --marionette
1499863080657   Marionette      INFO    Listening on port 51827
1499863080674   Marionette      INFO    Listening on port 51827
1499863080929   Marionette      DEBUG   Register listener.js for window 4294967297
14:38:00.950 INFO - Detected dialect: W3C
14:38:00.951 INFO - Done: [new session: Capabilities [{browserName=firefox, moz:firefoxOptions={log={level=trace}}}]]
14:38:00.986 INFO - Executing: [get: http://dev.nrk.no/valg/2017/resultat])
1499863081001   Marionette      DEBUG   Received DOM event "beforeunload" for "about:blank"
1499863081165   Marionette      DEBUG   Received DOM event "pagehide" for "about:blank"
1499863081166   Marionette      DEBUG   Received DOM event "unload" for "about:blank"
1499863083156   Marionette      DEBUG   Received DOM event "DOMContentLoaded" for "http://dev.nrk.no/valg/2017/resultat/"
1499863083741   Marionette      DEBUG   Received DOM event "pageshow" for "http://dev.nrk.no/valg/2017/resultat/"
14:38:03.760 INFO - Done: [get: http://dev.nrk.no/valg/2017/resultat]
14:38:03.822 INFO - Executing: [find elements: By.cssSelector: [data-selenium-id="search-input"]])
14:38:03.838 INFO - Done: [find elements: By.cssSelector: [data-selenium-id="search-input"]]
14:38:03.891 INFO - Executing: [is enabled: 0 [[FirefoxDriver: firefox on ANY (f1854306-c153-4775-9112-b71e5c393aa0)] -> css selector: [data-selenium-id="search-input"]]])
14:38:03.959 INFO - Done: [is enabled: 0 [[FirefoxDriver: firefox on ANY (f1854306-c153-4775-9112-b71e5c393aa0)] -> css selector: [data-selenium-id="search-input"]]]
14:38:04.291 INFO - Executing: [click: 0 [[FirefoxDriver: firefox on ANY (f1854306-c153-4775-9112-b71e5c393aa0)] -> css selector: [data-selenium-id="search-input"]]])
1499863084577   Marionette      DEBUG   Canceled page load listener because no navigation has been detected
14:38:04.575 INFO - Done: [click: 0 [[FirefoxDriver: firefox on ANY (f1854306-c153-4775-9112-b71e5c393aa0)] -> css selector: [data-selenium-id="search-input"]]]
14:38:04.607 INFO - Executing: [clear: 0 [[FirefoxDriver: firefox on ANY (f1854306-c153-4775-9112-b71e5c393aa0)] -> css selector: [data-selenium-id="search-input"]]])
14:38:04.638 INFO - Done: [clear: 0 [[FirefoxDriver: firefox on ANY (f1854306-c153-4775-9112-b71e5c393aa0)] -> css selector: [data-selenium-id="search-input"]]]
14:38:04.660 INFO - Executing: [send keys: 0 [[FirefoxDriver: firefox on ANY (f1854306-c153-4775-9112-b71e5c393aa0)] -> css selector: [data-selenium-id="search-input"]], [O, s, l, o]])
14:38:04.691 INFO - Done: [send keys: 0 [[FirefoxDriver: firefox on ANY (f1854306-c153-4775-9112-b71e5c393aa0)] -> css selector: [data-selenium-id="search-input"]], [O, s, l, o]]
14:38:05.662 INFO - Executing: [get element attribute: 0 [[FirefoxDriver: firefox on ANY (f1854306-c153-4775-9112-b71e5c393aa0)] -> css selector: [data-selenium-id="search-input"]], value])
14:38:05.724 INFO - Done: [get element attribute: 0 [[FirefoxDriver: firefox on ANY (f1854306-c153-4775-9112-b71e5c393aa0)] -> css selector: [data-selenium-id="search-input"]], value]
14:38:05.740 INFO - Executing: [find active element])
14:38:05.758 INFO - Done: [find active element]
14:38:06.778 INFO - Executing: [find elements: By.xpath: //div[text()="Oslo"]])
14:38:06.809 INFO - Done: [find elements: By.xpath: //div[text()="Oslo"]]
14:38:06.825 INFO - Executing: [get text: 1 [[FirefoxDriver: firefox on ANY (f1854306-c153-4775-9112-b71e5c393aa0)] -> xpath: //div[text()="Oslo"]]])
14:38:06.862 INFO - Done: [get text: 1 [[FirefoxDriver: firefox on ANY (f1854306-c153-4775-9112-b71e5c393aa0)] -> xpath: //div[text()="Oslo"]]]
14:38:06.894 INFO - Executing: [click: 1 [[FirefoxDriver: firefox on ANY (f1854306-c153-4775-9112-b71e5c393aa0)] -> xpath: //div[text()="Oslo"]]])
1499863087300   Marionette      DEBUG   Canceled page load listener because no navigation has been detected
14:38:07.295 INFO - Done: [click: 1 [[FirefoxDriver: firefox on ANY (f1854306-c153-4775-9112-b71e5c393aa0)] -> xpath: //div[text()="Oslo"]]]
14:38:07.364 INFO - Executing: [find elements: By.cssSelector: [data-selenium-id="related_links"] a])
14:38:07.379 INFO - Done: [find elements: By.cssSelector: [data-selenium-id="related_links"] a]
14:38:07.426 INFO - Executing: [find elements: By.cssSelector: [data-selenium-id="related_links"] a])
14:38:07.464 INFO - Done: [find elements: By.cssSelector: [data-selenium-id="related_links"] a]
14:38:07.495 INFO - Executing: [find elements: By.cssSelector: [data-selenium-id="related_links"] a])
14:38:07.827 INFO - Done: [find elements: By.cssSelector: [data-selenium-id="related_links"] a]
14:38:07.843 INFO - Executing: [find elements: By.cssSelector: [data-selenium-id="related_links"] a])
14:38:07.880 INFO - Done: [find elements: By.cssSelector: [data-selenium-id="related_links"] a]
14:38:07.912 INFO - Executing: [get text: 2 [[FirefoxDriver: firefox on ANY (f1854306-c153-4775-9112-b71e5c393aa0)] -> css selector: [data-selenium-id="related_links"] a]])
14:38:07.943 INFO - Done: [get text: 2 [[FirefoxDriver: firefox on ANY (f1854306-c153-4775-9112-b71e5c393aa0)] -> css selector: [data-selenium-id="related_links"] a]]
14:38:07.965 INFO - Executing: [click: 2 [[FirefoxDriver: firefox on ANY (f1854306-c153-4775-9112-b71e5c393aa0)] -> css selector: [data-selenium-id="related_links"] a]])
1499863088315   Marionette      DEBUG   Canceled page load listener because no navigation has been detected
14:38:08.313 INFO - Done: [click: 2 [[FirefoxDriver: firefox on ANY (f1854306-c153-4775-9112-b71e5c393aa0)] -> css selector: [data-selenium-id="related_links"] a]]
14:38:08.328 INFO - Executing: [find elements: By.xpath: //*[@class="nrk-pageHeader__title"][text()="Gamle Oslo"]])
14:38:08.482 INFO - Done: [find elements: By.xpath: //*[@class="nrk-pageHeader__title"][text()="Gamle Oslo"]]
14:38:09.245 INFO - Executing: [find elements: By.cssSelector: .nrk-results])
14:38:09.267 INFO - Done: [find elements: By.cssSelector: .nrk-results]
14:38:09.314 INFO - Executing: [go back])
14:43:09.374 WARN - Exception thrown
org.openqa.selenium.TimeoutException: Timeout loading page after 300000ms
Build info: version: '3.4.0', revision: 'unknown', time: 'unknown'
System info: host: 'NRKLT59921', ip: '160.67.0.124', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_121'
Driver info: org.openqa.selenium.firefox.FirefoxDriver
Capabilities [{moz:profile=C:\Users\n635412\AppData\Local\Temp\rust_mozprofile.pXJ9Kj2bm20E, rotatable=false, timeouts={implicit=0.0, pageLoad=300000.0, script=30000.0}, pageLoadStrategy=normal, platform=ANY, specificationLevel=0.0, moz:accessibilityChecks=false, acceptInsecureCerts=false, browserVersion=56.0a1, platformVersion=10.0, moz:processID=30968.0, browserName=firefox, javascriptEnabled=true, platformName=windows_nt}]
Session ID: f1854306-c153-4775-9112-b71e5c393aa0
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
        at java.lang.reflect.Constructor.newInstance(Unknown Source)
        at org.openqa.selenium.remote.http.W3CHttpResponseCodec.createException(W3CHttpResponseCodec.java:150)
        at org.openqa.selenium.remote.http.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:115)
        at org.openqa.selenium.remote.http.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:45)
        at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:164)
        at org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:82)
        at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:637)
        at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:694)
        at org.openqa.selenium.remote.RemoteWebDriver$RemoteNavigation.back(RemoteWebDriver.java:937)
        at org.openqa.selenium.support.events.EventFiringWebDriver$EventFiringNavigation.back(EventFiringWebDriver.java:484)
        at org.openqa.selenium.remote.server.handler.GoBack.call(GoBack.java:30)
        at org.openqa.selenium.remote.server.handler.GoBack.call(GoBack.java:22)
        at java.util.concurrent.FutureTask.run(Unknown Source)
        at org.openqa.selenium.remote.server.DefaultSession$1.run(DefaultSession.java:176)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.lang.Thread.run(Unknown Source)
14:43:09.374 WARN - Exception: Timeout loading page after 300000ms
Build info: version: '3.4.0', revision: 'unknown', time: 'unknown'
System info: host: 'NRKLT59921', ip: '160.67.0.124', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_121'
Driver info: org.openqa.selenium.firefox.FirefoxDriver
Capabilities [{moz:profile=C:\Users\n635412\AppData\Local\Temp\rust_mozprofile.pXJ9Kj2bm20E, rotatable=false, timeouts={implicit=0.0, pageLoad=300000.0, script=30000.0}, pageLoadStrategy=normal, platform=ANY, specificationLevel=0.0, moz:accessibilityChecks=false, acceptInsecureCerts=false, browserVersion=56.0a1, platformVersion=10.0, moz:processID=30968.0, browserName=firefox, javascriptEnabled=true, platformName=windows_nt}]
Session ID: f1854306-c153-4775-9112-b71e5c393aa0
14:43:09.421 INFO - Executing: [take screenshot])
14:43:09.923 INFO - Done: [take screenshot]
14:43:10.076 INFO - Executing: [delete session: 4199b66d-1934-4024-b342-d57521a99702])
1499863390089   Marionette      INFO    New connections will no longer be accepted
14:43:10.807 INFO - Done: [delete session: 4199b66d-1934-4024-b342-d57521a99702]
```

**Comment by whimboo** [comment] 2017-07-17 12:08
This is a debug log but not a trace log. Can you please show the code how you selected the trace option? Also please show the line of code which navigates back.

**Comment by metareven** [comment] 2017-07-17 12:21
Here is the code where I initialize the webdriver
```
const caps = {'moz:firefoxOptions': {log: {level: 'trace'}}}
    this.driver = new seleniumWebdriver.Builder()
    .usingServer('http://nrklt59921:4444/wd/hub')
    .withCapabilities(caps)
    .forBrowser('firefox')
    .build()
```

Here is the part of the test with the back navigation

```
return this.driver.elementExists('[data-selenium-id="related_links"] a')
    .then(() => this.driver.findElements({css:'[data-selenium-id="related_links"] a'}))
    .then(async(elements) => {
      for(let i = 0; i < elements.length; i++){
        const text = await elements[i].getText()
        await elements[i].click()
        await verifyPage(this.driver,text)
        await this.driver.navigate().back()
        await this.driver.elementExists('[data-selenium-id="related_links"] a')
        elements = await this.driver.findElements({css:'[data-selenium-id="related_links"] a'})
      }
    })
```


I assumed everything was in order since the first line printed when running the tests is
`14:37:56.978 INFO - Executing: [new session: Capabilities [{browserName=firefox, moz:firefoxOptions={log={level=trace}}}]])`

**Comment by whimboo** [comment] 2017-07-17 14:53
Strange. Not sure why this doesn't give trace level logs. @andreastt knows more about that, and maybe he can help.

Regarding navigating back, how is `navigate().back()` implemented for the Javascript binding? I would like to see how it calls into geckodriver. If you can send a link I would appreciate that. Thanks.

**Comment by metareven** [comment] 2017-07-18 07:27
Source code should be here: https://github.com/SeleniumHQ/selenium/blob/master/javascript/node/selenium-webdriver/lib/webdriver.js#L1151

https://github.com/SeleniumHQ/selenium/blob/ceaf3da79542024becdda5953059dfbb96fb3a90/javascript/webdriver/command.js

It's working for the other browsers we are currently testing on (Edge,Chrome,mobile chrome)

**Comment by whimboo** [comment] 2017-07-18 08:30
Ok, so this looks fine. But what I find strange is that debug events from Marionette show up in your log, but nothing appears for 'goBack'. Given that I cannot access this website, can you please check if it is using some framework? I wonder if it could be related to issue 697, which is about Turbolinks.

**Comment by metareven** [comment] 2017-07-18 11:56
I am not that technically involved in the development of our site, but AFAIK we're not using any specific framework that should affect anything here. However when looking at #697 I can confirm that we do not fire any pagehide or pageload events when navigating back and forth through our application. I guess you can merge this issue with #697 if you require these events to be fired in order to resolve a goBack

**Comment by whimboo** [comment] 2017-07-19 04:35
I see. But it might still be something else. So is this behavior only visible for the development version of the website? Or can someone also see this for the public version? If yes, it would be great if you can construct a minimal Selenium testcase which let me reproduce it.

**Comment by metareven** [comment] 2017-07-19 08:13
We don't have a production version of the website I am writing tests for right now, but we have another production site with the same issue that I could send you a link to. 

http://nrk.no/valg/2017/valgomat

```
const {Builder} = require('selenium-webdriver')

const driver = new Builder()
    .forBrowser('firefox')
    .build()

driver.get('https://www.nrk.no/valg/2017/valgomat/')
driver.findElement({css: '[data-selenium-id="alternative-2"]'}).click()
driver.findElement({css: '[data-selenium-id="forwardButton"]'}).click()
driver.navigate().back()
driver.quit()
```

The test times out on the `driver.navigate().back()` on firefox, but if you try with for instance chrome it should work just fine

**Comment by metareven** [comment] 2017-07-27 06:53
@whimboo  Have you been able to try this and see whether or not you are able to get more trace information than what I got?

**Comment by whimboo** [comment] 2017-08-03 08:32
Given that I was out the last 2 weeks I wasn't able to check this issue again. So lets see...

First, thanks a lot for this test case! It is pretty helpful for me to reproduce this problem. I'm not sure what's going on so I filed a bug for Marionette here: https://bugzilla.mozilla.org/show_bug.cgi?id=1386977. Hopefully we will have a solution for this problem soon.

**Comment by whimboo** [comment] 2017-08-03 08:44
@metareven, is this website using the react library from Facebook (https://facebook.github.io/react/)?

**Comment by metareven** [comment] 2017-08-03 11:47
@whimboo Yes this page uses react

**Comment by whimboo** [comment] 2017-08-03 11:51
Thanks! I will update the issue when the bug gets solved.

**Comment by whimboo** [comment] 2017-08-11 07:37
This is fixed now and will be available in the Nightly build of Firefox today.

**Closed by whimboo** 2017-08-11 07:37 UTC
Labels: marionette

**Comment by metareven** [comment] 2017-08-14 10:39
It works!
Thank you for a job well done

**Comment by whimboo** [comment] 2017-08-15 14:12
This feature just got uplifted and should be part of the next 56 beta.
