### ISSUE TITLE
Missing v0.19.0 32 bit

### ISSUE THREAD

**Issue by Drimix20** [mozilla/geckodriver#986] opened 2017-10-02 10:05 UTC
## System
* Version: v0.19.0
* Platform: Windows (64 bit)
* Firefox: 56.0 (32 bit)
* Selenium: 3.5.3

Missing released geckodriver v0.19.0 32 bit

**Comment by andreastt** [comment] 2017-10-02 12:43
Duplicate of https://github.com/mozilla/geckodriver/issues/951.

**Closed by andreastt** 2017-10-02 12:43 UTC
