### ISSUE TITLE
Firefox headless mode broken [geckodriver v0.22.0]

### ISSUE THREAD

**Issue by aj-dev** [mozilla/geckodriver#1381] opened 2018-09-20 15:18 UTC
## System

* Version: geckodriver v0.22.0
* Platform: macOS 10.13.6
* Firefox: 62.0 (64-bit)
* Selenium: selenium-server-standalone-3.14.0

## Testcase

Running Protractor tests on Firefox with `--headless` flag doesn't run them in headless mode with the latest geckodriver v0.22.0. Browser's GUI is always open.

This is a regression bug as tests run fine after downgrading to v0.21.0

**Comment by rodrigo-vazquez** [comment] 2018-09-20 19:52
Seeing the exact same issue, CI builds are failing when using Travis for me now. Downgrading to v0.21.0 ...

**Comment by whimboo** [comment] 2018-09-21 07:58
It works just fine for me with the 0.22.0 release. As we requested in the issue filing template a trace log should be provided. Sadly this wasn't done. So can one of you please add it as attachment please?

https://firefox-source-docs.mozilla.org/testing/geckodriver/geckodriver/TraceLogs.html

**Comment by andreastt** [comment] 2018-09-26 12:14
I don’t know protractor, but the `log` object above should be inside a `moz:firefoxOptions` entry, like this:

```
{"capabilities": {"alwaysMatch": {"moz:firefoxOptions": {"log": {"level": "trace"}}}}}
```

See also:

* https://firefox-source-docs.mozilla.org/testing/geckodriver/geckodriver/Capabilities.html#capabilities-example
* https://firefox-source-docs.mozilla.org/testing/geckodriver/geckodriver/TraceLogs.html

**Comment by aj-dev** [comment] 2018-09-26 13:12
@andreastt thanks but I moved `log` inside `moz:firefoxOptions` and was still getting default info logs 
[geckodriver-info.log](https://github.com/mozilla/geckodriver/files/2419679/geckodriver-info.log)

 What worked for me in the end was this:
1. protractor config
```
    directConnect: false,
    seleniumAddress: 'http://localhost:4444',
    geckoDriver: path.resolve(process.cwd(), config.paths.geckoDriver, 'geckodriver'),
    baseUrl: config.frontendUrl,
    capabilities: {
        browserName: 'firefox',
        'moz:firefoxOptions': {
            args: [
                '-headless'
            ]
        }
    }
```
2. start geckodriver from command line with `./geckodriver --log trace` (it has to be in your PATH). It starts on localhost port 4444 which is provided as `seleniumAddress` in protractor config
3. run protractor tests

Trace log [geckodriver-trace.log](https://github.com/mozilla/geckodriver/files/2419682/geckodriver-trace.log)

What's interesting is this line where `-headless` flag is missing in Firefox command line args:

`1537965293435	webdriver::server	DEBUG	-> POST /session {"desiredCapabilities":{"browserName":"firefox","count":1,"moz:firefoxOptions":{"args":["-headless"]}}}
1537965293441	mozrunner::runner	INFO	Running command: "/Applications/Firefox.app/Contents/MacOS/firefox-bin" "-marionette" "-foreground" "-no-remote" "-profile" "/var/folders/r_/mfgd63ns2fg67y00l0cm34xw0000gn/T/rust_mozprofile.06mOkmeU6GOG"`

If I downgrade geckodriver to v0.21.0, I see:

`1537967319730	webdriver::server	DEBUG	-> POST /session {"desiredCapabilities":{"browserName":"firefox","count":1,"moz:firefoxOptions":{"args":["-headless"]}}}
1537967319741	mozrunner::runner	INFO	Running command: "/Applications/Firefox.app/Contents/MacOS/firefox-bin" "-marionette" "-headless" "-foreground" "-no-remote" "-profile" "/var/folders/r_/mfgd63ns2fg67y00l0cm34xw0000gn/T/rust_mozprofile.xKC8EFsNG9rG"`

Note that now `-headless` flag is being passed to Firefox correctly.

**Comment by aj-dev** [comment] 2018-09-26 15:16
After some more digging I found the root cause. `Geckodriver v0.22.0` no longer supports `desiredCapabilities` but `selenium-webdriver v3.6.0` that is used as dependency by protractor still sends it.
I can open an issue in Protractor repo to update `selenium-webdriver` to the latest version.

**Comment by whimboo** [comment] 2018-09-27 10:50
Oh wow, thanks a lot! We will make sure to get this fixed for the next geckdriver release which is due by early next week. Work is tracked on https://bugzilla.mozilla.org/show_bug.cgi?id=1494617.

**Comment by whimboo** [comment] 2018-09-27 11:09
It's actually a dupe of #1384.

**Closed by whimboo** 2018-09-27 11:09 UTC
Labels: geckodriver
