### ISSUE TITLE
selenium3 firefox mac

### ISSUE THREAD

**Issue by xyqiang** [mozilla/geckodriver#506] opened 2017-03-02 07:16 UTC
In order to help us efficiently investigate your issue, please provide the following information:

## Firefox Version
51.0.1   x64

selenium3

## Platform
OSX

## Steps to reproduce -
put the geckodriver to /usr/local/bin/ 

run 

import org.junit.Test;
import org.openqa.selenium.By;
import org.openqa.selenium.Keys;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.support.ui.WebDriverWait;

import static org.openqa.selenium.support.ui.ExpectedConditions.titleContains;

public class GeckoDriver {

    @Test
    public void findMarionetteOnGithub() {
        WebDriver driver = new FirefoxDriver();
        WebDriverWait wait = new WebDriverWait(driver, 10);
        driver.get("https://github.com");
        driver.findElement(By.className("header-search-input")).sendKeys("geckodriver" + Keys.RETURN);
        wait.until(titleContains("Search")); 
        driver.findElement(By.linkText("mozilla/geckodriver")).click();
        wait.until(titleContains("mozilla/geckodriver"));
        System.out.println(driver.findElement(By.cssSelector("article>p")).getText());
        driver.quit();
    }

}

log:
1488438721936	geckodriver	INFO	Listening on 127.0.0.1:7148
1488438722155	mozprofile::profile	INFO	Using profile path /var/folders/0t/c0hs6gq11z38vtlwcsplmspw0000gn/T/rust_mozprofile.HY4D1jTEnlI3
1488438722167	geckodriver::marionette	INFO	Starting browser /Applications/Firefox.app/Contents/MacOS/firefox-bin
1488438722170	geckodriver::marionette	INFO	Connecting to Marionette on localhost:63014
1488438722413	addons.manager	DEBUG	Application has been upgraded
1488438722434	addons.manager	DEBUG	Loaded provider scope for resource://gre/modules/addons/XPIProvider.jsm: ["XPIProvider"]
1488438722436	addons.manager	DEBUG	Loaded provider scope for resource://gre/modules/LightweightThemeManager.jsm: ["LightweightThemeManager"]
1488438722441	addons.manager	DEBUG	Loaded provider scope for resource://gre/modules/addons/GMPProvider.jsm
1488438722443	addons.manager	DEBUG	Loaded provider scope for resource://gre/modules/addons/PluginProvider.jsm
1488438722444	addons.manager	DEBUG	Starting provider: XPIProvider
1488438722444	addons.xpi	DEBUG	startup
1488438722445	addons.xpi	INFO	SystemAddonInstallLocation directory is missing
1488438722446	addons.xpi	INFO	Mapping aushelper@mozilla.org to /Applications/Firefox.app/Contents/Resources/browser/features/aushelper@mozilla.org.xpi
1488438722446	addons.xpi	INFO	Mapping e10srollout@mozilla.org to /Applications/Firefox.app/Contents/Resources/browser/features/e10srollout@mozilla.org.xpi
1488438722447	addons.xpi	INFO	Mapping firefox@getpocket.com to /Applications/Firefox.app/Contents/Resources/browser/features/firefox@getpocket.com.xpi
1488438722447	addons.xpi	INFO	Mapping webcompat@mozilla.org to /Applications/Firefox.app/Contents/Resources/browser/features/webcompat@mozilla.org.xpi
1488438722448	addons.xpi	INFO	Mapping {972ce4c6-7e08-4474-a285-3208198ce6fd} to /Applications/Firefox.app/Contents/Resources/browser/extensions/{972ce4c6-7e08-4474-a285-3208198ce6fd}.xpi
1488438722448	addons.xpi	DEBUG	checkForChanges
1488438722449	addons.xpi	DEBUG	Loaded add-on state from prefs: {}
1488438722450	addons.xpi	DEBUG	New add-on aushelper@mozilla.org in app-system-defaults
1488438722451	addons.xpi	DEBUG	getModTime: Recursive scan of aushelper@mozilla.org
1488438722451	addons.xpi	DEBUG	New add-on e10srollout@mozilla.org in app-system-defaults
1488438722452	addons.xpi	DEBUG	getModTime: Recursive scan of e10srollout@mozilla.org
1488438722453	addons.xpi	DEBUG	New add-on firefox@getpocket.com in app-system-defaults
1488438722454	addons.xpi	DEBUG	getModTime: Recursive scan of firefox@getpocket.com
1488438722455	addons.xpi	DEBUG	New add-on webcompat@mozilla.org in app-system-defaults
1488438722456	addons.xpi	DEBUG	getModTime: Recursive scan of webcompat@mozilla.org
1488438722456	addons.xpi	DEBUG	New add-on {972ce4c6-7e08-4474-a285-3208198ce6fd} in app-global
1488438722457	addons.xpi	DEBUG	getModTime: Recursive scan of {972ce4c6-7e08-4474-a285-3208198ce6fd}
1488438722457	addons.xpi	DEBUG	getInstallState changed: true, state: {"app-system-defaults":{"aushelper@mozilla.org":{"d":"/Applications/Firefox.app/Contents/Resources/browser/features/aushelper@mozilla.org.xpi","st":1485381478000},"e10srollout@mozilla.org":{"d":"/Applications/Firefox.app/Contents/Resources/browser/features/e10srollout@mozilla.org.xpi","st":1485381478000},"firefox@getpocket.com":{"d":"/Applications/Firefox.app/Contents/Resources/browser/features/firefox@getpocket.com.xpi","st":1485381478000},"webcompat@mozilla.org":{"d":"/Applications/Firefox.app/Contents/Resources/browser/features/webcompat@mozilla.org.xpi","st":1485381478000}},"app-global":{"{972ce4c6-7e08-4474-a285-3208198ce6fd}":{"d":"/Applications/Firefox.app/Contents/Resources/browser/extensions/{972ce4c6-7e08-4474-a285-3208198ce6fd}.xpi","st":1485381478000}}}
1488438722466	addons.xpi-utils	DEBUG	Opening XPI database /var/folders/0t/c0hs6gq11z38vtlwcsplmspw0000gn/T/rust_mozprofile.HY4D1jTEnlI3/extensions.json
1488438722467	addons.xpi-utils	DEBUG	New add-on aushelper@mozilla.org installed in app-system-defaults
*** Blocklist::_loadBlocklistFromFile: blocklist is disabled
1488438722480	DeferredSave.extensions.json	DEBUG	Save changes
1488438722481	addons.xpi-utils	DEBUG	New add-on e10srollout@mozilla.org installed in app-system-defaults
1488438722484	DeferredSave.extensions.json	DEBUG	Starting timer
1488438722485	DeferredSave.extensions.json	DEBUG	Save changes
1488438722486	addons.xpi-utils	DEBUG	New add-on firefox@getpocket.com installed in app-system-defaults
1488438722493	DeferredSave.extensions.json	DEBUG	Save changes
1488438722493	addons.xpi-utils	DEBUG	New add-on webcompat@mozilla.org installed in app-system-defaults
1488438722498	DeferredSave.extensions.json	DEBUG	Save changes
1488438722499	addons.xpi-utils	DEBUG	New add-on {972ce4c6-7e08-4474-a285-3208198ce6fd} installed in app-global
1488438722505	DeferredSave.extensions.json	DEBUG	Save changes
1488438722506	addons.manager	DEBUG	Registering startup change 'installed' for aushelper@mozilla.org
1488438722515	addons.xpi	DEBUG	Loading bootstrap scope from /Applications/Firefox.app/Contents/Resources/browser/features/aushelper@mozilla.org.xpi
1488438722520	addons.xpi	DEBUG	Calling bootstrap method install on aushelper@mozilla.org version 1.0
1488438722520	addons.xpi-utils	DEBUG	Make addon app-system-defaults:aushelper@mozilla.org visible
1488438722520	DeferredSave.extensions.json	DEBUG	Save changes
1488438722522	addons.manager	DEBUG	Registering startup change 'installed' for e10srollout@mozilla.org
1488438722523	addons.xpi	DEBUG	Loading bootstrap scope from /Applications/Firefox.app/Contents/Resources/browser/features/e10srollout@mozilla.org.xpi
1488438722526	addons.xpi	DEBUG	Calling bootstrap method install on e10srollout@mozilla.org version 1.7
1488438722527	addons.xpi-utils	DEBUG	Make addon app-system-defaults:e10srollout@mozilla.org visible
1488438722528	DeferredSave.extensions.json	DEBUG	Save changes
1488438722528	addons.manager	DEBUG	Registering startup change 'installed' for firefox@getpocket.com
1488438722530	addons.xpi	DEBUG	Loading bootstrap scope from /Applications/Firefox.app/Contents/Resources/browser/features/firefox@getpocket.com.xpi
1488438722535	addons.xpi	DEBUG	Calling bootstrap method install on firefox@getpocket.com version 1.0.5
1488438722535	addons.xpi-utils	DEBUG	Make addon app-system-defaults:firefox@getpocket.com visible
1488438722536	DeferredSave.extensions.json	DEBUG	Save changes
1488438722536	addons.manager	DEBUG	Registering startup change 'installed' for webcompat@mozilla.org
1488438722538	addons.xpi	DEBUG	Loading bootstrap scope from /Applications/Firefox.app/Contents/Resources/browser/features/webcompat@mozilla.org.xpi
1488438722541	addons.xpi	DEBUG	Calling bootstrap method install on webcompat@mozilla.org version 1.0
1488438722541	addons.xpi-utils	DEBUG	Make addon app-system-defaults:webcompat@mozilla.org visible
1488438722542	DeferredSave.extensions.json	DEBUG	Save changes
1488438722542	addons.xpi-utils	DEBUG	Make addon app-global:{972ce4c6-7e08-4474-a285-3208198ce6fd} visible
1488438722543	DeferredSave.extensions.json	DEBUG	Save changes
1488438722543	addons.xpi	DEBUG	Updating XPIState for {"id":"aushelper@mozilla.org","syncGUID":"{b47d6841-800c-1f4b-b83a-069e13f2f3c6}","location":"app-system-defaults","version":"1.0","type":"extension","internalName":null,"updateURL":null,"updateKey":null,"optionsURL":null,"optionsType":null,"aboutURL":null,"icons":{},"iconURL":null,"icon64URL":null,"defaultLocale":{"name":"Application Update Service Helper","description":"Sets value(s) in the update url based on custom checks.","creator":null,"homepageURL":null},"visible":true,"active":true,"userDisabled":false,"appDisabled":false,"descriptor":"/Applications/Firefox.app/Contents/Resources/browser/features/aushelper@mozilla.org.xpi","installDate":1485381478000,"updateDate":1485381478000,"applyBackgroundUpdates":1,"bootstrap":true,"skinnable":false,"size":5975,"sourceURI":null,"releaseNotesURI":null,"softDisabled":false,"foreignInstall":false,"hasBinaryComponents":false,"strictCompatibility":false,"locales":[],"targetApplications":[{"id":"{ec8030f7-c20a-464f-9b0e-13a3a9e97384}","minVersion":"51.0.1","maxVersion":"51.*"}],"targetPlatforms":[],"multiprocessCompatible":true,"seen":true,"dependencies":[],"hasEmbeddedWebExtension":false,"mpcOptedOut":false}
1488438722543	addons.xpi	DEBUG	getModTime: Recursive scan of aushelper@mozilla.org
1488438722544	addons.xpi	DEBUG	Updating XPIState for {"id":"e10srollout@mozilla.org","syncGUID":"{b698dd76-2168-e843-b0ea-52806ce2101c}","location":"app-system-defaults","version":"1.7","type":"extension","internalName":null,"updateURL":null,"updateKey":null,"optionsURL":null,"optionsType":null,"aboutURL":null,"icons":{},"iconURL":null,"icon64URL":null,"defaultLocale":{"name":"Multi-process staged rollout","description":"Staged rollout of Firefox multi-process feature.","creator":null,"homepageURL":null},"visible":true,"active":true,"userDisabled":false,"appDisabled":false,"descriptor":"/Applications/Firefox.app/Contents/Resources/browser/features/e10srollout@mozilla.org.xpi","installDate":1485381478000,"updateDate":1485381478000,"applyBackgroundUpdates":1,"bootstrap":true,"skinnable":false,"size":6997,"sourceURI":null,"releaseNotesURI":null,"softDisabled":false,"foreignInstall":false,"hasBinaryComponents":false,"strictCompatibility":false,"locales":[],"targetApplications":[{"id":"{ec8030f7-c20a-464f-9b0e-13a3a9e97384}","minVersion":"51.0.1","maxVersion":"51.*"}],"targetPlatforms":[],"multiprocessCompatible":true,"seen":true,"dependencies":[],"hasEmbeddedWebExtension":false,"mpcOptedOut":false}
1488438722544	addons.xpi	DEBUG	getModTime: Recursive scan of e10srollout@mozilla.org
1488438722545	addons.xpi	DEBUG	Updating XPIState for {"id":"firefox@getpocket.com","syncGUID":"{584513a5-9e57-6940-86fd-e64a64b392f8}","location":"app-system-defaults","version":"1.0.5","type":"extension","internalName":null,"updateURL":null,"updateKey":null,"optionsURL":null,"optionsType":null,"aboutURL":null,"icons":{},"iconURL":null,"icon64URL":null,"defaultLocale":{"name":"Pocket","description":"When you find something you want to view later, put it in Pocket.","creator":null,"homepageURL":null},"visible":true,"active":true,"userDisabled":false,"appDisabled":false,"descriptor":"/Applications/Firefox.app/Contents/Resources/browser/features/firefox@getpocket.com.xpi","installDate":1485381478000,"updateDate":1485381478000,"applyBackgroundUpdates":1,"bootstrap":true,"skinnable":false,"size":921059,"sourceURI":null,"releaseNotesURI":null,"softDisabled":false,"foreignInstall":false,"hasBinaryComponents":false,"strictCompatibility":false,"locales":[],"targetApplications":[{"id":"{ec8030f7-c20a-464f-9b0e-13a3a9e97384}","minVersion":"51.0.1","maxVersion":"51.*"}],"targetPlatforms":[],"multiprocessCompatible":true,"seen":true,"dependencies":[],"hasEmbeddedWebExtension":false,"mpcOptedOut":false}
1488438722545	addons.xpi	DEBUG	getModTime: Recursive scan of firefox@getpocket.com
1488438722546	addons.xpi	DEBUG	Updating XPIState for {"id":"webcompat@mozilla.org","syncGUID":"{80daa3ce-c0a1-bf49-8220-39e06d0e34d2}","location":"app-system-defaults","version":"1.0","type":"extension","internalName":null,"updateURL":null,"updateKey":null,"optionsURL":null,"optionsType":null,"aboutURL":null,"icons":{},"iconURL":null,"icon64URL":null,"defaultLocale":{"name":"Web Compat","description":"Urgent post-release fixes for web compatibility.","creator":null,"homepageURL":null},"visible":true,"active":true,"userDisabled":false,"appDisabled":false,"descriptor":"/Applications/Firefox.app/Contents/Resources/browser/features/webcompat@mozilla.org.xpi","installDate":1485381478000,"updateDate":1485381478000,"applyBackgroundUpdates":1,"bootstrap":true,"skinnable":false,"size":1570,"sourceURI":null,"releaseNotesURI":null,"softDisabled":false,"foreignInstall":false,"hasBinaryComponents":false,"strictCompatibility":false,"locales":[],"targetApplications":[{"id":"{ec8030f7-c20a-464f-9b0e-13a3a9e97384}","minVersion":"51.0.1","maxVersion":"51.*"}],"targetPlatforms":[],"multiprocessCompatible":true,"seen":true,"dependencies":[],"hasEmbeddedWebExtension":false,"mpcOptedOut":false}
1488438722546	addons.xpi	DEBUG	getModTime: Recursive scan of webcompat@mozilla.org
1488438722547	addons.xpi	DEBUG	Updating XPIState for {"id":"{972ce4c6-7e08-4474-a285-3208198ce6fd}","syncGUID":"{3ca09625-a034-2d4a-aec2-586a396ec6e3}","location":"app-global","version":"51.0.1","type":"theme","internalName":"classic/1.0","updateURL":null,"updateKey":null,"optionsURL":null,"optionsType":null,"aboutURL":null,"icons":{"32":"icon.png","48":"icon.png"},"iconURL":null,"icon64URL":null,"defaultLocale":{"name":"Default","description":"The default theme.","creator":"Mozilla","homepageURL":null,"contributors":["Mozilla Contributors"]},"visible":true,"active":true,"userDisabled":false,"appDisabled":false,"descriptor":"/Applications/Firefox.app/Contents/Resources/browser/extensions/{972ce4c6-7e08-4474-a285-3208198ce6fd}.xpi","installDate":1485381478000,"updateDate":1485381478000,"applyBackgroundUpdates":1,"skinnable":true,"size":6352,"sourceURI":null,"releaseNotesURI":null,"softDisabled":false,"foreignInstall":false,"hasBinaryComponents":false,"strictCompatibility":true,"locales":[],"targetApplications":[{"id":"{ec8030f7-c20a-464f-9b0e-13a3a9e97384}","minVersion":"51.0.1","maxVersion":"51.0.1"}],"targetPlatforms":[],"seen":true,"dependencies":[],"hasEmbeddedWebExtension":false}
1488438722547	addons.xpi	DEBUG	getModTime: Recursive scan of {972ce4c6-7e08-4474-a285-3208198ce6fd}
1488438722549	DeferredSave.extensions.json	DEBUG	Save changes
1488438722549	addons.xpi	DEBUG	Updating database with changes to installed add-ons
1488438722549	addons.xpi-utils	DEBUG	Updating add-on states
1488438722550	addons.xpi-utils	DEBUG	Writing add-ons list
1488438722553	addons.xpi	DEBUG	Registering manifest for /Applications/Firefox.app/Contents/Resources/browser/features/aushelper@mozilla.org.xpi
1488438722554	addons.xpi	DEBUG	Calling bootstrap method startup on aushelper@mozilla.org version 1.0
1488438722556	addons.xpi	DEBUG	Registering manifest for /Applications/Firefox.app/Contents/Resources/browser/features/e10srollout@mozilla.org.xpi
1488438722559	addons.xpi	DEBUG	Calling bootstrap method startup on e10srollout@mozilla.org version 1.7
1488438722561	addons.xpi	DEBUG	Registering manifest for /Applications/Firefox.app/Contents/Resources/browser/features/firefox@getpocket.com.xpi
1488438722562	addons.xpi	DEBUG	Calling bootstrap method startup on firefox@getpocket.com version 1.0.5
1488438722564	addons.xpi	DEBUG	Registering manifest for /Applications/Firefox.app/Contents/Resources/browser/features/webcompat@mozilla.org.xpi
1488438722565	addons.xpi	DEBUG	Calling bootstrap method startup on webcompat@mozilla.org version 1.0
1488438722569	addons.manager	DEBUG	Registering shutdown blocker for XPIProvider
1488438722570	addons.manager	DEBUG	Provider finished startup: XPIProvider
1488438722570	addons.manager	DEBUG	Starting provider: LightweightThemeManager
1488438722570	addons.manager	DEBUG	Registering shutdown blocker for LightweightThemeManager
1488438722571	addons.manager	DEBUG	Provider finished startup: LightweightThemeManager
1488438722572	addons.manager	DEBUG	Starting provider: GMPProvider
1488438722579	addons.manager	DEBUG	Registering shutdown blocker for GMPProvider
1488438722580	addons.manager	DEBUG	Provider finished startup: GMPProvider
1488438722580	addons.manager	DEBUG	Starting provider: PluginProvider
1488438722580	addons.manager	DEBUG	Registering shutdown blocker for PluginProvider
1488438722580	addons.manager	DEBUG	Provider finished startup: PluginProvider
1488438722581	addons.manager	DEBUG	Completed startup sequence
1488438722781	Marionette	INFO	Listening on port 63014
1488438722977	addons.manager	DEBUG	Starting provider: <unnamed-provider>
1488438722977	addons.manager	DEBUG	Registering shutdown blocker for <unnamed-provider>
1488438722977	addons.manager	DEBUG	Provider finished startup: <unnamed-provider>
1488438722995	addons.manager	DEBUG	Starting provider: PreviousExperimentProvider
1488438722996	addons.manager	DEBUG	Registering shutdown blocker for PreviousExperimentProvider
1488438723003	addons.manager	DEBUG	Provider finished startup: PreviousExperimentProvider
1488438723009	DeferredSave.extensions.json	DEBUG	Starting write
1488438723222	DeferredSave.extensions.json	DEBUG	Write succeeded
1488438723223	addons.xpi-utils	DEBUG	XPI Database saved, setting schema version preference to 19
三月 02, 2017 3:12:04 下午 org.openqa.selenium.remote.ProtocolHandshake createSession
信息: Detected dialect: W3C
JavaScript error: , line 0: TypeError: NetworkError when attempting to fetch resource.
Proxy for using W3C WebDriver-compatible clients to interact with Gecko-based browsers.
[Child 37064] ###!!! ABORT: Aborting on channel error.: file /builds/slave/m-rel-m64-00000000000000000000/build/src/ipc/glue/MessageChannel.cpp, line 2056
[Child 37064] ###!!! ABORT: Aborting on channel error.: file /builds/slave/m-rel-m64-00000000000000000000/build/src/ipc/glue/MessageChannel.cpp, line 2056

**Comment by andreastt** [comment] 2017-03-02 18:33
Duplicate of https://github.com/mozilla/geckodriver/issues/285.

**Closed by andreastt** 2017-03-02 18:33 UTC
