### ISSUE TITLE
WebDriverException: Message: Process unexpectedly closed with status 11

### ISSUE THREAD

**Issue by EnricoBilla** [mozilla/geckodriver#1329] opened 2018-07-15 22:15 UTC
## System

* Version: 0.21.0
* Platform: Raspbian GNU/Linux 9 (stretch) on Raspberry Pi 3
* Firefox: 61.0.1
* Selenium: 3.13.0 (Python 2.7.13)

Both Firefox and Selenium should be compatible as the 0.21.0 release note:
> Note that with this release of geckodriver the minimum recommended
> Firefox and Selenium versions have changed:
> 
>  * Firefox 57 (and greater)
>  * Selenium 3.11 (and greater)

## Testcase

Just running this Python code should work

```
from selenium import webdriver
from selenium.webdriver.firefox.options import Options

options = Options()
options.log.level = "trace"
options.add_argument("--headless")

browser = webdriver.Firefox(firefox_options=options)
```

Note that the `--headless` argument is added in order to avoid the `Error: cannot open display: :0.0`

## Stacktrace

```
Traceback (most recent call last):
  File "prova.py", line 9, in <module>
    browser = webdriver.Firefox(firefox_options=options)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/firefox/webdriver.py", line 158, in __init__
    keep_alive=True)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/webdriver.py", line 154, in __init__
    self.start_session(desired_capabilities, browser_profile)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/webdriver.py", line 243, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/webdriver.py", line 311, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/errorhandler.py", line 237, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: Process unexpectedly closed with status 11
```

## Trace-level log

```
531692391019   geckodriver     INFO    geckodriver 0.21.0
1531692391052   geckodriver     INFO    Listening on 127.0.0.1:46133
1531692392045   mozrunner::runner       INFO    Running command: "/usr/bin/firefox" "-marionette" "-headless" "-foreground" "-no-remote" "-profile" "/tmp/rust_mozprofile.kVir5aclL1Ax"
1531692392050   geckodriver::marionette DEBUG   Waiting 60s to connect to browser on 127.0.0.1:43077
*** You are running in headless mode.
ExceptionHandler::GenerateDump cloned child 27089
ExceptionHandler::WaitForContinueSignal waiting for continue signal...
ExceptionHandler::SendContinueSignalToChild sent continue signal to child
1531692392653   webdriver::server       DEBUG   <- 500 Internal Server Error {"value":{"error":"unknown error","message":"Process unexpectedly closed with status 11","stacktrace":""}}
```

**Comment by andreastt** [comment] 2018-07-16 12:04
It looks like this is a Firefox crash, which is unrelated to geckodriver. Can you try get a crash dump from about:crashes?

**Comment by whimboo** [comment] 2018-07-24 19:39
Geckodriver disables crash report submission on purpose. If you want to check if it is a crash and crash details are available please follow: https://firefox-source-docs.mozilla.org/testing/geckodriver/geckodriver/CrashReports.html

Basically it should be a dupe of issue #1275. You cannot use a recent version of Firefox on Raspberry Pi.

**Closed by whimboo** 2018-07-24 19:39 UTC
Labels: waiting for reporter feedback
