### ISSUE TITLE
Inconsistent unload alert handling for clickElement and get

### ISSUE THREAD

**Issue by elliterate** [mozilla/geckodriver#1180] opened 2018-02-15 21:44 UTC
According to the response received in #1171, when navigating away from a page triggers an unload alert, subsequent driver interactions should:
* raise an unexpected alert error and
* dismiss the alert.

### Expected Behavior

**When** `WebDriver#get()` is called
**Then** a prompt is opened and must be enabled

### Actual Behavior

**When** `WebDriver#get()` is called
**Then** no prompt is opened and navigation completes immediately.

## System
* Version: 0.19.1
* Platform: macOS 10.12.6
* Firefox: 59.0b8; 60.0a1
* Selenium: py/3.9.0

### `test_handle_unload_alert.py`

```python
import inspect
import os.path
import pytest
from unittest import TestCase, main

from selenium import webdriver
from selenium.common.exceptions import NoAlertPresentException, UnexpectedAlertPresentException
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities


_DIR = os.path.dirname(os.path.abspath(inspect.getfile(inspect.currentframe())))

def _get_fixture_url(filename):
    return "file://{}".format(os.path.join(_DIR, filename))


class TestHandleUnloadAlert(TestCase):
    @classmethod
    def setUpClass(cls):
        capabilities = DesiredCapabilities.FIREFOX.copy()
        capabilities["marionette"] = True
        capabilities["moz:firefoxOptions"] = {"log": {"level": "trace"}}
        cls.driver = webdriver.Firefox(capabilities=capabilities)

    def setUp(self):
        self.driver.get(_get_fixture_url("with_unload_alert.html"))

    @classmethod
    def tearDownClass(cls):
        cls.driver.quit()

    # ...

    def test_get_without_unload_alert_handling(self):
        self.driver.get(_get_fixture_url("other.html"))

        # Error raised on driver interaction
        with self.assertRaises(UnexpectedAlertPresentException):
            self.driver.find_element_by_tag_name("p")

        # Alert automatically dismissed
        with self.assertRaises(NoAlertPresentException):
            self.driver.switch_to.alert

        # Navigation canceled
        self.assertNotIn("This is some other page.",
            self.driver.find_element_by_tag_name("p").text)

    def test_get_with_unload_alert_acceptance(self):
        self.driver.get(_get_fixture_url("other.html"))

        self.driver.switch_to.alert.accept()

        # Navigation completed
        self.assertIn("This is some other page.",
            self.driver.find_element_by_tag_name("p").text)

    def test_get_with_unload_alert_dismissal(self):
        self.driver.get(_get_fixture_url("other.html"))

        self.driver.switch_to.alert.dismiss()

        # Navigation canceled
        self.assertNotIn("This is some other page.",
            self.driver.find_element_by_tag_name("p").text)
            
    # ...


if __name__ == "__main__":
    main()
```

(Complete set of tested combinations: [test_handle_unload_alert.py.txt](https://github.com/mozilla/geckodriver/files/1731707/test_handle_unload_alert.py.txt))

### `with_unload_alert.html`

```html
<html>
  <head>
    <script>
        window.onbeforeunload = function(e) {
          return 'Unload?';
        };
    </script>
  </head>
  <body>
    <p>This triggers an alert on unload</p>

    <a href="landing.html">Go away</a>
  </body>
</html>
```

### `landing.html`

```html
<html>
  <body>
    <p>This is a landing page.</p>
  </body>
</html>
```

### `other.html`

```html
<html>
  <body>
    <p>This is some other page.</p>
  </body>
</html>
```

## Stacktrace

```
$ pytest -k test_get_without_unload_alert_handling
# ...
    def test_get_without_unload_alert_handling(self):
        self.driver.get(_get_fixture_url("other.html"))

        # Error raised on driver interaction
        with self.assertRaises(UnexpectedAlertPresentException):
>           self.driver.find_element_by_tag_name("p")
# ...
E           AssertionError: UnexpectedAlertPresentException not raised
```

```
$ pytest -k test_get_with_unload_alert_acceptance
# ...
    def test_get_with_unload_alert_acceptance(self):
        self.driver.get(_get_fixture_url("other.html"))

>       self.driver.switch_to.alert.accept()
# ...
E       selenium.common.exceptions.NoAlertPresentException: Message: No modal dialog is currently open
```

```
$ pytest -k test_get_with_unload_alert_dismissal
# ...
    def test_get_with_unload_alert_dismissal(self):
        self.driver.get(_get_fixture_url("other.html"))

>       self.driver.switch_to.alert.dismiss()
# ...
E       selenium.common.exceptions.NoAlertPresentException: Message: No modal dialog is currently open
```

## Trace-level log

[test_get_without_unload_alert_handling-geckodriver.log.txt](https://github.com/mozilla/geckodriver/files/1729500/test_get_without_unload_alert_handling-geckodriver.log.txt)
[test_get_with_unload_alert_acceptance-geckodriver.log.txt](https://github.com/mozilla/geckodriver/files/1729501/test_get_with_unload_alert_acceptance-geckodriver.log.txt)
[test_get_with_unload_alert_dismissal-geckodriver.log.txt](https://github.com/mozilla/geckodriver/files/1729502/test_get_with_unload_alert_dismissal-geckodriver.log.txt)

**Comment by whimboo** [comment] 2018-02-16 09:37
Same as for issue #1181. Please try to reduce the testcase. Thanks.

**Comment by elliterate** [comment] 2018-02-16 14:54
I moved the non-failing test cases into a separate, linked file.

**Comment by AutomatedTester** [comment] 2018-03-02 10:23
Duplicate of #1151

**Closed by AutomatedTester** 2018-03-02 10:23 UTC
Labels: waiting for reporter feedback
