### ISSUE TITLE
Hang when frame gets closed/removed with a click() from inside itself

### ISSUE THREAD

**Issue by caziz79** [mozilla/geckodriver#874] opened 2017-08-15 14:21 UTC
## System
* Version: 0.18.0
* Platform: Windows 10
* Firefox:  56 Beta
* Selenium: 3.4 or 3.5 Java 1.8

## Testcase
We have been waiting for the popup fixes and timeout changes in firefox which have made the browser untestable with our product via Webdriver.  While attempting to confirm the fixes in the Firefox 56 we found an issue.  Clicking on a button in an iframe that changes the location of the parent causes all following actions to result in TypeError: can't access dead object. 

**index.html**
<iframe id="leftFrame" class="iFrame" width="34%" height="100%" title="Access List Management Frame" src="/TestFrameSite/leftframe.html" name="subitem" style="height: 227px;"></iframe>

<iframe id="rightFrame" class="iFrame" width="64%" height="100%" title="Edit Permissions Frame" src="/TestFrameSite/rightframe.html" name="info" style="height: 227px;"></iframe>

**rightframe.html**

**leftframe.html**
input class="saveButton" type="button" value="Done" onclick="parent.location='/TestFrameSite/nextpage.html';"

**nextpage.html**
div id="nextpagediv"
next page
/div

driver.switchTo().defaultContent();
driver.switchTo().frame(driver.findElement(By.id("leftFrame")));
wait.until(ExpectedConditions.presenceOfElementLocated(By.className("saveButton")));
wait.until(ExpectedConditions.elementToBeClickable(driver.findElement(By.className("saveButton"))));
WebElement saveButton = driver.findElement(By.className("saveButton"));
saveButton.click();
		
wait.until(ExpectedConditions.presenceOfAllElementsLocatedBy(By.id("nextpagediv")));
WebElement nextpagediv = driver.findElement(By.id("nextpagediv"));
nextpagediv.getText();

## Stacktrace
*************************
A coding exception was thrown and uncaught in a Task.

Full message: TypeError: can't access dead object
Full stack: find_@chrome://marionette/content/element.js:302:7
element.find/</findElements<@chrome://marionette/content/element.js:267:17
evalFn@chrome://marionette/content/wait.js:90:7

*************************
*************************
A coding exception was thrown and uncaught in a Task.

Full message: TypeError: can't access dead object
Full stack: find_@chrome://marionette/content/element.js:302:7
element.find/</findElements<@chrome://marionette/content/element.js:267:17
evalFn@chrome://marionette/content/wait.js:90:7

*************************
Aug 15, 2017 9:50:53 AM org.openqa.selenium.support.ui.ExpectedConditions findElements
WARNING: WebDriverException thrown by findElements(By.id: nextpagediv)
org.openqa.selenium.WebDriverException: TypeError: can't access dead object
Build info: version: 'unknown', revision: 'unknown', time: 'unknown'
System info: host: , ip:, os.name: 'Windows 8.1', os.arch: 'amd64', os.version: '6.3', java.version: '1.8.0_40'
Driver info: org.openqa.selenium.firefox.FirefoxDriver
Capabilities [{moz:profile=C:\Users\caziz\AppData\Local\Temp\rust_mozprofile.yLZ4Q8OFvi3u, rotatable=false, timeouts={implicit=0.0, pageLoad=300000.0, script=30000.0}, pageLoadStrategy=normal, moz:headless=false, platform=ANY, specificationLevel=0.0, moz:accessibilityChecks=false, acceptInsecureCerts=true, browserVersion=56.0, platformVersion=10.0, moz:processID=20464.0, browserName=firefox, javascriptEnabled=true, platformName=windows_nt}]
Session ID: 71002cba-ca6d-4272-bf45-0b28ce9680cb
*** Element info: {Using=id, value=nextpagediv}
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:422)
	at org.openqa.selenium.remote.http.W3CHttpResponseCodec.createException(W3CHttpResponseCodec.java:185)
	at org.openqa.selenium.remote.http.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:120)
	at org.openqa.selenium.remote.http.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:49)
	at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:164)
	at org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:82)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:641)
	at org.openqa.selenium.remote.RemoteWebDriver.findElements(RemoteWebDriver.java:441)
	at org.openqa.selenium.remote.RemoteWebDriver.findElementsById(RemoteWebDriver.java:461)
	at org.openqa.selenium.By$ById.findElements(By.java:210)
	at org.openqa.selenium.remote.RemoteWebDriver.findElements(RemoteWebDriver.java:402)
	at org.openqa.selenium.support.ui.ExpectedConditions.findElements(ExpectedConditions.java:901)
	at org.openqa.selenium.support.ui.ExpectedConditions.access$200(ExpectedConditions.java:44)
	at org.openqa.selenium.support.ui.ExpectedConditions$11.apply(ExpectedConditions.java:316)
	at org.openqa.selenium.support.ui.ExpectedConditions$11.apply(ExpectedConditions.java:313)
	at org.openqa.selenium.support.ui.FluentWait.until(FluentWait.java:209)
	at com.opentext.auto.cs.gui.tests.chris.WorkingTest.testAdminLink(WorkingTest.java:29)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:47)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:44)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at com.opentext.automation.AutomationTestFailureRule$1.evaluate(AutomationTestFailureRule.java:25)
	at org.junit.rules.Verifier$1.evaluate(Verifier.java:35)
	at org.junit.rules.TestWatcher$1.evaluate(TestWatcher.java:55)
	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:271)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:70)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:50)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:63)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:236)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:53)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:229)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:48)
	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:309)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:86)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:459)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:678)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:382)

**Comment by whimboo** [comment] 2017-08-16 18:13
When the location of the parent of iframes is changed, all the frames are gone. And as such you are not able to continue to work with the currently selected frame. The error `TypeError: can't access dead object` just indicates that as long as [bug 1349861](https://bugzilla.mozilla.org/show_bug.cgi?id=1349861) is not fixed. Once done you will see get `NoSuchWindowException`.

So basically what you have to do here to be able to continue in the test is to call `Switch to Parent Frame` before any other operation. That will ensure that the parent frame gets selected.

So this is a dupe of #614.

**Comment by caziz79** [comment] 2017-08-16 18:33
So before gecko this used to work and all of the browser drivers still continue to function.  Are you saying that the other browser drivers are wrong?

**Comment by whimboo** [comment] 2017-08-18 10:25
@andreastt or @AutomatedTester any feedback from your side regarding the spec? 

I don't see anything which describes that we automatically should switch to the top-level browsing context in case the currently selected frame gets closed. Maybe it's something we are missing?

**Comment by AutomatedTester** [comment] 2017-08-18 13:15
This appears to be a really niche edge case and is only documented in https://github.com/SeleniumHQ/selenium/blob/master/java/client/test/org/openqa/selenium/FrameSwitchingTest.java#L307

This won't be getting added to the spec until at least a L2 of the spec. @shs96c is going to write up a bug for this as he has some of the historic knowledge of why people may want to do this.

**Comment by andreastt** [comment] 2017-08-18 18:22
@AutomatedTester Can you explain exactly what Marionette should be doing?

**Comment by AutomatedTester** [comment] 2017-08-21 09:48
@andreastt As I said in my previous comment, @shs96c is going to write it up. We can close this and potentially open something up again against the W3C bug.

It appears to have some implicit knowledge of moving back to frame that was removed and then readded in the index. This seems a little crazy as it goes against the main concepts of Selenium of trying to be explicit in your knowledge.

IRC Conversation in http://logs.glob.uno/?c=w3%23webdriver&s=18+Aug+2017&e=18+Aug+2017#c5468

**Closed by AutomatedTester** 2017-08-21 09:48 UTC
Labels: specification
