### ISSUE TITLE
Unable to start two sessions in sequence

### ISSUE THREAD

**Issue by davehunt** [mozilla/geckodriver#58] opened 2016-04-13 13:54 UTC
I've been trying to add Marionette support to the Selenium Docker images in https://github.com/SeleniumHQ/docker-selenium/pull/189 and have encountered an issue where after an initial session is created and deleted, any subsequent attempts to start a session fail. The initial wires process is successfully terminated, but each following failure to start a session orphans the wires process.

I found [this StackOverflow question](http://stackoverflow.com/questions/34510794/selenium-marionette-driver-unreachablebrowserexception-upon-second-launch), which concludes that randomizing the Marionette port solves the issue. This suggests that perhaps the port is not being properly released?

**Comment by andreastt** [comment] 2016-04-15 10:33
It does suggest that. Generally Mozilla automation is quite happy to use new ports, which could explain why this hasn’t surfaced. If it is the case that Gecko doesn’t release the port correctly, this is a Marionette bug.  I will try to investigate later today.

**Comment by LinuXperia** [comment] 2016-06-14 21:40
Hi all.
I have this Problem also. Tested it with Firefox Nightly and newest GeckoDriver 0.8 on Ubuntu Xenial.
I am also not able to run more than 1 Test using the Gecko/marionette Driver without to shutdown and restart Selenium everytime for a test. THis is very anoying.

Here is the Debug Log of Selenium when it fails on the second run.
Hope it can help to isolate the Problem.

`    First Test RUN Working
    ----------------------
     
    23:24:39.758 INFO - Executing: [new session: Capabilities [{nativeEvents=false, marionette=true, binary=firefox-trunk, browserName=firefox, javascriptEnabled=true, version=50.0a1}]])
    23:24:39.766 INFO - Creating a new session for Capabilities [{nativeEvents=false, marionette=true, binary=firefox-trunk, browserName=firefox, javascriptEnabled=true, version=50.0a1}]
    1465939480421	Marionette	DEBUG	Marionette enabled via build flag and pref
    1465939480880	Marionette	INFO	Listening on port 2828
    1465939482243	Marionette	DEBUG	Marionette enabled via command-line flag
    1465939482295	Marionette	DEBUG	Accepted connection conn0 from 127.0.0.1:50090
    1465939482402	Marionette	TRACE	conn0 -> [0,1,"newSession",{"capabilities":{"desiredCapabilities":{"binary":"firefox-trunk","browserName":"firefox","javascriptEnabled":true,"marionette":true,"nativeEvents":false,"version":"50.0a1"},"requiredCapabilities":{}},"sessionId":null}]
    1465939482403	Marionette	CONFIG	Changing capabilities: {"browserName":"Firefox","browserVersion":"50.0a1","platformName":"Linux","platformVersion":"4.4.0-24-generic","specificationLevel":0,"raisesAccessibilityExceptions":false,"rotatable":false,"acceptSslCerts":false,"takesElementScreenshot":true,"takesScreenshot":true,"proxy":{},"platform":"LINUX","XULappId":"{ec8030f7-c20a-464f-9b0e-13a3a9e97384}","appBuildId":"20160614030613","device":"desktop","version":"50.0a1","binary":"firefox-trunk","javascriptEnabled":true,"marionette":true,"nativeEvents":false}
    1465939483912	Marionette	INFO	startBrowser cc508a18-4452-45e4-a39b-5e0f578001b4
    1465939483918	Marionette	DEBUG	loaded listener.js
    1465939483921	Marionette	DEBUG	loaded listener.js
    1465939483922	Marionette	INFO	sendAsync cc508a18-4452-45e4-a39b-5e0f578001b4
    1465939484299	Marionette	TRACE	conn0 <- [1,1,null,{"sessionId":"cc508a18-4452-45e4-a39b-5e0f578001b4","capabilities":{"browserName":"Firefox","browserVersion":"50.0a1","platformName":"Linux","platformVersion":"4.4.0-24-generic","specificationLevel":0,"raisesAccessibilityExceptions":false,"rotatable":false,"acceptSslCerts":false,"takesElementScreenshot":true,"takesScreenshot":true,"proxy":{},"platform":"LINUX","XULappId":"{ec8030f7-c20a-464f-9b0e-13a3a9e97384}","appBuildId":"20160614030613","device":"desktop","version":"50.0a1","binary":"firefox-trunk","javascriptEnabled":true,"marionette":true,"nativeEvents":false,"command_id":1}}]
    23:24:44.329 INFO - Done: [new session: Capabilities [{nativeEvents=false, marionette=true, binary=firefox-trunk, browserName=firefox, javascriptEnabled=true, version=50.0a1}]]
    23:24:44.335 INFO - Executing: [get: http://moresearch.biz/news/])
    1465939484338	Marionette	TRACE	conn0 -> [0,2,"get",{"url":"http://moresearch.biz/news/"}]
    1465939484338	Marionette	INFO	sendAsync cc508a18-4452-45e4-a39b-5e0f578001b4
    1465939487765	Marionette	TRACE	conn0 <- [1,2,null,{}]
    23:24:47.767 INFO - Done: [get: http://moresearch.biz/news/]
     
     
     
    Closing First run Test
    ----------------------
     
    23:25:09.217 INFO - Executing: [delete session: 551a541d-3183-47a9-8bc9-800ede3fae4e])
    1465939509224	Marionette	TRACE	conn0 -> [0,3,"quitApplication",{"flags":["eForceQuit"]}]
    1465939509225	Marionette	TRACE	conn0 <- [1,3,null,{}]
    23:25:09.417 INFO - Done: [delete session: 551a541d-3183-47a9-8bc9-800ede3fae4e]
     
     
     
    Second Test Run Attept Fails always
    -----------------------------------
     
    23:26:23.255 INFO - Executing: [new session: Capabilities [{nativeEvents=false, marionette=true, binary=firefox-trunk, browserName=firefox, javascriptEnabled=true, version=50.0a1}]])
    23:26:23.256 INFO - Creating a new session for Capabilities [{nativeEvents=false, marionette=true, binary=firefox-trunk, browserName=firefox, javascriptEnabled=true, version=50.0a1}]
    23:26:23.261 WARN - Exception thrown
    java.util.concurrent.ExecutionException: org.openqa.selenium.WebDriverException: java.lang.reflect.InvocationTargetException
    Build info: version: '2.53.0', revision: '35ae25b', time: '2016-03-15 17:00:58'
    System info: host: 'Aspire-V3-772G', ip: '127.0.1.1', os.name: 'Linux', os.arch: 'amd64', os.version: '4.4.0-24-generic', java.version: '1.8.0_91'
    Driver info: driver.version: unknown
    	at java.util.concurrent.FutureTask.report(FutureTask.java:122)
    	at java.util.concurrent.FutureTask.get(FutureTask.java:192)
    	at org.openqa.selenium.remote.server.DefaultSession.execute(DefaultSession.java:183)
    	at org.openqa.selenium.remote.server.DefaultSession.<init>(DefaultSession.java:119)
    	at org.openqa.selenium.remote.server.DefaultSession.createSession(DefaultSession.java:95)
    	at org.openqa.selenium.remote.server.DefaultDriverSessions.newSession(DefaultDriverSessions.java:124)
    	at org.openqa.selenium.remote.server.handler.NewSession.handle(NewSession.java:59)
    	at org.openqa.selenium.remote.server.handler.NewSession.handle(NewSession.java:1)
    	at org.openqa.selenium.remote.server.rest.ResultConfig.handle(ResultConfig.java:111)
    	at org.openqa.selenium.remote.server.JsonHttpCommandHandler.handleRequest(JsonHttpCommandHandler.java:79)
    	at org.openqa.selenium.remote.server.DriverServlet.handleRequest(DriverServlet.java:204)
    	at org.openqa.selenium.remote.server.DriverServlet.doPost(DriverServlet.java:166)
    	at javax.servlet.http.HttpServlet.service(HttpServlet.java:707)
    	at org.openqa.selenium.remote.server.DriverServlet.service(DriverServlet.java:132)
    	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
    	at org.openqa.jetty.jetty.servlet.ServletHolder.handle(ServletHolder.java:428)
    	at org.openqa.jetty.jetty.servlet.ServletHandler.dispatch(ServletHandler.java:680)
    	at org.openqa.jetty.jetty.servlet.ServletHandler.handle(ServletHandler.java:571)
    	at org.openqa.jetty.http.HttpContext.handle(HttpContext.java:1526)
    	at org.openqa.jetty.http.HttpContext.handle(HttpContext.java:1479)
    	at org.openqa.jetty.http.HttpServer.service(HttpServer.java:920)
    	at org.openqa.jetty.http.HttpConnection.service(HttpConnection.java:820)
    	at org.openqa.jetty.http.HttpConnection.handleNext(HttpConnection.java:986)
    	at org.openqa.jetty.http.HttpConnection.handle(HttpConnection.java:837)
    	at org.openqa.jetty.http.SocketListener.handleConnection(SocketListener.java:243)
    	at org.openqa.jetty.util.ThreadedServer.handle(ThreadedServer.java:358)
    	at org.openqa.jetty.util.ThreadPool$PoolThread.run(ThreadPool.java:537)
    Caused by: org.openqa.selenium.WebDriverException: java.lang.reflect.InvocationTargetException
    Build info: version: '2.53.0', revision: '35ae25b', time: '2016-03-15 17:00:58'
    System info: host: 'Aspire-V3-772G', ip: '127.0.1.1', os.name: 'Linux', os.arch: 'amd64', os.version: '4.4.0-24-generic', java.version: '1.8.0_91'
    Driver info: driver.version: unknown
    	at org.openqa.selenium.remote.server.FirefoxDriverProvider.callConstructor(FirefoxDriverProvider.java:101)
    	at org.openqa.selenium.remote.server.FirefoxDriverProvider.newInstance(FirefoxDriverProvider.java:66)
    	at org.openqa.selenium.remote.server.DefaultDriverFactory.newInstance(DefaultDriverFactory.java:60)
    	at org.openqa.selenium.remote.server.DefaultSession$BrowserCreator.call(DefaultSession.java:222)
    	at org.openqa.selenium.remote.server.DefaultSession$BrowserCreator.call(DefaultSession.java:1)
    	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    	at org.openqa.selenium.remote.server.DefaultSession$1.run(DefaultSession.java:176)
    	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    	at java.lang.Thread.run(Thread.java:745)
    Caused by: java.lang.reflect.InvocationTargetException
    	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
    	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
    	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
    	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
    	at org.openqa.selenium.remote.server.FirefoxDriverProvider.callConstructor(FirefoxDriverProvider.java:91)
    	... 9 more
    Caused by: org.openqa.selenium.remote.UnreachableBrowserException: Could not start a new session. Possible causes are invalid address of the remote server or browser start-up failure.
    Build info: version: '2.53.0', revision: '35ae25b', time: '2016-03-15 17:00:58'
    System info: host: 'Aspire-V3-772G', ip: '127.0.1.1', os.name: 'Linux', os.arch: 'amd64', os.version: '4.4.0-24-generic', java.version: '1.8.0_91'
    Driver info: driver.version: MarionetteDriver
    	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:665)
    	at org.openqa.selenium.remote.RemoteWebDriver.startSession(RemoteWebDriver.java:249)
    	at org.openqa.selenium.remote.RemoteWebDriver.startSession(RemoteWebDriver.java:234)
    	at org.openqa.selenium.firefox.MarionetteDriver.run(MarionetteDriver.java:79)
    	at org.openqa.selenium.firefox.MarionetteDriver.<init>(MarionetteDriver.java:73)
    	at org.openqa.selenium.firefox.MarionetteDriver.<init>(MarionetteDriver.java:49)
    	... 14 more
    Caused by: org.openqa.selenium.WebDriverException: org.apache.http.conn.HttpHostConnectException: Connect to localhost:6696 [localhost/127.0.0.1] failed: Verbindungsaufbau abgelehnt
    Build info: version: '2.53.0', revision: '35ae25b', time: '2016-03-15 17:00:58'
    System info: host: 'Aspire-V3-772G', ip: '127.0.1.1', os.name: 'Linux', os.arch: 'amd64', os.version: '4.4.0-24-generic', java.version: '1.8.0_91'
    Driver info: driver.version: MarionetteDriver
    	at org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:91)
    	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:644)
    	... 19 more
    Caused by: org.apache.http.conn.HttpHostConnectException: Connect to localhost:6696 [localhost/127.0.0.1] failed: Verbindungsaufbau abgelehnt
    	at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:151)
    	at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:353)
    	at org.apache.http.impl.execchain.MainClientExec.establishRoute(MainClientExec.java:380)
    	at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:236)
    	at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:184)
    	at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:88)
    	at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:110)
    	at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:184)
    	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:71)
    	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:55)
    	at org.openqa.selenium.remote.internal.ApacheHttpClient.fallBackExecute(ApacheHttpClient.java:144)
    	at org.openqa.selenium.remote.internal.ApacheHttpClient.execute(ApacheHttpClient.java:90)
    	at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:142)
    	at org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:82)
    	... 20 more
    Caused by: java.net.ConnectException: Verbindungsaufbau abgelehnt
    	at java.net.PlainSocketImpl.socketConnect(Native Method)
    	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
    	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
    	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
    	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
    	at java.net.Socket.connect(Socket.java:589)
    	at org.apache.http.conn.socket.PlainConnectionSocketFactory.connectSocket(PlainConnectionSocketFactory.java:74)
    	at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:134)
    	... 33 more
    23:26:23.267 WARN - Exception: Verbindungsaufbau abgelehnt`

**Comment by jgraham** [comment] 2016-06-28 11:01
I think this was fixed by #112 Please reopen if this still doesn't work with master / the forthcoming 0.9.0.

**Closed by jgraham** 2016-06-28 11:01 UTC

**Comment by geloescht** [comment] 2016-07-04 09:25
I think I am still experiencing this bug on geckodriver v0.9. Keystone is using nightwatch and the first test in our test suite passes as expected, whereas the second one fails with the following error:
```
Connection refused! Is selenium server started?
{ sessionId: null,
  status: 13,
  state: 'unhandled error',
  value: 
   { message: 'Verbindungsaufbau abgelehnt',
     suppressed: [],
     localizedMessage: 'Verbindungsaufbau abgelehnt',
     cause: null,
     class: 'java.net.ConnectException',
     hCode: 1021439203,
     screen: null },
  class: 'org.openqa.selenium.remote.Response',
  hCode: 1746532665 }
```
Browser is Firefox 47.0, OS is Ubuntu 15.10, 64bit. 'Verbindungsaufbau abgelehnt' means 'connection rejected'.

**Comment by davehunt** [comment] 2016-07-04 10:19
This is failing for me with the currently Selenium standalone server release (2.53.1) most likely due to this not including this patch that waits for the GeckoDriver service to be running: https://github.com/SeleniumHQ/selenium/pull/2255/commits/2ebfea5852438202d5cc4de9a03e4a0b44606595. When I try the latest successful nightly build of Selenium (pre-3.0.beta) with GeckoDriver v0.9.0 this is working as expected. I'm going to see if we can uplift this change and release a new standalone server version.

**Comment by jesusmariajurado** [comment] 2016-07-19 08:46
For me is failing using 2.53.1, geckoDriver 0.9 in Ubuntu. But I found a solution here http://stackoverflow.com/questions/34510794/selenium-marionette-driver-unreachablebrowserexception-upon-second-launch thanks to http://stackoverflow.com/users/388827/qqilihq

**Comment by andreastt** [comment] 2016-07-20 13:12
@jesusmariajurado See @davehunt’s comment above.
