### ISSUE TITLE
pageLoadTimeout not working for Firefox browser in selenium

### ISSUE THREAD

**Issue by Suban5** [mozilla/geckodriver#1693] opened 2020-02-25 09:56 UTC
## System

* Version:  0.26.0
* Platform:  Linux
* Firefox: 73.0
* Selenium-java: 3.141.59

## Testcase
`driver.manage().timeouts().pageLoadTimeout(60, TimeUnit.SECONDS);
`
My codes works fine for Chromium Browser whereas in firefox, it doesn't wait for 60 sec pageLoadTimeout. It only waits for about 5sec.

For more information about the issue please [check this](https://stackoverflow.com/questions/60390926/pageloadtimeout-not-working-for-firefox-browser-in-selenium)

[main] INFO io.github.bonigarcia.wdm.WebDriverManager - Using geckodriver 0.26.0 (since Mozilla Firefox 73 is installed in your machine)
[main] INFO io.github.bonigarcia.wdm.WebDriverManager - Exporting webdriver.gecko.driver as /home/suban/.m2/repository/webdriver/geckodriver/linux64/0.26.0/geckodriver
1582624291449   mozrunner::runner       INFO    Running command: "/usr/lib/firefox/firefox" "-marionette" "-foreground" "-no-remote" "-profile" "/tmp/rust_mozprofile4nFa2u"
1582624291762   addons.webextension.doh-rollout@mozilla.org     WARN    Loading extension 'doh-rollout@mozilla.org': Reading manifest: Invalid extension permission: networkStatus
1582624292199   addons.webextension.screenshots@mozilla.org     WARN    Loading extension 'screenshots@mozilla.org': Reading manifest: Invalid extension permission: mozillaAddons
1582624292199   addons.webextension.screenshots@mozilla.org     WARN    Loading extension 'screenshots@mozilla.org': Reading manifest: Invalid extension permission: telemetry
1582624292200   addons.webextension.screenshots@mozilla.org     WARN    Loading extension 'screenshots@mozilla.org': Reading manifest: Invalid extension permission: resource://pdf.js/
1582624292200   addons.webextension.screenshots@mozilla.org     WARN    Loading extension 'screenshots@mozilla.org': Reading manifest: Invalid extension permission: about:reader*
1582624293876   Marionette      INFO    Listening on port 34145
1582624293958   Marionette      WARN    TLS certificate errors will be ignored for this session
Feb 25, 2020 3:36:34 PM org.openqa.selenium.remote.ProtocolHandshake createSession
INFO: Detected dialect: W3C

**Comment by whimboo** [comment] 2020-02-25 10:17
Could you please attach a [trace-level log] from geckodriver? Read more about reporting actionable bugs in our [contribution guidelines].

[trace-level log]: https://firefox-source-docs.mozilla.org/testing/geckodriver/TraceLogs.html
[contribution guidelines]: https://firefox-source-docs.mozilla.org/testing/geckodriver/Bugs.html

**Comment by Suban5** [comment] 2020-02-25 10:34
[logtrace.txt](https://github.com/mozilla/geckodriver/files/4249458/logtrace.txt)
place find my log here

**Comment by whimboo** [comment] 2020-02-25 13:08
I assume that you mean the page load activity as triggered by clicking the button with the xpath "//button[contains(text(),'CHECK SCORE')]"? As it looks like the click didn't cause any navigation to happen:

```
1582626594372   Marionette      DEBUG   0 -> [0,64,"WebDriver:ElementClick",{"id":"0444f561-e081-4796-8725-c4d79a571187"}]
1582626594393   Marionette      TRACE   [15] Received DOM event beforeunload for http://ec2-3-92-183-150.compute-1.amazonaws.com:7070/resume-upload-jd-text
1582626599598   Marionette      DEBUG   [15] Canceled page load listener because no navigation has been detected
```

Does the page have a `beforeunload` handler set, and did you modify any preference to force-enabling those beforeunload alerts?

**Comment by whimboo** [comment] 2020-02-25 13:09
Btw. this might be similar or even a dupe of issue #1675.

**Comment by Suban5** [comment] 2020-02-26 05:13
We are are not using `beforeunload` handler set.

**Comment by whimboo** [comment] 2020-02-26 09:49
So note that something is blocking the page from being unloaded. That within 5s after the `beforeunload` event has been fired. So please observe what happens when clicking this button. 

Would you be able to provide a testcase for reproduction?

**Comment by Suban5** [comment] 2020-02-26 11:41
I found out the following codes are used  for the browser:

```
window.onbeforeunload = function () {
        $('textarea').each(function () {
            var id = $(this).attr('id');
            var value = $(this).val();
            localStorage.setItem(id, value);
        });
    };
    window.onload = function () {
        $('textarea').each(function () {
            var id = $(this).attr('id');
            var text2 = localStorage.getItem(id);
            if (text2 !== null) $('#' + id).val(text2);
        });
    };
```
Can you tell me the solution? The same code works fine for chromium browser

**Comment by whimboo** [comment] 2020-04-16 05:47
@Suban5 do the examples here might help you to get it working in Firefox?

https://developer.mozilla.org/en-US/docs/Web/API/WindowEventHandlers/onbeforeunload#Example

**Comment by Naumansh** [comment] 2020-04-27 21:15
I am facing the same issue on firefox browser where page loading is still in progress and the click happens from selenium but its not executed actually as the Dom is still rendering the UI.

Firefox : 75
OS: mac os

This thing never happens on chrome or IE.

**Comment by whimboo** [comment] 2020-06-03 05:11
@Naumansh it's unlikely that you hit the exact same issue. Especially hard to tell because you haven't given any information like website, or example script. I would suggest you file a new issue and also provide a trace log as suggested there. Thanks.

**Comment by whimboo** [comment] 2020-09-23 08:47
No further reply from @Suban5 within a couple of months. Closing the issue.

**Closed by whimboo** 2020-09-23 08:47 UTC
Labels: awaiting reporter feedback
