### ISSUE TITLE
geckodriver 0.18 - file upload fails with *file not found*

### ISSUE THREAD

**Issue by rsuciu-gsg** [mozilla/geckodriver#880] opened 2017-08-17 14:36 UTC
## System
* Version: 0.18.0
* Platform: Mac OS X Sierra, MacBook Pro (Retina, 15-inch, Mid 2015)
* Firefox: 55.0.2 (64bit)
* Selenium: 3.4.3, Python binding

## Testcase
Using Behave 1.2.5, Selenium 3.4.3, Python bindings, I am trying to upload a file to my web app, by providing the full path for the file to be uploaded.
Although the path is correct, and this has been working in previous geckodriver versions, I am now having issues with this scenario, as the error received is *      selenium.common.exceptions.WebDriverException: Message: File not found: /Users/user/work/app/acceptance/data/resume/Adam_C -pdf.pdf* The path is the correct one.

## Stacktrace

And I upload resume file with path "/../../data/resume/Adam_C -pdf.pdf"                      # connect/steps/submit_candidates_steps.py:23 0.038s
      Traceback (most recent call last):
        File "/Users/user/work/app/acceptance/virtualenv/lib/python3.5/site-packages/behave/model.py", line 1456, in run
          match.run(runner.context)
        File "/Users/user/work/app/acceptance/virtualenv/lib/python3.5/site-packages/behave/model.py", line 1903, in run
          self.func(context, *args, **kwargs)
        File "/Users/user/work/app/acceptance/connect/steps/submit_candidates_steps.py", line 25, in upload_resume
          SubmitCandidatePage(context).upload_resume(path)
        File "/Users/user/work/app/acceptance/connect/pages/submit_candidates.py", line 115, in upload_resume
          self.context.driver.find_element(*self._resume_input_selector).send_keys(os.path.abspath(relative_path))
        File "/Users/user/work/app/acceptance/virtualenv/lib/python3.5/site-packages/selenium/webdriver/remote/webelement.py", line 349, in send_keys
          'value': keys_to_typing(value)})
        File "/Users/user/work/app/acceptance/virtualenv/lib/python3.5/site-packages/selenium/webdriver/remote/webelement.py", line 493, in _execute
          return self._parent.execute(command, params)
        File "/Users/user/work/app/acceptance/virtualenv/lib/python3.5/site-packages/selenium/webdriver/remote/webdriver.py", line 256, in execute
          self.error_handler.check_response(response)
        File "/Users/user/work/app/acceptance/virtualenv/lib/python3.5/site-packages/selenium/webdriver/remote/errorhandler.py", line 194, in check_response
          raise exception_class(message, screen, stacktrace)
      selenium.common.exceptions.WebDriverException: Message: File not found: /Users/user/work/app/acceptance/data/resume/Adam_C -pdf.pdf

**Comment by andreastt** [comment] 2017-08-17 18:34
Duplicate of https://github.com/mozilla/geckodriver/issues/858.

**Closed by andreastt** 2017-08-17 18:34 UTC
