### ISSUE TITLE
Firefox Ver 52.0.2 Crashes on Windows Server 2012 R2 Standard when  Driver.Quit() method is invoked by GeckoDriver 0.15.0.4

### ISSUE THREAD

**Issue by rtpd01** [mozilla/geckodriver#650] opened 2017-04-14 23:12 UTC
## Firefox Version
Firefox version 52.0.2 (32-bit) or 52.0.1 (32-bit), or 52.0 (32-bit)

## Platform
Windows Server 2012 R2 Standard

## Steps to reproduce -
1.	Run a test on Firefox version 52.0.2, or 52.0.1, or 52.0 on Windows Server 2012 R2 Standard
2.	Assume the test is running through the end
3.	Notice at the end of the test when Firefox is closed, The following Crash error message appears on screen and Task Manager shows Firefox and it is not closed properly.

![firefox crash](https://cloud.githubusercontent.com/assets/23105124/25058327/13094ff8-212d-11e7-91ae-53139d42788a.png)

NOTE:  This issue is reproducible on Windows Server 2012 R2, Therefore we cannot execute our tests on Firefox browser and need a fix ASAP.
Thanks in advance.

**Comment by AidanMcD** [comment] 2017-04-18 08:56
This is happening for me too.
see https://github.com/SeleniumHQ/selenium/issues/3822

**Comment by inzerion** [comment] 2017-04-19 13:06
Same crash on Windows R2 2008 Geckodriver 0.15.0, FF 52.0.2, Selenium 3.3.1

**Comment by hazmeister** [comment] 2017-04-20 13:21
Potential workaround: have you tried enabling automatic error reporting?
![image](https://cloud.githubusercontent.com/assets/11080542/25232819/a4989efa-25d4-11e7-8563-095e058b358d.png)

**Comment by rtpd01** [comment] 2017-04-20 23:18
Tried to disable by selecting "I don't want to participate, and don't ask me again", but still getting same  crash error "Firefox has stopped working".  So we still don't have a solution..

**Comment by hazmeister** [comment] 2017-04-21 06:07
I haven't tried with gecko yet, but for the old driver I opted in at the highest level (send report to Microsoft ) and the prompt would disappear after the upload.

**Comment by whimboo** [comment] 2017-04-21 06:29
No one on this issue actually provided the trace logs which are mentioned in the template when creating a new issue. So it's hard to say what's going on.

But I suspect this is a dupe of issue #285, and should not appear anymore with the last beta release of Firefox 54.0.

If that is not the case please provide a tracelog for Firefox 54.0 and we can reopen the issue. Thanks.

**Closed by whimboo** 2017-04-21 06:29 UTC

**Comment by TheRobOne** [comment] 2017-04-27 08:46
Same here with Selenium 3.4.0 and Firefox 52.0, Windows Server 2008 R2 Enterprise.
There is now output in the console because test finished with success anyway.

**Comment by andreastt** [comment] 2017-04-27 22:45
@TheRobOne “Me too” comments are not useful. See https://github.com/mozilla/geckodriver/issues/650#issuecomment-296090991 and try to provide concise information that lets us reproduce it instead.

**Comment by Nitrokitty** [comment] 2017-09-01 18:33
Redirect from https://github.com/mozilla/geckodriver/issues/639#issuecomment-326255433

> Further could you try using the latest Nightly build of Firefox and check if the crash for Quit still persists? Build can be found here: https://www.mozilla.org/en-US/firefox/channel/desktop/

I downloaded the nightly FF build (v57.0a1) on all servers and it is no longer crashing on driver.Quit(). However, if I encounter a selenium error while executing a test, the driver.Quit() method will not close the browser. For example, we use the following code to extend FindElements:
```
public static ReadOnlyCollection<IWebElement> FindElements(this IWebDriver driver, By by, int timeoutInSeconds)
		{
			if (timeoutInSeconds > 0)
			{				
				// Set the global wait setting
				driver.Manage().Timeouts().ImplicitWait = TimeSpan.FromSeconds(timeoutInSeconds);

				var elements = driver.FindElements(by);

				// Reset the global wait setting
				driver.Manage().Timeouts().ImplicitWait = TimeSpan.FromSeconds(timeoutInSeconds);

				return elements;
			}

			return driver.FindElements(by);
		}
```

Setting the implicit wait throws an exception in FF: `System.InvalidOperationException: timeouts` with this stack trace: 

![image](https://user-images.githubusercontent.com/15735852/29982788-1fa2b512-8f21-11e7-8016-086b0fcf58cf.png)
I assume this is a geckodriver issue so I'll post a ticket with them. However, we always call driver.Quit() before ending all of our tests (in the finally block after trying to execute the test and catching the error). When we call driver.Quit() on tests that have failed due to the previous exception, the browser will not close but I do see that the geckodriver has closed.

> So there are several things to mention here... First, if there is a content crash in Firefox which seems to have happened here we mostly hang for a while until Firefox gets killed by geckodriver. Can you please check if that is the case for you? With bug 1388249 being fixed for the next geckodriver release we will shutdown Firefox immediately.

I do not see the content crashes anymore after raising the browserTimeout but my previously stated problem might be related.

> I would suggest that you give feedback on issue #650. Thanks.

Here ya go! :)

**Comment by andreastt** [comment] 2017-09-01 20:07
@Nitrokitty I’m glad to hear `driver.quit()` has been fixed for you. I think your timeouts issue is the same as https://github.com/mozilla/geckodriver/issues/913.

**Comment by whimboo** [comment] 2017-09-05 13:25
> I downloaded the nightly FF build (v57.0a1) on all servers and it is no longer crashing on driver.Quit(). 

@Nitrokitty could you also test the latest Firefox 56.0 beta? It would be good to know if it's even working there. Thanks.
