### ISSUE TITLE
Failed close and Firefox crash when using quit

### ISSUE THREAD

**Issue by kumaralok444** [mozilla/geckodriver#173] opened 2016-08-11 06:47 UTC
Environment:- win 7, selenium 3.0.0 beta, Firefox48
Issue 1:-
command:- driver.close();

Expected Result:- browser should close.
Actual Result:- Browser is not closing.

Issue 2:-
command:- driver.quit();
Expected Result:- browser should close.
Actual Result:- Firefox crashed.

Plz reply me.

**Comment by AutomatedTester** [comment] 2016-08-11 23:06
I was able to recreate the browser not closing bug but I can't for the Firefox Crashed. 

Please can you give a much better bug report so that we can try reproduce.

**Comment by kumaralok444** [comment] 2016-08-12 03:37
I am pasting the code here plz have a look
Environment:- geckodriver-v0.10.0-win64, Firefox version 48, Webdriver version 3.0.0 beta, win 7
public class Test1 {
	public static void main(String args[])
	{
		
		System.setProperty("webdriver.gecko.driver", "D:\\Alok\\jar\\geckodriver-v0.10.0-win64\\geckodriver.exe");
		WebDriver driver=new FirefoxDriver();
		driver.get("https://github.com/mozilla/geckodriver/issues/173");
		try
		{
		driver.close();
		}
		catch(Error e)
		{
			System.out.println(e);
		}
	}
while i am running this code browser is opening the url but its not closing.

**Comment by andreastt** [comment] 2016-08-12 13:19
This is still a pretty terrible issue report. I cannot reproduce it either. Can you be more specific as to _what output_ you’re actually seeing? What error messages are you getting?

Can you try reproducing this and attaching the log from stdout when giving geckodriver the `-vv` flag for more verbose logs?

**Comment by kumaralok444** [comment] 2016-08-13 08:17
OK here is code in TestNg along with output its showing as all test pass but its not closing browser and for that its not producing any config error.
code:
public class Test1 {
	WebDriver driver;
		@BeforeTest
		public void setUp()
		{
		System.setProperty("webdriver.gecko.driver", "D:\\Alok\\jar\\geckodriver-v0.10.0-win64\\geckodriver.exe");
		driver=new FirefoxDriver();
		}
		@Test
		public void testCase1()
		{
		driver.get("https://github.com/mozilla/geckodriver/issues/173");
		}
		@AfterTest
		public void tearDown()
		{
		driver.close();
		}
}

Output:-
[TestRunner] Running the tests in 'myTest' with parallel mode:false
[RunInfo] Adding method selector: org.testng.internal.XmlMethodSelector@1a2ca36 priority: 10
[TestClass] Creating TestClass for [ClassImpl class=gecko.Test1]
[TestNG] Running:
  D:\JavaPractise\laxmiPackage\gecko\src\gecko\Test1.xml

[SuiteRunner] Created 1 TestRunners
[TestRunner] Running test myTest on 1  classes,  included groups:[] excluded groups:[]
===== Test class
gecko.Test1
    @Test Test1.testCase1()[pri:0, instance:gecko.Test1@cff1a]
======
[Invoker 5044175] Invoking @BeforeTest Test1.setUp()[pri:0, instance:gecko.Test1@cff1a]
1471076043507	Marionette	INFO	Listening on port 2663
1471076046139	Marionette	INFO	startBrowser 0ae5f385-9da8-451b-abb6-e48fb1208d26
1471076046151	Marionette	INFO	sendAsync 0ae5f385-9da8-451b-abb6-e48fb1208d26
[Invoker 5044175] Invoking gecko.Test1.testCase1
1471076046581	Marionette	INFO	sendAsync 0ae5f385-9da8-451b-abb6-e48fb1208d26
1471076046714	Marionette	INFO	sendAsync 0ae5f385-9da8-451b-abb6-e48fb1208d26
[Invoker 5044175] Invoking @AfterTest Test1.tearDown()[pri:0, instance:gecko.Test1@cff1a]
===== Invoked methods
  Test1.setUp()[pri:0, instance:gecko.Test1@cff1a] 851738
    Test1.testCase1()[pri:0, instance:gecko.Test1@cff1a] 851738
  Test1.tearDown()[pri:0, instance:gecko.Test1@cff1a] 851738
=====
Creating D:\JavaPractise\laxmiPackage\gecko\test-output\MySuite\myTest.html
Creating D:\JavaPractise\laxmiPackage\gecko\test-output\MySuite\myTest.xml
PASSED: testCase1

===============================================
    myTest
    Tests run: 1, Failures: 0, Skips: 0
===============================================


===============================================
MySuite
Total tests run: 1, Failures: 0, Skips: 0
===============================================

[TestNG] Time taken by org.testng.reporters.XMLReporter@1e18270: 8 ms
Creating D:\JavaPractise\laxmiPackage\gecko\test-output\junitreports\TEST-gecko.Test1.xml
[TestNG] Time taken by org.testng.reporters.JUnitReportReporter@103f852: 5 ms
Creating D:\JavaPractise\laxmiPackage\gecko\test-output\old\MySuite\toc.html
Creating D:\JavaPractise\laxmiPackage\gecko\test-output\old\MySuite\myTest.properties
Creating D:\JavaPractise\laxmiPackage\gecko\test-output\old\MySuite\index.html
Creating D:\JavaPractise\laxmiPackage\gecko\test-output\old\MySuite\main.html
Creating D:\JavaPractise\laxmiPackage\gecko\test-output\old\MySuite\groups.html
Creating D:\JavaPractise\laxmiPackage\gecko\test-output\old\MySuite\methods.html
Creating D:\JavaPractise\laxmiPackage\gecko\test-output\old\MySuite\methods.html
Creating D:\JavaPractise\laxmiPackage\gecko\test-output\old\MySuite\methods.html
Creating D:\JavaPractise\laxmiPackage\gecko\test-output\old\MySuite\methods.html
Creating D:\JavaPractise\laxmiPackage\gecko\test-output\old\MySuite\methods.html
Creating D:\JavaPractise\laxmiPackage\gecko\test-output\old\MySuite\methods-alphabetical.html
Creating D:\JavaPractise\laxmiPackage\gecko\test-output\old\MySuite\methods-alphabetical.html
Creating D:\JavaPractise\laxmiPackage\gecko\test-output\old\MySuite\methods-alphabetical.html
Creating D:\JavaPractise\laxmiPackage\gecko\test-output\old\MySuite\methods-alphabetical.html
Creating D:\JavaPractise\laxmiPackage\gecko\test-output\old\MySuite\methods-alphabetical.html
Creating D:\JavaPractise\laxmiPackage\gecko\test-output\old\MySuite\classes.html
Creating D:\JavaPractise\laxmiPackage\gecko\test-output\old\MySuite\reporter-output.html
Creating D:\JavaPractise\laxmiPackage\gecko\test-output\old\MySuite\methods-not-run.html
Creating D:\JavaPractise\laxmiPackage\gecko\test-output\old\MySuite\testng.xml.html
Creating D:\JavaPractise\laxmiPackage\gecko\test-output\old\index.html
[TestNG] Time taken by org.testng.reporters.SuiteHTMLReporter@41e737: 25 ms
[TestNG] Time taken by [FailedReporter passed=0 failed=0 skipped=0]: 0 ms
[TestNG] Time taken by org.testng.reporters.EmailableReporter2@ceda24: 6 ms
[TestNG] Time taken by org.testng.reporters.jq.Main@a35978: 27 ms

**Comment by andreastt** [comment] 2016-08-13 19:13
Closing this because not enough information was provided to investigate the issue and because we are unable to reproduce it. Will consider re-opening if the information requested above is provided.

**Closed by andreastt** 2016-08-13 19:13 UTC

**Comment by SaurTrip** [comment] 2016-09-24 17:59
I am facing this same issue when I use Quit method Firefox crashes. My BaseTest.java is mentioned below 👍 package com.xxx.scripts;

import java.util.concurrent.TimeUnit;

import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.firefox.FirefoxProfile;
import org.openqa.selenium.firefox.internal.ProfilesIni;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.testng.annotations.AfterMethod;
import org.testng.annotations.AfterSuite;
import org.testng.annotations.BeforeMethod;
import org.testng.annotations.BeforeSuite;

public class BaseTest {

	public WebDriver driver;
	
	
	@BeforeMethod
	public void setUp(){
		

		System.setProperty("webdriver.gecko.driver", "C:/Users/Saurabh/Downloads/geckodriver-v0.10.0-win64/geckodriver.exe");
		driver = new FirefoxDriver();
		driver.get("http://localhost/login.do");
		driver.manage().window().maximize();
		driver.manage().timeouts().implicitlyWait(45, TimeUnit.SECONDS);
	}
	
	@AfterMethod
	public void tearDown(){
		driver.quit();
	}
	
}
![error](https://cloud.githubusercontent.com/assets/11586709/18810240/af056c3e-82ae-11e6-8854-90b7093625d3.png)

**Comment by andreastt** [comment] 2016-09-26 12:04
@SaurTrip Your stacktrace indicates you are hitting https://github.com/mozilla/geckodriver/issues/210, which was solved in Firefox 49 and later. You should try again with Nightly.

**Comment by fallenreaper** [comment] 2016-09-29 15:03
i was having an issue which seems like it is related.  You can see a post I put together by way of StackOverflow.  http://stackoverflow.com/questions/39772902/firefox-driver-fails-and-gets-an-unreachable-error 

Right now I am on 47.1 and it is saying that firefox is up to date.  It seems to have issues as well with closing / quitting.  Do you have a site i could go to, to get into the firefox 49+ ?  Also, upgrading the browser doesnt seem to be the best resolution for this use case, is there a way to resolve this within code and still close the browser?  I could wrap it with a try{}catch and supress it, but i would slowly accumulate browsers.

**Comment by andreastt** [comment] 2016-09-29 17:33
@fallenreaper Yes you do: https://nightly.mozilla.org/

**Comment by idubinets** [comment] 2016-10-23 15:36
I have same issue in FF 49.0.2

**Comment by rowee55** [comment] 2016-10-29 18:49
I'm seeing the same issue with FF 49.0.2.6136

Problem signature:
  Problem Event Name:	APPCRASH
  Application Name:	plugin-container.exe
  Application Version:	49.0.2.6136
  Application Timestamp:	5807c043
  Fault Module Name:	mozglue.dll
  Fault Module Version:	49.0.2.6136
  Fault Module Timestamp:	5807b9a7
  Exception Code:	80000003
  Exception Offset:	0000e83e
  OS Version:	6.1.7601.2.1.0.272.7
  Locale ID:	1033
  Additional Information 1:	0a9e
  Additional Information 2:	0a9e372d3b4ad19135b953a78882e789
  Additional Information 3:	0a9e
  Additional Information 4:	0a9e372d3b4ad19135b953a78882e789

Read our privacy statement online:
  http://go.microsoft.com/fwlink/?linkid=104288&clcid=0x0409

If the online privacy statement is not available, please read our privacy statement offline:
  C:\Windows\system32\en-US\erofflps.txt

**Comment by AKMANN** [comment] 2016-11-25 13:13
i have Firefox V50.0 and i am also facing the similar issue where firefox crashes when we invoke driver.quit.
I tried calling Webdriver and RemoteWebDriver using gecko and in both case my Browser crashed.

problem Details as per Firefox crash pop-up.
Problem Event Name:	APPCRASH
  Application Name:	firefox.exe
  Application Version:	50.0.0.6152
  Application Timestamp:	581d78ba
  Fault Module Name:	mozglue.dll
  Fault Module Version:	50.0.0.6152
  Fault Module Timestamp:	581d788d
  Exception Code:	80000003
  Exception Offset:	0000ed40
  OS Version:	6.1.7601.2.1.0.256.48
  Locale ID:	1033
  Additional Information 1:	0a9e
  Additional Information 2:	0a9e372d3b4ad19135b953a78882e789
  Additional Information 3:	0a9e
  Additional Information 4:	0a9e372d3b4ad19135b953a78882e789

**Comment by Muggler2k** [comment] 2016-11-28 17:45
I'm having the same problem with FireFox 48,49 and 50

**Comment by kamau-asim** [comment] 2016-11-30 14:55
I am also having the same issue. I am using Windows 8, Firefox 50, GeckoDriver 11.1, and the v3.0.1 version of the Selenium Nuget package.  Code sample below:

`using (IWebDriver driver = new FirefoxDriver())
 {
                //do testing work....
  }`

When the using statement completes, and Dispose is called on 'driver' (equivalent to calling 'driver.close' or 'driver.quit' , Firefox throws an exception and does not close. The exception is as follows:

The exception Breakpoint.
A breakpoint has been reached.
(0x80000003) occurred in the application at location 0x5414ed40.

**Comment by simonlebonbon** [comment] 2016-12-01 00:02
I am getting the exact same as @kamau-asim  We upgraded our test vm's to the same spec and get the breakpoint reached error when we do a Dispose() of the driver

**Comment by andreastt** [comment] 2016-12-01 10:47
Locking this thread because of the many “me too” comments.
