### ISSUE TITLE
Geckodriver crashing with WebDriverException: Failed to find width field 

### ISSUE THREAD

**Issue by ykulkarni** [mozilla/geckodriver#826] opened 2017-07-13 16:23 UTC
If I switch back to geckodriver-v0.16.1 this is not reproducible.

## Platform and application details
* Platform: Window 10 1607
* Firefox: 54.0.1
* Selenium: 3.4.0

## Steps to reproduce
Execute simple test case below - 

	@Test
	public void maxWindowTest() throws MalformedURLException {
		URL server = new URL("http://127.0.0.1:4444/wd/hub");
		System.setProperty("webdriver.gecko.driver", WINDOWS_GECKO_DRIVER_PATH);
		FirefoxProfile profile = new FirefoxProfile();

		DesiredCapabilities capabilities = DesiredCapabilities.firefox();
		capabilities.setCapability(FirefoxDriver.PROFILE, profile);

		WebDriver driver = new RemoteWebDriver(server, capabilities);

		driver.get("http://www.google.com");
		driver.manage().window().maximize();
	}

- [ ] A trace level log:
Caused by: org.openqa.selenium.WebDriverException: Failed to find width field
Build info: version: '3.4.0', revision: 'unknown', time: 'unknown'
System info: host: 'KVMAUTO-OS-1', ip: 'xxxxxxxxxx', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_131'
Driver info: org.openqa.selenium.firefox.FirefoxDriver
Capabilities [{moz:profile=C:\Users\SUPERU~1\AppData\Local\Temp\rust_mozprofile.CqosM4FPvB6q, rotatable=false, timeouts={implicit=0.0, pageLoad=300000.0, script=30000.0}, pageLoadStrategy=normal, platform=ANY, specificationLevel=0.0, moz:accessibilityChecks=false, acceptInsecureCerts=true, browserVersion=54.0.1, platformVersion=10.0, moz:processID=7208.0, browserName=firefox, javascriptEnabled=true, platformName=windows_nt}]
Session ID: 40ad7bc6-3a31-4f6a-8dff-77c38cf1cf6f
Build info: version: 'unknown', revision: 'unknown', time: 'unknown'
System info: host: 'US-H2CGR72', ip: '10.9.116.210', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_92'
Driver info: driver.version: RemoteWebDriver
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
	at java.lang.reflect.Constructor.newInstance(Unknown Source)
	at org.openqa.selenium.remote.http.W3CHttpResponseCodec.createException(W3CHttpResponseCodec.java:150)
	at org.openqa.selenium.remote.http.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:115)
	at org.openqa.selenium.remote.http.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:45)
	at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:164)
	at org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:82)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:637)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:694)
	at org.openqa.selenium.remote.RemoteWebDriver$RemoteWebDriverOptions$RemoteWindow.maximize(RemoteWebDriver.java:925)
	at org.openqa.selenium.support.events.EventFiringWebDriver$EventFiringWindow.maximize(EventFiringWebDriver.java:641)
	at org.openqa.selenium.remote.server.handler.MaximizeWindow.call(MaximizeWindow.java:30)
	at org.openqa.selenium.remote.server.handler.MaximizeWindow.call(MaximizeWindow.java:22)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at org.openqa.selenium.remote.server.DefaultSession$1.run(DefaultSession.java:176)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)

**Comment by andreastt** [comment] 2017-07-13 16:25
Duplicate of https://github.com/mozilla/geckodriver/issues/820.

The tl;dr is that you need to upgrade to Firefox 55 or greater.

**Closed by andreastt** 2017-07-13 16:25 UTC
