### ISSUE TITLE
zombie processes left over after many `webDriver.get`'s on docker

### ISSUE THREAD

**Issue by nddipiazza** [mozilla/geckodriver#1200] opened 2018-03-06 03:11 UTC
## System

* Version: 0.19.1
* Platform: Docker version 17.05.0-ce, build 89658be, Running `openjdk:8u151-jdk` docker image
* Firefox: 57.0.1
* Selenium: 3.5.3

## Testcase

Start N threads where in each thread you:
1) Start up a geckodriver service
2) Start up a firefox driver using this geckodriver.
3) Do several thousand `webDriver.get(url)`
4) close the web driver.

Notice tons of zombie firefox `Web Content` processes:

```
root      5438  0.0  0.0      0     0 ?        Z+   Mar05   0:00 [Web Content] <defunct>
root      6035  0.0  0.0      0     0 ?        Z+   Mar05   0:00 [Web Content] <defunct>
root      6603  1.0  0.0      0     0 ?        Z+   Mar05   2:18 [Web Content] <defunct>
root      6848  0.9  0.0      0     0 ?        Z+   Mar05   2:13 [Web Content] <defunct>
root      6990  1.0  0.0      0     0 ?        Z+   Mar05   2:14 [Web Content] <defunct>
root      7147  1.0  0.0      0     0 ?        Z+   Mar05   2:15 [Web Content] <defunct>
root      7315  1.0  0.0      0     0 ?        Z+   Mar05   2:17 [Web Content] <defunct>
root      7459  0.9  0.0      0     0 ?        Z+   Mar05   2:13 [Web Content] <defunct>
root      7604  1.0  0.0      0     0 ?        Z+   Mar05   2:14 [Web Content] <defunct>
root      7745  0.9  0.0      0     0 ?        Z+   Mar05   2:13 [Web Content] <defunct>
root      7888  1.0  0.0      0     0 ?        Z+   Mar05   2:14 [Web Content] <defunct>
root      8029  1.0  0.0      0     0 ?        Z+   Mar05   2:14 [Web Content] <defunct>
root      8562  1.0  0.0      0     0 ?        Z+   Mar05   2:16 [Web Content] <defunct>
root      8831  1.0  0.0      0     0 ?        Z+   Mar05   2:16 [Web Content] <defunct>
root      8971  1.0  0.0      0     0 ?        Z+   Mar05   2:14 [Web Content] <defunct>
root      9111  1.0  0.0      0     0 ?        Z+   Mar05   2:14 [Web Content] <defunct>
root      9266  1.0  0.0      0     0 ?        Z+   Mar05   2:13 [Web Content] <defunct>
root      9431  0.9  0.0      0     0 ?        Z+   Mar05   2:12 [Web Content] <defunct>
root      9570  0.9  0.0      0     0 ?        Z+   Mar05   2:12 [Web Content] <defunct>
root      9716  1.0  0.0      0     0 ?        Z+   Mar05   2:13 [Web Content] <defunct>
root      9865  1.0  0.0      0     0 ?        Z+   Mar05   2:12 [Web Content] <defunct>
root     10006  0.9  0.0      0     0 ?        Z+   Mar05   2:12 [Web Content] <defunct>
root     13465  0.0  0.0  19956  3592 ?        Ss   03:03   0:00 /bin/bash
root     14228  0.0  0.0  38384  3108 ?        R+   03:05   0:00 ps aux
root     19322  0.9  0.0      0     0 ?        Z+   Mar05   1:57 [Web Content] <defunct>
root     19578  0.9  0.0      0     0 ?        Z+   Mar05   1:56 [Web Content] <defunct>
root     19753  0.9  0.0      0     0 ?        Z+   Mar05   1:57 [Web Content] <defunct>
root     19893  0.9  0.0      0     0 ?        Z+   Mar05   1:56 [Web Content] <defunct>
root     20037  0.9  0.0      0     0 ?        Z+   Mar05   1:55 [Web Content] <defunct>
root     20185  0.9  0.0      0     0 ?        Z+   Mar05   1:56 [Web Content] <defunct>
root     20328  0.9  0.0      0     0 ?        Z+   Mar05   1:56 [Web Content] <defunct>
root     20472  0.9  0.0      0     0 ?        Z+   Mar05   1:57 [Web Content] <defunct>
root     20612  1.0  0.0      0     0 ?        Z+   Mar05   1:57 [Web Content] <defunct>
root     20769  0.9  0.0      0     0 ?        Z+   Mar05   1:57 [Web Content] <defunct>
```

Anyone else see that?

**Comment by nddipiazza** [comment] 2018-03-06 14:11
I'm trying also to kill the processes in that manner as well but not having any success. 
Thanks for the tip about getCapability! that's awesome!

**Comment by andreastt** [comment] 2018-03-06 14:19
I can’t reproduce this. Do you have a reproducible test case?

**Comment by nddipiazza** [comment] 2018-03-06 14:21
Let me whip something up.

**Comment by soumyababy81** [comment] 2018-03-06 17:18
Example for the zombie process being piled up in task manager can happen when the driver.close or driver.quit doesn't work as expected, as explained with scenarios and test examples detailed in the following issue https://github.com/mozilla/geckodriver/issues/1146. These scenarios were many in our tests and we had to figure out a work around to kill the processes especially.

**Comment by whimboo** [comment] 2018-03-06 22:23
@nddipiazza it would be good if you could run a test with a debug version of Firefox Nightly, and trace logs enabled. That should give us quiet a bit of information to figure out what could be wrong. Such a build can be found at https://queue.taskcluster.net/v1/task/AEzPBfYYRxmZOv9vRCF87g/runs/0/artifacts/public/build/target.tar.bz2. Just untar the archive and the build is ready to be used.

**Comment by nddipiazza** [comment] 2018-03-07 14:43
@whimboo ok. i tried to pull the relevant code into a "reproducer" but have so far been unable to recreate this with the reproducer program. so it's something to do with my program possibly. and i'm already using the nightly build 60.0a. 

i think this problem may be related to the hacks needed to work around https://github.com/mozilla/geckodriver/issues/947 not being good enough.

**Comment by whimboo** [comment] 2018-03-07 17:41
Maybe something changed on that affected system?

**Comment by nddipiazza** [comment] 2018-04-07 15:32
@whimboo i'm pretty sure this issue is due to not enough memory/not enough cpus. It was hard to reproduce on a local machine because i have so many cpu's/memory on my local machine. On the cloud where those are at a premium it was easier to see.

**Comment by nddipiazza** [comment] 2018-04-07 15:32
either way can probably close this out.

**Comment by whimboo** [comment] 2018-04-09 06:50
Ok, thanks. In case you see it again a trace log of a debug build of Firefox would be nice to have, and we could reopen the issue. Until then lots close it.

**Closed by whimboo** 2018-04-09 06:50 UTC
Labels: waiting for reporter feedback

**Comment by ssethy** [comment] 2018-11-09 06:56
We have been facing this problem since a long causing our test cases to hang and consume lot of time to complete. Some time it times out as well. Selenium doesn't launch new firefox browser until i go and kill the existing browser process with a zombie process. 

[root@<hostname>]# ps -aef | grep firefox
root      1560  1357  0 22:02 pts/0    00:00:00 grep --color=auto firefox
root     23904 18518  0 19:06 ?        00:00:00 /root/<packagename>/src/test/resources/drivers/linux/geckodriver --port=8642 -b /usr/local/firefox/firefox
root     23918 23904  0 19:06 ?        00:00:31 [firefox] <defunct>
[root@<hostname>]# kill -9 23918
[root@<hostname>]# ps -aef | grep firefox
root      1644  1357  0 22:02 pts/0    00:00:00 grep --color=auto firefox
root     23904 18518  0 19:06 ?        00:00:00 /root/<packagename>/src/test/resources/drivers/linux/geckodriver --port=8642 -b /usr/local/firefox/firefox
root     23918 23904  0 19:06 ?        00:00:31 [firefox] <defunct>
[root@<hostname>]# kill -9 23904
[root@<hostname>]# ps -aef | grep firefox
root      1726 18518  1 22:03 ?        00:00:00 /root/<packagename>/src/test/resources/drivers/linux/geckodriver --port=19254 -b /usr/local/firefox/firefox
root      1739  1726 72 22:03 ?        00:00:00 /usr/local/firefox/firefox -marionette -foreground -no-remote -profile /tmp/rust_mozprofile.i2okripqUYui
root      1824  1357  0 22:03 pts/0    00:00:00 grep --color=auto firefox
You have new mail in /var/spool/mail/root

**Comment by whimboo** [comment] 2018-11-09 11:35
@ssethy did you notice that this issue has been closed? If you want to get some investigation and fix happen please file your own one, and provide all the requested details. Thanks.
