### ISSUE TITLE
Geckodriver freezes after closing a popup window

### ISSUE THREAD

**Issue by PascalGit1** [mozilla/geckodriver#818] opened 2017-07-11 13:51 UTC
**Platform: Windows 7
Firefox: 53
Selenium: 3.4.0
Geckodriver 0.18 (tried previous versions aswell)**

When i close a popup window using window.close it freezes the driver and i cannot perform :
driver.switchTo().window(parentWindowHandler);
To get back to the main window

Error log:
```
499780716017	geckodriver	INFO	geckodriver 0.18.0
1499780716026	geckodriver	INFO	Listening on 127.0.0.1:40600
1499780718742	Marionette	WARN	TLS certificate errors will be ignored for this session
jul 11, 2017 3:45:18 PM org.openqa.selenium.remote.ProtocolHandshake createSession
INFO: Detected dialect: W3C
are we in?
2147483652
2147483666
[GPU 8300] WARNING: pipe error: 109: file c:/builds/moz2_slave/m-rel-w64-00000000000000000000/build/src/ipc/chromium/src/chrome/common/ipc_channel_win.cc, line 346
[GPU 8300] WARNING: pipe error: 109: file c:/builds/moz2_slave/m-rel-w64-00000000000000000000/build/src/ipc/chromium/src/chrome/common/ipc_channel_win.cc, line 346
[Child 9624] WARNING: pipe error: 109: file c:/builds/moz2_slave/m-rel-w64-00000000000000000000/build/src/ipc/chromium/src/chrome/common/ipc_channel_win.cc, line 346
[Child 9624] WARNING: pipe error: 109: file c:/builds/moz2_slave/m-rel-w64-00000000000000000000/build/src/ipc/chromium/src/chrome/common/ipc_channel_win.cc, line 346
Tried to run command without establishing a connection
Build info: version: '3.4.0', revision: 'unknown', time: 'unknown'
System info: host: 'LTPLA102016', ip: '192.168.50.114', os.name: 'Windows 7', os.arch: 'amd64', os.version: '6.1', java.version: '1.8.0_111'
Driver info: org.openqa.selenium.firefox.FirefoxDriver
Capabilities [{moz:profile=C:\Users\PASCAL~1.VAN\AppData\Local\Temp\rust_mozprofile.NAIywkJSmJt5, rotatable=false, timeouts={implicit=0.0, pageLoad=300000.0, script=30000.0}, pageLoadStrategy=normal, platform=ANY, specificationLevel=0.0, moz:accessibilityChecks=false, acceptInsecureCerts=true, browserVersion=53.0, platformVersion=6.1, moz:processID=10776.0, browserName=firefox, javascriptEnabled=true, platformName=windows_nt}]
Session ID: a5fe29af-9ab1-4777-933a-2860b2609516
Failure in after hook:DriverHelper.ShutDown()
Message: org.openqa.selenium.SessionNotCreatedException: Tried to run command without establishing a connection
Build info: version: '3.4.0', revision: 'unknown', time: 'unknown'
System info: host: 'LTPLA102016', ip: '192.168.50.114', os.name: 'Windows 7', os.arch: 'amd64', os.version: '6.1', java.version: '1.8.0_111'
Driver info: org.openqa.selenium.firefox.FirefoxDriver
Capabilities [{moz:profile=C:\Users\PASCAL~1.VAN\AppData\Local\Temp\rust_mozprofile.NAIywkJSmJt5, rotatable=false, timeouts={implicit=0.0, pageLoad=300000.0, script=30000.0}, pageLoadStrategy=normal, platform=ANY, specificationLevel=0.0, moz:accessibilityChecks=false, acceptInsecureCerts=true, browserVersion=53.0, platformVersion=6.1, moz:processID=10776.0, browserName=firefox, javascriptEnabled=true, platformName=windows_nt}]
```

**Comment by andreastt** [comment] 2017-07-11 14:38
Did you try this with Firefox nightly as well?

**Comment by PascalGit1** [comment] 2017-07-11 14:42
I have tried with Firefox nightly before although not recently, but the issue was there

**Comment by andreastt** [comment] 2017-07-11 15:02
We don’t develop against Firefox 53 anymore because it is an old Firefox version. All development happens against the HEAD of the tree, from which Firefox Nightly is built. It is always a good idea to report bugs having tested against the most recent version.

If you could test against Firefox Nightly and attach a trace-level log that would be most appreciated.

**Comment by suvendu2016** [comment] 2017-07-12 06:40
Platform: Windows 10
Firefox: 54.0.1
Selenium: 3.4.0
Geckodriver 0.18

Faced the same issue as PascalGit1 described as above with FF v54.0.1

**Comment by PascalGit1** [comment] 2017-07-12 08:25
Tried it both on nightly and latest version of firefox now and still the same problem occurs

```
1499847845334	geckodriver	INFO	geckodriver 0.18.0
1499847845341	geckodriver	INFO	Listening on 127.0.0.1:38795
1499847849200	Marionette	WARN	TLS certificate errors will be ignored for this session
jul 12, 2017 10:24:09 AM org.openqa.selenium.remote.ProtocolHandshake createSession
INFO: Detected dialect: W3C
[GPU 9968] WARNING: pipe error: 109: file c:/builds/moz2_slave/m-rel-w32-00000000000000000000/build/src/ipc/chromium/src/chrome/common/ipc_channel_win.cc, line 346
[GPU 9968] WARNING: pipe error: 109: file c:/builds/moz2_slave/m-rel-w32-00000000000000000000/build/src/ipc/chromium/src/chrome/common/ipc_channel_win.cc, line 346
Tried to run command without establishing a connection
Build info: version: '3.4.0', revision: 'unknown', time: 'unknown'
System info: host: 'LTPLA102016', ip: '192.168.50.114', os.name: 'Windows 7', os.arch: 'amd64', os.version: '6.1', java.version: '1.8.0_111'
Driver info: org.openqa.selenium.firefox.FirefoxDriver
Capabilities [{moz:profile=C:\Users\PASCAL~1.VAN\AppData\Local\Temp\rust_mozprofile.mpVy5gpvlpUa, rotatable=false, timeouts={implicit=0.0, pageLoad=300000.0, script=30000.0}, pageLoadStrategy=normal, platform=ANY, specificationLevel=0.0, moz:accessibilityChecks=false, acceptInsecureCerts=true, browserVersion=53.0.2, platformVersion=6.1, moz:processID=11736.0, browserName=firefox, javascriptEnabled=true, platformName=windows_nt}]
Session ID: d40b2f92-887c-45e3-a10c-95bd8971e22e
jul 12, 2017 10:24:48 AM org.openqa.selenium.os.UnixProcess destroy
SEVERE: Unable to kill process with PID 13180
Failure in after hook:DriverHelper.ShutDown()
```

**Comment by andreastt** [comment] 2017-07-12 10:44
According to your latest paste, you were still using Firefox 53: `browserVersion=53.0.2`

**Comment by PascalGit1** [comment] 2017-07-12 13:10
Weird i see it to, but it did start up firefox Nightly, let me see why it did that

**Comment by PascalGit1** [comment] 2017-07-18 09:06
These are the methods i use to switch to popup, while using chrome i have no problems:

```
public void getWindow() {
		Set<String> handles = driver.getWindowHandles(); // get all window handles
		Iterator<String> iterator = handles.iterator();
		parentWindowHandler = iterator.next(); // The parent window is the top window
		while (iterator.hasNext()) {
			subWindowHandler = iterator.next();
		}
	}

	@When("^switch to popup$")
	public void switch_to_popup() throws Throwable {
		TimeUnit.SECONDS.sleep(1);
		getWindow();
		driver.switchTo().window(subWindowHandler);
	}

	@When("^switch to mainwindow$")
	public void switch_to_mainwindow() throws Throwable {
		getWindow();
		driver.switchTo().window(parentWindowHandler);
	}
```

**Comment by andreastt** [comment] 2017-07-18 16:08
We don’t develop against 54 either. Any chance you can test with Nightly (56)? It would also be useful with a trace-level log.

**Comment by PascalGit1** [comment] 2017-07-19 11:17
> We don’t develop against 54 either. Any chance you can test with Nightly (56)? It would also be useful with a trace-level log.

Like i said it works on Nightly.
But i guess I shouldnt try and get it to work on 54

**Comment by whimboo** [comment] 2017-07-20 15:18
This is just another dupe of issue #611, which I fixed in Firefox Nightly (56).

**Closed by whimboo** 2017-07-20 15:18 UTC
Labels: waiting for reporter feedback

**Comment by Fenici** [comment] 2017-10-24 06:10
How to call firefox nightly in mac ?
