### ISSUE TITLE
driver.close() is not working for Firefox 50.0 with gecko driver. Kindly help

### ISSUE THREAD

**Issue by Darpan-Chatterjee** [mozilla/geckodriver#583] opened 2017-03-29 10:08 UTC
In order to help us efficiently investigate your issue, please provide the following information:

## Firefox Version
50.1.0

## Platform
Windows 7

## Steps to reproduce -
Selenium Stand Alone server 3.0.0 with gecko driver.

 - Open a browser and try to close the same using driver.close(). Browser is not closing.

**Comment by snpanigrahi9** [comment] 2017-03-30 04:53
Issue already open.

**Comment by andreastt** [comment] 2017-03-30 14:49
Suspect this is a duplicate of https://github.com/mozilla/geckodriver/issues/285 or https://github.com/mozilla/geckodriver/issues/225.

**Closed by andreastt** 2017-03-30 14:49 UTC
