### ISSUE TITLE
[geckodriver ver 0.21.0 ] ConnectionAbortedError: [WinError 10053]  after input the verify code by pressing "Enter" Key.

### ISSUE THREAD

**Issue by brianlaibaoqin** [mozilla/geckodriver#1324] opened 2018-07-09 16:20 UTC
## System

* Version:     ver 0.21.0 
* Platform:   win7  X64
* Firefox:   ver 61 X64 
* Selenium:    selenium  3.13.0

    url = "https://account.dji.com/register"
## Testcase

       
 self.driver.find_element_by_css_selector("#userLogin").click()
        sleep(1)
        self.driver.find_element_by_css_selector(".btn.create-btn.second.lg").click()
        sleep(1)
        self.driver.find_element_by_xpath("//*[@name='email']").send_keys(email)
        sleep(1)
        self.driver.find_element_by_xpath("//*[@class='md-input-container md-input-required']/input").send_keys(password)
        sleep(1)
        self.driver.find_element_by_xpath("//*[@name='emailConfirmPassword']").send_keys(password)
       varify_code = str(input("请手动输入注册的验证码字符串:" ))
        sleep(1)
        print(varify_code,type((varify_code)))
        self.driver.find_element_by_xpath(".//*[@id='app']/div/div/div/div/div[2]/div/div[3]/div/div[1]/div[4]/div/div/input").send_keys(varify_code)
        self.driver.find_element_by_css_selector(".btn.register-btn.primary.lg").click()

  

> `geckodriver`

 version  ver 0.21.0  can reproduce this issue ,but ver 0.20.0 has no this issue.

## Trace-level log

![image](https://user-images.githubusercontent.com/34622645/42462573-3fdc50ae-83d6-11e8-9ce3-89b2d1c3e7d2.png)
![image](https://user-images.githubusercontent.com/34622645/42462600-5253d4be-83d6-11e8-9160-b2598471435f.png)

**Comment by andreastt** [comment] 2018-07-09 16:50
Could you please attach a [trace-level log] from geckodriver? Read more about reporting actionable bugs in our [contribution guidelines].

[trace-level log]: https://searchfox.org/mozilla-central/source/testing/geckodriver/doc/TraceLogs.md
[contribution guidelines]: https://searchfox.org/mozilla-central/source/testing/geckodriver/CONTRIBUTING.md#reporting-bugs

**Comment by brianlaibaoqin** [comment] 2018-07-10 02:01
[geckodriver.log](https://github.com/mozilla/geckodriver/files/2178582/geckodriver.log)

![image](https://user-images.githubusercontent.com/34622645/42484977-1cd2a52a-8428-11e8-8058-96ad63f640f4.png)

**Comment by brianlaibaoqin** [comment] 2018-07-10 02:02
![image](https://user-images.githubusercontent.com/34622645/42485016-5223432e-8428-11e8-8bd0-bf209a3e4ef0.png)
![image](https://user-images.githubusercontent.com/34622645/42485030-59fadd32-8428-11e8-9c8a-dba0355f6dfc.png)

**Comment by andreastt** [comment] 2018-07-10 10:59
@brianlaibaoqin I’m sorry but that’s not a trace-level log. See documentation on https://searchfox.org/mozilla-central/source/testing/geckodriver/doc/TraceLogs.md on how to increase the logging verbosity.

**Comment by Mattwmaster58** [comment] 2018-07-17 21:04
@brianlaibaoqin 
To set log level to trace with python selenium specifically use this little snippet:
~~~~~
options = webdriver.FirefoxOptions()
options.log.level = 'trace'
drv = webdriver.Firefox(options=options)
~~~~~

**Comment by whimboo** [comment] 2018-07-24 19:29
Well the log from 15 days ago shows the following:

> 1531187922781	Marionette	ERROR	No reply from Marionette:Register
> Unable to read VR Path Registry from C:\Users\o-brian.lai\AppData\Local\openvr\openvrpaths.vrpath
> JavaScript error: chrome://marionette/content/listener.js, line 464: TypeError: reply[0] is undefined

There is something wrong with the registration of the listener framescript, but I doubt this is related to the underlying issue here. 

So I think that this is basically a dupe of issue #1305.

**Closed by whimboo** 2018-07-24 19:29 UTC
Labels: waiting for reporter feedback
