### ISSUE TITLE
Should be able to access pages using URL credentials

### ISSUE THREAD

**Issue by shs96c** [mozilla/geckodriver#519] opened 2017-03-08 18:09 UTC
Firefox Version: 52.0
Platform: OS X

## Steps to reproduce -
In Java, but similar steps for other languages:

``
WebDriver driver = new FirefoxDriver();
// Encode user credentials in URL and access a page with BASIC auth
driver.get("http://user:pass@example.com");
``

Tests using geckodriver (0.15) ask for confirmation of whether to access the page using this user name.

**Comment by nithinvv** [comment] 2017-03-09 11:53
Update the selenium webdriver to 3.3.0.it is working fine

**Comment by shs96c** [comment] 2017-03-09 15:55
I'm the author of the Selenium 3.3.0 bindings. I assure you, it's not working fine.

**Comment by nithinvv** [comment] 2017-03-09 16:01
I faced an  issue that browser is not navigating to the url after updating
the selenium to 3.3.0.Then i have updated the geckodriver 15.now browser is
navigating to the url..

**Comment by jgraham** [comment] 2017-03-09 16:22
https://bugzilla.mozilla.org/show_bug.cgi?id=1280448

**Comment by andreastt** [comment] 2017-03-09 21:43
Duplicate of https://github.com/mozilla/geckodriver/issues/273.

**Closed by andreastt** 2017-03-09 21:43 UTC
Labels: marionette
