### ISSUE TITLE
click/submit do not trgger a page load

### ISSUE THREAD

**Issue by q-jack** [mozilla/geckodriver#1090] opened 2017-12-05 09:53 UTC
## System
* Version: geckodriver 0.19.1
* Platform: windows 10 64-bit
* Firefox: 57.0.1 (32-bit)
* Selenium: selenium standalone server 3.8.1

## Testcase

I am using the php webdriver lib [steward](https://github.com/lmc-eu/steward) for selenium test.
I have the issue when testing with firefox when submitting a form (via a click or via a submit) firefox does not load the redirected page. The event was firing but it seems like the request have been canceled and the next command failed because the html element is missing, due to not changing the webpage.
I tried implicid and explicid wait but that do not work.
It is working when i open the inspection tool while performing a test and navigate to network and then press on persist logs. It may seem like a timeout problem.

## Trace-level log

```
1512467250024   Marionette      INFO    Listening on port 61859
1512467250543   Marionette      DEBUG   Register listener.js for window 4294967297
10:47:30.576 INFO - Detected dialect: W3C
10:47:30.597 INFO - Done: [new session: Capabilities {browserName: firefox, firefox_profile: UEsDBBQAAAAAAOxVhUuBK46tKgA..., name: My\CreateStudyTest::testCre..., platform: ANY, requiredCapabilities: []}]
10:47:30.627 INFO - Executing: [set window size])
10:47:32.736 INFO - Done: [set window size]
10:47:32.741 INFO - Executing: [get: http://localhost/portal/de/])
1512467252747   Marionette      DEBUG   Received DOM event "beforeunload" for "about:blank"
1512467252979   Marionette      DEBUG   Received DOM event "pagehide" for "about:blank"
1512467252980   Marionette      DEBUG   Received DOM event "unload" for "about:blank"
1512467253142   Marionette      DEBUG   Received DOM event "DOMContentLoaded" for "http://localhost/portal/de/"
1512467253167   Marionette      DEBUG   Received DOM event "pageshow" for "http://localhost/portal/de/"
10:47:33.173 INFO - Done: [get: http://localhost/portal/de/]
10:47:33.179 INFO - Executing: [find element: By.id: UserUsername])
10:47:33.207 INFO - Done: [find element: By.id: UserUsername]
10:47:33.217 INFO - Executing: [send keys: 0 [[FirefoxDriver: firefox on XP (b56f7f81-b8c9-4203-88a7-b3da0d6d838d)] -> id: UserUsername], [tester]])
10:47:33.254 INFO - Done: [send keys: 0 [[FirefoxDriver: firefox on XP (b56f7f81-b8c9-4203-88a7-b3da0d6d838d)] -> id: UserUsername], [tester]]
10:47:33.256 INFO - Executing: [find element: By.id: UserPassword])
10:47:33.266 INFO - Done: [find element: By.id: UserPassword]
10:47:33.270 INFO - Executing: [send keys: 1 [[FirefoxDriver: firefox on XP (b56f7f81-b8c9-4203-88a7-b3da0d6d838d)] -> id: UserPassword], [test1234]])
10:47:33.292 INFO - Done: [send keys: 1 [[FirefoxDriver: firefox on XP (b56f7f81-b8c9-4203-88a7-b3da0d6d838d)] -> id: UserPassword], [test1234]]
10:47:33.294 INFO - Executing: [find element: By.className: full-width])
10:47:33.301 INFO - Done: [find element: By.className: full-width]
10:47:33.305 INFO - Executing: [click: 2 [[FirefoxDriver: firefox on XP (b56f7f81-b8c9-4203-88a7-b3da0d6d838d)] -> class name: full-width]])
1512467253325   Marionette      DEBUG   Received DOM event "beforeunload" for "http://localhost/portal/de/"
1512467254345   DeferredSave.webext.sc.lz4      DEBUG   Starting write
1512467254352   DeferredSave.webext.sc.lz4      DEBUG   Write succeeded
1512467254450   Marionette      DEBUG   Received DOM event "pagehide" for "http://localhost/portal/de/"
1512467254452   Marionette      DEBUG   Received DOM event "unload" for "http://localhost/portal/de/"
1512467254674   Marionette      DEBUG   Received DOM event "DOMContentLoaded" for "http://localhost/portal/de/studies/index"
1512467254813   Marionette      DEBUG   Received DOM event "pageshow" for "http://localhost/portal/de/studies/index"
10:47:34.817 INFO - Done: [click: 2 [[FirefoxDriver: firefox on XP (b56f7f81-b8c9-4203-88a7-b3da0d6d838d)] -> class name: full-width]]
10:47:34.822 INFO - Executing: [find element: By.cssSelector: #side-menu])
10:47:34.840 INFO - Done: [find element: By.cssSelector: #side-menu]
10:47:34.848 INFO - Executing: [is displayed: 3 [[FirefoxDriver: firefox on XP (b56f7f81-b8c9-4203-88a7-b3da0d6d838d)] -> css selector: #side-menu]])
10:47:34.900 INFO - Done: [is displayed: 3 [[FirefoxDriver: firefox on XP (b56f7f81-b8c9-4203-88a7-b3da0d6d838d)] -> css selector: #side-menu]]
10:47:34.903 INFO - Executing: [get current url])
10:47:34.913 INFO - Done: [get current url]
10:47:34.918 INFO - Executing: [find elements: By.className: cake-error])
10:47:34.929 INFO - Done: [find elements: By.className: cake-error]
10:47:34.934 INFO - Executing: [find elements: By.className: error])
10:47:34.946 INFO - Done: [find elements: By.className: error]
10:47:34.951 INFO - Executing: [find element: By.className: newStudy])
10:47:34.963 INFO - Done: [find element: By.className: newStudy]
10:47:34.965 INFO - Executing: [click: 4 [[FirefoxDriver: firefox on XP (b56f7f81-b8c9-4203-88a7-b3da0d6d838d)] -> class name: newStudy]])
1512467255012   Marionette      DEBUG   Received DOM event "beforeunload" for "http://localhost/portal/de/studies/index"
1512467255161   Marionette      DEBUG   Received DOM event "pagehide" for "http://localhost/portal/de/studies/index"
1512467255163   Marionette      DEBUG   Received DOM event "unload" for "http://localhost/portal/de/studies/index"
1512467255516   Marionette      DEBUG   Received DOM event "DOMContentLoaded" for "http://localhost/portal/de/studies/add"
1512467255516   Marionette      DEBUG   Received observer notification "outer-window-destroyed" for "4294967302"
1512467255516   Marionette      DEBUG   Received observer notification "outer-window-destroyed" for "4294967303"
1512467255542   Marionette      DEBUG   Received DOM event "pageshow" for "http://localhost/portal/de/studies/add"
10:47:35.547 INFO - Done: [click: 4 [[FirefoxDriver: firefox on XP (b56f7f81-b8c9-4203-88a7-b3da0d6d838d)] -> class name: newStudy]]
10:47:35.548 INFO - Executing: [get current url])
10:47:35.559 INFO - Done: [get current url]
10:47:35.563 INFO - Executing: [find elements: By.className: cake-error])
10:47:35.573 INFO - Done: [find elements: By.className: cake-error]
10:47:35.575 INFO - Executing: [find elements: By.className: error])
10:47:35.586 INFO - Done: [find elements: By.className: error]
10:47:35.590 INFO - Executing: [find element: By.id: StudyTitle])
10:47:35.599 INFO - Done: [find element: By.id: StudyTitle]
10:47:35.602 INFO - Executing: [find element: By.cssSelector: .panel-body])
10:47:35.609 INFO - Done: [find element: By.cssSelector: .panel-body]
10:47:35.612 INFO - Executing: [send keys: 5 [[FirefoxDriver: firefox on XP (b56f7f81-b8c9-4203-88a7-b3da0d6d838d)] -> id: StudyTitle], [1st testStudy]])
10:47:35.644 INFO - Done: [send keys: 5 [[FirefoxDriver: firefox on XP (b56f7f81-b8c9-4203-88a7-b3da0d6d838d)] -> id: StudyTitle], [1st testStudy]]
10:47:35.646 INFO - Executing: [send keys: 6 [[FirefoxDriver: firefox on XP (b56f7f81-b8c9-4203-88a7-b3da0d6d838d)] -> css selector: .panel-body], [This is an automatic generated test study]])
10:47:35.773 INFO - Done: [send keys: 6 [[FirefoxDriver: firefox on XP (b56f7f81-b8c9-4203-88a7-b3da0d6d838d)] -> css selector: .panel-body], [This is an automatic generated test study]]
10:47:35.775 INFO - Executing: [find element: By.id: addStudy])
10:47:35.786 INFO - Done: [find element: By.id: addStudy]
10:47:35.788 INFO - Executing: [click: 7 [[FirefoxDriver: firefox on XP (b56f7f81-b8c9-4203-88a7-b3da0d6d838d)] -> id: addStudy]])
1512467255847   Marionette      DEBUG   Received DOM event "beforeunload" for "http://localhost/portal/de/studies/add"
1512467256316   Marionette      DEBUG   Received DOM event "pagehide" for "http://localhost/portal/de/studies/add"
1512467256318   Marionette      DEBUG   Received DOM event "unload" for "http://localhost/portal/de/studies/add"
1512467256529   Marionette      DEBUG   Received DOM event "DOMContentLoaded" for "http://localhost/portal/de/studies/editElements/1290364751"
1512467256531   Marionette      DEBUG   Received DOM event "pageshow" for "http://localhost/portal/de/studies/editElements/1290364751"
10:47:36.533 INFO - Done: [click: 7 [[FirefoxDriver: firefox on XP (b56f7f81-b8c9-4203-88a7-b3da0d6d838d)] -> id: addStudy]]
10:47:36.535 INFO - Executing: [get current url])
10:47:36.538 INFO - Done: [get current url]
10:47:36.540 INFO - Executing: [find elements: By.className: cake-error])
10:47:36.550 INFO - Done: [find elements: By.className: cake-error]
10:47:36.553 INFO - Executing: [find elements: By.className: error])
10:47:36.577 INFO - Done: [find elements: By.className: error]
10:47:36.580 INFO - Executing: [find element: By.cssSelector: .add-Elmnt-click])
10:47:36.602 INFO - Done: [find element: By.cssSelector: .add-Elmnt-click]
10:47:36.606 INFO - Executing: [is displayed: 8 [[FirefoxDriver: firefox on XP (b56f7f81-b8c9-4203-88a7-b3da0d6d838d)] -> css selector: .add-Elmnt-click]])
10:47:36.632 INFO - Done: [is displayed: 8 [[FirefoxDriver: firefox on XP (b56f7f81-b8c9-4203-88a7-b3da0d6d838d)] -> css selector: .add-Elmnt-click]]
10:47:36.636 INFO - Executing: [find elements: By.className: add-Elmnt-click])
10:47:36.648 INFO - Done: [find elements: By.className: add-Elmnt-click]
10:47:36.650 INFO - Executing: [click: 8 [[FirefoxDriver: firefox on XP (b56f7f81-b8c9-4203-88a7-b3da0d6d838d)] -> css selector: .add-Elmnt-click]])
1512467256879   Marionette      DEBUG   Canceled page load listener because no navigation has been detected
10:47:36.882 INFO - Done: [click: 8 [[FirefoxDriver: firefox on XP (b56f7f81-b8c9-4203-88a7-b3da0d6d838d)] -> css selector: .add-Elmnt-click]]
10:47:36.884 INFO - Executing: [find element: By.id: addText])
10:47:36.891 INFO - Done: [find element: By.id: addText]
10:47:36.893 INFO - Executing: [click: 9 [[FirefoxDriver: firefox on XP (b56f7f81-b8c9-4203-88a7-b3da0d6d838d)] -> id: addText]])
1512467256920   Marionette      DEBUG   Received DOM event "beforeunload" for "http://localhost/portal/de/studies/editElements/1290364751"
1512467257064   Marionette      DEBUG   Received DOM event "pagehide" for "http://localhost/portal/de/studies/editElements/1290364751"
1512467257066   Marionette      DEBUG   Received DOM event "unload" for "http://localhost/portal/de/studies/editElements/1290364751"
1512467257413   Marionette      DEBUG   Received DOM event "DOMContentLoaded" for "http://localhost/portal/de/Texts/add/1290364751?position=0"
1512467257415   Marionette      DEBUG   Received DOM event "pageshow" for "http://localhost/portal/de/Texts/add/1290364751?position=0"
10:47:37.421 INFO - Done: [click: 9 [[FirefoxDriver: firefox on XP (b56f7f81-b8c9-4203-88a7-b3da0d6d838d)] -> id: addText]]
10:47:37.422 INFO - Executing: [get current url])
10:47:37.427 INFO - Done: [get current url]
10:47:37.429 INFO - Executing: [find elements: By.className: cake-error])
10:47:37.439 INFO - Done: [find elements: By.className: cake-error]
10:47:37.442 INFO - Executing: [find elements: By.className: error])
10:47:37.448 INFO - Done: [find elements: By.className: error]
10:47:37.450 INFO - Executing: [find element: By.cssSelector: .panel-body])
10:47:37.460 INFO - Done: [find element: By.cssSelector: .panel-body]
10:47:37.462 INFO - Executing: [send keys: 10 [[FirefoxDriver: firefox on XP (b56f7f81-b8c9-4203-88a7-b3da0d6d838d)] -> css selector: .panel-body], [This is the first element, which was generated automaticaly]])
10:47:37.631 INFO - Done: [send keys: 10 [[FirefoxDriver: firefox on XP (b56f7f81-b8c9-4203-88a7-b3da0d6d838d)] -> css selector: .panel-body], [This is the first element, which was generated automaticaly]]
10:47:37.634 INFO - Executing: [find element: By.id: TextButtonText])
10:47:37.640 INFO - Done: [find element: By.id: TextButtonText]
10:47:37.642 INFO - Executing: [clear: 11 [[FirefoxDriver: firefox on XP (b56f7f81-b8c9-4203-88a7-b3da0d6d838d)] -> id: TextButtonText]])
10:47:37.656 INFO - Done: [clear: 11 [[FirefoxDriver: firefox on XP (b56f7f81-b8c9-4203-88a7-b3da0d6d838d)] -> id: TextButtonText]]
10:47:37.658 INFO - Executing: [send keys: 11 [[FirefoxDriver: firefox on XP (b56f7f81-b8c9-4203-88a7-b3da0d6d838d)] -> id: TextButtonText], [GO ON]])
10:47:37.674 INFO - Done: [send keys: 11 [[FirefoxDriver: firefox on XP (b56f7f81-b8c9-4203-88a7-b3da0d6d838d)] -> id: TextButtonText], [GO ON]]
10:47:37.677 INFO - Executing: [find element: By.cssSelector: #saveText])
10:47:37.686 INFO - Done: [find element: By.cssSelector: #saveText]
10:47:37.689 INFO - Executing: [click: 12 [[FirefoxDriver: firefox on XP (b56f7f81-b8c9-4203-88a7-b3da0d6d838d)] -> css selector: #saveText]])
1512467257919   Marionette      DEBUG   Canceled page load listener because no navigation has been detected
10:47:37.922 INFO - Done: [click: 12 [[FirefoxDriver: firefox on XP (b56f7f81-b8c9-4203-88a7-b3da0d6d838d)] -> css selector: #saveText]]
10:47:37.924 INFO - Executing: [find elements: By.cssSelector: .add-Elmnt-click])
10:47:37.933 INFO - Done: [find elements: By.cssSelector: .add-Elmnt-click]
10:47:37.936 INFO - Executing: [get current url])
10:47:37.940 INFO - Done: [get current url]
10:47:37.942 INFO - Executing: [take screenshot])
10:47:38.014 INFO - Done: [take screenshot]
10:47:38.021 INFO - Executing: [get page source])
10:47:38.040 INFO - Done: [get page source]
10:47:38.079 INFO - Executing: [close window])
10:47:38.181 INFO - Done: [close window]
10:47:38.184 INFO - Executing: [delete session: b56f7f81-b8c9-4203-88a7-b3da0d6d838d])
10:47:38.635 WARN - Exception thrown
org.openqa.selenium.SessionNotCreatedException: Tried to run command without establishing a connection
Build info: version: '3.8.1', revision: '6e95a6684b', time: '2017-12-01T19:05:32.194Z'
System info: host: 'KUICH_EYEVIDO', ip: '192.168.188.33', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_121'
Driver info: org.openqa.selenium.firefox.FirefoxDriver
Capabilities {acceptInsecureCerts: false, browserName: firefox, browserVersion: 57.0.1, javascriptEnabled: true, moz:accessibilityChecks: false, moz:headless: false, moz:processID: 16560, moz:profile: C:\Users\kuich\AppData\Loca..., moz:webdriverClick: false, pageLoadStrategy: normal, platform: XP, platformName: XP, platformVersion: 10.0, rotatable: false, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}}
Session ID: b56f7f81-b8c9-4203-88a7-b3da0d6d838d
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
        at java.lang.reflect.Constructor.newInstance(Unknown Source)
        at org.openqa.selenium.remote.http.W3CHttpResponseCodec.createException(W3CHttpResponseCodec.java:187)
        at org.openqa.selenium.remote.http.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:122)
        at org.openqa.selenium.remote.http.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:49)
        at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:164)
        at org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:83)
        at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:601)
        at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:658)
        at org.openqa.selenium.remote.RemoteWebDriver.quit(RemoteWebDriver.java:497)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.lang.reflect.Method.invoke(Unknown Source)
        at org.openqa.selenium.support.events.EventFiringWebDriver$2.invoke(EventFiringWebDriver.java:108)
        at com.sun.proxy.$Proxy6.quit(Unknown Source)
        at org.openqa.selenium.support.events.EventFiringWebDriver.quit(EventFiringWebDriver.java:206)
        at org.openqa.selenium.remote.server.handler.DeleteSession.call(DeleteSession.java:49)
        at org.openqa.selenium.remote.server.handler.DeleteSession.call(DeleteSession.java:28)
        at org.openqa.selenium.remote.server.handler.WebDriverHandler.handle(WebDriverHandler.java:41)
        at org.openqa.selenium.remote.server.rest.ResultConfig.handle(ResultConfig.java:112)
        at org.openqa.selenium.remote.server.JsonHttpCommandHandler.handleRequest(JsonHttpCommandHandler.java:191)
        at org.openqa.selenium.remote.server.DriverServlet.lambda$handleRequest$0(DriverServlet.java:261)
        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
        at java.util.concurrent.FutureTask.run(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.lang.Thread.run(Unknown Source)
10:47:38.638 WARN - Exception: Tried to run command without establishing a connection
Build info: version: '3.8.1', revision: '6e95a6684b', time: '2017-12-01T19:05:32.194Z'
System info: host: 'KUICH_EYEVIDO', ip: '192.168.188.33', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_121'
Driver info: org.openqa.selenium.firefox.FirefoxDriver
Capabilities {acceptInsecureCerts: false, browserName: firefox, browserVersion: 57.0.1, javascriptEnabled: true, moz:accessibilityChecks: false, moz:headless: false, moz:processID: 16560, moz:profile: C:\Users\kuich\AppData\Loca..., moz:webdriverClick: false, pageLoadStrategy: normal, platform: XP, platformName: XP, platformVersion: 10.0, rotatable: false, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}}
Session ID: b56f7f81-b8c9-4203-88a7-b3da0d6d838d
```

Is this an issue or am I doing something wrong. Is there a way to workaound?
In chrome it works.

**Comment by andreastt** [comment] 2017-12-05 11:38
Could you please attach a [trace-level log] from geckodriver? Read more about reporting actionable bugs in our [contribution guidelines]. It would also be useful if you tried reproducing with Firefox Nightly.

[trace-level log]: https://searchfox.org/mozilla-central/source/testing/geckodriver/doc/TraceLogs.md
[contribution guidelines]: https://searchfox.org/mozilla-central/source/testing/geckodriver/CONTRIBUTING.md#reporting-bugs

**Comment by q-jack** [comment] 2017-12-05 12:23
sorry but in my setup I can not set the log level to trace.
The above mentioned log is not helpful at all? 

> 10:47:37.689 INFO - Executing: [click: 12 [[FirefoxDriver: firefox on XP (b56f7f81-b8c9-4203-88a7-b3da0d6d838d)] -> css selector: #saveText]])
1512467257919   Marionette      DEBUG   Canceled page load listener because no navigation has been detected

What does this log mean?

Are there some guidlines how to reproduce with firefox nightly?

**Comment by andreastt** [comment] 2017-12-05 13:06
It’s all documented in the [contribution guidelines] and examples are found in the [trace-level log] document I linked to earlier.

[trace-level log]: https://searchfox.org/mozilla-central/source/testing/geckodriver/doc/TraceLogs.md
[contribution guidelines]: https://searchfox.org/mozilla-central/source/testing/geckodriver/CONTRIBUTING.md#reporting-bugs

**Comment by whimboo** [comment] 2017-12-05 15:58
@q-jack is the submission of the form delayed by maybe a registered event listener for `#safeText`? That is what I could imagine when I see that code. 

Btw. you also commented on issue #1026 which I think this issue is a dupe of.

**Comment by q-jack** [comment] 2017-12-05 16:05
Thank you for the link because in the contribution file which is shown when clicking on new issue(https://github.com/mozilla/geckodriver/blob/master/CONTRIBUTING.md) the trace log link is broken.

I am really trying to get the trace log but it is not so easy with the facebook/php-webdriver

**Comment by q-jack** [comment] 2017-12-06 09:04
I have a trace log.
Error appears when clicking on button with id saveText

```
09:55:52.278 INFO - Done: [send keys: 11 [[FirefoxDriver: firefox on XP (f9af1bb1-113c-459e-803c-231926e45293)] -> id: TextButtonText], [GO ON]]
09:55:52.281 INFO - Executing: [find element: By.cssSelector: #saveText])
1512550552282	webdriver::server	DEBUG	-> POST /session/f9af1bb1-113c-459e-803c-231926e45293/element {"value":"#saveText","using":"css selector"}
1512550552282	geckodriver::marionette	TRACE	-> 65:[0,31,"findElement",{"using":"css selector","value":"#saveText"}]
1512550552284	Marionette	TRACE	0 -> [0,31,"findElement",{"using":"css selector","value":"#saveText"}]
1512550552286	Marionette	TRACE	0 <- [1,31,null,{"value":{"element-6066-11e4-a52e-4f735466cecf":"e75f135c-0aaa-418e-9951-4dc4ee511619","ELEMENT":"e75f135c-0aaa-418e-9951-4dc4ee511619"}}]
1512550552285	geckodriver::marionette	TRACE	<- [1,31,null,{"value":{"element-6066-11e4-a52e-4f735466cecf":"e75f135c-0aaa-418e-9951-4dc4ee511619","ELEMENT":"e75f135c-0aaa-418e-9951-4dc4ee511619"}}]
1512550552285	webdriver::server	DEBUG	<- 200 OK {"value":{"element-6066-11e4-a52e-4f735466cecf":"e75f135c-0aaa-418e-9951-4dc4ee511619"}}
09:55:52.287 INFO - Done: [find element: By.cssSelector: #saveText]
09:55:52.288 INFO - Executing: [click: 12 [[FirefoxDriver: firefox on XP (f9af1bb1-113c-459e-803c-231926e45293)] -> css selector: #saveText]])
1512550552289	webdriver::server	DEBUG	-> POST /session/f9af1bb1-113c-459e-803c-231926e45293/element/e75f135c-0aaa-418e-9951-4dc4ee511619/click {"id":"e75f135c-0aaa-418e-9951-4dc4ee511619"}
1512550552290	geckodriver::marionette	TRACE	-> 67:[0,32,"clickElement",{"id":"e75f135c-0aaa-418e-9951-4dc4ee511619"}]
1512550552291	Marionette	TRACE	0 -> [0,32,"clickElement",{"id":"e75f135c-0aaa-418e-9951-4dc4ee511619"}]
1512550552505	Marionette	DEBUG	Canceled page load listener because no navigation has been detected
1512550552506	Marionette	TRACE	0 <- [1,32,null,{}]
1512550552505	geckodriver::marionette	TRACE	<- [1,32,null,{}]
1512550552505	webdriver::server	DEBUG	<- 200 OK {"value": {}}
09:55:52.507 INFO - Done: [click: 12 [[FirefoxDriver: firefox on XP (f9af1bb1-113c-459e-803c-231926e45293)] -> css selector: #saveText]]
09:55:52.508 INFO - Executing: [find elements: By.cssSelector: .add-Elmnt-click])
1512550552510	webdriver::server	DEBUG	-> POST /session/f9af1bb1-113c-459e-803c-231926e45293/elements {"value":".add-Elmnt-click","using":"css selector"}
1512550552510	geckodriver::marionette	TRACE	-> 73:[0,33,"findElements",{"using":"css selector","value":".add-Elmnt-click"}]
1512550552511	Marionette	TRACE	0 -> [0,33,"findElements",{"using":"css selector","value":".add-Elmnt-click"}]
1512550552514	Marionette	TRACE	0 <- [1,33,null,[]]
1512550552514	geckodriver::marionette	TRACE	<- [1,33,null,[]]
1512550552514	webdriver::server	DEBUG	<- 200 OK {"value":[]}
09:55:52.515 INFO - Done: [find elements: By.cssSelector: .add-Elmnt-click]
09:55:52.518 INFO - Executing: [get current url])
1512550552520	webdriver::server	DEBUG	-> GET /session/f9af1bb1-113c-459e-803c-231926e45293/url 
1512550552520	geckodriver::marionette	TRACE	-> 25:[0,34,"getCurrentUrl",{}]
1512550552522	Marionette	TRACE	0 -> [0,34,"getCurrentUrl",{}]
1512550552523	Marionette	TRACE	0 <- [1,34,null,{"value":"http://localhost/portal/de/Texts/add/282224306?position=0"}]
1512550552522	geckodriver::marionette	TRACE	<- [1,34,null,{"value":"http://localhost/portal/de/Texts/add/282224306?position=0"}]
1512550552523	webdriver::server	DEBUG	<- 200 OK {"value":"http://localhost/portal/de/Texts/add/282224306?position=0"}
09:55:52.523 INFO - Done: [get current url]
09:55:52.525 INFO - Executing: [take screenshot])
1512550552526	webdriver::server	DEBUG	-> GET /session/f9af1bb1-113c-459e-803c-231926e45293/screenshot 
1512550552527	geckodriver::marionette	TRACE	-> 64:[0,35,"takeScreenshot",{"full":false,"highlights":[],"id":null}]
1512550552528	Marionette	TRACE	0 -> [0,35,"takeScreenshot",{"full":false,"highlights":[],"id":null}]
1512550552583	Marionette	TRACE	0 <- [1,35,null,{"value":"iVBORw0KGgoAAAANSUhEUgAABPQAAAOvCAYAAABLV5rVAAAgAElEQVR4nOy96VcU56K37ff3P3jOWufDFpPznOc8JycOIA5BRUAzmag5 ... WDHiSSJEmSJElaawY9SCRJkiRJkrTWDHqQSJIkSZIkaa0Z9CCRJEmSJEnSWjPoQSJJkiRJkqS1ZtCDRJIkSZIkSWvt/wfXnWDqYkPL4gAAAABJRU5ErkJggg=="}]
```

Full log attached
[log.txt](https://github.com/mozilla/geckodriver/files/1534455/log.txt)

**Comment by whimboo** [comment] 2017-12-06 09:11
As asked earlier, what is the `#safeText` element doing? Has it a listener attached, which delays the page load? Please provide as best an HTML testcase. Thanks.

**Comment by q-jack** [comment] 2017-12-06 09:54
The #saveText button submits a form.
Here is the [html](https://codepen.io/anon/pen/BmeBoW)

**Comment by q-jack** [comment] 2017-12-14 14:24
Were you able to reproduce this issue?

**Comment by whimboo** [comment] 2018-01-03 18:11
Sorry for the late reply but I was away most of last month. I had a look at the HTML testcase, but this is still too huge. Please minimize it to a reasonable size, and remove all external dependencies eg jQuery. As best have a single HTML file with all necessary code included.

**Comment by whimboo** [comment] 2019-01-30 08:44
Closing due to inactivity.

**Closed by whimboo** 2019-01-30 08:44 UTC
