### ISSUE TITLE
Intermittent null currentWindowGlobal instead of no such window error

### ISSUE THREAD

**Issue by titusfortner** [mozilla/geckodriver#1847] opened 2021-02-22 21:08 UTC
## System

* Version: 0.29.0
* Platform: Linux / Windows
* Firefox: 85.0.1 / 85.0.2
* Selenium: 4 beta 1 (Ruby)

I'm expecting this from the spec:
> If the current browsing context is no longer open, return error with error code no such window.

I'm intermittently getting:
> UnknownError: TypeError: browsingContextFn().currentWindowGlobal is null

This is the test that is intermittently failing:
https://github.com/watir/watir/blob/7_beta/spec/watirspec/window_switching_spec.rb#L279

Here is an [example of the failure on Linux](https://github.com/titusfortner/watir/runs/1955911073?check_suite_focus=true#step:6:2348)

Here is [the same failure on Windows](https://github.com/titusfortner/watir/runs/1955906870?check_suite_focus=true#step:5:2356)

Versions are recorded [here](https://github.com/titusfortner/watir/runs/1955911073?check_suite_focus=true#step:6:9
) and [here](https://github.com/titusfortner/watir/runs/1955906870?check_suite_focus=true#step:5:13)

It is relatively intermittent (about 1 failure every 4 runs), I've never seen it fail on Mac, only Linux & Windows, so I haven't been able to reproduce it locally.

**Comment by whimboo** [comment] 2021-02-23 14:24
@titusfortner, thank you for this report. Mind running again and provide a trace log? I'm not able to reproduce it locally with Firefox 85.0. Thanks.

**Comment by titusfortner** [comment] 2021-02-23 16:27
I can't reproduce it locally, either. :-/
Let me see if I can set up a spike with the settings and run it on GH actions until I see it again.

**Comment by titusfortner** [comment] 2021-02-23 16:45
https://github.com/titusfortner/watir/runs/1963048531?check_suite_focus=true#step:6:5510

**Comment by whimboo** [comment] 2021-02-23 21:35
> https://github.com/titusfortner/watir/runs/1963048531?check_suite_focus=true#step:6:5510

Looks like this job runs even 5h later. I assume there is something else broken with the job? Sadly there is no way to see details...

**Comment by titusfortner** [comment] 2021-02-23 22:22
hmm, maybe permissions are restricted on logs?

How about this:
https://gist.github.com/titusfortner/bf99aef08e69335ba09c5e667489df38#file-ff_bug_spike-log-L6080

**Comment by whimboo** [comment] 2021-02-23 22:41
I'll try tomorrow to create a testcase that works for me. 

But given the failure message a fix for https://bugzilla.mozilla.org/show_bug.cgi?id=1662808 might help here.

**Comment by whimboo** [comment] 2021-02-24 08:11
I'm not able to reproduce it. @titusfortner would it be possible for you to create a stand-alone testcase for that particular issue? As I can see in the trace logs you are using a page as served via localhost.

**Comment by whimboo** [comment] 2021-02-24 08:35
For reference here the related lines from the trace log:

```
2021-02-23T16:41:58.1227760Z 2021-02-23 16:41:58 INFO Selenium -> POST session/ca4f0738-6791-4d05-9f01-f2145a128bd5/element/9202c00e-2316-4342-a609-fa61f860dc26/click
2021-02-23T16:41:58.1230021Z 1614098518120	webdriver::server	DEBUG	-> POST /session/ca4f0738-6791-4d05-9f01-f2145a128bd5/element/9202c00e-2316-4342-a609-fa61f860dc26/click {}
2021-02-23T16:41:58.1238785Z 1614098518120	Marionette	DEBUG	0 -> [0,737,"WebDriver:ElementClick",{"id":"9202c00e-2316-4342-a609-fa61f860dc26"}]
2021-02-23T16:41:58.1290775Z 1614098518128	Marionette	TRACE	[4294967323] MarionetteEvents actor created for window id 4294967404
2021-02-23T16:41:58.1319264Z 1614098518131	Marionette	TRACE	Received event beforeunload for http://0.0.0.0:8180/closeable.html
2021-02-23T16:41:58.1324813Z 1614098518132	Marionette	TRACE	Received DOM event click for http://0.0.0.0:8180/closeable.html#
2021-02-23T16:41:58.1372261Z 1614098518137	Marionette	TRACE	Canceled page load listener because the top-browsing context has been closed
2021-02-23T16:41:58.1390739Z 1614098518138	Marionette	DEBUG	0 <- [1,737,null,{"value":null}]
2021-02-23T16:41:58.1393232Z JavaScript error: resource:///actors/ClickHandlerParent.jsm, line 58: TypeError: browser is null
2021-02-23T16:41:58.1406739Z JavaScript error: , line 0: NotFoundError: No such JSWindowActor 'MarionetteEvents'
2021-02-23T16:41:58.1419437Z 1614098518141	webdriver::server	DEBUG	<- 200 OK {"value":null}
2021-02-23T16:41:58.1439392Z 2021-02-23 16:41:58 INFO Selenium <- {"value":null}
2021-02-23T16:41:58.1440700Z 2021-02-23 16:41:58 INFO Selenium -> POST session/ca4f0738-6791-4d05-9f01-f2145a128bd5/element
2021-02-23T16:41:58.1442539Z 2021-02-23 16:41:58 INFO Selenium    >>> http://127.0.0.1:4444/session/ca4f0738-6791-4d05-9f01-f2145a128bd5/element | {"using":"xpath","value":".//*[local-name()='a']"}
2021-02-23T16:41:58.1446189Z 2021-02-23 16:41:58 DEBUG Selenium      > {"Accept"=>"application/json", "Content-Type"=>"application/json; charset=UTF-8", "User-Agent"=>"selenium/3.142.7 (ruby linux)", "Content-Length"=>"50"}
2021-02-23T16:41:58.1448417Z 1614098518143	webdriver::server	DEBUG	-> POST /session/ca4f0738-6791-4d05-9f01-f2145a128bd5/element {"using":"xpath","value":".//*[local-name()='a']"}
2021-02-23T16:41:58.1450073Z 1614098518144	Marionette	DEBUG	0 -> [0,738,"WebDriver:FindElement",{"using":"xpath","value":".//*[local-name()='a']"}]
2021-02-23T16:41:58.1527398Z JavaScript error: , line 0: NotFoundError: No such JSWindowActor 'MarionetteEvents'
2021-02-23T16:41:58.1531099Z 1614098518153	Marionette	TRACE	Retrying "findElement", attempt: 1
2021-02-23T16:41:58.1536449Z 1614098518153	Marionette	DEBUG	0 <- [1,738,{"error":"unknown error","message":"TypeError: browsingContextFn().currentWindowGlobal is null","stacktrace":"getMarionetteCommandsActorProxy/get/<@chrome://marionette/content/actors/MarionetteCommandsParent.jsm:332:29\n"},null]
2021-02-23T16:41:58.1539119Z Marionette threw an error: TypeError: browsingContextFn().currentWindowGlobal is null
2021-02-23T16:41:58.1591937Z getMarionetteCommandsActorProxy/get/<@chrome://marionette/content/actors/MarionetteCommandsParent.jsm:332:29
2021-02-23T16:41:58.1593140Z 
2021-02-23T16:41:58.1596022Z 1614098518154	webdriver::server	DEBUG	<- 500 Internal Server Error {"value":{"error":"unknown error","message":"TypeError: browsingContextFn().currentWindowGlobal is null","stacktrace":"getMarionetteCommandsActorProxy/get/<@chrome://marionette/content/actors/MarionetteCommandsParent.jsm:332:29\n"}}
```

**Comment by whimboo** [comment] 2021-02-24 08:36
And here as reference what I see locally:

```
1614154166879	Marionette	DEBUG	2 -> [0,23,"WebDriver:ElementClick",{"id":"22bfec18-edea-6743-b029-a2bd3886dbdf"}]
1614154166905	Marionette	TRACE	Received DOM event click for javascript:window.close();
1614154166908	Marionette	TRACE	[35] MarionetteEvents actor created for window id 6442450946
1614154166909	Marionette	TRACE	Received event beforeunload for http://127.0.0.1:55832/clicks.html
1614154166928	Marionette	TRACE	Canceled page load listener because the top-browsing context has been closed
1614154166928	Marionette	DEBUG	2 <- [1,23,null,{"value":null}]
1614154167031	Marionette	DEBUG	2 -> [0,24,"WebDriver:FindElement",{"value":"close-window","using":"id"}]
1614154167032	Marionette	DEBUG	2 <- [1,24,{"error":"no such window","message":"Browsing context has been discarded","stacktrace":"WebDriv
```

**Comment by titusfortner** [comment] 2021-02-24 13:12
Are you trying to reproduce it on Windows or Linux? For some reason it has never failed for me on my mac locally or on Github Actions Mac, but regularly fails on the other platforms.

**Comment by whimboo** [comment] 2021-02-24 13:19
Oh. I'm on MacOS. Maybe that's the reason then. I will take a look later or the next days.

**Comment by whimboo** [comment] 2023-05-22 15:14
Closing given that the before-mentioned patch should have fixed that.

**Closed by whimboo** 2023-05-22 15:14 UTC
Labels: marionette, needs investigation
