### ISSUE TITLE
Improvement suggestions on GeckoDriver/WebDriver

### ISSUE THREAD

**Issue by SetTrend** [mozilla/geckodriver#1341] opened 2018-08-02 09:30 UTC
I'd like to propose two improvements to GeckoDriver/WebDriver which I believe are essential for comprehensive and standardized automated testing of CSS and web application testing:

- [Add facility to take a screenshot of whole document](https://github.com/w3c/webdriver/issues/1283)
- [Set value of hidden `<input/>` elements](https://github.com/w3c/webdriver/issues/1281) ― [(alternative link)](https://github.com/w3c/webdriver/issues/1230)

I'm looking for opinions on how to realize these and have them implemented.

**Comment by whimboo** [comment] 2018-08-02 11:44
Hi Axel. Thank you for filing the issue. Please note that geckodriver targets to only implement behaviors as defined by the [WebDriver specification](https://w3c.github.io/webdriver/). While some parts haven't been implemented yet, we cannot just implement custom behavior. As such it doesn't help to file issues for geckodriver when topics are getting denied for the spec.

Let me get to your items:

1) As you noted your filed issue on the w3c repository I think this is just a dupe of https://github.com/w3c/webdriver/issues/893. It hasn't been finally discussed yet, and is waiting on a decision which we will have to make for level 2. I cannot guarantee when this will happen, but maybe in October.

2) I think @andreastt gave all the information you need, and for `input` of `type=file` it is still not discussed (https://github.com/w3c/webdriver/issues/1230). 

That means that nothing on this issue is actionable, and as such I have to close it.

**Closed by whimboo** 2018-08-02 11:44 UTC

**Comment by SetTrend** [comment] 2018-08-05 13:55
@whimboo :
Hi Henrik,

as I just replied to the WebDriver thread, my issue is different. I will elaborate my reasoning there.

I'm looking for support to have these urgent and important features get added to the WebDriver specification.

GeckoDriver programmers, in particular, have the skills to argument against @andreastt's statement where he's claiming it's impossible to easily create and save an off-screen image of full documents. I'd like to invite you to support the suggested feature there. It's desperately needed for device independant testing.
