### ISSUE TITLE
iframe reported as not displayed while visible in browser window

### ISSUE THREAD

**Issue by akostadinov** [mozilla/geckodriver#935] opened 2017-09-07 15:48 UTC
## System
* Version: 0.18.0
* Platform: Fedora Linux 26 amd64
* Firefox: Firefox 55
* Selenium: ruby - watir (6.7.3), selenium-webdriver (3.5.1)

## Testcase
```
<html class="index-page">
  <head></head>
  <body style="display: block;" hidden="">
    <iframe src="https://mdn-samples.mozilla.org/snippets/html/iframe-simple-contents.html"></iframe>
  </body>
</html>
```

## Trace-level log
```
1504798904835	webdriver::server	DEBUG	-> POST /session/d96d98b8-6b89-4f12-96e1-b5478e6c5eac/element {"using":"css selector","value":"iframe"}
1504798904836	geckodriver::marionette	TRACE	-> 61:[0,3,"findElement",{"using":"css selector","value":"iframe"}]
1504798904837	Marionette	TRACE	0 -> [0,3,"findElement",{"using":"css selector","value":"iframe"}]
1504798904843	Marionette	TRACE	0 <- [1,3,null,{"value":{"element-6066-11e4-a52e-4f735466cecf":"6812b009-f857-4bf8-bb9b-478b4956b6c1","ELEMENT":"6812b009-f857-4bf8-bb9b-478b4956b6c1"}}]
1504798904844	geckodriver::marionette	TRACE	<- [1,3,null,{"value":{"element-6066-11e4-a52e-4f735466cecf":"6812b009-f857-4bf8-bb9b-478b4956b6c1","ELEMENT":"6812b009-f857-4bf8-bb9b-478b4956b6c1"}}]
1504798904844	webdriver::server	DEBUG	<- 200 OK {"value":{"element-6066-11e4-a52e-4f735466cecf":"6812b009-f857-4bf8-bb9b-478b4956b6c1"}}
1504798904848	webdriver::server	DEBUG	-> GET /session/d96d98b8-6b89-4f12-96e1-b5478e6c5eac/element/6812b009-f857-4bf8-bb9b-478b4956b6c1/displayed 
1504798904848	geckodriver::marionette	TRACE	-> 72:[0,4,"isElementDisplayed",{"id":"6812b009-f857-4bf8-bb9b-478b4956b6c1"}]
1504798904849	Marionette	TRACE	0 -> [0,4,"isElementDisplayed",{"id":"6812b009-f857-4bf8-bb9b-478b4956b6c1"}]
1504798904901	Marionette	TRACE	0 <- [1,4,null,{"value":false}]
1504798904902	geckodriver::marionette	TRACE	<- [1,4,null,{"value":false}]
1504798904902	webdriver::server	DEBUG	<- 200 OK {"value":false}
```

As far as I can tell, GeckoDriver says that element with `css` selector `iframe` is not displayed while it is in fact displayed in the browser.

When using the Legacy driver, the element is correctly reported visible. I noticed this while trying to switch our existing tests to GeckoDriver.

**Comment by jineshqa** [comment] 2017-09-07 20:39
Reproducible on mac as well,

- Version: 0.18.0
- Platform: Mac 10.12.5
- Firefox: Firefox 55.0.3 (64 bit)
- Selenium: Java 3.5.3

Didn't want to spam with +1 type comment but added the comment anyway since it is on a different platform and selenium binding.

**Comment by whimboo** [comment] 2017-09-08 12:19
Dupe of issue #864?

**Comment by andreastt** [comment] 2017-09-11 14:29
Sure looks like it.

**Closed by andreastt** 2017-09-11 14:29 UTC
