### ISSUE TITLE
Execute any Javascript on Angular site: Permission denied to access property "invoke"

### ISSUE THREAD

**Issue by Mikeux** [mozilla/geckodriver#681] opened 2017-04-25 10:48 UTC
Newest selenium (3.4.0) and geckodriver(0.16) raise error on Angular site when try to execute any JS.

Test URL: http://www.syntaxsuccess.com/angular-2-samples/#/demo/spreadsheet
Test JS: this.JS.ExecuteScript("return '';");

**Error: Permission denied to access property "invoke"**

## Firefox Version
53.0, and Nightly (55.0a1) as well, both 32bit

## Platform
e.g. Windows 7 64bit, NET c#

## Steps to reproduce -
1. Open URL
2. Execute any Javascript

StackRace:
   at OpenQA.Selenium.Remote.RemoteWebDriver.UnpackAndThrowOnError(Response errorResponse)
   at OpenQA.Selenium.Remote.RemoteWebDriver.Execute(String driverCommandToExecute, Dictionary`2 parameters)
   at OpenQA.Selenium.Remote.RemoteWebDriver.ExecuteScriptCommand(String script, String commandName, Object[] args)
   at OpenQA.Selenium.Remote.RemoteWebDriver.ExecuteScript(String script, Object[] args)
   at asedev_QA.Core.CommonWebDriver.set_Url(String value) in C:\GitHub\ase-qa\asedev_QA\asedev_QA.Core\CommonWebDriver.cs:line 2349
   at asedev_QA.Core.Protractor.NgNavigation.GoToUrl(String url, Boolean ensureAngularApp) in C:\GitHub\ase-qa\asedev_QA\asedev_QA.Core\Protactor\NgNavigation.cs:line 112
   at asedev_QA.Core.Protractor.NgNavigation.OpenQA.Selenium.INavigation.GoToUrl(String url) in C:\GitHub\ase-qa\asedev_QA\asedev_QA.Core\Protactor\NgNavigation.cs:line 91
   at asedev_QA.Core.CommonWebDriver.goToURL(String url, Boolean createNew, Boolean clearCache) in C:\GitHub\ase-qa\asedev_QA\asedev_QA.Core\CommonWebDriver.cs:line 887

**Comment by andreastt** [comment] 2017-04-25 11:32
I can confirm that this is fixed by https://bugzilla.mozilla.org/show_bug.cgi?id=1353074. Closing this as a duplicate of https://github.com/mozilla/geckodriver/issues/515.

**Closed by andreastt** 2017-04-25 11:32 UTC
