### ISSUE TITLE
execute_async_script after time.sleep causes [Errno 32] Broken pipe

### ISSUE THREAD

**Issue by traffisco** [mozilla/geckodriver#1340] opened 2018-08-02 06:31 UTC
## System

* Version: geckodriver 0.21.0
* Platform: Linux/macOS>
* Firefox: Firefox 61.0.1
* Selenium: selenium-3.13.0

## Testcase
When sleeping the thread for more then 5 seconds and calling execute_async_script, the function errors with [Errno 32] Broken pipe after script timeout ended without the callback value.
Same code works on macos.

    from selenium import webdriver
    from selenium.webdriver.support.ui import WebDriverWait
    import time
    
    driver = webdriver.Firefox()
    
    driver.get('http://example.com')
    time.sleep(6)
    
    ret = driver.execute_async_script("var callback = arguments[arguments.length - 1];setTimeout(function(){callback('done')}, 7000)")
    print('ret '+ ret)

## Stacktrace
    Traceback (most recent call last):
      File "test.py", line 10, in <module>
    ret = driver.execute_async_script("var callback = arguments[arguments.length - 1];setTimeout(function(){callback('done')}, 7000)")
      File "/usr/local/lib/python3.6/dist-packages/selenium/webdriver/remote/webdriver.py", line 658, in execute_async_script
    'args': converted_args})['value']
      File "/usr/local/lib/python3.6/dist-packages/selenium/webdriver/remote/webdriver.py", line 318, in execute
        response = self.command_executor.execute(driver_command, params)
      File "/usr/local/lib/python3.6/dist-packages/selenium/webdriver/remote/remote_connection.py", line 472, in execute
        return self._request(command_info[0], url, body=data)
      File "/usr/local/lib/python3.6/dist-packages/selenium/webdriver/remote/remote_connection.py", line 495, in _request
        self._conn.request(method, parsed_url.path, body, headers)
      File "/usr/lib/python3.6/http/client.py", line 1239, in request
        self._send_request(method, url, body, headers, encode_chunked)
      File "/usr/lib/python3.6/http/client.py", line 1285, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
      File "/usr/lib/python3.6/http/client.py", line 1234, in endheaders
        self._send_output(message_body, encode_chunked=encode_chunked)
      File "/usr/lib/python3.6/http/client.py", line 1065, in _send_output
        self.send(chunk)
      File "/usr/lib/python3.6/http/client.py", line 986, in send
        self.sock.sendall(data)
    BrokenPipeError: [Errno 32] Broken pipe

## Trace-level log

[geckodriver.log](https://github.com/mozilla/geckodriver/files/2252349/geckodriver.log)

**Comment by whimboo** [comment] 2018-08-02 11:48
This is basically a dupe of issue #1304.

**Closed by whimboo** 2018-08-02 11:48 UTC
