### ISSUE TITLE
Not able to click element from revealed HTML element

### ISSUE THREAD

**Issue by ashutosh143** [mozilla/geckodriver#574] opened 2017-03-28 06:15 UTC
## Firefox Version
52.0.1

## Platform
Windows 8.1 pro

## Steps to reproduce -
Click on the dropdown and click on the expected value from visible list.

Tried below mentioned alternatives.
1. driver.findElement(By.id("ddlCategory-button")).click();
        driver.findElement(By.id("ui-id-4")).click();
2. ((JavascriptExecutor)driver).executeScript("arguments[0].click();", driver.findElement(By.id("ui-id-4")));
3. As dropdown dosen't have option tag we can not use Select tag here
4. Action methods are not working in this case too.
5. Tried with old gecko driver with old/new selenium jar. Not solved.

Note*
Using first case steps we are able to select the value in chrome.

![firefoxissue](https://cloud.githubusercontent.com/assets/10814956/24391306/e416c0e2-13ab-11e7-89cb-b250162e4e1c.png)

**Comment by andreastt** [comment] 2017-03-28 14:23
Please provide a reproducible test case an a minimal HTML document.

**Comment by ashutosh143** [comment] 2017-04-03 06:01
Steps to reproduce:
1.  Click on drop-down list.
2.  Select any option of opened list. 

HTML Document:

<span id="abc" class="ui-selectmenu-button ui-widget ui-state-default ui-state-focus ui-corner-top" tabindex="0" role="combobox" aria-expanded="true" aria-autocomplete="list" aria-owns="ddlCategory-menu" aria-haspopup="true" style="width: 242px;" aria-activedescendant="ui-id-2" aria-labelledby="ui-id-1" aria-disabled="false">
<div class="ui-selectmenu-menu ui-front ui-selectmenu-open" style="top: 57.25px; left: 0.5px;">
<ul id="ddlCategory-menu" class="ui-menu ui-widget ui-widget-content ui-corner-bottom custom-scrollbar" aria-hidden="false" aria-labelledby="ddlCategory-button" role="listbox" tabindex="0" aria-activedescendant="ui-id-2" aria-disabled="false" style="width: 302px;">
<li id="ui-id-1" class="ui-menu-item" tabindex="-1" role="option">Select</li>
<li id="ui-id-2" class="ui-menu-item ui-state-focus" tabindex="-1" role="option">Accounting and Finance</li>
<li id="ui-id-3" class="ui-menu-item" tabindex="-1" role="option">Administrative Support</li>
<li id="ui-id-4" class="ui-menu-item" tabindex="-1" role="option">Architecture</li>
<li id="ui-id-5" class="ui-menu-item" tabindex="-1" role="option">Art, Fashion and Design</li>
<li id="ui-id-6" class="ui-menu-item" tabindex="-1" role="option">Banking and Financial Services</li>
<li id="ui-id-7" class="ui-menu-item" tabindex="-1" role="option">Beauty and Spa</li>
<li id="ui-id-8" class="ui-menu-item" tabindex="-1" role="option">Business</li>
<li id="ui-id-9" class="ui-menu-item" tabindex="-1" role="option">Childcare</li>
</ul>
</div>
</div>

**Comment by andreastt** [comment] 2017-04-04 15:45
That document looks like this to me:

![screenshot-2017-04-04-164447](https://cloud.githubusercontent.com/assets/399120/24665683/0cd7ee48-1956-11e7-9b92-7650a94fe7ca.png)

Since there are no reproducible steps here, I am going to close the issue.

**Closed by andreastt** 2017-04-04 15:45 UTC
Labels: needinfo
