### ISSUE TITLE
can anyone help plzzzz,,,,,,/////????

### ISSUE THREAD

**Issue by mamun626** [mozilla/geckodriver#1740] opened 2020-07-03 15:20 UTC
## System

* Version:  0.26
* Platform:  kali linux
* Firefox:  78(64-bit)
* Selenium: 4.0.0a1

*************************************************************
*                       WhatsApp Bomber                     *
*                         Version 1.1                       *
*                  Made By Debayan Sutradhar                *
*                   (ladiesman6969, DX_BETA)                *
*                     OPEN SOURCE IS LOVE                   *
*       https://github.com/ladiesman6969/whatsappBomber     *
*                          16/08/2018                       *
*************************************************************
Checking for WebDriver...
Please select any one of the Web Drivers : 
1. Mozilla FireFox (Gecko Driver)
1
Loading Gecko Web Driver ...
Traceback (most recent call last):
  File "bomber.py", line 150, in <module>
    app_method_1()
  File "bomber.py", line 131, in app_method_1
    driver = webdriver.Firefox()
  File "/usr/lib/python3/dist-packages/selenium/webdriver/firefox/webdriver.py", line 170, in __init__
    RemoteWebDriver.__init__(
  File "/usr/lib/python3/dist-packages/selenium/webdriver/remote/webdriver.py", line 152, in __init__
    self.start_session(capabilities, browser_profile)
  File "/usr/lib/python3/dist-packages/selenium/webdriver/remote/webdriver.py", line 249, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "/usr/lib/python3/dist-packages/selenium/webdriver/remote/webdriver.py", line 318, in execute
    self.error_handler.check_response(response)
  File "/usr/lib/python3/dist-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException**: Message: invalid argument: can't kill an exited process**

**Comment by whimboo** [comment] 2020-07-06 06:29
Dupe of #1716.

**Closed by whimboo** 2020-07-06 06:29 UTC
Labels: invalid
