### ISSUE TITLE
Can't choose the option from the select lists

### ISSUE THREAD

**Issue by michalpotasiakdroptica** [mozilla/geckodriver#294] opened 2016-10-22 12:27 UTC
OS: Linux 14.04
Selenium Version: 3.0.1
IDE: Exlipse
Java: java version "1.8.0_101"
Browser: Firefox 47.0.1
Geckodriver: v0.11.1

Create WebDriver
`System.setProperty("webdriver.gecko.driver","geckodriver");
driver = new FirefoxDriver();`

My function.
`Select dropdownTextField = new Select(driver.findElement(By.id("edit-new-storage-type")));
dropdownTextField.selectByVisibleText("Text (formatted, long)");
Thread.sleep(2000);`

Element to select:
https://s18.postimg.org/i8h1jlyll/Zaznaczenie_194.png

Actual Behavior:
- error
`(firefox:11037): GLib-GObject-CRITICAL **: g_type_add_interface_static: assertion 'g_type_parent (interface_type) == G_TYPE_INTERFACE' failed

(firefox:11037): GLib-GObject-CRITICAL **: g_type_add_interface_static: assertion 'g_type_parent (interface_type) == G_TYPE_INTERFACE' failed

(firefox:11037): GLib-GObject-CRITICAL **: g_type_add_interface_static: assertion 'g_type_parent (interface_type) == G_TYPE_INTERFACE' failed

(firefox:11037): GLib-GObject-CRITICAL **: g_type_add_interface_static: assertion 'g_type_parent (interface_type) == G_TYPE_INTERFACE' failed
JavaScript warning: https://normandy.cdn.mozilla.net/static/bundles/selfrepair-910943d53dbd84b4c75a.a958f9d28733.js, line 7: mutating the [[Prototype]] of an object will cause your code to run very slowly; instead create the object with the correct initial [[Prototype]] value using Object.create

(firefox:11037): GLib-GObject-CRITICAL **: g_type_add_interface_static: assertion 'g_type_parent (interface_type) == G_TYPE_INTERFACE' failed
JavaScript warning: resource://gre/modules/commonjs/toolkit/loader.js -> resource://gre/modules/commonjs/sdk/system/environment.js, line 15: Proxy.create and Proxy.createFunction are deprecated, use new Proxy instead
console.warn: Asynchronous operation was aborted as selection changed.`
- test fail

**Comment by andreastt** [comment] 2016-10-22 12:40
Support for `<select>` and `<option>` elements was added in [bug 1255955](https://bugzilla.mozilla.org/show_bug.cgi?id=1255955).

Resolving as duplicate of https://github.com/mozilla/geckodriver/issues/94.

**Closed by andreastt** 2016-10-22 12:40 UTC
