### ISSUE TITLE
Exceptions When Switching Frames in Firefox 102.0 ESR with GeckoDriver v0.32 

### ISSUE THREAD

**Issue by OtiliaRegheni** [mozilla/geckodriver#2164] opened 2024-03-01 10:54 UTC
## System

* Version: 0.32
* Platform: CentOS
* Firefox: 102.0esr 
* Selenium:  3.14 and 4.13. 

When switching to a different frame on a webpage using Selenium WebDriver with Firefox 102.0 ESR and GeckoDriver v0.32, intermittent exceptions are encountered when attempting to interact with elements within the switched frame. Instead of receiving a TimeoutException or a relevant error indicating the frame is not ready, the following exceptions are thrown without a preceding indication of frame availability issues:

-      NoSuchWindowException: Browsing context has been discarded.

-      StaleElementReferenceException: The element reference is stale; either the element is no longer attached to the DOM, it is not in the current frame context, or the document has been refreshed.

This behavior is inconsistent and complicates element interaction within frames, requiring a workaround that involves retrying the frame switch and element interaction.

**This issue can be reproduced by following these steps:**

1.Initiate a Selenium WebDriver session with Firefox 102.0 ESR using GeckoDriver v0.32.
2.Navigate to a webpage that contains multiple frames.
3.Switch to a new frame using the "ExpectedConditions.frameToBeAvailableAndSwitchToIt(frameBy)" condition.
4.Attempt to select an element within the new frame context.

**Expected Behavior:** After switching to a new frame, elements within that frame should be selectable without errors.

**Actual Behavior:** When attempting to select an element within a newly switched frame, exceptions are thrown intermittently:

- NoSuchWindowException: Browsing context has been discarded
- StaleElementReferenceException: The element reference of [element details] is stale; either the element is no longer attached to the DOM, it is not in the current frame context, or the document has been refreshed.

**Comment by whimboo** [comment] 2024-03-04 09:00
Firefox ESR 102 is no longer supported so please switch to the recent (ESR) release. Also you should update geckodriver accordingly. If it is still reproducible for you please attach a [trace-level log] from geckodriver. Also read more about reporting actionable bugs in our [contribution guidelines]. Thanks.

[trace-level log]: https://firefox-source-docs.mozilla.org/testing/geckodriver/TraceLogs.html
[contribution guidelines]: https://firefox-source-docs.mozilla.org/testing/geckodriver/Bugs.html

**Comment by OtiliaRegheni** [comment] 2024-03-12 07:35
Hello. I will try with a latest version of Firefox ESR and gecko driver and came back with feedback regarding this. Thank you.

**Comment by whimboo** [comment] 2024-03-25 07:11
Closing as incomplete because of a missing reply from the reporter, but happy to reopen if more details are provided, which demonstrate that this is an issue with geckodriver or Firefox.

**Closed by whimboo** 2024-03-25 07:11 UTC
Labels: awaiting reporter feedback
