### ISSUE TITLE
Click is not waiting for subsequent page load

### ISSUE THREAD

**Issue by davehunt** [mozilla/geckodriver#911] opened 2017-08-30 17:56 UTC
## System
* Version: 0.18.0
* Platform: macOS Sierra 10.12.6
* Firefox: 57.0a1 (2017-08-30) (64-bit)
* Selenium: Python 3.6.2 with selenium 3.5.0

## Testcase

```python
from selenium.webdriver import Firefox
from selenium.webdriver.firefox.options import Options
from selenium.webdriver.support.wait import WebDriverWait


def wait_for_page_to_load():
    WebDriverWait(f, timeout=10).until(
        lambda s: len(f.find_elements_by_css_selector('.job-btn.filter-shown')) >= 1)


def active_repo():
    el = f.find_element_by_css_selector('#watched-repo-navbar button.active')
    print(el.text)


def switch_repo():
    f.find_element_by_id('repoLabel').click()
    f.find_element_by_css_selector('#repo-dropdown a[href*="mozilla-central"]').click()
    wait_for_page_to_load()
    active_repo()


o = Options()
o.log.level = 'trace'
o.binary = '/Applications/FirefoxNightly.app/Contents/MacOS/firefox-bin'

f = Firefox(firefox_options=o)
f.get('https://treeherder.allizom.org/')
wait_for_page_to_load()

active_repo()
switch_repo()
f.quit()
```

## Stacktrace

Sometimes the script will return the unmodified active repository because the page load has not yet happened, and sometimes the page load is in progress and we fail to locate the active repository, as shown in the following trace:

```
Traceback (most recent call last):
  File "treeherder-switch-repo.py", line 32, in <module>
    switch_repo()
  File "treeherder-switch-repo.py", line 20, in switch_repo
    active_repo()
  File "treeherder-switch-repo.py", line 12, in active_repo
    el = f.find_element_by_css_selector('#watched-repo-navbar button.active')
  File "/Users/dhunt/.pyenv/versions/geckodriver-tmp/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 498, in find_element_by_css_selector
    return self.find_element(by=By.CSS_SELECTOR, value=css_selector)
  File "/Users/dhunt/.pyenv/versions/geckodriver-tmp/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 832, in find_element
    'value': value})['value']
  File "/Users/dhunt/.pyenv/versions/geckodriver-tmp/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 297, in execute
    self.error_handler.check_response(response)
  File "/Users/dhunt/.pyenv/versions/geckodriver-tmp/lib/python3.6/site-packages/selenium/webdriver/remote/errorhandler.py", line 194, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: Unable to locate element: #watched-repo-navbar button.active
```

## Trace-level log

[geckodriver.log.zip](https://github.com/mozilla/geckodriver/files/1264569/geckodriver.log.zip)

**Comment by whimboo** [comment] 2017-08-30 18:11
So inspecting the trace log I do not see that your test reaches the first `click` at all. It already fails here:

```
1504115679968	Marionette	TRACE	0 -> [0,12,"findElement",{"using":"css selector","value":"#watched-repo-navbar button.active"}]
1504115680121	Marionette	TRACE	0 <- [1,12,{"error":"no such element","message":"Unable to locate element: #watched-repo-navbar 
```
So whatever you are waiting for in `wait_for_page_to_load()` is not waiting long enough for `#watched-repo-navbar button.active` being present. So `find_element_by_css_selector` will clearly fail. 

Can you please clarify? Thanks.

**Comment by davehunt** [comment] 2017-08-30 18:28
Please try running the script and you will see that the clicks are indeed received. I didn't check the final log before uploading so perhaps there was an issue with my last run, but I'm now away from my machine for the evening.

**Comment by davehunt** [comment] 2017-08-31 09:41
@whimboo the successful click is in the log:

```
1504115679511	webdriver::server	DEBUG	-> POST /session/8ee6884c-2e88-7947-a54a-e8d984930f6c/element {"using": "css selector", "value": "#repo-dropdown a[href*=\"mozilla-central\"]", "sessionId": "8ee6884c-2e88-7947-a54a-e8d984930f6c"}
1504115679511	geckodriver::marionette	TRACE	-> 98:[0,9,"findElement",{"using":"css selector","value":"#repo-dropdown a[href*=\"mozilla-central\"]"}]
1504115679512	Marionette	TRACE	0 -> [0,9,"findElement",{"using":"css selector","value":"#repo-dropdown a[href*=\"mozilla-central\"]"}]
1504115679562	Marionette	TRACE	0 <- [1,9,null,{"value":{"element-6066-11e4-a52e-4f735466cecf":"566121aa-eab6-4542-b56d-cfc8b78da9b2","ELEMENT":"566121aa-eab6-4542-b56d-cfc8b78da9b2"}}]
1504115679562	geckodriver::marionette	TRACE	<- [1,9,null,{"value":{"element-6066-11e4-a52e-4f735466cecf":"566121aa-eab6-4542-b56d-cfc8b78da9b2","ELEMENT":"566121aa-eab6-4542-b56d-cfc8b78da9b2"}}]
1504115679563	webdriver::server	DEBUG	<- 200 OK {"value":{"element-6066-11e4-a52e-4f735466cecf":"566121aa-eab6-4542-b56d-cfc8b78da9b2"}}
1504115679563	webdriver::server	DEBUG	-> POST /session/8ee6884c-2e88-7947-a54a-e8d984930f6c/element/566121aa-eab6-4542-b56d-cfc8b78da9b2/click {"id": "566121aa-eab6-4542-b56d-cfc8b78da9b2", "sessionId": "8ee6884c-2e88-7947-a54a-e8d984930f6c"}
1504115679566	geckodriver::marionette	TRACE	-> 67:[0,10,"clickElement",{"id":"566121aa-eab6-4542-b56d-cfc8b78da9b2"}]
1504115679567	Marionette	TRACE	0 -> [0,10,"clickElement",{"id":"566121aa-eab6-4542-b56d-cfc8b78da9b2"}]
1504115679654	Marionette	DEBUG	Received DOM event "popstate" for "https://treeherder.allizom.org/#/jobs?repo=mozilla-central"
```

The part you quoted is most likely the attempt to locate the element during the page load.

**Comment by davehunt** [comment] 2017-09-01 13:35
As mentioned on IRC, this is working if I switch back to Firefox 47 with the legacy driver.

**Comment by whimboo** [comment] 2017-09-05 18:18
The events as used by Treeherder are very strange. So this is what I see when I remove the listeners for `popstate` and `hashchange` events:

```
1504634227041   Marionette  DEBUG   Received DOM event "popstate" for "https://treeherder.allizom.org/#/jobs?repo=mozilla-central"
1504634227044    Marionette  DEBUG   Received DOM event "beforeunload" for "https://treeherder.allizom.org/#/jobs?repo=mozilla-central"
1504634227143   Marionette  DEBUG   Received DOM event "hashchange" for "https://treeherder.allizom.org/#/jobs?repo=mozilla-central"
1504634227370   Marionette  DEBUG   Received DOM event "pagehide" for "https://treeherder.allizom.org/#/jobs?repo=mozilla-central"
1504634227375   Marionette  DEBUG   Received DOM event "unload" for "https://treeherder.allizom.org/#/jobs?repo=mozilla-central"
1504634228037   Marionette  DEBUG   Received DOM event "DOMContentLoaded" for "https://treeherder.allizom.org/#/jobs?repo=mozilla-central"
1504634228045   Marionette  DEBUG   Received DOM event "pageshow" for "https://treeherder.allizom.org/#/jobs?repo=mozilla-central"
```

So first we see a `popstate` event, which means that another history item got activated. Usually we return here immediately in Marionette because no page load events will be fired at all in those cases. But here we see a `beforeunload` event 3ms later which indicates that the page is about to get unloaded. Then we have a `hashchange` event. I don't know why we actually have that given that with the `popstate` event we already have `mozilla-central` in the URL. Usually after a `hashchange` we immediatelly return in Marionette. But then we see a full page load happening again, which finishes with `pageshow`.

I don't know which magic Treeherder is actually performing here. Maybe @edmorley can help us to better understand this behavior. When I see the above I have the feeling that there are multiple page loads involved, means that TH force triggers a page load after activating the history for the new repository.

**Comment by akostadinov** [comment] 2017-09-06 09:21
might be related or duplicate of #878

**Comment by edmorley** [comment] 2017-09-06 09:40
> I don't know which magic Treeherder is actually performing here. Maybe @edmorley can help us to better understand this behavior.

Redirect to @camd who has worked more with the Treeherder frontend.

**Comment by whimboo** [comment] 2017-09-06 09:42
> might be related or duplicate of #878

No, given that this issue is specific about `submit` and is not a public API of the Webdriver spec.

**Comment by davehunt** [comment] 2017-09-18 19:10
Note that I can still replicate this with geckodriver 0.19.0 and Firefox 57.0a1 (2017-09-18) (64-bit)

**Comment by camd** [comment] 2017-10-12 16:45
I'm not entirely sure why it's not waiting for that element to show.  It sounds like Firefox had some rendering optimizations in 57 that change the order of things.  You could also try searching for the class ``.ready`` in ``wait_for_page_to_load`` rather than the selector you're currently using to see if that's more reliable.  We have an element that adds that class once the jobs have been loaded.

**Comment by wlach** [comment] 2017-10-12 17:56
Maybe we need to wait for certain elements to be marked as visible and not merely loaded? I noticed this in the travis tests a few months ago:

https://github.com/mozilla/treeherder/commit/c5bf853499e7adab578ec04c3769e36555aa0c93

As an aside, this test would be far more useful if it was run as part of the travis build.

**Comment by davehunt** [comment] 2017-10-12 18:04
This is not about waiting for elements, but for the page load that follows the click. We could indeed work around this by waiting for the state of certain elements, but in the webdriver spec if a [click](https://w3c.github.io/webdriver/webdriver-spec.html#element-click) causes navigation, then we should try to [wait for the navigation to complete](https://w3c.github.io/webdriver/webdriver-spec.html#dfn-waiting-for-the-navigation-to-complete).

> As an aside, this test would be far more useful if it was run as part of the travis build (I know some of the other selenium tests depend on data that's only on allizom, but that doesn't seem to be the case here).

Agreed, and @rbillings is working on this.

**Comment by wlach** [comment] 2017-10-12 18:15
Maybe I'm missing something, but it looks like `wait_for_page_to_load` does seem to wait for an element to be present? Are you sure there isn't a race here somewhere?

**Comment by davehunt** [comment] 2017-10-12 18:20
> Maybe I'm missing something, but it looks like `wait_for_page_to_load` does seem to wait for an element to be present? Are you sure there isn't a race here somewhere?

It waits for there to be at least one element with the specified location to be present (not necessarily displayed). This is only an attempt to demonstrate the bug, which is that the `click` is returning too early. It is perhaps not the best demonstration, and I see that it has proven to be a little misleading.

**Comment by davehunt** [comment] 2017-10-20 18:50
After doing some digging, it appears that clicking links within Treeherder cause a `popstate` event to be fired before the `beforeunload`, `hashchange`, `pagehide`, and `unload` events. Looking at [our code](https://dxr.mozilla.org/mozilla-central/rev/20d57b9c4183973af4af5e078dff2aec0b74f928/testing/marionette/listener.js#134), we're aborting the wait for unload when `popstate` or `hashchange` events are fired. I suspect this is the reason we're not waiting here.

From what I understand, Treeherder is using Angular. I found [this code](https://github.com/angular/angular.js/blob/dfcb5ac1e43e25f2df19dd89c0514022e6ff62b3/src/ng/browser.js#L150) that suggests it's using the history API when changing the browser location. That could be a red herring, but it looks a bit suspect.

We changed the behaviour to avoid waiting for page loads when navigating back/forward in [bug 1386977](https://bugzilla.mozilla.org/show_bug.cgi?id=1386977) due to #815. I'm not sure of the best solution for this, but clearly a `popstate` does not only relate to back/forward/refresh, and may be a particular issue if it affects all sites built using Angular.

**Comment by davehunt** [comment] 2017-10-24 14:27
After further discussion with @camd and @whimboo and additional investigation, I have raised [bug 1411264](https://bugzilla.mozilla.org/show_bug.cgi?id=1411264) with a reduced test that replicated the issue. It appears that a `window.location.hash` change followed by a `window.location` change is enough to replicate this issue.

**Comment by whimboo** [comment] 2017-10-25 04:18
Thanks Dave.

**Comment by whimboo** [comment] 2021-02-22 08:00
https://bugzilla.mozilla.org/show_bug.cgi?id=1411264 was marked as wontfix a long time ago. As such closing this issue.

**Closed by whimboo** 2021-02-22 08:00 UTC
Labels: marionette
