### ISSUE TITLE
Selenium element.screenshot() does not capture the element but the viewport

### ISSUE THREAD

**Issue by aaltat** [mozilla/geckodriver#1413] opened 2018-10-31 19:22 UTC
## System

* Version: geckodriver 0.23.0 ( 2018-10-04)
* Platform: Ubuntu 18.04.1 LTS 
* Firefox: 63.0
* Selenium: 3.14.1

## Testcase
Test html: https://gist.github.com/aaltat/d3280f053072725290787408a6a3f612#file-test-html
Test case: https://gist.github.com/aaltat/d3280f053072725290787408a6a3f612#file-test-py

When the `test.py` is run, browser opens, screen capture is saved and errors are not displayed. But when `picture.png` is opened, then it seen that the screen shot is taken from the full page. I did expect that screen shot is taken only from the element containing id nothing2. Then the Webdriver specification, https://www.w3.org/TR/webdriver1/#take-element-screenshot outlines that only the element should be in the picture.

## Stacktrace
Not available

## Trace-level log
Please see: https://gist.github.com/aaltat/d3280f053072725290787408a6a3f612#file-geckodriver-log

**Comment by whimboo** [comment] 2018-11-01 08:51
Thank you for reporting this problem. I can verify and it is a regression since geckodriver 0.22.0. Specially my changes to move to Serde caused it. I will have a look at it over on https://bugzilla.mozilla.org/show_bug.cgi?id=1503804.

**Comment by whimboo** [comment] 2019-01-30 09:01
This is now fixed in the newly released geckodriver 0.24.0.

**Closed by whimboo** 2019-01-30 09:01 UTC
Labels: geckodriver

**Comment by aaltat** [comment] 2019-01-30 11:54
Thanks for fixing the issue.
