### ISSUE TITLE
0.21.0 regression: BrokenPipeError on driver.get method call

### ISSUE THREAD

**Issue by Mattwmaster58** [mozilla/geckodriver#1331] opened 2018-07-17 21:15 UTC
## System

* Version: 0.21.0
* Platform: Arch Linux Kernel 4.17.5-1
* Firefox: 63.0a1 (tested on 15+ different nightly builds from July)
* Selenium: Python selenium bindings v3.13.0
    * Python: 3.6.6

Code works flawlessly on version 0.20.1

## Testcase

~~~~~
from selenium import webdriver

urls = ['https://google.ca','https://amazon.ca']
drv = webdriver.Firefox()
while True:
    for u in urls:
        drv.get(u)
~~~~~
## Stacktrace

```
  File "/home/matt/auto/agaa/ga_client.py", line 146, in enter_giveaway
    self.drv.get(url)
  File "/home/matt/.local/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 332, in get
    self.execute(Command.GET, {'url': url})
  File "/home/matt/.local/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 318, in execute
    response = self.command_executor.execute(driver_command, params)
  File "/home/matt/.local/lib/python3.6/site-packages/selenium/webdriver/remote/remote_connection.py", line 472, in execute
    return self._request(command_info[0], url, body=data)
  File "/home/matt/.local/lib/python3.6/site-packages/selenium/webdriver/remote/remote_connection.py", line 495, in _request
    self._conn.request(method, parsed_url.path, body, headers)
  File "/usr/lib/python3.6/http/client.py", line 1239, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/lib/python3.6/http/client.py", line 1285, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.6/http/client.py", line 1234, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.6/http/client.py", line 1065, in _send_output
    self.send(chunk)
  File "/usr/lib/python3.6/http/client.py", line 986, in send
    self.sock.sendall(data)
BrokenPipeError: [Errno 32] Broken pipe
```

## Trace-level log

```
1531860077191	webdriver::server	DEBUG	-> GET /session/6e2e7e0d-7281-4d54-a898-bca23a0c3e33/element/2c047b28-1d5c-497c-b5b8-a78e3e37a26e/text
1531860077194	Marionette	TRACE	0 -> [0,5323,"WebDriver:GetElementText",{"id":"2c047b28-1d5c-497c-b5b8-a78e3e37a26e"}]
1531860077391	Marionette	TRACE	0 <- [1,5323,null,{"value":"John, you didn't win"}]
1531860077392	webdriver::server	DEBUG	<- 200 OK {"value":"John, you didn't win"}
1531860077394	webdriver::server	DEBUG	-> GET /session/6e2e7e0d-7281-4d54-a898-bca23a0c3e33/title
1531860077399	Marionette	TRACE	0 -> [0,5324,"WebDriver:GetTitle",{}]
1531860077399	Marionette	TRACE	0 <- [1,5324,null,{"value":"Amazon Giveaways"}]
1531860077407	webdriver::server	DEBUG	<- 200 OK {"value":"Amazon Giveaways"}
1531860083023	webdriver::server	DEBUG	-> GET /session/6e2e7e0d-7281-4d54-a898-bca23a0c3e33/screenshot
1531860083056	Marionette	TRACE	0 -> [0,5325,"WebDriver:TakeScreenshot",{"full":false,"highlights":[],"id":null}]
1531860083854	Marionette	TRACE	0 <- [1,5325,null,{"value":"iVBORw0KGgoAAAANSUhEUgAABUwAAAK2CAYAAACVVtY/AAAgAElEQVR4nOydd3wU5fr2YzvnWFEPqEdRQLo00QMogopiRUAFKyAWQL ... upVCkMFlm8qJ81q69ibPMdHDt2bMY+7N69mysu76dcqqBUVNRKLT+9w8ksqyil2rxWiypqWcNQLf7+ki+fxm84iURypvA/xHCmJA7kBCkAAAAASUVORK5CYII="}]
1531860084013	webdriver::server	DEBUG	<- 200 OK {"value":"insert_encoded_screenshot_here"}
webdriver::server	DEBUG	-> DELETE /session/6e2e7e0d-7281-4d54-a898-bca23a0c3e33
1531860084151	Marionette	TRACE	0 -> [0,5326,"Marionette:Quit",{"flags":["eForceQuit"]}]
1531860084167	Marionette	INFO	Stopped listening on port 39029
1531860084859	Marionette	TRACE	0 <- [1,5326,null,{"cause":"shutdown"}]
1531860085239	webdriver::server	DEBUG	Deleting session
1531860085281	Marionette	TRACE	0 -> [0,5327,"Marionette:Quit",{"flags":["eForceQuit"]}]
1531860085283	Marionette	TRACE	0 <- [1,5327,{"error":"invalid session id","message":"","stacktrace":"WebDriverError@chrome://marionette/content/error.js:178:5\nI ... et@chrome://marionette/content/server.js:245:8\n_onJSONObjectReady/<@chrome://marionette/content/transport.js:490:9\n"},null]
1531860085654	Marionette	DEBUG	Closed connection 0
[Parent 18891, Gecko_IOThread] WARNING: pipe error (91): Connection reset by peer: file /builds/worker/workspace/build/src/ipc/chromium/src/chrome/common/ipc_channel_posix.cc, line 353
1531860086283	Marionette	DEBUG	Received observer notification xpcom-will-shutdown
1531860086283	Marionette	DEBUG	Resetting recommended pref apz.content_response_timeout
1531860086284	Marionette	DEBUG	Resetting recommended pref browser.download.panel.shown
1531860086284	Marionette	DEBUG	Resetting recommended pref browser.pagethumbnails.capturing_disabled
1531860086284	Marionette	DEBUG	Resetting recommended pref browser.search.update
1531860086285	Marionette	DEBUG	Resetting recommended pref toolkit.cosmeticAnimations.enabled
1531860086286	Marionette	DEBUG	Resetting recommended pref browser.tabs.disableBackgroundZombification
1531860086286	Marionette	DEBUG	Resetting recommended pref browser.tabs.warnOnCloseOtherTabs
1531860086287	Marionette	DEBUG	Resetting recommended pref browser.tabs.warnOnOpen
1531860086287	Marionette	DEBUG	Resetting recommended pref browser.usedOnWindows10.introURL
1531860086288	Marionette	DEBUG	Resetting recommended pref browser.urlbar.suggest.searches
1531860086290	Marionette	DEBUG	Resetting recommended pref datareporting.policy.dataSubmissionPolicyAccepted
1531860086290	Marionette	DEBUG	Resetting recommended pref dom.disable_beforeunload
1531860086290	Marionette	DEBUG	Resetting recommended pref dom.disable_open_during_load
1531860086290	Marionette	DEBUG	Resetting recommended pref dom.file.createInChild
1531860086291	Marionette	DEBUG	Resetting recommended pref dom.max_chrome_script_run_time
1531860086291	Marionette	DEBUG	Resetting recommended pref dom.max_script_run_time
1531860086292	Marionette	DEBUG	Resetting recommended pref extensions.getAddons.cache.enabled
1531860086293	Marionette	DEBUG	Resetting recommended pref extensions.webservice.discoverURL
1531860086293	Marionette	DEBUG	Resetting recommended pref network.http.prompt-temp-redirect
1531860086293	Marionette	DEBUG	Resetting recommended pref network.http.speculative-parallel-limit
1531860086293	Marionette	DEBUG	Resetting recommended pref security.fileuri.strict_origin_policy
1531860086293	Marionette	DEBUG	Resetting recommended pref security.notification_enable_delay
1531860086294	Marionette	DEBUG	Resetting recommended pref signon.autofillForms
1531860086295	Marionette	DEBUG	Resetting recommended pref signon.rememberSignons
1531860086298	Marionette	DEBUG	Remote service is inactive
1531860088201	geckodriver::marionette	DEBUG	Browser process stopped: exit code: 0
1531860088251	webdriver::server	DEBUG	<- 200 OK {"value": null}
```

**Comment by andreastt** [comment] 2018-07-21 11:42
This is not so much a regression in geckodriver as much as a bug in the Python standard library. If you upgrade to Python 3.7 I think you will see the problem go away.

geckodriver 0.21.0 enabled persistent HTTP connections (HTTP/1.1 `Keep-Alive`), and because there is a bug in httplib which the Selenium Python client uses, it fails to notice when the connection gets dropped by the server after the timeout.

This issue is a duplicate of https://github.com/mozilla/geckodriver/issues/1304, and https://github.com/SeleniumHQ/selenium/pull/6103 tracks the Selenium client fix. @AutomatedTester, do you have an update on when we can expect that to land?

**Closed by andreastt** 2018-07-21 11:42 UTC

**Comment by whimboo** [comment] 2018-07-25 07:30
@Mattwmaster58 so I would suggest you keep version 0.20.1 for now until we release a new version of geckodriver.
