### ISSUE TITLE
Firefox 56, geckodriver 0.19.0 error/exception in driver.quit()

### ISSUE THREAD

**Issue by TPinheiroDias** [mozilla/geckodriver#1071] opened 2017-11-22 11:27 UTC
## System
* Version: <geckodriver-v0.19.0>
* Platform: <Windows 10>
* Firefox: <56.0 (64-bit)>
* Selenium: <selenium-server-standalone-3.5.3>

## Testcase

I'm using RemoteWebDriver and when i try to perform driver.quit(), selenium returns an exception.
Code Example:

```
public static void main(String[] args) {
	try {
		
		DesiredCapabilities dr = DesiredCapabilities.firefox();
		WebDriver driver = new RemoteWebDriver(new URL("http://localhost:5555/wd/hub"), dr);

		driver.manage().window().maximize();
		driver.get("https://google.pt");
		
		driver.close();
		driver.quit();
	} catch (Exception e) {
		e.printStackTrace();
	}
}
```

## Stacktrace

```
org.openqa.selenium.SessionNotCreatedException: Tried to run command without establishing a connection
Build info: version: '3.5.3', revision: 'a88d25fe6b', time: '2017-08-29T12:54:15.039Z'
System info: host: 'AAAA', ip: '127.0.0.1', os.name: 'Windows 10', os.arch: 'x86', os.version: '10.0', java.version: '1.8.0_141'
Driver info: driver.version: unknown
Command duration or timeout: 154 milliseconds
Build info: version: 'unknown', revision: '3169782', time: '2016-09-29 10:24:50 -0700'
System info: host: 'AAAA', ip: '127.0.0.1', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_131'
Driver info: org.openqa.selenium.remote.RemoteWebDriver
Capabilities [{moz:profile=C:\Users\AAAA\AppData\Local\Temp\rust_mozprofile.jQvCaYoQFPAD, rotatable=false, timeouts={implicit=0, pageLoad=300000, script=30000}, pageLoadStrategy=normal, moz:headless=false, platform=ANY, specificationLevel=0, moz:accessibilityChecks=false, acceptInsecureCerts=false, browserVersion=56.0, platformVersion=10.0, moz:processID=10048, browserName=firefox, platformName=windows_nt}]
Session ID: 2ac50a12-90af-48bf-af07-66bb06cd270a
```

## Trace-level log

[trace_log.txt](https://github.com/mozilla/geckodriver/files/1495731/trace_log.txt)

**Comment by rahull** [comment] 2017-11-22 12:28
@TPinheiroDias You are calling  driver.quit(); after calling driver.close()

If there is only one browser window open and you use driver.close(), it will quit the webdriver session.
In your case you are calling driver.quite() on deleted session .  Just use driver.quite() for above test case.

**Comment by whimboo** [comment] 2017-11-27 13:35
It's a dupe of issue #966.

**Closed by whimboo** 2017-11-27 13:35 UTC
