### ISSUE TITLE
SessionNotCreatedException: Message: Unable to find a matching set of capabilities

### ISSUE THREAD

**Issue by choosebest** [mozilla/geckodriver#1168] opened 2018-02-08 22:06 UTC
## System
* Version: geckodriver : 0.18.0-win32
* Platform:  Windows 10
* Firefox: 57.0 (64 bit)
* Selenium: 
Python 2.7.14
Robot Framework 3.0.2
wxPython 2.18.12.1 (unicode) for Python 2.7
RIDE 1.5.2.1.on Python2.7.14

## Testcase

*** Settings ***
Library Selenium2Library

*** Test Cases ***
Open URL
Open Browser http://www.firefox.com ff

Just try to open a web page on Windows 10, got the following error -
FAIL - SessionNotCreatedException: Message: Unable to find a matching set of capabilities

Is there a table shows working Firefox, geckodriver, wxPython, Robot, RIDE versions on Windows10?

## Trace-level log

==============================================================================
20180208 13:43:30.075 - INFO - + START SUITE: RF Hello World [ ]
==============================================================================
20180208 13:43:30.076 - INFO - +- START TEST: Open URL [ ]
------------------------------------------------------------------------------
20180208 13:43:30.076 - INFO - +-- START KW: Selenium2Library.Open Browser [ http://www.firefox.com | ff ]
20180208 13:43:30.077 - INFO - Opening browser 'ff' to base url 'http://www.firefox.com'.
20180208 13:43:32.324 - INFO - +--- START KW: Selenium2Library.Capture Page Screenshot [ ]
20180208 13:43:32.326 - INFO - Cannot capture screenshot because no browser is open.
20180208 13:43:32.326 - INFO - +--- END KW: Selenium2Library.Capture Page Screenshot (2)
20180208 13:43:32.329 - FAIL - SessionNotCreatedException: Message: Unable to find a matching set of capabilities
20180208 13:43:32.330 - DEBUG - Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\SeleniumLibrary\__init__.py", line 360, in run_keyword
    return DynamicCore.run_keyword(self, name, args, kwargs)
  File "C:\Python27\lib\site-packages\SeleniumLibrary\base\robotlibcore.py", line 102, in run_keyword
    return self.keywords[name](*args, **kwargs)
  File "C:\Python27\lib\site-packages\SeleniumLibrary\keywords\browsermanagement.py", line 145, in open_browser
    ff_profile_dir, remote_url)
  File "C:\Python27\lib\site-packages\SeleniumLibrary\keywords\browsermanagement.py", line 441, in _make_driver
    driver = creation_func(remote, desired_capabilities, profile_dir)
  File "C:\Python27\lib\site-packages\SeleniumLibrary\keywords\browsermanagement.py", line 459, in _make_ff
    **self._geckodriver_log_config)
  File "C:\Python27\lib\site-packages\selenium\webdriver\firefox\webdriver.py", line 158, in __init__
    keep_alive=True)
  File "C:\Python27\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 154, in __init__
    self.start_session(desired_capabilities, browser_profile)
  File "C:\Python27\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 243, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "C:\Python27\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 311, in execute
    self.error_handler.check_response(response)
  File "C:\Python27\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 237, in check_response
    raise exception_class(message, screen, stacktrace)
20180208 13:43:32.330 - INFO - +-- END KW: Selenium2Library.Open Browser (2254)
------------------------------------------------------------------------------
20180208 13:43:32.339 - INFO - +- END TEST: Open URL (2262)
------------------------------------------------------------------------------
20180208 13:43:32.342 - INFO - + END SUITE: RF Hello World (2731)
==============================================================================

**Comment by andreastt** [comment] 2018-02-08 22:36
Could you please attach a [trace-level log] from geckodriver? Read more about reporting actionable bugs in our [contribution guidelines].

[trace-level log]: https://searchfox.org/mozilla-central/source/testing/geckodriver/doc/TraceLogs.md
[contribution guidelines]: https://searchfox.org/mozilla-central/source/testing/geckodriver/CONTRIBUTING.md#reporting-bugs

**Comment by whimboo** [comment] 2018-02-12 10:43
What is the platform capability as passed in? Is it `windows_nt` or `windows` or something else? Please be aware of issue #1030 this might be a dupe of.

**Comment by AutomatedTester** [comment] 2018-02-27 10:24
Duplicate of #1030

**Closed by AutomatedTester** 2018-02-27 10:24 UTC
Labels: waiting for reporter feedback

**Comment by DvaKompota** [comment] 2019-08-14 22:41
Had the same problem on a very similar system. The reason appeared to be this:
Version: geckodriver : 0.18.0-**win32**
Firefox: 57.0 (**64 bit**)

So just replace you 32-bit geckodriver with a 64-bit version and it may solve your problem just like it did with mine.

**Comment by andreastt** [comment] 2019-08-15 07:05
If 32- vs. 64-bit makes a difference that is surprising as there’s nothing in geckodriver that is architecture dependent. To communicate with Firefox it uses a transparent TCP networking protocol, and does not rely on bitwise-specific COM operations like the IEDriver.

As I understand it, Windows ships with a 32-bit compatibility layer that allows 32-bit executables to be run on 64-bit systems. Of course you _should always_ prefer the 64-bit if your system supports it…

**Comment by whimboo** [comment] 2019-08-16 08:31
@andreastt the problem here is that a 32bit executable of geckodriver will check a different path in the Registry than the 64bit one. As such a 64bit installation of Firefox cannot be found. It might be similar vice versa. As such we always might have to check for both a 32bit and 64bit installation of Firefox.

As what I just found issue #1045 should cover that.
