### ISSUE TITLE
Can't input full string into textfield using python+selenium

### ISSUE THREAD

**Issue by fionazzz** [mozilla/geckodriver#1395] opened 2018-10-11 09:08 UTC
## System

* Version: 
* Platform: <!Windows 7 & Windows10>
* Firefox: <!62.0.3(32bit) on win7 and 57.0.4(64bit) on win10>
* Selenium: <!selenium 3.12.0>

## Testcase
Using selenium
1.open www.zoom.us/join
2.input '1234567890' in join-confno textfield  [ textfield.send_keys('1234567890') or driver.execute_execute_script(....) ]
You can see that the text displayed in textfield is incomplete.

If I set javascript to False in FirefoxProfile, the case will pass.
Using Chromedriver  or IEdriver won't have this issue.

![geckodriver_sendkeys](https://user-images.githubusercontent.com/25630797/46792887-f086c800-cd76-11e8-8dbc-b7c00d6b65fb.png)

**Comment by whimboo** [comment] 2018-10-16 08:08
Could you please attach a [trace-level log] from geckodriver? Read more about reporting actionable bugs in our [contribution guidelines].

Also I cannot reproduce this problem locally with the mentioned release of Firefox nor a Nightly build.

[trace-level log]: https://firefox-source-docs.mozilla.org/testing/geckodriver/geckodriver/TraceLogs.html
[contribution guidelines]: https://firefox-source-docs.mozilla.org/testing/geckodriver/geckodriver/Bugs.html

**Comment by whimboo** [comment] 2019-01-16 14:19
No report from the reporter anymore. Closing the issue.

**Closed by whimboo** 2019-01-16 14:19 UTC
