### ISSUE TITLE
driver.close() and failed to decode marionette

### ISSUE THREAD

**Issue by kindut** [mozilla/geckodriver#172] opened 2016-08-11 03:40 UTC
Failed to decode marionette.

Using selenium 2.53.6 with Firefox 48.

When opening an additional window (target="_blank") and then later closing that window in order to open another one, the window closes with driver.close(), but fails to release from memory, so that after x-amount of times opening and closing windows.

**Comment by andreastt** [comment] 2016-08-12 13:47
I don’t understand. Can you please explain exactly what fails to be released from memory?

**Comment by locksley** [comment] 2016-08-23 22:12
I'm able to reproduce the problem with Selenium 3.0.0, Firefox v48.01, and geckodriver v0.10.0. Code to repro (in Java):

`
System.setProperty("webdriver.gecko.driver", "geckodriver.exe");

DesiredCapabilities capabilities = DesiredCapabilities.firefox();
capabilities.setCapability("marionette", true);
WebDriver driver = new FirefoxDriver(capabilities);
driver.close();
`

Stepping through the code, I see that `execute(DriverCommand.CLOSE)` in RemoveWebDriver is called but the Firefox window does not close.

`execute(DriverCommand.QUIT)`, however, succeeds.

**Comment by saladisathish** [comment] 2016-08-26 21:44
This is reproducible in Firefox 48.0.2, Selenium-java-3.0.0-beta2, geckodriver v0.10.0... driver.close() doesnt close the firefox. Here is the code to reproduce:
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.remote.DesiredCapabilities;

public class TesterFile {

public static WebDriver wd;
public static void main(String[] args) {

System.setProperty("webdriver.gecko.driver","C:\\Users\\<User>\\tools\\geckodriver.exe");
wd = new FirefoxDriver();
wd.get("http://www.google.com");

wd.close();
}
}

**Comment by harshg0910** [comment] 2016-09-30 09:49
I am also facing same issue as @saladisathish 
When I enabled logs in marionette and execute close(), I saw following log
1475228240058	Marionette	INFO	sendAsync null

Normally I could see following logs
1475228236266	Marionette	INFO	sendAsync #SOME-HASH_VALUE

Seems like there is failure in sending/receiving command itself.
@andreastt  : I'm not clear why related issue #198 was closed. Can you please update ?

**Comment by andreastt** [comment] 2016-09-30 10:08
@kindut I still have no idea what this issue is about. Some of the comments made in this conversation seem unrelated.

@harshg0910 The sendAsync log entry is nothing to worry about. It’s some debug code that was accidentally logged to INFO. It has since been removed. I would recommend upgrading to [Firefox Nightly](http://nightly.mozilla.org/).

Issue #198 was closed because it was not reproducible.

**Comment by harshg0910** [comment] 2016-09-30 12:30
@andreastt 
Are you able to properly close browser ?
My code hangs when I call this 
    wd = new FirefoxDriver();
    wd.close();

If you are not getting this issue, I'll share complete test code to reproduce.

**Comment by andreastt** [comment] 2016-10-18 12:19
Closing this in favour of https://github.com/mozilla/geckodriver/issues/285.

**Closed by andreastt** 2016-10-18 12:19 UTC

**Comment by snpanigrahi9** [comment] 2017-03-10 11:52
Today I tested with gecko driver 0.15 and selenium client library 3.3.0
Firefox 52.0

Still its not closing the browser using driver.close();
