### ISSUE TITLE
Clicking element that closes top-level browsing context causes crash

### ISSUE THREAD

**Issue by bicarbon8** [mozilla/geckodriver#320] opened 2016-11-04 16:53 UTC
when using geckodriver.exe 0.11.0 with Selenium 3.0.0 (C#) and Firefox 49.0.2 to click on an IWebElement that closes the currently active window a WebDriverException is returned on the actual call to _element.Click()_ with a message of `The HTTP request to the remote WebDriver server for URL http://localhost:55555/session/e2f5ee11-7a60-49dc-a9ac-b893a075edea/element/e72123d9-2b18-41b7-8096-795016b44637/click timed out after 10 seconds`

## The following code was used to induce the issue:
```
string codeBase = Assembly.GetExecutingAssembly().CodeBase;
UriBuilder uri = new UriBuilder(codeBase);
string path = Uri.UnescapeDataString(uri.Path);
string dir = Path.GetDirectoryName(path);
string indexPath = string.Format("file:///{0}/index.html", dir);

FirefoxDriver driver = new FirefoxDriver(FirefoxDriverService.CreateDefaultService(), new FirefoxOptions(), TimeSpan.FromSeconds(10));
driver.Navigate().GoToUrl(indexPath);

// get button that opens sub-page
IWebElement button = driver.FindElement(By.Id("button"));

// get current window handle
string indexHandle = driver.CurrentWindowHandle;

// click and switch to pupup window (sub-page)
PopupWindowFinder finder = new PopupWindowFinder(driver);
string handle = finder.Click(button);
driver.SwitchTo().Window(handle);

// get button that closes sub-page
IWebElement closeButton = null;
WebDriverWait wait = new WebDriverWait(driver, TimeSpan.FromSeconds(10));
wait.Until(d =>
{
    closeButton = driver.FindElement(By.Id("closeButton"));
    return closeButton != null;
});

// click on close button (***!!!CRASH!!!***)
closeButton.Click();

// switch back to index window
driver.SwitchTo().Window(indexHandle);
```

### _index.html_
```
﻿<!DOCTYPE html>
<html lang="en" xmlns="http://www.w3.org/1999/xhtml">
<head>
    <meta charset="utf-8" />
</head>
<body style="min-width: 1135px">
    <div id="dropdownContainer">
        <div class="btn-group" role="group" aria-label="...">
            <button type="button" id="button" onclick="window.open('subPage.html', 'subPage', 'menubar=no,resizable=no,scrollbars=no');" class="btn btn-default">Open SubPage</button>
        </div>
    </div>
</body>
</html>
```
### _subPage.html_
```
<!DOCTYPE html>
<html lang="en" xmlns="http://www.w3.org/1999/xhtml">
<head>
    <meta charset="utf-8" />
</head>
<body style="max-width: 400px; max-height: 300px;">
    <div id="buttonContainer">
        <button type="button" id="closeButton" onclick="window.close();" class="btn btn-default">Close SubPage</button>
    </div>
</body>
</html>
```

## Other browsers
The same code was tested and run successfully using ChromeDriver 2.25.0.0 and Selenium 3.0.0 so I believe the issue to be with geckodriver's handling of the `window.close();` call in javascript.

## Temporary workaround
Adding in the following to the javascript on the page allows enough time for the `element.Click();` call to complete so no error occurs, but this is less than optimal to have to do for each page loaded:
```
((IJavaScriptExecutor)driver).ExecuteScript("var windowClose = windowClose || window.close; window.close = function() { setTimeout(function() { windowClose(); }, 2000); };");
```

**Comment by andreastt** [comment] 2017-01-04 08:16
When you say it “crashes”, what exception/stacktrace are you seeing?

Can you please also include a trace-level verbose geckodriver log (as it said in the issue template!). You can see the README on how to configure it.

**Comment by bicarbon8** [comment] 2017-01-04 14:07
@andreastt , apologies for not including the logs... by the time I completed the rest of the information I seem to have either forgotten about the logs or just not seen them in the template... here is what I get from the logs when set to Trace level:
[traceLog.txt](https://github.com/mozilla/geckodriver/files/684815/traceLog.txt)

**Comment by andreastt** [comment] 2017-04-07 15:15
Closed as duplicate of https://github.com/mozilla/geckodriver/issues/611.

**Closed by andreastt** 2017-04-07 15:15 UTC
Labels: marionette
