### ISSUE TITLE
isDisplayed throws NullPointerException

### ISSUE THREAD

**Issue by andcanit** [mozilla/geckodriver#1825] opened 2020-12-24 08:34 UTC
## System

* Version: geckodriver 0.28.0 (c00d2b6acd3f 2020-11-03 16:29 +0200)
* Platform: Windows 10
* Firefox: 84.0.1
* Selenium: 3.141.59 Java binding

## Testcase

`driver.findElement(By.cssSelector("html")).isDisplayed()`

## Stacktrace

`java.lang.NullPointerException: null
	at org.openqa.selenium.remote.RemoteWebElement.isDisplayed(RemoteWebElement.java:329)`

**Comment by whimboo** [comment] 2020-12-27 13:24
Could you please attach a [trace-level log] from geckodriver? Read more about reporting actionable bugs in our [contribution guidelines].

[trace-level log]: https://firefox-source-docs.mozilla.org/testing/geckodriver/TraceLogs.html
[contribution guidelines]: https://firefox-source-docs.mozilla.org/testing/geckodriver/Bugs.html

**Comment by PiotrZgadzaj** [comment] 2021-02-23 21:17
I also run into this problem after FF upgrade. My setup is:

FF 85.0
Geckodriver 0.29.0
Selenium 3.11

I will provide trace logs if only i will be able to reproduce the problem with traces enabled. What i can add for now is that screenshot made right after the failure shows an blank page (empty html)

**Comment by whimboo** [comment] 2021-02-24 09:06
Yes, trace logs would be very helpful. Maybe that is related to https://bugzilla.mozilla.org/show_bug.cgi?id=1693252. But hard to say with the information as given so far.

**Comment by PiotrZgadzaj** [comment] 2021-03-11 11:22
I still don't have trace logs. It seems that the problem is not reproducible when i run the scenario locally on Ubuntu 16, but when executed the same scenario on our company Cloud it happens from time to time.

What i wanted to say in my previous comment is that, it seems this happens in following scenarios

1. We have no-stale releference to an element of the page (WebElement). 
2. Then some action on page is made which makes the page reload

Sometimes, when during page reload, webElement.isDisplayed() is triggered such a null pointer is thrown. From my observation, it seems that always when it happens, browser did not start rendering the response yet - page is blank, no html

**Comment by whimboo** [comment] 2021-03-11 12:08
Note that `WebDriver:Refresh` waits for the page to be loaded. So if you run other commands at that time do you have a `pageLoadStrategy` of `None`?

**Comment by PiotrZgadzaj** [comment] 2021-03-11 12:13
Refresh is not done by triggering webDriver.refresh. But by making a post, either as a result of selenium click or by Javascript which does the submit

**Comment by whimboo** [comment] 2021-03-11 13:30
Note that `WebDriver:ElementClick` also waits for the page to be loaded. Javascript is indeed different.

**Comment by PiotrZgadzaj** [comment] 2021-03-11 20:22
I was able to finally reproduce the problem so i have trace logs.

Scenario is as follows
1. Near log with timestamp 1615489837466, button which submits the page is clicked
2. Response is back - at 1615489840712, it's rendered and from that point, in a loop, test is checking if certain element disappeared from the page (initially, after response is rendered, the element is displayed. However there is a pooling in JS implemented which triggers AJAX requests and when AJAX says, that element has to be hidden, then it disappears).
That loop is done without normal selenium Expected conditions, just normal java loop, to ensure that frequency of checking if element disappeared is high enough to produce the NullPointerException
3. Last check if element is there is done at 1615489840524 and it produces the NullPointerException
4. Near 1615489840578 you see my code which is doing the screenshot + html dump
[ff_cut.log](https://github.com/mozilla/geckodriver/files/6125766/ff_cut.log)


Java code which does the checking (whole loop):
`        while (true) {
            try {
                System.out.println(new Date().getTime());
                List<WebElement> element = getDriver().findElements(By.xpath(
                        "//div[contains(@class, 'authorisationDetailsDialog')]"));
                if (element == null || element.isEmpty() || !element.get(0).isDisplayed()) {
                    return;
                }
            } catch (StaleElementReferenceException e) {
                //ignore
            }
        }`

**Comment by whimboo** [comment] 2021-03-11 21:24
@PiotrZgadzaj thank you for the log! It was pretty helpful.

So I had a look and in the full log I cannot find a single call to `WebDriver:IsElementDisplayed`, which would be the WebDriver specific implementation in geckodriver. That said the `isDisplayed()` method as implemented in your Selenium binding is actually running some custom Javascript code, which is failing here. This is outside of the scope of geckodriver, and should be reported on the appropriate repository. Don't ask me why this is done...

Given that @andcanit is also using the Java bindings I'm going to close this issue as invalid.

**Closed by whimboo** 2021-03-11 21:24 UTC
Labels: awaiting reporter feedback, marionette

**Comment by whimboo** [comment] 2021-03-11 21:28
Sorry, I have to partly correct myself. There is no spec'ed `Is Element Displayed` command. As such each binding is using that custom JS code.
