### ISSUE TITLE
Repeated alert not handled properly

### ISSUE THREAD

**Issue by prnysarker** [mozilla/geckodriver#1524] opened 2019-03-18 05:45 UTC
## System

* Version: 0.24.0
* Platform: Windows 10
* Firefox: 65.0.2
* Selenium: 3.141.59

## Testcase
In a scenario there can be multiple alert need to consume all alerts. 

Accepting first alert works fine but when the second alert comes driver is not able to switch to the next alert it throws NoAlertPresentException. This was working fine upto 60.0.1  after upgrading to 65.0.2 it started failing.
[Formated](https://pastebin.com/xdB65HKP)
`public static void main(String[] args){
    System.setProperty("webdriver.gecko.driver","C:/webdriver/GeckoDriver/windows/64bit/geckodriver.exe");
    WebDriver driver = new FirefoxDriver();
    String baseUrl = "file:///C:/verify.html";
    driver.get(driver.findElements(By.xpath("//button[contains(text(),'Genrate')]")).get(0).click(); 
    int i = 4; //Asuming there is 4 alerts
    while (i > 0) {
        Alert x = driver.switchTo().alert(); //throws exception here, on second time
        x.accept();
        i--;
    }
    driver.close();
}`
**HTML**
[Codepen](https://codepen.io/prny/pen/MxXJOr)

## Stacktrace
[Formated](https://pastebin.com/QDtmJSVD)
`Exception in thread "main" org.openqa.selenium.NoAlertPresentException: 
Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:25:53'
System info: host: 'XXXXXX', ip: 'X', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_191'
Driver info: org.openqa.selenium.firefox.FirefoxDriver
Capabilities {acceptInsecureCerts: true, browserName: firefox, browserVersion: 65.0.2, javascriptEnabled: true, moz:accessibilityChecks: false, moz:geckodriverVersion: 0.24.0, moz:headless: false, moz:processID: 15172, moz:profile: C:\Users\XXXX\AppData\Local..., moz:shutdownTimeout: 60000, moz:useNonSpecCompliantPointerOrigin: false, moz:webdriverClick: true, pageLoadStrategy: normal, platform: WINDOWS, platformName: WINDOWS, platformVersion: 10.0, rotatable: false, setWindowRect: true, strictFileInteractability: false, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}, unhandledPromptBehavior: dismiss and notify}
Session ID: 06e0ed3b-cd80-4902-93b1-6a52c800ca5d
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
	at java.lang.reflect.Constructor.newInstance(Unknown Source)
	at org.openqa.selenium.remote.http.W3CHttpResponseCodec.createException(W3CHttpResponseCodec.java:187)
	at org.openqa.selenium.remote.http.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:122)
	at org.openqa.selenium.remote.http.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:49)
	at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:158)
	at org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:83)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:552)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:609)
	at org.openqa.selenium.remote.RemoteWebDriver$RemoteTargetLocator.alert(RemoteWebDriver.java:932)
	at Index.main(Index.java:43)
`

## Trace-level log
[Formated](https://pastebin.com/002YPdYf)
`1552889862529	mozrunner::runner	INFO	Running command: "C:\\Program Files\\Mozilla Firefox\\firefox.exe" "-marionette" "-foreground" "-no-remote" "-profile" "C:\\Users\\XXXXX\\AppData\\Local\\Temp\\rust_mozprofile.DytjPPXNZF1o"
1552889863432	addons.webextension.screenshots@mozilla.org	WARN	Loading extension 'screenshots@mozilla.org': Reading manifest: Invalid host permission: resource://pdf.js/
1552889863432	addons.webextension.screenshots@mozilla.org	WARN	Loading extension 'screenshots@mozilla.org': Reading manifest: Invalid host permission: about:reader*
1552889865703	Marionette	INFO	Listening on port 62296
1552889865769	Marionette	WARN	TLS certificate errors will be ignored for this session
Mar 18, 2019 11:47:46 AM org.openqa.selenium.remote.ProtocolHandshake createSession
INFO: Detected dialect: W3C
[Child 9884, Chrome_ChildThread] WARNING: pipe error: 109: file z:/build/build/src/ipc/chromium/src/chrome/common/ipc_channel_win.cc, line 332
[Child 9884, Chrom1552889867373	Marionette	WARN	TimedPromise timed out after 500 ms: stacktrace:
bail@chrome://marionette/content/sync.js:196:64
openRemotePrompt@jar:file:///C:/Program%20Files/Mozilla%20Firefox/omni.ja!/components/nsPrompter.js:507:5
openPrompt@jar:file:///C:/Program%20Files/Mozilla%20Firefox/omni.ja!/components/nsPrompter.js:541:17
alertCheck@jar:file:///C:/Program%20Files/Mozilla%20Firefox/omni.ja!/components/nsPrompter.js:629:9
genrateAlert@file:///C:/Users/XXXXX/Desktop/placeholder/ANT%20scen/verify.html:7:4
onclick@file:///C:/Users/XXXXX/Desktop/placeholder/ANT%20scen/verify.html:1:1
event.synthesizeMouseAtPoint@chrome://marionette/content/event.js:202:5
webdriverClickElement@chrome://marionette/content/interaction.js:183:5`

**Comment by whimboo** [comment] 2019-03-19 09:36
dupe of #620.

**Closed by whimboo** 2019-03-19 09:36 UTC

**Comment by prnysarker** [comment] 2019-03-20 09:13
> dupe of #620.

Hi @whimboo , Looks like both issues are different , my test were working perfectly upto 60.0.1 version, the linked issue is on 55. 

In my case, First alert handles properly, but when the second alert comes the driver is not able to switch to the new alert, `driver.switchTo().alert();` on this line it throws `NoAlertPresentException` . Please reconsider it to open.

Thanks

**Comment by whimboo** [comment] 2019-03-27 12:38
The version of Firefox doesn't matter here. As long as it it not fixed all version will fail to handle multiple open alerts.
