### ISSUE TITLE
how to get geckodriver sourcecode incl. Cargo.lock for specific geckodriver release?

### ISSUE THREAD

**Issue by das-g** [mozilla/geckodriver#1427] opened 2018-11-15 01:58 UTC
## System

* Version: e.g. 0.23.0
* Platform: NixOS unstable
* Firefox: 63.0
* Selenium: 3.141.0

## Usecase

I'd like to update the NixOS package [geckodriver](https://github.com/NixOS/nixpkgs/blob/a4c4cbb613cc3e15186de0fdb04082fa7e38f6a0/pkgs/development/tools/geckodriver/default.nix). Currently, [it refers](https://github.com/NixOS/nixpkgs/blob/a4c4cbb613cc3e15186de0fdb04082fa7e38f6a0/pkgs/development/tools/geckodriver/default.nix#L15) to _some_ `mozilla/gecko-dev` revision ([ecb86060b4](https://github.com/mozilla/gecko-dev/tree/ecb86060b4c5a9808798b81a57e79e821bb47082)) that probably doesn't correspond to any actual geckodriver release. (The resulting binary reports to be `geckodriver 0.19.1` when called with `--version`).

I'd like to get the package back in sync with an actual release, and at that a recent enough one to be compatible with the Firefox version 63.0 currently included in nixpkgs. For that, I need the cargo-buildable geckodriver source for a specific release (e.g. 0.23.0) **including** `Cargo.lock`. (Because Nix, NixOS and nixpkgs are all about reproducibility.)

## Question

Thus: How do I **obtain the geckodriver source code including `Cargo.lock` _for a specific release_**?

## Current difficulty

For recent releases, this repo here (github.com/mozilla/geckodriver) doesn't include `Cargo.lock` anymore. (It got removed in 24b44bf63b92aaa614e20e93ff4e2bb31489cb06.) https://github.com/mozilla/geckodriver/issues/1403#issuecomment-431374278 seems to imply that that's intentional and that it should be obtained from mozilla-central, but it's unclear to me how to obtain a revision corresponding to a specific geckodriver release from there. Dito for github.com/mozilla/gecko-dev, which seem to still ([or again?](https://github.com/mozilla/gecko-dev/commit/0ba01aed1b23b0369b810aa3b846bb360a7bf96a#diff-fea904e75a3579e40d9bd3f70c331c02)) include the file in its `testing/geckodriver` subdir, but doesn't seem to feature any geckodriver-release-specific tags.

**Comment by whimboo** [comment] 2018-11-15 08:06
Dupe of issue #1403.

**Comment by das-g** [comment] 2018-11-15 09:23
Please re-open.

#1403 and the documentation linked there doesn't answer the question
> How do I obtain the geckodriver source code including Cargo.lock for a specific release?

**Closed** 2018-11-16 08:00 UTC
Labels: duplicate

**Comment by das-g** [comment] 2018-11-16 08:19
I see you've re-opened #1403, @whimboo. Is the plan thus to include `Cargo.lock` in github.com/mozilla/geckodriver again? If so, will git tags for existing releases and/or release source archive downloads be changed accordingly?

Or will the question
> How do I obtain the geckodriver source code including `Cargo.lock` for a specific release?

be answered otherwise, be it here on the issue tracker or in the documentation?

Note that a way to look up the respective `Cargo.lock` version used for each geckodriver release would suffice for now &mdash;  `Cargo.lock` and the rest of the code don't necessarily need to come from the same repo/source location as long as we can match them to releases somehow.

**Comment by andreastt** [comment] 2018-11-16 13:08
I’ve synced the README.md change from https://bugzilla.mozilla.org/show_bug.cgi?id=1500938 over to the GitHub repository in https://github.com/mozilla/geckodriver/commit/fd75e69bdcb37c917d9da36d23298e06346fdccc. There’s now a new _Source code_ section here: https://github.com/mozilla/geckodriver#source-code

It says:

> geckodriver’s canonical source code can be found in [mozilla-central](https://hg.mozilla.org/mozilla-central/file/tip/testing/geckodriver). We only use this GitHub repository for issue tracking and making releases. See our [contribution documentation](https://firefox-source-docs.mozilla.org/testing/geckodriver/geckodriver/#for-developers) for more information.

**Comment by das-g** [comment] 2018-11-16 17:42
Are there any [tags](https://hg.mozilla.org/mozilla-central/tags) that correspond to geckodriver releases? Or is there another way to identify the revision corresponding to a geckodriver releases?

**Comment by whimboo** [comment] 2018-11-16 19:08
Please follow-up on the other issue. This one is closed.
