### ISSUE TITLE
0.19.1/FF 56.0.2 Second invisible browser window with red/blue/green squares prevents the simplest test to run

### ISSUE THREAD

**Issue by lega-land** [mozilla/geckodriver#1043] opened 2017-11-03 13:59 UTC
## System
* Version: 0.19.1
* Platform: Windows 7
* Firefox: 56.0.2 (x64)
* Selenium: 3.6.0

## Testcase
Run test() as JUnit:
```
    @Test
    public void test() {
        System.setProperty("webdriver.gecko.driver", "C:\\temp\\geckodriver.exe");
        WebDriver driver = new FirefoxDriver();
        driver.get("http://google.com");
        Thread.sleep(5000);
        driver.close();
    }
```
There are 2 FF windows shown in taskbar. One of them is invisible with some red/blue/green squares (see screenshot below).
**Note: If I close that invisible window test proceeds as expected with no errors or delays.**

## Stacktrace
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:422)
	at org.openqa.selenium.remote.W3CHandshakeResponse.lambda$new$0(W3CHandshakeResponse.java:57)
	at org.openqa.selenium.remote.W3CHandshakeResponse.lambda$getResponseFunction$2(W3CHandshakeResponse.java:104)
	at org.openqa.selenium.remote.ProtocolHandshake.lambda$createSession$24(ProtocolHandshake.java:359)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
	at java.util.Spliterators$ArraySpliterator.tryAdvance(Spliterators.java:958)
	at java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:126)
	at java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:498)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:485)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.FindOps$FindOp.evaluateSequential(FindOps.java:152)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.findFirst(ReferencePipeline.java:464)
	at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:362)
	at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:136)
	at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:142)
	at org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:83)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:586)
	at org.openqa.selenium.remote.RemoteWebDriver.startSession(RemoteWebDriver.java:217)
	at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:140)
	at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:120)
	at Test.test(Test.java:15)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:47)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)

## Trace-level log
```
1509714634200	geckodriver	INFO	geckodriver 0.19.1
1509714634216	geckodriver	INFO	Listening on 127.0.0.1:42071
1509714634732	mozrunner::runner	INFO	Running command: "C:/Program Files (x86)/Mozilla Firefox/firefox.exe" "-marionette" "-profile" "C:\\Users\\oyatsun\\AppData\\Local\\Temp\\rust_mozprofile.t5vczLtX2Oji"
1509714635557	addons.xpi	WARN	Error parsing extensions state: [Exception... "Component returned failure code: 0x80520012 (NS_ERROR_FILE_NOT_FOUND) [amIAddonManagerStartup.readStartupData]"  nsresult: "0x80520012 (NS_ERROR_FILE_NOT_FOUND)"  location: "JS frame :: resource://gre/modules/addons/XPIProvider.jsm :: loadExtensionState :: line 1554"  data: no] Stack trace: loadExtensionState()@resource://gre/modules/addons/XPIProvider.jsm:1554 < getInstallState()@resource://gre/modules/addons/XPIProvider.jsm:1589 < checkForChanges()@resource://gre/modules/addons/XPIProvider.jsm:3109 < startup()@resource://gre/modules/addons/XPIProvider.jsm:2188 < callProvider()@resource://gre/modules/AddonManager.jsm:269 < _startProvider()@resource://gre/modules/AddonManager.jsm:739 < startup()@resource://gre/modules/AddonManager.jsm:906 < startup()@resource://gre/modules/AddonManager.jsm:3090 < observe()@jar:file:///C:/Program%20Files%20(x86)/Mozilla%20Firefox/omni.ja!/components/addonManager.js:65
1509714635881	Marionette	DEBUG	Received observer notification "profile-after-change"
1509714636060	Marionette	DEBUG	Received observer notification "command-line-startup"
1509714636060	Marionette	INFO	Enabled via --marionette
1509714636747	geckodriver::marionette	TRACE	  connection attempt 0/600
1509714636791	DeferredSave.extensions.json	WARN	Write failed: Win error 32 during operation move on file C:\Users\oyatsun\AppData\Local\Temp\rust_mozprofile.t5vczLtX2Oji\extensions.json.tmp (The process cannot access the file because it is being used by another process.
) ((unknown module)) No traceback available
1509714636793	addons.xpi-utils	WARN	Failed to save XPI database: Win error 32 during operation move on file C:\Users\oyatsun\AppData\Local\Temp\rust_mozprofile.t5vczLtX2Oji\extensions.json.tmp (The process cannot access the file because it is being used by another process.
) ((unknown module)) No traceback available
1509714636794	addons.xpi-utils	WARN	Failed to save XPI database: Win error 32 during operation move on file C:\Users\oyatsun\AppData\Local\Temp\rust_mozprofile.t5vczLtX2Oji\extensions.json.tmp (The process cannot access the file because it is being used by another process.
) ((unknown module)) No traceback available
1509714636794	addons.xpi-utils	WARN	Failed to save XPI database: Win error 32 during operation move on file C:\Users\oyatsun\AppData\Local\Temp\rust_mozprofile.t5vczLtX2Oji\extensions.json.tmp (The process cannot access the file because it is being used by another process.
) ((unknown module)) No traceback available
1509714636794	addons.xpi-utils	WARN	Failed to save XPI database: Win error 32 during operation move on file C:\Users\oyatsun\AppData\Local\Temp\rust_mozprofile.t5vczLtX2Oji\extensions.json.tmp (The process cannot access the file because it is being used by another process.
) ((unknown module)) No traceback available
1509714636794	addons.xpi-utils	WARN	Failed to save XPI database: Win error 32 during operation move on file C:\Users\oyatsun\AppData\Local\Temp\rust_mozprofile.t5vczLtX2Oji\extensions.json.tmp (The process cannot access the file because it is being used by another process.
) ((unknown module)) No traceback available
1509714636795	addons.xpi-utils	WARN	Failed to save XPI database: Win error 32 during operation move on file C:\Users\oyatsun\AppData\Local\Temp\rust_mozprofile.t5vczLtX2Oji\extensions.json.tmp (The process cannot access the file because it is being used by another process.
) ((unknown module)) No traceback available
1509714636795	addons.xpi-utils	WARN	Failed to save XPI database: Win error 32 during operation move on file C:\Users\oyatsun\AppData\Local\Temp\rust_mozprofile.t5vczLtX2Oji\extensions.json.tmp (The process cannot access the file because it is being used by another process.
) ((unknown module)) No traceback available
1509714636796	addons.xpi-utils	WARN	Failed to save XPI database: Win error 32 during operation move on file C:\Users\oyatsun\AppData\Local\Temp\rust_mozprofile.t5vczLtX2Oji\extensions.json.tmp (The process cannot access the file because it is being used by another process.
) ((unknown module)) No traceback available
1509714636796	addons.xpi-utils	WARN	Failed to save XPI database: Win error 32 during operation move on file C:\Users\oyatsun\AppData\Local\Temp\rust_mozprofile.t5vczLtX2Oji\extensions.json.tmp (The process cannot access the file because it is being used by another process.
) ((unknown module)) No traceback available
1509714636796	addons.xpi-utils	WARN	Failed to save XPI database: Win error 32 during operation move on file C:\Users\oyatsun\AppData\Local\Temp\rust_mozprofile.t5vczLtX2Oji\extensions.json.tmp (The process cannot access the file because it is being used by another process.
) ((unknown module)) No traceback available
1509714636796	addons.xpi-utils	WARN	Failed to save XPI database: Win error 32 during operation move on file C:\Users\oyatsun\AppData\Local\Temp\rust_mozprofile.t5vczLtX2Oji\extensions.json.tmp (The process cannot access the file because it is being used by another process.
) ((unknown module)) No traceback available
1509714636796	addons.xpi-utils	WARN	Failed to save XPI database: Win error 32 during operation move on file C:\Users\oyatsun\AppData\Local\Temp\rust_mozprofile.t5vczLtX2Oji\extensions.json.tmp (The process cannot access the file because it is being used by another process.
) ((unknown module)) No traceback available
1509714636797	addons.xpi-utils	WARN	Failed to save XPI database: Win error 32 during operation move on file C:\Users\oyatsun\AppData\Local\Temp\rust_mozprofile.t5vczLtX2Oji\extensions.json.tmp (The process cannot access the file because it is being used by another process.
) ((unknown module)) No traceback available
1509714636797	addons.xpi-utils	WARN	Failed to save XPI database: Win error 32 during operation move on file C:\Users\oyatsun\AppData\Local\Temp\rust_mozprofile.t5vczLtX2Oji\extensions.json.tmp (The process cannot access the file because it is being used by another process.
) ((unknown module)) No traceback available
1509714636797	addons.xpi-utils	WARN	Failed to save XPI database: Win error 32 during operation move on file C:\Users\oyatsun\AppData\Local\Temp\rust_mozprofile.t5vczLtX2Oji\extensions.json.tmp (The process cannot access the file because it is being used by another process.
) ((unknown module)) No traceback available
1509714636798	addons.xpi-utils	WARN	Failed to save XPI database: Win error 32 during operation move on file C:\Users\oyatsun\AppData\Local\Temp\rust_mozprofile.t5vczLtX2Oji\extensions.json.tmp (The process cannot access the file because it is being used by another process.
) ((unknown module)) No traceback available
1509714636798	addons.xpi-utils	WARN	Failed to save XPI database: Win error 32 during operation move on file C:\Users\oyatsun\AppData\Local\Temp\rust_mozprofile.t5vczLtX2Oji\extensions.json.tmp (The process cannot access the file because it is being used by another process.
) ((unknown module)) No traceback available
1509714636798	addons.xpi-utils	WARN	Failed to save XPI database: Win error 32 during operation move on file C:\Users\oyatsun\AppData\Local\Temp\rust_mozprofile.t5vczLtX2Oji\extensions.json.tmp (The process cannot access the file because it is being used by another process.
) ((unknown module)) No traceback available
1509714636798	addons.xpi-utils	WARN	Failed to save XPI database: Win error 32 during operation move on file C:\Users\oyatsun\AppData\Local\Temp\rust_mozprofile.t5vczLtX2Oji\extensions.json.tmp (The process cannot access the file because it is being used by another process.
) ((unknown module)) No traceback available
1509714636799	addons.xpi-utils	WARN	Failed to save XPI database: Win error 32 during operation move on file C:\Users\oyatsun\AppData\Local\Temp\rust_mozprofile.t5vczLtX2Oji\extensions.json.tmp (The process cannot access the file because it is being used by another process.
) ((unknown module)) No traceback available
1509714636799	addons.xpi-utils	WARN	Failed to save XPI database: Win error 32 during operation move on file C:\Users\oyatsun\AppData\Local\Temp\rust_mozprofile.t5vczLtX2Oji\extensions.json.tmp (The process cannot access the file because it is being used by another process.
) ((unknown module)) No traceback available
1509714636799	addons.xpi-utils	WARN	Failed to save XPI database: Win error 32 during operation move on file C:\Users\oyatsun\AppData\Local\Temp\rust_mozprofile.t5vczLtX2Oji\extensions.json.tmp (The process cannot access the file because it is being used by another process.
) ((unknown module)) No traceback available
1509714636799	addons.xpi-utils	WARN	Failed to save XPI database: Win error 32 during operation move on file C:\Users\oyatsun\AppData\Local\Temp\rust_mozprofile.t5vczLtX2Oji\extensions.json.tmp (The process cannot access the file because it is being used by another process.
) ((unknown module)) No traceback available
1509714636799	addons.xpi-utils	WARN	Failed to save XPI database: Win error 32 during operation move on file C:\Users\oyatsun\AppData\Local\Temp\rust_mozprofile.t5vczLtX2Oji\extensions.json.tmp (The process cannot access the file because it is being used by another process.
) ((unknown module)) No traceback available
1509714636800	addons.xpi-utils	WARN	Failed to save XPI database: Win error 32 during operation move on file C:\Users\oyatsun\AppData\Local\Temp\rust_mozprofile.t5vczLtX2Oji\extensions.json.tmp (The process cannot access the file because it is being used by another process.
) ((unknown module)) No traceback available
Unable to read VR Path Registry from C:\Users\oyatsun\AppData\Local\openvr\openvrpaths.vrpath
JavaScript error: jar:file:///C:/Program%20Files%20(x86)/Mozilla%20Firefox/omni.ja!/components/SanityTest.js, line 69: NS_ERROR_FILE_IS_LOCKED: Component returned failure code: 0x8052000e (NS_ERROR_FILE_IS_LOCKED) [nsIPrefService.savePrefFile]
1509714637919	Marionette	DEBUG	Received observer notification "sessionstore-windows-restored"
JavaScript error: , line 0: NS_ERROR_FILE_IS_LOCKED: Component returned failure code: 0x8052000e (NS_ERROR_FILE_IS_LOCKED) [nsIAppStartup.trackStartupCrashEnd]
1509714638851	geckodriver::marionette	TRACE	  connection attempt 1/600
...
1509715902293	geckodriver::marionette	TRACE	  connection attempt 601/600
1509715902295	webdriver::server	DEBUG	<- 500 Internal Server Error {"value":{"error":"unknown error","message":"connection refused","stacktrace":"stack backtrace:\n   0:           0x47e934 - <no info>\n   1:           0x47f0a3 - <no info>\n   2:           0x442649 - <no info>\n   3:           0x4494e0 - <no info>\n   4:           0x42a890 - <no info>\n   5:           0x406f5e - <no info>\n   6:           0x40cfc9 - <no info>\n   7:           0x6bef19 - <no info>\n   8:           0x420756 - <no info>\n   9:           0x6b96e0 - <no info>\n  10:         0x775759cd - BaseThreadInitThunk"}}

org.openqa.selenium.WebDriverException: connection refused
Build info: version: '3.6.0', revision: '6fbf3ec767', time: '2017-09-27T15:28:36.4Z'
System info: host: 'OYATSUN', ip: '135.39.48.XX', os.name: 'Windows 7', os.arch: 'amd64', os.version: '6.1', java.version: '1.8.0_65'
Driver info: driver.version: FirefoxDriver
remote stacktrace: stack backtrace:
   0:           0x47e934 - <no info>
   1:           0x47f0a3 - <no info>
   2:           0x442649 - <no info>
   3:           0x4494e0 - <no info>
   4:           0x42a890 - <no info>
   5:           0x406f5e - <no info>
   6:           0x40cfc9 - <no info>
   7:           0x6bef19 - <no info>
   8:           0x420756 - <no info>
   9:           0x6b96e0 - <no info>
  10:         0x775759cd - BaseThreadInitThunk
```

## Screenshot
![default](https://user-images.githubusercontent.com/12608090/32375490-729836ba-c0aa-11e7-9585-3c080d4a0067.png)

**Comment by andreastt** [comment] 2017-11-03 16:12
@whimboo Could this be the graphics test window that is meant to be hidden? It appears it somehow prevents the Marionette server from starting. I don’t think I’ve ever seen this before, but I’m wiling to bet it’s a bug in Firefox.

@lega-land Can you navigate to about:support, click the ‘Copy text to clipboard’ and paste it somewhere, please?

**Comment by lega-land** [comment] 2017-11-03 16:46
@andreastt,
[support.txt](https://github.com/mozilla/geckodriver/files/1441806/support.txt)

**Comment by whimboo** [comment] 2017-11-03 16:56
Yes, it is. Marionette server gets initialized after this window has been closed, and that should always happen. @lega-land is that always reproducible for you? Also do you see the same behavior with Firefox 57 beta, and 58 (Nightly)? You can download those builds here: https://www.mozilla.org/en-US/firefox/channel/desktop/

Is it also visible when you start Firefox yourself? Or only by passing in the `-marionette` option?

Once we figured out the above issue, we should file a bug.

**Comment by whimboo** [comment] 2017-11-03 16:59
Maybe this is related to [bug 1382162](https://bugzilla.mozilla.org/show_bug.cgi?id=1382162), which we haven't figured out yet.

**Comment by whimboo** [comment] 2017-11-03 17:08
Also did this started to happen for you with Firefox 56, or was is also present in Firefox 55?

**Comment by lega-land** [comment] 2017-11-03 17:40
@whimboo, yes, it always reproduces for me on different Windows hosts. 

I do not observe the window when I start Firefox manually.

That window successfully immediately closes and Marionette initializes normally with both 57 beta and 58 Nightly.

Unfortunately I didn't try the test with prior Firefox versions.

**Comment by whimboo** [comment] 2017-11-04 07:57
Interesting. So it looks like there was a regression which has been fixed for your case. Would you midn testing the first devedition build of Firefox 57, if that is also affected? You can download it from https://archive.mozilla.org/pub/devedition/releases/57.0b1/win64/en-US/.

Also please have a look with Firefox 55 if that is reproducible then.

Firefox 57 will be released over-next week, so there is nothing which could be done for the 56 release. But I would be interested in why this is happening for you given that we also have mystic hangs sometimes, which are not explainable at the moment. So I would appreciate your help.

**Comment by lega-land** [comment] 2017-11-04 18:51
I wasn't able to reproduce issue neither on 55.0.3 nor 57.0b1 DevEdition.
GeckoDriver 0.19.1 and Selenium 3.6.0 was used in all cases.

**Comment by lega-land** [comment] 2017-11-15 08:28
No issue on latest official FF 57

**Comment by iragoubi** [comment] 2017-11-22 14:29
I have the same problem on 
Version: 0.19
Platform: Windows 10
Firefox: 56  (32 bits)
Selenium: 3.6.0

**Comment by whimboo** [comment] 2017-11-27 10:59
The underlying issue here is actually not fixed, but only the symptom which caused it to appear for Firefox 56. So I filed https://bugzilla.mozilla.org/show_bug.cgi?id=1420864 to get Marionette initialized even with the window staying open.

**Comment by whimboo** [comment] 2017-11-28 10:24
@lega-land and @iragoubi, I assume you both see this gfx sanity window all the time when using Firefox 56 with geckodriver? And only then, right? Could you both do us a favor and help figuring out which patch exactly fixed the problem for you in Firefox 57? We would kinda appreciate that.

**Comment by lega-land** [comment] 2017-11-28 15:06
@whimboo, yes, only in 56. How can I help?

**Comment by whimboo** [comment] 2017-11-28 16:41
@lega-land, are you familiar with Python and how to install/run packages from pypi inside of a virtualenv? If yes, please install https://pypi.python.org/pypi/mozregression/. It can be used to figure out since when a feature is broken or got fixed.

To not have to do all the steps manually you would need a simple Selenium test, which you should already have. This test would have to be called from the command line by mozregression. The following arguments are necessary:

> `mozregression --bad 56 --good 57 --find-fix --command -c "%command to start your test%"

In my case I have a Python script called `test_selenium.py`. So I specify `--command="python test_selenium.py"`. 

Please note that your test script has to set the correct binary, as downloaded and extracted by mozregression. You can retrieve the binary path from the environment variable `MOZREGRESSION_BINARY`. Use that one to set the binary in FirefoxOptions.

Let me know if you have problems running this script. Thanks!

**Comment by whimboo** [comment] 2019-08-09 09:48
Issue #1518 has a more descriptive name and contains more details. Lets dupe this issue over.

**Closed by whimboo** 2019-08-09 09:48 UTC
Labels: firefox, marionette
