### ISSUE TITLE
selenium.common.exceptions.SessionNotCreatedException: Message: Error: NS_ERROR_UNKNOWN_HOST error opening Firefox v103.0.2 with GeckoDriver v0.31.0

### ISSUE THREAD

**Issue by Debanjan-B** [mozilla/geckodriver#2036] opened 2022-08-13 00:29 UTC
## System

* Version: 0.31.0
* Platform: Windows 10
* Firefox: 103.0.2 (64-bit)
* Selenium: 4.4.0, Python client, Python  version 3.9.0

## Testcase

Description:

Firefox v103.0.2 (latest) when initiated with latest GeckoDriver v0.31.0 and Selenium v4.4.0 crashes with `NS_ERROR_UNKNOWN_HOST` error

Code trials:

```
from selenium import webdriver
from selenium.webdriver.firefox.options import Options
from selenium.webdriver.firefox.service import Service
from selenium.webdriver.firefox.options import Log

import sys
print ("Python Version: " +str(sys.version_info))

import selenium
print("Selenium version: " +selenium.__version__)

log = Log()
log.level = "trace"
options = Options()
options.add_argument(log.level)
s = Service('C:\\BrowserDrivers\\geckodriver.exe')
driver = webdriver.Firefox(service=s, options=options)
driver.get('https://www.google.com/')
```

## Stacktrace

```
selenium.common.exceptions.SessionNotCreatedException: Message: Error: NS_ERROR_UNKNOWN_HOST
Stacktrace:
#checkLoadingState@chrome://remote/content/shared/Navigate.jsm:239:28
onStateChange@chrome://remote/content/shared/Navigate.jsm:284:28
```

## Trace-level log

```
Python Version: 3.9.0 (tags/v3.9.0:9cf6752, Oct  5 2020, 15:34:40) [MSC v.1927 64 bit (AMD64)]
Python Version: sys.version_info(major=3, minor=9, micro=0, releaselevel='final', serial=0)
Python Version: 3.9.0
Selenium version: 4.4.0
Traceback (most recent call last):
  File "C:\Users\debanjan.bhattacharj\Desktop\Python Programs\Selenium_Firefox_tests.py", line 26, in <module>
    driver = webdriver.Firefox(service=s, options=options)
  File "C:\Users\debanjan.bhattacharj\AppData\Local\Programs\Python\Python39\lib\site-packages\selenium\webdriver\firefox\webdriver.py", line 177, in __init__
    super().__init__(
  File "C:\Users\debanjan.bhattacharj\AppData\Local\Programs\Python\Python39\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 276, in __init__
    self.start_session(capabilities, browser_profile)
  File "C:\Users\debanjan.bhattacharj\AppData\Local\Programs\Python\Python39\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 369, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "C:\Users\debanjan.bhattacharj\AppData\Local\Programs\Python\Python39\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 434, in execute
    self.error_handler.check_response(response)
  File "C:\Users\debanjan.bhattacharj\AppData\Local\Programs\Python\Python39\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 243, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.SessionNotCreatedException: Message: Error: NS_ERROR_UNKNOWN_HOST
Stacktrace:
#checkLoadingState@chrome://remote/content/shared/Navigate.jsm:239:28
onStateChange@chrome://remote/content/shared/Navigate.jsm:284:28
```

**Comment by whimboo** [comment] 2022-09-07 07:05
Note that this issue was also filed as https://bugzilla.mozilla.org/show_bug.cgi?id=1784593. Investigation will happen over there.

**Comment by whimboo** [comment] 2022-09-20 12:26
Due to missing feedback from reporter closing the issue.

**Closed by whimboo** 2022-09-20 12:26 UTC
Labels: awaiting reporter feedback

**Comment by whimboo** [comment] 2023-03-28 18:57
@iulianduca which Linux distribution and version is that? Is that local, remote, or in a container? It would be good if you can provide a [trace log](https://firefox-source-docs.mozilla.org/testing/geckodriver/TraceLogs.html) as well.

**Comment by y2jhotaru** [comment] 2023-04-12 14:17
Hi. I'm having the same problem with geckodriver. I reverted firefox to an old version (85) as a workaround.

**Comment by whimboo** [comment] 2023-04-12 14:47
@y2jhotaru with which version of Firefox does the problem start for you?

**Comment by y2jhotaru** [comment] 2023-04-14 13:50
> 

Hi, I tested with Firefox 112 and GeckoDriver 0.33.0 to reproduce the error.

**Comment by whimboo** [comment] 2023-04-17 08:08
@y2jhotaru could you please bisect with other Firefox releases so that we know in which exact version the problem started to happen? Right now we have a kinda broad range from 85 to 112. Maybe you could start with the 91 and 102 ESR releases and then shrink the range further? The downloads of the releases can be found at https://archive.mozilla.org/pub/firefox/releases/. Thanks a lot.

**Comment by SublateSamuel** [comment] 2023-04-27 10:35
hello everyone, I can contribute with this problem you are facing.

adding a capability
`setCapability('acceptInsecureCerts', true);`

in firefox versions 110, 110, 112 throws NS_ERROR_UNKNOWN_HOST exception
but this error does not match the truth
if you try to reproduce with firefox version 99.0 you will see the real error appear.

**Comment by whimboo** [comment] 2023-04-27 10:55
@SublateSamuel what do you mean with the real error? Could you provide a [trace log](https://firefox-source-docs.mozilla.org/testing/geckodriver/TraceLogs.html)?

**Comment by eabase** [comment] 2025-07-22 02:44
Happening today

**Comment by emoxam** [comment] 2025-09-09 06:44
face the same issue after a day of using. A the morning
FF 142.0.1 (64-bit) on kubuntu 24.04.
Didn't understand how to give a trace logs.
