### ISSUE TITLE
Driver.Manage().Window.Size cause an error "System.InvalidOperationException : Invalid requested size, cannot maximize"

### ISSUE THREAD

**Issue by redheadTriss** [mozilla/geckodriver#468] opened 2017-02-13 10:35 UTC
I have monitor (14 inch) with resolution 1920*1080.
When I try to run a test (Selenium3+xUnit runner) with setting the size to 1280*800 I have got an error: "System.InvalidOperationException : Invalid requested size, cannot maximize"

## Firefox Version
51.0.1

## Platform
Windows 

## Steps to reproduce -
1. Set up monitor resolution to 1920*1080
2. Try to run a test with setting the Driver size to 1280*800 

Code example:

[Fact]
        public void Test()
        {
            Driver.Manage().Window.Size = new Size(1280, 800);
        }

 - [ ] A [trace level log](https://github.com/mozilla/geckodriver#firefox-capabilities) from a geckodriver session that demonstrates the problem using the minimal example file:

1486981966333   geckodriver     INFO    Listening on 127.0.0.1:53803
1486981968398   mozprofile::profile     INFO    Using profile path C:\Users\ANNA_A~1\AppData\Local\Temp\rust_mozprofile.GUL4Ft03BNu8
1486981968404   geckodriver::marionette INFO    Starting browser C:\Program Files\Mozilla Firefox\firefox.exe
1486981968433   geckodriver::marionette INFO    Connecting to Marionette on localhost:53835

**Comment by andreastt** [comment] 2017-02-13 14:25
Please include a trace-level log from geckodriver.

**Comment by andreastt** [comment] 2017-03-01 10:56
I am closing this since no trace log has been provided in 16 days. I am happy to reopen once we have established that this issue is reproducible.

**Closed by andreastt** 2017-03-01 10:56 UTC
Labels: needinfo
