### ISSUE TITLE
If an input is disabled, WebElement.sendKeys() should throw InvalidElementStateException

### ISSUE THREAD

**Issue by h-rueda** [mozilla/geckodriver#912] opened 2017-08-30 21:29 UTC
## System
* Version: 0.18.0
* Platform: Windows 7
* Firefox: 47.0.2
* Selenium: 3.5.3 for Java

## Testcase
```
import java.net.MalformedURLException;
import org.openqa.selenium.*;
import org.openqa.selenium.chrome.*;
import org.openqa.selenium.firefox.*;
import org.openqa.selenium.remote.*;
import org.openqa.selenium.support.events.*;

public class Test {

	public static void main(String[] args) throws MalformedURLException {
		WebDriver driver;
		System.setProperty("webdriver.gecko.driver", "C:\\\\Users\\harmin\\workspace\\geckodriver.exe");

		driver = new FirefoxDriver();
		EventFiringWebDriver eventDriver = new EventFiringWebDriver(driver);
		EventListener handler = new EventListener();
		eventDriver.register(handler);
		
		eventDriver.get("file:///C:/Users/harmin/workspace/Bug/page.html");
		
		WebElement element;
		element = eventDriver.findElement(By.name("txt"));
		element.sendKeys("xxxxx");
		
		eventDriver.close();
		eventDriver.quit();
	}
}

class EventListener implements WebDriverEventListener {
	public void onException(Throwable error, WebDriver driver) {
		System.err.println("I've got an exception");
	}

	@Override
	public void afterAlertAccept(WebDriver arg0) { }

	@Override
	public void afterAlertDismiss(WebDriver arg0) { }

	@Override
	public void afterChangeValueOf(WebElement arg0, WebDriver arg1, CharSequence[] arg2) { }

	@Override
	public void afterClickOn(WebElement arg0, WebDriver arg1) { }

	@Override
	public void afterFindBy(By arg0, WebElement arg1, WebDriver arg2) { }

	@Override
	public void afterNavigateBack(WebDriver arg0) { }

	@Override
	public void afterNavigateForward(WebDriver arg0) { }

	@Override
	public void afterNavigateRefresh(WebDriver arg0) { }

	@Override
	public void afterNavigateTo(String arg0, WebDriver arg1) { }

	@Override
	public void afterScript(String arg0, WebDriver arg1) { }

	@Override
	public void beforeAlertAccept(WebDriver arg0) { }

	@Override
	public void beforeAlertDismiss(WebDriver arg0) { }

	@Override
	public void beforeChangeValueOf(WebElement arg0, WebDriver arg1, CharSequence[] arg2) { }

	@Override
	public void beforeClickOn(WebElement arg0, WebDriver arg1) { }

	@Override
	public void beforeFindBy(By arg0, WebElement arg1, WebDriver arg2) { }

	@Override
	public void beforeNavigateBack(WebDriver arg0) { }

	@Override
	public void beforeNavigateForward(WebDriver arg0) { }

	@Override
	public void beforeNavigateRefresh(WebDriver arg0) { }

	@Override
	public void beforeNavigateTo(String arg0, WebDriver arg1) { }

	@Override
	public void beforeScript(String arg0, WebDriver arg1) { }
}
```

```
<html>
<body>
  <form>
    Your name
    <input type="text" name="txt" disabled>
    <input type="button" name="btn" value="Click" disabled>
  </form>
</body>
</html>
```

Expected result  : 
```
I've got an exception
Exception in thread "main" org.openqa.selenium.InvalidElementStateException: Element is not enabled
```

Actual result : 
No exception was raised

**Comment by barancev** [comment] 2017-08-30 21:51
Duplicate of #668

**Closed** 2017-08-31 14:29 UTC
