### ISSUE TITLE
e10s is now on by default in 0.10.0

### ISSUE THREAD

**Issue by juangj** [mozilla/geckodriver#157] opened 2016-08-03 04:00 UTC
Is that intentional? It looks like the default was flipped in 9e05d53902a9b8a72912815f012c4608b10524f7 (the flag was renamed from --e10s to --no-e10s).

e10s causes crashes in my environment so the change was a bit of an unpleasant surprise.

**Comment by jgraham** [comment] 2016-08-03 08:56
I think the right solution here is now to not change the prefs at all by default, and *maybe* have some capabilities to enable/disable (or maybe just get people who really care to set the prefs).

I'll make sure this is fixed for 0.11.

(what environment are you running out of interest? Windows 10 + touchscreen?)

**Comment by juangj** [comment] 2016-08-05 02:54
On the Google flavor of Ubuntu 14.04. Shouldn't be that much different from vanilla Ubuntu, but I haven't reproduced the crash anywhere else. It's very possible that it's something crazy we're doing.

**Comment by andreastt** [comment] 2016-08-05 08:47
Not explicitly enabling e10s by default sounds like the right thing to do. We could have explicit `--enable-e10s` and `--disable-e10s` flags, but I sort of suspect that the people that care about switching it on and off (i.e. browser vendors) might need other custom preferences set anyway, and that triggering e10s through preferences would be acceptable.

@juangj That sounds awful! We have done a lot of testing before shipping e10s, so an outright consistent crash sounds suspicious. Can you navigate to about:crash in one of the browsers and provide a link to the crash report?

Other things worth checking is the shell output. You can also run geckodriver with `-vv` to get more verbose output from Gecko.

**Comment by jgraham** [comment] 2016-08-10 10:32
Closing as this will be fixed in the next release.

**Closed by jgraham** 2016-08-10 10:32 UTC

**Comment by klausenbusk** [comment] 2017-02-11 10:49
> @juangj That sounds awful! We have done a lot of testing before shipping e10s, so an outright consistent crash sounds suspicious. Can you navigate to about:crash in one of the browsers and provide a link to the crash report?

This is a old issue report, but I'm also experiencing crash with e10s enabled. The tab crash most of the time if e10s is enabled, but if I disable e10s the issue is gone (I tried with http://version2.dk).

Here is a crash report: https://crash-stats.mozilla.com/report/index/1369f601-b6f1-46a9-abb5-3bc272170210 , and it seems [like](https://crash-stats.mozilla.com/signature/?product=Firefox&signature=libyuv%3A%3AARGBSetRow_X86&date=%3E%3D2016-08-10T19%3A19%3A45.000Z&date=%3C2017-02-10T19%3A19%3A45.000Z&_columns=date&_columns=product&_columns=version&_columns=build_id&_columns=platform&_columns=reason&_columns=address&_sort=-date&page=1#graphs) that I'm not the only one with this crash.

It is properly related to the fact that I run Firefox in a Docker container with Xvfb and llvmpipe: (https://github.com/SeleniumHQ/docker-selenium)
I'm gonna open a bug in bugzilla later today, I just wanna let you know :)
