### ISSUE TITLE
Can't use Firefox profile.

### ISSUE THREAD

**Issue by anonmu07** [mozilla/geckodriver#188] opened 2016-08-19 15:43 UTC
With selenium 2.53.0, I can open webdriver with a new Profile for Firefox using:
```
FirefoxProfile fp = new FirefoxProfile();
return new FirefoxDriver(fp);
```
But this doesn't work in 3.0.0-beta2:

> your firefox profile cannot be loaded. it may be missing or inaccessible.

So I have created the new profile named "Firefox", but I still receive this errror message.
How can I resolve this?

**Comment by andreastt** [comment] 2016-08-19 15:47
This sounds like a problem in Selenium, and you should probably re-check this with the latest Selenium beta release which as more support for geckodriver and Marionette.

I’m going to close this issue as Firefox profile support is working, but please feel free to add more information later in which case I can re-open the issue.

**Closed by andreastt** 2016-08-19 15:47 UTC

**Comment by jgraham** [comment] 2016-08-19 16:46
I suspect the issue is that we don't support providing a path to a profile on the local drive, just for providing a base64-encoded zip of a profile.

**Comment by anonmu07** [comment] 2016-08-22 12:27
I have changed the code to use DesiredCapabilities with encoded profile. Now the preferences work, but I still receive this error message. I guess I will leave it for now and check with the latter release.

**Comment by jajavi** [comment] 2016-09-16 10:41
dis you solve it?how?
