### ISSUE TITLE
Second get() call hangs

### ISSUE THREAD

**Issue by barry-scott** [mozilla/geckodriver#1157] opened 2018-02-04 14:55 UTC
## System
* Version:  v0.19.1
* Platform: Linux
* Firefox: firefox-58.0.1-1.fc27.x86_64
* Selenium: 3.8.1

## Testcase

I have a python script that logs into a web site and after completing the login process it browses to a another page in the site using get(url).

profile is configured to save files to disk without prompting.

The get will result in a download that I see completes.
But the get() does not return, it just hangs.
Ctrl-C to get a traceback showing where it is stuck.

I have failed to make a small example so far.

## Stacktrace

```
Traceback (most recent call last):
  File "/home/barry/wc/svn/ComputerConfiguration/Utilities/DownloadBankStatement/download_bank_base.py", line 120, in fetchStatementsWrapper
    return self.fetchStatements()
  File "download_partnershipcard.py", line 105, in fetchStatements
    self.driver.get( url )
  File "/home/barry/wc/svn/ComputerConfiguration/Utilities/DownloadBankStatement/bank-download-app/lib64/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 324, in get
    self.execute(Command.GET, {'url': url})
  File "/home/barry/wc/svn/ComputerConfiguration/Utilities/DownloadBankStatement/bank-download-app/lib64/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 310, in execute
    response = self.command_executor.execute(driver_command, params)
  File "/home/barry/wc/svn/ComputerConfiguration/Utilities/DownloadBankStatement/bank-download-app/lib64/python3.6/site-packages/selenium/webdriver/remote/remote_connection.py", line 466, in execute
    return self._request(command_info[0], url, body=data)
  File "/home/barry/wc/svn/ComputerConfiguration/Utilities/DownloadBankStatement/bank-download-app/lib64/python3.6/site-packages/selenium/webdriver/remote/remote_connection.py", line 490, in _request
    resp = self._conn.getresponse()
  File "/usr/lib64/python3.6/http/client.py", line 1331, in getresponse
    response.begin()
  File "/usr/lib64/python3.6/http/client.py", line 297, in begin
    version, status, reason = self._read_status()
  File "/usr/lib64/python3.6/http/client.py", line 258, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/usr/lib64/python3.6/socket.py", line 586, in readinto
    return self._sock.recv_into(b)
KeyboardInterrupt
```

## Trace-level log

url changed to example.com to protect privacy.

```
1517754985947	geckodriver::marionette	TRACE	-> 67:[0,31,"clickElement",{"id":"a81b4e6b-98a7-4da3-874d-412aa2f5bee7"}]
1517754985948	Marionette	TRACE	0 -> [0,31,"clickElement",{"id":"a81b4e6b-98a7-4da3-874d-412aa2f5bee7"}]
1517754985963	Marionette	DEBUG	Received DOM event "beforeunload" for "https://example.com/billsmith/signin/step2"
1517754987215	Marionette	DEBUG	Received DOM event "pagehide" for "https://example.com/billsmith/signin/step2"
1517754987217	Marionette	DEBUG	Received DOM event "unload" for "https://example.com/billsmith/signin/step2"
1517754987340	Marionette	DEBUG	Received DOM event "DOMContentLoaded" for "https://example.com/billsmith/my-accounts"
1517754987380	Marionette	DEBUG	Received observer notification "outer-window-destroyed" for "2147483679"
1517754987381	Marionette	DEBUG	Received observer notification "outer-window-destroyed" for "2147483684"
1517754987381	Marionette	DEBUG	Received observer notification "outer-window-destroyed" for "2147483681"
1517754988256	Marionette	DEBUG	Received DOM event "pageshow" for "https://example.com/billsmith/my-accounts"
1517754988256	Marionette	TRACE	0 <- [1,31,null,{}]
1517754988256	geckodriver::marionette	TRACE	<- [1,31,null,{}]
1517754988256	webdriver::server	DEBUG	<- 200 OK {"value": {}}
1517754993263	webdriver::server	DEBUG	-> POST /session/20205ee5-6d77-48ec-8d4a-d9448cee60e7/url {"url": "https://example.com/billsmith/my-card-account/exporttransactions?Range.FromDay=8&Range.FromMonth=8&Range.FromYear=2017&Range.ToDay=4&Range.ToMonth=2&Range.ToYear=2018&ExportType=CSV&reversed=False&offset=0&maxpageSize=100000"}
1517754993263	geckodriver::marionette	TRACE	-> 271:[0,32,"get",{"url":"https://example.com/billsmith/my-card-account/exporttransactions?Range.FromDay=8&Range.FromMonth=8&Range.FromYear=2017&Range.ToDay=4&Range.ToMonth=2&Range.ToYear=2018&ExportType=CSV&reversed=False&offset=0&maxpageSize=100000"}]
1517754993265	Marionette	TRACE	0 -> [0,32,"get",{"url":"https://example.com/billsmith/my-card-account/exporttransactions?Range.FromDay=8& ... ge.FromYear=2017&Range.ToDay=4&Range.ToMonth=2&Range.ToYear=2018&ExportType=CSV&reversed=False&offset=0&maxpageSize=100000"}]
1517754993267	Marionette	DEBUG	Received DOM event "beforeunload" for "https://example.com/billsmith/my-accounts"
```

**Comment by andreastt** [comment] 2018-02-07 13:22
Is that the full trace-level log? You see no other entries after the `beforeunload` event gets logged?

Would you be able to attach a reproducible HTML document for which geckodriver doesn’t finish loading?

**Comment by whimboo** [comment] 2018-02-08 10:07
This is just a dupe of issue #1065.

**Closed by whimboo** 2018-02-08 10:07 UTC
Labels: waiting for reporter feedback
