### ISSUE TITLE
Still encountering untrusted certificate warning when acceptInsecureCerts is set to true

### ISSUE THREAD

**Issue by pembertonrw** [mozilla/geckodriver#422] opened 2017-01-05 21:38 UTC
I am trying to use the new function acceptInsecureCerts but I am still getting the "Your connection is insecure" prompt. I am using the java implementation of selenium webdriver and my tests are being ran against Selenium Grid. I am sure I am doing something incorrect but I don't know what.

The code I am using to set the capabilities is

`        DesiredCapabilities capabilities;
        capabilities = DesiredCapabilities.firefox();
        capabilities.setCapability("marionette", true);
        capabilities.setCapability("proxyType", "pac");
        capabilities.setCapability("proxyAutoconfigUrl", _defaultprop.getString("proxyURL"));
        capabilities.setCapability("acceptInsecureCerts", true);
        capabilities.setCapability("browser.private.browsing.autostart", true);`

## Selenium Standalone version
3.0.1

## Geckodriver version
v0.12.0

## Firefox Version
Firefox nightly build 2017-01-05

## Platform
Windows Server 2008 R2

**Comment by andreastt** [comment] 2017-01-06 08:12
Duplicate of https://github.com/mozilla/geckodriver/issues/97.

You need to set the `proxy` capability as a required capability for the time being, until [bug 1326534](https://bugzilla.mozilla.org/show_bug.cgi?id=1326534) lands.

**Closed by andreastt** 2017-01-06 08:12 UTC
