### ISSUE TITLE
https://github.com/mozilla/geckodriver/issues/233 - another test case

### ISSUE THREAD

**Issue by MartaWdowicka** [mozilla/geckodriver#943] opened 2017-09-11 17:45 UTC
## Meta -
OS:  Windows 10
Selenium Version:  3.5.2
Browser:  Firefox
Firefox version 55 - no add-ons

"System.InvalidOperationException: '(147, 4161.516502380371) is out of bounds of viewport width (1920) and height (971) (InvalidElementCoordinates)'" is being thrown when i try to move an element from loooong list of rectangle drag-and drop elements

Code that triggered error (at action perform) which is working with chromedriver:

> var action = new Actions(Driver)
>                 .ClickAndHold(elementToDrag)
>                 .MoveToElement(targetElement)
>                 .Release(targetElement)
>                 .Build();
> 
>             action.Perform();

**Comment by MartaWdowicka** [comment] 2017-09-11 17:46
Do you know any way to go around this?

**Comment by codingphil** [comment] 2017-09-12 13:24
Maybe this is related to the issue https://github.com/mozilla/geckodriver/issues/901?
The center of the target element may be not in the viewport.

**Comment by andreastt** [comment] 2017-09-13 08:38
I think @codingphil is correct. Closing this as a duplicate of #901.

That particular issue is tracked by https://bugzilla.mozilla.org/show_bug.cgi?id=1393831, which is relatively easy to fix if anyone wants to have a go.

**Closed by andreastt** 2017-09-13 08:38 UTC
