### ISSUE TITLE
Connection refused attempting to use RemoteWebDriver

### ISSUE THREAD

**Issue by schmidtkp** [mozilla/geckodriver#61] opened 2016-05-13 15:48 UTC
I cannot get RemoteWebDriver to work using v0.6.2 or v0.7.1 of GeckoDriver.

Config:
OSX 10.11.4
Selenium 2.53.0
Wires v0.6.2 and 0.7.1

Example using RemoteWebDriver:

System.setProperty(GeckoDriverService.GECKO_DRIVER_EXE_PROPERTY, "/temp/wires-0.7.1-OSX");
DesiredCapabilities capabilities = DesiredCapabilities.firefox();
capabilities.setCapabilities("marionette", true);
WebDriver webDriver = new RemoteWebDriver(seleniumHubUrl, capabilities);

This causes a org.openqa.selenium.WebDriverException: Connection refused to be thrown.

I can, however, get it to work using MarionetteDriver.
Example using MarionetteDriver:

System.setProperty(GeckoDriverService.GECKO_DRIVER_EXE_PROPERTY, "/temp/wires-0.7.1-OSX");
DesiredCapabilities capabilities = DesiredCapabilities.firefox();
MarionetteDriver marionetteDriver = new MarionetteDriver(capabilities);

This successfully opens a Firefox browser.

I need to be able to use RemoteWebDriver so I can utilize our Selenium Grid.

Any help resolving this would be greatly appreciated.

**Comment by MoCoTester** [comment] 2016-06-12 00:05
This is still an issue in v0.8.0.  My configuration is Ubuntu 16.04, Selenium 2.53.0, and Firefox 47.0.

**Comment by kgston** [comment] 2016-06-14 05:50
Same here with v0.8.0. Win 7, Selenium 2.53.0 & Firefox 46.0.1 & 47

**Comment by andreastt** [comment] 2016-06-14 08:39
@kgston Can you verify for me if http://sny.no/e/geckodriver1.exe works without the VS C runtime library installed?

**Comment by kgston** [comment] 2016-06-15 04:17
@andreastt You are right, my issue is slightly different in that the geckodriver fails silently without the VS C runtime library, both with the MarionetteDriver and RemoteWebDriver for Grid. I can confirm that without the runtime library installed, the v0.8.0 windows binary does not work on my system. It returns a "The application was unable to start correctly (0x000007b)" application error message when you run "geckodriver.exe --help".

I can also confirm that the binary you linked works without the runtime library installed.

**Comment by andreastt** [comment] 2016-06-15 09:18
@kgston Excellent! That is very good to know. After https://github.com/mozilla/geckodriver/pull/83 is merged we will make all releases through Travis, by cross-compiling a static Windows binary using the GNU C library.

**Comment by andreastt** [comment] 2016-06-15 09:22
I think the issue described initially could be related to the Selenium RemoteWebDriver’s ability to detect whether it’s speaking to a W3C WebDriver conformant remote end. Currently a capability is used to put the user binding into conformant mode, but it should instead probe the remote end to find if it is Selenium or WebDriver compatible.

**Comment by andreastt** [comment] 2016-06-15 09:30
I think this is the same issue as #91, and going to use that as the main tracking issue because it has some good stack traces.

**Closed by andreastt** 2016-06-15 09:30 UTC
Labels: selenium

**Comment by schmidtkp** [comment] 2016-06-16 18:55
@andreastt I don't feel this issue should be closed or tracked against [#91](https://github.com/mozilla/geckodriver/issues/91). They may seem similar but #91 is calling new FirefoxDriver(options) and *not* RemoteWebDriver(), also, a different OS in my case, therefore a different binary.

I just tried RemoteWebDriver again today with v0.8.0 and still get connection refused.

As for stack trace, here ya go:

org.openqa.selenium.WebDriverException: Connection refused
Command duration or timeout: 7.83 seconds
Build info: version: '2.53.0', revision: '35ae25b1534ae328c771e0856c93e187490ca824', time: '2016-03-15 10:43:46'
System info: host: 'kschmidt-retina.local', ip: '10.201.16.182', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.11.5', java.version: '1.7.0_79'
Driver info: com.bazaarvoice.automation.common.webdriver.driver.EnhancedRemoteWebDriver
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:526)
	at org.openqa.selenium.remote.ErrorHandler.createThrowable(ErrorHandler.java:206)
	at org.openqa.selenium.remote.ErrorHandler.throwIfResponseFailed(ErrorHandler.java:158)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:678)
	at org.openqa.selenium.remote.RemoteWebDriver.startSession(RemoteWebDriver.java:249)
	at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:131)
	at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:158)
	at com.bazaarvoice.automation.common.webdriver.driver.EnhancedRemoteWebDriver.<init>(EnhancedRemoteWebDriver.java:51)
	at com.bazaarvoice.automation.webrunner.webdriver.WebDriverManager.startWebDriver(WebDriverManager.java:299)
	at com.bazaarvoice.automation.webrunner.runner.TestWebRunner.startWebDriver(TestWebRunner.java:188)
	at com.bazaarvoice.automation.webrunner.runner.TestWebRunner.testWebRunnerBeforeClass(TestWebRunner.java:142)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:552)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:215)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:140)
	at org.testng.internal.TestMethodWorker.invokeBeforeClassMethods(TestMethodWorker.java:170)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:104)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.net.ConnectException: Connection refused
	at java.net.PlainSocketImpl.socketConnect(Native Method)
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:339)
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:200)
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:182)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:579)
	at org.apache.http.conn.socket.PlainConnectionSocketFactory.connectSocket(PlainConnectionSocketFactory.java:74)
	at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:141)
	at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:353)
	at org.apache.http.impl.execchain.MainClientExec.establishRoute(MainClientExec.java:380)
	at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:236)
	at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:184)
	at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:88)
	at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:110)
	at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:184)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:71)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:55)
	at org.openqa.selenium.remote.internal.ApacheHttpClient.fallBackExecute(ApacheHttpClient.java:144)
	at org.openqa.selenium.remote.internal.ApacheHttpClient.execute(ApacheHttpClient.java:90)
	at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:142)
	at org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:82)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:644)
	at org.openqa.selenium.remote.RemoteWebDriver.startSession(RemoteWebDriver.java:249)
	at org.openqa.selenium.remote.RemoteWebDriver.startSession(RemoteWebDriver.java:234)
	at org.openqa.selenium.firefox.MarionetteDriver.run(MarionetteDriver.java:79)
	at org.openqa.selenium.firefox.MarionetteDriver.<init>(MarionetteDriver.java:73)
	at org.openqa.selenium.firefox.MarionetteDriver.<init>(MarionetteDriver.java:49)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:526)
	at org.openqa.selenium.remote.server.FirefoxDriverProvider.callConstructor(FirefoxDriverProvider.java:91)
	at org.openqa.selenium.remote.server.FirefoxDriverProvider.newInstance(FirefoxDriverProvider.java:66)
	at org.openqa.selenium.remote.server.DefaultDriverFactory.newInstance(DefaultDriverFactory.java:60)
	at org.openqa.selenium.remote.server.DefaultSession$BrowserCreator.call(DefaultSession.java:222)
	at org.openqa.selenium.remote.server.DefaultSession$BrowserCreator.call(DefaultSession.java:209)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at org.openqa.selenium.remote.server.DefaultSession$1.run(DefaultSession.java:176)
	... 3 more

**Comment by djb61** [comment] 2016-06-20 16:07
I have also been experiencing this issue. Everything works fine using marionette with a local driver but fails with the same connection refused error when using RemoteWebdriver and a SeleniumGrid.

I do not believe this is an issue with geckodriver however, I found this PR on the selenium project https://github.com/SeleniumHQ/selenium/pull/2255 . I patched that into the selenium 2.53.0 code and built from source. Using this patched version of selenium-server-standalone-2.53.0.jar on my grid node the connection refused issue is resolved and firefox now works using marionette.

Unfortunately from the linked PR it seems selenium are not intending to do another release until 3.x so it will be a long time before this patch is available in a binary release.

**Comment by andreastt** [comment] 2016-06-20 16:53
@djb61 That’s very interesting. Thanks for linking that.

**Comment by schmidtkp** [comment] 2016-06-20 17:29
@djb61 Thanks for this information. It's a shame this isn't going to get patched in to any pre-3.X release.  I'm sure there are many who could use this capability.

**Comment by davehunt** [comment] 2016-07-04 16:20
I've uplifted https://github.com/SeleniumHQ/selenium/commit/a88dc509ec6e697f099ecb9dcd1bab5e7e34818a to leg-rc branch, and will see if we can get another 2.53.x release.

**Comment by andreastt** [comment] 2016-07-04 16:25
@davehunt Note that jleyba is considering doing another release of the 2.53.x branch too (but probably from master?) because of https://github.com/SeleniumHQ/selenium/commit/431070e95fb081ff0709e3ff81cd788ef72ddcc0.

**Comment by schmidtkp** [comment] 2016-07-13 15:14
Any chance this will go in to another 2.53.x release?  It didn't get included in 2.53.1 :-(

**Comment by davehunt** [comment] 2016-07-13 15:41
@lukeis was at least considering doing a 2.53.2 release for us... 😄

**Comment by lukeis** [comment] 2016-07-13 15:51
oh yeah, that :) but we're this >.< close to getting 3.0 beta1 out the door!

**Comment by davehunt** [comment] 2016-07-13 16:30
How long will the beta be though? I'd like this in a stable version before Firefox 48 is released.

**Comment by schmidtkp** [comment] 2016-07-13 16:49
My company is really wanting to get ahead of the curve on this... I'd buy ya a beer(s) if you considered doing it :-)

**Comment by lukeis** [comment] 2016-07-13 16:51
@schmidtkp then consider using the 'alpha' of 3.0 selenium:
http://ci.seleniumhq.org:8080/job/Build_All_Java/lastSuccessfulBuild/artifact/selenium-server-standalone-latest.jar

I'm currently working through a bug with registering grid nodes to the hub in the new 3.0

**Comment by schmidtkp** [comment] 2016-07-13 16:53
@lukeis Sounds like a plan! Thanks.
