### ISSUE TITLE
selenium.WebDriverException: Error: Permission denied to access property "_musculaEventHandlerId"

### ISSUE THREAD

**Issue by yunj** [mozilla/geckodriver#853] opened 2017-08-03 10:20 UTC
## System
* Version: 0.15.0
* Platform: CentOS 7.3.1611
* Firefox: 52.2.0 ESR (64-bit) (This is the latest Firefox rpm for CentOS 7 so not able to upgrade to a newer version.)
* Selenium: 3.3.1

## Testcase

Once the library **musculahq.appspot.com/Muscula7.js** is included on the page, `((JavascriptExecutor) driver).executeScript("window.sessionStorage.clear()");` or `WebElement.isDisplayed()` would throw the same exception. These methods used to work with Selenium 2.53.1.

`  <script type='text/javascript'>
      window.Muscula = { settings:{
          //
      }};
      (function () {
          var m = document.createElement('script'); m.type = 'text/javascript'; m.async = true;
          m.src = (window.location.protocol == 'https:' ? 'https:' : 'http:') +
              '//musculahq.appspot.com/Muscula7.js';
            var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(m, s);
          window.Muscula.run=function(){var a;eval(arguments[0]);window.Muscula.run=function(){};};
          window.Muscula.errors=[];window.onerror=function(){window.Muscula.errors.push(arguments);
          return window.Muscula.settings.suppressErrors===undefined;}
      })();
  </script>`

## Trace-level log
1502084204110	hyper::server::response	DEBUG	write 13 bytes
1502084204110	hyper::server::response	TRACE	ending
1502084204111	hyper::server	DEBUG	keep_alive = false for 127.0.0.1:59513
1502084204111	hyper::server	DEBUG	keep_alive loop ending for 127.0.0.1:59513
1502084204119	hyper::server	DEBUG	Incoming stream
1502084204119	hyper::buffer	TRACE	get_buf []
1502084204119	hyper::buffer	TRACE	read_into_buf buf[0..4096]
1502084204121	hyper::buffer	TRACE	get_buf [u8; 4096][0..327]
1502084204121	hyper::http::h1	TRACE	try_parse([80, 79, 83, 84, 32, 47, 115, 101, 115, 115, 105, 111, 110, 47, 54, 55, 51, 50, 101, 53, 97, 52, 45, 97, 48, 48, 49, 45, 52, 50, 52, 57, 45, 97, 99, 50, 98, 45, 49, 52, 99, 98, 97, 55, 97, 98, 48, 98, 53, 56, 47, 101, 120, 101, 99, 117, 116, 101, 47, 115, 121, 110, 99, 32, 72, 84, 84, 80, 47, 49, 46, 49, 13, 10, 67, 111, 110, 116, 101, 110, 116, 45, 84, 121, 112, 101, 58, 32, 97, 112, 112, 108, 105, 99, 97, 116, 105, 111, 110, 47, 106, 115, 111, 110, 59, 32, 99, 104, 97, 114, 115, 101, 116, 61, 117, 116, 102, 45, 56, 13, 10, 67, 111, 110, 116, 101, 110, 116, 45, 76, 101, 110, 103, 116, 104, 58, 32, 53, 50, 13, 10, 72, 111, 115, 116, 58, 32, 108, 111, 99, 97, 108, 104, 111, 115, 116, 58, 49, 50, 55, 53, 56, 13, 10, 67, 111, 110, 110, 101, 99, 116, 105, 111, 110, 58, 32, 75, 101, 101, 112, 45, 65, 108, 105, 118, 101, 13, 10, 85, 115, 101, 114, 45, 65, 103, 101, 110, 116, 58, 32, 65, 112, 97, 99, 104, 101, 45, 72, 116, 116, 112, 67, 108, 105, 101, 110, 116, 47, 52, 46, 53, 46, 50, 32, 40, 74, 97, 118, 97, 47, 49, 46, 56, 46, 48, 95, 49, 51, 49, 41, 13, 10, 65, 99, 99, 101, 112, 116, 45, 69, 110, 99, 111, 100, 105, 110, 103, 58, 32, 103, 122, 105, 112, 44, 100, 101, 102, 108, 97, 116, 101, 13, 10, 13, 10, 123, 34, 115, 99, 114, 105, 112, 116, 34, 58, 34, 119, 105, 110, 100, 111, 119, 46, 115, 101, 115, 115, 105, 111, 110, 83, 116, 111, 114, 97, 103, 101, 46, 99, 108, 101, 97, 114, 40, 41, 34, 44, 34, 97, 114, 103, 115, 34, 58, 91, 93, 125])
1502084204121	hyper::http::h1	TRACE	Request.try_parse([Header; 100], [u8; 327])
1502084204121	hyper::http::h1	TRACE	Request.try_parse Complete(275)
1502084204121	hyper::header	TRACE	raw header: "Content-Type"=[97, 112, 112, 108, 105, 99, 97, 116, 105, 111, 110, 47, 106, 115, 111, 110, 59, 32, 99, 104, 97, 114, 115, 101, 116, 61, 117, 116, 102, 45, 56]
1502084204121	hyper::header	TRACE	raw header: "Content-Length"=[53, 50]
1502084204121	hyper::header	TRACE	raw header: "Host"=[108, 111, 99, 97, 108, 104, 111, 115, 116, 58, 49, 50, 55, 53, 56]
1502084204121	hyper::header	TRACE	raw header: "Connection"=[75, 101, 101, 112, 45, 65, 108, 105, 118, 101]
1502084204121	hyper::header	TRACE	raw header: "User-Agent"=[65, 112, 97, 99, 104, 101, 45, 72, 116, 116, 112, 67, 108, 105, 101, 110, 116, 47, 52, 46, 53, 46, 50, 32, 40, 74, 97, 118, 97, 47, 49, 46, 56, 46, 48, 95, 49, 51, 49, 41]
1502084204121	hyper::header	TRACE	raw header: "Accept-Encoding"=[103, 122, 105, 112, 44, 100, 101, 102, 108, 97, 116, 101]
1502084204121	hyper::server::request	DEBUG	Request Line: Post AbsolutePath("/session/6732e5a4-a001-4249-ac2b-14cba7ab0b58/execute/sync") Http11
1502084204121	hyper::server::request	DEBUG	Headers { Content-Type: application/json; charset=utf-8
, Content-Length: 52
, Host: localhost:12758
, Connection: Keep-Alive
, User-Agent: Apache-HttpClient/4.5.2 (Java/1.8.0_131)
, Accept-Encoding: gzip,deflate
, }
1502084204121	hyper::header	TRACE	Headers.set( "Connection", Connection([Close]) )
1502084204121	hyper::http::h1	TRACE	Sized read, remaining=52
1502084204121	hyper::http::h1	TRACE	Sized read: 32
1502084204121	hyper::http::h1	TRACE	Sized read, remaining=20
1502084204121	hyper::http::h1	TRACE	Sized read: 20
1502084204121	hyper::http::h1	TRACE	Sized read, remaining=0
1502084204121	webdriver::server	DEBUG	Got request POST AbsolutePath("/session/6732e5a4-a001-4249-ac2b-14cba7ab0b58/execute/sync")
1502084204122	webdriver::command	DEBUG	Got request body {"script":"window.sessionStorage.clear()","args":[]}
1502084204122	geckodriver::marionette	DEBUG	→ 137:[0,13,"executeScript",{"args":[],"newSandbox":false,"script":"window.sessionStorage.clear()","scriptTimeout":null,"specialPowers":false}]
1502084204127	Marionette	TRACE	conn0 -> [0,13,"executeScript",{"args":[],"newSandbox":false,"script":"window.sessionStorage.clear()","scriptTimeout":null,"specialPowers":false}]
1502084204136	Marionette	TRACE	conn0 <- [1,13,{"error":"webdriver error","message":"Error: Permission denied to access property \"_musculaEventHandlerId\"","stacktrace":"a.removeEventListener@http://localhost:9191/loyaltymodule/form/group-price-request-and-booking/ line 27 > eval:1:14113\n"},null]
1502084204137	geckodriver::marionette	DEBUG	← [1,13,{"error":"webdriver error","message":"Error: Permission denied to access property \"_musculaEventHandlerId\"","stacktrace":"a.removeEventListener@http://localhost:9191/loyaltymodule/form/group-price-request-and-booking/ line 27 > eval:1:14113\n"},null]
1502084204138	webdriver::server	DEBUG	Returning status InternalServerError
1502084204138	webdriver::server	DEBUG	Returning body {"value":{"error":"unknown error","message":"Error: Permission denied to access property \"_musculaEventHandlerId\"","stacktrace":"stack backtrace:\n   0:           0x61f07f - <no info>\n   1:           0x61fe59 - <no info>\n   2:           0x43b0b5 - <no info>\n   3:           0x420313 - <no info>\n   4:           0x408307 - <no info>\n   5:           0x6750f9 - <no info>\n   6:           0x416877 - <no info>\n   7:           0x66ed53 - <no info>\n   8:     0x7ffcd3468364 - BaseThreadInitThunk"}}
1502084204138	hyper::header	TRACE	Headers.set( "Content-Type", ContentType(Mime(Application, Json, [(Charset, Utf8)])) )
1502084204138	hyper::header	TRACE	Headers.set( "Cache-Control", CacheControl([NoCache]) )
1502084204138	hyper::header	TRACE	Headers.set( "Content-Length", ContentLength(502) )
1502084204138	hyper::server::response	DEBUG	writing head: Http11 InternalServerError
1502084204138	hyper::header	TRACE	Headers.set( "Date", Date(HttpDate(Tm { tm_sec: 44, tm_min: 36, tm_hour: 5, tm_mday: 7, tm_mon: 7, tm_year: 117, tm_wday: 1, tm_yday: 219, tm_isdst: 0, tm_utcoff: 0, tm_nsec: 138515700 })) )
1502084204138	hyper::server::response	DEBUG	headers [
Headers { Connection: close
, Content-Type: application/json; charset=utf-8
, Cache-Control: no-cache
, Content-Length: 502
, Date: Mon, 07 Aug 2017 05:36:44 GMT
, }]
1502084204138	hyper::server::response	DEBUG	write 502 bytes
1502084204138	hyper::server::response	TRACE	ending
1502084204139	hyper::server	DEBUG	keep_alive = false for 127.0.0.1:59514
1502084204139	hyper::server	DEBUG	keep_alive loop ending for 127.0.0.1:59514

org.openqa.selenium.WebDriverException: Error: Permission denied to access property "_musculaEventHandlerId"
Build info: version: '3.3.1', revision: '5234b325d5', time: '2017-03-10 09:10:29 +0000'
System info: host: '840G35CG7132ZNS', ip: '100.64.0.1', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_131'
Driver info: org.openqa.selenium.firefox.FirefoxDriver
Capabilities [{moz:profile=C:\Users\bob\AppData\Local\Temp\2\rust_mozprofile.JpwZEfofLM0N, rotatable=false, timeouts={implicit=0, page load=300000, script=30000}, pageLoadStrategy=normal, platform=ANY, specificationLevel=0, moz:accessibilityChecks=false, acceptInsecureCerts=false, browserVersion=52.2.0, platformVersion=10.0, moz:processID=20696, browserName=firefox, platformName=windows_nt}]
Session ID: 6732e5a4-a001-4249-ac2b-14cba7ab0b58

	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.openqa.selenium.remote.http.W3CHttpResponseCodec.createException(W3CHttpResponseCodec.java:133)
	at org.openqa.selenium.remote.http.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:99)
	at org.openqa.selenium.remote.http.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:43)
	at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:163)
	at org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:82)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:604)
	at org.openqa.selenium.remote.RemoteWebDriver.executeScript(RemoteWebDriver.java:540)
	at automation.config.TestContext.cleanupBrowser(TestContext.java:45)
	at automation.steps.common.LifeCycleSteps.cleanUp(LifeCycleSteps.java:30)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at cucumber.runtime.Utils$1.call(Utils.java:40)
	at cucumber.runtime.Timeout.timeout(Timeout.java:16)
	at cucumber.runtime.Utils.invoke(Utils.java:34)
	at cucumber.runtime.java.JavaHookDefinition.execute(JavaHookDefinition.java:60)
	at cucumber.runtime.Runtime.runHookIfTagsMatch(Runtime.java:224)
	at cucumber.runtime.Runtime.runHooks(Runtime.java:212)
	at cucumber.runtime.Runtime.runAfterHooks(Runtime.java:206)
	at cucumber.runtime.model.CucumberScenario.run(CucumberScenario.java:46)
	at cucumber.runtime.junit.ExecutionUnitRunner.run(ExecutionUnitRunner.java:102)
	at cucumber.runtime.junit.FeatureRunner.runChild(FeatureRunner.java:63)
	at cucumber.runtime.junit.FeatureRunner.runChild(FeatureRunner.java:18)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at cucumber.runtime.junit.FeatureRunner.run(FeatureRunner.java:70)
	at cucumber.api.junit.Cucumber.runChild(Cucumber.java:95)
	at cucumber.api.junit.Cucumber.runChild(Cucumber.java:38)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at cucumber.api.junit.Cucumber.run(Cucumber.java:100)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:47)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)

**Comment by andreastt** [comment] 2017-08-04 16:28
Note that you’ve reported a bug against geckodriver 0.15.0 and Firefox 52; neither of which are in active development. Please check that this still reproduces with the latest geckodriver and Firefox Nightly.

If the issue is still reproducible, it would help us if you included a minimal HTML document that reproduces the problem alongside a trace-level geckodriver log.

**Comment by yunj** [comment] 2017-08-05 05:39
Thanks for your comment. As I said, 52.2.0 ESR rpm is the latest Firefox that CentOS 7 has, not able to upgrade to a newer version. Regarding the geckodriver, 0.18.0 has the same issue.

**Comment by andreastt** [comment] 2017-08-05 10:55
And when you tested with 0.18.0, was that together with Nightly? I need to establish if the problem is still present in Nightly or if it has been fixed. If the problem does persist there, please also include a trace-level log from geckodriver (see README for how to get one).

**Comment by yunj** [comment] 2017-08-05 20:19
I have tested against Firefox 54 on windows and it seems that the problem is gone. But CentOS does not have the corresponding RPM and we can only use the latest RPM on CentOS which is Firefox 52. Do you have some idea? thanks.

**Comment by whimboo** [comment] 2017-08-08 05:23
Having a range of 53.0.3 to 54.0.1 is huge! It's not that easy to say what could have fixed it. If you could do us a favor, we can at least try. But your help would be necessary.

So there is a place we host beta releases for Firefox. You can find it at http://archive.mozilla.org/pub/firefox/releases/. All sub dirs with 54.0bXX would be relevant. If you could bisect which beta fixed it, the chance to find what's necessary is way better. Thanks.

**Comment by yunj** [comment] 2017-08-08 06:07
Thanks very much for your reply. It's has been fixed at Firefox [54.0b8](http://archive.mozilla.org/pub/firefox/releases/54.0b8/win64/en-US/).

**Comment by whimboo** [comment] 2017-08-08 07:15
Ok, so the changes between 54.0b7 and 54.0b8 are the following:

https://hg.mozilla.org/releases/mozilla-beta/pushloghtml?fromchange=8b7e2a303954&tochange=9bef2dfbd584

I strongly believe this was fixed by the sandbox related patch on [bug 1353074](https://bugzilla.mozilla.org/show_bug.cgi?id=1353074) @andreastt was working on.

**Comment by yunj** [comment] 2017-08-08 08:17
@whimboo Thanks for your information. Do you know any workaround? Fixing my test could solve the problem?

**Comment by whimboo** [comment] 2017-08-08 08:46
Lets give @andreastt some time to respond. He might know a workaround.

**Comment by yunj** [comment] 2017-08-08 09:50
We have another internal web application which references the Muscula7.js library on some page as well, but no errors when calling WebElement.isDisplayed() on that page with Firefox 52.2.0 ESR.

so don't know the issue is from muscula library, or our web application, or selenium test? thanks.

**Comment by andreastt** [comment] 2017-08-08 14:58
Not interacting with `window.onerror` is a workaround. You could also try `window.addEventListener("error", …)`, which I think should be safe.

Closing this since the underlying issue was fixed in https://bugzilla.mozilla.org/show_bug.cgi?id=1353074.

**Closed by andreastt** 2017-08-08 14:58 UTC
Labels: waiting for reporter feedback

**Comment by yunj** [comment] 2017-08-09 05:30
@andreastt Thanks very much for your reply. Do you know when 54.xxx ESR will be released? because we can't change the existing JavaScript.

**Comment by andreastt** [comment] 2017-08-09 08:27
@yunj The next ESR will be Firefox 59 released in June 2018.

**Comment by andreastt** [comment] 2017-08-09 08:28
See https://wiki.mozilla.org/RapidRelease/Calendar.
