### ISSUE TITLE
rust_mozprofile folders are cluttering TEMP

### ISSUE THREAD

**Issue by JekRock** [mozilla/geckodriver#1611] opened 2019-09-06 08:26 UTC
## System

* Version: 0.20.0
* Platform: Windows 10 1903
* Firefox: 59.0.1
* Selenium: selenium-java 3.8.1

Is there any way to change the folder where rust_mozprofile folders are created except changing TEPM system variable?
Temp folder is cluttered with rust_mozprofile because sometimes program may be terminated without calling a `driver.quit()` and this folder will be left inside TEMP forever as Windows doesn't clean it by default.
It would be nice to have the ability to specify a folder for rust_mozprofile so it can be manually deleted at least.

Changing the TEMP system variable is not an option as it will affect all programs.

**Comment by andreastt** [comment] 2019-09-06 11:42
It’s a known bug that geckodriver sometimes leaves the throwaway profile behind, see https://github.com/mozilla/geckodriver/issues/299.

Setting the `TMPDIR` environment variable is the only way to configure where the throwaway profiles are created. You don’t have to set it system-wide: just make sure it is part of the geckodriver process’ environment before it is started:

    % TEMPDIR=/some/location ./geckodriver

I will take a follow-up to document this at https://firefox-source-docs.mozilla.org/testing/geckodriver/.

**Comment by andreastt** [comment] 2019-09-06 11:47
I just discovered that `TMPDIR` only applies to Unix systems. On Windows the following variables are read, in order:

1. `TMP`
2. `TEMP`
3. `USERPROFILE`

This is documented on https://doc.rust-lang.org/std/env/fn.temp_dir.html.

**Comment by JekRock** [comment] 2019-09-06 13:18
@andreastt setting the TEMP variable for the process on Windows seems to work. Thanks!

**Comment by andreastt** [comment] 2019-09-06 14:47
https://bugzilla.mozilla.org/show_bug.cgi?id=1579389 adds some documentation on Firefox profiles.

**Comment by hheexx** [comment] 2019-09-23 16:36
Heres short c# method I run periodicly to clean up leftovers:

`{
    string temp = Path.GetTempPath();
    Logger.Info("Temp Cleanup. Folder: " + temp);

    foreach (var d in System.IO.Directory.GetDirectories(temp).Where(x => x.Contains(@"\rust_mozprofile.")))
    {
        var lastModified = System.IO.Directory.GetLastWriteTimeUtc(d);
        if (lastModified.AddDays(1) < DateTime.UtcNow)
        {
            Logger.Info("Deleting " + d);
            try
            {
                System.IO.Directory.Delete(d, true);
                Logger.Info("OK.");
            }
            catch (Exception ex)
            {
                Logger.WarnDisplay("Error: " + ex.ToString());
            }
        }
    }

    Logger.Info("Done.");
}
`

**Comment by andreastt** [comment] 2019-09-24 04:44
Closing this since it’s a duplicate of https://github.com/mozilla/geckodriver/issues/299 and the documentation change that landed as part of https://bugzilla.mozilla.org/show_bug.cgi?id=1579389 is now live at https://firefox-source-docs.mozilla.org/testing/geckodriver/Profiles.html.

**Closed by andreastt** 2019-09-24 04:44 UTC
Labels: geckodriver
