### ISSUE TITLE
Set Window Position not moving Firefox browser window

### ISSUE THREAD

**Issue by mgavilan** [mozilla/geckodriver#403] opened 2016-12-21 15:54 UTC
Dear Geckodriver team,

I'm using the following environment:

Windows 10
Firefox 49.0.2
Geckodriver 0.11.1
Selenium 3.0.1

I've followed an issue reported with issue #113 - Missing Set Window Position endpoint as I was facing exceptions with older geckodriver versions, when trying to position the Firefox browser window.

If I got it right, the actual change was implemented with commit #254 - Set Window position and Get Window Position and is supposed to be contained in geckodriver version 0.11 and greater, correct?
There is also another issue with #335 - Set Window Position not moving Firefox browser window which has been closed due to inactivity, as I was away from work for quite some time.

While I do not get exceptions with geckodriver 0.11.1 anymore, when using setPosition() method of FirefoxDriver, the browser window is not moved to the expected screen position though.

Here I attach a small example opening a Firefox browser instance and doing some modification to the browser window size (setSize()) and position (setPosition()).

[NewFirefoxDriver_setPosition.java.txt](https://github.com/mozilla/geckodriver/files/666750/NewFirefoxDriver_setPosition.java.txt)

By executing you will notice, the browser is opened and the size is changed stepwise, but the position is not. This happens on Windows, and I'm not able to try with Linux, not with macOS

Any idea, why this is not working?

Thanks and regards
mgavilan

**Comment by andreastt** [comment] 2016-12-29 14:38
I’m not able to reproduce this on Linux:

```
>>> m.set_window_position(0,0)
1483022128646	Marionette	TRACE	conn2 -> [0,2,"setWindowPosition",{"y":0,"x":0}]
1483022128661	Marionette	TRACE	conn2 <- [1,2,null,{"x":0,"y":0}]
>>> m.set_window_position(250,850)
1483022139211	Marionette	TRACE	conn2 -> [0,3,"setWindowPosition",{"y":850,"x":250}]
1483022139222	Marionette	TRACE	conn2 <- [1,3,null,{"x":250,"y":850}]
```

I somewhat suspect this is specific to Windows. [Internally](https://github.com/mozilla/gecko-dev/blob/master/testing/marionette/driver.js#L1259-L1285), Marionette uses [Window.moveTo](https://developer.mozilla.org/en-US/docs/Web/API/Window/moveTo) to position the window. Can you try if this works in the devtools console on Windows?

**Comment by andreastt** [comment] 2017-01-04 01:28
@mgavilan Were you able to make any progress on debugging this?

**Comment by AutomatedTester** [comment] 2017-01-18 17:13
CLosing as information has not been added.

**Closed by AutomatedTester** 2017-01-18 17:13 UTC
Labels: waiting on info

**Comment by acodring** [comment] 2017-01-29 00:32
I think I'm seeing this too.
FF 45
Geckodriver v13
Selenium 3.0.1
OSX 10.12.2

I can resize the window, but it doesn't move.
```
wd.manage().window().setSize(new Dimension(640,480));
wd.manage().window().setPosition(new Point(windowPositionX,windowPositionY));
```

I tried window.moveTo as requested above in FF | Developer | Web Console :
```
>>window.moveTo(0,0);
<- undefined
>>window.resizeTo(500,500);
<-undefined
```

**Comment by BrandonDude** [comment] 2017-06-15 15:58
Still an issue with:

**Selenium:** 3.4
**Geckodriver:** 0.17.0
**Firefox:** 54.0 (64-bit)
**Windows:** 7

This has also been reported in issues [335](https://github.com/mozilla/geckodriver/issues/335) & [676](https://github.com/mozilla/geckodriver/issues/676).


### I suggest moving all comments to [676](https://github.com/mozilla/geckodriver/issues/676).
