### ISSUE TITLE
Auto suggest drop-down list issue

### ISSUE THREAD

**Issue by AppleTree74** [mozilla/geckodriver#381] opened 2016-12-06 01:26 UTC
## Meta -
OS: Windows 7 Enterprise 

Browser Version:  
e.g.: 50.0.2623.87 (64-bit)

## Expected Behavior - 
You should be able to select an option from a drop-down list, in this example a location from a travel website (https://www.expedia.co.uk), after entering a few search characters. 

## Actual Behavior -
No location options appear after search criteria are entered. The code below is working for Chrome and Internet Explorer, but not Firefox. 

## Steps to reproduce -
Java code:-

package tests;

import org.testng.annotations.*;
import org.openqa.selenium.*;

import java.util.List;
import java.util.concurrent.TimeUnit;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.ie.InternetExplorerDriver;

public class AjaxExample {
	WebDriver driver;

	@BeforeClass
	public void setUp() throws Exception {

		String browser = "Firefox";

		// select browser driver
		if (browser.equalsIgnoreCase("Firefox")) {
			System.setProperty("webdriver.gecko.driver",
					"//...../Selenium/WebDrivers/geckodriver.exe");
			driver = new FirefoxDriver();
		} else if (browser.equalsIgnoreCase("Chrome")) {
			System.setProperty("webdriver.chrome.driver",
					"//...../Selenium/WebDrivers/chromedriver.exe");
			driver = new ChromeDriver();
		} else if (browser.equalsIgnoreCase("IE")) {
			System.setProperty("webdriver.ie.driver",
					"//...../Selenium/WebDrivers/IEDriverServer.exe");
			driver = new InternetExplorerDriver();
		}

		// url
		driver.get("https://www.expedia.co.uk/");
		driver.manage().window().maximize();
		driver.manage().timeouts().implicitlyWait(30, TimeUnit.SECONDS);
	}

	@Test
	public void testCompanyLookup() throws Exception {

		driver.findElement(By.cssSelector("span.tab-label")).click();

		String search = "so";
		String destination = "Cardiff, Wales, UK";

		driver.findElement(By.id("flight-origin")).clear();
		driver.findElement(By.id("flight-origin")).sendKeys(search);

		List<WebElement> locations = driver.findElements(By.xpath("//li[@class='results-item']/a"));
		System.out.println("Total locations: " + locations.size());

		driver.findElement(By.xpath("//li[@class='results-item']/a[contains(.,'" + destination + "')]")).click();

	}

	@AfterClass
	public void tearDown() throws Exception {
		driver.quit();
	}
}

 - [ ] A [trace level log](https://github.com/mozilla/geckodriver#firefox-capabilities) from geckodriver showing the issue
Output from the console from Eclipse:-
1480987004306	geckodriver	INFO	Listening on 127.0.0.1:3903
Dec 06, 2016 2:16:44 PM org.openqa.selenium.remote.ProtocolHandshake createSession
INFO: Attempting bi-dialect session, assuming Postel's Law holds true on the remote end
log4j:WARN No appenders could be found for logger (org.apache.http.client.protocol.RequestAddCookies).
log4j:WARN Please initialize the log4j system properly.
log4j:WARN See http://logging.apache.org/log4j/1.2/faq.html#noconfig for more info.
1480987004976	mozprofile::profile	INFO	Using profile path C:\Users\PIETER~1.MOL\AppData\Local\Temp\rust_mozprofile.aerogiynT2PU
1480987004981	geckodriver::marionette	INFO	Starting browser C:\Program Files (x86)\Mozilla Firefox\firefox.exe
1480987004993	geckodriver::marionette	INFO	Connecting to Marionette on localhost:61327
1480987005863	Marionette	INFO	Listening on port 61327
Dec 06, 2016 2:16:47 PM org.openqa.selenium.remote.ProtocolHandshake createSession
INFO: Detected dialect: W3C
JavaScript error: https://b.travel-assets.com/datacapture/2-81/01d4e8b0ac521a160cb14098ca971c58fd463e36/datacapture/js/analytics-core-bundle-min.js, line 1: Error: 50003 (Error occurred during the evaluation of one or more experiments.)
JavaScript error: https://b.travel-assets.com/datacapture/2-81/01d4e8b0ac521a160cb14098ca971c58fd463e36/datacapture/js/analytics-core-bundle-min.js, line 1: Error: 50003 (Error occurred during the evaluation of one or more experiments.)
JavaScript error: https://b.travel-assets.com/datacapture/2-81/01d4e8b0ac521a160cb14098ca971c58fd463e36/datacapture/js/analytics-core-bundle-min.js, line 1: Error: 50003 (Error occurred during the evaluation of one or more experiments.)
JavaScript error: https://b.travel-assets.com/datacapture/2-81/01d4e8b0ac521a160cb14098ca971c58fd463e36/datacapture/js/analytics-core-bundle-min.js, line 1: Error: 50003 (Error occurred during the evaluation of one or more experiments.)
JavaScript error: https://b.travel-assets.com/datacapture/2-81/01d4e8b0ac521a160cb14098ca971c58fd463e36/datacapture/js/analytics-core-bundle-min.js, line 1: Error: 50003 (Error occurred during the evaluation of one or more experiments.)
JavaScript error: https://b.travel-assets.com/datacapture/2-81/01d4e8b0ac521a160cb14098ca971c58fd463e36/datacapture/js/analytics-core-bundle-min.js, line 1: Error: 50003 (Error occurred during the evaluation of one or more experiments.)
JavaScript error: https://b.travel-assets.com/datacapture/2-81/01d4e8b0ac521a160cb14098ca971c58fd463e36/datacapture/js/analytics-core-bundle-min.js, line 1: Error: 50003 (Error occurred during the evaluation of one or more experiments.)
JavaScript error: https://b.travel-assets.com/datacapture/2-81/01d4e8b0ac521a160cb14098ca971c58fd463e36/datacapture/js/analytics-core-bundle-min.js, line 1: Error: 50003 (Error occurred during the evaluation of one or more experiments.)
Total locations: 0
[Child 7176] ###!!! ABORT: Aborting on channel error.: file c:/builds/moz2_slave/m-rel-w32-00000000000000000000/build/src/ipc/glue/MessageChannel.cpp, line 2056
Dec 06, 2016 2:18:01 PM org.openqa.selenium.os.UnixProcess destroy
SEVERE: Unable to kill process with PID 9292
FAILED: testCompanyLookup
 
 - [ ] A minimal HTML file (or files) that can be used to reproduce the issue
 - [ ] A Selenium code snippet that can be run as is to reproduce the issues

** If any of the above are missing we will have to unforunately close your issue. We will gladly reopen the issue once all the information requested has been added **

**Comment by andreastt** [comment] 2016-12-09 00:16
I guess this is because we do not generate all the right keyboard events when typing, so I think we can mark this as a duplicate of https://github.com/mozilla/geckodriver/issues/348.

**Closed by andreastt** 2016-12-09 00:16 UTC
