### ISSUE TITLE
Calling a Frame with an incorrect value

### ISSUE THREAD

**Issue by titusfortner** [mozilla/geckodriver#1456] opened 2018-12-24 20:42 UTC
## System

* Version: 0.23
* Platform: Mac
* Firefox: 64
* Selenium: 3.141.0

## Testcase

HTML does not matter

## Trace-level log

Note, I found this while refactoring Watir code and accidentally passing in the wrong object. Chrome was giving the expected error and Firefox was not.

```
2018-12-24 14:35:47 INFO Selenium -> POST session/048b061c-fae2-624c-b701-72c2e9f24b05/frame
2018-12-24 14:35:47 INFO Selenium    >>> http://127.0.0.1:4444/session/048b061c-fae2-624c-b701-72c2e9f24b05/frame | {"id":"#<Watir::FramedDriver:0x00007fc10d338f08>"}
2018-12-24 14:35:47 INFO Selenium <- {"value":{"error":"invalid argument","message":"data did not match any variant of untagged enum FrameId at line 1 column 50","stacktrace":""}}
```

Per spec I would expect:
> If id is not null, a Number object, or an Object that represents a web element, return error with error code no such frame.

**Comment by whimboo** [comment] 2019-01-02 09:09
Thanks @titusfortner! This looks like a regression from moving to Serde. I filed https://bugzilla.mozilla.org/show_bug.cgi?id=1517196 to get this fixed.

**Comment by JohnChen0** [comment] 2019-01-07 17:01
I'm OK with updating the WebDriver specification to return `invalid argument` in this case.

What ChromeDriver does is actually a little more complicated. It does return `invalid argument` if the frame id is a type it doesn't recognize:

```
curl -X POST http://localhost:9515/session/4e5cbd50763e9bf481ea93c703499efa/frame -d '{"id":[]}'
{"sessionId":"4e5cbd50763e9bf481ea93c703499efa","status":61,"value":{"message":"invalid argument: invalid 'id'\n  (Session info: chrome=71.0.3578.98)\n  (Driver info: chromedriver=2.45.615279 (12b89733300bd268cff3b78fc76cb8f3a7cc44e5),platform=Linux 4.18.10-1rodete2-amd64 x86_64)"}}
```

An id of string type, however, is handled as a spacial case, carried over from pre-W3C days. The string is interpreted as a frame ID, and ChromeDriver searches for a frame with `name` or `id` attribute that matches the string. If such a frame is not found, then `no such frame` error is returned.

**Comment by whimboo** [comment] 2019-01-07 19:54
Ah, that is good to know! Thanks for the explanation, and allowing us to fix the specification. I filed https://github.com/w3c/webdriver/issues/1387 to get it corrected.

As such we can close this geckodriver specific issue because it's working as expected.

**Closed by whimboo** 2019-01-07 19:54 UTC
Labels: geckodriver

**Comment by whimboo** [comment] 2019-01-10 07:17
Thanks to this issue we now have an updated spec, and webdriver tests which should fully cover each aspect of the switch to frame command.
