### ISSUE TITLE
geckodriver.log spammed with pdfjs.js errors

### ISSUE THREAD

**Issue by OscarVanL** [mozilla/geckodriver#1729] opened 2020-06-03 14:14 UTC
## System

* Version: geckodriver-v0.26.0-win64
* Platform: Windows
* Firefox: 76.0.1 (64-bit)
* Selenium: Python 3.8 + Selenium 3.141.0

## Testcase

I am downloading a large number of PDFs, I have set these to auto-download, and disabled the browser PDF plugin as I do not need PDF previews.

```
ffx_profile = webdriver.FirefoxOptions()
# Allows Selenium to download to non-default location
ffx_profile.set_preference('browser.download.folderList', 2)
ffx_profile.set_preference('browser.download.dir', output_attachments)
# Disable PDF browser plugin
ffx_profile.set_preference('plugin.disable_full_page_plugin_for_types', 'application/pdf')
ffx_profile.set_preference('pdfjs.disabled', True)
ffx_profile.set_preference('pdfjs.enabledCache.state', False)
# Enable autosave for PDFs.
ffx_profile.set_preference('browser.download.manager.showWhenStarting', False)
ffx_profile.set_preference('browser.helperApps.neverAsk.saveToDisk', 'application/pdf')
ffx_profile.set_preference('browser.helperApps.alwaysAsk.force', False)
driver = webdriver.Firefox(options=ffx_profile)

driver.get('https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf')
```

I expect the error may be caused because pdfjs is disabled so throwing an exception of some kind that geckodriver does not expect.

## Stacktrace

Selenium + geckodriver are working as expected and my client gives errors/stack traces, however the `geckodriver.log` file is spammed with the same error:

`JavaScript error: resource:///modules/pdfjs.js, line 31: uncaught exception: 2147746132`

## Trace-level log

[geckodriver.log](https://github.com/mozilla/geckodriver/files/4723972/geckodriver.log)

**Comment by whimboo** [comment] 2020-06-03 20:10
Note that this output is caused by:
https://searchfox.org/mozilla-central/rev/7cadba1d8b8feaec4615f5bb98aac4b8a719793c/browser/extensions/pdfjs/pdfjs.js#31

Whatever uses `StreamConverterFactory` here should be fixed. I assume you see the same in the browser console under `Tools -> WebDeveloper`? If yes would you mind filing a bug for Firefox under [Firefox / General](https://bugzilla.mozilla.org/enter_bug.cgi?product=Firefox&component=General)?

Note that we don't have filtering in geckodriver so that all the log output of Firefox is redirected to geckodriver. See issue #1046, which this is a dupe of from geckodriver perspective.

**Closed by whimboo** 2020-06-03 20:10 UTC
