### ISSUE TITLE
Failed to maximize browser using window().maximize() | GeckoDriver: v0.17.0, Selenium: v3.4.0, Firefox: v54.0

### ISSUE THREAD

**Issue by avinvarghese** [mozilla/geckodriver#808] opened 2017-07-06 13:54 UTC
## Platform and application details
* Ubunut 16.04 
* Firefox: 54.0
* Selenium: 3.4.0
* GeckoDriver: 0.17.0

## Steps to reproduce
```
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;

public class FirefoxTest {
	
	public static void main(String[] args) throws InterruptedException {		
		System.setProperty("webdriver.gecko.driver","/usr/local/geckodriver/geckodriver");

		FirefoxDriver driver = new FirefoxDriver();
		driver.get("http://google.com");
		Thread.sleep(5000);
		//minimize the browser.
                System.out.println("minimize...");
		driver.manage().window().maximize();
                System.out.println("maximize..");
}
```

- [x] Log:
```
1499345054197	geckodriver	INFO	Listening on 127.0.0.1:16963
1499345054527	geckodriver::marionette	INFO	Starting browser /usr/lib/firefox/firefox with args ["-marionette"]
1499345058311	Marionette	INFO	Listening on port 34344
Jul 06, 2017 6:14:18 PM org.openqa.selenium.remote.ProtocolHandshake createSession
INFO: Detected dialect: W3C
minimize...
maximize..
```

**Comment by andreastt** [comment] 2017-07-11 20:37
What exactly is the problem? I don’t see any stacktrace or error resulting from running this code. It would generally help if you also provided a stacktrace and tested this against Firefox Nightly, because that’s the target we are currently developing against.

I have recently done substantive work on the Maximize Window command, so you may find that whatever your problem is, will be fixed in Nightly.

**Comment by andreastt** [comment] 2017-07-13 16:26
I suspect this is a duplicate of https://github.com/mozilla/geckodriver/issues/820.

**Closed by andreastt** 2017-07-13 16:26 UTC
Labels: waiting for reporter feedback

**Comment by skptricks** [comment] 2018-03-03 13:48
update to latest ChromeDriver that is 2.33. Hope it will resolve your issues.
