### ISSUE TITLE
Navigating to a local html file crashes the geckodriver with Firefox 55

### ISSUE THREAD

**Issue by datatooldev** [mozilla/geckodriver#861] opened 2017-08-09 16:18 UTC
## System
* Version: 18
* Platform: Windows 10
* Firefox: 55
* C# Binding

## Testcase

Navigating to a local file crashes the communication between the driver and the browser. The following code demonstrates the issue. The browser gets stacked at the local file. The same code works fine with Firefox 54 or earlier versions.

             FirefoxOptions options = new FirefoxOptions();
            options.LogLevel = FirefoxDriverLogLevel.Trace;
            var driver = new FirefoxDriver(options);
            driver.Navigate().GoToUrl("about:blank");
            driver.Navigate().GoToUrl(@"file:///C:/recentprojects.html");
            driver.Navigate().GoToUrl("about:blank");
            driver.Quit();

## Trace-level log

1502295661262   geckodriver     INFO    geckodriver 0.18.0
1502295661269   geckodriver     INFO    Listening on 127.0.0.1:51177
1502295662575   geckodriver::marionette INFO    Starting browser C:\Program Files\Mozilla Firefox\firefox.exe with args ["-marionette"]
1502295664595   geckodriver::marionette DEBUG   Connected to Marionette on localhost:51181
1502295664598   geckodriver::marionette TRACE   <- {"applicationType":"gecko","marionetteProtocol":3}
1502295664598   geckodriver::marionette TRACE   -> 163:[0,1,"newSession",{"acceptInsecureCerts":true,"browserName":"firefox","capabilities":{"desiredCapabilities":{"acceptInsecureCerts":true,"browserName":"firefox"}}}]
1502295664653   geckodriver::marionette TRACE   <- [1,1,null,{"sessionId":"d76cb3d7-36e0-4143-bd49-8d86840d19ef","capabilities":{"browserName":"firefox","browserVersion":"55.0","platformName":"windows_nt","platformVersion":"10.0","pageLoadStrategy":"normal","acceptInsecureCerts":true,"timeouts":{"implicit":0,"pageLoad":300000,"script":30000},"rotatable":false,"specificationLevel":0,"moz:processID":9080,"moz:profile":"C:\\Users\\lvov\\AppData\\Local\\Temp\\rust_mozprofile.QVpclFtn3dIN","moz:accessibilityChecks":false}}]
1502295664653   webdriver::server       DEBUG   <- 200 OK {"value": {"sessionId":"d76cb3d7-36e0-4143-bd49-8d86840d19ef","capabilities":{"acceptInsecureCerts":true,"browserName":"firefox","browserVersion":"55.0","moz:accessibilityChecks":false,"moz:processID":9080,"moz:profile":"C:\\Users\\lvov\\AppData\\Local\\Temp\\rust_mozprofile.QVpclFtn3dIN","pageLoadStrategy":"normal","platformName":"windows_nt","platformVersion":"10.0","rotatable":false,"specificationLevel":0,"timeouts":{"implicit":0,"pageLoad":300000,"script":30000}}}}
1502295664702   webdriver::server       DEBUG   -> POST /session/d76cb3d7-36e0-4143-bd49-8d86840d19ef/url {"url":"about:blank"}
1502295664703   geckodriver::marionette TRACE   -> 33:[0,2,"get",{"url":"about:blank"}]
1502295664735   geckodriver::marionette TRACE   <- [1,2,null,{}]
1502295664736   webdriver::server       DEBUG   <- 200 OK {"value": {}}
1502295664737   webdriver::server       DEBUG   -> POST /session/d76cb3d7-36e0-4143-bd49-8d86840d19ef/url {"url":"file:///C:/recentprojects.html"}
1502295664738   geckodriver::marionette TRACE   -> 52:[0,3,"get",{"url":"file:///C:/recentprojects.html"}]
1502295724739   webdriver::server       DEBUG   -> POST /session/d76cb3d7-36e0-4143-bd49-8d86840d19ef/url {"url":"about:blank"}
1502295785742   webdriver::server       DEBUG   -> DELETE /session/d76cb3d7-36e0-4143-bd49-8d86840d19ef

**Comment by whimboo** [comment] 2017-08-09 17:25
We don't have official support for navigating to file:// URLs before Firefox 56.0. So you should upgrade to Firefox 56.0 which will handle it correctly. See issue #469.

Also the trace doesn't show any kind of crash or something related because most likely it misses all the debug/tracing output from Firefox.

Please report back how it works with Firefox 56.0b1. Thanks.

**Comment by datatooldev** [comment] 2017-08-09 18:35
Thank you for prompt response. The driver works fine with Firefox 56.0b1.
Here is the trace:

1502303494402   webdriver::server       DEBUG   -> POST /session/cbf9b84c-e429-4867-901f-4b99a5407c41/url {"url":"file:///C:/recentprojects.html"}
1502303494403   geckodriver::marionette TRACE   -> 52:[0,3,"get",{"url":"file:///C:/recentprojects.html"}]
1502303495271   geckodriver::marionette TRACE   <- [1,3,null,{}]
1502303495280   webdriver::server       DEBUG   <- 200 OK {"value": {}}
1502303495284   webdriver::server       DEBUG   -> POST /session/cbf9b84c-e429-4867-901f-4b99a5407c41/url {"url":"about:blank"}
1

**Comment by whimboo** [comment] 2017-08-09 18:44
Great! Marking as dupe of #469.

**Closed by whimboo** 2017-08-09 18:44 UTC
Labels: waiting for reporter feedback
