### ISSUE TITLE
Cannot start the driver service on http://localhost

### ISSUE THREAD

**Issue by copavan** [mozilla/geckodriver#372] opened 2016-11-30 08:46 UTC
I'm using the Geckodriver and seeing the issue "Cannot start the driver service on http://localhost". I have also set the path in Environment variables for the Gecko Driver executable. Can anyone please help.

Seeing the below error :
---------------------------
geckodriver.exe - Application Error
---------------------------
The application was unable to start correctly (0xc0000142). Click OK to close the application.

**Comment by jgraham** [comment] 2016-11-30 09:20
It's hard to diagnose anything with so little information, but it might be that you are trying to run the wrong geckodriver for your architecture? Which build did you download and which OS/hardware are you using (in particular I suspect you might be trying to run a Windows 64 build on 32 bit Windows).

**Comment by copavan** [comment] 2016-11-30 15:29
hi Graham,
We are using Selenium with C# (Visual Studio and Microsoft Test Manager). we are using the latest version: Geckodriver-v0.11.1-win64. I have Windows 7 enterprise edition 64 bit operating system (please see the below screenshot). My colleagues are also facing the same issue. This problem occurs only when we try to debug any test from Visual Studio with Firefox as the default browser. But it works fine when we run our tests on a Virtual machine from Microsoft Test Manager. 
Also we have installed the latest versions of Selenium webdriver, Firefox Driver, Chrome Driver and IE driver. Below are the versions.

1) Selenium WebDriver 3.0.1 
2) Selenium Support 3.0.1
3) Mozilla Firefox Webdriver 0.6.0.1
4) Chrome Driver 2.25.0.8
5) IE driver 3.0.0.1


![winos](https://cloud.githubusercontent.com/assets/24267066/20758044/8bd7b62e-b6e6-11e6-8d8f-306a18de1a88.PNG)

**Comment by andreastt** [comment] 2016-11-30 18:15
So what happens if you execute geckodriver.exe from the Windows command prompt? Do you get any errors then?

**Comment by copavan** [comment] 2016-11-30 19:12
![geckodriverrun](https://cloud.githubusercontent.com/assets/24267066/20767061/da4ce84a-b706-11e6-8322-7d9908820d85.PNG)

please see the attached when I run the geckoDriver exe manually

**Comment by jishusharma** [comment] 2016-12-02 11:46
Hi! I am also facing the same error. 

My code - 
var driverService = FirefoxDriverService.CreateDefaultService(@"D:\tools\Selenium dotnet\geckodriver-v0.9.0-win64", "geckodriver.exe");
                driverService.FirefoxBinaryPath = @"C:\Program Files (x86)\Mozilla Firefox\firefox.exe";
                driverService.HideCommandPromptWindow = true;
                driverService.SuppressInitialDiagnosticInformation = true;
                DriverInstance = new FirefoxDriver(driverService, new FirefoxOptions(), TimeSpan.FromSeconds(10));

Error: Cannot start the driver service on http://localhost:12879/

I tried to do driverService.Start(); just before creating new FirefoxDriver and found that it fails with the same exception. 

What I wish to know is that why this particular code stopped working after upgrading to selenium-dotnet-3.0.1. If I revert back just the reference dlls WebDriver.dll and WebDriver.Support.dll to selenium-dotnet-2.53.1, then driverService.Start(); executes and eveything works. 

Specifications : 
Windows7, Visual Studio

**Comment by jgraham** [comment] 2016-12-02 11:53
If the binary is working normally, it seems like you should file this issue with the selenium project. If it turns out there is a geckodriver bug I expect they will be able to provide us with details of the exact problem.

**Comment by andreastt** [comment] 2016-12-09 00:17
Closing this since no actionable reproducible steps have been added. I’m happy to re-open it if you think this is wrong.

**Closed by andreastt** 2016-12-09 00:17 UTC

**Comment by jishusharma** [comment] 2016-12-09 08:27
I should have mentioned it before. We have an open issue now with Selenium project - 
https://github.com/SeleniumHQ/selenium/issues/3195
