### ISSUE TITLE
GeckoDriver 0.16.0 not taking full Page Screenshot

### ISSUE THREAD

**Issue by anukriti-chawla** [mozilla/geckodriver#687] opened 2017-04-26 09:17 UTC
GeckoDriver Version 0.16.0
Firefox 51
selenium 3.4
java 1.8
I am trying take full page screenshot but the following code is taking screenshot of only in view webpage.
This issue persists since many previous versions of geckodriver. When this will get resolved.
Code to take Screenshot is : 

String screenshotBase64 = ((TakesScreenshot) driver).getScreenshotAs(OutputType.BASE64);

**Comment by SergioLeone** [comment] 2017-04-26 09:25
This is working fine for me with selenium_3.4.0+gecko_0.16.0+ff_53.0:
```
TakesScreenshot ts=(TakesScreenshot)driver;
File source=ts.getScreenshotAs(OutputType.FILE);
```

Also, you shouldn't use ff 51 with latest version of gecko and selenium as mentioned in the release notes

**Comment by anukriti-chawla** [comment] 2017-04-27 11:05
@SergioLeone 
Hi 
I used ff 53.0, gecko 0.16 and selenium 3.4.0
But even then it is not taking full page screenshot. Only taking screenshot of first (upper) view of page.

**Comment by andreastt** [comment] 2017-04-27 22:43
Duplicate of https://github.com/mozilla/geckodriver/issues/570.

See [my comment](https://github.com/mozilla/geckodriver/issues/570#issuecomment-289788299) there for some further information on full-document screenshots. The tl;dr is that WebDriver does not officially support these, but that we can do them in geckodriver.

**Closed by andreastt** 2017-04-27 22:43 UTC
