### ISSUE TITLE
 Will Gecko Web Driver ever wait for the page to load

### ISSUE THREAD

**Issue by kcrump** [mozilla/geckodriver#344] opened 2016-11-16 15:42 UTC
I opened this issue before and it was closed by @andreastt because I did not have any reproducible steps.  I am not sure what he is looking for but if I am missing something please let me know instead of just closing the ticket. 
I am using Windows 8 and Firefox 50.0 (however I experienced this issue on previous versions of Firefox). I am running my script in MyEclipse.  
Gecko does not wait until the page loads before it allows my test to continue. The old firefox Selenium web driver would wait. Is there something that I could add to my script so that Gecko could wait until the page loads before continuing? I am using a script that records how long it takes for different pages to load in a website.  I attached the file that contains my scripts.  
If you all need more information then please let me know as I signed up for this site to look for help. 

Here is a snipped of my script
    pageLoad.start();
    driver.findElement(By.xpath("//*[@id='navcreativeon']")).click();
    WebDriverWait wait1 = new WebDriverWait(driver, 10);
    wait1.until(ExpectedConditions.presenceOfElementLocated(By.xpath("//*[@id='content']/div[1]/div/blockquote/fieldset/div/ul/li[1]/a[2]")));
    pageLoad.stop();
    long pageLoadTime_ms1 = pageLoad.getTime();
    long pageLoadTime_Seconds1 = pageLoadTime_ms1 / 1000;
    System.out.println("Total Promotion Home Page Load Time: " + pageLoadTime_ms1 + " milliseconds");
    System.out.println("Total Promotion Home Page Load Time: " + pageLoadTime_Seconds1 + " seconds");
    System.out.println("====================================");
        
    pageLoad.reset();

[load.txt](https://github.com/mozilla/geckodriver/files/595052/load.txt)

**Comment by andreastt** [comment] 2016-11-16 15:52
I don”t know what `pageLoad.start` is or the contents of the document you are trying to load. If you can provide an HTML document which Marionette isn’t waiting for the DOMContentLoaded event to occur before returning, I would be much obliged.

**Comment by kcrump** [comment] 2016-11-16 19:31
I cannot provide you with the html page that I use because it is an internal page that you will not be able to access.  I did provide you with a script going to the w3 site.  When this runs on my browser it doesnt look like the 2nd link is being accessed (or clicked on).   


package com.kcrump;

import java.util.regex.Pattern;
import java.util.concurrent.TimeUnit;

import org.apache.commons.lang3.time.StopWatch;
import org.junit.*;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.*;
import org.openqa.selenium.*;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.Select;
import org.openqa.selenium.support.ui.WebDriverWait;

public class Time_Load2forhim {
  private WebDriver driver;
  private String baseUrl;
  private boolean acceptNextAlert = true;
  private StringBuffer verificationErrors = new StringBuffer();

  @Before
  public void setUp() throws Exception {
	System.setProperty("webdriver.gecko.driver", "C:\\resources\\geckodriver\\geckodriver.exe");  //nmark if using geckodriver 
	driver = new FirefoxDriver();
	baseUrl = "http://www.w3schools.com/";
    driver.manage().timeouts().implicitlyWait(30, TimeUnit.SECONDS);
    driver.manage().window().maximize();
  }

  @Test
  public void testTimeLoad2forhim() throws Exception {
    driver.get(baseUrl);
    StopWatch pageLoad = new StopWatch();
    

    pageLoad.start();
    driver.findElement(By.xpath("//nav[@id='mySidenav']/a")).click();
    WebDriverWait wait1 = new WebDriverWait(driver, 10);
    wait1.until(ExpectedConditions.presenceOfElementLocated(By.linkText("Go to HTML Examples!")));
    pageLoad.stop();
    long pageLoadTime_ms1 = pageLoad.getTime();
    long pageLoadTime_Seconds1 = pageLoadTime_ms1 / 1000;
    System.out.println("First Link on w3 page: " + pageLoadTime_ms1 + " milliseconds");
    System.out.println("First Link on w3 page: " + pageLoadTime_Seconds1 + " seconds");
    System.out.println("====================================");
    pageLoad.reset();
   
    pageLoad.start();
    driver.findElement(By.linkText("HTML Editors")).click();
    WebDriverWait wait2 = new WebDriverWait(driver, 10);
    wait2.until(ExpectedConditions.presenceOfElementLocated(By.linkText("HTML Basic")));
    pageLoad.stop();
    long pageLoadTime_ms2 = pageLoad.getTime();
    long pageLoadTime_Seconds2 = pageLoadTime_ms2 / 1000;
    System.out.println("2nd Link on W3: " + pageLoadTime_ms2 + " milliseconds");
    System.out.println("2nd Link on W3: " + pageLoadTime_Seconds2 + " seconds");
    System.out.println("===========================================");
    
    pageLoad.reset();
    driver.close();
  }

  @After
  public void tearDown() throws Exception {
    driver.quit();
    String verificationErrorString = verificationErrors.toString();
    if (!"".equals(verificationErrorString)) {
      fail(verificationErrorString);
    }
  }

  private boolean isElementPresent(By by) {
    try {
      driver.findElement(by);
      return true;
    } catch (NoSuchElementException e) {
      return false;
    }
  }

  private boolean isAlertPresent() {
    try {
      driver.switchTo().alert();
      return true;
    } catch (NoAlertPresentException e) {
      return false;
    }
  }

  private String closeAlertAndGetItsText() {
    try {
      Alert alert = driver.switchTo().alert();
      String alertText = alert.getText();
      if (acceptNextAlert) {
        alert.accept();
      } else {
        alert.dismiss();
      }
      return alertText;
    } finally {
      acceptNextAlert = true;
    }
  }
}

**Comment by tortlepp** [comment] 2016-11-17 15:00
Seems I stumbled upon the same issue today. The setup I am using is:

- Selenium IDE to record tests
- Selenese Runner Java (https://github.com/vmi/selenese-runner-java) to start the tests
- Selenium Standalone Server to run the tests on different browsers

The tests run properly on Selenium 2.53.1 (with build in Firefox support) but they fail on Selenium 3.0.1 with  geckodriver 0.11.1. In both cases Firefox ESR 45.5.0 is used.

When using geckodriver and calling _clickAndWait_ there is no waiting at all, the next command is executed immediately. Also an explicit _waitForPageToLoad_ behaves in the same way.

Unfortunately the website I am testing is still beta and not public yet but I will try to further investigate the issue and maybe also provide a sample HTML (if possible).

**Comment by andreastt** [comment] 2016-11-17 16:26
@tortlepp geckodriver does not support Firefox 45. You should consider using [Nightly](https://nightly.mozilla.org/).

I’m going to close this issue until someone comes up with a way to reproduce this issue.

**Closed by andreastt** 2016-11-17 16:26 UTC

**Comment by kcrump** [comment] 2016-11-17 16:29
@andreastt  I gave you the test case.  The simple one that you called "nonsense" doesn't even work.  Did you try to run it at least?

**Comment by tortlepp** [comment] 2016-11-17 21:20
@andreastt You are right, I didn't see that requirement. But anyway the problem is not related to the Firefox version. I tried ESR 45.5.0 , Stable 50.0 and Nightly 53.0a1 - the issue occurs with all these Firefox versions. Also the operating system does not matter, I tried Windows and Linux and got the same results.

In the Selenium Server Node I see a Java stack trace when the _Wait_ part of _clickAndWait_ fails:

```
21:24:29.704 WARN - Exception thrown
org.openqa.selenium.JavascriptException: [object Object]
Build info: version: '3.0.1', revision: '1969d75', time: '2016-10-18 09:48:19 -0700'
System info: host: 'XXX', ip: 'XXX', os.name: 'Windows 7', os.arch: 'amd64', os.version: '6.1', java.version: '1.8.0_112'
Driver info: org.openqa.selenium.firefox.FirefoxDriver
Capabilities [{rotatable=false, raisesAccessibilityExceptions=false, firefoxOptions={args=[], profile=...}, appBuildId=20161117030212, version=, platform=XP, proxy={}, command_id=1, specificationLevel=0, acceptSslCerts=false, processId=5840, browserVersion=53.0a1, platformVersion=6.1, XULappId={ec8030f7-c20a-464f-9b0e-13a3a9e97384}, browserName=firefox, takesScreenshot=true, takesElementScreenshot=true, platformName=windows_nt, firefox_profile=UEsDBBQACAgIAAqrcUkAAAAAAAAAA...}]
Session ID: 295bb552-38f3-42bd-83b5-da234aa9b5de
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
	at java.lang.reflect.Constructor.newInstance(Unknown Source)
	at org.openqa.selenium.remote.http.W3CHttpResponseCodec.createException(W3CHttpResponseCodec.java:127)
	at org.openqa.selenium.remote.http.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:93)
	at org.openqa.selenium.remote.http.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:42)
	at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:163)
	at org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:82)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:601)
	at org.openqa.selenium.remote.RemoteWebDriver.executeScript(RemoteWebDriver.java:537)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.openqa.selenium.support.events.EventFiringWebDriver$2.invoke(EventFiringWebDriver.java:103)
	at com.sun.proxy.$Proxy6.executeScript(Unknown Source)
	at org.openqa.selenium.support.events.EventFiringWebDriver.executeScript(EventFiringWebDriver.java:216)
	at org.openqa.selenium.remote.server.handler.ExecuteScript.call(ExecuteScript.java:54)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at org.openqa.selenium.remote.server.DefaultSession$1.run(DefaultSession.java:176)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
```
I think that really the _wait_ part of _clickAndWait_ fails because a _click_ (with the same locator) followed by a _pause_ (for let's say 10 seconds) gives a working test.

**Comment by milosc** [comment] 2017-01-22 19:03
Same issue here. Wait.Until works just for By.Id selector. If I put xpath ones it dies.

**Comment by andreastt** [comment] 2017-01-23 10:27
@tortlepp The Wait utility you refer to is a Selenium component and not related to geckodriver in any way. Please provide a _reproducible_ test case for me to take this issue seriously.

**Comment by tracim** [comment] 2017-03-03 09:26
We are facing the same issue, here. Is there an issue open on Selenium bug tracker ?

**Comment by tortlepp** [comment] 2017-03-05 13:50
Well, I did no further investigation on this case. I stumbled upon more issues with geckodriver and Selenium 3 - all in all that combination still feels like a beta. So I switched my entire testing to Chrome with chromedriver which works without any issues at all.

**Comment by sethuster** [comment] 2017-03-10 19:33
I've also seen this issue with our firefox tests.  Unable to set the page_load timeout object properly.  

Switching to chrome driver and everything works perfectly out of the box.  That's a shame. Oh well, on ward and upward.

**Comment by DMWOO7** [comment] 2017-03-12 09:23
Same issue like the poster above me, but using C# and the latest versions avaliable: 

Selenium.WebDriver = 3.3.0
Selenium.Firefox.WebDriver = 0.14.0

I submit an HTML form and check the page source for a string, that confirms if the login was successfull. But the test continues, so that the page source contains the input form, not the output which is displayed after submit. Seems to be an issue of gecko/firefox. For testing purpose, I switched to the latest Chrome driver. There, my test works fine like expected.

**Comment by andreastt** [comment] 2017-03-23 07:46
Locking due to obnoxious comments.
