### ISSUE TITLE
moveTo() doesn't work - on googleChrome it does

### ISSUE THREAD

**Issue by Pieras2** [mozilla/geckodriver#1683] opened 2020-02-04 13:32 UTC
## System

* Version: 0.26.0
* Platform: Windows 10
* Firefox: 72.0.2

## Testcase
For test purpose used this one https://www.webpagetest.org/

## Stacktrace

 ```
Starting GeckoDriver on port 4444...
 GeckoDriver up and running on port 4444 with pid: 3340 (135ms).

[Test File] Test Suite
======================
- Connecting to localhost on port 4444...
   Request POST  /session  
   { capabilities:
      { browserName: 'firefox',
        alwaysMatch: { 'moz:firefoxOptions': { args: [] } },
        name: 'Test File' },
     desiredCapabilities:
      { browserName: 'firefox',
        platform: 'ANY',
        alwaysMatch: { 'moz:firefoxOptions': { args: [] } },
/ Connecting to localhost on port 4444...
   Response 200 POST /session (2048ms)
   { value:
      { sessionId: 'e0f0daf0-1b2a-4699-a713-79329fb27de4',
        capabilities:
         { acceptInsecureCerts: false,
           browserName: 'firefox',
           browserVersion: '72.0.2',
           'moz:accessibilityChecks': false,
           'moz:buildID': '20200117190643',
           'moz:geckodriverVersion': '0.26.0',
           'moz:headless': false,
           'moz:processID': 23136,
           'moz:profile':
            'C:\\Users\\admin\\AppData\\Local\\Temp\\rust_mozprofileE0xPLb',
           'moz:shutdownTimeout': 60000,
           'moz:useNonSpecCompliantPointerOrigin': false,
           'moz:webdriverClick': true,
           pageLoadStrategy: 'normal',
           platformName: 'windows',
           platformVersion: '10.0',
           rotatable: false,
           setWindowRect: true,
           strictFileInteractability: false,
           timeouts: { implicit: 0, pageLoad: 300000, script: 30000 },
i Connected to localhost on port 4444 (2099ms).
  Using: firefox (72.0.2) on windows 10.0 platform.

 Received session with ID: e0f0daf0-1b2a-4699-a713-79329fb27de4


 → Running command: status ([Function])
   Request GET  /status  
   Response 200 GET /status (2ms)
   { value: { message: 'Session already started', ready: false } }
{ message: 'Session already started', ready: false }
  → Completed command: status ([Function]) (14ms)
 → Running [before]:
 → Completed [before].
Running:  LogIn

 → Running [beforeEach]:
 → Completed [beforeEach].

 → Running command: url ('https://www.webpagetest.org/', [Function])
   Request POST  /session/e0f0daf0-1b2a-4699-a713-79329fb27de4/url  
   { url: 'https://www.webpagetest.org/' }
   Response 200 POST /session/e0f0daf0-1b2a-4699-a713-79329fb27de4/url (1417ms)
   { value: null }
  → Completed command: url ('https://www.webpagetest.org/', [Function]) (1419ms)

 → Running command: getLocation ('.logo', [Function])
   Request POST  /session/e0f0daf0-1b2a-4699-a713-79329fb27de4/elements  
   { using: 'css selector', value: '.logo' }
   Response 200 POST /session/e0f0daf0-1b2a-4699-a713-79329fb27de4/elements (22ms)
   { value:
      [ { 'element-6066-11e4-a52e-4f735466cecf': 'e58b16c2-6563-4995-a37f-e2174b6ce147' } ] }
   Request GET  /session/e0f0daf0-1b2a-4699-a713-79329fb27de4/element/e58b16c2-6563-4995-a37f-e2174b6ce147/rect  
   Response 200 GET /session/e0f0daf0-1b2a-4699-a713-79329fb27de4/element/e58b16c2-6563-4995-a37f-e2174b6ce147/rect (44ms)
   { value: { x: 143.5, y: 18, width: 222, height: 102.8000030517578 } }
Coords: 143.5,18
  → Completed command: getLocation ('.logo', [Function]) (78ms)

 → Running command: moveToElement ('#nav_bar .current', 143.5, 18)
   Request POST  /session/e0f0daf0-1b2a-4699-a713-79329fb27de4/elements  
   { using: 'css selector', value: '#nav_bar .current' }
   Response 200 POST /session/e0f0daf0-1b2a-4699-a713-79329fb27de4/elements (77ms)
   { value:
      [ { 'element-6066-11e4-a52e-4f735466cecf': 'd117dcf1-dc73-41f2-9b2a-6d9f25c9fa47' } ] }
   Request POST  /session/e0f0daf0-1b2a-4699-a713-79329fb27de4/moveto  
   { element: 'd117dcf1-dc73-41f2-9b2a-6d9f25c9fa47',
     xoffset: 143.5,
     yoffset: 18 }
   Response 405 POST /session/e0f0daf0-1b2a-4699-a713-79329fb27de4/moveto (2ms)
   { status: -1, value: 'HTTP method not allowed' }
 Error while running .moveTo() protocol action: An unknown error has occurred.

  → Completed command: moveToElement ('#nav_bar .current', 143.5, 18) (84ms)

 → Running command: mouseButtonClick (1)
   Request POST  /session/e0f0daf0-1b2a-4699-a713-79329fb27de4/click  
   { button: 1 }
   Response 405 POST /session/e0f0daf0-1b2a-4699-a713-79329fb27de4/click (3ms)
   { status: -1, value: 'HTTP method not allowed' }
 Error while running .mouseButtonClick() protocol action: An unknown error has occurred.

  → Completed command: mouseButtonClick (1) (31ms)

 → Running command: pause (10000)
  → Completed command: pause (10000) (10002ms)
 → Running [afterEach]:
 → Completed [afterEach].

FAILED: 1 errors (11.621s)
 → Running [after]:
 → Completed [after].
{ name: 'LogIn',
  module: 'testFile',
  group: '',
  results:
   { time: '11.62',
     assertions: [],
     passed: 0,
     errors: 1,
     failed: 0,
     retries: undefined,
     skipped: 0,
     tests: 0,
     steps: [],
     lastError:
      { TimeoutError: An error occurred while running .moveToElement() command on <#nav_bar .current>: undefined; undefined
          at Function.getError (C:\CS6-LandingPage\node_modules\@qc\nightwatch\node_modules\nightwatch\lib\utils\periodic-promise.js:157:12)
          at PeriodicPromise.perform (C:\CS6-LandingPage\node_modules\@qc\nightwatch\node_modules\nightwatch\lib\utils\periodic-promise.js:109:27)
          at process._tickCallback (internal/process/next_tick.js:68:7)
        name: 'TimeoutError',
        now: 1580823002246,
        response: [Object],
        startTime: undefined,
        detailedErr:
         '{"status":-1,"value":"HTTP method not allowed","errorStatus":-1,"error":"An unknown error has occurred.","httpStatusCode":405}' },
     stackTrace:
      'TimeoutError: An error occurred while running .moveToElement() command on <#nav_bar .current>: undefined; undefined\n    at Function.getError (C:\\CS6-LandingPage\\node_modules\\@qc\\nightwatch\\node_modules\\nightwatch\\lib\\utils\\periodic-promise.js:157:12)\n    at PeriodicPromise.perform (C:\\CS6-LandingPage\\node_modules\\@qc\\nightwatch\\node_modules\\nightwatch\\lib\\utils\\periodic-promise.js:109:27)\n    at process._tickCallback (internal/process/next_tick.js:68:7)',
     testcases: { LogIn: [Object] },
     timeMs: 11621 } }
 
 → Running command: end ([Function])
 Failures in "LogIn". Taking screenshot...

 → Running command: saveScreenshot ('C:\CS6-LandingPage\screens\testFile\LogIn_FAILED_Feb-04-2020-143012-GMT+0100.png', [Function])
 
 → Running command: screenshot (false, [Function])
   Request GET  /session/e0f0daf0-1b2a-4699-a713-79329fb27de4/screenshot  
   Response 500 GET /session/e0f0daf0-1b2a-4699-a713-79329fb27de4/screenshot (87ms)
   { value: '', suppressBase64Data: true }
 Error while running .getScreenshot() protocol action: Failed to decode response from marionette

  → Completed command: screenshot (false, [Function]) (89ms)
   Error: Failed to decode response from marionette
       at FSReqWrap.args [as oncomplete] (fs.js:140:20)
 Error saving screenshot...
   { status: -1,
     value:
      { error: 'unknown error',
        message: 'Failed to decode response from marionette',
        stacktrace: '' },
     errorStatus: '',
     error: 'Failed to decode response from marionette',
     httpStatusCode: 500 }
  → Completed command: saveScreenshot ('C:\CS6-LandingPage\screens\testFile\LogIn_FAILED_Feb-04-2020-143012-GMT+0100.png', [Function]) (98ms)

 → Running command: session ('delete', [Function])
   Request DELETE  /session/e0f0daf0-1b2a-4699-a713-79329fb27de4  
   Response 404 DELETE /session/e0f0daf0-1b2a-4699-a713-79329fb27de4 (1ms)
   { value:
      { error: 'invalid session id',
        message: 'Tried to run command without establishing a connection',
        stacktrace: '' } }
 Error while running .sessionAction() protocol action: Tried to run command without establishing a connection

  → Completed command: end ([Function]) (116ms)
  → Completed command: session ('delete', [Function]) (5ms)
_________________________________________________

TEST FAILURE: 1 error during execution; 0 tests failed, 0 passed (14.169s)

 × testFile
 – LogIn (11.621s)

  TimeoutError: An error occurred while running .moveToElement() command on <#nav_bar .current>: undefined; undefined
   {"status":-1,"value":"HTTP method not allowed","errorStatus":-1,"error":"An unknown error has occurred.","httpStatusCode":405}
       at process._tickCallback (internal/process/next_tick.js:68:7)

```

## NOTE:
- it works on google chrome
- I use Nightwatch nodejs framework for E2E tests

**Comment by whimboo** [comment] 2020-02-04 15:10
This is not a valid command. It makes it a dupe of issue #1622.

**Closed by whimboo** 2020-02-04 15:10 UTC

**Comment by Pieras2** [comment] 2020-02-04 20:52
Thank you, seems I didn't struggled myself enough to find it 🙄

**Comment by Pieras2** [comment] 2020-02-05 18:12
@whimboo why are saying that moveTo is invalid command ??

https://webdriver.io/docs/api/element/moveTo.html

**Comment by whimboo** [comment] 2020-02-07 12:41
Geckodriver implements the [WebDriver specification](https://w3c.github.io/webdriver/) which you shouldn't confound with what the webdriver.io framework does. Maybe there is special code in this framework which causes the test to fail when run with geckodriver/Firefox. 

Feel free to attach a [trace log](https://firefox-source-docs.mozilla.org/testing/geckodriver/TraceLogs.html) to this issue, and I can have another look, but IMO you better file an issue for webdriver.io.

**Comment by Pieras2** [comment] 2020-02-07 12:44
Request POST  /session/e0f0daf0-1b2a-4699-a713-79329fb27de4/moveto  
  { element: 'd117dcf1-dc73-41f2-9b2a-6d9f25c9fa47',
    xoffset: 143.5,
    yoffset: 18 }
  Response 405 POST /session/e0f0daf0-1b2a-4699-a713-79329fb27de4/moveto (2ms)
  { status: -1, value: 'HTTP method not allowed' }

The frameWork uses "moveTo" command with json object carrying coordinates of window.
Honestly speaking ... I understand that geckodriver is not the same as chromedriver but removing this option makes job more difficulties to many people that use E2E frameworks where support requires both browsers (chrome, firefox)

**Comment by whimboo** [comment] 2020-02-07 14:15
This is not a trace level log! Please read the document carefully. Instead this is just the log from webdriver.io.

Also if chromedriver supports `moveTo()` it wouldn't be standard compliant. Our implementation is purely based on the WebDriver specification. Positioning and resizing of the window can be done via https://w3c.github.io/webdriver/#set-window-rect. I assume webdriver.io only adds a wrapper for that.
