### ISSUE TITLE
Copyright notice for geckodriver 0.26.0 

### ISSUE THREAD

**Issue by nagik** [mozilla/geckodriver#1713] opened 2020-04-25 04:57 UTC
This is in continuation to the earlier issue that I had raised - #1710

I’m specifically looking for a copyright notice for geckodriver.  I understand that the license terms are same as Mozilla Public License, but I would like get a copyright notice that is specific to geckodriver.  Please point me to the copyright notice that applies to geckodriver.

**Comment by whimboo** [comment] 2020-04-27 18:31
Please don't start new issues but continue our discussion on the mailing list. It doesn't make much sense to have it on several places. Thanks. Marking as dupe of issue #1710.

**Closed by whimboo** 2020-04-27 18:31 UTC

**Comment by nagik** [comment] 2020-04-28 09:36
Ok, i assumed the issue was closed, hence opened a new thread.  I'll go back to the old one.
