### ISSUE TITLE
Problem with changing browser window size

### ISSUE THREAD

**Issue by mariankral** [mozilla/geckodriver#984] opened 2017-10-02 06:14 UTC
gecko v 0.18
FF v 55.0.3 32-bit
Windows 10
WebDriver v 3.5.1

I use one instance of the browser. When I run multiple tests, during the first test the browser window is maximized. At the start of the second test, the browser window size changes to the default size. At the start of the third test, the window is maximized and at the start of the fourth test, window size changes to the default size...etc.

This occurred when using the latest version of WebDriver - GeckoDriver 0.18.0. With previous version of WebDriver, the browser window size has remained maximized during all tests.
And I use the latest version of web browser Firefox 55.0.3.
With browser Chrome or IE it works well.

All test scripts contains driver.Manage().Window.Maximize();

Any idea why this is happening?
And how to fix it?

**Comment by andreastt** [comment] 2017-10-02 12:51
Previously the _Maximize Window_ command was not idempotent, meaning it would put the browser window into maximised state on the first invocation and bring it back to the normal window state (restoring it) a the second call.

This was fixed in a more recent Firefox version, so as it says in the README, I would encourage you to use Firefox Nightly when using geckodriver. It is still pre-release software.

**Closed by andreastt** 2017-10-02 12:51 UTC

**Comment by whimboo** [comment] 2017-10-02 15:36
Well, the current 57.0 beta should be still fine in handling that. Not everyone can/wants to use Nightly.

**Comment by warpech** [comment] 2017-10-16 09:30
For own reference: looks like duplicate of https://github.com/mozilla/geckodriver/issues/900
