### ISSUE TITLE
Selenium webdriver.Firefox() selenium.common.exceptions.WebDriverException: Message: Process unexpectedly closed with status: 1

### ISSUE THREAD

**Issue by nobism** [mozilla/geckodriver#1163] opened 2018-02-07 03:45 UTC
I originally created this issue in Selenium but was directed to come here.

## Meta -
Platform: Raspberry Pi 3
OS:  Ubuntu 16.04 Classic Server
Selenium Version: 3.9.0
Geckodriver: 19.0.1 ARM7hf
Browser:  Firefox 58.0.1
Language: Python 3.5.2

## Expected Behavior -
Expect no exception.

## Actual Behavior -
Exception raised:

> Traceback (most recent call last):
>   File "<stdin>", line 1, in <module>
>   File "/home/martin/.local/lib/python3.5/site-packages/selenium/webdriver/firefox/webdriver.py", line 162, in __init__
>     keep_alive=True)
>   File "/home/martin/.local/lib/python3.5/site-packages/selenium/webdriver/remote/webdriver.py", line 154, in __init__
>     self.start_session(desired_capabilities, browser_profile)
>   File "/home/martin/.local/lib/python3.5/site-packages/selenium/webdriver/remote/webdriver.py", line 243, in start_session
>     response = self.execute(Command.NEW_SESSION, parameters)
>   File "/home/martin/.local/lib/python3.5/site-packages/selenium/webdriver/remote/webdriver.py", line 312, in execute
>     self.error_handler.check_response(response)
>   File "/home/martin/.local/lib/python3.5/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
>     raise exception_class(message, screen, stacktrace)
> selenium.common.exceptions.WebDriverException: Message: Process unexpectedly closed with status: 1

geckodriver.log 

> 1517973993086	geckodriver	INFO	geckodriver 0.19.1
> 1517973993130	geckodriver	INFO	Listening on 127.0.0.1:33938
> 1517973994816	mozrunner::runner	INFO	Running command: "/usr/bin/firefox" "-marionette" "-profile" "/tmp/rust_mozprofile.5EcLbXHxWGet"
> ExceptionHandler::GenerateDump cloned child ExceptionHandler::WaitForContinueSignal waiting for continue signal...
> 16639
> ExceptionHandler::SendContinueSignalToChild sent continue signal to child

geckodriver.log (from Jenkins test, see below)

> 1517973683203	geckodriver	INFO	geckodriver 0.19.1
> 1517973683224	geckodriver	INFO	Listening on 127.0.0.1:44639
> 1517973686092	mozrunner::runner	INFO	Running command: "/usr/bin/firefox" "-marionette" "-profile" "/tmp/rust_mozprofile.U9bo7S9WVbVv"
> ExceptionHandler::GenerateDump cloned child 16387
> ExceptionHandler::WaitForContinueSignal waiting for continue signal...
> ExceptionHandler::SendContinueSignalToChild sent continue signal to child
> 1517973692009	geckodriver	INFO	geckodriver 0.19.1
> 1517973692030	geckodriver	INFO	Listening on 127.0.0.1:51052
> 1517973693698	mozrunner::runner	INFO	Running command: "/usr/bin/firefox" "-marionette" "-profile" "/tmp/rust_mozprofile.fYJ8OWbQXcXg"
> ExceptionHandler::GenerateDump cloned child 16427
> ExceptionHandler::WaitForContinueSignal waiting for continue signal...
> ExceptionHandler::SendContinueSignalToChild sent continue signal to child
> 1517973697889	geckodriver	INFO	geckodriver 0.19.1
> 1517973697930	geckodriver	INFO	Listening on 127.0.0.1:51720
> 1517973699621	mozrunner::runner	INFO	Running command: "/usr/bin/firefox" "-marionette" "-profile" "/tmp/rust_mozprofile.ChmQVltqdxxx"
> ExceptionHandler::GenerateDump cloned child ExceptionHandler::WaitForContinueSignal waiting for continue signal...
> 16466
> ExceptionHandler::SendContinueSignalToChild sent continue signal to child
> 

## Steps to reproduce -
```
$ python3
>>> from selenium import webdriver
>>> webdriver.Firefox()
```

## My actual problem -
Above is the simplest way that I've been able to reproduce the issue. But I've actually been trying to run tests using Jenkins on my Raspberry Pi 3, and I get the same error when `webdriver.Firefox()` is called. The setup on Jenkins is the same, except for `xvfb` is being used with the old `export DISPLAY=:99` trick (which doesn't work for me). I've also tried to use `pyvirtualdisplay` with no luck (same exception as above):

```
$ python3
>>> from selenium import webdriver
>>> from pyvirtualdisplay import Display
>>> display = Display(visible=0, size=(1366, 768))
>>> display.start()
>>> webdriver.Firefox()
```

I've tried *many* different versions of Selenium, geckodriver (even compiled ARM6hf versions) and Firefox with no luck.

I have had some success though, earlier I had Raspbian Stretch Lite (Nov 2017) on my Raspberry Pi 3 and my tests were working fine on Jenkins using Geckodriver 15.0, Firefox-sre 52.6 and Selenium 3.4.1. I'll fall back to this setup if this issue can't be resolved.

**Comment by andreastt** [comment] 2018-02-07 11:16
It looks to me like Firefox is crashing here and debugging that problem with the multitude of layers geckodriver and Selenium adds isn’t easy. Are you able to run Firefox successfully separately?

**Comment by nobism** [comment] 2018-02-07 11:52
Oops, I think I just pooped my OS installation by swapping the SD card with a different one. I'll reinstall it and get back to you..

**Comment by nobism** [comment] 2018-02-08 10:06
I get this when running `firefox` after `export DISPLAY=:0`:

> Failed to connect to Mir: Failed to connect to server socket: No such file or directory
> Unable to init server: Could not connect: Connection refused
> Error: cannot open display: :0

**Comment by whimboo** [comment] 2018-02-08 10:12
You want `DISPLAY=:99 firefox`, right?

**Comment by nobism** [comment] 2018-02-08 10:15
@whimboo Thanks for the reply, same error.

**Comment by cgoldberg** [comment] 2018-02-08 16:30
> Geckodriver: 19.0.1 ARM7hf

doesn't the Pi3 use ARMv8?

**Comment by whimboo** [comment] 2018-02-12 09:35
`-screenshot` internally uses `-headless`. Is GTK installed on a Pi3? See https://bugzilla.mozilla.org/show_bug.cgi?id=1372998 for details.

**Comment by AutomatedTester** [comment] 2018-02-28 11:24
Duplicate of #1172

**Comment by whimboo** [comment] 2018-03-06 08:16
I don't see that this is a dupe of issue #1172. It has the same outcome but not the same underlying issue. 

@nobism, can you please give a reply to my last question which I raised 22 days ago? Thanks.

**Comment by andreastt** [comment] 2018-03-28 14:01
Closing for inactivity.

**Closed by andreastt** 2018-03-28 14:01 UTC
Labels: waiting for reporter feedback

**Comment by vitovalov** [comment] 2018-08-10 14:35
Any solution found since March?

**Comment by whimboo** [comment] 2018-08-10 18:56
@vitovalov, solution for what? If you have a problem please file a new issue and provide ALL the requested details. Only then we are able to help. Thanks.
