### ISSUE TITLE
geckodriver     ERROR   An attempt was made to access a socket in a way forbidden by its access permissions. 

### ISSUE THREAD

**Issue by flik** [mozilla/geckodriver#1208] opened 2018-03-11 09:11 UTC
## System

* Version: geckodriver-v0.19.1-win64
* Platform: windows 8.1
* Firefox: 56.0
* Selenium: selenium-server-standalone-3.3.0

## Testcase
$ ./geckodriver.exe
1520755700829   geckodriver     INFO    geckodriver 0.19.1
1520755700838   geckodriver     ERROR   An attempt was made to access a socket i                       n a way forbidden by its access permissions. (os error 10013)

## Stacktrace

$ ./geckodriver.exe
1520755700829   geckodriver     INFO    geckodriver 0.19.1
1520755700838   geckodriver     ERROR   An attempt was made to access a socket i                       n a way forbidden by its access permissions. (os error 10013)

## Trace-level log
$ ./geckodriver.exe
1520755700829   geckodriver     INFO    geckodriver 0.19.1
1520755700838   geckodriver     ERROR   An attempt was made to access a socket i                       n a way forbidden by its access permissions. (os error 10013)

**Comment by flik** [comment] 2018-03-11 09:13
My os was 64bit and browser firefox installed 32.
I was running 64bit driver version. 
Then I download 32bit version and fixed. 
Now, issue fixed.

**Comment by andreastt** [comment] 2018-03-11 15:01
The bitness of Firefox has nothing to do with the fact that geckodriver fails to bind to a port. My guess would be that you have a firewall running on the system that prevents geckodriver.exe from binding to port 4444?

**Comment by hazmeister** [comment] 2018-03-13 10:59
Do you have Selenium Grid running on port 4444 on the same machine?

**Comment by whimboo** [comment] 2018-03-13 13:08
Dupe of issue #550.

**Closed by whimboo** 2018-03-13 13:08 UTC
Labels: waiting for reporter feedback
