### ISSUE TITLE
Unable to run Firefox in headless mode on Linux when GTK3 is not available

### ISSUE THREAD

**Issue by nddipiazza** [mozilla/geckodriver#1037] opened 2017-11-01 14:38 UTC
## System
* Version: 1.0.18+
* Platform: All Linux
* Firefox: 56+
* Selenium: 3.x+

## Testcase

Attempt to run selenium using the headless firefox with an operating system without GTK3.

Expected: Error should be readable and tell developer that GTK3 is not available.

Actual: Undecipherable back trace. 

## Stacktrace

```
stack backtrace:
   0:           0x5787ed - backtrace::backtrace::trace::h59229d13f6a8837d
   1:           0x578942 - backtrace::capture::Backtrace::new::h23089c033eded8f0
   2:           0x4463cc - webdriver::error::WebDriverError::new::hd11f864b1fdf4510
   3:           0x450591 - geckodriver::marionette::MarionetteHandler::create_connection::h6f7058fccafe4367
   4:           0x425c32 - <webdriver::server::Dispatcher<T, U>>::run::h8f5348b8f5f7c053
   5:           0x40b22c - std::panicking::try::do_call::hb67c6fb6bcd96195
   6:           0x5dc20a - panic_unwind::__rust_maybe_catch_panic
                        at /checkout/src/libpanic_unwind/lib.rs:98
   7:           0x41b943 - <F as alloc::boxed::FnBox<A>>::call_box::h4100941edc372034
   8:           0x5d48a4 - alloc::boxed::{{impl}}::call_once<(),()>
                        at /checkout/src/liballoc/boxed.rs:650
                         - std::sys_common::thread::start_thread
                        at /checkout/src/libstd/sys_common/thread.rs:21
                         - std::sys::imp::thread::{{impl}}::new::thread_start
                        at /checkout/src/libstd/sys/unix/thread.rs:84"
```

**Comment by andreastt** [comment] 2017-11-01 14:52
The backtrace you see here is not relevant to the cause of the problem you’re seeing. It is attached to every error that geckodriver returns. We have remedied this in https://bugzilla.mozilla.org/show_bug.cgi?id=1413292 to not cause confusion, so it will be gone with the 0.20.0 release.

It’s not immediately clear to me why GTK3 is required for running Firefox in headless mode. One should think it was not. Can you describe the steps for reproducing this problem? We will also need a trace-level log.

**Comment by nddipiazza** [comment] 2017-11-01 19:02
1) Extract a firefox tar.gz of v56+ to some `/home/your/path/firefox`
2) Run this

```
docker run -it -v /home/your/path/firefox:/root/firefox --name ffx java:openjdk-8
/root/firefox/firefox
```

*Expected*: `*** You are running in headless mode.`
*Actual*: 

```
XPCOMGlueLoad error for file /root/firefox/libmozgtk.so:
libgtk-3.so.0: cannot open shared object file: No such file or directory
Couldn't load XPCOM.
```

**Comment by whimboo** [comment] 2017-11-01 20:06
@nddipiazza this is great info. Given that this is not a geckodriver issue, would you mind filing this as a bug in the following component? It's something devs have to take a look at.

https://bugzilla.mozilla.org/enter_bug.cgi?product=Firefox&component=Headless

Thanks a lot! And also please let us know about the bug number.

**Comment by andreastt** [comment] 2017-11-01 20:18
I’m not sure it’s possible to unlink libgtk3 from the firefox binary. I think the only thing we can do on the geckodriver side is to improve the error message when it exits immediately/is not able to start.

**Comment by nddipiazza** [comment] 2017-11-01 21:42
@whimboo https://bugzilla.mozilla.org/show_bug.cgi?id=1413704

we should look into documenting how to get at the trace logs when using headless mode in selenium.

**Comment by andreastt** [comment] 2017-11-01 21:43
@nddipiazza https://searchfox.org/mozilla-central/source/testing/geckodriver/doc/TraceLogs.md

**Comment by nddipiazza** [comment] 2017-11-01 21:46
omg i didn't read down far enough lol. thanks

**Comment by whimboo** [comment] 2017-11-02 07:24
Ok, so the problem was already known as I can see now. As result we have to wait for bug 1372998 to be fixed now. As you can see it has lower priority, also given the amount of work to do, and that it is really a corner case. For the time being you might have to install GTK+ libraries to get it working.

I will close this issue now given that it is a known bug in Firefox.

**Closed by whimboo** 2017-11-02 07:24 UTC
Labels: firefox, waiting for reporter feedback

**Comment by josephecombs** [comment] 2017-12-12 10:21
I am having this issure right and I view it as a major major problem. I am having this exact issue:

-trying to run headless firefox with selenium 
-on Amazon Linux 
-which apparently is derived from CentOS 6
-which apparently does not have libgtk-3.so.0 on it and is very difficult to install

**Comment by whimboo** [comment] 2017-12-14 09:53
@josephecombs it's nothing we can do for geckodriver. The bug has to be fixed by developers working on the headless mode. So as best CC yourself on https://bugzilla.mozilla.org/show_bug.cgi?id=1372998, and wait for updates.
