### ISSUE TITLE
Geckodriver  can't start Firefox 122 on Mac

### ISSUE THREAD

**Issue by mayank6147** [mozilla/geckodriver#2161] opened 2024-02-16 13:42 UTC
## System

* Version: 0.34.0
* Platform: macOS
* Mac Os arch: aarch64
* Firefox: 122.0.1 (64-bit)
*  Java : 17.0.9
* Selenium: 3.141.59

## Testcase
i am just trying to opens www.google.com using the Firefox browser with geckodriver Below is an example : - 
public static void main(String[] args) {
        // Set the path to the geckodriver executable
        System.setProperty("webdriver.gecko.driver", "path/to/geckodriver");

        // Create FirefoxOptions to configure the FirefoxDriver
        FirefoxOptions options = new FirefoxOptions();

        // Optional: You can add additional configurations to the FirefoxOptions if needed

        // Create an instance of the FirefoxDriver with the specified options
        WebDriver driver = new FirefoxDriver(options);

        // Open Google.com
        driver.get("https://www.google.com");

        // Optional: You can perform additional actions on the page if needed

        // Close the browser
        driver.quit();
    } 

## Stacktrace

remote stacktrace: org.openqa.selenium.WebDriverException: Process unexpectedly closed with status signal

remote stacktrace:

 
 at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)

 

 at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77)	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77)

 

 at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)

 

 at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)

 

 at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:480)	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:480)

 

 at org.openqa.selenium.remote.W3CHandshakeResponse.lambda$errorHandler$0(W3CHandshakeResponse.java:62)	at org.openqa.selenium.remote.W3CHandshakeResponse.lambda$errorHandler$0(W3CHandshakeResponse.java:62)
 

 at org.openqa.selenium.remote.HandshakeResponse.lambda$getResponseFunction$0(HandshakeResponse.java:30)	at org.openqa.selenium.remote.HandshakeResponse.lambda$getResponseFunction$0(HandshakeResponse.java:30)

 

 at org.openqa.selenium.remote.ProtocolHandshake.lambda$createSession$0(ProtocolHandshake.java:126)	at org.openqa.selenium.remote.ProtocolHandshake.lambda$createSession$0(ProtocolHandshake.java:126)

 at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)

 
 at java.base/java.util.Spliterators$ArraySpliterator.tryAdvance(Spliterators.java:1002)	at java.base/java.util.Spliterators$ArraySpliterator.tryAdvance(Spliterators.java:1002)

 

 at java.base/java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:129)	at java.base/java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:129)

 

 at java.base/java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:527)	at java.base/java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:527)

 

 at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:513)	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:513)

 

 at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)

 
 at java.base/java.util.stream.FindOps$FindOp.evaluateSequential(FindOps.java:150)	at java.base/java.util.stream.FindOps$FindOp.evaluateSequential(FindOps.java:150)

 

 at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)

 

 at java.base/java.util.stream.ReferencePipeline.findFirst(ReferencePipeline.java:647)	at java.base/java.util.stream.ReferencePipeline.findFirst(ReferencePipeline.java:647)

 

 at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:128)	at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:128)

 at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:74)	at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:74)

 

 at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:136)	at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:136)

 

 at org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:83)	at org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:83)

 

 at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:552)	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:552)

 

 at com.crestech.opkey.plugin.webdriver.b.b.execute(OpKeyFirefoxDriver.java:61)	at com.crestech.opkey.plugin.webdriver.b.b.execute(OpKeyFirefoxDriver.java:61)

 

 at org.openqa.selenium.remote.RemoteWebDriver.startSession(RemoteWebDriver.java:213)	at org.openqa.selenium.remote.RemoteWebDriver.startSession(RemoteWebDriver.java:213)
 

 at com.crestech.opkey.plugin.webdriver.b.b.startSession(OpKeyFirefoxDriver.java:379)	at com.crestech.opkey.plugin.webdriver.b.b.startSession(OpKeyFirefoxDriver.java:379)

 at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:131)	at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:131)

 at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:147)	at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:147)

**Comment by thc202** [comment] 2024-02-16 13:46
You should use a newer version of Selenium (or specify the binary yourself), see also #2144.

**Comment by whimboo** [comment] 2024-02-19 08:57
Closing as duplicate of #2144.

**Closed by whimboo** 2024-02-19 08:57 UTC
