### ISSUE TITLE
driver.quit() doesn't work as expected

### ISSUE THREAD

**Issue by robinsmathewgit** [mozilla/geckodriver#499] opened 2017-02-28 10:55 UTC
I am facing issue when doing driver.quit() using GeckoDriver

Browser : **Firefox Nightly 54.0, Firefox 51.0**
Selenium : **3.1.0**
GeckoDriver : **geckodriver-v0.14.0-win64**

**GeckoDriver is happy with most of the websites but it is crashing for some main websites.**

Website Crashing
--------------------
http://www.cnn.com/
http://www.dailymail.co.uk/
https://www.bet365.com/
http://www.foxnews.com/
http://abcnews.go.com/

Most of the other site I have checked worked without any problem

When driver.quit() is called it will show the message **"Plugin container for Nightly stopped working"** 

Here is the message displayed in Firefox popup (For all the above websites its the same)
----------------------------------------------------------------------

Problem signature:
  Problem Event Name:	    **APPCRASH**
  Application Name:	    plugin-container.exe
  Application Version:	    54.0.0.6264
  Application Timestamp:    58b02aac
  Fault Module Name:	    **xul.dll**
  Fault Module Version:	    54.0.0.6264
  Fault Module Timestamp: 58b029ef
  Exception Code:	            80000003
  Exception Offset:	            008cb329
  OS Version:	                    6.1.7601.2.1.0.256.4
  Locale ID:	                    2057
  Additional Information 1:  0a9e
  Additional Information 2: 0a9e372d3b4ad19135b953a78882e789
  Additional Information 3: 0a9e
  Additional Information 4: 0a9e372d3b4ad19135b953a78882e789

Read our privacy statement online:
  http://go.microsoft.com/fwlink/?linkid=104288&clcid=0x0409

If the online privacy statement is not available, please read our privacy statement offline:
  C:\windows\system32\en-US\erofflps.txt

I am sharing the code I have used. This issue is consistent for any of the above websites.

Code
------
package CrossBrowser.Tests.POC;

import java.net.URL;

import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.firefox.FirefoxProfile;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.testng.annotations.Test;

public class GeckoDriverIssue {

	WebDriver driver;

	@Test(description = "Launch Website")
	public void geckoDriverIssue() {		

		try {
			FirefoxProfile fp = new FirefoxProfile();
			DesiredCapabilities firefoxCapabilities = DesiredCapabilities.firefox();
			firefoxCapabilities.setCapability(FirefoxDriver.PROFILE, fp);
			firefoxCapabilities.setCapability("marionette", true);
			driver = new RemoteWebDriver(new URL("http://localhost:4444/wd/hub"), firefoxCapabilities);

			String webSite = "http://www.cbsnews.com/";
			driver.get(webSite);

		} catch (Exception e) {	}
		
		finally {
			driver.quit();	
		}

	}
}

Thanks,
Robins

**Comment by andreastt** [comment] 2017-03-01 09:41
Suspect this is a duplicate of https://github.com/mozilla/geckodriver/issues/494.

**Closed by andreastt** 2017-03-01 09:41 UTC
