### ISSUE TITLE
Firefox memory leak

### ISSUE THREAD

**Issue by tsoernes** [mozilla/geckodriver#1561] opened 2019-05-28 10:18 UTC
## System

Using GeckoDriver version: 0.24.0
Mozilla Firefox 67.0
Linux Fedora 29 kernel 5.0.16
Python 3.7, Selenium 3.141.0

## Testcase
Fetching 100 pages, copying a small piece of text from each (less than 1 meg total for all 100 pages) results in, eventually, 6 GB of RAM usage by the firefox process. The driver is only initialized once.

https://gist.github.com/tsoernes/14a6b53fa59bdf6df0770860d332ea62

## Trace-level log

[geckodriverlog3.txt](https://github.com/mozilla/geckodriver/files/3227049/geckodriverlog3.txt)

**Comment by andreastt** [comment] 2019-05-28 10:20
Likely a duplicate of https://github.com/mozilla/geckodriver/issues/181.

**Closed by andreastt** 2019-05-28 10:20 UTC
