### ISSUE TITLE
Cant find the link text if there is &nbsp non-block space in the html source code

### ISSUE THREAD

**Issue by adam-zjy** [mozilla/geckodriver#978] opened 2017-09-28 06:06 UTC
## System
* Version: 0.19.0
* Platform: Windows / MacOS
* Firefox: 55
* Selenium: 3.5.3

## Testcase

Souce Code

-     <a href="dummyLink">Self&nbsp;-&nbsp;Charles Grant</a>

Java Code
List<WebElement> webElementList = this.getWebDriver().findElements(new By.ByLinkText("Self - Charles Grant"));

Expected: Value returned from the web
Actually: No result returned

**Comment by whimboo** [comment] 2017-09-28 19:36
Please provide a trace level log as requested when filing the issue. Further please try to add an id for this element, find it that way and retrieve the element text. I'm fairly sure this is a problem because `&nbsp` is not equal to `%20` (which is space).

**Comment by adam-zjy** [comment] 2017-09-29 01:15
hi Whimboo,

Thanks for taking into process.

I'm not sure what kind of trace log you want, is that the one printed in the console logs like that?

1506646405012	Marionette	DEBUG	Received DOM event "beforeunload" for "http://dc13qaautocandcfapp01.lab.od.sap.biz:8080/sf/pmreviews?bplte_company=datPLT12&_s.crb=5zE%2bnaBI6y4hA%2bmTq11CzDFKSVI%3d"
1506646406942	Marionette	DEBUG	Received DOM event "pagehide" for "http://dc13qaautocandcfapp01.lab.od.sap.biz:8080/sf/pmreviews?bplte_company=datPLT12&_s.crb=5zE%2bnaBI6y4hA%2bmTq11CzDFKSVI%3d"
1506646406953	Marionette	DEBUG	Received DOM event "unload" for "http://dc13qaautocandcfapp01.lab.od.sap.biz:8080/sf/pmreviews?bplte_company=datPLT12&_s.crb=5zE%2bnaBI6y4hA%2bmTq11CzDFKSVI%3d"
1506646413118	Marionette	DEBUG	Received DOM event "DOMContentLoaded" for "http://dc13qaautocandcfapp01.lab.od.sap.biz:8080/acme?_s.crb=5zE%252bnaBI6y4hA%252bmTq11CzDFKSVI%253d#focus"
1506646415104	Marionette	DEBUG	Received DOM event "pageshow" for "http://dc13qaautocandcfapp01.lab.od.sap.biz:8080/acme?_s.crb=5zE%252bnaBI6y4hA%252bmTq11CzDFKSVI%253d#focus"
2017-09-29 08:53:35,227 INFO  [main] - New page successfully loaded in 2s!  Current URL is:http://dc13qaautocandcfapp01.lab.od.sap.biz:8080/acme?_s.crb=5zE%252bnaBI6y4hA%252bmTq11CzDFKSVI%253d#focus
2017-09-29 08:53:35,259 INFO  [Thread-9] - Cache Hook is not enabled yet!
1506646415706	Marionette	DEBUG	Received DOM event "beforeunload" for "http://dc13qaautocandcfapp01.lab.od.sap.biz:8080/acme?_s.crb=5zE%252bnaBI6y4hA%252bmTq11CzDFKSVI%253d#focus"
1506646416754	Marionette	DEBUG	Received DOM event "pagehide" for "http://dc13qaautocandcfapp01.lab.od.sap.biz:8080/acme?_s.crb=5zE%252bnaBI6y4hA%252bmTq11CzDFKSVI%253d#focus"
1506646416762	Marionette	DEBUG	Received DOM event "unload" for "http://dc13qaautocandcfapp01.lab.od.sap.biz:8080/acme?_s.crb=5zE%252bnaBI6y4hA%252bmTq11CzDFKSVI%253d#focus"
1506646424043	Marionette	DEBUG	Received DOM event "DOMContentLoaded" for "http://dc13qaautocandcfapp01.lab.od.sap.biz:8080/acme?bplte_company=datPLT12&fbacme_o=my_forms&myf%5fos=inbox&myf%5fss=&myf%5fmode=&inbox%5fos=create&fbnd_pm_fmid=588&fbnd_pm_subpge=fbnd%5fval%5fsubj&inbox_fbfl_ftype=Review&_s.crb=5zE%2bnaBI6y4hA%2bmTq11CzDFKSVI%3d"
1506646427440	Marionette	DEBUG	Received DOM event "pageshow" for "http://dc13qaautocandcfapp01.lab.od.sap.biz:8080/acme?bplte_company=datPLT12&fbacme_o=my_forms&myf%5fos=inbox&myf%5fss=&myf%5fmode=&inbox%5fos=create&fbnd_pm_fmid=588&fbnd_pm_subpge=fbnd%5fval%5fsubj&inbox_fbfl_ftype=Review&_s.crb=5zE%2bnaBI6y4hA%2bmTq11CzDFKSVI%3d"
2017-09-29 08:53:47,584 INFO  [main] - New page successfully loaded in 2s!  Current URL is:http://dc13qaautocandcfapp01.lab.od.sap.biz:8080/acme?bplte_company=datPLT12&fbacme_o=my_forms&myf%5fos=inbox&myf%5fss=&myf%5fmode=&inbox%5fos=create&fbnd_pm_fmid=588&fbnd_pm_subpge=fbnd%5fval%5fsubj&inbox_fbfl_ftype=Review&_s.crb=5zE%2bnaBI6y4hA%2bmTq11CzDFKSVI%3d
2017-09-29 08:53:47,610 INFO  [Thread-10] - Cache Hook is not enabled yet!
1506646589090	DeferredSave.extensions.json	DEBUG	Save changes
1506646589093	DeferredSave.extensions.json	DEBUG	Starting timer
1506646589119	DeferredSave.extensions.json	DEBUG	Starting write
1506646589154	DeferredSave.extensions.json	DEBUG	Write succeeded

And also there is no id for my webelement, please see the attached screenshot
![image](https://user-images.githubusercontent.com/16423729/30996891-ac7e870a-a4f6-11e7-88e6-b5fa4eaaa79e.png)

Thanks,
Adam

**Comment by whimboo** [comment] 2017-09-29 07:29
So I checked that myself and figured out that it is actually a dupe of issue #802.

**Closed by whimboo** 2017-09-29 07:29 UTC
