### ISSUE TITLE
FF 57 and deleting cookies - Geckodriver:Capybara:Selenium-Webdriver

### ISSUE THREAD

**Issue by lefty1975** [mozilla/geckodriver#1080] opened 2017-11-29 00:30 UTC
## System
* Version: geckodriver 0.19.1
* Platform: macOS
* Firefox: 57
* Selenium: selenium-webdriver (3.7.0)
* Capybara: (2.16.1)
* Cucumber: (3.0.2)

I have recently upgraded to Firefox version 57 to run our end to end UI automation scripts. However, this revamp of firefox seems to not be receiving this Capybara command `@browser.manage.delete_all_cookies` documentation: https://github.com/teamcapybara/capybara/blob/master/lib/capybara/selenium/driver.rb#L119 
This is causing me issues when I run my scenarios concurrently because my cookies are not being deleted, which is keeping my sessions in a logged in state, thus making all of my additional scenarios to fail because I cannot log in with a different user.

I am posting this issue here because I'm hoping that Geckodriver will have a newer version in the next few days to accommodate the overhaul of the latest Firefox version. And once a new version of Geckodriver is out, then my issue will be addressed.

This is not causing my issues when using Chrome with Chromedriver or FF version 55 with the aforementioned Geckodriver version.

**Comment by andreastt** [comment] 2017-11-29 14:06
Could you please attach a [trace-level log] from geckodriver? Read more about reporting actionable bugs in our [contribution guidelines].

[trace-level log]: https://searchfox.org/mozilla-central/source/testing/geckodriver/doc/TraceLogs.md
[contribution guidelines]: https://searchfox.org/mozilla-central/source/testing/geckodriver/CONTRIBUTING.md#reporting-bugs

**Comment by lefty1975** [comment] 2017-11-29 23:13
I don't know if I'm providing the correct information.
[tracelog.pdf](https://github.com/mozilla/geckodriver/files/1515885/tracelog.pdf)

**Comment by lefty1975** [comment] 2017-12-04 19:02
Can the `waiting for reporter feedback` tag be removed from this issue, or is more information required in addition to the trace log?

**Comment by lefty1975** [comment] 2017-12-13 16:39
It feels like marionette is not properly handling clearing window.localstorage information received from Gecko driver. Is there any way I can provide information (trace.log) to substantiate my claims?

**Comment by twalpole** [comment] 2017-12-13 18:38
@lefty1975 By default Capybara clears only cookies at reset, `localstorage` is separate from cookies.  I think you can close this issue.

**Comment by lefty1975** [comment] 2017-12-18 22:05
I'm reopening this ticket because local and session storage is being cleared, however, cookies are not being cleared which is causing my issue of cross-contamination between scenarios. I have manually tried executing `page.driver.browser.manage.delete_all_cookies` and it does not clear my cookies. I have provided a trace.log above. With that said, can someone guide me what additional information is needed so we can either eliminate Gecko/Marionette as the issue or determine if it is the issue of not clearing cookies.

**Comment by whimboo** [comment] 2017-12-23 14:33
@lefty1975 can you please try again with Firefox 58 (Beta) and/or Firefox 59 (Nightly)? You can get those builds via https://www.mozilla.org/en-US/firefox/channel/desktop/. Please let us know if one of those versions fixes it for you.

**Comment by lefty1975** [comment] 2017-12-26 16:43
@whimboo I will give those a try and report back.
Thanks!

**Comment by lefty1975** [comment] 2017-12-27 23:58
@whimboo Firefox Nightly 59.0a1 worked for me. I will try 58 in a bit.

**Comment by lefty1975** [comment] 2017-12-28 16:16
@whimboo still an issue in Firefox 58.0b12

**Comment by whimboo** [comment] 2018-01-03 19:05
There is nothing specific which we changed in Marionette for Firefox 59 for deleting all cookies. So maybe there was a Firefox bug which got fixed for 59.

Given that we cannot reproduce the problem due to missing tests I will close the issue now. And you will have to wait for Firefox 59, which will soon reach beta.

**Closed by whimboo** 2018-01-03 19:05 UTC
Labels: waiting for reporter feedback
