### ISSUE TITLE
v0.19.0 release missing win32 artifact

### ISSUE THREAD

**Issue by joshbruning** [mozilla/geckodriver#976] opened 2017-09-27 17:46 UTC
v0.19.0 release missing win32 artifact

https://github.com/mozilla/geckodriver/releases/tag/v0.19.0
Expected to see geckodriver-v0.19.0-win32.zip

Previous releases have artifacts like: geckodriver-v0.18.0-win32.zip
https://github.com/mozilla/geckodriver/releases

Plan to work around by building from source this time; however, would really appreciate getting win32 back in the official release process. Thanks!

**Comment by andreastt** [comment] 2017-09-27 17:54
Duplicate of https://github.com/mozilla/geckodriver/issues/951.

**Closed by andreastt** 2017-09-27 17:54 UTC
