### ISSUE TITLE
Selenium FirefoxDriver - WebElement.click() is getting hanged if window is closing on click using Geckodriver

### ISSUE THREAD

**Issue by saurabh-gaur** [mozilla/geckodriver#573] opened 2017-03-28 05:50 UTC
## Meta
Selenium 3.3.1
Firefox v52.0.1 (32-bit)
Geckodriver v0.15.0 (32-bit)
Java v1.8_121 (32-bit)

## Platform
Windows 10

## Steps to reproduce -
I have prepared two .html to reproduce this issue.

1. mainWindow.html

```
<title>Main Window</title>
<input type="submit" value ="Open Window" id="open" onclick="openWindow()">

<script>
function openWindow() 
{
 window.open("newWindow.html", "", "width=500,height=500");
}
```
2. newWindow.html
```
<title>New Window</title>
<input type="submit" value="Close Window" id="close" onclick="closeWindow()">

<script>
function closeWindow() 
{
 window.close();
}
</script>
```
**Selenium steps to reproduced :-**

```
System.setProperty("webdriver.gecko.driver", "geckodriverWin32-0.15.0.exe");

WebDriver driver = new FirefoxDriver();
driver.get("file:///mainWindow.html");
driver.manage().window().maximize();

driver.findElement(By.id("open")).click(); //This works fine

String curWindowHandle = driver.getWindowHandle();
Set<String> winHandles = driver.getWindowHandles();

for(String win : winHandles) {
    if (!curWindowHandle.toString().equals(win)) {
         driver.switchTo().window(win);
    }
}

driver.findElement(By.id("close")).click(); //This click is getting hanged
```

**Question :-** Why WebElement.click() is getting hanged in that case if click event is going to close current window in firefox using FirefoxDriver while it's working fine on chrome using ChromeDriver?

**Comment by Erezinho** [comment] 2017-03-30 20:01
Same thing hapoens to me as well.
Trying to invoke JS does not help.

My tests fail due to this behavior only on Firefox (chrome does not suffer from this).

Will be helpful to get a workaround until t will be fixed.

Thanks!!!

**Comment by saurabh-gaur** [comment] 2017-03-31 05:31
@Erezinho Yes, you are right. I have also tried to perform last `click` using `JavascriptExecutor` as -

`((JavascriptExecutor)driver).executeScript("arguments[0].click()", driver.findElement(By.id("close")));`

but it also not responded in firefox.

**Comment by andreastt** [comment] 2017-03-31 08:18
Duplicate of https://github.com/mozilla/geckodriver/issues/398.

**Closed by andreastt** 2017-03-31 08:18 UTC

**Comment by saurabh-gaur** [comment] 2017-03-31 10:58
@andreastt You have mentioned this is duplicate of #398 and closed, But you didn't provide any solution. I have also seen this #398, but also there is no solution.

So could please provide any workaround instead.

Thanks.

**Comment by andreastt** [comment] 2017-03-31 12:03
I don’t have a workaround. It is a bug.
