### ISSUE TITLE
Focusout event not firing when browser is not on focus

### ISSUE THREAD

**Issue by Lucasgermani** [mozilla/geckodriver#1170] opened 2018-02-09 19:19 UTC
When running a selenium test on firefox using geckodriver, if the browser it's not on focus, "focusout" javascript event is not fired.
Everything works fine if the browser is on focus.
This cause a severe impact on selenium grid test execution.

What i'm trying to do is calling:
zipcodeInput.sendKeys(Keys.TAB);
to fire this event and later make a validation on what that javascript block does, which is calling and api and fill other field with api return statements,

## System
* Version: 0.19.1
* Platform: Windows 10 PRO 
* Firefox: 58.0
* Selenium: Java - 3.8.1

## Testcase

`
got a simple input field 
\<input type="text" name="zip_code" id="zip_code" value="" autocomplete="off" aria-required="true" aria-invalid="false" class="valid"\>

<! -- with a focusout event attached on js -->
$('#zip_code').focusout(function () {
console.log("zip_code -->focusout --> event fired");
}
`

## Stacktrace

not related to error cause

## Trace-level log
Attachment.
* See after interactions with zip_code element
[complete.log](https://github.com/mozilla/geckodriver/files/1712141/complete.log)

**Comment by whimboo** [comment] 2018-02-12 10:33
Dupe of issue #906.

**Closed by whimboo** 2018-02-12 10:33 UTC
