### ISSUE TITLE
Geckodriver for linux 32 bits

### ISSUE THREAD

**Issue by aplicacionamedida** [mozilla/geckodriver#266] opened 2016-10-07 18:51 UTC
It's a pitty that it's not possible to use geckodriver for linux 32 bits.

is there some alternatives to use firefox driver in linux 32 bits?

**Comment by andreastt** [comment] 2016-10-10 09:36
Yes. Upgrade to a 64-bit OS.

Duplicate of https://github.com/mozilla/geckodriver/issues/237.

**Closed by andreastt** 2016-10-10 09:36 UTC
