### ISSUE TITLE
send_keys doesn't work for key combinations in geckodriver 0.19.1 + FF 57.0

### ISSUE THREAD

**Issue by FzmTYustas** [mozilla/geckodriver#1075] opened 2017-11-24 11:48 UTC
## System
* Version: 0.19.1
* Platform: Win7x64 SP1 Ent
* Firefox: 57.0
* Selenium: 3.7.0

## Testcase

```python
from selenium import webdriver
from selenium.webdriver.firefox.firefox_binary import FirefoxBinary
from selenium.webdriver.common.by import By
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.support import expected_conditions as ec
from selenium.webdriver.support.ui import WebDriverWait

binary = FirefoxBinary("C:\\Program Files\\Mozilla Firefox\\firefox.exe")
driver = webdriver.Firefox(firefox_binary=binary)

driver_wait = WebDriverWait(driver, 4)

el = driver_wait.until(ec.presence_of_element_located((By.TAG_NAME, 'body')))
el.send_keys(Keys.CONTROL + 't')
```

As a result, new tab is not opened.

**Comment by whimboo** [comment] 2017-11-27 16:55
You cannot use `Ctrl + T` to open a new tab, because this is a reserved shortcut and only accessible by Firefox chrome itself. Web content cannot use that. Please see issue #786 which this is a dupe of.

**Closed by whimboo** 2017-11-27 16:55 UTC

**Comment by sivask444** [comment] 2018-02-27 18:22
findETCElement("name", webLocatorString).sendKeys(Keys.chord(Keys.CONTROL, "a"),Keys.DELETE, inputValueAndQuery);

is not working with firefox 57, Version: 0.19.1.
could u tell me the solution for this one

**Comment by wangjunmei** [comment] 2018-03-23 06:44
action.sendKeys(Keys.chord(Keys.CONTROL, "a")).build().perform();
is not working with firefox 56\chrome 63\geckodriver 0.20  \chromedriver 2.36\selenium 3.8.1
Answer the answer

**Comment by FzmTYustas** [comment] 2018-03-23 14:16
Now I'm using smth like _execute_script("window.open();")_ in my tests and this works for me.

**Comment by tpangburn** [comment] 2018-08-01 20:47
So I had a script that I used cntl-'-' to zoom out of the window. Now after upgrading I find out it doesn't work anymore. I need it so so I can get my screen captures right size to fit the whole screen. How can I do this now if they don't allow control sequences?

**Comment by andreastt** [comment] 2018-08-01 20:52
Sending keys that affect chrome behaviour is explicitly intended not to work. WebDriver emulates user interactions with the _web platform_, not with the browser.

**Comment by tpangburn** [comment] 2018-08-01 21:13
OK I guess I don't understand what you mean to say here. I am looking for another way to zoom out of the current window if I can't use the control keys.

**Comment by tpangburn** [comment] 2018-08-01 21:24
There wouldn't be any browser preferences for instance I could set when I initialize etc?

**Comment by tpangburn** [comment] 2018-08-01 22:09
The reason I really need this control is because I use the scripts to take snapshots of things on a web UI and I want them for logging purposes. However the screen shots get chopped off if I don't have the screen size right.

**Comment by andreastt** [comment] 2018-08-01 23:25
In geckodriver you _can_ enter chrome context through the Set Context command to gain access to changing the zoom level, but this won’t be cross-browser compatible.

Zooming out to take a full-document screenshot seems very brittle due to the fact that many modern web apps loading more content as you scroll to edges (such as Twitter). Instead you can use the proprietary geckodriver API to take a full screenshot, or `firefox -headless -screenshot PATH`.

**Comment by tpangburn** [comment] 2018-08-02 20:17
OK I missed that you replied here as well, but I still not sure how to use the geckodriver API to do it in python. Not sure if I follow what you mean on the firefox -headless  option either an how I would put that into the python script or is that someplace else?

**Comment by tpangburn** [comment] 2018-08-02 22:16
Well I figured out what I was doing wrong to pass the headless to firefox. However It looks like it still cuts off the bottom a bit. I like to figure out how to do it with the API command if possible because I sort of like to see what's happening while it is running.

**Comment by whimboo** [comment] 2018-08-03 06:26
Ok, so here the example with the Python bindings of Selenium. Please note that other bindings might not have added support for `set_context()`!

```python
from selenium.webdriver.common.keys import Keys

driver = webdriver.Firefox(...)
driver.get("https://mozilla.org")
driver.set_context("chrome")
win = driver.find_element_by_tag_name("window")
win.send_keys(Keys.META + "-")
```

**Comment by tpangburn** [comment] 2018-08-07 19:19
Oh Ok I didn't understand what andreastt was trying to tell me. Having code example makes it much clearer. I not sure if this means I don't have the support for set_context then? I thought I installed selenium onto python, but maybe its not the right version.

driver.set_context("chrome")
AttributeError: 'WebDriver' object has no attribute 'set_context'

**Comment by tpangburn** [comment] 2018-08-07 21:31
well I got it to work but somehow its hanging up when I do a find by css later on that I can't figure out. It seems like if i do the find_element by tag command its screwing things up later on.

**Comment by tpangburn** [comment] 2018-08-08 21:25
Cool thanks that fixed it!!

**Comment by tpangburn** [comment] 2018-08-08 21:36
I guess if anyone knows how to still implement the proprietary geckodriver API to do the full screenshot let me know. It sounds like that would be the better long term solution. I not too worried about being web browser agnostic for my application.

**Comment by NetonD** [comment] 2019-02-22 04:41
> Ok, so here the example with the Python bindings of Selenium. Please note that other bindings might not have added support for `set_context()`!
> 
> ```python
> from selenium.webdriver.common.keys import Keys
> 
> driver = webdriver.Firefox(...)
> driver.get("https://mozilla.org")
> driver.set_context("chrome")
> win = driver.find_element_by_tag_name("window")
> win.send_keys(Keys.META + "-")
> ```

Not forgetting to go back to the content context later if necessary:
    `driver.set_context("content")`
