### ISSUE TITLE
selenium.common.exceptions.SessionNotCreatedException: Message: Unable to find a matching set of capabilities

### ISSUE THREAD

**Issue by Aravindha1234u** [mozilla/geckodriver#1762] opened 2020-08-18 07:12 UTC
## System

* Version: geckodriver 0.27.0
* Platform: Linux 5.7.0-kali1-amd64
* Firefox: 78.1.0esr (64-bit)
* Selenium: 3.141.0

## Testcase
solve.py
!#/usr/bin/python3
from selenium import webdriver
driver = webdriver.Firefox()

## Stacktrace

Traceback (most recent call last):
  File "solve.py", line 17, in <module>
    driver = webdriver.Firefox()
  File "/home/aravindha/.local/lib/python3.8/site-packages/selenium/webdriver/firefox/webdriver.py", line 170, in __init__
    RemoteWebDriver.__init__(
  File "/home/aravindha/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 157, in __init__
    self.start_session(capabilities, browser_profile)
  File "/home/aravindha/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 252, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "/home/aravindha/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/aravindha/.local/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.SessionNotCreatedException: Message: Unable to find a matching set of capabilities

## Trace-level log

tail geckodriver.log 
1597734653534	geckodriver	INFO	Listening on 127.0.0.1:34543

Help me out to solve this issues. I dont want to use webdriver by giving path to it because my teammate have different path i cant make changes in code.

**Comment by whimboo** [comment] 2020-08-18 08:41
Duplicate of issue #1756. You can use the signed nightly binary of geckodriver as posted on the other issue for the time being.

**Closed by whimboo** 2020-08-18 08:41 UTC
