### ISSUE TITLE
Screenshots of elements inside of Iframe are incorrect

### ISSUE THREAD

**Issue by rasikrodri** [mozilla/geckodriver#1666] opened 2019-12-09 19:04 UTC
## System

* Version: v0.26.0
* Platform: Windows 10
* Firefox: 70 and 71
* Selenium: Selenium.WebDriverBackedSelenium 3.13.1.0 for .Net

[geckodriver trace.txt](https://github.com/mozilla/geckodriver/files/3946626/geckodriver.trace.txt)

Screenshots of elements inside of Iframe are incorrect.
An area of the size of the element is captured but it is captured at x=0, y=0

**It seems that it gets the location of the element in the IFrame but takes the screenshot of that location as if it is on the webpage's main context instead of the iframe context.

Is supposed to capture the text area I circled with blue:
![image](https://user-images.githubusercontent.com/10351664/70465983-25cc9a00-1a90-11ea-95c2-9f42f5561eef.png)

But it captures this:
![image](https://user-images.githubusercontent.com/10351664/70466061-5280b180-1a90-11ea-9ffa-559b52c79e28.png)

**Comment by whimboo** [comment] 2019-12-09 23:16
Could you please attach a [trace-level log] from geckodriver? Read more about reporting actionable bugs in our [contribution guidelines].

[trace-level log]: https://firefox-source-docs.mozilla.org/testing/geckodriver/TraceLogs.html
[contribution guidelines]: https://firefox-source-docs.mozilla.org/testing/geckodriver/Bugs.html

**Comment by rasikrodri** [comment] 2019-12-10 16:17
Is this what you need?
[geckodriver trace.txt](https://github.com/mozilla/geckodriver/files/3945907/geckodriver.trace.txt)

**Comment by rasikrodri** [comment] 2019-12-10 16:28
Is this what you need?
[geckodriver trace.txt](https://github.com/mozilla/geckodriver/files/3945956/geckodriver.trace.txt)

**Comment by whimboo** [comment] 2020-01-03 09:46
@rasikrodri sorry for the delay here, and thanks for your reply. I can reproduce it, and as such filed https://bugzilla.mozilla.org/show_bug.cgi?id=1606794 to get this regression fixed. Thanks a lot for reporting!

**Comment by whimboo** [comment] 2020-01-07 06:33
This is now fixed in Firefox 64 Nighlty, and should soon be available in one of the next 73 beta releases. Thanks again for reporting.

**Closed by whimboo** 2020-01-07 06:33 UTC
Labels: marionette

**Comment by whimboo** [comment] 2020-01-07 08:51
Sorry, I have to reopen the issue due to the backout we had to make.
