### ISSUE TITLE
Firefox browser get opened but URL is not fired.

### ISSUE THREAD

**Issue by bhoomi9488** [mozilla/geckodriver#855] opened 2017-08-03 21:29 UTC
## System
* Version: 0.18.0
* Platform: Mac OS X El Capitan
* Firefox: 55.0 (64-bit)
* Selenium: 3.4.0

## Testcase

System.setProperty("webdriver.firefox.marionette","/Users/sidd_44/Downloads/geckodriver”);
WebDriver driver = new FirefoxDriver();
driver.get("http://www.google.com/“);

## Stacktrace

JavaScript error: chrome://loop/content/modules/MozLoopService.jsm, line 104: NS_ERROR_FILE_NOT_FOUND: Component returned failure code: 0x80520012 (NS_ERROR_FILE_NOT_FOUND) [nsIXPCComponents_Utils.import]
JavaScript error: chrome://loop/content/modules/MozLoopService.jsm, line 104: NS_ERROR_FILE_NOT_FOUND: Component returned failure code: 0x80520012 (NS_ERROR_FILE_NOT_FOUND) [nsIXPCComponents_Utils.import]
1501795687327	addons.manager	DEBUG	Starting provider: <unnamed-provider>
1501795687327	addons.manager	DEBUG	Registering shutdown blocker for <unnamed-provider>
1501795687328	addons.manager	DEBUG	Provider finished startup: <unnamed-provider>
1501795687332	addons.xpi	INFO	Mapping fxdriver@googlecode.com to /var/folders/68/jdd_d0hd62b7g1qbjhyg89fh0000gn/T/anonymous4026991535961178394webdriver-profile/extensions/fxdriver@googlecode.com
1501795687332	addons.xpi	DEBUG	Ignoring file entry whose name is not a valid add-on ID: /var/folders/68/jdd_d0hd62b7g1qbjhyg89fh0000gn/T/anonymous4026991535961178394webdriver-profile/extensions/webdriver-staging
1501795687332	addons.xpi	DEBUG	Existing add-on fxdriver@googlecode.com in app-profile
1501795687333	addons.xpi	INFO	Mapping aushelper@mozilla.org to /Applications/Firefox.app/Contents/Resources/browser/features/aushelper@mozilla.org.xpi
1501795687333	addons.xpi	INFO	Mapping clicktoplay-rollout@mozilla.org to /Applications/Firefox.app/Contents/Resources/browser/features/clicktoplay-rollout@mozilla.org.xpi
1501795687335	addons.xpi	INFO	Mapping e10srollout@mozilla.org to /Applications/Firefox.app/Contents/Resources/browser/features/e10srollout@mozilla.org.xpi
1501795687337	addons.xpi	INFO	Mapping firefox@getpocket.com to /Applications/Firefox.app/Contents/Resources/browser/features/firefox@getpocket.com.xpi
1501795687337	addons.xpi	INFO	Mapping followonsearch@mozilla.com to /Applications/Firefox.app/Contents/Resources/browser/features/followonsearch@mozilla.com.xpi
1501795687337	addons.xpi	INFO	Mapping loop@mozilla.org to /Applications/Firefox.app/Contents/Resources/browser/features/loop@mozilla.org.xpi
1501795687338	addons.xpi	INFO	Mapping screenshots@mozilla.org to /Applications/Firefox.app/Contents/Resources/browser/features/screenshots@mozilla.org.xpi
1501795687338	addons.xpi	INFO	Mapping shield-recipe-client@mozilla.org to /Applications/Firefox.app/Contents/Resources/browser/features/shield-recipe-client@mozilla.org.xpi
1501795687338	addons.xpi	INFO	Mapping webcompat@mozilla.org to /Applications/Firefox.app/Contents/Resources/browser/features/webcompat@mozilla.org.xpi
1501795687339	addons.xpi	DEBUG	Existing add-on aushelper@mozilla.org in app-system-defaults
1501795687339	addons.xpi	DEBUG	Existing add-on clicktoplay-rollout@mozilla.org in app-system-defaults
1501795687340	addons.xpi	DEBUG	Existing add-on e10srollout@mozilla.org in app-system-defaults
1501795687341	addons.xpi	DEBUG	Existing add-on firefox@getpocket.com in app-system-defaults
1501795687341	addons.xpi	DEBUG	Existing add-on followonsearch@mozilla.com in app-system-defaults
1501795687342	addons.xpi	DEBUG	Existing add-on loop@mozilla.org in app-system-defaults
1501795687342	addons.xpi	DEBUG	Existing add-on screenshots@mozilla.org in app-system-defaults
1501795687342	addons.xpi	DEBUG	Existing add-on shield-recipe-client@mozilla.org in app-system-defaults
1501795687343	addons.xpi	DEBUG	Existing add-on webcompat@mozilla.org in app-system-defaults
1501795687344	addons.xpi	INFO	Mapping {972ce4c6-7e08-4474-a285-3208198ce6fd} to /Applications/Firefox.app/Contents/Resources/browser/extensions/{972ce4c6-7e08-4474-a285-3208198ce6fd}.xpi
1501795687344	addons.xpi	DEBUG	Existing add-on {972ce4c6-7e08-4474-a285-3208198ce6fd} in app-global
1501795687345	addons.xpi	DEBUG	getInstallState changed: false, state: {}
1501795687812	addons.productaddons	INFO	sending request to: https://aus5.mozilla.org/update/3/GMP/55.0/20170802111634/Darwin_x86_64-gcc3/en-US/beta/Darwin%2015.4.0/default/default/update.xml
1501795688143	addons.productaddons	INFO	Completed downloading document
1501795689180	addons.productaddons	INFO	downloadXHR File download. status=200
1501795689184	addons.productaddons	INFO	Downloaded file will be saved to /var/folders/68/jdd_d0hd62b7g1qbjhyg89fh0000gn/T/tmpaddon-a3647
1501795690877	addons.productaddons	INFO	downloadXHR File download. status=200
1501795690881	addons.productaddons	INFO	Downloaded file will be saved to /var/folders/68/jdd_d0hd62b7g1qbjhyg89fh0000gn/T/tmpaddon-591a8c
Exception in thread "main" org.openqa.selenium.remote.UnreachableBrowserException: Could not start a new session. Possible causes are invalid address of the remote server or browser start-up failure.
Build info: version: 'unknown', revision: 'unknown', time: 'unknown'
System info: host: 'siddharths-MacBook-Pro.local', ip: '10.231.13.130', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.11.4', java.version: '1.8.0_131'
Driver info: driver.version: FirefoxDriver
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:658)
	at org.openqa.selenium.remote.RemoteWebDriver.startSession(RemoteWebDriver.java:250)
	at org.openqa.selenium.remote.RemoteWebDriver.startSession(RemoteWebDriver.java:236)
	at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:137)
	at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:191)
	at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:108)
	at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:104)
	at NewPackage.KeyPressSimulation.main(KeyPressSimulation.java:13)
Caused by: java.lang.NullPointerException
	at org.openqa.selenium.remote.service.DriverService.waitUntilAvailable(DriverService.java:192)
	at org.openqa.selenium.firefox.XpiDriverService.start(XpiDriverService.java:94)
	at org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:78)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:637)
	... 7 more

**Comment by thc202** [comment] 2017-08-03 22:25
Note that the system property is `webdriver.gecko.driver`.

**Comment by mseele** [comment] 2017-08-04 07:56
I have the same effect under windows 7 & 10. 
Version 0.17.0 works like expected.

**Comment by andreastt** [comment] 2017-08-04 16:25
Please include a trace-level geckodriver log which you were asked to in the issue template. We can’t really tell what’s wrong from the Selenium stack trace.

**Comment by mseele** [comment] 2017-08-07 06:15
this is the output that i get with 0.18.0:

```1502086215541	geckodriver	INFO	geckodriver 0.18.0
1502086215557	geckodriver	INFO	Listening on 127.0.0.1:33045
1502086216202	geckodriver::marionette	INFO	Starting browser C:\Program Files\Mozilla Firefox\firefox.exe with args ["-marionette"]
1502086217868	Marionette	DEBUG	Setting recommended pref datareporting.policy.dataSubmissionPolicyAccepted to false
1502086217868	Marionette	INFO	Listening on port 54392
1502086218214	geckodriver::marionette	DEBUG	Connected to Marionette on localhost:54392
1502086218220	Marionette	DEBUG	Accepted connection 0 from 127.0.0.1:54397
1502086218221	geckodriver::marionette	TRACE	<- {"applicationType":"gecko","marionetteProtocol":3}
1502086218221	geckodriver::marionette	TRACE	-> 163:[0,1,"newSession",{"acceptInsecureCerts":true,"browserName":"firefox","capabilities":{"desiredCapabilities":{"acceptInsecureCerts":true,"browserName":"firefox"}}}]
1502086218225	Marionette	TRACE	0 -> [0,1,"newSession",{"acceptInsecureCerts":true,"browserName":"firefox","capabilities":{"desiredCapabilities":{"acceptInsecureCerts":true,"browserName":"firefox"}}}]
1502086218231	Marionette	CONFIG	Matched capabilities: {"browserName":"firefox","browserVersion":"54.0.1","platformName":"windows_nt","platformVersion":"10.0","pageLoadStrategy":"normal","acceptInsecureCerts":true,"timeouts":{"implicit":0,"pageLoad":300000,"script":30000},"rotatable":false,"specificationLevel":0,"moz:processID":12600,"moz:profile":"C:\\Users\\mseele\\AppData\\Local\\Temp\\rust_mozprofile.jZxvLpD8bxvr","moz:accessibilityChecks":false}
1502086218231	Marionette	WARN	TLS certificate errors will be ignored for this session
1502086218257	Marionette	DEBUG	loaded listener.js
1502086218271	Marionette	TRACE	0 <- [1,1,null,{"sessionId":"fb18fec6-c23d-4bf9-8513-43daf89058dc","capabilities":{"browserName":"firefox","browserVersion":"54.0.1","platformName":"windows_nt","platformVersion":"10.0","pageLoadStrategy":"normal","acceptInsecureCerts":true,"timeouts":{"implicit":0,"pageLoad":300000,"script":30000},"rotatable":false,"specificationLevel":0,"moz:processID":12600,"moz:profile":"C:\\Users\\mseele\\AppData\\Local\\Temp\\rust_mozprofile.jZxvLpD8bxvr","moz:accessibilityChecks":false}}]
1502086218272	geckodriver::marionette	TRACE	<- [1,1,null,{"sessionId":"fb18fec6-c23d-4bf9-8513-43daf89058dc","capabilities":{"browserName":"firefox","browserVersion":"54.0.1","platformName":"windows_nt","platformVersion":"10.0","pageLoadStrategy":"normal","acceptInsecureCerts":true,"timeouts":{"implicit":0,"pageLoad":300000,"script":30000},"rotatable":false,"specificationLevel":0,"moz:processID":12600,"moz:profile":"C:\\Users\\mseele\\AppData\\Local\\Temp\\rust_mozprofile.jZxvLpD8bxvr","moz:accessibilityChecks":false}}]
1502086218273	webdriver::server	DEBUG	<- 200 OK {"value": {"sessionId":"fb18fec6-c23d-4bf9-8513-43daf89058dc","capabilities":{"acceptInsecureCerts":true,"browserName":"firefox","browserVersion":"54.0.1","moz:accessibilityChecks":false,"moz:processID":12600,"moz:profile":"C:\\Users\\mseele\\AppData\\Local\\Temp\\rust_mozprofile.jZxvLpD8bxvr","pageLoadStrategy":"normal","platformName":"windows_nt","platformVersion":"10.0","rotatable":false,"specificationLevel":0,"timeouts":{"implicit":0,"pageLoad":300000,"script":30000}}}}
1502086218351	webdriver::server	DEBUG	-> POST /session/fb18fec6-c23d-4bf9-8513-43daf89058dc/window/maximize {}
1502086218352	geckodriver::marionette	TRACE	-> 25:[0,2,"maximizeWindow",{}]
1502086218354	Marionette	TRACE	0 -> [0,2,"maximizeWindow",{}]
1502086218357	Marionette	TRACE	0 <- [1,2,null,{}]
1502086218360	geckodriver::marionette	TRACE	<- [1,2,null,{}]
1502086218361	webdriver::server	DEBUG	<- 500 Internal Server Error {"value":{"error":"unknown error","message":"Failed to find width field","stacktrace":"stack backtrace:\n   0:           0x4bb74f - <no info>\n   1:           0x4bbea9 - <no info>\n   2:           0x44d60e - <no info>\n   3:           0x44944a - <no info>\n   4:           0x4203e1 - <no info>\n   5:           0x407dc7 - <no info>\n   6:           0x6d95b9 - <no info>\n   7:           0x4173a7 - <no info>\n   8:           0x6d38b3 - <no info>\n   9:     0x7ff9fbce2774 - BaseThreadInitThunk"}}
```
and this is the output i get with 0.17.0 (same code, only binary changed):

```1502086388836	geckodriver	INFO	Listening on 127.0.0.1:25960
1502086389548	geckodriver::marionette	INFO	Starting browser C:\Program Files\Mozilla Firefox\firefox.exe with args ["-marionette"]
1502086391224	Marionette	DEBUG	Setting recommended pref datareporting.policy.dataSubmissionPolicyAccepted to false
1502086391225	Marionette	INFO	Listening on port 54465
1502086391570	geckodriver::marionette	DEBUG	Connected to Marionette on localhost:54465
1502086391574	Marionette	DEBUG	Accepted connection 0 from 127.0.0.1:54470
1502086391575	geckodriver::marionette	TRACE	<- {"applicationType":"gecko","marionetteProtocol":3}
1502086391575	geckodriver::marionette	TRACE	-> 163:[0,1,"newSession",{"acceptInsecureCerts":true,"browserName":"firefox","capabilities":{"desiredCapabilities":{"acceptInsecureCerts":true,"browserName":"firefox"}}}]
1502086391579	Marionette	TRACE	0 -> [0,1,"newSession",{"acceptInsecureCerts":true,"browserName":"firefox","capabilities":{"desiredCapabilities":{"acceptInsecureCerts":true,"browserName":"firefox"}}}]
1502086391584	Marionette	CONFIG	Matched capabilities: {"browserName":"firefox","browserVersion":"54.0.1","platformName":"windows_nt","platformVersion":"10.0","pageLoadStrategy":"normal","acceptInsecureCerts":true,"timeouts":{"implicit":0,"pageLoad":300000,"script":30000},"rotatable":false,"specificationLevel":0,"moz:processID":12536,"moz:profile":"C:\\Users\\mseele\\AppData\\Local\\Temp\\rust_mozprofile.jr3wEOQiOaOd","moz:accessibilityChecks":false}
1502086391585	Marionette	WARN	TLS certificate errors will be ignored for this session
1502086391608	Marionette	DEBUG	loaded listener.js
1502086391617	Marionette	TRACE	0 <- [1,1,null,{"sessionId":"5dc7e212-954e-48e7-b49c-13e5e510866a","capabilities":{"browserName":"firefox","browserVersion":"54.0.1","platformName":"windows_nt","platformVersion":"10.0","pageLoadStrategy":"normal","acceptInsecureCerts":true,"timeouts":{"implicit":0,"pageLoad":300000,"script":30000},"rotatable":false,"specificationLevel":0,"moz:processID":12536,"moz:profile":"C:\\Users\\mseele\\AppData\\Local\\Temp\\rust_mozprofile.jr3wEOQiOaOd","moz:accessibilityChecks":false}}]
1502086391618	geckodriver::marionette	TRACE	<- [1,1,null,{"sessionId":"5dc7e212-954e-48e7-b49c-13e5e510866a","capabilities":{"browserName":"firefox","browserVersion":"54.0.1","platformName":"windows_nt","platformVersion":"10.0","pageLoadStrategy":"normal","acceptInsecureCerts":true,"timeouts":{"implicit":0,"pageLoad":300000,"script":30000},"rotatable":false,"specificationLevel":0,"moz:processID":12536,"moz:profile":"C:\\Users\\mseele\\AppData\\Local\\Temp\\rust_mozprofile.jr3wEOQiOaOd","moz:accessibilityChecks":false}}]
1502086391619	webdriver::server	DEBUG	<- 200 OK {"value": {"sessionId":"5dc7e212-954e-48e7-b49c-13e5e510866a","capabilities":{"acceptInsecureCerts":true,"browserName":"firefox","browserVersion":"54.0.1","moz:accessibilityChecks":false,"moz:processID":12536,"moz:profile":"C:\\Users\\mseele\\AppData\\Local\\Temp\\rust_mozprofile.jr3wEOQiOaOd","pageLoadStrategy":"normal","platformName":"windows_nt","platformVersion":"10.0","rotatable":false,"specificationLevel":0,"timeouts":{"implicit":0,"pageLoad":300000,"script":30000}}}}
1502086391701	webdriver::server	DEBUG	-> POST /session/5dc7e212-954e-48e7-b49c-13e5e510866a/window/maximize {}
1502086391701	geckodriver::marionette	TRACE	-> 25:[0,2,"maximizeWindow",{}]
1502086391704	Marionette	TRACE	0 -> [0,2,"maximizeWindow",{}]
1502086391710	Marionette	TRACE	0 <- [1,2,null,{}]
1502086391717	geckodriver::marionette	TRACE	<- [1,2,null,{}]
1502086391717	webdriver::server	DEBUG	<- 200 OK {"value": {}}
1502086391724	webdriver::server	DEBUG	-> POST /session/5dc7e212-954e-48e7-b49c-13e5e510866a/timeouts {"implicit":30000}
1502086391725	geckodriver::marionette	TRACE	-> 35:[0,3,"timeouts",{"implicit":30000}]
1502086391732	Marionette	TRACE	0 -> [0,3,"timeouts",{"implicit":30000}]
1502086391734	Marionette	TRACE	0 <- [1,3,null,{}]
1502086391734	geckodriver::marionette	TRACE	<- [1,3,null,{}]
1502086391734	webdriver::server	DEBUG	<- 200 OK {"value": {}}
1502086391737	webdriver::server	DEBUG	-> POST /session/5dc7e212-954e-48e7-b49c-13e5e510866a/url {"url":"http://localhost:8080/eDHTReporter/index"}
1502086391738	geckodriver::marionette	TRACE	-> 62:[0,4,"get",{"url":"http://localhost:8080/eDHTReporter/index"}]
1502086391739	Marionette	TRACE	0 -> [0,4,"get",{"url":"http://localhost:8080/eDHTReporter/index"}]
1502086391741	Marionette	DEBUG	Received DOM event "beforeunload" for "chrome://browser/content/browser.xul"
1502086391788	Marionette	DEBUG	Received DOM event "pagehide" for "chrome://browser/content/browser.xul"
1502086391788	Marionette	DEBUG	Received DOM event "unload" for "chrome://browser/content/browser.xul"
1502086391840	Marionette	DEBUG	Received DOM event "DOMContentLoaded" for "http://localhost:8080/eDHTReporter/index"
1502086391841	Marionette	DEBUG	Received DOM event "DOMContentLoaded" for "http://localhost:8080/eDHTReporter/index"
1502086391853	Marionette	DEBUG	Received DOM event "pageshow" for "http://localhost:8080/eDHTReporter/index"
1502086391879	Marionette	DEBUG	Received DOM event "pageshow" for "http://localhost:8080/eDHTReporter/index"
1502086391891	Marionette	TRACE	0 <- [1,4,null,{}]
1502086391894	geckodriver::marionette	TRACE	<- [1,4,null,{}]
1502086391894	webdriver::server	DEBUG	<- 200 OK {"value": {}}
1502086391907	webdriver::server	DEBUG	-> GET /session/5dc7e212-954e-48e7-b49c-13e5e510866a/title 
1502086391907	geckodriver::marionette	TRACE	-> 19:[0,5,"getTitle",{}]
1502086391908	Marionette	TRACE	0 -> [0,5,"getTitle",{}]
1502086391911	Marionette	TRACE	0 <- [1,5,null,{"value":"eDHTReporter"}]
1502086391912	geckodriver::marionette	TRACE	<- [1,5,null,{"value":"eDHTReporter"}]
1502086391913	webdriver::server	DEBUG	<- 200 OK {"value":"eDHTReporter"}
1502086391917	webdriver::server	DEBUG	-> GET /session/5dc7e212-954e-48e7-b49c-13e5e510866a/url 
1502086391918	geckodriver::marionette	TRACE	-> 24:[0,6,"getCurrentUrl",{}]
1502086391919	Marionette	TRACE	0 -> [0,6,"getCurrentUrl",{}]
1502086391920	Marionette	TRACE	0 <- [1,6,null,{"value":"http://localhost:8080/eDHTReporter/index"}]
1502086391921	geckodriver::marionette	TRACE	<- [1,6,null,{"value":"http://localhost:8080/eDHTReporter/index"}]
1502086391921	webdriver::server	DEBUG	<- 200 OK {"value":"http://localhost:8080/eDHTReporter/index"}
1502086391975	webdriver::server	DEBUG	-> GET /session/5dc7e212-954e-48e7-b49c-13e5e510866a/url 
1502086391975	geckodriver::marionette	TRACE	-> 24:[0,7,"getCurrentUrl",{}]
...
```

**Comment by mseele** [comment] 2017-08-07 06:17
Looks like the code

`driver.manage().window().maximize();`

is the problem. Without these line the test runs fine...

**Comment by whimboo** [comment] 2017-08-08 05:15
Yes, that is correct. Marking as dupe of issue #820.

**Closed by whimboo** 2017-08-08 05:15 UTC
Labels: waiting for reporter feedback

**Comment by Sanchit-20** [comment] 2017-12-11 21:26
Java                                  :openjdk version "1.8.0_151"
OS                                    : Ubuntu (16.04 LTS)
Browser                            : Mozilla Firefox 57.0.1 (64-bit)
Selenium java jar file        : 3.8.1
Mozilla Gecko webdriver  :0.19.0
Browser is opened but unable to open the URL.

Code
public static void main(String[] args) {
		//System.setProperty("webdriver.gecko.driver","/home/sanchit/eclipse-workspace/geckodriver.exe");
		System.setProperty("webdriver.firefox.marionette","/home/sanchit/eclipse-workspace/geckodriver.exe");
		WebDriver driver = new FirefoxDriver(); // Launches Firefox Browser with blank url
		driver.get("https://www.google.com"); // Navigates to the specified URL
		String Title = driver.getTitle();
		System.out.println(Title);
		driver.close(); // Closes the Browser
    }

Getting following exception.
Exception in thread "main" org.openqa.selenium.WebDriverException: Timed out waiting 45 seconds for Firefox to start.
Build info: version: '3.8.1', revision: '6e95a6684b', time: '2017-12-01T19:05:14.666Z'
System info: host: 'sanchit-Vostro-3558', ip: '127.0.1.1', os.name: 'Linux', os.arch: 'amd64', os.version: '4.4.0-101-generic', java.version: '1.8.0_151'
Driver info: driver.version: FirefoxDriver
	at org.openqa.selenium.firefox.XpiDriverService.waitUntilAvailable(XpiDriverService.java:131)
	at org.openqa.selenium.firefox.XpiDriverService.start(XpiDriverService.java:116)
	at org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:79)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:601)
	at org.openqa.selenium.remote.RemoteWebDriver.startSession(RemoteWebDriver.java:219)
	at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:142)
	at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:120)
	at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:98)
	at newpackage.Myclass.main(Myclass.java:12)
Caused by: org.openqa.selenium.net.UrlChecker$TimeoutException: Timed out waiting for [http://localhost:18379/hub/status] to be available after 45039 ms
	at org.openqa.selenium.net.UrlChecker.waitUntilAvailable(UrlChecker.java:100)
	at org.openqa.selenium.firefox.XpiDriverService.waitUntilAvailable(XpiDriverService.java:129)
	... 8 more
Caused by: java.util.concurrent.TimeoutException
	at java.util.concurrent.FutureTask.get(FutureTask.java:205)
	at com.google.common.util.concurrent.SimpleTimeLimiter.callWithTimeout(SimpleTimeLimiter.java:147)
	at org.openqa.selenium.net.UrlChecker.waitUntilAvailable(UrlChecker.java:75)
	... 9 more


Please someone help me to fix it, i am struggling with this since yesterday.

**Comment by mungaihpk** [comment] 2018-08-25 06:56
Change this line
`System.setProperty("webdriver.firefox.marionette","/Users/sidd_44/Downloads/geckodriver”);`
To look like this:
`System.setProperty("webdriver.gecko.driver","/Users/sidd_44/Downloads/geckodriver.exe”);`
