### ISSUE TITLE
org.openqa.selenium.InvalidArgumentException: File not found: for any uploading file

### ISSUE THREAD

**Issue by Pilleo** [mozilla/geckodriver#841] opened 2017-07-25 10:12 UTC
In order to help us efficiently investigate your issue, please provide the following information:

## Platform and application details
* Platform:   Linux + Ubuntu 17.04
* Firefox:  55.0b13 (64-bit) 56.0b1 (64-bit)
* Selenium:   firefoxdriver -0.18 + selenium 3.4 

## Steps to reproduce

Upload any image to any site form with .sendKeys()
It stopped working a few days ago with update of Firefox. It is working fine with Chrome.
- [x] Reproducable testcase:

 http://adiso.us/post-free-ad will fail for sure. Just upload image there
- [x] A trace level log:
  It crashes always with or without capabilities

**Comment by andreastt** [comment] 2017-08-08 15:04
Duplicate of https://github.com/mozilla/geckodriver/issues/859.

**Comment by andreastt** [comment] 2017-08-08 15:05
Duplicate of https://github.com/mozilla/geckodriver/issues/858, sorry.

**Closed by andreastt** 2017-08-08 15:04 UTC
Labels: marionette
