### ISSUE TITLE
Modifier is not released in Element Send Keys

### ISSUE THREAD

**Issue by phoenix384** [mozilla/geckodriver#1386] opened 2018-09-27 11:19 UTC
When using sendKeys with Keys.chord modifier keys don't seem to get released.
Keys.chord itself does not seem to be a problem since it simply adds Keys.NULL to a key combination to release any modifier key.
But Keys.NULL does not cause the releasing when using GeckoDriver.

`input.sendKeys(Keys.chord(Keys.CONTROL, "a"), "a");`
does nothing (because CTRL stays pressed)

Using Shift makes it more visible:
`input.sendKeys(Keys.chord(Keys.SHIFT, "a"), "b");`
should print "Ab" but prints "AB" (the "" seems to be Keys.NULL). So the Shift key did not get released (since it is a capital "b") and the NULL key got printed.

**Both examples work with Chrome and the legacy Firefox driver!**

If I avoid using Keys.chord and do it the way Actions (keyDown/keyUp) does, it works:
input.sendKeys(Keys.SHIFT, "a", Keys.SHIFT, "b");

## System

* Version: 0.22
* Platform: Windows 10
* Firefox: 62
* Selenium: 3.14.0

[trace.log](https://github.com/mozilla/geckodriver/files/2423828/trace.log)

**Comment by andreastt** [comment] 2018-09-27 12:02
It is not clear to me what the actual problem is here since the Selenium API does not match 1:1 down to the WebDriver primitives. What is the expected behaviour of `input.sendKeys(Keys.chord(Keys.SHIFT, "a"), "b")`? Should it produce `AB` or `Ab`?

From the trace log I can see that the following gets passed on the wire:

```
1538043909412	Marionette	TRACE	0 -> [0,11,"WebDriver:ElementSendKeys",{"id":"20bac883-6cfe-4ab5-ad26-5d210b49c54b","text":"ab","value":["","a","","b"]}]
```

 is U+E008, which WebDriver uses to indicate _Left Shift_.  is U+E000 which it calls the _null key_, and is used for clearing the key input state in an action chain. It should be possible to both pass U+E008 a second time and U+E000 to release _Left Shift_. From this I conclude that the expected input is `Ab`.

The [_Left Shift_, `A`, _Left Shift_] sequence was recently fixed by @whimboo in https://bugzilla.mozilla.org/show_bug.cgi?id=1405370. However, because geckodriver’s Element Send Keys command is not backed internally by the action chain, this must mean U+E000 isn’t recognised. This is tracked in https://bugzilla.mozilla.org/show_bug.cgi?id=1418995 and we are scheduled to begin work on that fairly soon.

**Comment by whimboo** [comment] 2018-09-27 13:54
I filed https://bugzilla.mozilla.org/show_bug.cgi?id=1494661 to track that work.

**Comment by dbrgn** [comment] 2018-11-14 18:48
I think I'm affected by the same issue.

With this test script:

```javascript
// $ node test.js firefox
const { Builder, By, Key, until, WebDriver, WebElement } = require('selenium-webdriver');

const browser = process.argv[2];

(async function() {
    const driver = await new Builder().forBrowser(browser).build();
    await driver.get('https://dbrgn.ch/textarea.html');
    await driver.findElement(By.id('area')).click();
    await driver.findElement(By.id('area')).sendKeys('hello');
    await driver.findElement(By.id('area')).sendKeys(Key.chord(Key.SHIFT, Key.ENTER));
    await driver.findElement(By.id('area')).sendKeys('world');
    await driver.sleep(10000);
    await driver.quit();
})();
```

...the result in Firefox looks like this:

![img](https://tmp.dbrgn.ch/screenshots/20181114193039-614u_in2.png)

It works fine in Chromium.

**Comment by dbrgn** [comment] 2019-02-25 17:33
> It is not clear to me what the actual problem is here since the Selenium API does not match 1:1 down to the WebDriver primitives. What is the expected behaviour of `input.sendKeys(Keys.chord(Keys.SHIFT, "a"), "b")`? Should it produce `AB` or `Ab`?

There is some documentation here: https://seleniumhq.github.io/selenium/docs/api/javascript/module/selenium-webdriver/index_exports_WebElement.html#sendKeys

![img](https://tmp.dbrgn.ch/screenshots/20190225183335-pkpcrv8a.png)

This might be a duplicate of #1502 and https://bugzilla.mozilla.org/show_bug.cgi?id=1527300.

**Comment by whimboo** [comment] 2019-02-26 14:19
Yes, it is indeed a dupe. I will mark it the other way around because #1502 has more information. Thanks for pointing that out.

**Closed by whimboo** 2019-02-26 14:19 UTC
Labels: marionette
