### ISSUE TITLE
Unable to create new session using a custom profile

### ISSUE THREAD

**Issue by bamBrewing** [mozilla/geckodriver#1459] opened 2019-01-02 14:01 UTC
## System

* Version: 0.23.0
* Platform: Linux
* Firefox: 60.3esr
* Selenium: n/a

## Testcase
- Start geckodriver on port 4444
- Post the following to the session endpoint (https://firefox-source-docs.mozilla.org/testing/geckodriver/geckodriver/Capabilities.html#capabilities-example):
```
{
  "capabilities":{
    "alwaysMatch":{
      "moz:firefoxOptions":{
        "binary":"/bin/firefox",
        "args":[
          "-profile",
          "/home/bambrew/.mozilla/firefox/gyus2ywv.nightwatch"
        ]
      }
    }
  }
}
```
- geckodriver will log:
`Running command: "/bin/firefox" "-marionette" "-profile" "/home/bambrew/.mozilla/firefox/gyus2ywv.nightwatch" "-foreground" "-no-remote"`
- Firefox will open and the profile is loaded as expected (with client certificates)
- After 60 seconds a 500 will be returned from the server with a connection refused message.
- If I remove the alwaysMatch from the capabilities:
```
{
  "capabilities":{
    "moz:firefoxOptions":{
      "binary":"/bin/firefox",
      "args":[
        "-profile",
        "/home/bambrew/.mozilla/firefox/gyus2ywv.nightwatch"
      ]
    }
  }
}
```
- geckodriver will log:
`Running command: "/bin/firefox" "-marionette" "-profile" "/tmp/rust_mozprofile.6JBkouREH02c" "-foreground" "-no-remote"`
- Firefox will open, but the profile is not loaded
- The session is created using, and my profile settings are not loaded.

## Stacktrace

none

## Trace-level log
```
1546436729809	webdriver::server	DEBUG	-> POST /session {
  "capabilities":{
    "alwaysMatch":{
      "moz:firefoxOptions":{
        "binary":"/bin/firefox",
        "args":[
          "-profile",
          "/home/bambrew/.mozilla/firefox/gyus2ywv.nightwatch"
        ]
      }
    }
  }
}
1546436729832	mozrunner::runner	INFO	`Running command: "/bin/firefox" "-marionette" "-profile" "/home/bambrew/.mozilla/firefox/gyus2ywv.nightwatch" "-foreground" "-no-remote"
1546436729836	geckodriver::marionette	DEBUG	Waiting 60s to connect to browser on 127.0.0.1:37844
1546436789880	mozrunner::runner	DEBUG	Killing process 8946
1546436789910	webdriver::server	DEBUG	<- 500 Internal Server Error {"value":{"error":"unknown error","message":"connection refused","stacktrace":""}}
```

**Comment by andreastt** [comment] 2019-01-02 14:16
I see you already spotted that this is a dupe of https://github.com/mozilla/geckodriver/issues/1058.

**Closed by andreastt** 2019-01-02 14:16 UTC
