### ISSUE TITLE
"Unable to find a matching set of capabilities" when the Firefox executable in PATH is a shell script outside the Firefox directory

### ISSUE THREAD

**Issue by wblondel** [mozilla/geckodriver#1756] opened 2020-08-04 21:11 UTC
When the Firefox executable that is in PATH is actually a shell script setting up the environment and lunching Firefox (on Fedora, for instance), Selenium fails by raising the following exception:
```
selenium.common.exceptions.SessionNotCreatedException: Message: Unable to find a matching set of capabilities
```
In 2017, this bug was already discussed: https://github.com/SeleniumHQ/selenium/issues/3884#issuecomment-296988595

## System

* Version: geckodriver 0.27.0 (7b8c4f32cdde 2020-07-28 18:16 +0000)
* Platform: Fedora 32
* Firefox: 79.0
* Selenium: Python 3.141.0

## Testcase

1. Start Fedora or any distribution where the Firefox executable in PATH is actually a shell script

```
[wblondel@localhost]$ which firefox
/usr/bin/firefox

[wblondel@localhost]$ file $(which firefox)
/usr/bin/firefox: Bourne-Again shell script, ASCII text executable

[wblondel@localhost]$ firefox -version
Mozilla Firefox 79.0
```

2. Download GeckoDriver and put it in your path or wherever you want as long as you give the correct path...

3. Run the code given below.

```python
from selenium import webdriver

driver = webdriver.Firefox(executable_path='./geckodriver')
```

## Script that SOLVES the issue but should be temporary

```python
from selenium import webdriver
from selenium.webdriver.firefox.firefox_binary import FirefoxBinary

binary = FirefoxBinary('/usr/lib64/firefox/firefox')
driver = webdriver.Firefox(executable_path='./geckodriver', firefox_binary=binary)
```

## Stacktrace

```
Traceback (most recent call last):
  File "main-firefox-nowork.py", line 4, in <module>
    driver = webdriver.Firefox(executable_path="./geckodriver")
  File "/home/wblondel/.local/lib/python3.8/site-packages/selenium/webdriver/firefox/webdriver.py", line 170, in __init__
    RemoteWebDriver.__init__(
  File "/home/wblondel/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 157, in __init__
    self.start_session(capabilities, browser_profile)
  File "/home/wblondel/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 252, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "/home/wblondel/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/wblondel/.local/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.SessionNotCreatedException: Message: Unable to find a matching set of capabilities
```

## Trace-level log

With this code:
```python
from selenium import webdriver
from selenium.webdriver.firefox.options import Options

opts = Options()
opts.log.level = "trace"
driver = webdriver.Firefox(executable_path="./geckodriver", options=opts)
```

(see: https://firefox-source-docs.mozilla.org/testing/geckodriver/TraceLogs.html#python)

the logs are:

```
1596575384033	geckodriver	INFO	Listening on 127.0.0.1:32997
```

(linked issue: https://github.com/SeleniumHQ/selenium/issues/8604 )

**Comment by mvermaes** [comment] 2020-08-05 06:40
We started experiencing the same error after updating geckodriver to 0.27 (wasn't see the error with 0.26). All versions identical to those listed above. Using @wblondel's workaround resolved the issue. Thanks!

**Comment by kingthorin** [comment] 2020-08-06 17:51
We've experienced this on Kali linux. It seems to have something to do with the intermediate script Kali uses to launch firefox. The script is normally `/usr/bin/firefox` which launches `firefox-esr`. Temporarily moving the script `mv /usr/bin/firefox /usr/bin/firefox-tmp` and creating a symbolic link `ln -s /usr/bin/firefox-esr /usr/bin/firefox` gets things working again (as a work around ... no idea if it negatively impacts other parts of Kali).

**Comment by dvershinin** [comment] 2020-08-06 22:17
Same issue with RHEL 8's Firefox and geckodriver 0.27.0.
No issue with 0.26.0.

**Comment by jgraham** [comment] 2020-08-07 08:56
Are these shell scripts passing through the full set of command line arguments? The change in 0.27 that's probably breaking things here is that we check the version of Firefox passed in using `firefox --version`. We added a regression test using a shell script wrapper, so there must be some discrepancy between our test and what's happening here.

**Comment by psiinon** [comment] 2020-08-07 09:02
The kali script:

    kali@kali:~$ cat /usr/bin/firefox
    #!/bin/sh

    FIREFOX="$(which firefox)"
    [ -x "$FIREFOX.real" ] && exec "$FIREFOX.real" "$@"

    exec firefox-esr "$@"
    kali@kali:~$ 

Also posted to https://chat.mozilla.org/#/room/#interop:mozilla.org :)

**Comment by jgraham** [comment] 2020-08-07 09:38
So that script is working for me. I added `set -x` at the top, created a `firefox.real` symlink to the actual firefox, and adjusted `PATH` so that `$(which firefox).real` would point at the symlink:
```
1596792841619	geckodriver	INFO	Listening on 127.0.0.1:4444
1596792854475	webdriver::server	DEBUG	-> POST /session {"capabilities": {"alwaysMatch": {"moz:firefoxOptions": {"binary": "/home/jgraham/test/firefox"}}}}
1596792854476	geckodriver::capabilities	DEBUG	Trying to read firefox version from ini files
1596792854476	geckodriver::capabilities	DEBUG	Trying to read firefox version from binary
+ which firefox
+ FIREFOX=/home/jgraham/test/firefox
+ [ -x /home/jgraham/test/firefox.real ]
+ exec /home/jgraham/test/firefox.real --version
1596792854580	geckodriver::capabilities	DEBUG	Found version Mozilla Firefox 79.0
1596792854585	mozrunner::runner	INFO	Running command: "/home/jgraham/test/firefox" "--marionette" "-foreground" "-no-remote" "-profile" "/tmp/rust_mozprofilelgapmJ"
1596792854587	geckodriver::marionette	DEBUG	Waiting 60s to connect to browser on 127.0.0.1:39259
+ which firefox
+ FIREFOX=/home/jgraham/test/firefox
+ [ -x /home/jgraham/test/firefox.real ]
+ exec /home/jgraham/test/firefox.real --marionette -foreground -no-remote -profile /tmp/rust_mozprofilelgapmJ
1596792856839	Marionette	TRACE	Marionette enabled
```

Can you try running geckodriver with `--log=trace` and adding some logging to the wrapper script to figure out what's different about your setup?

**Comment by jgraham** [comment] 2020-08-07 09:40
I didn't try the esr path, so maybe whatever `firefox-esr` ends up executing is the actual problem here?

**Comment by thc202** [comment] 2020-08-07 09:47
In Kali calling `firefox --version` returns `Mozilla Firefox 68.11.0esr` (relaying info gathered previously, in case that helps).

**Comment by mvermaes** [comment] 2020-08-07 09:52
FWIW on Fedora 32, `firefox --version` is `Mozilla Firefox 79.0`.

[This](https://src.fedoraproject.org/rpms/firefox/blob/master/f/firefox.sh.in) seems to be the upstream version of the `/usr/bin/firefox` script.

**Comment by mvermaes** [comment] 2020-08-07 10:13
Here's a [gist](https://gist.github.com/mvermaes/49bdc6bf9833749c5b783c63ea20268a) with a log from 0.26 and 0.27, after adding `set -x` to the top of `/usr/bin/firefox`

**Comment by thc202** [comment] 2020-08-07 10:38
That does not seem to have been run with `--log=trace`? (It's missing some messages e.g. `DEBUG	Trying to read firefox version from binary`.)

**Comment by mvermaes** [comment] 2020-08-07 10:56
Sorry, I assumed the example in the original comment was equivalent:
```
from selenium import webdriver
from selenium.webdriver.firefox.options import Options

opts = Options()
opts.log.level = "trace"
driver = webdriver.Firefox(executable_path="/home/user/bin/geckodriver", options=opts)
```
Dumb question, but how do I pass `--log=trace` here? Or should I be running something else?

**Comment by thc202** [comment] 2020-08-07 11:10
Don't know with the Python bindings, but you can run geckodriver directly in the command line with that argument.

**Comment by mvermaes** [comment] 2020-08-07 11:34
Adding @jgraham's comment from gist:

> I think the issue with esr is likely https://bugzilla.mozilla.org/show_bug.cgi?id=1657876 In the meantime, using any non-esr Firefox might be a viable workaround.

Note that my (Fedora 32/FF 79) log is non-esr. But the original workaround (specifying the path to the binary) is perfectly fine for me anyway. Was just trying to be helpful with the logs :)

**Comment by kingthorin** [comment] 2020-08-07 11:52
To be clear. On Kali setting up a sym link for esr seems to work, while the intermediate script does not.

**Comment by wblondel** [comment] 2020-08-07 13:32
> 
> 
> Sorry, I assumed the example in the original comment was equivalent:
> 
> ```
> from selenium import webdriver
> from selenium.webdriver.firefox.options import Options
> 
> opts = Options()
> opts.log.level = "trace"
> driver = webdriver.Firefox(executable_path="/home/user/bin/geckodriver", options=opts)
> ```
> 
> Dumb question, but how do I pass `--log=trace` here? Or should I be running something else?

That's the correct way to set the log level to trace, with the Python bindings (see here https://firefox-source-docs.mozilla.org/testing/geckodriver/TraceLogs.html#python )
Unfortunately, it doesn't give any useful logs.

**Comment by jgraham** [comment] 2020-08-07 14:25
Actually for the logs in this case you want `--log=trace` passed as an option to geckodriver. I'm not sure what the selenium bindings allow here (maybe you can start geckodriver manually and use a remote WebDriver to connect to it? I'm just using a custom client, and this case is pretty easy to do using Python+requests (or similar); simply start geckodriver and run something like `requests.post("http://localhost:4444/session", json={"capabilities": {"alwaysMatch": {"moz:firefoxOptions": {"binary": "/usr/bin/firefox"}}}})`

**Comment by wblondel** [comment] 2020-08-07 14:57
> 
> 
> Actually for the logs in this case you want `--log=trace` passed as an option to geckodriver. I'm not sure what the selenium bindings allow here (maybe you can start geckodriver manually and use a remote WebDriver to connect to it? I'm just using a custom client, and this case is pretty easy to do using Python+requests (or similar); simply start geckodriver and run something like `requests.post("http://localhost:4444/session", json={"capabilities": {"alwaysMatch": {"moz:firefoxOptions": {"binary": "/usr/bin/firefox"}}}})`

Okay, here is something very interesting.

The code I posted on the first post doesn't work (it uses Selenium).

But if I manually run geckodriver with `./geckodriver --log trace` and execute this Python script:
```
import requests

requests.post("http://localhost:4444/session", json={"capabilities": {"alwaysMatch": {"moz:firefoxOptions": {"binary": "/usr/bin/firefox"}}}})
```
It works with no issue (Firefox opens)!

As a reminder:
```
[wblondel@vm-test-fedora issue1756]$ which firefox
/usr/bin/firefox

[wblondel@vm-test-fedora issue1756]$ file $(which firefox)
/usr/bin/firefox: Bourne-Again shell script, ASCII text executable

[wblondel@vm-test-fedora issue1756]$ firefox -version
Mozilla Firefox 79.0
```

Here is the tracelog: https://gist.github.com/wblondel/52d96f3b58191c58726c481114a65130

**Comment by jgraham** [comment] 2020-08-07 14:59
I think it will work for firefox but fail for firefox-esr, if it's wrapped by a shell script.

**Comment by wblondel** [comment] 2020-08-07 15:00
> 
> 
> I think it will work for firefox but fail for firefox-esr, if it's wrapped by a shell script.

My Firefox is not firefox-esr, and it is wrapped by a shell script

**Comment by jgraham** [comment] 2020-08-07 15:02
Can you reproduce (and paste the logs, if so) if you don't specify a Firefox binary in the capabilities (i.e. pass in `capabilities={}`).

**Comment by wblondel** [comment] 2020-08-07 15:07
> 
> 
> Can you reproduce (and paste the logs, if so) if you don't specify a Firefox binary in the capabilities (i.e. pass in `capabilities={}`).

```python
import requests

requests.post("http://localhost:4444/session", json={"capabilities": {}})
```

logs: https://gist.github.com/wblondel/52d96f3b58191c58726c481114a65130#file-geckodriver-issue1756-wblonde-no-capabilities-log

It works also.

**Comment by thc202** [comment] 2020-08-07 15:56
Here's the trace log (diff) when running through Selenium, first with 0.26.0 and then with 0.27.0:
```diff
 geckodriver	DEBUG	Listening on 127.0.0.1:25904
 webdriver::server	DEBUG	-> POST /session {
   "desiredCapabilities": {
     "browserName": "firefox",
     "firefox_binary": "/path/to/firefox-bin.sh",
     "moz:firefoxOptions": {
       "args": [
       ],
       "binary": "/path/to/firefox-bin.sh",
       "prefs": {
       }
     },
     "acceptInsecureCerts": true
   },
   "capabilities": {
     "firstMatch": [
       {
         "acceptInsecureCerts": true,
         "browserName": "firefox",
         "moz:firefoxOptions": {
           "args": [
           ],
           "binary": "/path/to/firefox-bin.sh",
           "prefs": {
           }
         }
       }
     ]
   }
 }
 geckodriver::capabilities	DEBUG	Trying to read firefox version from ini files
 geckodriver::capabilities	DEBUG	Trying to read firefox version from binary
 + which firefox
 + FIREFOX=/usr/bin/firefox
 + [ -x /usr/bin/firefox.real ]
 + exec firefox --version
 geckodriver::capabilities	DEBUG	Found version Mozilla Firefox 79.0
-mozrunner::runner	INFO	Running command: "/path/to/firefox-bin.sh" "-marionette" "-foreground" "-no-remote" "-profile" "/tmp/rust_mozprofiledse2US"
+webdriver::server	DEBUG	<- 500 Internal Server Error {"value":{"error":"session not created","message":"Unable to find a matching set of capabilities","stacktrace":""}}
```
(Timestamps and port/level in first line omitted for clear diff.)

The version 0.26.0 keeps going (ends up starting Firefox), version 0.27.0 does not produce more output after the 500 error.

**Comment by thc202** [comment] 2020-08-07 17:09
Trial and error, it seems the problem is with `acceptInsecureCerts` (set to `true`) when using the script, sending the following request fails:
```Python
requests.post("http://localhost:4444/session", json={"capabilities": {"alwaysMatch": {"acceptInsecureCerts": True, "moz:firefoxOptions": {"binary": "/path/to/firefox-bin.sh"}}}})
```
if the `binary` field is changed to the Firefox binary it works (as already mentioned in a previous comment).

**Comment by whimboo** [comment] 2020-08-10 11:52
I had a quick look and this is related to a change in 0.27.0 where we don't fully parse the version number for esr and minor releases for a version check if the application.ini file is not available like in this case for a bash script. It will be fixed via https://bugzilla.mozilla.org/show_bug.cgi?id=1649693.

Thanks everyone for reporting that regression!

**Comment by thc202** [comment] 2020-08-10 12:13
This also happens with non-minor/esr releases, the tests above were done with 79.0. Are those versions also affected by that issue?

**Comment by whimboo** [comment] 2020-08-11 13:41
@mjzffr given that you have a Linux machine, would you mind to check that?

**Comment by quyvsquy** [comment] 2020-08-11 15:31
Manjaro KDE 20.0.3
Same issue with  Firefox 79 and geckodriver 0.27.0.
No issue with 0.26.0.

**Comment by mjzffr** [comment] 2020-08-11 17:35
@whimboo wfm on Ubuntu, Firefox 79.0 + geckodriver 0.27.0 whether I see the shell script as the binary or not.

Maybe Debian-based distros are not affected.

**Comment by thc202** [comment] 2020-08-11 18:40
Did you set the `acceptInsecureCerts` capability?

**Comment by whimboo** [comment] 2020-08-12 06:40
Setting capabilities or not especially for insecure certificates doesn't matter for this issue.

I would suggest that we first fix the minor and esr release parsing, and offer you a nightly build of geckodriver to test. Then we can see if the problem has been fixed or would need further investigation. I hope that we will have that ready soon. @jgraham is already working on it.

**Comment by thc202** [comment] 2020-08-12 09:21
The tests/evidence show otherwise, the browser is launched when that capability is not passed (or is set to `false`) even when the `binary` **is** a script. Just guessing (wrongly maybe), the problem might not be directly the capability but what geckodriver is doing when that's set, e.g.: https://github.com/mozilla/geckodriver/blob/917daaccc78bb8cac3ab324861ada48d68746d13/src/capabilities.rs#L134-L145 seems to trigger a version check, maybe that's not working (for all versions) when the `binary` is a script regardless of the version scheme.

Anyway, looking forward for the geckodriver with the minor/esr version fix, was just trying to make sure we don't miss the forest for a tree

**Comment by thc202** [comment] 2020-08-12 12:32
fyi, I debugged this, it fails in the above code, the `version_str` is "Mozilla Firefox 79.0" while `Version::from_str()` expects just the version numbers `79.0` (if I'm reading the regular expression correctly, it fails with `Failed to parse input as version string` though).

**Comment by thc202** [comment] 2020-08-12 14:29
Updated the diff on https://github.com/mozilla/geckodriver/issues/1756#issuecomment-670586398 I missed the version change, in 0.26.0 the `version_from_binary` was matching just the version (returned `79.0`) while in 0.27.0 is now matching also Mozilla Firefox, thus returning more than expected (for the later call).

**Comment by whimboo** [comment] 2020-08-13 06:17
Oh wow, good catch. I haven't realized that there is a version check in the `acceptInsecureCerts` capability. I think this was done around the days when the capability has been added, and we wanted to raise an error when an older not supported Firefox version was used.  Given that our minimal supported Firefox version is 60 now, we can perfectly remove the check now. I filed https://bugzilla.mozilla.org/show_bug.cgi?id=1658870 to get this done. Thanks again!

**Comment by whimboo** [comment] 2020-08-13 06:41
@thc202 mind testing a geckodriver build from our CI with the checks removed? It can be found at https://treeherder.mozilla.org/#/jobs?repo=try&revision=1e46b3c1e801b2e73439afe14264f6d51bd5c5ca&selectedTaskRun=TYJHiugySXuiTD4mw9gVKQ.0. Just click `Artifacts` in the lower pane and download the tarball. Thanks!

**Comment by thc202** [comment] 2020-08-13 09:05
Works as expected, browser is now launched, thank you!

**Comment by whimboo** [comment] 2020-08-13 10:46
Perfect. I will get this landed and when the next signed nightly builds of geckodriver are available I will post here.

@wblondel and anyone else seeing this can you also please test the geckodriver build from above? Thanks.

**Comment by mvermaes** [comment] 2020-08-13 10:56
Yep, works good for me. Thanks!

**Comment by wblondel** [comment] 2020-08-13 12:42
> 
> 
> Perfect. I will get this landed and when the next signed nightly builds of geckodriver are available I will post here.
> 
> @wblondel and anyone else seeing this can you also please test the geckodriver build from above? Thanks.

I confirm everything is working well now on my system! Thank you.

**Comment by whimboo** [comment] 2020-08-13 16:25
Thanks for all your feedback. My patch has been merged in the meantime and signed geckodriver nightly builds are available. If needed you can use those until the next geckodriver release has happened. We hope it won't take that long.

https://treeherder.mozilla.org/#/jobs?repo=mozilla-central&searchStr=gd-s&revision=06e4f8547d78187f934074b2b4ff4d4d4d12efd5

**Closed by whimboo** 2020-08-13 16:25 UTC
Labels: geckodriver

**Comment by pr-it** [comment] 2020-10-22 21:16
> Same issue with RHEL 8's Firefox and geckodriver 0.27.0.
> No issue with 0.26.0.

I can confirm. The issue is related to driver 27 and 26 works fine.
