### ISSUE TITLE
Problem with start/stop per test

### ISSUE THREAD

**Issue by ttwd80** [mozilla/geckodriver#115] opened 2016-06-25 01:38 UTC
I test multiple Selenium drivers in my Junit test case.
In the @Before method, i create new instance of the driver.
In my @After method, I use "quit" method.
This works for
- phantomjs
- google chrome

```
	@Before
	public void init() {
		webDriver = createWebDriver();
	}

	@After
	public void cleanUp() {
		webDriver.quit();
	}

```

When I use this logic with geckodriver/wires, it only works for the first item being tested.
After my first test (create and quit), the next create says, connection refused.

```
1466818465301	Marionette	DEBUG	Marionette enabled via build flag and pref
1466818465425	Marionette	INFO	Listening on port 2828
1466818465550	Marionette	DEBUG	Marionette enabled via command-line flag
1466818465612	Marionette	DEBUG	Accepted connection conn0 from 127.0.0.1:53242
1466818465675	Marionette	TRACE	conn0 -> [0,1,"newSession",{"capabilities":{"desiredCapabilities":{"browserName":"firefox","platform":"ANY","version":""},"requiredCapabilities":{}},"sessionId":null}]
1466818465691	Marionette	CONFIG	Changing capabilities: {"browserName":"Firefox","browserVersion":"47.0","platformName":"Linux","platformVersion":"4.4.0-24-generic","specificationLevel":0,"raisesAccessibilityExceptions":false,"rotatable":false,"acceptSslCerts":false,"takesElementScreenshot":true,"takesScreenshot":true,"proxy":{},"platform":"LINUX","XULappId":"{ec8030f7-c20a-464f-9b0e-13a3a9e97384}","appBuildId":"20160606113944","device":"desktop","version":""}
1466818466377	Marionette	DEBUG	loaded listener.js
1466818466382	Marionette	DEBUG	loaded listener.js
1466818466484	Marionette	TRACE	conn0 <- [1,1,null,{"sessionId":"a1b50489-d052-4d66-8e4a-867bf006ebbd","capabilities":{"browserName":"Firefox","browserVersion":"47.0","platformName":"Linux","platformVersion":"4.4.0-24-generic","specificationLevel":0,"raisesAccessibilityExceptions":false,"rotatable":false,"acceptSslCerts":false,"takesElementScreenshot":true,"takesScreenshot":true,"proxy":{},"platform":"LINUX","XULappId":"{ec8030f7-c20a-464f-9b0e-13a3a9e97384}","appBuildId":"20160606113944","device":"desktop","version":"","command_id":1}}]
1466818466607	Marionette	TRACE	conn0 -> [0,2,"get",{"url":"http://localhost:58080/test/1-test-static-text.html"}]
1466818467574	Marionette	TRACE	conn0 <- [1,2,null,{}]
1466818467586	Marionette	TRACE	conn0 -> [0,3,"findElements",{"using":"css selector","value":"div div ol li span.africa"}]
1466818467590	Marionette	TRACE	conn0 <- [1,3,null,[{"element-6066-11e4-a52e-4f735466cecf":"aa2061ca-ed7a-446a-a27c-2001038dba04","ELEMENT":"aa2061ca-ed7a-446a-a27c-2001038dba04"}]]
1466818467608	Marionette	TRACE	conn0 -> [0,4,"quitApplication",{"flags":["eForceQuit"]}]
1466818467608	Marionette	TRACE	conn0 <- [1,4,null,{}]
Tests run: 4, Failures: 0, Errors: 3, Skipped: 0, Time elapsed: 4.39 sec <<< FAILURE! - in web.sanity.IntegrationTest1WebStaticTextIT
test1StaticTextCount(web.sanity.IntegrationTest1WebStaticTextIT)  Time elapsed: 0.024 sec  <<< ERROR!
org.openqa.selenium.remote.UnreachableBrowserException: 
Could not start a new session. Possible causes are invalid address of the remote server or browser start-up failure.
Build info: version: '2.53.0', revision: '35ae25b1534ae328c771e0856c93e187490ca824', time: '2016-03-15 10:43:46'
System info: host: 'ubuntu', ip: '127.0.1.1', os.name: 'Linux', os.arch: 'amd64', os.version: '4.4.0-24-generic', java.version: '1.8.0_91'
Driver info: driver.version: MarionetteDriver
Caused by: org.openqa.selenium.WebDriverException: 
org.apache.http.conn.HttpHostConnectException: Connect to localhost:9950 [localhost/127.0.0.1, localhost/0:0:0:0:0:0:0:1] failed: Connection refused
Build info: version: '2.53.0', revision: '35ae25b1534ae328c771e0856c93e187490ca824', time: '2016-03-15 10:43:46'

```

I tried adding a sleep method prior to invocation, but it does not work.
I still get errors.
Any insight on this?

When i put the configuration to use chrome,
on my 4 @Test cases, I get all passes.

When i put the configuration to use phantomjs,
on my 4 @Test cases, I get all passes.

When i put the configuration to use Marionette,
on my 4 @Test cases, only the first one passes.
The rest fail.
Tests in error: 
  ```
IntegrationTest1WebStaticTextIT>AbstractWebIntegrationTest.init:29->AbstractWebIntegrationTest.createWebDriver:70 » UnreachableBrowser
  IntegrationTest1WebStaticTextIT>AbstractWebIntegrationTest.init:29->AbstractWebIntegrationTest.createWebDriver:70 » UnreachableBrowser
  IntegrationTest1WebStaticTextIT>AbstractWebIntegrationTest.init:29->AbstractWebIntegrationTest.createWebDriver:70 » UnreachableBrowser

```

The reason I quit after each test is to isolate the tests. Quit will ensure the cookies and/or other session related data will not bleed from one test to another.

**Comment by martijnhjk** [comment] 2016-06-27 15:33
@ttwd80 is this a dupe of https://github.com/mozilla/geckodriver/issues/42 ?

**Comment by andreastt** [comment] 2016-06-27 15:48
Looks like it. Thanks, @martijnhjk!

**Closed by andreastt** 2016-06-27 15:48 UTC
