### ISSUE TITLE
Regression in confirmation dialog opened with onbeforeunload since Firefox 124.0

### ISSUE THREAD

**Issue by surli** [mozilla/geckodriver#2182] opened 2024-06-19 15:46 UTC
The bug was originally reported there: https://github.com/SeleniumHQ/docker-selenium/issues/2215
Basically when using the docker image for Firefox 123.0 I was able to properly intercept any confirmation dialog triggered by a onbeforeunload javascript call, which was allowing us to perform some validations of our UI.
Since Firefox 124.0 however, all those calls seems to not work anymore. 

According to @diemol in https://github.com/SeleniumHQ/docker-selenium/issues/2215#issuecomment-2168192421 this is not a selenium issue and should be reported, hence this ticket.

## System

* Version: 0.34.0
* Platform: Linux
* Firefox: 
* Selenium: 4.21.0 (but apparently reproduced on 4.18.0)

## Testcase

The issue can be reproduced with the following selenium snippet:
```


from selenium import webdriver
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC
from selenium.webdriver.common.by import By
import time

def open_url():
    driver = webdriver.Firefox()
    driver.get("https://www.selenium.dev/blog/2024/selenium-4-21-released/")
    driver.execute_script("window.onbeforeunload = function () { return false; }")
    link = driver.find_element(By.XPATH, "//a[text()='@diemol']")
    link.click()
    time.sleep(20)

    alert = WebDriverWait(driver, 3).until(EC.alert_is_present())
    alert.accept()
    driver.quit()

if __name__ == "__main__":
    open_url()
```

**Comment by whimboo** [comment] 2024-06-19 21:33
Please note that in Firefox 124 we shipped support for handling the `beforeunload` prompt correctly. As per specification the prompt should always be automatically accepted. Up until Firefox 123 this kind of prompt was completely disabled by default. When you are saying that you were able to handle the dialog did you reset the preference `dom.disable_beforeunload` to `false`? You should not have seen this dialog at all.

**Comment by surli** [comment] 2024-06-20 07:16
Thanks for the answer, though I'm not sure to understand it completely. 

> As per specification the prompt should always be automatically accepted.

You mean that the prompt should never be displayed even for an end user using Firefox? Or you're talking about the specification for using Firefox in an automated way only (sorry I'm not entirely familiar with your project)?

> When you are saying that you were able to handle the dialog did you reset the preference dom.disable_beforeunload to false?

Yes we do set this property to false for executing our tests. I actually tried to remove this setting from our test framework, but AFAIR it didn't change the outcome.

Note that in our case it's important that we are able to test that this confirmation dialog is displayed for our end users: we want to ensure that they won't leave an edition page before saving without having to confirm it. And we're doing this test in an automated way for a long time now, so it's really an important regression for us to lose that.

**Comment by whimboo** [comment] 2024-06-20 07:55
> > As per specification the prompt should always be automatically accepted.
> 
> You mean that the prompt should never be displayed even for an end user using Firefox? Or you're talking about the specification for using Firefox in an automated way only (sorry I'm not entirely familiar with your project)?

Sorry when it as a bit unclear. When we speak about geckodriver and testing via WebDriver classic then I reference the https://w3c.github.io/webdriver/ specification. Given the limitations of WebDriver classic it is not possible to correctly handle the `beforeunload` prompts. As such the specification defines that these kind of prompts are automatically accepted to not block any navigation. See the [3rd paragraph here](https://w3c.github.io/webdriver/#user-prompts). 

This doesn't apply to normal users of Firefox for sure.

> > When you are saying that you were able to handle the dialog did you reset the preference dom.disable_beforeunload to false?
> 
> Yes we do set this property to false for executing our tests. I actually tried to remove this setting from our test framework, but AFAIR it didn't change the outcome.

Ok, so by changing this preference value you entered an unsupported mode, which by coincidence worked in your case. But only because our implementation for this type of prompt was not complete and also didn't conform to the specification. This has now been corrected with the Firefox 124 release.

> Note that in our case it's important that we are able to test that this confirmation dialog is displayed for our end users: we want to ensure that they won't leave an edition page before saving without having to confirm it. And we're doing this test in an automated way for a long time now, so it's really an important regression for us to lose that.

Given that you are using Selenium for testing, you will need to update your tests to utilize the WebDriver BiDi upgrade path. Here are the steps you can follow to get it working again:

1. Make sure that the `webSocketUrl` capability gets set to `true` which requests a WebDriver BiDi session.
2. Connect to the BiDi session via a method as offered by your Selenium binding.

Now with an active BiDi session the `beforeunload` prompt should no longer be accepted automatically, and your current approach should work again. The only downside here is that you are required to use Firefox 129, which is currently only available as Nightly build.

Please let us know if this solution works for you or if you encounter any issues. Additionally, while I may not be aware of all the current limitations in Selenium, @diemol can potentially provide further assistance and insights.

**Comment by whimboo** [comment] 2024-06-20 09:33
If you start with BiDi please let us know which features are missing. A good matrix of commands and events that we are going to implement or already have implemented can be found in [this document](https://docs.google.com/spreadsheets/d/1bkiPU5eDBCqFkx5p_VSBx_OK8gy9TeHRKQVPHKMATGQ/edit?pli=1#gid=1960491400). At least for Firefox and the web-platform sections I keep it up to date.

**Comment by surli** [comment] 2024-06-20 09:38
Perfect, thanks for the pointers. We'll try to move on the subject in a branch and to see how much tests are broken, I'll keep you posted if we see missing features, but honestly we don't use much advanced stuff I think so I hope it should be ok.

**Comment by whimboo** [comment] 2024-06-20 09:44
Sounds good.

I'm going to close this issue now given that it is not actually a regression but an expected change in behavior when `beforeunload` prompts were enabled by the preference.

**Closed by whimboo** 2024-06-20 09:44 UTC
Labels: awaiting reporter feedback

**Comment by basil** [comment] 2024-07-31 01:49
We were also setting `dom.disable_beforeunload` to false and were impacted by this. I installed the latest Firefox nightly and enabled BiDi in Selenium with `org.openqa.selenium.firefox.FirefoxOptions#enableBiDi()` (which calls `org.openqa.selenium.firefox.FirefoxOptions#setCapability("webSocketUrl", true)`), and I now see the alert again (good!) but I still think there is a Selenium issue: `org.openqa.selenium.support.ui.ExpectedConditions#alertIsPresent` (which we are waiting on to confirm the alert is displayed) is never true, perhaps because Selenium needs to adapt to the new type of alert?

**Comment by whimboo** [comment] 2024-08-01 07:32
@basil that's good to hear! Regarding the remaining issue would you mind creating a trace log so that we can see what geckodriver actually returns? Please see https://firefox-source-docs.mozilla.org/testing/geckodriver/TraceLogs.html for details. Thanks.

**Comment by whimboo** [comment] 2024-08-08 13:57
I don't have a chance to easily run this Selenium test for the Java bindings. What I would like to know about is which WebDriver API Selenium actually uses when calling `ExpectedConditions.alertIsPresent()`.

@shs96c or @pujagani could you maybe help out with that? Could it be a Selenium issue? Thanks!

**Comment by pujagani** [comment] 2024-08-08 14:54
I can help take a look.

**Comment by pujagani** [comment] 2024-08-09 03:46
@whimboo Selenium uses Get Alert Text https://www.w3.org/TR/webdriver/#get-alert-text when calling `ExpectedConditions.alertIsPresent()`.

**Comment by pujagani** [comment] 2024-08-09 04:12
@basil I ran the example successfully with BiDi enabled and could see the alert message being printed too. 

Firefox Nightly version: 130.0b2
Geckodriver version: [0.35.0](https://github.com/mozilla/geckodriver/releases/tag/v0.35.0)
Selenium version: 4.23.0

```
 FirefoxOptions firefoxOptions = new FirefoxOptions();
    firefoxOptions.setBinary("/Applications/Firefox Developer Edition.app/Contents/MacOS/firefox");
    firefoxOptions.enableBiDi();

    //    int firefoxVersion = getFirefoxVersion();
//    System.err.println("Firefox version: " + firefoxVersion);
//    if (firefoxVersion < 124) {
//      System.err.println("dom.disable_beforeunload=false");
//      firefoxOptions.addPreference("dom.disable_beforeunload", false);
//    } else if (firefoxVersion > 128) {
//      System.err.println("enableBiDi()");
//      firefoxOptions.enableBiDi();
//    }
```
I commented on the lines trying to find the version because I was getting some errors. 
Please ensure the options are pointing to Firefox Nightly binary. 
I hope this helps!

**Comment by whimboo** [comment] 2024-08-09 08:19
Thank you @pujagani! So it's not clear to me what the issue is for @basil and without a [trace log](https://firefox-source-docs.mozilla.org/testing/geckodriver/TraceLogs.html) there is nothing that I can do.

**Comment by basil** [comment] 2024-08-09 18:04
> Please ensure the options are pointing to Firefox Nightly binary. I hope this helps!

I do not see how it could.

> So it's not clear to me what the issue is for @basil

@whimboo The issue was clearly described above:

> Either navigating away by clicking within the same page or going to a new page should display the alert, but going to a new page doesn't seem to display the alert

The above test passes whether `clickWithinPage` is set to `true` or `false` on Firefox < 124 with `dom.disable_beforeunload=false`. With Firefox > 128 and `enableBiDi()`, the above test passes when `clickWithinPage` is true but fails when `clickWithinPage` is false, which is a change in behavior. I would expect to see the alert in either case, just like in Firefox < 124.

**Comment by surli** [comment] 2024-08-19 15:06
> Either navigating away by clicking within the same page or going to a new page should display the alert, but going to a new page doesn't seem to display the alert

For info I started to apply the changes in our project to support BiDi and it seems to fix properly my original issue, except in one case when we actually leave the page without clicking on a link but by using `driver.get('myurl')`. So it seems to confirm the regression reported by @basil.
