### ISSUE TITLE
Navigating to about:addons causes Marionette to hang

### ISSUE THREAD

**Issue by KSKS** [mozilla/geckodriver#715] opened 2017-05-03 18:24 UTC
## Firefox Version
53

## Platform
Windows

geckodriver v0.16.1
selenium-webdriver 3.4.0

## Steps to reproduce -
Start Firefox with webdriver.js
Goes to Tools -> Add-ons in Firefox
The page never finish "loading", can't add/manage add-ons manually or programmatically

![addonsloading](https://cloud.githubusercontent.com/assets/555130/25649436/69ef6968-2f8a-11e7-80a9-cd23aeebd66c.PNG)

geokodriver log:

> 1493833475650   webdriver::httpapi      DEBUG   Creating routes
> 1493833475666   geckodriver     INFO    Listening on 127.0.0.1:4444
> 1493833475666   webdriver::server       DEBUG   ? GET /status
> 1493833475666   webdriver::server       DEBUG   ? 200 OK {"value":{"message":"","ready":true}}
> 1493833475697   webdriver::server       DEBUG   ? POST /session {"desiredCapabilities":{"browserName
> ":"firefox","nativeEvents":true,"marionette":true,"moz:firefoxOptions":{}}}
> 1493833475744   geckodriver::marionette INFO    Starting browser \\?\H:\Program Files (x86)\Mozilla
> Firefox\firefox.exe with args ["-marionette"]
> 1493833477783   geckodriver::marionette DEBUG   Connected to Marionette on localhost:51684
> 1493833477821   geckodriver::marionette TRACE   ? {"applicationType":"gecko","marionetteProtocol":3}
> 
> 1493833477822   geckodriver::marionette TRACE   ? 185:[0,1,"newSession",{"browserName":"firefox","ca
> pabilities":{"desiredCapabilities":{"browserName":"firefox","marionette":true,"nativeEvents":true}},
> "marionette":true,"nativeEvents":true}]
> 1493833477899   geckodriver::marionette TRACE   ? [1,1,null,{"sessionId":"c191a4c1-535c-4d86-8fdf-d1
> e53f39a09b","capabilities":{"browserName":"firefox","browserVersion":"54.0","platformName":"windows_
> nt","platformVersion":"6.1","pageLoadStrategy":"normal","acceptInsecureCerts":false,"timeouts":{"imp
> licit":0,"pageLoad":300000,"script":30000},"rotatable":false,"specificationLevel":0,"moz:processID":
> 1768,"moz:profile":"H:\\Users\\kns\\AppData\\Local\\Temp\\rust_mozprofile.W33WZl17JJu2","moz:accessi
> bilityChecks":false}}]
> 1493833477902   webdriver::server       DEBUG   ? 200 OK {"value": {"sessionId":"c191a4c1-535c-4d86-
> 8fdf-d1e53f39a09b","capabilities":{"acceptInsecureCerts":false,"browserName":"firefox","browserVersi
> on":"54.0","moz:accessibilityChecks":false,"moz:processID":1768,"moz:profile":"H:\\Users\\kns\\AppDa
> ta\\Local\\Temp\\rust_mozprofile.W33WZl17JJu2","pageLoadStrategy":"normal","platformName":"windows_n
> t","platformVersion":"6.1","rotatable":false,"specificationLevel":0,"timeouts":{"implicit":0,"pageLo
> ad":300000,"script":30000}}}}

This doesn't reproduce on OSX.
This doesn't reproduce with geokodriver v0.15.0

I also tried to set the Firefox profile to an existing profile that didn't have this issue, but it still occurs.

**Comment by andreastt** [comment] 2017-05-03 19:40
We recently made a number of changes to the page loading algorithm in Firefox. Could you try this again with the latest Firefox Nightly to see if that makes a difference?

cc @whimboo

**Comment by whimboo** [comment] 2017-05-03 21:10
`Get Addons` is a remote page and loads its content from the web. As Andreas said, please use a Nightly build and paste the trace level log. It will show which page load events Marionette receives. It can give an idea.

**Comment by andreastt** [comment] 2017-05-03 21:21
Do you have a trace-level log from that run?

**Comment by KSKS** [comment] 2017-05-03 21:22
geckodriver log with nightly:

> 
> 1493833399495   webdriver::httpapi      DEBUG   Creating routes
> 1493833399511   geckodriver     INFO    Listening on 127.0.0.1:4444
> 1493833399511   webdriver::server       DEBUG   ? GET /status
> 1493833399511   webdriver::server       DEBUG   ? 200 OK {"value":{"message":"","ready":true}}
> 1493833399542   webdriver::server       DEBUG   ? POST /session {"desiredCapabilities":{"browserName
> ":"firefox","nativeEvents":true,"marionette":true,"moz:firefoxOptions":{"binary":"H:\\Program Files\
> \Nightly\\firefox.exe"}}}
> 1493833399589   geckodriver::marionette INFO    Starting browser \\?\H:\Program Files\Nightly\firefo
> x.exe with args ["-marionette"]
> 1493833401633   geckodriver::marionette TRACE     connection attempt 0/600
> 1493833402773   geckodriver::marionette DEBUG   Connected to Marionette on localhost:51920
> 1493833402773   geckodriver::marionette TRACE   ? {"applicationType":"gecko","marionetteProtocol":3}
> 
> 1493833402773   geckodriver::marionette TRACE   ? 185:[0,1,"newSession",{"browserName":"firefox","ca
> pabilities":{"desiredCapabilities":{"browserName":"firefox","marionette":true,"nativeEvents":true}},
> "marionette":true,"nativeEvents":true}]
> 1493833402866   geckodriver::marionette TRACE   ? [1,1,null,{"sessionId":"62e83e9c-f98d-42b1-881c-41
> 36ca4a7b95","capabilities":{"browserName":"firefox","browserVersion":"55.0a1","platformName":"window
> s_nt","platformVersion":"6.1","pageLoadStrategy":"normal","acceptInsecureCerts":false,"timeouts":{"i
> mplicit":0,"pageLoad":300000,"script":30000},"rotatable":false,"specificationLevel":0,"moz:processID
> ":4136,"moz:profile":"H:\\Users\\kns\\AppData\\Local\\Temp\\rust_mozprofile.ckXxfhT6jwyZ","moz:acces
> sibilityChecks":false}}]
> 1493833402882   webdriver::server       DEBUG   ? 200 OK {"value": {"sessionId":"62e83e9c-f98d-42b1-
> 881c-4136ca4a7b95","capabilities":{"acceptInsecureCerts":false,"browserName":"firefox","browserVersi
> on":"55.0a1","moz:accessibilityChecks":false,"moz:processID":4136,"moz:profile":"H:\\Users\\kns\\App
> Data\\Local\\Temp\\rust_mozprofile.ckXxfhT6jwyZ","pageLoadStrategy":"normal","platformName":"windows
> _nt","platformVersion":"6.1","rotatable":false,"specificationLevel":0,"timeouts":{"implicit":0,"page
> Load":300000,"script":30000}}}}

**Comment by whimboo** [comment] 2017-05-04 06:35
Nothing in this trace log shows that a `get` request for `about:addons` was issued through geckodriver.

**Comment by KSKS** [comment] 2017-05-04 14:11
I just go to the addons page manually. if it helps this is the log that includes going to about:addons through geckodriver:

> 1493836364716   webdriver::httpapi      DEBUG   Creating routes
> 1493836364732   geckodriver     INFO    Listening on 127.0.0.1:4444
> 1493836364732   webdriver::server       DEBUG   ? GET /status
> 1493836364732   webdriver::server       DEBUG   ? 200 OK {"value":{"message":"","ready":true}}
> 1493836364763   webdriver::server       DEBUG   ? POST /session {"desiredCapabilities":{"browserName
> ":"firefox","nativeEvents":true,"marionette":true,"moz:firefoxOptions":{"binary":"H:\\Program Files\
> \Nightly\\firefox.exe"}}}
> 1493836364796   geckodriver::marionette INFO    Starting browser \\?\H:\Program Files\Nightly\firefo
> x.exe with args ["-marionette"]
> 1493836366850   geckodriver::marionette TRACE     connection attempt 0/600
> 1493836367974   geckodriver::marionette DEBUG   Connected to Marionette on localhost:52184
> 1493836367974   geckodriver::marionette TRACE   ? {"applicationType":"gecko","marionetteProtocol":3}
> 
> 1493836367974   geckodriver::marionette TRACE   ? 185:[0,1,"newSession",{"browserName":"firefox","ca
> pabilities":{"desiredCapabilities":{"browserName":"firefox","marionette":true,"nativeEvents":true}},
> "marionette":true,"nativeEvents":true}]
> 1493836368052   geckodriver::marionette TRACE   ? [1,1,null,{"sessionId":"2bc4ffd4-a7fa-494f-ae23-29
> ed6420591c","capabilities":{"browserName":"firefox","browserVersion":"55.0a1","platformName":"window
> s_nt","platformVersion":"6.1","pageLoadStrategy":"normal","acceptInsecureCerts":false,"timeouts":{"i
> mplicit":0,"pageLoad":300000,"script":30000},"rotatable":false,"specificationLevel":0,"moz:processID
> ":5752,"moz:profile":"H:\\Users\\kns\\AppData\\Local\\Temp\\rust_mozprofile.iMfjBoftlWDj","moz:acces
> sibilityChecks":false}}]
> 1493836368052   webdriver::server       DEBUG   ? 200 OK {"value": {"sessionId":"2bc4ffd4-a7fa-494f-
> ae23-29ed6420591c","capabilities":{"acceptInsecureCerts":false,"browserName":"firefox","browserVersi
> on":"55.0a1","moz:accessibilityChecks":false,"moz:processID":5752,"moz:profile":"H:\\Users\\kns\\App
> Data\\Local\\Temp\\rust_mozprofile.iMfjBoftlWDj","pageLoadStrategy":"normal","platformName":"windows
> _nt","platformVersion":"6.1","rotatable":false,"specificationLevel":0,"timeouts":{"implicit":0,"page
> Load":300000,"script":30000}}}}
> 1493836368067   webdriver::server       DEBUG   ? POST /session/2bc4ffd4-a7fa-494f-ae23-29ed6420591c
> /url {"url":"about:addons"}
> 1493836368067   geckodriver::marionette TRACE   ? 34:[0,2,"get",{"url":"about:addons"}]
> 1493836368535   geckodriver::marionette TRACE   ? [1,2,null,{}]
> 1493836368535   webdriver::server       DEBUG   ? 200 OK {"value": {}}

**Comment by whimboo** [comment] 2017-05-05 07:06
Well, if the page doesn't load when you are not using geckodriver, then something is wrong in Firefox or something is blocking the network connection. It sounds like a good candidate to get an answer from support.mozilla.org.

Basically the remote page which should load there is controlled via the preference `extensions.webservice.discoverURL`, which by default points to `https://discovery.addons.mozilla.org/%LOCALE%/firefox/discovery/pane/%VERSION%/%OS%/%COMPATIBILITY_MODE%`. So I assume that `https://discovery.addons.mozilla.org/` doesn't really load for you.

**Comment by KSKS** [comment] 2017-05-05 15:11
Like I said in the description, this issue happens only when I start firefox with geckodriver v0.16. You asked why there wasn't a get request to `about:addons` in the log, that is because I went to that page manually in the original test scenario (in a firefox process that was started by geckodriver 0.16). But to show that it doesn't matter how I goes to that page, I also provided log where I use geckodriver to go to `about:addons`.

If I start Firefox with geckodriver v0.15, this issue does **not** happen.
If I start Firefox manually, this issue does **not** happen.

For the value of `extensions.webservice.discoverURL` it is a modified value of `http://%(server)s/dummy/discoveryURL` for Firefox that were started with either geckodriver v0.15 or v0.16, and `https://discovery.addons.mozilla.org/` doesn't load in either case.

It still looks to me that some changes between 0.15 and 0.16 in geckodriver have triggered this issue, because there is no other way I can reproduce it yet. Can we re-open this issue? The culprit might be in firefox or a dependence of geckodriver, but until we know for sure I think we should keep this issue open.

**Comment by whimboo** [comment] 2017-05-05 16:15
Oh, now I see. So yes, there was indeed a change, which modified this preference and may should not have done it for this preference at the first place. @andreastt knows more about it.

**Comment by andreastt** [comment] 2017-05-08 13:47
From the trace log above, it’s not apparent that about:addons fails to load:

```
1493836368067   webdriver::server       DEBUG   → POST /session/2bc4ffd4-a7fa-494f-ae23-29ed6420591c /url {"url":"about:addons"}
1493836368067   geckodriver::marionette TRACE   → 34:[0,2,"get",{"url":"about:addons"}]
1493836368535   geckodriver::marionette TRACE   ← [1,2,null,{}]
1493836368535   webdriver::server       DEBUG   ← 200 OK {"value": {}}
```

The `extensions.webservice.discoverURL` preference was set to `http://%(server)s/dummy/discoveryURL` as part of https://github.com/mozilla/geckodriver/commit/2bfdc3ec8151c427a6a75a6ba3ad203459540495 nearly five months ago. This was part of synchronising the preferences we use in internal Mozilla automation with those used by geckodriver.

@KSKS If I understand you correctly, if you set this preference to something else, e.g. `about:blank`, the problem goes away? I think @whimboo is correct that the problem seems to be that https://discovery.addons.mozilla.org/ doesn’t load on your environment?

**Comment by KSKS** [comment] 2017-05-08 15:34
@andreastt I didn't try to set the preference to something else before, but I just tried it based on your comment and the problem doesn't go away.

`https://discovery.addons.mozilla.org/` always redirect me to `https://discovery.addons.mozilla.org/en-US/firefox` and it always return 404 page not found there, even when I tried it from Firefox or Chrome, on either Mac or Windows, or a remote machine.

It returns 404 even on a Firefox that was started by geckodriver v0.15, but its `about:add-ons` page stills works.

**Comment by andreastt** [comment] 2017-05-08 15:46
The pref was still set to `http://%(server)s/dummy/discoveryURL` in 0.15.0, so I somewhat doubt that this is related to the version of geckodriver. It could be that the 0.16.1 release picks up a different Firefox on your system since we fixed bugs related to that.

In any case, it’s obviously not great for us to pick up a remote resource. Changing `extensions.webservice.discoverURL` to `about:blank` on my system causes the “Loading…” message on about:addons to disappear, so I wonder if we should do that instead.

**Comment by whimboo** [comment] 2017-05-08 15:53
@KSKS can you please check which value `extensions.webservice.discoverURL` has in Firefox when you run with geckodriver 0.15 and 0.16?

**Comment by KSKS** [comment] 2017-05-08 16:24
The value is `http://%(server)s/dummy/discoveryURL` for Firefox started in both geckodriver v0.15.0 and v0.16.0

**Comment by whimboo** [comment] 2017-05-08 19:12
I had a look at the latest attached trace log and I miss certain parts from it. Is this really a trace log? I asked because I cannot find any `Marionette` entries in there. Please run it again and make sure to use a latest Nightly build of Firefox.

**Comment by KSKS** [comment] 2017-05-09 04:36
I just run it again and it has similar log (below). The log I posted has entries that said `geckodriver::marionette TRACE`, are those Marionette entries? If not what do they look like? And where can I find out how to include Marionette entries?

```
1494285627650   webdriver::httpapi      DEBUG   Creating routes
1494285627666   geckodriver     INFO    Listening on 127.0.0.1:4444
1494285628181   webdriver::server       DEBUG   ? GET /status
1494285628181   webdriver::server       DEBUG   ? 200 OK {"value":{"message":"",
"ready":true}}
1494285628196   webdriver::server       DEBUG   ? POST /session {"desiredCapabil
ities":{"browserName":"firefox","nativeEvents":true,"marionette":true,"moz:firef
oxOptions":{"binary":"H:\\Program Files\\Nightly\\firefox.exe"},"loggingPrefs":{
"browser":"ALL","driver":"ALL","client":"ALL","server":"ALL"}}}
1494285628243   geckodriver::marionette INFO    Starting browser \\?\H:\Program
Files\Nightly\firefox.exe with args ["-marionette"]
1494285630269   geckodriver::marionette TRACE     connection attempt 0/600
1494285631380   geckodriver::marionette DEBUG   Connected to Marionette on local
host:53979
1494285631380   geckodriver::marionette TRACE   ? {"applicationType":"gecko","ma
rionetteProtocol":3}
1494285631380   geckodriver::marionette TRACE   ? 341:[0,1,"newSession",{"browse
rName":"firefox","capabilities":{"desiredCapabilities":{"browserName":"firefox",
"loggingPrefs":{"browser":"ALL","client":"ALL","driver":"ALL","server":"ALL"},"m
arionette":true,"nativeEvents":true}},"loggingPrefs":{"browser":"ALL","client":"
ALL","driver":"ALL","server":"ALL"},"marionette":true,"nativeEvents":true}]
1494285631458   geckodriver::marionette TRACE   ? [1,1,null,{"sessionId":"55e665
4a-7c16-4513-998e-4ed50b2f0d0e","capabilities":{"browserName":"firefox","browser
Version":"55.0a1","platformName":"windows_nt","platformVersion":"6.1","pageLoadS
trategy":"normal","acceptInsecureCerts":false,"timeouts":{"implicit":0,"pageLoad
":300000,"script":30000},"rotatable":false,"specificationLevel":0,"moz:processID
":4372,"moz:profile":"H:\\Users\\kns\\AppData\\Local\\Temp\\rust_mozprofile.Z0uH
bNwTqCy6","moz:accessibilityChecks":false}}]
1494285631458   webdriver::server       DEBUG   ? 200 OK {"value": {"sessionId":
"55e6654a-7c16-4513-998e-4ed50b2f0d0e","capabilities":{"acceptInsecureCerts":fal
se,"browserName":"firefox","browserVersion":"55.0a1","moz:accessibilityChecks":f
alse,"moz:processID":4372,"moz:profile":"H:\\Users\\kns\\AppData\\Local\\Temp\\r
ust_mozprofile.Z0uHbNwTqCy6","pageLoadStrategy":"normal","platformName":"windows
_nt","platformVersion":"6.1","rotatable":false,"specificationLevel":0,"timeouts"
:{"implicit":0,"pageLoad":300000,"script":30000}}}}
1494285631458   webdriver::server       DEBUG   ? POST /session/55e6654a-7c16-45
13-998e-4ed50b2f0d0e/url {"url":"about:addons"}
1494285631473   geckodriver::marionette TRACE   ? 34:[0,2,"get",{"url":"about:ad
dons"}]
1494285631943   geckodriver::marionette TRACE   ? [1,2,null,{}]
1494285631943   webdriver::server       DEBUG   ? 200 OK {"value": {}}
```

**Comment by whimboo** [comment] 2017-05-09 06:52
Using the Python bindings for Selenium with GeckoDriver the following entries should appear when `trace` is enabled:
```
1494270603893	Marionette	TRACE	0 -> [0,2,"get",{"url":"about:addons"}]
1494270603932	Marionette	DEBUG	Received DOM event "beforeunload" for "about:blank"
```

I don't see those in your trace log. There is nothing else you would have to specify given that geckodriver forwards it to Firefox. Can you tell us which binding you are using and which version of it?

**Comment by KSKS** [comment] 2017-05-09 14:57
I am using Javascript (webdriver.js) selenium 3.4.0.

The interesting thing is, I just used the same test script that I used to generate those logs on Windows to run on Mac, and the log is showing entires with `Marionette	TRACE`. So these Marionette logs are missing only on the Windows.

**Comment by KSKS** [comment] 2017-05-09 17:01
I narrow down when the issue occur in the commit history. With the commit 74fb9c7ffbf6aa25d59452fe64791b9ffbd8cb79, the issue didn't happen, but on 6d25d383048cbf5b38eeb786f70732be697ec0fb, the issue started showing up.

Looking at the changes between these two commits, I am guessing it happened on 6f1e3c192463342a0a49f5f3f0af914ad0e1ae7a, where the bulk of changes happened. but I can't verify for sure because that commit can't compile.

I am testing these with Firefox 53, because nightly can't connect with geckodrivers built from these older commits.

**Comment by KSKS** [comment] 2017-05-09 18:51
I just try it with geckodriver.exe running as a standalone process, connected with webdriver.js via localhost:4444, and I still don't see any log entries with `Marionette	TRACE` (it does have trace log with `geckodriver::marionette TRACE`)

**Comment by whimboo** [comment] 2017-05-09 22:02
> The interesting thing is, I just used the same test script that I used to generate those logs on Windows to run on Mac, and the log is showing entires with Marionette TRACE. So these Marionette logs are missing only on the Windows.

Interesting. Can you please file a separate issue for this? Beside that do you see the same behavior on MacOS? If yes, can you please provide the trace log from that platform instead?

**Comment by KSKS** [comment] 2017-05-10 01:17
File #730 for the log issue.

MacOS does not have the same behavior, because it does not have this issue (`about:addons` loads fine). The log is  [mac.txt](https://github.com/mozilla/geckodriver/files/988408/mac.txt) incase you want it.

**Comment by whimboo** [comment] 2017-05-10 06:30
Can you please set `extensions.webservice.discoverURL` to `about:blank` and try again? I would assume that this fixes your issue. Also setting it to the original value should work.

**Comment by andreastt** [comment] 2017-05-10 10:51
But the macOS log contains log entries from Log.jsm:

> ```
> 1494378819722    Marionette    DEBUG    loaded listener.js
> ```

**Comment by KSKS** [comment] 2017-05-10 14:36
Setting the value of `extensions.webservice.discoverURL` to either `about:blank` or `https://discovery.addons.mozilla.org/%LOCALE%/firefox/discovery/pane/%VERSION%/%OS%/%COMPATIBILITY_MODE%` does not fix the issue. I tried before, and just tried again with Firefox Nightly.

**Comment by wengoooooooo** [comment] 2017-05-11 09:54
i also have the problem

python 2.7 
firefox 52
geckodriver 0.16.1
windows 7
```python
from selenium import webdriver
driver =  webdriver.Firefox()
```

geckodriver

```
1494496355335	geckodriver	INFO	Listening on 127.0.0.1:60917
1494496355842	geckodriver::marionette	INFO	Starting browser \\?\C:\Program Files (x86)\Mozilla Firefox\firefox.exe with args ["-marionette"]
1494496356431	addons.manager	ERROR	startup failed: [Exception... "Component returned failure code: 0x80070057 (NS_ERROR_ILLEGAL_VALUE) [nsIFile.create]"  nsresult: "0x80070057 (NS_ERROR_ILLEGAL_VALUE)"  location: "JS frame :: resource://gre/modules/FileUtils.jsm :: FileUtils_getDir :: line 70"  data: no] Stack trace: FileUtils_getDir()@resource://gre/modules/FileUtils.jsm:70 < FileUtils_getFile()@resource://gre/modules/FileUtils.jsm:42 < AddonManagerInternal.validateBlocklist()@resource://gre/modules/AddonManager.jsm:700 < AddonManagerInternal.startup()@resource://gre/modules/AddonManager.jsm:870 < this.AddonManagerPrivate.startup()@resource://gre/modules/AddonManager.jsm:3033 < amManager.prototype.observe()@resource://gre/components/addonManager.js:65
JavaScript error: resource://gre/modules/AddonManager.jsm, line 1677: NS_ERROR_NOT_INITIALIZED: AddonManager is not initialized
1494496356933	Marionette	INFO	Listening on port 60921
1494496357042	Marionette	WARN	TLS certificate errors will be ignored for this session
JavaScript error: resource://gre/modules/AddonManager.jsm, line 2585: NS_ERROR_NOT_INITIALIZED: AddonManager is not initialized
JavaScript error: resource://gre/modules/AddonManager.jsm, line 2076: NS_ERROR_NOT_INITIALIZED: AddonManager is not initialized

```

**Comment by andreastt** [comment] 2017-05-15 16:40
@wengoooooooo I can’t see that that’s the same issue? You aren’t navigating to about:addons at all.

**Comment by wengoooooooo** [comment] 2017-05-16 16:11
@andreastt it's the same issue.

```python
driver = webdriver.Firefox()
driver.get("about:addons")
```
geckodriver.log
```python
1494950842046	geckodriver	INFO	Listening on 127.0.0.1:3363
1494950756287	geckodriver::marionette	INFO	Starting browser \\?\C:\Program Files (x86)\Mozilla Firefox\firefox.exe with args ["-marionette"]
1494950756752	addons.manager	DEBUG	Application has been upgraded
1494950756752	addons.manager	ERROR	startup failed: [Exception... "Component returned failure code: 0x80070057 (NS_ERROR_ILLEGAL_VALUE) [nsIFile.create]"  nsresult: "0x80070057 (NS_ERROR_ILLEGAL_VALUE)"  location: "JS frame :: resource://gre/modules/FileUtils.jsm :: FileUtils_getDir :: line 70"  data: no] Stack trace: FileUtils_getDir()@resource://gre/modules/FileUtils.jsm:70 < FileUtils_getFile()@resource://gre/modules/FileUtils.jsm:42 < validateBlocklist()@resource://gre/modules/AddonManager.jsm:671 < startup()@resource://gre/modules/AddonManager.jsm:834 < startup()@resource://gre/modules/AddonManager.jsm:3129 < observe()@resource://gre/components/addonManager.js:65
1494950756754	addons.manager	DEBUG	Completed startup sequence
JavaScript error: resource://gre/modules/AddonManager.jsm, line 1657: NS_ERROR_NOT_INITIALIZED: AddonManager is not initialized
*** Blocklist::_preloadBlocklistFile: blocklist is disabled
1494950758596	Marionette	INFO	Listening on port 3262
JavaScript error: resource://gre/modules/AddonManager.jsm, line 2570: NS_ERROR_NOT_INITIALIZED: AddonManager is not initialized
1494950759090	Marionette	WARN	TLS certificate errors will be ignored for this session
JavaScript error: resource://gre/modules/AddonManager.jsm, line 2010: NS_ERROR_NOT_INITIALIZED: AddonManager is not initialized
JavaScript error: resource://gre/modules/FileUtils.jsm, line 70: NS_ERROR_ILLEGAL_VALUE: Component returned failure code: 0x80070057 (NS_ERROR_ILLEGAL_VALUE) [nsIFile.create]
1494950818309	addons.productaddons	INFO	sending request to: https://aus5.mozilla.org/update/3/GMP/53.0.2/20170504105526/WINNT_x86-msvc-x64/zh-CN/release/Windows_NT%206.1.1.0%20(x64)/default/default/update.xml
1494950825209	addons.productaddons	INFO	Completed downloading document
1494950826635	addons.productaddons	INFO	downloadXHR File download. status=200
1494950826638	addons.productaddons	INFO	Downloaded file will be saved to C:\Users\lenovo\AppData\Local\Temp\tmpaddon
1494950832037	addons.productaddons	INFO	downloadXHR File download. status=200
1494950832040	addons.productaddons	INFO	Downloaded file will be saved to C:\Users\lenovo\AppData\Local\Temp\tmpaddon
JavaScript error: resource://app/modules/WindowsJumpLists.jsm, line 403: NS_ERROR_FILE_NOT_FOUND: Component returned failure code: 0x80520012 (NS_ERROR_FILE_NOT_FOUND) [nsIJumpListShortcut.app]
JavaScript error: resource://app/modules/WindowsJumpLists.jsm, line 403: NS_ERROR_FILE_NOT_FOUND: Component returned failure code: 0x80520012 (NS_ERROR_FILE_NOT_FOUND) [nsIJumpListShortcut.app]

```

![avatar](https://cloud.githubusercontent.com/assets/555130/25649436/69ef6968-2f8a-11e7-80a9-cd23aeebd66c.PNG)

**Comment by AutomatedTester** [comment] 2017-05-19 07:56
@wengoooooooo The Loading has nothing to do with Marionette in your last comment, it would appear it is struggling to speak to https://addons.mozilla.org. Your log doesn't show a navigation either to that site.

**Comment by whimboo** [comment] 2017-06-01 11:22
So I was able to get this reproduced. It's all because the add-on manager and other components cannot be correctly initialized. Reason is the strange path as used for starting Firefox. I will work on a fix via https://bugzilla.mozilla.org/show_bug.cgi?id=1368965.

**Comment by KSKS** [comment] 2017-06-01 14:32
This doesn't seem to be related to window handles. I assume you mean https://bugzilla.mozilla.org/show_bug.cgi?id=1364385?

**Comment by whimboo** [comment] 2017-06-01 16:10
Sorry, yes I do. Thanks for noticing that.

**Comment by cnico** [comment] 2017-06-03 14:22
I fall on this bug with the message "NS_ERROR_NOT_INITIALIZED: AddonManager is not initialized" while running webdriver 3.4.0 with firefox on windows 7.
The problem for me is that I would like to use a custom xpi extension and because of this problem, my extension is not loaded by firefox.
The problem is clearly explained in the bugzilla 1364385 in previous comment.

As a workaround, what I did is go back to an older version of geckodriver. With version 0.15.0, it works well until a correction of bug is done either in geckodriver or in firefox...

**Comment by whimboo** [comment] 2017-06-06 06:59
The fix for geckodriver landed via the before mentioned bug, and will be part of the next release of geckodriver maybe even this week.

The initially reported issue with failing to load `about:addons` is also fixed. So closing this issue.

**Closed by whimboo** 2017-06-06 06:59 UTC
Labels: marionette
