### ISSUE TITLE
Add support for setting log path

### ISSUE THREAD

**Issue by soulgalore** [mozilla/geckodriver#1813] opened 2020-11-26 12:52 UTC
Hi!
I have a feature request: I would like to have the ability to set the log path of the Geckodriver log so you could decide where the log ends up. Something like `--log-path /path/to/log`. When we use Browsertime the Geckodriver log ends up in the Browsertime log and its really hard when you need to report an issue to Geckodriver. We have tests that continuously runs 24h a day and if we have a issue, we need to turn on the log from Geckodriver on trace level and it bloats our logs and its hard to find the right log entries. If we instead could set the log output to a file, its easier to find the right logs.

Or do you think this should be implemented on the Selenium side? At the moment there you only send the logs to stdio.

**Comment by whimboo** [comment] 2020-11-26 13:40
This might actually be a good idea. In the past we faced lots of problems with users not using the most used Selenium bindings, or tools that rely on Selenium in getting the logs. By having this flag we could clearly store all the log data in a specific file. Also this would bring us in-par with chromedriver, which uses it already.

When implemented we might have to make an announcement to the Selenium project so that they can update their code to make use of this option.

**Comment by whimboo** [comment] 2020-11-26 13:44
Actually this got already filed a while ago as https://bugzilla.mozilla.org/show_bug.cgi?id=1611003.

**Comment by whimboo** [comment] 2020-11-26 13:47
And this makes this issue a dupe of issue #1568.

**Closed by whimboo** 2020-11-26 13:47 UTC
Labels: geckodriver
