### ISSUE TITLE
org.openqa.selenium.WebDriverException: TypeError: can't access dead object

### ISSUE THREAD

**Issue by Naumansh** [mozilla/geckodriver#1715] opened 2020-04-27 21:50 UTC
## System

* Version: 0.26.0
*
[trace_level_logs.zip](https://github.com/mozilla/geckodriver/files/4542154/trace_level_logs.zip)

 Platform: mac os Mojave
* Firefox: 75
* Selenium: 3.124

## Testcase

This issue is random and comes up any time even if the page is properly loaded. I am using salesforce platform. And never faced any such issue on any of the other browsers. 

## Stacktrace
org.openqa.selenium.WebDriverException: TypeError: can't access dead object
Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:17:03'
System info: host: 'C02XT4NLJGH5.local', ip: 'fe80:0:0:0:8ab:fd22:24e0:24b3%en0', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.14.6', java.version: '11.0.5'
Driver info: org.openqa.selenium.firefox.FirefoxDriver
Capabilities {acceptInsecureCerts: true, browserName: firefox, browserVersion: 75.0, javascriptEnabled: true, moz:accessibilityChecks: false, moz:buildID: 20200403170909, moz:geckodriverVersion: 0.26.0, moz:headless: false, moz:processID: 88991, moz:profile: /var/folders/gh/7vpfcz1s0bj..., moz:shutdownTimeout: 60000, moz:useNonSpecCompliantPointerOrigin: false, moz:webdriverClick: true, pageLoadStrategy: none, platform: MAC, platformName: MAC, platformVersion: 18.7.0, rotatable: false, setWindowRect: true, strictFileInteractability: false, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}, unhandledPromptBehavior: dismiss and notify}
Session ID: 18e5150c-246b-e64b-93af-4d9efa666d51
*** Element info: {Using=xpath, value=//div[@id='holdon-overlay'] | //div[@class='rowLevelOverlay']}
        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
        at org.openqa.selenium.remote.http.W3CHttpResponseCodec.createException(W3CHttpResponseCodec.java:187)
        at org.openqa.selenium.remote.http.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:122)
        at org.openqa.selenium.remote.http.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:49)
        at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:158)
        at org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:83)
        at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:552)
        at org.openqa.selenium.remote.RemoteWebDriver.findElements(RemoteWebDriver.java:353)
        at org.openqa.selenium.remote.RemoteWebDriver.findElementsByXPath(RemoteWebDriver.java:432)
        at org.openqa.selenium.By$ByXPath.findElements(By.java:348)
        at org.openqa.selenium.remote.RemoteWebDriver.findElements(RemoteWebDriver.java:311)

## Trace-level log
[trace_level_logs.zip](https://github.com/mozilla/geckodriver/files/4542156/trace_level_logs.zip)

Logs attached

**Comment by Naumansh** [comment] 2020-04-29 03:22
Adding another log:

Running Step: I navigate to "Roles" sub tab

1588130536860	webdriver::server	DEBUG	-> GET /session/4381f8b0-9347-0c44-907e-7b421a8bad3c/alert/text
1588130536861	Marionette	TRACE	0 -> [0,8967,"WebDriver:GetAlertText",{}]
1588130536862	Marionette	TRACE	0 <- [1,8967,{"error":"no such alert","message":"No modal dialog is currently open","stacktrace":"WebDriverError@chrome://marionet ... et@chrome://marionette/content/server.js:242:8\n_onJSONObjectReady/<@chrome://marionette/content/transport.js:500:9\n"},null]
1588130536862	webdriver::server	DEBUG	<- 404 Not Found {"value":{"error":"no such alert","message":"No modal dialog is currently open","stacktrace":"WebDriverError@chrome://marionette/content/error.js:178:5\nNoSuchAlertError@chrome://marionette/content/error.js:377:5\nGeckoDriver.prototype._checkIfAlertIsPresent@chrome://marionette/content/driver.js:3179:11\nGeckoDriver.prototype.getTextFromDialog@chrome://marionette/content/driver.js:3142:3\ndespatch@chrome://marionette/content/server.js:294:20\nexecute@chrome://marionette/content/server.js:268:11\nonPacket/<@chrome://marionette/content/server.js:243:15\nonPacket@chrome://marionette/content/server.js:242:8\n_onJSONObjectReady/<@chrome://marionette/content/transport.js:500:9\n"}}
1588130536865	webdriver::server	DEBUG	-> POST /session/4381f8b0-9347-0c44-907e-7b421a8bad3c/execute/sync {
  "script": "return document.readyState",
  "args": [
  ]
}
1588130536866	Marionette	TRACE	0 -> [0,8968,"WebDriver:ExecuteScript",{"args":[],"newSandbox":false,"script":"return document.readyState","scriptTimeout":null,"specialPowers":false}]
1588130536867	Marionette	TRACE	0 <- [1,8968,{"error":"unknown error","message":"TypeError: can't access dead object","stacktrace":"sandbox.create@chrome://marion ... ch/</req<@chrome://marionette/content/listener.js:489:14\ndispatch/<@chrome://marionette/content/listener.js:484:15\n"},null]
1588130536868	webdriver::server	DEBUG	<- 500 Internal Server Error {"value":{"error":"unknown error","message":"TypeError: can't access dead object","stacktrace":"sandbox.create@chrome://marionette/content/evaluate.js:396:10\nsandbox.createMutable@chrome://marionette/content/evaluate.js:414:10\nexecute@chrome://marionette/content/listener.js:672:12\ndispatch/</req<@chrome://marionette/content/listener.js:489:14\ndispatch/<@chrome://marionette/content/listener.js:484:15\n"}}
1588130537073	webdriver::server	DEBUG	-> POST /session/4381f8b0-9347-0c44-907e-7b421a8bad3c/execute/sync {
  "script": "return document.readyState",
  "args": [
  ]
}
1588130537073	Marionette	TRACE	0 -> [0,8969,"WebDriver:ExecuteScript",{"args":[],"newSandbox":false,"script":"return document.readyState","scriptTimeout":null,"specialPowers":false}]
1588130537075	Marionette	TRACE	0 <- [1,8969,{"error":"unknown error","message":"TypeError: can't access dead object","stacktrace":"sandbox.create@chrome://marion ... ch/</req<@chrome://marionette/content/listener.js:489:14\ndispatch/<@chrome://marionette/content/listener.js:484:15\n"},null]
1588130537076	webdriver::server	DEBUG	<- 500 Internal Server Error {"value":{"error":"unknown error","message":"TypeError: can't access dead object","stacktrace":"sandbox.create@chrome://marionette/content/evaluate.js:396:10\nsandbox.createMutable@chrome://marionette/content/evaluate.js:414:10\nexecute@chrome://marionette/content/listener.js:672:12\ndispatch/</req<@chrome://marionette/content/listener.js:489:14\ndispatch/<@chrome://marionette/content/listener.js:484:15\n"}}
1588130537283	webdriver::server	DEBUG	-> POST /session/4381f8b0-9347-0c44-907e-7b421a8bad3c/elements {
  "value": " \u002f\u002ful[@id='topTabsID']\u002f\u002fli[contains(@class,'active')]",
  "using": "xpath"
}
1588130537283	Marionette	TRACE	0 -> [0,8970,"WebDriver:FindElements",{"using":"xpath","value":" //ul[@id='topTabsID']//li[contains(@class,'active')]"}]
1588130537514	Marionette	TRACE	0 <- [1,8970,{"error":"unknown error","message":"TypeError: can't access dead object","stacktrace":"find_@chrome://marionette/cont ... ch/</req<@chrome://marionette/content/listener.js:489:14\ndispatch/<@chrome://marionette/content/listener.js:484:15\n"},null]
1588130537515	webdriver::server	DEBUG	<- 500 Internal Server Error {"value":{"error":"unknown error","message":"TypeError: can't access dead object","stacktrace":"find_@chrome://marionette/content/element.js:354:7\nelement.find/</findElements<@chrome://marionette/content/element.js:317:17\nevalFn@chrome://marionette/content/sync.js:97:7\nPollPromise/<@chrome://marionette/content/sync.js:112:5\nPollPromise@chrome://marionette/content/sync.js:92:10\nelement.find/<@chrome://marionette/content/element.js:316:24\nelement.find@chrome://marionette/content/element.js:315:10\nfindElementsContent@chrome://marionette/content/listener.js:1170:19\ndispatch/</req<@chrome://marionette/content/listener.js:489:14\ndispatch/<@chrome://marionette/content/listener.js:484:15\n"}}
1588130537517	webdriver::server	DEBUG	-> POST /session/4381f8b0-9347-0c44-907e-7b421a8bad3c/element {
  "value": " \u002f\u002fdiv[@id='myTabs']\u002f\u002fspan[text()='More Tabs']\u002fancestor::li[1]",
  "using": "xpath"
}
1588130537519	Marionette	TRACE	0 -> [0,8971,"WebDriver:FindElement",{"using":"xpath","value":" //div[@id='myTabs']//span[text()='More Tabs']/ancestor::li[1]"}]
1588130537523	Marionette	TRACE	0 <- [1,8971,{"error":"unknown error","message":"TypeError: can't access dead object","stacktrace":"find_@chrome://marionette/cont ... ch/</req<@chrome://marionette/content/listener.js:489:14\ndispatch/<@chrome://marionette/content/listener.js:484:15\n"},null]
1588130537524	webdriver::server	DEBUG	<- 500 Internal Server Error {"value":{"error":"unknown error","message":"TypeError: can't access dead object","stacktrace":"find_@chrome://marionette/content/element.js:354:7\nelement.find/</findElements<@chrome://marionette/content/element.js:317:17\nevalFn@chrome://marionette/content/sync.js:97:7\nPollPromise/<@chrome://marionette/content/sync.js:112:5\nPollPromise@chrome://marionette/content/sync.js:92:10\nelement.find/<@chrome://marionette/content/element.js:316:24\nelement.find@chrome://marionette/content/element.js:315:10\nfindElementContent@chrome://marionette/content/listener.js:1156:18\ndispatch/</req<@chrome://marionette/content/listener.js:489:14\ndispatch/<@chrome://marionette/content/listener.js:484:15\n"}}
1588130537525	webdriver::server	DEBUG	-> GET /session/4381f8b0-9347-0c44-907e-7b421a8bad3c/alert/text
1588130537526	Marionette	TRACE	0 -> [0,8972,"WebDriver:GetAlertText",{}]
1588130537526	Marionette	TRACE	0 <- [1,8972,{"error":"no such alert","message":"No modal dialog is currently open","stacktrace":"WebDriverError@chrome://marionet ... et@chrome://marionette/content/server.js:242:8\n_onJSONObjectReady/<@chrome://marionette/content/transport.js:500:9\n"},null]
1588130537526	webdriver::server	DEBUG	<- 404 Not Found {"value":{"error":"no such alert","message":"No modal dialog is currently open","stacktrace":"WebDriverError@chrome://marionette/content/error.js:178:5\nNoSuchAlertError@chrome://marionette/content/error.js:377:5\nGeckoDriver.prototype._checkIfAlertIsPresent@chrome://marionette/content/driver.js:3179:11\nGeckoDriver.prototype.getTextFromDialog@chrome://marionette/content/driver.js:3142:3\ndespatch@chrome://marionette/content/server.js:294:20\nexecute@chrome://marionette/content/server.js:268:11\nonPacket/<@chrome://marionette/content/server.js:243:15\nonPacket@chrome://marionette/content/server.js:242:8\n_onJSONObjectReady/<@chrome://marionette/content/transport.js:500:9\n"}}
1588130537528	webdriver::server	DEBUG	-> POST /session/4381f8b0-9347-0c44-907e-7b421a8bad3c/execute/sync {
  "script": "return document.readyState",
  "args": [
  ]
}
1588130537530	Marionette	TRACE	0 -> [0,8973,"WebDriver:ExecuteScript",{"args":[],"newSandbox":false,"script":"return document.readyState","scriptTimeout":null,"specialPowers":false}]
1588130537531	Marionette	TRACE	0 <- [1,8973,{"error":"unknown error","message":"TypeError: can't access dead object","stacktrace":"sandbox.create@chrome://marion ... ch/</req<@chrome://marionette/content/listener.js:489:14\ndispatch/<@chrome://marionette/content/listener.js:484:15\n"},null]
1588130537532	webdriver::server	DEBUG	<- 500 Internal Server Error {"value":{"error":"unknown error","message":"TypeError: can't access dead object","stacktrace":"sandbox.create@chrome://marionette/content/evaluate.js:396:10\nsandbox.createMutable@chrome://marionette/content/evaluate.js:414:10\nexecute@chrome://marionette/content/listener.js:672:12\ndispatch/</req<@chrome://marionette/content/listener.js:489:14\ndispatch/<@chrome://marionette/content/listener.js:484:15\n"}}
1588130537737	webdriver::server	DEBUG	-> POST /session/4381f8b0-9347-0c44-907e-7b421a8bad3c/execute/sync {
  "script": "return document.readyState",
  "args": [
  ]
}
1588130537738	Marionette	TRACE	0 -> [0,8974,"WebDriver:ExecuteScript",{"args":[],"newSandbox":false,"script":"return document.readyState","scriptTimeout":null,"specialPowers":false}]
1588130537834	Marionette	TRACE	0 <- [1,8974,{"error":"unknown error","message":"TypeError: can't access dead object","stacktrace":"sandbox.create@chrome://marion ... ch/</req<@chrome://marionette/content/listener.js:489:14\ndispatch/<@chrome://marionette/content/listener.js:484:15\n"},null]
1588130537835	webdriver::server	DEBUG	<- 500 Internal Server Error {"value":{"error":"unknown error","message":"TypeError: can't access dead object","stacktrace":"sandbox.create@chrome://marionette/content/evaluate.js:396:10\nsandbox.createMutable@chrome://marionette/content/evaluate.js:414:10\nexecute@chrome://marionette/content/listener.js:672:12\ndispatch/</req<@chrome://marionette/content/listener.js:489:14\ndispatch/<@chrome://marionette/content/listener.js:484:15\n"}}
1588130538039	webdriver::server	DEBUG	-> POST /session/4381f8b0-9347-0c44-907e-7b421a8bad3c/elements {
  "value": " \u002f\u002fdiv[@id='myTabs']\u002f\u002fspan[normalize-space(translate(text(), 'ABCDEFGHIJKLMNOPQRSTUVWXYZ ' , 'abcdefghijklmnopqrstuvwxyz '))=normalize-space(translate('Roles', 'ABCDEFGHIJKLMNOPQRSTUVWXYZ ' , 'abcdefghijklmnopqrstuvwxyz '))]\u002fancestor::li[1]\u002fa",
  "using": "xpath"
}
1588130538039	Marionette	TRACE	0 -> [0,8975,"WebDriver:FindElements",{"using":"xpath","value":" //div[@id='myTabs']//span[normalize-space(translate(text(), 'ABCD ...  '))=normalize-space(translate('Roles', 'ABCDEFGHIJKLMNOPQRSTUVWXYZ ' , 'abcdefghijklmnopqrstuvwxyz '))]/ancestor::li[1]/a"}]
1588130538042	Marionette	TRACE	0 <- [1,8975,{"error":"unknown error","message":"TypeError: can't access dead object","stacktrace":"find_@chrome://marionette/cont ... ch/</req<@chrome://marionette/content/listener.js:489:14\ndispatch/<@chrome://marionette/content/listener.js:484:15\n"},null]
1588130538042	webdriver::server	DEBUG	<- 500 Internal Server Error {"value":{"error":"unknown error","message":"TypeError: can't access dead object","stacktrace":"find_@chrome://marionette/content/element.js:354:7\nelement.find/</findElements<@chrome://marionette/content/element.js:317:17\nevalFn@chrome://marionette/content/sync.js:97:7\nPollPromise/<@chrome://marionette/content/sync.js:112:5\nPollPromise@chrome://marionette/content/sync.js:92:10\nelement.find/<@chrome://marionette/content/element.js:316:24\nelement.find@chrome://marionette/content/element.js:315:10\nfindElementsContent@chrome://marionette/content/listener.js:1170:19\ndispatch/</req<@chrome://marionette/content/listener.js:489:14\ndispatch/<@chrome://marionette/content/listener.js:484:15\n"}}
1588130538547	webdriver::server	DEBUG	-> POST /session/4381f8b0-9347-0c44-907e-7b421a8bad3c/element {
  "value": " \u002f\u002fdiv[@id='myTabs']\u002f\u002fspan[normalize-space(translate(text(), 'ABCDEFGHIJKLMNOPQRSTUVWXYZ ' , 'abcdefghijklmnopqrstuvwxyz '))=normalize-space(translate('Roles', 'ABCDEFGHIJKLMNOPQRSTUVWXYZ ' , 'abcdefghijklmnopqrstuvwxyz '))]\u002fancestor::li[1]\u002fa",
  "using": "xpath"
}
1588130538547	Marionette	TRACE	0 -> [0,8976,"WebDriver:FindElement",{"using":"xpath","value":" //div[@id='myTabs']//span[normalize-space(translate(text(), 'ABCDE ...  '))=normalize-space(translate('Roles', 'ABCDEFGHIJKLMNOPQRSTUVWXYZ ' , 'abcdefghijklmnopqrstuvwxyz '))]/ancestor::li[1]/a"}]
1588130539188	Marionette	TRACE	0 <- [1,8976,{"error":"unknown error","message":"TypeError: can't access dead object","stacktrace":"find_@chrome://marionette/cont ... ch/</req<@chrome://marionette/content/listener.js:489:14\ndispatch/<@chrome://marionette/content/listener.js:484:15\n"},null]
1588130539189	webdriver::server	DEBUG	<- 500 Internal Server Error {"value":{"error":"unknown error","message":"TypeError: can't access dead object","stacktrace":"find_@chrome://marionette/content/element.js:354:7\nelement.find/</findElements<@chrome://marionette/content/element.js:317:17\nevalFn@chrome://marionette/content/sync.js:97:7\nPollPromise/<@chrome://marionette/content/sync.js:112:5\nPollPromise@chrome://marionette/content/sync.js:92:10\nelement.find/<@chrome://marionette/content/element.js:316:24\nelement.find@chrome://marionette/content/element.js:315:10\nfindElementContent@chrome://marionette/content/listener.js:1156:18\ndispatch/</req<@chrome://marionette/content/listener.js:489:14\ndispatch/<@chrome://marionette/content/listener.js:484:15\n"}}
1588130539192	webdriver::server	DEBUG	-> POST /session/4381f8b0-9347-0c44-907e-7b421a8bad3c/element {
  "value": " \u002f\u002fdiv[@id='myTabs']\u002f\u002fspan[normalize-space(translate(text(), 'ABCDEFGHIJKLMNOPQRSTUVWXYZ ' , 'abcdefghijklmnopqrstuvwxyz '))=normalize-space(translate('Roles', 'ABCDEFGHIJKLMNOPQRSTUVWXYZ ' , 'abcdefghijklmnopqrstuvwxyz '))]\u002fancestor::li[1][contains(@class,'active')]",
  "using": "xpath"
}
1588130539192	Marionette	TRACE	0 -> [0,8977,"WebDriver:FindElement",{"using":"xpath","value":" //div[@id='myTabs']//span[normalize-space(translate(text(), 'ABCDE ... slate('Roles', 'ABCDEFGHIJKLMNOPQRSTUVWXYZ ' , 'abcdefghijklmnopqrstuvwxyz '))]/ancestor::li[1][contains(@class,'active')]"}]
1588130539219	Marionette	TRACE	0 <- [1,8977,{"error":"unknown error","message":"TypeError: can't access dead object","stacktrace":"find_@chrome://marionette/cont ... ch/</req<@chrome://marionette/content/listener.js:489:14\ndispatch/<@chrome://marionette/content/listener.js:484:15\n"},null]
1588130539221	webdriver::server	DEBUG	<- 500 Internal Server Error {"value":{"error":"unknown error","message":"TypeError: can't access dead object","stacktrace":"find_@chrome://marionette/content/element.js:354:7\nelement.find/</findElements<@chrome://marionette/content/element.js:317:17\nevalFn@chrome://marionette/content/sync.js:97:7\nPollPromise/<@chrome://marionette/content/sync.js:112:5\nPollPromise@chrome://marionette/content/sync.js:92:10\nelement.find/<@chrome://marionette/content/element.js:316:24\nelement.find@chrome://marionette/content/element.js:315:10\nfindElementContent@chrome://marionette/content/listener.js:1156:18\ndispatch/</req<@chrome://marionette/content/listener.js:489:14\ndispatch/<@chrome://marionette/content/listener.js:484:15\n"}}
1588130539224	webdriver::server	DEBUG	-> POST /session/4381f8b0-9347-0c44-907e-7b421a8bad3c/element {
  "value": " \u002f\u002fdiv[@id='myTabs']\u002f\u002fspan[normalize-space(translate(text(), 'ABCDEFGHIJKLMNOPQRSTUVWXYZ ' , 'abcdefghijklmnopqrstuvwxyz '))=normalize-space(translate('Roles', 'ABCDEFGHIJKLMNOPQRSTUVWXYZ ' , 'abcdefghijklmnopqrstuvwxyz '))]\u002fancestor::li[1]\u002fa",
  "using": "xpath"
}
1588130539226	Marionette	TRACE	0 -> [0,8978,"WebDriver:FindElement",{"using":"xpath","value":" //div[@id='myTabs']//span[normalize-space(translate(text(), 'ABCDE ...  '))=normalize-space(translate('Roles', 'ABCDEFGHIJKLMNOPQRSTUVWXYZ ' , 'abcdefghijklmnopqrstuvwxyz '))]/ancestor::li[1]/a"}]
1588130539432	Marionette	TRACE	0 <- [1,8978,{"error":"unknown error","message":"TypeError: can't access dead object","stacktrace":"find_@chrome://marionette/cont ... ch/</req<@chrome://marionette/content/listener.js:489:14\ndispatch/<@chrome://marionette/content/listener.js:484:15\n"},null]
1588130539432	webdriver::server	DEBUG	<- 500 Internal Server Error {"value":{"error":"unknown error","message":"TypeError: can't access dead object","stacktrace":"find_@chrome://marionette/content/element.js:354:7\nelement.find/</findElements<@chrome://marionette/content/element.js:317:17\nevalFn@chrome://marionette/content/sync.js:97:7\nPollPromise/<@chrome://marionette/content/sync.js:112:5\nPollPromise@chrome://marionette/content/sync.js:92:10\nelement.find/<@chrome://marionette/content/element.js:316:24\nelement.find@chrome://marionette/content/element.js:315:10\nfindElementContent@chrome://marionette/content/listener.js:1156:18\ndispatch/</req<@chrome://marionette/content/listener.js:489:14\ndispatch/<@chrome://marionette/content/listener.js:484:15\n"}}
java.lang.IndexOutOfBoundsException: Index 1 out of bounds for length 1
	at java.base/jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:64)
	at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:70)
	at java.base/jdk.internal.util.Preconditions.checkIndex(Preconditions.java:248)
	at java.base/java.util.Objects.checkIndex(Objects.java:372)
	at java.base/java.util.ArrayList.get(ArrayList.java:458)
	at com.framework.automation.projectmanager.ProjectWebServices.executeDefaultConfigurations(ProjectWebServices.java:234)
	at com.framework.automation.projectmanager.ProjectWebServices.callRelevantConfiguration(ProjectWebServices.java:210)
	at com.framework.automation.projectmanager.ProjectWebServices.lambda$postDefaultConfigCall$0(ProjectWebServices.java:196)
	at java.base/java.util.HashMap$KeySpliterator.forEachRemaining(HashMap.java:1603)
	at java.base/java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:658)
	at com.framework.automation.projectmanager.ProjectWebServices.postDefaultConfigCall(ProjectWebServices.java:196)
	at com.framework.automation.steps.setup.wrapUp(setup.java:45)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at io.cucumber.java.Invoker.invoke(Invoker.java:27)
	at io.cucumber.java.JavaHookDefinition.execute(JavaHookDefinition.java:61)
	at io.cucumber.core.runner.CoreHookDefinition.execute(CoreHookDefinition.java:31)
	at io.cucumber.core.runner.HookDefinitionMatch.runStep(HookDefinitionMatch.java:20)
	at io.cucumber.core.runner.TestStep.executeStep(TestStep.java:64)
	at io.cucumber.core.runner.TestStep.run(TestStep.java:49)
	at io.cucumber.core.runner.TestCase.run(TestCase.java:55)
	at io.cucumber.core.runner.Runner.runPickle(Runner.java:66)
	at io.cucumber.junit.PickleRunners$NoStepDescriptions.run(PickleRunners.java:149)
	at io.cucumber.junit.FeatureRunner.runChild(FeatureRunner.java:83)
	at io.cucumber.junit.FeatureRunner.runChild(FeatureRunner.java:24)
	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:330)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:78)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:328)
	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:65)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:292)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:305)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:412)
	at io.cucumber.junit.Cucumber.runChild(Cucumber.java:185)
	at io.cucumber.junit.Cucumber.runChild(Cucumber.java:83)
	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:330)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:78)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:328)
	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:65)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:292)
	at io.cucumber.junit.Cucumber$RunCucumber.evaluate(Cucumber.java:219)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:305)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:412)
	at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:365)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeWithRerun(JUnit4Provider.java:273)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:238)
	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:159)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:384)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:345)
	at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:126)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:418)

Suite Execution Summary:
Successful / Failed / Total scenarios: 0 / 1 / 1

1588130539448	webdriver::server	DEBUG	-> GET /session/4381f8b0-9347-0c44-907e-7b421a8bad3c/screenshot
1588130539449	Marionette	TRACE	0 -> [0,8979,"WebDriver:TakeScreenshot",{"full":false,"highlights":[],"id":null}]
1588130539558	Marionette	TRACE	0 <- [1,8979,{"error":"unknown error","message":"TypeError: can't access dead object","stacktrace":"capture.viewport@chrome://mari ... ch/</req<@chrome://marionette/content/listener.js:489:14\ndispatch/<@chrome://marionette/content/listener.js:484:15\n"},null]
1588130539559	webdriver::server	DEBUG	<- 500 Internal Server Error {"value":{"error":"unknown error","message":"TypeError: can't access dead object","stacktrace":"capture.viewport@chrome://marionette/content/capture.js:70:7\ntakeScreenshot@chrome://marionette/content/listener.js:1547:14\ndispatch/</req<@chrome://marionette/content/listener.js:489:14\ndispatch/<@chrome://marionette/content/listener.js:484:15\n"}}
1588130539562	webdriver::server	DEBUG	-> DELETE /session/4381f8b0-9347-0c44-907e-7b421a8bad3c/cookie
1588130539562	Marionette	TRACE	0 -> [0,8980,"WebDriver:DeleteAllCookies",{}]
1588130539567	Marionette	TRACE	0 <- [1,8980,null,{}]
1588130539567	webdriver::server	DEBUG	<- 200 OK {"value": null}
1588130539569	webdriver::server	DEBUG	-> DELETE /session/4381f8b0-9347-0c44-907e-7b421a8bad3c
1588130539570	Marionette	TRACE	0 -> [0,8981,"Marionette:Quit",{"flags":["eForceQuit"]}]
1588130539570	Marionette	DEBUG	New connections will no longer be accepted
1588130539632	Marionette	TRACE	0 <- [1,8981,null,{"cause":"shutdown"}]
1588130539652	webdriver::server	DEBUG	Deleting session
1588130539687	Marionette	TRACE	0 -> [0,8982,"Marionette:Quit",{"flags":["eForceQuit"]}]
1588130539688	Marionette	TRACE	0 <- [1,8982,{"error":"invalid session id","message":"","stacktrace":"WebDriverError@chrome://marionette/content/error.js:178:5\nI ... et@chrome://marionette/content/server.js:242:8\n_onJSONObjectReady/<@chrome://marionette/content/transport.js:500:9\n"},null]
1588130539688	Marionette	DEBUG	Closed connection 0
1588130539776	Marionette	DEBUG	Received observer notification xpcom-will-shutdown
1588130539776	Marionette	DEBUG	Resetting recommended pref apz.content_response_timeout
1588130539776	Marionette	DEBUG	Resetting recommended pref browser.download.panel.shown
1588130539777	Marionette	DEBUG	Resetting recommended pref browser.pagethumbnails.capturing_disabled
1588130539777	Marionette	DEBUG	Resetting recommended pref toolkit.cosmeticAnimations.enabled
1588130539777	Marionette	DEBUG	Resetting recommended pref browser.tabs.disableBackgroundZombification
1588130539777	Marionette	DEBUG	Resetting recommended pref browser.tabs.warnOnCloseOtherTabs
1588130539777	Marionette	DEBUG	Resetting recommended pref browser.urlbar.suggest.searches
1588130539777	Marionette	DEBUG	Resetting recommended pref datareporting.policy.dataSubmissionPolicyAccepted
1588130539777	Marionette	DEBUG	Resetting recommended pref dom.disable_beforeunload
1588130539778	Marionette	DEBUG	Resetting recommended pref dom.file.createInChild
1588130539778	Marionette	DEBUG	Resetting recommended pref extensions.getAddons.cache.enabled
1588130539778	Marionette	DEBUG	Resetting recommended pref extensions.webservice.discoverURL
1588130539778	Marionette	DEBUG	Resetting recommended pref network.http.prompt-temp-redirect
1588130539778	Marionette	DEBUG	Resetting recommended pref network.http.speculative-parallel-limit
1588130539778	Marionette	DEBUG	Resetting recommended pref security.notification_enable_delay
1588130539778	Marionette	DEBUG	Resetting recommended pref signon.autofillForms
1588130539990	geckodriver::marionette	DEBUG	Browser process stopped: exit code: 0
1588130540077	webdriver::server	DEBUG	<- 200 OK {"value": null}

**Comment by whimboo** [comment] 2020-04-29 14:37
Thanks for the report. Given the lack of a test case are you switching between frames when this `TypeError` is thrown?

Also please do not add those huge trace logs as comment, it makes issues unreadable. Thanks.

**Comment by whimboo** [comment] 2020-04-29 14:43
So the trace log actually shows usages of frames, so is the frame you are interacting with removed before the `executeScript` call? I think that this is a dupe of issue #614.

**Comment by Naumansh** [comment] 2020-04-29 17:04
@whimboo  So the frame switching is already kept in a try catch block and i do not what more can be done to avoid it.  I observed that it usually happens when there is any page on which the page loading status is not returned appropriately by the javascript. So i assume there is a problem in any javascript execution.

**Comment by Naumansh** [comment] 2020-04-29 17:18
Adding another log for your reference
[lofs_ff.zip](https://github.com/mozilla/geckodriver/files/4553242/lofs_ff.zip)

**Comment by whimboo** [comment] 2020-04-30 08:21
Consider the following situation.. The test switches to a frame which gets unloaded due to some activity. It means the reference to it is invalid and that as long as you don't switch to the parent or top frame. So when do you call `execute_script`? Can you be sure that the frame as selected is still valid? What if you run other methods before `execute_script`? Do those not fail?

**Comment by Naumansh** [comment] 2020-04-30 20:04
Thanks for the response @whimboo 
i agree with what you are saying. thats the issue. But why don't we have a standard selenium exception of no such element or an empty list of elements in return ? is there any plan to atleast return an empty list for findElements instead of this exceptioon ?

**Comment by whimboo** [comment] 2020-05-04 12:47
No we should return a `no such window` error, if the underlying frame is no longer present. You will have to manually switch to the new or top / parent frame.

I will mark this issue as dupe of #614.

**Closed by whimboo** 2020-05-04 12:47 UTC
