### ISSUE TITLE
KeyboardEvent.Key is allways empty

### ISSUE THREAD

**Issue by kornelf** [mozilla/geckodriver#169] opened 2016-08-10 10:30 UTC
SendKeys generates browser events (onKeyPress, onKeyDown etc.) with missing field 'KeyboardEvent.Key' in it.

**Comment by kornelf** [comment] 2016-08-10 10:32
Same issue is in chromedriver.
Link with description and reproduction test.
https://bugs.chromium.org/p/chromedriver/issues/detail?id=1411#c2

**Comment by andreastt** [comment] 2017-01-04 08:02
Closing this as a duplicate of https://github.com/mozilla/geckodriver/issues/348.

**Closed by andreastt** 2017-01-04 08:02 UTC
Labels: marionette
