### ISSUE TITLE
Can't interact with injected MutationObserver

### ISSUE THREAD

**Issue by Mayestril** [mozilla/geckodriver#364] opened 2016-11-25 15:52 UTC
I'm injecting a MutationObserver object while running a selenium test, and upon trying to interact with the object I get: 
`WebDriverException: Message: ReferenceError: mutationObserver is not defined`

[Gist with MutationObserver.js and the python class where it's initialized](https://gist.github.com/BeyondEvil/9a8e8910252b568c0fb88b65e74d6cf7)

`self._driver.execute_sync_script(script)` is just calling execute_script()

Selenium version - 3.0.1 (python)
Firefox version - 48+
geckodriver version:- v0.11.1

**Comment by AutomatedTester** [comment] 2016-11-28 14:49
can you give a reduced test case, the gist unfortunately has missing pieces of code that if I try to just run it, it fails.

**Comment by Mayestril** [comment] 2016-11-29 09:27
Certainly, here's a gist with a simple test case that gives me the same error as above.

https://gist.github.com/Mayestril/34085c767c8bea46a418cb6d801f519e

**Comment by amitbhoraniya** [comment] 2016-12-20 14:11
@Mayestril Did you find any workaround on this? I am facing the same issue.

**Comment by Mayestril** [comment] 2017-01-20 08:02
@amitbhoraniya Nope. I actually stopped using it this way, and after asking around a bit it seemed that the community was against using this method anyway. So I guess my workaround was just to solve the problem by dropping it entirely.

**Comment by whimboo** [comment] 2019-01-30 09:15
I'm sure this is just a dupe of issue #1067.

**Closed by whimboo** 2019-01-30 09:15 UTC
Labels: marionette
