### ISSUE TITLE
selenium tests fail if firefox runs in background and another browser is in foreground(for example Chrome)

### ISSUE THREAD

**Issue by Gerald94** [mozilla/geckodriver#2044] opened 2022-09-08 14:55 UTC
## System

* Version:  0.31.0
* Platform:  Windows
* Firefox:  104.0.2
* Selenium: 3.141

If have the problem that my selenium tests can not run in firefox background, i get an TimeoutException, if the test runs in foreground, everything is good.

Has anyone else the same problem?

**Comment by whimboo** [comment] 2022-09-08 18:24
Is that a new issue starting with Firefox 104? Or did it also happen before? It would be good if you could attach a [trace log from geckodriver](https://firefox-source-docs.mozilla.org/testing/geckodriver/TraceLogs.html)

**Comment by whimboo** [comment] 2022-09-08 18:25
Maybe a duplicate of #2040.

**Comment by Gerald94** [comment] 2022-09-08 18:59
> Is that a new issue starting with Firefox 104? Or did it also happen before? It would be good if you could attach a [trace log from geckodriver](https://firefox-source-docs.mozilla.org/testing/geckodriver/TraceLogs.html)

It did also happen with version 103, i will attach a trace log from geckodriver tomorrow, but it seems that it is exactly the same issue from #2040

**Comment by whimboo** [comment] 2022-09-08 20:01
Ok, so lets dupe this issue against #2040 then. Once you have a trace log please attach it over there. Thanks!

**Closed by whimboo** 2022-09-08 20:01 UTC
Labels: awaiting reporter feedback
