### ISSUE TITLE
Geckodriver is not working for Actions class

### ISSUE THREAD

**Issue by sharshasaitala** [mozilla/geckodriver#429] opened 2017-01-11 17:35 UTC
Please find the below etails which i am using.
## Firefox Version
50.1.0
Platform:Windows8 64 bit

## Steps to reproduce -
Steps to reproduce the problem, 

I am trying to automate flipkart.
Below is my code.
package flipkart;

import java.util.concurrent.TimeUnit;

import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.interactions.Actions;

public class Flipkart {
	
	
	
	public static void main(String[] args) throws Exception {
		System.setProperty("webdriver.gecko.driver", "C:\\Users\\Downloads\\geckodriver.exe");
		WebDriver driver = new FirefoxDriver();
		driver.manage().window().maximize();
		driver.manage().timeouts().implicitlyWait(1000, TimeUnit.SECONDS);
		driver.get("https://www.flipkart.com/");
		//WebElement dri =driver.findElement(By.linkText("Electronics"));
		//driver.findElement(By.linkText("Samsung")).click();
		Actions a = new Actions(driver);

		Thread.sleep(1000);
		driver.findElement(By.linkText("Electronics")).click();
		a.moveToElement(driver.findElement(By.linkText("Electronics"))).build().perform();
		   //a.moveToElement(driver.findElement(By.xpath("//span[text()='Electronics']"))).build().perform();
		Thread.sleep(1000);
		}

}

xxxxxxxxxxxxxxxxxxxxx

In the above I am trying to click on Electronics and wanted to perform actions on that. But not able to do that.
 I am getting the below error.
Jan 11, 2017 11:34:13 AM org.openqa.selenium.remote.ProtocolHandshake createSession
INFO: Attempting bi-dialect session, assuming Postel's Law holds true on the remote end
1484156054930	Marionette	INFO	Listening on port 64457
Jan 11, 2017 11:34:19 AM org.openqa.selenium.remote.ProtocolHandshake createSession
INFO: Detected dialect: W3C
Exception in thread "main" org.openqa.selenium.UnsupportedCommandException: POST /session/ce713672-44ab-43b9-8baf-aa2a6f370818/moveto did not match a known command
Build info: version: 'unknown', revision: '1969d75', time: '2016-10-18 09:43:45 -0700'
System info: host: 'per-00', ip: '192.168.56.1', os.name: 'Windows 8.1', os.arch: 'amd64', os.version: '6.3', java.version: '1.8.0_91'
Driver info: org.openqa.selenium.firefox.FirefoxDriver
Capabilities [{rotatable=false, raisesAccessibilityExceptions=false, marionette=true, firefoxOptions={args=[], prefs={}}, appBuildId=20161208153507, moz:firefoxOptions={args=[], prefs={}}, version=, platform=XP, proxy={}, command_id=1, specificationLevel=0, acceptSslCerts=false, processId=1732, browserVersion=50.1.0, platformVersion=6.3, XULappId={ec8030f7-c20a-464f-9b0e-13a3a9e97384}, browserName=firefox, takesScreenshot=true, takesElementScreenshot=true, platformName=windows_nt}]
Session ID: ce713672-44ab-43b9-8baf-aa2a6f370818
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
	at java.lang.reflect.Constructor.newInstance(Unknown Source)
	at org.openqa.selenium.remote.http.W3CHttpResponseCodec.createException(W3CHttpResponseCodec.java:127)
	at org.openqa.selenium.remote.http.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:93)
	at org.openqa.selenium.remote.http.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:42)
	at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:163)
	at org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:82)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:601)
	at org.openqa.selenium.remote.RemoteExecuteMethod.execute(RemoteExecuteMethod.java:35)
	at org.openqa.selenium.remote.RemoteMouse.mouseMove(RemoteMouse.java:89)
	at org.openqa.selenium.interactions.MoveMouseAction.perform(MoveMouseAction.java:39)
	at org.openqa.selenium.interactions.CompositeAction.perform(CompositeAction.java:50)
	at flipkart.Flipkart.main(Flipkart.java:27)

**Comment by AutomatedTester** [comment] 2017-01-18 17:09
duplicate of #233

**Closed by AutomatedTester** 2017-01-18 17:09 UTC
