### ISSUE TITLE
missing geckodriver-v0.15.0-linux32.tar.gz version

### ISSUE THREAD

**Issue by 810** [mozilla/geckodriver#533] opened 2017-03-10 22:05 UTC
In order to help us efficiently investigate your issue, please provide the following information:

## Firefox Version
none

## Platform
Linux

## Steps to reproduce -
I can't see any new release for the Linux 32bit version, did you forgot to upload or is it depricated

**Comment by pbihler** [comment] 2017-03-13 09:07
Still missing...

**Comment by andreastt** [comment] 2017-03-14 13:16
As @pbi-qfs noted, it is missing because the x86 build is failing in CI because of Travis VM dependency issues. I checked that it compiles fine locally before the release, so I can do a manual upload of an x86 musl build from my workstation.

(Although you should really consider upgrading your hardware to 64-bit.)

**Comment by pbi-qfs** [comment] 2017-03-14 13:34
Great - I'm staying tuned...

**Comment by pbi-qfs** [comment] 2017-03-15 12:51
@andreastt Is there any ETA for the upload?

**Comment by andreastt** [comment] 2017-03-15 14:07
See my latest comments on https://github.com/mozilla/geckodriver/issues/495: It looks like this is a more serious issue than I first thought. It appears cross-compilation from x86_64 to x86 with a musl libc is not working at all. What we first thought was a Travis-related issue appears to reproduce fine on my workstation. So more investigation is needed.

**Comment by andreastt** [comment] 2017-03-23 12:57
Closing this as a duplicate of https://github.com/mozilla/geckodriver/issues/495.

**Closed by andreastt** 2017-03-23 12:57 UTC
