### ISSUE TITLE
Cannot make a  screenshoots of bootstrap modal window elements using selenium

### ISSUE THREAD

**Issue by viktor-silakov** [mozilla/geckodriver#1916] opened 2021-08-17 14:08 UTC
## System

* Version: 0.29.1
* Platform: macOS Big Sur
* Firefox: 91.0
* Selenium: 4.0.0-beta.4

## Testcase

1. Open https://getbootstrap.com/docs/4.0/components/modal/ 
2. Scroll to the button "//*[@data-target='#exampleModalLive']"
3. Click the button
4. Make the screenshoot
Pure webdriver js script:
```javascript
const { Builder, By, Key, until } = require('selenium-webdriver');
const fs = require('fs');


(async function example() {
    let driver = await new Builder().forBrowser('firefox').build();
    try {
        await driver.get('https://getbootstrap.com/docs/4.0/components/modal/');
        const button = await driver.findElement(By.xpath(`//*[@data-target='#exampleModalLive']`))

        await driver.executeScript("arguments[0].scrollIntoView(true);", button);
        await new Promise(r => setTimeout(r, 1000));
        await driver.executeScript("window.scrollBy(0, 350);");
        await new Promise(r => setTimeout(r, 3000));
        await driver.executeScript("arguments[0].click();", button);
        await new Promise(r => setTimeout(r, 3000));
        const ss = new Buffer(await driver.takeScreenshot(), 'base64');

        fs.writeFileSync('ss.png', ss);
    } finally {
        await driver.quit();
    }
})();

```

### Expected result: the viewport screenshot with the modal window: 
![image](https://user-images.githubusercontent.com/23633060/129740969-aa3be750-893f-4705-ab2e-2cd904f7e1fd.png)

### Actual result: the viewport screenshot without the modal window: 
![image](https://user-images.githubusercontent.com/23633060/129741101-79af4dde-720c-4b67-9671-900599a5acf6.png)

**Comment by whimboo** [comment] 2021-09-06 19:12
This is similar to https://bugzilla.mozilla.org/show_bug.cgi?id=1725343 that you filed. The new kind of modal dialog is a popup, which Marionette and other in-browser screenshot tools cannot handle. See https://bugzilla.mozilla.org/show_bug.cgi?id=1198432.

**Comment by whimboo** [comment] 2021-09-06 19:12
Marking as dupe of issue #1907.

**Closed by whimboo** 2021-09-06 19:12 UTC
Labels: marionette, firefox
