### ISSUE TITLE
Geckodriver on android is not running

### ISSUE THREAD

**Issue by nekolatony** [mozilla/geckodriver#1977] opened 2022-01-09 15:11 UTC
## System

* Version: 17 and 30
* Platform:Windows

## Testcase

I am trying to launch geckodriver on android using appium but it always says the the marionette port is not set 
I tried setting the marionette in the moz:firefoxOptions cap under args option like this :
'moz:firefoxOptions',  {
        "androidPackage": "org.mozilla.firefox",
        "androidActivity": "org.mozilla.firefox.App",
        "args":["--connect-existing","--marionette-port","2828"],
        'androidIntentArguments':{"devtools.debugger.remote-enabled":True},
}
how can I set the marionette port from the desired caps 

## Stacktrace

2022-01-09 15:05:45:842 [W3C] Encountered internal error running command: Error: An unknown server-side error occurred while processing the command. Original error: 'GET /status' cannot be proxied to Gecko Driver server because its process is not running (probably crashed). Check the Appium log for more details
2022-01-09 15:05:45:842 [W3C]     at waitMs (C:\Users\cr-tnekola-galil\AppData\Roaming\npm\node_modules\appium\node_modules\appium-geckodriver\lib\gecko.js:162:19)
2022-01-09 15:05:45:843 [W3C]     at spin (C:\Users\cr-tnekola-galil\AppData\Roaming\npm\node_modules\appium\node_modules\asyncbox\lib\asyncbox.js:138:20)
2022-01-09 15:05:45:843 [W3C]     at spin (C:\Users\cr-tnekola-galil\AppData\Roaming\npm\node_modules\appium\node_modules\asyncbox\lib\asyncbox.js:148:14)
2022-01-09 15:05:45:843 [W3C]     at waitForCondition (C:\Users\cr-tnekola-galil\AppData\Roaming\npm\node_modules\appium\node_modules\asyncbox\lib\asyncbox.js:155:10)
2022-01-09 15:05:45:843 [W3C]     at GeckoDriverServer.start (C:\Users\cr-tnekola-galil\AppData\Roaming\npm\node_modules\appium\node_modules\appium-geckodriver\lib\gecko.js:156:7)
2022-01-09 15:05:45:843 [W3C]     at GeckoDriver.createSession (C:\Users\cr-tnekola-galil\AppData\Roaming\npm\node_modules\appium\node_modules\appium-geckodriver\lib\driver.js:59:7)
2022-01-09 15:05:45:844 [W3C]     at AppiumDriver.createSession (C:\Users\cr-tnekola-galil\AppData\Roaming\npm\node_modules\appium\lib\appium.js:387:35)
2022-01-09 15:05:45:845 [HTTP] <-- POST /wd/hub/session 500 1069 ms - 1045
2022-01-09 15:05:45:845 [HTTP] 

## Trace-level log

2022-01-09 15:05:44:773 [HTTP] Request idempotency key: 22eae1ed-b316-4e7e-bc04-460619704669
2022-01-09 15:05:44:776 [HTTP] --> POST /wd/hub/session
2022-01-09 15:05:44:776 [HTTP] {"capabilities":{"firstMatch":[{"platformName":"Android","appium:noReset":true,"appium:newCommandTimeout":10000,"appium:deviceName":"R58NA53GW1F","appium:udid":"R58NA53GW1F","appium:systemPort":8207,"appium:automationName":"Gecko","browserName":"firefox","moz:firefoxOptions":{"androidPackage":"org.mozilla.firefox","androidActivity":"org.mozilla.firefox.App","args":["--connect-existing","--marionette-port","2828"],"androidIntentArguments":{"devtools.debugger.remote-enabled":true},"":["-a","android.intent.action.VIEW"]},"\"appium:marionette\"":true}]},"desiredCapabilities":{"platformName":"Android","noReset":true,"newCommandTimeout":10000,"deviceName":"R58NA53GW1F","udid":"R58NA53GW1F","systemPort":8207,"automationName":"Gecko","browserName":"firefox","moz:firefoxOptions":{"androidPackage":"org.mozilla.firefox","androidActivity":"org.mozilla.firefox.App","args":["--connect-existing","--marionette-port","2828"],"androidIntentArguments":{"devtools.debugger.remote-enabled":true},"":["-a","android.intent.action....
2022-01-09 15:05:44:776 [W3C] Calling AppiumDriver.createSession() with args: [{"platformName":"Android","noReset":true,"newCommandTimeout":10000,"deviceName":"R58NA53GW1F","udid":"R58NA53GW1F","systemPort":8207,"automationName":"Gecko","browserName":"firefox","moz:firefoxOptions":{"androidPackage":"org.mozilla.firefox","androidActivity":"org.mozilla.firefox.App","args":["--connect-existing","--marionette-port","2828"],"androidIntentArguments":{"devtools.debugger.remote-enabled":true},"":["-a","android.intent.action.VIEW"]},"\"appium:marionette\"":true},null,{"firstMatch":[{"platformName":"Android","appium:noReset":true,"appium:newCommandTimeout":10000,"appium:deviceName":"R58NA53GW1F","appium:udid":"R58NA53GW1F","appium:systemPort":8207,"appium:automationName":"Gecko","browserName":"firefox","moz:firefoxOptions":{"androidPackage":"org.mozilla.firefox","androidActivity":"org.mozilla.firefox.App","args":["--connect-existing","--marionette-port","2828"],"androidIntentArguments":{"devtools.debugger.remote-enabled":true},"":["-a","android.intent.action.VIEW"]},"\"appium:marionette\"":tr...
2022-01-09 15:05:44:776 [BaseDriver] Event 'newSessionRequested' logged at 1641740744776 (17:05:44 GMT+0200 (Israel Standard Time))
2022-01-09 15:05:44:777 [Appium] Appium v1.22.1 creating new GeckoDriver (v0.3.3) session
2022-01-09 15:05:44:778 [Appium] Explicitly enabling use of insecure features:
2022-01-09 15:05:44:778 [Appium]     chromedriver_autodownload
2022-01-09 15:05:44:778 [BaseDriver] W3C capabilities and MJSONWP desired capabilities were provided
2022-01-09 15:05:44:779 [BaseDriver] Creating session with W3C capabilities: {
2022-01-09 15:05:44:779 [BaseDriver]   "alwaysMatch": {
2022-01-09 15:05:44:779 [BaseDriver]     "platformName": "Android",
2022-01-09 15:05:44:779 [BaseDriver]     "browserName": "firefox",
2022-01-09 15:05:44:779 [BaseDriver]     "moz:firefoxOptions": {
2022-01-09 15:05:44:780 [BaseDriver]       "androidPackage": "org.mozilla.firefox",
2022-01-09 15:05:44:780 [BaseDriver]       "androidActivity": "org.mozilla.firefox.App",
2022-01-09 15:05:44:780 [BaseDriver]       "args": [
2022-01-09 15:05:44:780 [BaseDriver]         "--connect-existing",
2022-01-09 15:05:44:780 [BaseDriver]         "--marionette-port",
2022-01-09 15:05:44:780 [BaseDriver]         "2828"
2022-01-09 15:05:44:780 [BaseDriver]       ],
2022-01-09 15:05:44:780 [BaseDriver]       "androidIntentArguments": {
2022-01-09 15:05:44:780 [BaseDriver]         "devtools.debugger.remote-enabled": true
2022-01-09 15:05:44:780 [BaseDriver]       },
2022-01-09 15:05:44:781 [BaseDriver]       "": [
2022-01-09 15:05:44:781 [BaseDriver]         "-a",
2022-01-09 15:05:44:781 [BaseDriver]         "android.intent.action.VIEW"
2022-01-09 15:05:44:781 [BaseDriver]       ]
2022-01-09 15:05:44:781 [BaseDriver]     },
2022-01-09 15:05:44:781 [BaseDriver]     "\"appium:marionette\"": true,
2022-01-09 15:05:44:781 [BaseDriver]     "appium:noReset": true,
2022-01-09 15:05:44:781 [BaseDriver]     "appium:newCommandTimeout": 10000,
2022-01-09 15:05:44:781 [BaseDriver]     "appium:deviceName": "R58NA53GW1F",
2022-01-09 15:05:44:781 [BaseDriver]     "appium:udid": "R58NA53GW1F",
2022-01-09 15:05:44:782 [BaseDriver]     "appium:systemPort": 8207,
2022-01-09 15:05:44:782 [BaseDriver]     "appium:automationName": "Gecko"
2022-01-09 15:05:44:782 [BaseDriver]   },
2022-01-09 15:05:44:782 [BaseDriver]   "firstMatch": [
2022-01-09 15:05:44:782 [BaseDriver]     {}
2022-01-09 15:05:44:782 [BaseDriver]   ]
2022-01-09 15:05:44:782 [BaseDriver] }
2022-01-09 15:05:44:783 [BaseDriver] The following capabilities were provided, but are not recognized by Appium:
2022-01-09 15:05:44:784 [BaseDriver]   "appium:marionette"
2022-01-09 15:05:44:784 [BaseDriver] Session created with session id: 8fe03648-4a25-467c-9b82-4e4729fd4474
2022-01-09 15:05:44:815 [GeckoDriverServer] Starting 'C:\DRIVERS\geckodriver\geckodriver.exe' with args ["--connect-existing","-p",8207]
2022-01-09 15:05:44:834 [WD Proxy] Matched '/status' to command name 'getStatus'
2022-01-09 15:05:44:834 [WD Proxy] Proxying [GET /status] to [GET http://127.0.0.1:8207/status] with no body
2022-01-09 15:05:44:836 [WD Proxy] connect ECONNREFUSED 127.0.0.1:8207
2022-01-09 15:05:44:863 [GeckoDriverServer] [geckodriver.exe] error: The following required arguments were not provided:
2022-01-09 15:05:44:863 [GeckoDriverServer]     --marionette-port <PORT>
2022-01-09 15:05:44:864 [GeckoDriverServer] 
2022-01-09 15:05:44:864 [GeckoDriverServer] USAGE:
2022-01-09 15:05:44:864 [GeckoDriverServer]     geckodriver.exe --connect-existing --marionette-port <PORT> --port <PORT>
2022-01-09 15:05:44:864 [GeckoDriverServer] 
2022-01-09 15:05:44:864 [GeckoDriverServer] For more information try --help
2022-01-09 15:05:44:866 [GeckoDriverServer] geckodriver.exe has exited with code 1, signal null
2022-01-09 15:05:45:840 [GeckoDriver] Ending Gecko Driver session
2022-01-09 15:05:45:841 [GeckoDriverServer] Gecko Driver session cannot be stopped, because the server is not running
2022-01-09 15:05:45:841 [BaseDriver] Event 'newSessionStarted' logged at 1641740745841 (17:05:45 GMT+0200 (Israel Standard Time))
2022-01-09 15:05:45:842 [W3C] Encountered internal error running command: Error: An unknown server-side error occurred while processing the command. Original error: 'GET /status' cannot be proxied to Gecko Driver server because its process is not running (probably crashed). Check the Appium log for more details
2022-01-09 15:05:45:842 [W3C]     at waitMs (C:\Users\cr-tnekola-galil\AppData\Roaming\npm\node_modules\appium\node_modules\appium-geckodriver\lib\gecko.js:162:19)
2022-01-09 15:05:45:843 [W3C]     at spin (C:\Users\cr-tnekola-galil\AppData\Roaming\npm\node_modules\appium\node_modules\asyncbox\lib\asyncbox.js:138:20)
2022-01-09 15:05:45:843 [W3C]     at spin (C:\Users\cr-tnekola-galil\AppData\Roaming\npm\node_modules\appium\node_modules\asyncbox\lib\asyncbox.js:148:14)
2022-01-09 15:05:45:843 [W3C]     at waitForCondition (C:\Users\cr-tnekola-galil\AppData\Roaming\npm\node_modules\appium\node_modules\asyncbox\lib\asyncbox.js:155:10)
2022-01-09 15:05:45:843 [W3C]     at GeckoDriverServer.start (C:\Users\cr-tnekola-galil\AppData\Roaming\npm\node_modules\appium\node_modules\appium-geckodriver\lib\gecko.js:156:7)
2022-01-09 15:05:45:843 [W3C]     at GeckoDriver.createSession (C:\Users\cr-tnekola-galil\AppData\Roaming\npm\node_modules\appium\node_modules\appium-geckodriver\lib\driver.js:59:7)
2022-01-09 15:05:45:844 [W3C]     at AppiumDriver.createSession (C:\Users\cr-tnekola-galil\AppData\Roaming\npm\node_modules\appium\lib\appium.js:387:35)
2022-01-09 15:05:45:845 [HTTP] <-- POST /wd/hub/session 500 1069 ms - 1045
2022-01-09 15:05:45:845 [HTTP]

**Comment by whimboo** [comment] 2022-01-10 08:48
Duplicate of issue #1922.

**Closed by whimboo** 2022-01-10 08:48 UTC
