### ISSUE TITLE
clicking on row, wider than screen, failed: Element <tr> could not be scrolled into view

### ISSUE THREAD

**Issue by mseele** [mozilla/geckodriver#1294] opened 2018-06-06 11:18 UTC
## System

* Version: 0.20.1
* Platform: Windows 10
* Firefox: 60.0.1 (64-Bit)
* Selenium: 3.12.0

## Testcase

Clicking on row failed:

ClickSnippet.java
```
import java.util.List;

import org.junit.Test;
import org.openqa.selenium.By;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.firefox.FirefoxDriver;

public class ClickSnippet {

	@Test
	public void verifyBug() {
		System.setProperty("webdriver.gecko.driver", "/path/to/geckodriver");
		WebDriver webDriver = new FirefoxDriver();
		try {

			webDriver.manage().window().setSize(new Dimension(1280, 800));
			webDriver.get("path/to/click_snippet.html");

			WebElement baseTable = webDriver.findElement(By.tagName("tbody"));
			List<WebElement> rows = baseTable.findElements(By.tagName("tr"));
			// click fails because row is wider than screen
			rows.get(0).click();

			webDriver.close();
		} finally {
			webDriver.quit();
		}
	}

}

```

click_snippet.html
```
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<title>Snippet</title>
<style type="text/css">
.tg  {border-collapse:collapse;border-spacing:0;}
.tg td{font-family:Arial, sans-serif;font-size:14px;padding:10px 5px;border-style:solid;border-width:1px;overflow:hidden;word-break:normal;border-color:black;}
.tg th{font-family:Arial, sans-serif;font-size:14px;font-weight:normal;padding:10px 5px;border-style:solid;border-width:1px;overflow:hidden;word-break:normal;border-color:black;}
.tg .tg-yw4l{vertical-align:top}
</style>
</head>
<body>
<table class="tg" style="undefined;table-layout: fixed; width: 1500px">
<colgroup>
<col style="width: 300px">
<col style="width: 300px">
<col style="width: 300px">
<col style="width: 300px">
<col style="width: 300px">
</colgroup>
  <tr>
    <th class="tg-yw4l">a</th>
    <th class="tg-yw4l">b</th>
    <th class="tg-yw4l">c</th>
    <th class="tg-yw4l">d</th>
    <th class="tg-yw4l">e</th>
  </tr>
</table>
</body>
</html>
```

## Stacktrace

```
org.openqa.selenium.ElementNotInteractableException: Element <tr> could not be scrolled into view
Build info: version: '3.12.0', revision: '7c6e0b3', time: '2018-05-08T15:15:08.936Z'
System info: host: 'GHCL11', ip: '192.168.100.116', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_172'
Driver info: org.openqa.selenium.firefox.FirefoxDriver
Capabilities {acceptInsecureCerts: true, browserName: firefox, browserVersion: 60.0.1, javascriptEnabled: true, moz:accessibilityChecks: false, moz:headless: false, moz:processID: 20684, moz:profile: C:\Users\mseele\AppData\Loc..., moz:useNonSpecCompliantPointerOrigin: false, moz:webdriverClick: true, pageLoadStrategy: normal, platform: XP, platformName: XP, platformVersion: 10.0, rotatable: false, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}}
Session ID: f8996230-e67a-4b82-8aa1-8aa0e2a4d2e9
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.openqa.selenium.remote.http.W3CHttpResponseCodec.createException(W3CHttpResponseCodec.java:187)
	at org.openqa.selenium.remote.http.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:122)
	at org.openqa.selenium.remote.http.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:49)
	at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:158)
	at org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:83)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:543)
	at org.openqa.selenium.remote.RemoteWebElement.execute(RemoteWebElement.java:276)
	at org.openqa.selenium.remote.RemoteWebElement.click(RemoteWebElement.java:83)
	at ClickSnippet.verifyBug(ClickSnippet.java:24)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:86)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:538)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:760)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:460)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:206)
```

## Trace-level log

```
1528283846881	geckodriver	INFO	geckodriver 0.20.1
1528283846891	geckodriver	INFO	Listening on 127.0.0.1:30143
1528283847629	mozrunner::runner	INFO	Running command: "C:\\Program Files\\Mozilla Firefox\\firefox.exe" "-marionette" "-profile" "C:\\Users\\mseele\\AppData\\Local\\Temp\\rust_mozprofile.VYeeMIemznms"
1528283847638	geckodriver::marionette	DEBUG	Waiting 60s to connect to browser
1528283848412	Marionette	DEBUG	Received observer notification profile-after-change
Unable to read VR Path Registry from C:\Users\mseele\AppData\Local\openvr\openvrpaths.vrpath
1528283848617	Marionette	DEBUG	Received observer notification command-line-startup
1528283848617	Marionette	DEBUG	Received observer notification nsPref:changed
Unable to read VR Path Registry from C:\Users\mseele\AppData\Local\openvr\openvrpaths.vrpath
Unable to read VR Path Registry from C:\Users\mseele\AppData\Local\openvr\openvrpaths.vrpath
Unable to read VR Path Registry from C:\Users\mseele\AppData\Local\openvr\openvrpaths.vrpath
1528283849608	Marionette	DEBUG	Received observer notification sessionstore-windows-restored
1528283849757	Marionette	DEBUG	Setting recommended pref toolkit.cosmeticAnimations.enabled to false
1528283849757	Marionette	DEBUG	Setting recommended pref datareporting.policy.dataSubmissionPolicyAccepted to false
1528283849758	Marionette	DEBUG	Setting recommended pref extensions.shield-recipe-client.api_url to 
1528283849790	Marionette	DEBUG	New connections are accepted
1528283849790	Marionette	INFO	Listening on port 57790
Unable to read VR Path Registry from C:\Users\mseele\AppData\Local\openvr\openvrpaths.vrpath
1528283850752	geckodriver::marionette	DEBUG	Connected to Marionette on localhost:57790
1528283850758	Marionette	DEBUG	Accepted connection 0 from 127.0.0.1:57812
1528283850760	geckodriver::marionette	TRACE	<- {"applicationType":"gecko","marionetteProtocol":3}
1528283850760	geckodriver::marionette	TRACE	-> 163:[0,1,"newSession",{"acceptInsecureCerts":true,"browserName":"firefox","capabilities":{"desiredCapabilities":{"acceptInsecureCerts":true,"browserName":"firefox"}}}]
1528283850763	Marionette	TRACE	0 -> [0,1,"newSession",{"acceptInsecureCerts":true,"browserName":"firefox","capabilities":{"desiredCapabilities":{"acceptInsecureCerts":true,"browserName":"firefox"}}}]
1528283850765	Marionette	WARN	TLS certificate errors will be ignored for this session
1528283850821	Marionette	DEBUG	Register listener.js for window 4294967297
1528283850828	Marionette	TRACE	0 <- [1,1,null,{"sessionId":"b3ad045e-e069-4c62-ae56-4716f71559a6","capabilities":{"browserName":"firefox","browserVersion":"60.0. ... AppData\\Local\\Temp\\rust_mozprofile.VYeeMIemznms","moz:useNonSpecCompliantPointerOrigin":false,"moz:webdriverClick":true}}]
1528283850830	geckodriver::marionette	TRACE	<- [1,1,null,{"sessionId":"b3ad045e-e069-4c62-ae56-4716f71559a6","capabilities":{"browserName":"firefox","browserVersion":"60.0.1","platformName":"windows_nt","platformVersion":"10.0","pageLoadStrategy":"normal","acceptInsecureCerts":true,"timeouts":{"implicit":0,"pageLoad":300000,"script":30000},"rotatable":false,"moz:accessibilityChecks":false,"moz:headless":false,"moz:processID":15672,"moz:profile":"C:\\Users\\mseele\\AppData\\Local\\Temp\\rust_mozprofile.VYeeMIemznms","moz:useNonSpecCompliantPointerOrigin":false,"moz:webdriverClick":true}}]
1528283850830	webdriver::server	DEBUG	<- 200 OK {"value": {"sessionId":"b3ad045e-e069-4c62-ae56-4716f71559a6","capabilities":{"acceptInsecureCerts":true,"browserName":"firefox","browserVersion":"60.0.1","moz:accessibilityChecks":false,"moz:headless":false,"moz:processID":15672,"moz:profile":"C:\\Users\\mseele\\AppData\\Local\\Temp\\rust_mozprofile.VYeeMIemznms","moz:useNonSpecCompliantPointerOrigin":false,"moz:webdriverClick":true,"pageLoadStrategy":"normal","platformName":"windows_nt","platformVersion":"10.0","rotatable":false,"timeouts":{"implicit":0,"pageLoad":300000,"script":30000}}}}
Jun 06, 2018 1:17:30 PM org.openqa.selenium.remote.ProtocolHandshake createSession
INFORMATION: Detected dialect: W3C
1528283850886	webdriver::server	DEBUG	-> POST /session/b3ad045e-e069-4c62-ae56-4716f71559a6/window/rect {"width":1280,"height":800}
1528283850887	geckodriver::marionette	TRACE	-> 67:[0,2,"setWindowRect",{"height":800,"width":1280,"x":null,"y":null}]
1528283850889	Marionette	TRACE	0 -> [0,2,"setWindowRect",{"height":800,"width":1280,"x":null,"y":null}]
1528283852922	Marionette	TRACE	0 <- [1,2,null,{"x":4,"y":4,"width":1280,"height":800,"state":"normal"}]
1528283852925	geckodriver::marionette	TRACE	<- [1,2,null,{"x":4,"y":4,"width":1280,"height":800,"state":"normal"}]
1528283852925	webdriver::server	DEBUG	<- 200 OK {"value": {"height":800,"width":1280,"x":4,"y":4}}
1528283852930	webdriver::server	DEBUG	-> POST /session/b3ad045e-e069-4c62-ae56-4716f71559a6/url {"url":"file:///C:/dev/workspaces/dmm/dmmRegressionTests/src/click_snippet.html"}
1528283852930	geckodriver::marionette	TRACE	-> 93:[0,3,"get",{"url":"file:///C:/dev/workspaces/dmm/dmmRegressionTests/src/click_snippet.html"}]
1528283852933	Marionette	TRACE	0 -> [0,3,"get",{"url":"file:///C:/dev/workspaces/dmm/dmmRegressionTests/src/click_snippet.html"}]
1528283852946	Marionette	DEBUG	Received DOM event beforeunload for about:blank
1528283852962	Marionette	DEBUG	Received DOM event pagehide for about:blank
1528283852963	Marionette	DEBUG	Received DOM event unload for about:blank
1528283852964	Marionette	DEBUG	Received observer notification outer-window-destroyed for 4294967297
[Child 22648, Chrome_ChildThread] WARNING: pipe error: 109: file z:/build/build/src/ipc/chromium/src/chrome/common/ipc_channel_win.cc, line 346
[Child 22648, Unable to read VR Path Registry from C:\Users\mseele\AppData\Local\openvr\openvrpaths.vrpath
1528283853525	Marionette	DEBUG	Register listener.js for window 8589934593
1528283853560	Marionette	DEBUG	Check readyState uninitialized for about:blank
1528283853587	Marionette	DEBUG	Received DOM event DOMContentLoaded for file:///C:/dev/workspaces/dmm/dmmRegressionTests/src/click_snippet.html
1528283853615	Marionette	DEBUG	Received DOM event pageshow for file:///C:/dev/workspaces/dmm/dmmRegressionTests/src/click_snippet.html
1528283853617	Marionette	TRACE	0 <- [1,3,null,{}]
1528283853619	geckodriver::marionette	TRACE	<- [1,3,null,{}]
1528283853620	webdriver::server	DEBUG	<- 200 OK {"value": {}}
1528283853628	webdriver::server	DEBUG	-> POST /session/b3ad045e-e069-4c62-ae56-4716f71559a6/element {"value":"tbody","using":"css selector"}
1528283853628	geckodriver::marionette	TRACE	-> 60:[0,4,"findElement",{"using":"css selector","value":"tbody"}]
1528283853631	Marionette	TRACE	0 -> [0,4,"findElement",{"using":"css selector","value":"tbody"}]
1528283853635	Marionette	TRACE	0 <- [1,4,null,{"value":{"element-6066-11e4-a52e-4f735466cecf":"057142cc-aad6-4037-ac48-16153fb85e1e","ELEMENT":"057142cc-aad6-4037-ac48-16153fb85e1e"}}]
1528283853636	geckodriver::marionette	TRACE	<- [1,4,null,{"value":{"element-6066-11e4-a52e-4f735466cecf":"057142cc-aad6-4037-ac48-16153fb85e1e","ELEMENT":"057142cc-aad6-4037-ac48-16153fb85e1e"}}]
1528283853636	webdriver::server	DEBUG	<- 200 OK {"value":{"element-6066-11e4-a52e-4f735466cecf":"057142cc-aad6-4037-ac48-16153fb85e1e"}}
1528283853645	webdriver::server	DEBUG	-> POST /session/b3ad045e-e069-4c62-ae56-4716f71559a6/element/057142cc-aad6-4037-ac48-16153fb85e1e/elements {"using":"css selector","id":"057142cc-aad6-4037-ac48-16153fb85e1e","value":"tr"}
1528283853645	geckodriver::marionette	TRACE	-> 107:[0,5,"findElements",{"element":"057142cc-aad6-4037-ac48-16153fb85e1e","using":"css selector","value":"tr"}]
1528283853648	Marionette	TRACE	0 -> [0,5,"findElements",{"element":"057142cc-aad6-4037-ac48-16153fb85e1e","using":"css selector","value":"tr"}]
1528283853651	Marionette	TRACE	0 <- [1,5,null,[{"element-6066-11e4-a52e-4f735466cecf":"f6ae20d7-94b9-4cad-adbf-e9297cfeccf7","ELEMENT":"f6ae20d7-94b9-4cad-adbf-e9297cfeccf7"}]]
1528283853652	geckodriver::marionette	TRACE	<- [1,5,null,[{"element-6066-11e4-a52e-4f735466cecf":"f6ae20d7-94b9-4cad-adbf-e9297cfeccf7","ELEMENT":"f6ae20d7-94b9-4cad-adbf-e9297cfeccf7"}]]
1528283853652	webdriver::server	DEBUG	<- 200 OK {"value":[{"element-6066-11e4-a52e-4f735466cecf":"f6ae20d7-94b9-4cad-adbf-e9297cfeccf7"}]}
1528283853662	webdriver::server	DEBUG	-> POST /session/b3ad045e-e069-4c62-ae56-4716f71559a6/element/f6ae20d7-94b9-4cad-adbf-e9297cfeccf7/click {"id":"f6ae20d7-94b9-4cad-adbf-e9297cfeccf7"}
1528283853662	geckodriver::marionette	TRACE	-> 66:[0,6,"clickElement",{"id":"f6ae20d7-94b9-4cad-adbf-e9297cfeccf7"}]
1528283853665	Marionette	TRACE	0 -> [0,6,"clickElement",{"id":"f6ae20d7-94b9-4cad-adbf-e9297cfeccf7"}]
1528283853674	Marionette	TRACE	0 <- [1,6,{"error":"element not interactable","message":"Element <tr> could not be scrolled into view","stacktrace":"WebDriverErro ... avigate@chrome://marionette/content/listener.js:414:13\nclickElement@chrome://marionette/content/listener.js:1220:5\n"},null]
1528283853674	geckodriver::marionette	TRACE	<- [1,6,{"error":"element not interactable","message":"Element <tr> could not be scrolled into view","stacktrace":"WebDriverError@chrome://marionette/content/error.js:178:5\nElementNotInteractableError@chrome://marionette/content/error.js:286:5\nwebdriverClickElement@chrome://marionette/content/interaction.js:158:11\ninteraction.clickElement@chrome://marionette/content/interaction.js:129:11\nclickElement/<@chrome://marionette/content/listener.js:1221:14\nnavigate/<@chrome://marionette/content/listener.js:415:13\nnavigate@chrome://marionette/content/listener.js:414:13\nclickElement@chrome://marionette/content/listener.js:1220:5\n"},null]
1528283853674	webdriver::server	DEBUG	<- 400 Bad Request {"value":{"error":"element not interactable","message":"Element <tr> could not be scrolled into view","stacktrace":"WebDriverError@chrome://marionette/content/error.js:178:5\nElementNotInteractableError@chrome://marionette/content/error.js:286:5\nwebdriverClickElement@chrome://marionette/content/interaction.js:158:11\ninteraction.clickElement@chrome://marionette/content/interaction.js:129:11\nclickElement/<@chrome://marionette/content/listener.js:1221:14\nnavigate/<@chrome://marionette/content/listener.js:415:13\nnavigate@chrome://marionette/content/listener.js:414:13\nclickElement@chrome://marionette/content/listener.js:1220:5\n"}}
1528283853688	webdriver::server	DEBUG	-> DELETE /session/b3ad045e-e069-4c62-ae56-4716f71559a6 
1528283853688	geckodriver::marionette	TRACE	-> 37:[0,7,"quit",{"flags":["eForceQuit"]}]
1528283853689	Marionette	TRACE	0 -> [0,7,"quit",{"flags":["eForceQuit"]}]
1528283853690	Marionette	DEBUG	New connections will no longer be accepted
1528283853721	Marionette	TRACE	0 <- [1,7,null,{"cause":"shutdown"}]
[Parent 15672, Gecko_IOThread] WARNING: pipe error: 109: file z:/build/build/src/ipc/chromium/src/chrome/common/ipc_channel_win.cc, line 346
1528283853734	geckodriver::marionette	TRACE	<- [1,7,null,{"cause":"shutdown"}]
1528283853734	webdriver::server	DEBUG	Deleting session
1528283853734	geckodriver::marionette	TRACE	-> 37:[0,8,"quit",{"flags":["eForceQuit"]}]
[Child 13236, Chrome_ChildThread] WARNING: pipe error: 109: file z:/build/build/src/ipc/chromium/src/chrome/common/ipc_channel_win.cc, line 346
[Child 13236, Chr1528283853741	Marionette	TRACE	0 -> [0,8,"quit",{"flags":["eForceQuit"]}]
1528283853742	Marionette	TRACE	0 <- [1,8,{"error":"invalid session id","message":"","stacktrace":"WebDriverError@chrome://marionette/content/error.js:178:5\nInva ... et@chrome://marionette/content/server.js:241:8\n_onJSONObjectReady/<@chrome://marionette/content/transport.js:500:9\n"},null]
1528283853743	geckodriver::marionette	TRACE	<- [1,8,{"error":"invalid session id","message":"","stacktrace":"WebDriverError@chrome://marionette/content/error.js:178:5\nInvalidSessionIDError@chrome://marionette/content/error.js:347:5\nassert.that/<@chrome://marionette/content/assert.js:405:13\nassert.session@chrome://marionette/content/assert.js:79:3\ndespatch@chrome://marionette/content/server.js:290:7\nexecute@chrome://marionette/content/server.js:267:11\nonPacket/<@chrome://marionette/content/server.js:242:15\nonPacket@chrome://marionette/content/server.js:241:8\n_onJSONObjectReady/<@chrome://marionette/content/transport.js:500:9\n"},null]
[Parent 15672, Gecko_IOThread] WARNING: pipe error: 109: file z:/build/build/src/ipc/chromium/src/chrome/common/ipc_channel_win.cc, line 346
[Child 4484, Chrome_ChildThread] WARNING: pipe error: 109: file z:/build/build/src/ipc/chromium/src/chrome/common/ipc_channel_win.cc, line 346
[Child 4484, Chrome_ChildThre1528283853755	Marionette	DEBUG	Closed connection 0
[Parent 15672, Gecko_IOThread] WARNING: pipe error: 109: file z:/build/build/src/ipc/chromium/src/chrome/common/ipc_channel_win.cc, line 346
*** UTM:SVC TimerManager:registerTimer called after profile-before-change notification. Ignoring timer registration for id: telemetry_modules_ping
1528283853859	Marionette	DEBUG	Received observer notification xpcom-will-shutdown
1528283853859	Marionette	DEBUG	Resetting recommended pref toolkit.cosmeticAnimations.enabled
1528283853859	Marionette	DEBUG	Resetting recommended pref datareporting.policy.dataSubmissionPolicyAccepted
1528283853860	Marionette	DEBUG	Resetting recommended pref extensions.shield-recipe-client.api_url
[GPU 20288, Chrome_ChildThread] WARNI
###!!! [Child][MessageChannel::SendAndWait] Error: Channel error: cannot send/recv

1528283854147	geckodriver::marionette	DEBUG	Browser process stopped with exit status exit code: 0
1528283854294	webdriver::server	DEBUG	<- 200 OK {"value": {}}

```

**Comment by andreastt** [comment] 2018-06-06 11:33
I haven’t looked to closely at the HTML document yet, but this sounds like a specification problem. Under normal circumstances, WebDriver uses an element’s _in-view centre point_—that is, the X/Y coordinate in the middle of the subsection of the element that is rendered in the viewport—as the click point. There may be some edge cases with `<tr>` and tables that the specification is not covering.

This needs more investigation, but thanks for including a trace-level log. That was useful for determining which internal implementation of the click algorithm you used. As we can see, the `moz:webdriverClick` capability returned is true.

**Comment by mseele** [comment] 2018-06-06 11:37
does only happen with geckodriver. chromedriver / edgedriver works as expected

**Comment by whimboo** [comment] 2018-06-06 18:14
@mseele would you have the time to further reduce the HTML snippet? As smaller it is as better for us for investigation. Thanks!

**Comment by mseele** [comment] 2018-06-06 18:17
@whimboo yes, but its only a blank table in a body tag. what can i reduce there?
please see https://jsfiddle.net/e6sxaqLr/

**Comment by twalpole** [comment] 2018-06-06 18:40
This is caused by the workaround for <tr> tags not being included in paint trees - https://dxr.mozilla.org/mozilla-central/source/testing/marionette/element.js#1073 - which just isn't correct.  The workaround checks whether the first cell is in the paint tree but the middle of the element isn't over the first cell, so it fails.  A fix for this would be to check whether any of the cells in the row are in the paint tree rather than just the first, although that probably still fail if the center of the row ended up being between two cells.  

When writing tests the solution, for now, is to click on a cell rather than the row, which is what a user would do anyway.

**Comment by whimboo** [comment] 2018-06-06 19:27
Ah, so in this case issue #1228 should cover that, and especially https://bugzilla.mozilla.org/show_bug.cgi?id=1448825. Marking as dupe.

**Closed by whimboo** 2018-06-06 19:27 UTC
Labels: specification, waiting for reporter feedback
