### ISSUE TITLE
Unable to doubleClick on an Element from Java-Selenium 3.3.1 (marionette)

### ISSUE THREAD

**Issue by adriens** [mozilla/geckodriver#558] opened 2017-03-21 03:47 UTC
In order to help us efficiently investigate your issue, please provide the following information:

## Firefox Version
52.0 (64-bit)
Mozilla Firefox for Linux Mint
mint - 1.0

## Platform
```
Linux Mint 17.3 Rosa \n \l
Linux themint 3.19.0-32-generic #37~14.04.1-Ubuntu SMP Thu Oct 22 09:41:40 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
```

Geckodriver :

```
geckodriver-v0.15.0-linux64.tar.gz
```

Selenium Java :

```xml
<dependency>
    <groupId>org.seleniumhq.selenium</groupId>
    <artifactId>selenium-java</artifactId>
    <version>3.3.1</version>
</dependency>
```

## Steps to reproduce (Java code snippet)

The simple click works whereas the DbleCLick doesn't

```java

System.setProperty("webdriver.gecko.driver", "/opt/marionette/geckodriver");
DesiredCapabilities caps = DesiredCapabilities.firefox();
caps.setCapability("marionette", true);
driver = new FirefoxDriver(caps);

WebElement firstProject = driver.findElementsByClassName("z-listitem").get(0);
Assert.assertNotNull("At least one project should be retrieved", firstProject);
System.out.println("Found a project : " + firstProject.getText());
firstProject.click();
// up to here everything is running fine
// now let's try to Dble-Click the element
Actions action = new Actions(driver);
        action.moveToElement(firstProject).doubleClick().build().perform();
        try{
            Thread.sleep(10000);
        }
        catch(InterruptedException ex){
            ex.printStackTrace();
        }
```

 - [ ] A [trace level log](https://github.com/mozilla/geckodriver#firefox-capabilities) from a geckodriver session that demonstrates the problem using the minimal example file. Note: this is *not* the same as a selenium log.

Here is the selenium log :

```
1490067141848	Marionette	INFO	New connections will no longer be accepted
[Child 31868] WARNING: pipe error (3): Connection reset by peer: file /build/firefox-e9xccf/firefox-52.0+linuxmint1+rosa/ipc/chromium/src/chrome/common/ipc_channel_posix.cc, line 322
[Child 31868] ###!!! ABORT: Aborting on channel error.: file /build/firefox-e9xccf/firefox-52.0+linuxmint1+rosa/ipc/glue/MessageChannel.cpp, line 2143
[Child 31868] ###!!! ABORT: Aborting on channel error.: file /build/firefox-e9xccf/firefox-52.0+linuxmint1+rosa/ipc/glue/MessageChannel.cpp, line 2143
```

I did not find how to provide you the ```trace level log``` as you expect it : can you provide a simple how to so i can generate one ?

**Comment by snpanigrahi9** [comment] 2017-03-21 09:25
i am also facing the issue.

**Comment by Twyllo** [comment] 2017-03-21 11:00
Have you tried with 32bit ff? Same code has issues/is slower for me when on 64bit ff while on 32bit works great

**Comment by adriens** [comment] 2017-03-21 21:28
@Twyllo : nope, did not yet try on a 32b FF. Hence I'll give it a try as soon as possible.
I'll make a feedback on the post.
Thanks a lot for pointing this ! :+1:

**Comment by DerekTM1** [comment] 2017-03-22 11:46
Faced the same issue with 32b FF and actions.

[NPAPI 2764] WARNING: pipe error: 109: file c:/builds/moz2_slave/m-rel-w32-00000000000000000000/build/src/ipc/chromium/src/chrome/common/ipc_channel_win.cc, line 345
[NPAPI 2764] WARNING: pipe error: 109: file c:/builds/moz2_slave/m-rel-w32-00000000000000000000/build/src/ipc/chromium/src/chrome/common/ipc_channel_win.cc, line 345

**Comment by adriens** [comment] 2017-03-22 21:57
@DerekTM1 : happy to not be alone but... :cry: that the FF32 does not fix it

**Comment by DerekTM1** [comment] 2017-03-23 05:12
It seems that Actions does not work at all for me. Tried doubleclick, moveToElement and a simple action.click(xpath).build().perform() also not works. No errors and no actions :( I'm using the latest 32b FF, geckodriver-v0.15.0-win32 and selenium 3.3.1.

**Comment by jeep101** [comment] 2017-03-23 06:48
I am also encountering the same issue. Actions are not working if I use FF, geckodriver v0.15 and selenium 3.3.1 but it is working fine when I use chrome :(

**Comment by andreastt** [comment] 2017-03-23 12:48
This is in some sense a duplicate of https://github.com/mozilla/geckodriver/issues/159. But the double click action in the Selenium API needs to have a shim implemented so that it calls down to the appropriate pointer action to initiate a double click.

**Closed by andreastt** 2017-03-23 12:48 UTC
