### ISSUE TITLE
Do we support Selenium 3.0 beta 2 - Firefox 47+ Geckodriver + protractor-net lib?

### ISSUE THREAD

**Issue by iPiyushPatel** [mozilla/geckodriver#208] opened 2016-09-02 09:52 UTC
Hi,
I've just updated Selenium version to 3.0 beta 2 , also downloaded required geckodriver (https://github.com/mozilla/geckodriver/releases) , and started testing with Firefox 47.0.1.

I noticed that - driver doesn't wait for angular request to finish & test fails. I use protractor-net lib (https://github.com/bbaia/protractor-net) to work with Angular application.  

Can you please help ?
Let me know if any other additional info required.

**Comment by andreastt** [comment] 2016-09-05 11:43
You will have to be more specific than that. Generally, the more recent Firefox version the better the support. I would urge you to try again with Nightly, and if that still fails try to debug the problem.

As this stands currently this isn’t an actionable issue, so I’m going to close it. If you however find more information in the future about what the real cause is, I’m happy to reopen it.

**Closed by andreastt** 2016-09-05 11:43 UTC

**Comment by murdog05** [comment] 2016-09-05 12:27
I have the same issue.  We have had to keep our tests running on FireFox 47 with the old FireFoxDriver because marrionette does not wait until the page loads before it allows the test code to continue.  The old driver did this which is behavior all our automated tests expect which now causes elements that were found before to not be found anymore.

Perhaps a setting or something that requires a page to be loaded before the tests can proceed.  I know there is another bug entered for this same issue.  I feel that if this bug is not fixed I cannot proceed using Marrionette and Firefox because it will require too much refactoring of our tests, we would be better off switching to Chrome or Internet explorer and hopefully finding some stability there.

**Comment by andreastt** [comment] 2016-09-05 12:43
@murdog05 I’m not able to reproduce that it doesn’t block until the page is fully loaded. Marionette waits for the _DOMContentLoaded_ event before returning from a navigation call. It would be good if you are able to come up with a reproducible test case for that.

**Comment by murdog05** [comment] 2016-09-05 13:07
Is this something fixed recently?  Because I am easily able to reproduce it.  I downloaded version .10 a few weeks ago.  I will try the latest nightly build and see what it does.

**Comment by andreastt** [comment] 2016-09-05 13:20
The WebDriver implementation lives inside of Gecko/Firefox. The geckodriver binary is just a proxy that provides the HTTP API. A new-ish Nightly is always good to use when trying to reproduce.
