### ISSUE TITLE
Select is not working with geckodriver

### ISSUE THREAD

**Issue by kumaralok444** [mozilla/geckodriver#199] opened 2016-08-27 06:42 UTC
Hiiii
Environment: java, selenium-java-3.0.0-beta2, geckodriver-v0.10.0-win64
command:- 
Select se= new Select(webelement);
se.selectByIndex(1);
Expected op:- it Should select second element in Select option.
Actual op:- its not selecting any element from select option.

Here is the Code:
public class t2 {
	public static void main(String[] args) throws InterruptedException {
		WebDriver driver;
		System.setProperty("webdriver.gecko.driver", "D:\\Testing\\geckodriver-v0.10.0-win64\\geckodriver.exe");
		driver=new FirefoxDriver();
		driver.get("file:///D:/computershop/index.html");
		String pid=driver.getWindowHandle();
		System.out.println(pid);
		WebElement jim=driver.findElement(By.id("source"));
		Select se=new Select(jim);
		se.selectByIndex(1);  //Here it should select second Element in select option but its not working.
          }
}

**Comment by andreastt** [comment] 2016-08-28 17:01
Duplicate of https://github.com/mozilla/geckodriver/issues/94.

**Closed by andreastt** 2016-08-28 17:01 UTC
