### ISSUE TITLE
Unable to locate element by tagName

### ISSUE THREAD

**Issue by katrinaclokie** [mozilla/geckodriver#230] opened 2016-09-14 01:42 UTC
I'm using FF 48.0.2, GeckoDriver 0.10.0, and Selenium WebDriver 3.0.0-beta3

I see an exception when trying to locate elements by tagName. 

As an example, I can do:

```
    driver.getTitle();
```

But I cannot do:

```
    driver.findElement(By.tagName("title");
```

The latter fails with the exception:

```
org.openqa.selenium.NoSuchElementException: Unable to locate element: #title (WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 30.08 seconds
For documentation on this error, please visit: http://seleniumhq.org/exceptions/no_such_element.html
Build info: version: 'unknown', revision: 'c7b525d', time: '2016-09-01 14:57:44 -0700'
System info: host: '****', ip: '****', os.name: 'Windows 8.1', os.arch: 'amd64', os.version: '6.3', java.version: '1.8.0_45'
Driver info: org.openqa.selenium.firefox.FirefoxDriver
Capabilities [{rotatable=false, raisesAccessibilityExceptions=false, marionette=true, appBuildId=20160823121617, version=, platform=XP, proxy={}, command_id=1, specificationLevel=0, acceptSslCerts=false, browserVersion=48.0.2, platformVersion=6.3, XULappId={ec8030f7-c20a-464f-9b0e-13a3a9e97384}, browserName=Firefox, takesScreenshot=true, takesElementScreenshot=true, platformName=Windows_NT, device=desktop}]
Session ID: 7056ae06-98bb-4b09-94a0-6623e0a96b31
*** Element info: {Using=tag name, value=title}
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:422)
	at org.openqa.selenium.remote.ErrorHandler.createThrowable(ErrorHandler.java:206)
	at org.openqa.selenium.remote.ErrorHandler.throwIfResponseFailed(ErrorHandler.java:158)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:631)
	at org.openqa.selenium.remote.RemoteWebDriver.findElement(RemoteWebDriver.java:369)
	at org.openqa.selenium.remote.RemoteWebDriver.findElementByTagName(RemoteWebDriver.java:442)
	at org.openqa.selenium.By$ByTagName.findElement(By.java:334)
	at org.openqa.selenium.remote.RemoteWebDriver.findElement(RemoteWebDriver.java:361)
	at pages.LoginPage.landAt(LoginPage.java:39)
```

I can find elements successfully using other locators. e.g. id

**Comment by andreastt** [comment] 2016-09-14 11:09
From your stacktrace it looks like something is converting `title` to `#title` (tag name to CSS ID selector) and I’m guessing this is because the [WebDriver standard](http://w3c.github.io/webdriver/webdriver-spec.html), unlike Selenium, does not specify a tag name element selector. (The presumption is to use CSS selectors for that.)

To confirm that theory it would be good if you could also provide the verbose log output from geckodriver. You can get this by starting it with the `-vv` flag.

**Comment by zipperle** [comment] 2016-09-14 13:25
I have the same problem and found the root cause, the tag selector is falsely prefixed with the id selector. I have already submitted a pull request which fixes the bug.

**Comment by andreastt** [comment] 2016-09-14 14:23
@zipperle Thanks for fixing this!

**Comment by katrinaclokie** [comment] 2016-09-14 19:50
Thanks for the quick responses @andreastt and @zipperle 

I'll look forward to testing this change in the next release of geckodriver.

**Comment by zipperle** [comment] 2016-09-14 21:44
@katrinaclokie the problem lies with selenium, so you must wait for the next selenium release :)

**Comment by katrinaclokie** [comment] 2016-09-14 23:08
@zipperle Thank you! :)

**Comment by AutomatedTester** [comment] 2016-09-15 22:57
Closing this as it is fixed in selenium, waiting on their next release

**Closed by AutomatedTester** 2016-09-15 22:57 UTC
Labels: selenium
