### ISSUE TITLE
Second call to SetWindowRect with dimension larger than the screen resolution fails

### ISSUE THREAD

**Issue by JessefSpecialisterren** [mozilla/geckodriver#1326] opened 2018-07-12 14:09 UTC
Hey geckodriver people,

First of all: thanks for making an awesome product! We recently switched to geckodriver from chromedriver and have generally encountered much less trouble 🙂.

That said, we did run into an issue where our second test would hang on trying to set the window size to what it already was on our MacOS test server. I managed to isolate the issue and write minimal repro code. Hope you'll be able to fix it! We currently work around the issue by first maximizing the window and then setting it to the right size at the start of each test, in case someone else runs into this before it's fixed.

I hope the information below will be enough to help you fix the issue. If not, please let me know!

## System

* Version: 0.21.0
* Platform: MacOS High Sierra 10.13.4
* Firefox: Firefox Quantum 61.0.1 (64-bits)
* Selenium: Java bindings of 3.13.0

## Testcase
Java code:
```java
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.firefox.FirefoxDriverLogLevel;
import org.openqa.selenium.firefox.FirefoxOptions;

public class GeckodriverBug {
    public static void main(String[] args) {
        FirefoxOptions options = new FirefoxOptions();
        options.setLogLevel(FirefoxDriverLogLevel.TRACE);
        WebDriver driver = new FirefoxDriver(options);

        driver.manage().window().setSize(new Dimension(768, 1024));
        driver.manage().window().setSize(new Dimension(768, 1024));

        driver.quit();
    }
}
```

**Observed behavior:** the second `driver.manage().window().setSize(new Dimension(768, 1024));` call hangs indefinitely. This only appears happens on MacOS, and not when trying to set a more common window size like 1366x768.
**Expected behavior:** the second `driver.manage().window().setSize(new Dimension(768, 1024));` call returns (almost) immediately and program execution continues. This is how it behaves on Windows 10.

## Stacktrace

No errors or stacktraces, it just hangs on the second `driver.manage().window().setSize(new Dimension(768, 1024));` call.

## Trace-level log

```
1531402950742	geckodriver	INFO	geckodriver 0.21.0
1531402950751	geckodriver	INFO	Listening on 127.0.0.1:7050
1531402951056	mozrunner::runner	INFO	Running command: "/Applications/Firefox.app/Contents/MacOS/firefox-bin" "-marionette" "-foreground" "-no-remote" "-profile" "/var/folders/d4/fdnzyw9x6b7bg_0d037sf_4c0000gp/T/rust_mozprofile.dkNSud59KuRu"
1531402951057	geckodriver::marionette	DEBUG	Waiting 60s to connect to browser on 127.0.0.1:49934
1531402951809	Marionette	DEBUG	Received observer notification profile-after-change
1531402951916	Marionette	DEBUG	Received observer notification command-line-startup
1531402951917	Marionette	DEBUG	Received observer notification nsPref:changed
2018-07-12 15:42:32.857 plugin-container[815:18333] *** CFMessagePort: bootstrap_register(): failed 1100 (0x44c) 'Permission denied', port = 0x8543, name = 'com.apple.tsm.portname'
See /usr/include/servers/bootstrap_defs.h for the error codes.
2018-07-12 15:42:33.094 plugin-container[816:18357] *** CFMessagePort: bootstrap_register(): failed 1100 (0x44c) 'Permission denied', port = 0x6c3f, name = 'com.apple.tsm.portname'
See /usr/include/servers/bootstrap_defs.h for the error codes.
1531402953170	Marionette	DEBUG	Received observer notification sessionstore-windows-restored
1531402953293	Marionette	DEBUG	Setting recommended pref apz.content_response_timeout to 60000
1531402953293	Marionette	DEBUG	Setting recommended pref browser.download.panel.shown to true
1531402953293	Marionette	DEBUG	Setting recommended pref browser.pagethumbnails.capturing_disabled to true
1531402953294	Marionette	DEBUG	Setting recommended pref browser.search.update to false
1531402953295	Marionette	DEBUG	Setting recommended pref toolkit.cosmeticAnimations.enabled to false
1531402953295	Marionette	DEBUG	Setting recommended pref browser.tabs.disableBackgroundZombification to false
1531402953295	Marionette	DEBUG	Setting recommended pref browser.tabs.warnOnCloseOtherTabs to false
1531402953296	Marionette	DEBUG	Setting recommended pref browser.tabs.warnOnOpen to false
1531402953296	Marionette	DEBUG	Setting recommended pref browser.usedOnWindows10.introURL to 
1531402953296	Marionette	DEBUG	Setting recommended pref browser.urlbar.suggest.searches to false
1531402953297	Marionette	DEBUG	Setting recommended pref datareporting.policy.dataSubmissionPolicyAccepted to false
1531402953297	Marionette	DEBUG	Setting recommended pref dom.disable_beforeunload to true
1531402953297	Marionette	DEBUG	Setting recommended pref dom.disable_open_during_load to false
1531402953298	Marionette	DEBUG	Setting recommended pref dom.file.createInChild to true
1531402953298	Marionette	DEBUG	Setting recommended pref dom.max_chrome_script_run_time to 0
1531402953298	Marionette	DEBUG	Setting recommended pref dom.max_script_run_time to 0
1531402953298	Marionette	DEBUG	Setting recommended pref extensions.getAddons.cache.enabled to false
1531402953299	Marionette	DEBUG	Setting recommended pref extensions.webservice.discoverURL to http://%(server)s/dummy/discoveryURL
1531402953299	Marionette	DEBUG	Setting recommended pref network.http.prompt-temp-redirect to false
1531402953299	Marionette	DEBUG	Setting recommended pref network.http.speculative-parallel-limit to 0
1531402953299	Marionette	DEBUG	Setting recommended pref security.fileuri.strict_origin_policy to false
1531402953299	Marionette	DEBUG	Setting recommended pref security.notification_enable_delay to 0
1531402953299	Marionette	DEBUG	Setting recommended pref signon.autofillForms to false
1531402953299	Marionette	DEBUG	Setting recommended pref signon.rememberSignons to false
1531402953350	Marionette	DEBUG	New connections are accepted
1531402953350	Marionette	INFO	Listening on port 49934
1531402953410	geckodriver::marionette	DEBUG	Connected to Marionette on 127.0.0.1:49934
1531402953413	Marionette	DEBUG	Accepted connection 0 from 127.0.0.1:49962
1531402953424	Marionette	TRACE	0 -> [0,1,"WebDriver:NewSession",{"acceptInsecureCerts":true,"browserName":"firefox","capabilities":{"desiredCapabilities":{"acceptInsecureCerts":true,"browserName":"firefox"}}}]
1531402953424	Marionette	WARN	TLS certificate errors will be ignored for this session
1531402953468	Marionette	DEBUG	Register listener.js for window 4294967297
1531402953475	Marionette	TRACE	0 <- [1,1,null,{"sessionId":"69f55a4c-68fc-564e-a8a8-e350de751639","capabilities":{"browserName":"firefox","browserVersion":"61.0. ... bg_0d037sf_4c0000gp/T/rust_mozprofile.dkNSud59KuRu","moz:useNonSpecCompliantPointerOrigin":false,"moz:webdriverClick":true}}]
1531402953477	webdriver::server	DEBUG	<- 200 OK {"value": {"sessionId":"69f55a4c-68fc-564e-a8a8-e350de751639","capabilities":{"acceptInsecureCerts":true,"browserName":"firefox","browserVersion":"61.0.1","moz:accessibilityChecks":false,"moz:headless":false,"moz:processID":814,"moz:profile":"/var/folders/d4/fdnzyw9x6b7bg_0d037sf_4c0000gp/T/rust_mozprofile.dkNSud59KuRu","moz:useNonSpecCompliantPointerOrigin":false,"moz:webdriverClick":true,"pageLoadStrategy":"normal","platformName":"darwin","platformVersion":"17.5.0","rotatable":false,"timeouts":{"implicit":0,"pageLoad":300000,"script":30000}}}}
1531402953557	webdriver::server	DEBUG	-> POST /session/69f55a4c-68fc-564e-a8a8-e350de751639/window/rect {
  "width": 768,
  "height": 1024
}
1531402953571	Marionette	TRACE	0 -> [0,2,"WebDriver:SetWindowRect",{"height":1024,"width":768,"x":null,"y":null}]
1531402953718	Marionette	TRACE	0 <- [1,2,null,{"x":4,"y":23,"width":768,"height":812,"state":"normal"}]
1531402953718	webdriver::server	DEBUG	<- 200 OK {"value": {"height":812,"width":768,"x":4,"y":23}}
1531402953732	webdriver::server	DEBUG	-> POST /session/69f55a4c-68fc-564e-a8a8-e350de751639/window/rect {
  "width": 768,
  "height": 1024
}
1531402953733	Marionette	TRACE	0 -> [0,3,"WebDriver:SetWindowRect",{"height":1024,"width":768,"x":null,"y":null}]
2018-07-12 15:42:33.948 plugin-container[817:18462] *** CFMessagePort: bootstrap_register(): failed 1100 (0x44c) 'Permission denied', port = 0x7803, name = 'com.apple.tsm.portname'
See /usr/include/servers/bootstrap_defs.h for the error codes.
```

**Comment by andreastt** [comment] 2018-07-12 15:36
I should first say that our implementation of [Set Window Rect](https://w3c.github.io/webdriver/#dfn-set-window-rect) is known to not be 100% reliable. This is mainly due to the inherent async nature of window managers. WMs typically don’t give you any notification/callback when the window has been repositioned or resized, and although this is known to be a bigger problem on Linux (due to the async nature of the X11 protocol) it is not unexpected that it is also the case other platforms.

However the behaviour you describe where resize a window to 1024⨉768 and it hangs on a second invocation should not happen. Indeed, we have an explicit check in https://searchfox.org/mozilla-central/source/testing/marionette/driver.js#1485 to avoid this.

From the trace log you attached I note one strange thing: as Set Window Rect returns it carries with it the current window rect, and it reports it as 768⨉812 in your case. I suppose the window real estate is larger than 1024⨉768?

My initial reaction to this is that Marionette hangs because the window’s size is inaccurately reported as 768⨉812, which is obviously different to 1024⨉768. If the window then changes to 1024⨉768 after you’ve entered the promise waiting for the `resize` DOM event, you would not expect it to fire because the event only fires when the window actually resizes. This then means the first Set Window Rect call returns too soon, before the window has had time to resize itself.

Speaking from experience, there is an underlying problem in Gecko where retrieving the `ChromeWindow`’s `outerWidth`/`outerHeight` returns different values depending on from which thread/call context you are in. I still haven’t been able to track down the exact pattern to reproduce this problem, but it is not unlikely that this is why the first invocation of Set Window Rect is returning too soon.

**Comment by JessefSpecialisterren** [comment] 2018-07-13 08:14
Thanks for the quick reply! Some remarks/questions:

> 1024⨉768

Please note that we're setting the window size to _768x1024_, not 1024x768. This is to emulate a tablet in portrait mode.

> I suppose the window real estate is larger than 1024⨉768?

What exactly do you mean by this? At any rate, I took another look at the Firefox window opened by the repro code, and noticed that after the first resize it seemed to be clamped between the menu bar on top and the dock on bottom. Running `javascript:alert(window.outerHeight)` in the address bar yielded the same value that was returned in the trace log. I guess MacOS won't allow resizing windows beyond the available space. Could this be part of what causes this bug?

> waiting for the `resize` DOM event, you would not expect it to fire because the event only fires when the window actually resizes

I'm going to speculate here without knowing a thing about the code behind it, but could the following sequence of events be occurring:

1. On the second SetWindowRect call, the requested height differs from the actual window height, so a resize attempt is triggered
2. MacOS's WM limits the height just like it did for the first SetWindowRect call, resulting in no window size change, and therefore no `resize` DOM event
3. The SetWindowRect call is left waiting forever for a `resize` DOM event that is not going to happen

**Comment by andreastt** [comment] 2018-07-25 13:48
Filed https://bugzilla.mozilla.org/show_bug.cgi?id=1478358 to investigate this.

**Comment by Andriy-Smirnov** [comment] 2018-08-07 14:14
Hi Guys,
We've got a similar porblem for FirefoxPortable running on Windows Server 2012 R2 when trying to resize window size.
Error  seems to be in this line of code: OpenQA.Selenium.Remote.RemoteWindow.set_Size(Size value)

Environment:
Selenium 3.10.0
Gecko driver 0.21.0
Firefox portable to 61.0.1

Reported error example:
Test(s) failed. OpenQA.Selenium.WebDriverException : The HTTP request to the remote WebDriver server for URL http://localhost:57644/session/e3202dd0-f72f-46a8-948e-c899d63c06e8/window/rect timed out after 180 seconds.
  ----> System.Net.WebException : The operation has timed out
   at OpenQA.Selenium.Remote.HttpCommandExecutor.MakeHttpRequest(HttpRequestInfo requestInfo)
   at OpenQA.Selenium.Remote.HttpCommandExecutor.Execute(Command commandToExecute)
   at OpenQA.Selenium.Remote.DriverServiceCommandExecutor.Execute(Command commandToExecute)
   at OpenQA.Selenium.Remote.RemoteWebDriver.Execute(String driverCommandToExecute, Dictionary`2 parameters)
   at OpenQA.Selenium.Remote.RemoteWindow.set_Size(Size value)

**Comment by whimboo** [comment] 2018-11-09 10:13
I assume that the problem here is/was that the expected size never could have been reached and as such the command never returned. Now we take this into account and observe the `resize` events only, and return when no such event is caught anymore after a short moment.

@JessefSpecialisterren would you mind to test again with the most recent Nightly build of Firefox? I strongly believe your problem should be fixed now by the bug as created by @andreastt above. You can download such a build from https://www.mozilla.org/en-US/firefox/channel/desktop/#nightly. Thanks.

**Comment by JessefSpecialisterren** [comment] 2018-11-13 11:30
@whimboo Great to hear that something has been done about the problem 🎉! Things are very busy here right now, so though it's on my to-do list, it may be a while before I get around to testing it

**Comment by whimboo** [comment] 2018-11-14 08:08
So I tried to reproduce the problem, and I can still see it with latest Nightly. But it doesn't hang anymore, which is good. I updated the bug as mentioned by @andreastt above, to cover the remaining work to do.

**Comment by JessefSpecialisterren** [comment] 2018-11-15 11:42
@whimboo Thanks for looking into it! I read your comment on https://bugzilla.mozilla.org/show_bug.cgi?id=1478358, and noticed the following part:

> Only resize a window to a larger dimension if it hasn't reached its maximized state. As it looks like we perfectly detect that already.

There actually is a use case for resizing beyond the maximized state. Windows 10 allows resizing windows beyond the dimensions of the connected screen(s), which is very useful if you want to run a test on a specific resolution while on the go with a low laptop screen resolution. Losing this possibility would require a few people at this office to upgrade their hardware :wink:. Could that change be kept Mac-only, maybe?

**Comment by whimboo** [comment] 2018-11-16 08:00
Sure, we don't want to loose that either. It's all up for discussion in how to best solve it.

**Closed** 2019-01-30 09:06 UTC
Labels: marionette
