### ISSUE TITLE
Geckodriver done the process , but still rise an error 

### ISSUE THREAD

**Issue by Fenici** [mozilla/geckodriver#1027] opened 2017-10-24 05:39 UTC
## System
* Version:  0.19.0 
* Platform:  os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.12.6',
* Firefox:  56.0.1 (64-bit) 
* Selenium: < "org.seleniumhq.selenium" % "selenium-java" % "3.6.0" % "test",
  "org.seleniumhq.selenium"% "htmlunit-driver"% "2.27"% "test", 

## Testcase

Multi Browser Testing using Selenium

## Stacktrace

[error] Test automationFramework.GeckoDriver.selenium_ScreenShot failed: org.openqa.selenium.SessionNotCreatedException: Tried to run command without establishing a connection
[error] Build info: version: '3.6.0', revision: '6fbf3ec767', time: '2017-09-27T15:28:36.4Z'
[error] System info: host: 'YuDongs-MacBook-Pro.local', ip: 'fe80:0:0:0:14f0:36ba:2dd2:26fc%en0', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.12.6', java.version: '1.8.0_131'
[error] Driver info: org.openqa.selenium.firefox.FirefoxDriver
[error] Capabilities [{moz:profile=/var/folders/zl/xls4ndvn4jx6227zf5z_21rw0000gn/T/rust_mozprofile.zzM7wI7EuHX2, rotatable=false, timeouts={implicit=0, pageLoad=300000, script=30000}, pageLoadStrategy=normal, moz:headless=false, platform=MAC, specificationLevel=0, moz:accessibilityChecks=false, acceptInsecureCerts=true, browserVersion=56.0.1, platformVersion=16.7.0, moz:processID=41381, browserName=firefox, javascriptEnabled=true, platformName=MAC}]
[error] Session ID: 76053a68-6628-6641-9ee5-ded3669cd5d7, took 42.018 sec
[error]     at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[error]     at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
[error]     at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
[error]     at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
[error]     at org.openqa.selenium.remote.http.W3CHttpResponseCodec.createException(W3CHttpResponseCodec.java:185)
[error]     at org.openqa.selenium.remote.http.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:120)
[error]     at org.openqa.selenium.remote.http.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:49)
[error]     at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:164)
System Property Removing Key value.
[error]     at org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:83)
[error]     at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:586)
[error]     at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:643)
[error]     at org.openqa.selenium.remote.RemoteWebDriver.quit(RemoteWebDriver.java:482)
[error]     at automationFramework.GeckoDriver.test_Cleaning(GeckoDriver.java:60)
[error]     ...
[error] Failed: Total 1, Failed 1, Errors 0, Passed 0
[error] Failed tests:
[error]         automationFramework.GeckoDriver
[error] (test:testOnly) sbt.TestsFailedException: Tests unsuccessful
[error] Total time: 45 s, completed 24/10/2017 4:29:36 PM

**Comment by andreastt** [comment] 2017-10-24 14:51
As indicated in the stacktrace you pasted, `org.openqa.selenium.SessionNotCreatedException: Tried to run command without establishing a connection` would mean you haven’t started the session yet.

Could you please attach a [trace-level log] from geckodriver? Read more about reporting actionable bugs in our [contribution guidelines].

[trace-level log]: https://searchfox.org/mozilla-central/source/testing/geckodriver/doc/TraceLogs.md
[contribution guidelines]: https://searchfox.org/mozilla-central/source/testing/geckodriver/CONTRIBUTING.md#reporting-bugs

**Comment by Fenici** [comment] 2017-10-24 22:50
Oh well, I found issues are regarding with driver.close() , gecko driver doesn't recognise in firefox 
however it works on other browser like chrome , safari and Opera. I wondering why ?

**Comment by andreastt** [comment] 2017-10-25 07:42
Who knows? We won’t be able to find out what the problem is unless you attach a trace-level log.

Closing this because it is not actionable.

**Comment by andreastt** [comment] 2017-10-25 07:42
FWIW I’m happy to re-open once reproducible steps are added.

**Closed by andreastt** 2017-10-25 07:42 UTC
Labels: waiting for reporter feedback
