### ISSUE TITLE
geckodriver pending when a click automatically closes a popup

### ISSUE THREAD

**Issue by remidebette** [mozilla/geckodriver#783] opened 2017-06-14 08:02 UTC
Dear everyone,
With Firefox 54 released in the last days and the https://github.com/mozilla/geckodriver/issues/308 fix done, our tests have been greatly improved so thanks for the fix!

Unfortunately there is a regression for popups that close automatically when a button is clicked. 
e.g.: You fill a form in the popup and this updates the main page after closing.
(In comparison Chrome works fine)

The code is very simplistic but proves my case.

## Platform and application details
* Platform: Windows 7
* Python 3.6.1
* Selenium 3.4.3
* Firefox 54
* geckodriver 0.17.0
* Chrome 59
* chromedriver 2.30

## Steps to reproduce
Create two html files and a python script in the same directory:
page.html
```html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Sample Page</title>
</head>
<body>
    <a id="search_breed" onclick="foo = window.open('popup.html','name','height=400,width=500'); foo.focus(); return false;" href="#">
	<span>Opens the Popup</span>
    </a>
</body>
</html>
```
pop_up.html
```html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Popup</title>
</head>
<body>
    <a id="found_breed" onclick="window.close();" href="#">
        <span>Closes the Popup</span>
    </a>
</body>
</html>
```
script.py
```python
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait

driver = webdriver.Firefox()  # This fails since Firefox 54
# driver = webdriver.Chrome()  # This succeeds

driver.get("file:///C:/..................../sample.html")
handle_page = driver.window_handles[0]

# The following button opens a popup
button = driver.find_element(By.ID, "search_breed")
button.click()

pop_up_handle = driver.window_handles[1]
driver.switch_to.window(pop_up_handle)

# By clicking the following button, the popup automatically closes
locator = (By.ID, 'found_breed')

WebDriverWait(driver, 10).until(expected_conditions.presence_of_element_located(locator))
button = driver.find_element(*locator)

# With Firefox 54 this command never finishes
button.click()


driver.switch_to.window(handle_page)

pass

```

- [x] Reproducable testcase:
Execute the script

**Comment by andreastt** [comment] 2017-06-14 16:44
It would be useful if you attached the trace-level log from geckodriver. It would help diagnosing the issue.

Also cc’ing @whimboo as he’s done work in this area.

**Comment by whimboo** [comment] 2017-06-14 18:32
Dupe of issue #611.

**Closed by whimboo** 2017-06-14 18:32 UTC
