### ISSUE TITLE
Hang on clicking element that closes window

### ISSUE THREAD

**Issue by barancev** [mozilla/geckodriver#611] opened 2017-04-07 10:41 UTC
## Firefox Version
55.0a1 (2017-04-06) (64-bit)
geckodriver 0.15

## Platform
Windows 7

## Steps to reproduce
Selenium Java test WindowSwitchingTest.testClickingOnAButtonThatClosesAnOpenWindowDoesNotCauseTheBrowserToHang, the main part is:
```
    driver.findElement(By.name("windowThree")).click(); // opens a new window
    wait.until(newWindowIsOpened(currentWindowHandles));
    driver.switchTo().window("result");
    wait.until(ExpectedConditions.presenceOfElementLocated(By.id("close")));
    driver.findElement(By.id("close")).click(); // this button closes the window
```

Trace (note the time difference between click command end the error response):
```
1491560691433	webdriver::server	DEBUG	Got request POST AbsolutePath("/session/39295c18-795a-4fd0-9376-fe04e5f629f9/element/f85e52f2-3959-45f3-90a8-40a071ad8e03/click")
1491560691434	webdriver::command	DEBUG	Got request body {"id":"f85e52f2-3959-45f3-90a8-40a071ad8e03"}
1491560691434	geckodriver::marionette	DEBUG	→ 67:[0,20,"clickElement",{"id":"f85e52f2-3959-45f3-90a8-40a071ad8e03"}]
1491560691435	Marionette	TRACE	0 -> [0,20,"clickElement",{"id":"f85e52f2-3959-45f3-90a8-40a071ad8e03"}]
*************************
A coding exception was thrown and uncaught in a Task.

Full message: TypeError: NetworkError when attempting to fetch resource.
Full stack: 
*************************
1491561553403	webdriver::server	DEBUG	Deleting session
1491561553403	geckodriver::marionette	DEBUG	Stopping browser process
1491561553600	webdriver::server	DEBUG	Returning status InternalServerError
1491561553600	webdriver::server	DEBUG	Returning body {"value":{"error":"unknown error","message":"Failed to decode response from marionette","stacktrace":"stack backtrace:\n   0:           0x61f07f - <no info>\n   1:           0x61fe59 - <no info>\n   2:           0x41f9e2 - <no info>\n   3:           0x408307 - <no info>\n   4:           0x6750f9 - <no info>\n   5:           0x416877 - <no info>\n   6:           0x66ed53 - <no info>\n   7:         0x76da59cd - BaseThreadInitThunk"}}
```

**Comment by andreastt** [comment] 2017-04-07 13:28
This is https://bugzilla.mozilla.org/show_bug.cgi?id=1223277.

**Comment by barancev** [comment] 2017-04-07 14:49
Sorry for not checking for duplicates... May be #320 is related too.

**Comment by andreastt** [comment] 2017-04-10 16:45
The `Failed to decode response from marionette` error is slightly surprising. It basically means Marionette is sending something that geckodriver fails to decode.

Can you provide a trace-level log?

**Comment by barancev** [comment] 2017-04-12 18:03
Trying to reproduce the issue in today's Nightly I can't get the same error, it just hangs on click:
![2017-04-12_20-57-15](https://cloud.githubusercontent.com/assets/617090/24972112/dea61d38-1fc2-11e7-8a72-77063b94794c.png)

The trace log of the mentioned Java test is:
```
1492019500449	geckodriver	INFO	Listening on 127.0.0.1:9475

1492019501055	webdriver::server	DEBUG	Got request POST AbsolutePath("/session")
1492019501055	webdriver::command	DEBUG	Got request body {
  "desiredCapabilities": {
    "nativeEvents": false,
    "firefox_binary": {
      "extraEnv": {},
      "hCode": 1738236591,
      "class": "org.openqa.selenium.firefox.FirefoxBinary",
      "timeout": 45000
    },
    "marionette": true,
    "acceptInsecureCerts": true,
    "browserName": "firefox",
    "moz:firefoxOptions": {
      "binary": "c:\\Program Files\\Nightly\\firefox.exe",
      "prefs": {},
      "args": []
    },
    "version": "",
    "platform": "ANY"
  },
  "requiredCapabilities": {},
  "capabilities": {
    "desiredCapabilities": {
      "nativeEvents": false,
      "firefox_binary": {
        "extraEnv": {},
        "hCode": 1738236591,
        "class": "org.openqa.selenium.firefox.FirefoxBinary",
        "timeout": 45000
      },
      "marionette": true,
      "acceptInsecureCerts": true,
      "browserName": "firefox",
      "moz:firefoxOptions": {
        "binary": "c:\\Program Files\\Nightly\\firefox.exe",
        "prefs": {},
        "args": []
      },
      "version": "",
      "platform": "ANY"
    },
    "requiredCapabilities": {},
    "alwaysMatch": {
      "acceptInsecureCerts": true
    },
    "firstMatch": [
      {
        "browserName": "firefox",
        "moz:firefoxOptions": {
          "binary": "c:\\Program Files\\Nightly\\firefox.exe",
          "prefs": {},
          "args": []
        }
      }
    ]
  }
}
1492019501082	mozprofile::profile	INFO	Using profile path C:\Users\alexei\AppData\Local\Temp\rust_mozprofile.KjhWkhnEF8Kx
1492019501084	geckodriver::marionette	INFO	Starting browser c:\Program Files\Nightly\firefox.exe with args []
1492019501101	geckodriver::marionette	INFO	Connecting to Marionette on localhost:54089
1492019501707	Marionette	WARN	Deprecated preference marionette.defaultPrefs.enabled detected, please use marionette.enabled
1492019502101	geckodriver::marionette	DEBUG	  connection attempt 0/600
[Child 18348] WARNING: pipe error: 109: file c:/builds/moz2_slave/m-cen-w64-ntly-000000000000000/build/src/ipc/chromium/src/chrome/common/ipc_channel_win.cc, line 346
1492019503200	geckodriver::marionette	DEBUG	  connection attempt 1/600
1492019503311	Marionette	DEBUG	Setting recommended pref datareporting.policy.dataSubmissionPolicyAccepted to false
1492019503312	Marionette	INFO	Listening on port 54089
1492019503799	geckodriver::marionette	DEBUG	TCP connection established
1492019503802	Marionette	DEBUG	Accepted connection 0 from 127.0.0.1:54100
1492019503802	geckodriver::marionette	DEBUG	← {"applicationType":"gecko","marionetteProtocol":3}
1492019503802	geckodriver::marionette	DEBUG	→ 344:[0,1,"newSession",{"capabilities":{"desiredCapabilities":{"acceptInsecureCerts":true,"browserName":"firefox","firefox_binary":{"class":"org.openqa.selenium.firefox.FirefoxBinary","extraEnv":{},"hCode":1738236591,"timeout":45000},"marionette":true,"nativeEvents":false,"platform":"ANY","version":""},"requiredCapabilities":{}},"sessionId":null}]
1492019503804	Marionette	TRACE	0 -> [0,1,"newSession",{"capabilities":{"desiredCapabilities":{"acceptInsecureCerts":true,"browserName":"firefox","firefox_binary":{"class":"org.openqa.selenium.firefox.FirefoxBinary","extraEnv":{},"hCode":1738236591,"timeout":45000},"marionette":true,"nativeEvents":false,"platform":"ANY","version":""},"requiredCapabilities":{}},"sessionId":null}]
1492019503807	Marionette	CONFIG	Matched capabilities: {"browserName":"firefox","browserVersion":"55.0a1","platformName":"windows_nt","platformVersion":"6.1","pageLoadStrategy":"normal","acceptInsecureCerts":true,"timeouts":{"implicit":0,"pageLoad":300000,"script":30000},"rotatable":false,"specificationLevel":0,"moz:processID":48552,"moz:profile":"C:\\Users\\alexei\\AppData\\Local\\Temp\\rust_mozprofile.KjhWkhnEF8Kx","moz:accessibilityChecks":false}
1492019503807	Marionette	WARN	TLS certificate errors will be ignored for this session
1492019503857	Marionette	TRACE	0 <- [1,1,null,{"sessionId":"702233be-56b3-4941-a8ce-e427a7790e00","capabilities":{"browserName":"firefox","browserVersion":"55.0a1","platformName":"windows_nt","platformVersion":"6.1","pageLoadStrategy":"normal","acceptInsecureCerts":true,"timeouts":{"implicit":0,"pageLoad":300000,"script":30000},"rotatable":false,"specificationLevel":0,"moz:processID":48552,"moz:profile":"C:\\Users\\alexei\\AppData\\Local\\Temp\\rust_mozprofile.KjhWkhnEF8Kx","moz:accessibilityChecks":false}}]
1492019503861	geckodriver::marionette	DEBUG	← [1,1,null,{"sessionId":"702233be-56b3-4941-a8ce-e427a7790e00","capabilities":{"browserName":"firefox","browserVersion":"55.0a1","platformName":"windows_nt","platformVersion":"6.1","pageLoadStrategy":"normal","acceptInsecureCerts":true,"timeouts":{"implicit":0,"pageLoad":300000,"script":30000},"rotatable":false,"specificationLevel":0,"moz:processID":48552,"moz:profile":"C:\\Users\\alexei\\AppData\\Local\\Temp\\rust_mozprofile.KjhWkhnEF8Kx","moz:accessibilityChecks":false}}]
1492019503861	webdriver::server	DEBUG	Returning status Ok
1492019503861	webdriver::server	DEBUG	Returning body {"value": {"sessionId":"702233be-56b3-4941-a8ce-e427a7790e00","value":{"acceptInsecureCerts":true,"browserName":"firefox","browserVersion":"55.0a1","moz:accessibilityChecks":false,"moz:processID":48552,"moz:profile":"C:\\Users\\alexei\\AppData\\Local\\Temp\\rust_mozprofile.KjhWkhnEF8Kx","pageLoadStrategy":"normal","platformName":"windows_nt","platformVersion":"6.1","rotatable":false,"specificationLevel":0,"timeouts":{"implicit":0,"pageLoad":300000,"script":30000}}}}

1492019503896	webdriver::server	DEBUG	Got request GET AbsolutePath("/session/702233be-56b3-4941-a8ce-e427a7790e00/window")
1492019503896	geckodriver::marionette	DEBUG	→ 26:[0,2,"getWindowHandle",{}]
1492019503913	Marionette	TRACE	0 -> [0,2,"getWindowHandle",{}]
1492019503914	Marionette	TRACE	0 <- [1,2,null,{"value":"4294967297"}]
1492019503915	geckodriver::marionette	DEBUG	← [1,2,null,{"value":"4294967297"}]
1492019503915	webdriver::server	DEBUG	Returning status Ok
1492019503915	webdriver::server	DEBUG	Returning body {"value":"4294967297"}

1492019504475	webdriver::server	DEBUG	Got request POST AbsolutePath("/session/702233be-56b3-4941-a8ce-e427a7790e00/url")
1492019504475	webdriver::command	DEBUG	Got request body {"url":"http://comp1:47653/common/xhtmlTest.html"}
1492019504475	geckodriver::marionette	DEBUG	→ 62:[0,3,"get",{"url":"http://comp1:47653/common/xhtmlTest.html"}]
1492019504477	Marionette	TRACE	0 -> [0,3,"get",{"url":"http://comp1:47653/common/xhtmlTest.html"}]
1492019504683	Marionette	TRACE	0 <- [1,3,null,{}]
1492019504692	geckodriver::marionette	DEBUG	← [1,3,null,{}]
1492019504692	webdriver::server	DEBUG	Returning status Ok
1492019504692	webdriver::server	DEBUG	Returning body {"value": {}}

1492019504708	webdriver::server	DEBUG	Got request POST AbsolutePath("/session/702233be-56b3-4941-a8ce-e427a7790e00/execute/sync")
1492019504709	webdriver::command	DEBUG	Got request body {"script":"return navigator.userAgent;","args":[]}
1492019504709	geckodriver::marionette	DEBUG	→ 134:[0,4,"executeScript",{"args":[],"newSandbox":false,"script":"return navigator.userAgent;","scriptTimeout":null,"specialPowers":false}]
1492019504711	Marionette	TRACE	0 -> [0,4,"executeScript",{"args":[],"newSandbox":false,"script":"return navigator.userAgent;","scriptTimeout":null,"specialPowers":false}]
1492019504724	Marionette	TRACE	0 <- [1,4,null,{"value":"Mozilla/5.0 (Windows NT 6.1; Win64; x64; rv:55.0) Gecko/20100101 Firefox/55.0"}]
1492019504723	geckodriver::marionette	DEBUG	← [1,4,null,{"value":"Mozilla/5.0 (Windows NT 6.1; Win64; x64; rv:55.0) Gecko/20100101 Firefox/55.0"}]
1492019504723	webdriver::server	DEBUG	Returning status Ok
1492019504723	webdriver::server	DEBUG	Returning body {"value":"Mozilla/5.0 (Windows NT 6.1; Win64; x64; rv:55.0) Gecko/20100101 Firefox/55.0"}

1492019504731	webdriver::server	DEBUG	Got request POST AbsolutePath("/session/702233be-56b3-4941-a8ce-e427a7790e00/execute/sync")
1492019504731	webdriver::command	DEBUG	Got request body {"script":"return navigator.userAgent;","args":[]}
1492019504731	geckodriver::marionette	DEBUG	→ 134:[0,5,"executeScript",{"args":[],"newSandbox":false,"script":"return navigator.userAgent;","scriptTimeout":null,"specialPowers":false}]
1492019504733	Marionette	TRACE	0 -> [0,5,"executeScript",{"args":[],"newSandbox":false,"script":"return navigator.userAgent;","scriptTimeout":null,"specialPowers":false}]
1492019504741	Marionette	TRACE	0 <- [1,5,null,{"value":"Mozilla/5.0 (Windows NT 6.1; Win64; x64; rv:55.0) Gecko/20100101 Firefox/55.0"}]
1492019504741	geckodriver::marionette	DEBUG	← [1,5,null,{"value":"Mozilla/5.0 (Windows NT 6.1; Win64; x64; rv:55.0) Gecko/20100101 Firefox/55.0"}]
1492019504741	webdriver::server	DEBUG	Returning status Ok
1492019504741	webdriver::server	DEBUG	Returning body {"value":"Mozilla/5.0 (Windows NT 6.1; Win64; x64; rv:55.0) Gecko/20100101 Firefox/55.0"}

1492019504747	webdriver::server	DEBUG	Got request GET AbsolutePath("/session/702233be-56b3-4941-a8ce-e427a7790e00/window/handles")
1492019504747	geckodriver::marionette	DEBUG	→ 27:[0,6,"getWindowHandles",{}]
1492019504749	Marionette	TRACE	0 -> [0,6,"getWindowHandles",{}]
1492019504750	Marionette	TRACE	0 <- [1,6,null,["4294967297"]]
1492019504750	geckodriver::marionette	DEBUG	← [1,6,null,["4294967297"]]
1492019504750	webdriver::server	DEBUG	Returning status Ok
1492019504750	webdriver::server	DEBUG	Returning body {"value":["4294967297"]}

1492019504759	webdriver::server	DEBUG	Got request POST AbsolutePath("/session/702233be-56b3-4941-a8ce-e427a7790e00/element")
1492019504759	webdriver::command	DEBUG	Got request body {"value":"*[name='windowThree']","using":"css selector"}
1492019504759	geckodriver::marionette	DEBUG	→ 76:[0,7,"findElement",{"using":"css selector","value":"*[name='windowThree']"}]
1492019504761	Marionette	TRACE	0 -> [0,7,"findElement",{"using":"css selector","value":"*[name='windowThree']"}]
1492019504766	Marionette	TRACE	0 <- [1,7,null,{"value":{"element-6066-11e4-a52e-4f735466cecf":"990f682c-815f-46df-a15b-271112415918","ELEMENT":"990f682c-815f-46df-a15b-271112415918"}}]
1492019504765	geckodriver::marionette	DEBUG	← [1,7,null,{"value":{"element-6066-11e4-a52e-4f735466cecf":"990f682c-815f-46df-a15b-271112415918","ELEMENT":"990f682c-815f-46df-a15b-271112415918"}}]
1492019504766	webdriver::server	DEBUG	Returning status Ok
1492019504766	webdriver::server	DEBUG	Returning body {"value":{"element-6066-11e4-a52e-4f735466cecf":"990f682c-815f-46df-a15b-271112415918"}}

1492019504777	webdriver::server	DEBUG	Got request POST AbsolutePath("/session/702233be-56b3-4941-a8ce-e427a7790e00/element/990f682c-815f-46df-a15b-271112415918/click")
1492019504777	webdriver::command	DEBUG	Got request body {"id":"990f682c-815f-46df-a15b-271112415918"}
1492019504777	geckodriver::marionette	DEBUG	→ 66:[0,8,"clickElement",{"id":"990f682c-815f-46df-a15b-271112415918"}]
1492019504779	Marionette	TRACE	0 -> [0,8,"clickElement",{"id":"990f682c-815f-46df-a15b-271112415918"}]
1492019504818	Marionette	TRACE	0 <- [1,8,null,{}]
1492019504818	geckodriver::marionette	DEBUG	← [1,8,null,{}]
1492019504818	webdriver::server	DEBUG	Returning status Ok
1492019504818	webdriver::server	DEBUG	Returning body {"value": {}}

1492019504826	webdriver::server	DEBUG	Got request GET AbsolutePath("/session/702233be-56b3-4941-a8ce-e427a7790e00/window/handles")
1492019504826	geckodriver::marionette	DEBUG	→ 27:[0,9,"getWindowHandles",{}]
1492019504845	Marionette	DEBUG	loaded listener.js
1492019504890	Marionette	TRACE	0 -> [0,9,"getWindowHandles",{}]
1492019504891	Marionette	TRACE	0 <- [1,9,null,["4294967297"]]
1492019504910	geckodriver::marionette	DEBUG	← [1,9,null,["4294967297"]]
1492019504910	webdriver::server	DEBUG	Returning status Ok
1492019504910	webdriver::server	DEBUG	Returning body {"value":["4294967297"]}

1492019505420	webdriver::server	DEBUG	Got request GET AbsolutePath("/session/702233be-56b3-4941-a8ce-e427a7790e00/window/handles")
1492019505421	geckodriver::marionette	DEBUG	→ 28:[0,10,"getWindowHandles",{}]
1492019505422	Marionette	TRACE	0 -> [0,10,"getWindowHandles",{}]
1492019505423	Marionette	TRACE	0 <- [1,10,null,["4294967297","4294967301"]]
1492019505423	geckodriver::marionette	DEBUG	← [1,10,null,["4294967297","4294967301"]]
1492019505423	webdriver::server	DEBUG	Returning status Ok
1492019505423	webdriver::server	DEBUG	Returning body {"value":["4294967297","4294967301"]}

1492019505432	webdriver::server	DEBUG	Got request POST AbsolutePath("/session/702233be-56b3-4941-a8ce-e427a7790e00/window")
1492019505432	webdriver::command	DEBUG	Got request body {"handle":"result"}
1492019505432	geckodriver::marionette	DEBUG	→ 41:[0,11,"switchToWindow",{"name":"result"}]
1492019505435	Marionette	TRACE	0 -> [0,11,"switchToWindow",{"name":"result"}]
1492019505438	Marionette	TRACE	0 <- [1,11,{"error":"no such window","message":"Unable to locate window: result","stacktrace":"WebDriverError@chrome://marionette/content/error.js:211:5\nNoSuchWindowError@chrome://marionette/content/error.js:413:5\nGeckoDriver.prototype.switchToWindow@chrome://marionette/content/driver.js:1425:11\nTaskImpl_run@resource://gre/modules/Task.jsm:319:42\nTaskImpl@resource://gre/modules/Task.jsm:277:3\nasyncFunction@resource://gre/modules/Task.jsm:252:14\nTask_spawn@resource://gre/modules/Task.jsm:166:12\nTaskImpl_handleResultValue@resource://gre/modules/Task.jsm:389:16\nTaskImpl_run@resource://gre/modules/Task.jsm:327:15\nTaskImpl@resource://gre/modules/Task.jsm:277:3\nasyncFunction@resource://gre/modules/Task.jsm:252:14\nTask_spawn@resource://gre/modules/Task.jsm:166:12\nexecute@chrome://marionette/content/server.js:500:15\nonPacket@chrome://marionette/content/server.js:471:7\n_onJSONObjectReady/<@chrome://marionette/content/server.js -> resource://devtools/shared/transport/transport.js:483:11\nexports.makeInfallible/<@resource://gre/modules/commonjs/toolkit/loader.js -> resource://devtools/shared/ThreadSafeDevToolsUtils.js:101:14\nexports.makeInfallible/<@resource://gre/modules/commonjs/toolkit/loader.js -> resource://devtools/shared/ThreadSafeDevToolsUtils.js:101:14\n"},null]
1492019505438	geckodriver::marionette	DEBUG	← [1,11,{"error":"no such window","message":"Unable to locate window: result","stacktrace":"WebDriverError@chrome://marionette/content/error.js:211:5\nNoSuchWindowError@chrome://marionette/content/error.js:413:5\nGeckoDriver.prototype.switchToWindow@chrome://marionette/content/driver.js:1425:11\nTaskImpl_run@resource://gre/modules/Task.jsm:319:42\nTaskImpl@resource://gre/modules/Task.jsm:277:3\nasyncFunction@resource://gre/modules/Task.jsm:252:14\nTask_spawn@resource://gre/modules/Task.jsm:166:12\nTaskImpl_handleResultValue@resource://gre/modules/Task.jsm:389:16\nTaskImpl_run@resource://gre/modules/Task.jsm:327:15\nTaskImpl@resource://gre/modules/Task.jsm:277:3\nasyncFunction@resource://gre/modules/Task.jsm:252:14\nTask_spawn@resource://gre/modules/Task.jsm:166:12\nexecute@chrome://marionette/content/server.js:500:15\nonPacket@chrome://marionette/content/server.js:471:7\n_onJSONObjectReady/<@chrome://marionette/content/server.js -> resource://devtools/shared/transport/transport.js:483:11\nexports.makeInfallible/<@resource://gre/modules/commonjs/toolkit/loader.js -> resource://devtools/shared/ThreadSafeDevToolsUtils.js:101:14\nexports.makeInfallible/<@resource://gre/modules/commonjs/toolkit/loader.js -> resource://devtools/shared/ThreadSafeDevToolsUtils.js:101:14\n"},null]
1492019505438	webdriver::server	DEBUG	Returning status BadRequest
1492019505438	webdriver::server	DEBUG	Returning body {"value":{"error":"no such window","message":"Unable to locate window: result","stacktrace":"stack backtrace:\n   0:           0x61f07f - <no info>\n   1:           0x61fe59 - <no info>\n   2:           0x43b0b5 - <no info>\n   3:           0x420313 - <no info>\n   4:           0x408307 - <no info>\n   5:           0x6750f9 - <no info>\n   6:           0x416877 - <no info>\n   7:           0x66ed53 - <no info>\n   8:         0x76da59cd - BaseThreadInitThunk"}}

1492019505455	webdriver::server	DEBUG	Got request GET AbsolutePath("/session/702233be-56b3-4941-a8ce-e427a7790e00/window")
1492019505455	geckodriver::marionette	DEBUG	→ 27:[0,12,"getWindowHandle",{}]
1492019505456	Marionette	TRACE	0 -> [0,12,"getWindowHandle",{}]
1492019505457	Marionette	TRACE	0 <- [1,12,null,{"value":"4294967297"}]
1492019505457	geckodriver::marionette	DEBUG	← [1,12,null,{"value":"4294967297"}]
1492019505457	webdriver::server	DEBUG	Returning status Ok
1492019505457	webdriver::server	DEBUG	Returning body {"value":"4294967297"}

1492019505464	webdriver::server	DEBUG	Got request GET AbsolutePath("/session/702233be-56b3-4941-a8ce-e427a7790e00/window/handles")
1492019505464	geckodriver::marionette	DEBUG	→ 28:[0,13,"getWindowHandles",{}]
1492019505466	Marionette	TRACE	0 -> [0,13,"getWindowHandles",{}]
1492019505467	Marionette	TRACE	0 <- [1,13,null,["4294967297","4294967301"]]
1492019505466	geckodriver::marionette	DEBUG	← [1,13,null,["4294967297","4294967301"]]
1492019505466	webdriver::server	DEBUG	Returning status Ok
1492019505466	webdriver::server	DEBUG	Returning body {"value":["4294967297","4294967301"]}

1492019505473	webdriver::server	DEBUG	Got request POST AbsolutePath("/session/702233be-56b3-4941-a8ce-e427a7790e00/window")
1492019505473	webdriver::command	DEBUG	Got request body {"handle":"4294967297"}
1492019505473	geckodriver::marionette	DEBUG	→ 45:[0,14,"switchToWindow",{"name":"4294967297"}]
1492019505475	Marionette	TRACE	0 -> [0,14,"switchToWindow",{"name":"4294967297"}]
1492019505483	Marionette	TRACE	0 <- [1,14,null,{}]
1492019505491	geckodriver::marionette	DEBUG	← [1,14,null,{}]
1492019505491	webdriver::server	DEBUG	Returning status Ok
1492019505491	webdriver::server	DEBUG	Returning body {"value": {}}

1492019505498	webdriver::server	DEBUG	Got request POST AbsolutePath("/session/702233be-56b3-4941-a8ce-e427a7790e00/execute/sync")
1492019505498	webdriver::command	DEBUG	Got request body {"script":"return window.name","args":[]}
1492019505498	geckodriver::marionette	DEBUG	→ 126:[0,15,"executeScript",{"args":[],"newSandbox":false,"script":"return window.name","scriptTimeout":null,"specialPowers":false}]
1492019505499	Marionette	TRACE	0 -> [0,15,"executeScript",{"args":[],"newSandbox":false,"script":"return window.name","scriptTimeout":null,"specialPowers":false}]
1492019505510	Marionette	TRACE	0 <- [1,15,null,{"value":""}]
1492019505509	geckodriver::marionette	DEBUG	← [1,15,null,{"value":""}]
1492019505509	webdriver::server	DEBUG	Returning status Ok
1492019505509	webdriver::server	DEBUG	Returning body {"value":""}

1492019505516	webdriver::server	DEBUG	Got request POST AbsolutePath("/session/702233be-56b3-4941-a8ce-e427a7790e00/window")
1492019505517	webdriver::command	DEBUG	Got request body {"handle":"4294967301"}
1492019505517	geckodriver::marionette	DEBUG	→ 45:[0,16,"switchToWindow",{"name":"4294967301"}]
1492019505518	Marionette	TRACE	0 -> [0,16,"switchToWindow",{"name":"4294967301"}]
1492019505530	Marionette	TRACE	0 <- [1,16,null,{}]
1492019505533	geckodriver::marionette	DEBUG	← [1,16,null,{}]
1492019505533	webdriver::server	DEBUG	Returning status Ok
1492019505533	webdriver::server	DEBUG	Returning body {"value": {}}

1492019505542	webdriver::server	DEBUG	Got request POST AbsolutePath("/session/702233be-56b3-4941-a8ce-e427a7790e00/execute/sync")
1492019505543	webdriver::command	DEBUG	Got request body {"script":"return window.name","args":[]}
1492019505543	geckodriver::marionette	DEBUG	→ 126:[0,17,"executeScript",{"args":[],"newSandbox":false,"script":"return window.name","scriptTimeout":null,"specialPowers":false}]
1492019505545	Marionette	TRACE	0 -> [0,17,"executeScript",{"args":[],"newSandbox":false,"script":"return window.name","scriptTimeout":null,"specialPowers":false}]
1492019505549	Marionette	TRACE	0 <- [1,17,null,{"value":"result"}]
1492019505549	geckodriver::marionette	DEBUG	← [1,17,null,{"value":"result"}]
1492019505549	webdriver::server	DEBUG	Returning status Ok
1492019505549	webdriver::server	DEBUG	Returning body {"value":"result"}

1492019505558	webdriver::server	DEBUG	Got request POST AbsolutePath("/session/702233be-56b3-4941-a8ce-e427a7790e00/execute/sync")
1492019505558	webdriver::command	DEBUG	Got request body {"script":"return navigator.userAgent;","args":[]}
1492019505558	geckodriver::marionette	DEBUG	→ 135:[0,18,"executeScript",{"args":[],"newSandbox":false,"script":"return navigator.userAgent;","scriptTimeout":null,"specialPowers":false}]
1492019505560	Marionette	TRACE	0 -> [0,18,"executeScript",{"args":[],"newSandbox":false,"script":"return navigator.userAgent;","scriptTimeout":null,"specialPowers":false}]
1492019505564	Marionette	TRACE	0 <- [1,18,null,{"value":"Mozilla/5.0 (Windows NT 6.1; Win64; x64; rv:55.0) Gecko/20100101 Firefox/55.0"}]
1492019505563	geckodriver::marionette	DEBUG	← [1,18,null,{"value":"Mozilla/5.0 (Windows NT 6.1; Win64; x64; rv:55.0) Gecko/20100101 Firefox/55.0"}]
1492019505563	webdriver::server	DEBUG	Returning status Ok
1492019505563	webdriver::server	DEBUG	Returning body {"value":"Mozilla/5.0 (Windows NT 6.1; Win64; x64; rv:55.0) Gecko/20100101 Firefox/55.0"}

1492019505571	webdriver::server	DEBUG	Got request POST AbsolutePath("/session/702233be-56b3-4941-a8ce-e427a7790e00/elements")
1492019505572	webdriver::command	DEBUG	Got request body {"value":"#close","using":"css selector"}
1492019505572	geckodriver::marionette	DEBUG	→ 63:[0,19,"findElements",{"using":"css selector","value":"#close"}]
1492019505573	Marionette	TRACE	0 -> [0,19,"findElements",{"using":"css selector","value":"#close"}]
1492019505576	Marionette	TRACE	0 <- [1,19,null,[{"element-6066-11e4-a52e-4f735466cecf":"c9d38a91-450d-4413-b68d-522e4959049c","ELEMENT":"c9d38a91-450d-4413-b68d-522e4959049c"}]]
1492019505576	geckodriver::marionette	DEBUG	← [1,19,null,[{"element-6066-11e4-a52e-4f735466cecf":"c9d38a91-450d-4413-b68d-522e4959049c","ELEMENT":"c9d38a91-450d-4413-b68d-522e4959049c"}]]
1492019505576	webdriver::server	DEBUG	Returning status Ok
1492019505576	webdriver::server	DEBUG	Returning body {"value":[{"element-6066-11e4-a52e-4f735466cecf":"c9d38a91-450d-4413-b68d-522e4959049c"}]}

1492019505584	webdriver::server	DEBUG	Got request POST AbsolutePath("/session/702233be-56b3-4941-a8ce-e427a7790e00/element/c9d38a91-450d-4413-b68d-522e4959049c/click")
1492019505584	webdriver::command	DEBUG	Got request body {"id":"c9d38a91-450d-4413-b68d-522e4959049c"}
1492019505584	geckodriver::marionette	DEBUG	→ 67:[0,20,"clickElement",{"id":"c9d38a91-450d-4413-b68d-522e4959049c"}]
1492019505586	Marionette	TRACE	0 -> [0,20,"clickElement",{"id":"c9d38a91-450d-4413-b68d-522e4959049c"}]
```

**Comment by andreastt** [comment] 2017-04-18 17:07
I can’t see the “failed to decode message” error in the latest log, but I’m guessing that could be a side effect of the geckodriver process being killed after it has been inactive for too long or similar, and isn’t directly related to the issue.

In any case this appears to be https://bugzilla.mozilla.org/show_bug.cgi?id=1223277.

**Comment by whimboo** [comment] 2017-04-20 15:34
Dupe of issue #398.

**Comment by andreastt** [comment] 2017-04-21 06:23
This issue has better logs than https://github.com/mozilla/geckodriver/issues/398, so flipping the dupe relationship.

**Comment by whimboo** [comment] 2017-06-28 16:22
The feature should be finally available in the next Nightly build of Firefox. Given the complexity of the patch we most likely won't uplift it for Firefox 55.

**Closed by whimboo** 2017-06-28 16:22 UTC
Labels: marionette
