### ISSUE TITLE
Double Click not working 

### ISSUE THREAD

**Issue by rscwcd** [mozilla/geckodriver#773] opened 2017-06-07 06:26 UTC
Hi, 

We upgraded our system to use Gecko Driver(Version geckodriver-v0.16.1-win64) along with Selenium Web Driver(3.4.0) and FF 53.0. A feature called "Double Click" in our project is not working. We tried many different techniques but till now there is no success in hand. Also, we are not getting any error out of that. Below are the code that we are using to do so :

 protected T double_click(By locator) {
        WebElement clickable = findElement(ExpectedConditions.elementToBeClickable(locator));
        new Actions(driver).moveToElement(clickable).doubleClick(clickable).perform();
        return me();
    }

The above method is :-1: 
1) Able to find the element
2) Able to click on the element
3) Not able to generate double click event.
4) Rest other tests gets fail

The failure is not specific to any event or project but to all. Please advise.

**Comment by andreastt** [comment] 2017-06-07 10:35
Duplicate of https://github.com/mozilla/geckodriver/issues/661.

**Closed by andreastt** 2017-06-07 10:35 UTC

**Comment by rscwcd** [comment] 2017-06-07 10:44
@andreastt : Hi, yes,this issue is duplicate of many others issues in the forum but I did't find any solution over there. Request you to let us know the exact actions that can be taken to get out of this.

**Comment by andreastt** [comment] 2017-06-07 10:52
@rscwcd I haven’t had time to look into it yet.

**Comment by rscwcd** [comment] 2017-06-07 10:59
Okay. Please look into it whenever you get time, but i saw this issue has already been closed by you.

**Comment by rscwcd** [comment] 2017-06-08 05:55
@andreastt  : Hi, did you get time to look for this issue ? This is show stopper for our project.

**Comment by andreastt** [comment] 2017-06-08 18:24
@rscwcd I haven’t had time to look into https://github.com/mozilla/geckodriver/issues/661 yet.

**Comment by rscwcd** [comment] 2017-06-09 06:43
@andreastt : Hi, I have generated a new issue on Selenium Forum with below link 

[actions.moveToElement in Selenium does not scroll down the page #4148](url)

**Comment by vinhtc2000** [comment] 2017-06-11 15:35
@rscwcd I have met the same issue like you. You can use javascript to work around. Below are the Python script that I did:

executeScript = "var event = new MouseEvent('dblclick', {'view': window,'bubbles': true,'cancelable': true});document.evaluate(\"" + XPATH_VARIABLE + "\", document, null, XPathResult.FIRST_ORDERED_NODE_TYPE, null).singleNodeValue.dispatchEvent(event);"

driver.execute_script(executeScript)

====
XPATH_VARIABLE  <= the element's xpath
====

Hope this helps!

**Comment by CDJojn** [comment] 2017-06-13 13:17
@vinhtc2000 are you sure that code is working? I have tried very similar code with different kind of MouseEvent - "mouseover", "mouseenter" and "mousemove" and it is not working, because this dispatched event has set isTrusted set as false. In this case a lot of JS functionality on web doesn't work. Do you have any solution how to start Firefox without checking of isTrusted flag?

**Comment by vinhtc2000** [comment] 2017-06-14 16:05
@CDJojn I had not meet the same with your issue. My script works fine until now. I'm using:
- Firefox 53.0.3 (32 bit)
- Selenium 3.3.x
- Python 2.7.3

**Comment by BeschtaBrandon** [comment] 2017-06-14 20:11
I believe the double click issue is still occuring

**Comment by whimboo** [comment] 2017-06-19 21:34
In case there is any helpful information please add it to issue #661. It's not helpful to have to maintain two issues which handle the same topic.

To prevent more me too comments, I will lock down this one now. Thanks.
