### ISSUE TITLE
object null reference exception when typping OpenQA.Selenium.Keys.Tab to driver

### ISSUE THREAD

**Issue by ggja** [mozilla/geckodriver#939] opened 2017-09-08 12:40 UTC
## System
* Version:  0.18.0 
* Platform:  Windows 10 
* Firefox: 55.0.3 (32-bit) 
* Selenium: 3.5.1 

.Net application

## Testcase

send key OpenQA.Selenium.Keys.Tab to the driver there is current active element is not visible. (for example popup with input hided after the  last "tab" typing )

## Stacktrace
Object null reference exception :

 at OpenQA.Selenium.Remote.HttpCommandExecutor.Execute(Command commandToExecute)
   at OpenQA.Selenium.Remote.DriverServiceCommandExecutor.Execute(Command commandToExecute)
   at OpenQA.Selenium.Remote.RemoteWebDriver.Execute(String driverCommandToExecute, Dictionary`2 parameters)
   at OpenQA.Selenium.Remote.RemoteKeyboard.SendKeys(String keySequence)

**Comment by AutomatedTester** [comment] 2017-09-08 16:31
Unfortunately there is not much that we can do to solve this issue as it lacks html to reproduce, a GeckoDriver log or a script to reproduce. Closing this issue. 

If you add them to this issue we can see about reopening the issue.

**Closed by AutomatedTester** 2017-09-08 16:31 UTC

**Comment by darxis** [comment] 2018-01-09 18:38
Please reopen this issue, I have the same problem using just the code:
```c#
WebDriver.Keyboard.SendKeys(Keys.Space);
```
```
NullReferenceException
   at OpenQA.Selenium.Remote.HttpCommandExecutor.HttpRequestInfo..ctor(Uri serverUri, Command commandToExecute, CommandInfo commandInfo)
   at OpenQA.Selenium.Remote.HttpCommandExecutor.Execute(Command commandToExecute)
   at OpenQA.Selenium.Remote.DriverServiceCommandExecutor.Execute(Command commandToExecute)
   at OpenQA.Selenium.Remote.RemoteWebDriver.Execute(String driverCommandToExecute, Dictionary`2 parameters)
   at OpenQA.Selenium.Remote.RemoteKeyboard.SendKeys(String keySequence)
```

**Comment by andreastt** [comment] 2018-01-09 19:11
@darxis That seems like a problem with the Selenium client you’re using.

**Comment by yesinsky** [comment] 2018-01-23 18:23
This issue is still actual. Null reference exception is being thrown on any WebDriver.Keyboard.SendKeys(...); action.

**Comment by andreastt** [comment] 2018-01-23 21:40
@yesinsky Sure, but if you were to read the context of the issue you would realise it is not a bug in geckodriver, but in the client you are using. I would suggest reporting a bug there.
