### ISSUE TITLE
Exception Breakpoint error 

### ISSUE THREAD

**Issue by kcrump** [mozilla/geckodriver#339] opened 2016-11-15 18:48 UTC
I am using Windows 8 and Firefox 50.0.  The Gecko driver is failing my test with the below error. 
![mozillaerror](https://cloud.githubusercontent.com/assets/23484091/20318846/f9e26532-ab39-11e6-918c-6fd32c852dca.png)
Can someone please take a look? I have included my test that is failing as well. 
[testthatisfailing.txt](https://github.com/mozilla/geckodriver/files/592839/testthatisfailing.txt)

**Comment by andreastt** [comment] 2016-11-16 16:17
I believe this is a duplicate of https://github.com/mozilla/geckodriver/issues/210. Please try again with [Nightly](https://nightly.mozilla.org/).

**Closed by andreastt** 2016-11-16 16:17 UTC

**Comment by kcrump** [comment] 2016-11-16 18:36
@andreastt 

In the ticket that you mentioned (#210) line 2046 is mentioned in the error.   [Child 2760] ###!!! ABORT: Aborting on channel error.: file c:/builds/moz2_slave/m-rel-w32-00000000000000000000/build/src/ipc/glue/MessageChannel.cpp, line **2046**
Exception in thread "main" org.openqa.selenium.remote.UnreachableBrowserException: Error communicating with the remote browser. It may have died.


When looking in my logs line 2056 is mentioned in mine. 
Nov 16, 2016 1:28:53 PM org.openqa.selenium.remote.ProtocolHandshake createSession
INFO: Attempting bi-dialect session, assuming Postel's Law holds true on the remote end
1479320935956	Marionette	INFO	Listening on port 56659
Nov 16, 2016 1:28:59 PM org.openqa.selenium.remote.ProtocolHandshake createSession
INFO: Detected dialect: W3C
[Child 100804] ###!!! ABORT: Aborting on channel error.: file c:/builds/moz2_slave/m-rel-w32-00000000000000000000/build/src/ipc/glue/MessageChannel.cpp, line **2056**

**Comment by andreastt** [comment] 2016-11-17 16:22
That looks the same. You probably have a newer build and the source code line that causes the message to be printed has moved down a few lines.

But to be clear: This message from Firefox is nothing to worry about.

**Comment by andrey2good** [comment] 2017-03-06 15:13
Is there any workaround to move on over this error ? I am running multiple tests on the same machine and this is quite annoying. Also, why this is closed? 

You can quickly reproduce this error using the following versions:
 - windows 7
 - firefox 51.0.1 (32bit)
 - gecko_griver_0_14_0
 - selenium 3.0.1

**Comment by andreastt** [comment] 2017-03-06 15:24
This appears to be a duplicate of https://github.com/mozilla/geckodriver/issues/285, but no, we are not able to reproduce this issue. We believe https://bugzilla.mozilla.org/show_bug.cgi?id=1337743 may help.
