### ISSUE TITLE
Too much recursion in execute_script

### ISSUE THREAD

**Issue by shinglyu** [mozilla/geckodriver#328] opened 2016-11-10 06:00 UTC
Firefox Nightly 52.0a1 (2016-11-09)
geckodriver v0.11.1
python 3.4.3
selenium-3.0.1 (python)

When I run the code 

```
firefox_binary = "./firefox/firefox/firefox"                                 
driver = webdriver.Firefox(firefox_binary=firefox_binary)                    
driver.set_page_load_timeout(timeout)                                        
driver.get(testcase)            
timings = driver.execute_script("return performance.timing") 
```
it crashes with `WebDriverException: Message: too much recursions`

But the js code `return performance.timing` doesn't have any recursion.

The test case is the `www.dailymail.co.uk` page from [tp5](https://wiki.mozilla.org/Buildbot/Talos/Tests#tp5) test suite.

I'm not sure if it's a Marionette issue or geckodriver one, so I'm filing it here.

**Comment by andreastt** [comment] 2016-12-13 18:07
I’m unable to reproduce this using [Firefox Nightly](https://nightly.mozilla.org/). Can you provide the trace log from geckodriver?

**Comment by andreastt** [comment] 2016-12-13 18:25
From some exploratory testing I did with the Marionette client on central:

```
>>> session.navigate("http://www.dailymail.co.uk/")
>>> session.execute_script("return window.performance.timing")
{u'redirectStart': 0, u'domContentLoadedEventStart': 1481653390448, u'toJSON': {}, u'redirectEnd': 0, u'fetchStart': 1481653390290, u'navigationStart': 1481653390265, u'domainLookupEnd': 1481653390358, u'connectEnd': 1481653390360, u'unloadEventEnd': 0, u'requestStart': 1481653390406, u'responseEnd': 1481653390409, u'unloadEventStart': 0, u'domLoading': 1481653390412, u'loadEventEnd': 1481653390485, u'connectStart': 1481653390358, u'loadEventStart': 1481653390485, u'responseStart': 1481653390409, u'domContentLoadedEventEnd': 1481653390448, u'domComplete': 1481653390485, u'domInteractive': 1481653390446, u'domainLookupStart': 1481653390290}
```

Even returning `window.performance` works fine:

```
>>> session.execute_script("return window.performance")
{u'onresourcetimingbufferfull': None, u'timeOrigin': 1481653390265.2324, u'getEntries': {}, u'setResourceTimingBufferSize': {}, u'clearMeasures': {}, u'getEntriesByName': {}, u'mark': {}, u'clearMarks': {}, u'getEntriesByType': {}, u'now': {}, u'clearResourceTimings': {}, u'measure': {}, u'timing': {u'redirectStart': 0, u'domContentLoadedEventStart': 1481653390448, u'toJSON': {}, u'redirectEnd': 0, u'fetchStart': 1481653390290, u'navigationStart': 1481653390265, u'domainLookupEnd': 1481653390358, u'connectEnd': 1481653390360, u'unloadEventEnd': 0, u'requestStart': 1481653390406, u'responseEnd': 1481653390409, u'unloadEventStart': 0, u'domLoading': 1481653390412, u'loadEventEnd': 1481653390485, u'connectStart': 1481653390358, u'loadEventStart': 1481653390485, u'responseStart': 1481653390409, u'domContentLoadedEventEnd': 1481653390448, u'domComplete': 1481653390485, u'domInteractive': 1481653390446, u'domainLookupStart': 1481653390290}, u'toJSON': {}, u'navigation': {u'TYPE_RELOAD': 1, u'redirectCount': 0, u'TYPE_RESERVED': 255, u'toJSON': {}, u'type': 0, u'TYPE_BACK_FORWARD': 2, u'TYPE_NAVIGATE': 0}}
```

**Comment by andreastt** [comment] 2016-12-13 18:27
I noticed that `window.performance.timing` is a `PerformanceTiming` object that holds a `toJSON` method. Perhaps you will have greater luck returning `window.performance.timing.toJSON()`?

But in any case, I’m curious why returning the object doesn’t work for you. We should have a serialisation algorithm that supports dropping complex and recursive objects.

**Comment by AutomatedTester** [comment] 2017-01-18 17:13
closing as requested info has not been added

**Comment by andreastt** [comment] 2017-01-18 19:15
@AutomatedTester Maybe we can change WebDriver to always call `toJSON` on objects if it exists, like `JSON.stringify` does?

**Comment by shinglyu** [comment] 2017-03-06 07:49
Sorry for the late reply. I workedaround it with 
```
driver.execute_script("return JSON.stringify(performance.timing)")
```

basically the same as what you suggested.

**Comment by andreastt** [comment] 2017-03-06 13:46
I’ve proposed https://github.com/w3c/webdriver/issues/849 to the specification.

**Comment by whimboo** [comment] 2017-08-28 14:58
> I’ve proposed w3c/webdriver#849 to the specification.

That has been added a while ago. So I think we have to get this implemented in Marionette now? @andreastt if I'm wrong please let me know.

**Comment by andreastt** [comment] 2017-08-28 16:07
>> I’ve proposed w3c/webdriver#849 to the specification.
>
> That has been added a while ago. So I think we have to get this implemented in Marionette now? 

If you check the source, this is already in Marionette: https://searchfox.org/mozilla-central/rev/18c16ebf818abb86805ce08a6e537e4cd826f044/testing/marionette/evaluate.js#282-286

It was added in https://bugzilla.mozilla.org/show_bug.cgi?id=1363053, which ships in Firefox 55.

Closing this.

**Closed by andreastt** 2017-08-28 16:07 UTC
Labels: marionette
