### ISSUE TITLE
Marionette returns null when waiting for response from content frame script and a document unloads

### ISSUE THREAD

**Issue by jsa34** [mozilla/geckodriver#1350] opened 2018-08-13 10:28 UTC
## System

* Version: 0.21.0
* Platform: Linux
* Selenium: docker version 3.14.0, 3.13.0 (could be present with other releases, but only checked with these versions).

## Scenario

Trying to call findElement (a select type element) as part of a webdriverwait method call, throws the following error:

## Stacktrace

Aug 13, 2018 11:22:57 AM org.openqa.selenium.support.ui.ExpectedConditions findElement
WARNING: WebDriverException thrown by findElement(By.id: xxx)
org.openqa.selenium.WebDriverException: Failed to interpret value as array
Build info: version: '3.14.0', revision: 'aacccce0', time: '2018-08-02T20:19:58.91Z'
System info: host: '****', ip: '****', os.name: 'Linux', os.arch: 'amd64', os.version: '3.10.0-862.el7.x86_64', java.version: '1.8.0_161'
Driver info: org.openqa.selenium.remote.RemoteWebDriver
Capabilities {acceptInsecureCerts: true, browserName: firefox, browserVersion: 61.0.1, javascriptEnabled: true, moz:accessibilityChecks: false, moz:headless: false, moz:processID: 678, moz:profile: /tmp/rust_mozprofile.t5EIhs..., moz:useNonSpecCompliantPointerOrigin: false, moz:webdriverClick: true, pageLoadStrategy: normal, platform: LINUX, platformName: LINUX, platformVersion: 3.10.0-862.2.3.el7.x86_64, rotatable: false, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}, webdriver.remote.sessionid: aaaaaaaaaaaaaaaaaaaaaaaaaa}
Session ID: aaaaaaaaaaaaaaaaaaaaaaaaaa
*** Element info: {Using=id, value=xxx}
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.openqa.selenium.remote.http.W3CHttpResponseCodec.createException(W3CHttpResponseCodec.java:187)
	at org.openqa.selenium.remote.http.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:122)
	at org.openqa.selenium.remote.http.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:49)
	at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:158)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:548)
	at org.openqa.selenium.remote.RemoteWebDriver.findElements(RemoteWebDriver.java:349)
	at org.openqa.selenium.remote.RemoteWebDriver.findElementsById(RemoteWebDriver.java:372)
	at org.openqa.selenium.By$ById.findElements(By.java:180)
	at org.openqa.selenium.remote.RemoteWebDriver.findElements(RemoteWebDriver.java:310)
	at org.openqa.selenium.support.ui.ExpectedConditions.findElement(ExpectedConditions.java:895)
	at org.openqa.selenium.support.ui.ExpectedConditions.access$000(ExpectedConditions.java:44)
	at org.openqa.selenium.support.ui.ExpectedConditions$6.apply(ExpectedConditions.java:183)
	at org.openqa.selenium.support.ui.ExpectedConditions$6.apply(ExpectedConditions.java:180)
	at org.openqa.selenium.support.ui.FluentWait.until(FluentWait.java:260)
	at xxxxx.selectElementFromDropDown(Site.java:90)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at cucumber.runtime.Utils$1.call(Utils.java:26)
	at cucumber.runtime.Timeout.timeout(Timeout.java:16)
	at cucumber.runtime.Utils.invoke(Utils.java:20)
	at cucumber.runtime.java.JavaStepDefinition.execute(JavaStepDefinition.java:48)
	at cucumber.runtime.PickleStepDefinitionMatch.runStep(PickleStepDefinitionMatch.java:50)
	at cucumber.runner.TestStep.executeStep(TestStep.java:55)
	at cucumber.runner.TestStep.run(TestStep.java:42)
	at cucumber.runner.PickleStepTestStep.run(PickleStepTestStep.java:53)
	at cucumber.runner.TestCase.run(TestCase.java:47)
	at cucumber.runner.Runner.runPickle(Runner.java:44)
	at cucumber.api.testng.TestNGCucumberRunner.runScenario(TestNGCucumberRunner.java:56)
	at cucumber.api.testng.AbstractTestNGCucumberTests.runScenario(AbstractTestNGCucumberTests.java:22)
	at sun.reflect.GeneratedMethodAccessor99.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

## Trace-level log

[Parent 663, Gecko_IOThread] WARNING: pipe error (58): Connection reset by peer: file /builds/worker/workspace/build/src/ipc/chromium/src/chrome/common/ipc_channel_posix.cc, line 353

###!!! [Parent][MessageChannel] Error: (msgtype=0x16007F,name=PBrowser::Msg_Destroy) Channel error: cannot send/recv

1534160395964 webdriver::server DEBUG -> POST /session/aaaaaaaaaaaaaaaaaaaaaa/elements {
"value": "#xxxxxxxxxxxxxxxx",
"using": "css selector"
}
1534160395987 Marionette DEBUG Register listener.js for window 23
A content process crashed and MOZ_CRASHREPORTER_SHUTDOWN is set, shutting down
1534160396077 Marionette TRACE 0 -> [0,169,"WebDriver:FindElements",{"using":"css selector","value":"#xxxxxxxxxxxxxxxxxxxxx"}]
1534160396185 Marionette DEBUG Received DOM event unload for [object XULDocument]
1534160396195 Marionette DEBUG Received observer notification message-manager-disconnect
1534160396200 Marionette TRACE 0 <- [1,169,null,null]
1534160396206 webdriver::server DEBUG <- 500 Internal Server Error {"value":{"error":"unknown error","message":"Failed to interpret value as array","stacktrace":""}}
1534160396222 webdriver::server DEBUG -> GET /session/aaaaaaaaaaaaaaaaaaaaaaaaaaaa/screenshot
1534160396222 webdriver::server DEBUG Deleting session
1534160396235 Marionette DEBUG Closed connection 0
*** UTM:SVC TimerManager:registerTimer called after profile-before-change notification. Ignoring timer registration for id: telemetry_modules_ping
1534160396574 Marionette DEBUG Received observer notification xpcom-will-shutdown
1534160396574 Marionette DEBUG Resetting recommended pref apz.content_response_timeout
1534160396574 Marionette DEBUG Resetting recommended pref browser.download.panel.shown
1534160396575 Marionette DEBUG Resetting recommended pref browser.pagethumbnails.capturing_disabled
1534160396575 Marionette DEBUG Resetting recommended pref browser.search.update
1534160396575 Marionette DEBUG Resetting recommended pref toolkit.cosmeticAnimations.enabled
1534160396575 Marionette DEBUG Resetting recommended pref browser.tabs.disableBackgroundZombification
1534160396576 Marionette DEBUG Resetting recommended pref browser.tabs.warnOnCloseOtherTabs
1534160396576 Marionette DEBUG Resetting recommended pref browser.tabs.warnOnOpen
1534160396576 Marionette DEBUG Resetting recommended pref browser.usedOnWindows10.introURL
1534160396576 Marionette DEBUG Resetting recommended pref browser.urlbar.suggest.searches
1534160396576 Marionette DEBUG Resetting recommended pref datareporting.policy.dataSubmissionPolicyAccepted
1534160396577 Marionette DEBUG Resetting recommended pref dom.disable_beforeunload
1534160396577 Marionette DEBUG Resetting recommended pref dom.disable_open_during_load
1534160396577 Marionette DEBUG Resetting recommended pref dom.file.createInChild
1534160396577 Marionette DEBUG Resetting recommended pref dom.max_chrome_script_run_time
1534160396577 Marionette DEBUG Resetting recommended pref dom.max_script_run_time
1534160396577 Marionette DEBUG Resetting recommended pref extensions.getAddons.cache.enabled
1534160396577 Marionette DEBUG Resetting recommended pref extensions.webservice.discoverURL
1534160396577 Marionette DEBUG Resetting recommended pref network.http.prompt-temp-redirect
1534160396577 Marionette DEBUG Resetting recommended pref network.http.speculative-parallel-limit
1534160396577 Marionette DEBUG Resetting recommended pref security.fileuri.strict_origin_policy
1534160396577 Marionette DEBUG Resetting recommended pref security.notification_enable_delay
1534160396578 Marionette DEBUG Resetting recommended pref signon.autofillForms
1534160396578 Marionette DEBUG Resetting recommended pref signon.rememberSignons
1534160396578 Marionette DEBUG New connections will no longer be accepted
1534160397033 geckodriver::marionette DEBUG Browser process stopped: exit code: 0
1534160397041 webdriver::server DEBUG <- 500 Internal Server Error {"value":{"error":"unknown error","message":"Failed to decode response from marionette","stacktrace":""}}

**Comment by andreastt** [comment] 2018-08-13 10:31
It should probably also reproduce if you run the same program against a local geckodriver? Without a [trace-level log] I’m afraid it is hard to say what this could be.

**Comment by jsa34** [comment] 2018-08-13 10:33
Hello,

Just after posting this, I realised the trace-level logging for geckodriver is in the node logs, not the hub. 

Now trying to ascertain which nodes had the error thrown to find the geckodriver errors...

**Comment by andreastt** [comment] 2018-08-13 10:35
The client in this case probably inherits the geckodriver subprocess’ stdout.

**Comment by jsa34** [comment] 2018-08-13 10:58
Still trying to find out - but weirdly this never seems to cause any errors in my local,  but always on the remote webdriver.

**Comment by andreastt** [comment] 2018-08-13 10:59
That might indicate there’s a protocol conversion error in Selenium. In W3CHttpResponseCodec.java:122, specifically.

**Comment by jsa34** [comment] 2018-08-13 11:00
But this is never throwing an error with chromedriver...

**Comment by jsa34** [comment] 2018-08-13 11:42
Got it :)
[Parent 663, Gecko_IOThread] WARNING: pipe error (58): Connection reset by peer: file /builds/worker/workspace/build/src/ipc/chromium/src/chrome/common/ipc_channel_posix.cc, line 353

###!!! [Parent][MessageChannel] Error: (msgtype=0x16007F,name=PBrowser::Msg_Destroy) Channel error: cannot send/recv

1534160395964   webdriver::server       DEBUG   -> POST /session/aaaaaaaaaaaaaaaaaaaaaa/elements {
  "value": "#xxxxxxxxxxxxxxxx",
  "using": "css selector"
}
1534160395987   Marionette      DEBUG   Register listener.js for window 23
A content process crashed and MOZ_CRASHREPORTER_SHUTDOWN is set, shutting down
1534160396077   Marionette      TRACE   0 -> [0,169,"WebDriver:FindElements",{"using":"css selector","value":"#xxxxxxxxxxxxxxxxxxxxx"}]
1534160396185   Marionette      DEBUG   Received DOM event unload for [object XULDocument]
1534160396195   Marionette      DEBUG   Received observer notification message-manager-disconnect
1534160396200   Marionette      TRACE   0 <- [1,169,null,null]
1534160396206   webdriver::server       DEBUG   <- 500 Internal Server Error {"value":{"error":"unknown error","message":"Failed to interpret value as array","stacktrace":""}}
1534160396222   webdriver::server       DEBUG   -> GET /session/aaaaaaaaaaaaaaaaaaaaaaaaaaaa/screenshot
1534160396222   webdriver::server       DEBUG   Deleting session
1534160396235   Marionette      DEBUG   Closed connection 0
*** UTM:SVC TimerManager:registerTimer called after profile-before-change notification. Ignoring timer registration for id: telemetry_modules_ping
1534160396574   Marionette      DEBUG   Received observer notification xpcom-will-shutdown
1534160396574   Marionette      DEBUG   Resetting recommended pref apz.content_response_timeout
1534160396574   Marionette      DEBUG   Resetting recommended pref browser.download.panel.shown
1534160396575   Marionette      DEBUG   Resetting recommended pref browser.pagethumbnails.capturing_disabled
1534160396575   Marionette      DEBUG   Resetting recommended pref browser.search.update
1534160396575   Marionette      DEBUG   Resetting recommended pref toolkit.cosmeticAnimations.enabled
1534160396575   Marionette      DEBUG   Resetting recommended pref browser.tabs.disableBackgroundZombification
1534160396576   Marionette      DEBUG   Resetting recommended pref browser.tabs.warnOnCloseOtherTabs
1534160396576   Marionette      DEBUG   Resetting recommended pref browser.tabs.warnOnOpen
1534160396576   Marionette      DEBUG   Resetting recommended pref browser.usedOnWindows10.introURL
1534160396576   Marionette      DEBUG   Resetting recommended pref browser.urlbar.suggest.searches
1534160396576   Marionette      DEBUG   Resetting recommended pref datareporting.policy.dataSubmissionPolicyAccepted
1534160396577   Marionette      DEBUG   Resetting recommended pref dom.disable_beforeunload
1534160396577   Marionette      DEBUG   Resetting recommended pref dom.disable_open_during_load
1534160396577   Marionette      DEBUG   Resetting recommended pref dom.file.createInChild
1534160396577   Marionette      DEBUG   Resetting recommended pref dom.max_chrome_script_run_time
1534160396577   Marionette      DEBUG   Resetting recommended pref dom.max_script_run_time
1534160396577   Marionette      DEBUG   Resetting recommended pref extensions.getAddons.cache.enabled
1534160396577   Marionette      DEBUG   Resetting recommended pref extensions.webservice.discoverURL
1534160396577   Marionette      DEBUG   Resetting recommended pref network.http.prompt-temp-redirect
1534160396577   Marionette      DEBUG   Resetting recommended pref network.http.speculative-parallel-limit
1534160396577   Marionette      DEBUG   Resetting recommended pref security.fileuri.strict_origin_policy
1534160396577   Marionette      DEBUG   Resetting recommended pref security.notification_enable_delay
1534160396578   Marionette      DEBUG   Resetting recommended pref signon.autofillForms
1534160396578   Marionette      DEBUG   Resetting recommended pref signon.rememberSignons
1534160396578   Marionette      DEBUG   New connections will no longer be accepted
1534160397033   geckodriver::marionette DEBUG   Browser process stopped: exit code: 0
1534160397041   webdriver::server       DEBUG   <- 500 Internal Server Error {"value":{"error":"unknown error","message":"Failed to decode response from marionette","stacktrace":""}}

**Comment by andreastt** [comment] 2018-08-13 12:02
chromedriver doesn’t support the W3C WebDriver protocol, which is why Selenium uses an adapter to convert the standards conforming protocol geckodriver uses.

The trace log doesn’t appear to have trace-level verbosity.

**Comment by jsa34** [comment] 2018-08-13 12:05
Thats all I got at the point of the exception being thrown....
definitely set to trace-level (See line 1534160396200 Marionette TRACE 0 <- [1,169,null,null]) but you're right, there's not much being logged...

I see - makes sense RE: chromedriver.

**Comment by andreastt** [comment] 2018-08-13 12:08
Oh sorry, I missed that part:

```
1534160396077 Marionette TRACE 0 -> [0,169,"WebDriver:FindElements",{"using":"css selector","value":"#xxxxxxxxxxxxxxxxxxxxx"}]
1534160396185 Marionette DEBUG Received DOM event unload for [object XULDocument]
1534160396195 Marionette DEBUG Received observer notification message-manager-disconnect
1534160396200 Marionette TRACE 0 <- [1,169,null,null]
1534160396206 webdriver::server DEBUG <- 500 Internal Server Error {"value":{"error":"unknown error","message":"Failed to interpret value as array","stacktrace":""}}
```

**Comment by andreastt** [comment] 2018-08-13 12:09
It looks like a XULDocument (maybe about:addons or a dialogue?) is closing and this causes testing/marionette/proxy.js to return from the frame script immediately. This is a known problem because we’re currently unable to track messages to individual frame scripts.

This causes Marionette to return null, but geckodriver is expecting an array.

**Comment by andreastt** [comment] 2018-08-13 12:10
I would say this issue is pending on https://bugzilla.mozilla.org/show_bug.cgi?id=1311041. The patches for that won’t fix this problem exactly, but will enable us to use more refined IPC mechanisms between the Marionette chrome- and content frame scripts.

**Comment by jsa34** [comment] 2018-08-13 12:38
Thanks for the update - there doesn't seem to be any unusual things happening from the UI end at this stage - it is first element that is interacted with after going to the second page of a form.  No addons, no dialogue boxes, no popups, no growlers.  The element is of type select, but it is simply calling a webdriver wait for the element and never gets to the element's interaction method.

Interestingly, however, it is the first element that the test interacts with after getting to page 2, so I put a wait on to make sure that the URL was different to before going to the second page, just to make sure it only starts polling for the element on the correct page DOM, but still get the same error but at different places waiting for different elements - it appears that if the wait is called before the DOM is refreshed, geckodriver throws an error.

So it appears that the errors are thrown when webdriver wait polls for an element, but starts searching for it before the DOM is refreshed in some way.

**Comment by jsa34** [comment] 2018-08-13 12:45
I meant to say waiting for the page to change seemed to fix original error, but now getting it in other places.

**Comment by jsa34** [comment] 2018-08-13 14:17
New trace-level response for further issues:

1534169388904   webdriver::server       DEBUG   -> POST /session/fee50572-7056-459e-9e1a-6a33b0ed1317/element {
  "value": "*[name='submit_save']",
  "using": "css selector"
}
1534169388905   Marionette      TRACE   0 -> [0,160,"WebDriver:FindElement",{"using":"css selector","value":"*[name='submit_save']"}]
1534169388908   Marionette      TRACE   0 <- [1,160,null,{"value":{"element-6066-11e4-a52e-4f735466cecf":"e934aac2-8a4b-432a-b6fe-ea351cf9bba8","ELEMENT":"e934aac2-8a4b-432a-b6fe-ea351cf9bba8"}}]
1534169388908   webdriver::server       DEBUG   <- 200 OK {"value":{"element-6066-11e4-a52e-4f735466cecf":"e934aac2-8a4b-432a-b6fe-ea351cf9bba8"}}
1534169388918   webdriver::server       DEBUG   -> POST /session/fee50572-7056-459e-9e1a-6a33b0ed1317/element/e934aac2-8a4b-432a-b6fe-ea351cf9bba8/click {
  "id": "e934aac2-8a4b-432a-b6fe-ea351cf9bba8"
}
1534169388918   Marionette      TRACE   0 -> [0,161,"WebDriver:ElementClick",{"id":"e934aac2-8a4b-432a-b6fe-ea351cf9bba8"}]
1534169388983   Marionette      DEBUG   Received DOM event beforeunload for http://*****************************/step1
1534169389183   Marionette      DEBUG   Received DOM event pagehide for http://**********************************/step1
1534169389185   Marionette      DEBUG   Received DOM event unload for http://*************************/step1
1534169389338   Marionette      DEBUG   Received DOM event DOMContentLoaded for http://*********************/step2

###!!! [Parent][MessageChannel] Error: (msgtype=0x16007F,name=PBrowser::Msg_Destroy) Channel error: cannot send/recv

[Parent 3693, Gecko_IOThread] WARNING: pipe error (53): Connection reset by peer: file /builds/worker/workspace/build/src/ipc/chromium/src/chrome/common/ipc_channel_posix.cc, line 353
1534169389540   Marionette      DEBUG   Register listener.js for window 23
A content process crashed and MOZ_CRASHREPORTER_SHUTDOWN is set, shutting down
1534169389597   Marionette      DEBUG   Check readyState uninitialized for about:blank
1534169389627   Marionette      DEBUG   Received DOM event unload for [object XULDocument]
1534169389635   Marionette      DEBUG   Received observer notification message-manager-disconnect
1534169389638   Marionette      TRACE   0 <- [1,161,null,{}]
1534169389641   webdriver::server       DEBUG   <- 200 OK {"value": null}
1534169389646   webdriver::server       DEBUG   -> GET /session/fee50572-7056-459e-9e1a-6a33b0ed1317/url
1534169389646   webdriver::server       DEBUG   Deleting session
1534169389649   Marionette      DEBUG   Closed connection 0
*** UTM:SVC TimerManager:registerTimer called after profile-before-change notification. Ignoring timer registration for id: telemetry_modules_ping
1534169389757   Marionette      DEBUG   Received observer notification xpcom-will-shutdown
1534169389757   Marionette      DEBUG   Resetting recommended pref apz.content_response_timeout
1534169389757   Marionette      DEBUG   Resetting recommended pref browser.download.panel.shown
1534169389757   Marionette      DEBUG   Resetting recommended pref browser.pagethumbnails.capturing_disabled
1534169389757   Marionette      DEBUG   Resetting recommended pref browser.search.update
1534169389757   Marionette      DEBUG   Resetting recommended pref toolkit.cosmeticAnimations.enabled
1534169389758   Marionette      DEBUG   Resetting recommended pref browser.tabs.disableBackgroundZombification
1534169389758   Marionette      DEBUG   Resetting recommended pref browser.tabs.warnOnCloseOtherTabs
1534169389758   Marionette      DEBUG   Resetting recommended pref browser.tabs.warnOnOpen
1534169389758   Marionette      DEBUG   Resetting recommended pref browser.usedOnWindows10.introURL
1534169389758   Marionette      DEBUG   Resetting recommended pref browser.urlbar.suggest.searches
1534169389759   Marionette      DEBUG   Resetting recommended pref datareporting.policy.dataSubmissionPolicyAccepted
1534169389759   Marionette      DEBUG   Resetting recommended pref dom.disable_beforeunload
1534169389759   Marionette      DEBUG   Resetting recommended pref dom.disable_open_during_load
1534169389759   Marionette      DEBUG   Resetting recommended pref dom.file.createInChild
1534169389759   Marionette      DEBUG   Resetting recommended pref dom.max_chrome_script_run_time
1534169389759   Marionette      DEBUG   Resetting recommended pref dom.max_script_run_time
1534169389759   Marionette      DEBUG   Resetting recommended pref extensions.getAddons.cache.enabled
1534169389760   Marionette      DEBUG   Resetting recommended pref extensions.webservice.discoverURL
1534169389760   Marionette      DEBUG   Resetting recommended pref network.http.prompt-temp-redirect
1534169389760   Marionette      DEBUG   Resetting recommended pref network.http.speculative-parallel-limit
1534169389760   Marionette      DEBUG   Resetting recommended pref security.fileuri.strict_origin_policy
1534169389760   Marionette      DEBUG   Resetting recommended pref security.notification_enable_delay
1534169389760   Marionette      DEBUG   Resetting recommended pref signon.autofillForms
1534169389760   Marionette      DEBUG   Resetting recommended pref signon.rememberSignons
1534169389760   Marionette      DEBUG   New connections will no longer be accepted
1534169390047   geckodriver::marionette DEBUG   Browser process stopped: exit code: 0
1534169390053   webdriver::server       DEBUG   <- 500 Internal Server Error {"value":{"error":"unknown error","message":"Failed to decode response from marionette","stacktrace":""}}
1534169390058   webdriver::server       DEBUG   -> GET /session/fee50572-7056-459e-9e1a-6a33b0ed1317/screenshot
1534169390058   webdriver::server       DEBUG   <- 500 Internal Server Error {"value":{"error":"session not created","message":"Tried to run command without establishing a connection","stacktrace":""}}

**Comment by whimboo** [comment] 2018-09-18 07:49
No response from @jsa34 anymore. Closing issue.

**Closed by whimboo** 2018-09-18 07:49 UTC
Labels: firefox
