### ISSUE TITLE
Firefox crashes without obvious reason

### ISSUE THREAD

**Issue by pierre-jenchen** [mozilla/geckodriver#395] opened 2016-12-13 10:47 UTC
I run automated tests with docker selenium, but firefox always crashes after a short while. Especially opening new tabs triggers it always.

## Firefox Version
Firefox 49

## Platform
Linux

## Steps to reproduce -
- open page with selenium docker (version 3.0.1) and geckodriver with navigate().to()
- click on a button which opens a new tab
-> the page loads but after it finished the message: "Bad news first: This tab has crashed" appears and the webdriver immediatly looses connection.

```
org.openqa.selenium.WebDriverException: Error communicating with the remote browser. It may have died.
Build info: version: '3.0.1', revision: '1969d75', time: '2016-10-18 09:48:19 -0700'
System info: host: 'nodefirefox', ip: '172.17.0.3', os.name: 'Linux', os.arch: 'amd64', os.version: '4.4.27-boot2docker', java.version: '1.8.0_91'
Driver info: driver.version: RemoteWebDriver
```
If i run the test with my local firefox browser everything is fine. I use the latest images for the firefox node.
There are similarities to  #https://github.com/mozilla/geckodriver/issues/210 but i'm not sure if this is the reason in my case because it's firefox 49.
I downgraded the firefox version to every version down to 45, but always the same issue occurs.

The log in docker-compose looks like this:
```
nodefirefox    | (firefox:123): GLib-GObject-WARNING **: /build/glib2.0-7IO_Yw/glib2.0-2.48.1/./gobject/gsignal.c:3486: signal name 'selection_changed' is invalid for instance '0x7f2a06433100' of type 'MaiAtkType139'
nodefirefox    | 02:38:04.899 INFO - Done: [find element: By.className: search-btn]
nodefirefox    | 02:38:04.951 INFO - Executing: [click: 106 [[FirefoxDriver: firefox on LINUX (bfdb3a57-a74a-4373-b747-821ec1d2f6b6)] -> class name: search-btn]])
nodefirefox    | JavaScript error: chrome://marionette/content/proxy.js, line 187: NS_ERROR_ILLEGAL_VALUE: Component returned failure code: 0x80070057 (NS_ERROR_ILLEGAL_VALUE) [nsIMessageSender.sendAsyncMessage]
nodefirefox    | 02:38:05.442 INFO - Done: [click: 106 [[FirefoxDriver: firefox on LINUX (bfdb3a57-a74a-4373-b747-821ec1d2f6b6)] -> class name: search-btn]]
nodefirefox    | 13/12/2016 02:38:07 XDAMAGE is not working well... misses: 149/224
nodefirefox    | 13/12/2016 02:38:07 Maybe an OpenGL app like Beryl or Compiz is the problem?
nodefirefox    | 13/12/2016 02:38:07 Use x11vnc -noxdamage or disable the Beryl/Compiz app.
nodefirefox    | 13/12/2016 02:38:07 To disable this check and warning specify -xdamage twice.
nodefirefox    | 02:38:07.458 INFO - Executing: [find element: By.id: inputDateFromSearch])
nodefirefox    | 02:38:07.474 INFO - Done: [find element: By.id: inputDateFromSearch]
nodefirefox    | 02:38:07.497 INFO - Executing: [get element attribute: 102 [[FirefoxDriver: firefox on LINUX (bfdb3a57-a74a-4373-b747-821ec1d2f6b6)] -> id: inputDateFromSearch], value])
nodefirefox    | 02:38:07.521 INFO - Done: [get element attribute: 102 [[FirefoxDriver: firefox on LINUX (bfdb3a57-a74a-4373-b747-821ec1d2f6b6)] -> id: inputDateFromSearch], value]
nodefirefox    | 02:38:07.548 INFO - Executing: [find element: By.className: search-list])
nodefirefox    | 02:38:07.566 INFO - Done: [find element: By.className: search-list]
nodefirefox    | 02:38:07.601 INFO - Executing: [find child elements: 107 [[FirefoxDriver: firefox on LINUX (bfdb3a57-a74a-4373-b747-821ec1d2f6b6)] -> class name: search-list], By.className: search-list-item])
nodefirefox    | 1481625501199	addons.productaddons	INFO	sending request to: https://aus5.mozilla.org/update/3/GMP/49.0.1/20160922113459/Linux_x86_64-gcc3/en-US/release/Linux%204.4.27-boot2docker%20(GTK%203.18.9%2Clibpulse%20not-available)/default/default/update.xml
nodefirefox    | 1481625502330	addons.productaddons	INFO	Completed downloading document
nodefirefox    | 02:38:23.540 INFO - Executing: [take screenshot])
nodefirefox    | 1481625503835	addons.productaddons	INFO	downloadXHR File download. status=200
nodefirefox    | 1481625503843	addons.productaddons	INFO	Downloaded file will be saved to /tmp/tmpaddon
nodefirefox    | 02:38:27.901 INFO - Done: [take screenshot]
nodefirefox    | 02:38:28.190 INFO - Executing: [delete all cookies])
nodefirefox    | 02:38:41.926 INFO - Done: [delete all cookies]
nodefirefox    | 02:38:41.979 INFO - Executing: [delete session: 895f469f-eac1-4598-8011-e019e6c15fcc])
nodefirefox    | [Child 168] ###!!! ABORT: Aborting on channel error.: file /builds/slave/m-rel-l64-00000000000000000000/build/src/ipc/glue/MessageChannel.cpp, line 2052
nodefirefox    | [Child 168] ###!!! ABORT: Aborting on channel error.: file /builds/slave/m-rel-l64-00000000000000000000/build/src/ipc/glue/MessageChannel.cpp, line 2052
nodefirefox    | 02:38:42.407 INFO - Done: [delete session: 895f469f-eac1-4598-8011-e019e6c15fcc]
nodefirefox    | 13/12/2016 02:38:49 XDAMAGE is not working well... misses: 145/215
nodefirefox    | 13/12/2016 02:38:49 Maybe an OpenGL app like Beryl or Compiz is the problem?
nodefirefox    | 13/12/2016 02:38:49 Use x11vnc -noxdamage or disable the Beryl/Compiz app.
nodefirefox    | 13/12/2016 02:38:49 To disable this check and warning specify -xdamage twice.
```

Any help is highly appreciated and if you need more data/logs then please let me know.

**Comment by HackToday** [comment] 2016-12-15 03:39
In our test, we found similar Firefox errors in logs like  
```
[Child 2287] ###!!! ABORT: Aborting on channel error.: file /builds/slave/m-rel-l64-00000000000000000000/build/src/ipc/glue/MessageChannel.cpp, line 2056
[Child 2287] ###!!! ABORT: Aborting on channel error.: file /builds/slave/m-rel-l64-00000000000000000000/build/src/ipc/glue/MessageChannel.cpp, line 2056
```

However, Ours issue is this include more like this

```
1481771416951	addons.manager	DEBUG	Provider finished startup: PluginProvider
1481771416951	addons.manager	DEBUG	Completed startup sequence
1481771417136	Marionette	ERROR	Error on starting server: [Exception... "Component returned failure code: 0x804b0036 (NS_ERROR_SOCKET_ADDRESS_IN_USE) [nsIServerSocket.initSpecialConnection]"  nsresult: "0x804b0036 (NS_ERROR_SOCKET_ADDRESS_IN_USE)"  location: "JS frame :: chrome://marionette/content/server.js :: MarionetteServer.prototype.start :: line 85"  data: no]
[Exception... "Component returned failure code: 0x804b0036 (NS_ERROR_SOCKET_ADDRESS_IN_USE) [nsIServerSocket.initSpecialConnection]"  nsresult: "0x804b0036 (NS_ERROR_SOCKET_ADDRESS_IN_USE)"  location: "JS frame :: chrome://marionette/content/server.js :: MarionetteServer.prototype.start :: line 85"  data: no]
MarionetteServer.prototype.start@chrome://marionette/content/server.js:85:19
MarionetteComponent.prototype.init@resource://gre/components/marionettecomponent.js:218:5
MarionetteComponent.prototype.observe@resource://gre/components/marionettecomponent.js:142:7

```

Reference here
https://github.com/mozilla/geckodriver/issues/380

**Comment by andreastt** [comment] 2016-12-15 23:29
Duplicate of #210.

**Closed by andreastt** 2016-12-15 23:29 UTC

**Comment by pierre-jenchen** [comment] 2016-12-19 17:00
@andreastt this seems to be a not uncommon problem but all related Github issues are closed.
(And no workaround applies to my issue)

What can i do/provide to make a fix possible?

**Comment by HackToday** [comment] 2016-12-19 23:50
https://github.com/mozilla/geckodriver/issues/380 is still not solved, I will try provide to Firefox developers more info. As I think it is a serious issue.
