### ISSUE TITLE
Can't use --connect-existing in Selenium on Python

### ISSUE THREAD

**Issue by jainnimish** [mozilla/geckodriver#1980] opened 2022-01-21 06:18 UTC
## System

* Version: 0.30.0
* Platform: macOS
* Firefox v94.0.2
* Selenium(4.1.0) on Python(3.9.7)

## Testcase
When I try to pass a list of arguments to  GeckoDriver as a Service through Selenium, the driver unexpectedly quits with status code **64**. This issue is only occuring on using the "--connect-existing" parameter. 

**Code:**
```
from selenium import webdriver 

driver = webdriver.Firefox(service_args=["--connect-existing"])
```
## Stacktrace
```
XXX/work.py:5: DeprecationWarning: service_args has been deprecated, please pass in a Service object
driver = webdriver.Firefox(service_args=["--connect-existing"])

Traceback (most recent call last):
File "XXX/work.py", line 5, in <module>
   driver = webdriver.Firefox(service_args=["--connect-existing"])
File "XXX/lib/python3.9/site-packages/selenium/webdriver/firefox/webdriver.py", line 74, in __init__
    self.service.start()
File "XXX/lib/python3.9/site-packages/selenium/webdriver/common/service.py", line 98, in start
    self.assert_process_still_running()
File "XXX/lib/python3.9/site-packages/selenium/webdriver/common/service.py", line 110, in assert_process_still_running
    raise WebDriverException(
selenium.common.exceptions.WebDriverException: Message: Service geckodriver unexpectedly exited. Status code was: 64
```

**Comment by whimboo** [comment] 2022-01-21 08:04
This is a dupe of issue #1959.

**Closed by whimboo** 2022-01-21 08:04 UTC
