### ISSUE TITLE
JavaException seen for web element selecttype

### ISSUE THREAD

**Issue by sharmistharoy** [mozilla/geckodriver#488] opened 2017-02-20 23:00 UTC
In order to help us efficiently investigate your issue, please provide the following information:

## Firefox Version
FF 51.0.1 (32-bit), geckodriver-v0.14.0-win64, and selenium-java-3.0.1

## Platform
Windows 64 bit

## Steps to reproduce -
This is my first selenium webdriver program to get values from a List of values box.
The site I am using to test is : http://book.theautomatedtester.co.uk. Click on Chapter1 - link and then try to select values from the LOV box on the page.

I am using the below code snippet for selecting the LOV(list of values) box.
**Select drop = new Select(d.findElement(By.id("selecttype")));**
On executing this code I get the following error:
_Exception in thread "main" org.openqa.selenium.NoSuchElementException: Unable to locate element: **#selecttype**  For documentation on this error, please visit: http://seleniumhq.org/exceptions/no_such_element.html_

If I do an Inspect element on the web page - I get : 
<select id="selecttype">
					<option value="Selenium IDE">Selenium IDE</option>
					<option value="Selenium Code">Selenium Core</option>
					<option value="Selenium RC">Selenium RC</option>
					<option value="Selenium Grid">Selenium Grid</option>
				</select>

How can I fix this?

**Comment by andreastt** [comment] 2017-02-23 14:43
As far as I know Marionette currently does not wait for the page to finish loading when clicking a link that takes you to a new document. We are (partially) fixing this as part of https://bugzilla.mozilla.org/show_bug.cgi?id=1330348.

This is a duplicate of https://github.com/mozilla/geckodriver/issues/308.

**Closed by andreastt** 2017-02-23 14:43 UTC
