### ISSUE TITLE
Selenium::WebDriver::Error::UnknownError: Process unexpectedly closed with status: 1

### ISSUE THREAD

**Issue by yb66** [mozilla/geckodriver#1172] opened 2018-02-11 19:22 UTC
Hello,

I was having problems getting geckodriver to work with Ruby (which is where the title of this issue comes from) so I thought I'd try a more direct method by using [the standalone example from the README](https://github.com/mozilla/geckodriver#standalone). It failed with the same error code but gave more info, if it's not going to work for that it won't for Ruby so I suggest we ignore that (for now:)

Let me know if you need anything more. Any help will be much appreciated.

Regards,
iain

## System

* Version: 0.19.1
* Platform: OS X 10.9.5 (I consider High Sierra to be a botch job so I downgraded, I won't be upgrading this system again)
* Firefox: 58.0.1 (64-bit)
* Selenium: selenium-webdriver 3.8.0
* curl: 7.57.0
* Ruby: 2.5.0

## Testcase

    $ geckodriver -vv &                                                                                       
    [1] 97256
    1518374147230   geckodriver     INFO    geckodriver 0.19.1                                                                                                    
    1518374147231	webdriver::httpapi	DEBUG	Creating routes
    1518374147237	geckodriver	INFO	Listening on 127.0.0.1:4444

    $ curl -d '{"capabilities": {"alwaysMatch": {"acceptInsecureCerts": true}}}' http://localhost:4444/session

## Testcase

    $ geckodriver -vv &                                                                                       
    [1] 97256
    1518374147230   geckodriver     INFO    geckodriver 0.19.1                                                                                                    
    1518374147231	webdriver::httpapi	DEBUG	Creating routes
    1518374147237	geckodriver	INFO	Listening on 127.0.0.1:4444

    $ curl -d '{"capabilities": {"alwaysMatch": {"acceptInsecureCerts": true}}}' http://localhost:4444/session

## Trace-level log

    1518374154769	webdriver::server	DEBUG	-> POST /session {"capabilities": {"alwaysMatch": {"acceptInsecureCerts": true}}}
    1518374154769	geckodriver::capabilities	DEBUG	Trying to read firefox version from ini files
    1518374154770	geckodriver::capabilities	DEBUG	Found version 58.0.1
    1518374154806	mozrunner::runner	INFO	Running command: "/Applications/Firefox.app/Contents/MacOS/firefox-bin" "-marionette" "-profile" "/var/folders/8v/jn6zyx3d6zb8yx_b23_238hh0000gn/T/rust_mozprofile.YFASRHMdrH4G"
    1518374154808	geckodriver::marionette	TRACE	  connection attempt 0/600
    1518374154909	geckodriver::marionette	TRACE	  connection attempt 1/600
    1518374155010	geckodriver::marionette	TRACE	  connection attempt 2/600
    1518374155112	geckodriver::marionette	TRACE	  connection attempt 3/600
    1518374155189	Marionette	DEBUG	Received observer notification "profile-after-change"
    1518374155212	geckodriver::marionette	TRACE	  connection attempt 4/600
    1518374155238	Marionette	DEBUG	Received observer notification "command-line-startup"
    1518374155238	Marionette	INFO	Enabled via --marionette
    1518374155314	geckodriver::marionette	TRACE	  connection attempt 5/600
    1518374155415	geckodriver::marionette	TRACE	  connection attempt 6/600
    1518374155516	geckodriver::marionette	TRACE	  connection attempt 7/600
    1518374155617	geckodriver::marionette	TRACE	  connection attempt 8/600
    1518374155718	geckodriver::marionette	TRACE	  connection attempt 9/600
    1518374155820	geckodriver::marionette	TRACE	  connection attempt 10/600
    1518374155928	webdriver::server	DEBUG	<- 500 Internal Server Error {"value":{"error":"unknown error","message":"Process unexpectedly closed with status: 1","stacktrace":"stack backtrace:
      0:        0x107bab49e - backtrace::backtrace::trace::h3ab5720c483fe461
      1:        0x107bab4dc - backtrace::capture::Backtrace::new::h096accf58447e0d5
      2:        0x107ae4534 - webdriver::error::WebDriverError::new::hc0958d01acda7bfc
      3:        0x107aebe1d - geckodriver::marionette::MarionetteHandler::create_connection::h59a68c8dfef48e54
      4:        0x107acad3c - _$LT$webdriver..server..Dispatcher$LT$T$C$$u20$U$GT$$GT$::run::h5a26ba0bb4fdb139
      5:        0x107aa30c5 - std::sys_common::backtrace::__rust_begin_short_backtrace::h3f868f7a1a12bdcc
      6:        0x107aadd2d - std::panicking::try::do_call::hfce1ad2a948c3632
      7:        0x107c57a5c - __rust_maybe_catch_panic
      8:        0x107ac0eb5 - _$LT$F$u20$as$u20$alloc..boxed..FnBox$LT$A$GT$$GT$::call_box::h651dedb755194a8c
      9:        0x107c53c4b - std::sys::imp::thread::Thread::new::thread_start::h48c72bb09587cbc3
      10:     0x7fff92b07898 - _pthread_body
      11:     0x7fff92b07729 - _pthread_start"}}
      {"value":{"error":"unknown error","message":"Process unexpectedly closed with status: 1","stacktrace":"stack backtrace:
      0:        0x107bab49e - backtrace::backtrace::trace::h3ab5720c483fe461
      1:        0x107bab4dc - backtrace::capture::Backtrace::new::h096accf58447e0d5
      2:        0x107ae4534 - webdriver::error::WebDriverError::new::hc0958d01acda7bfc
      3:        0x107aebe1d - geckodriver::marionette::MarionetteHandler::create_connection::h59a68c8dfef48e54
      4:        0x107acad3c - _$LT$webdriver..server..Dispatcher$LT$T$C$$u20$U$GT$$GT$::run::h5a26ba0bb4fdb139
      5:        0x107aa30c5 - std::sys_common::backtrace::__rust_begin_short_backtrace::h3f868f7a1a12bdcc
      6:        0x107aadd2d - std::panicking::try::do_call::hfce1ad2a948c3632
      7:        0x107c57a5c - __rust_maybe_catch_panic
      8:        0x107ac0eb5 - _$LT$F$u20$as$u20$alloc..boxed..FnBox$LT$A$GT$$GT$::call_box::h651dedb755194a8c
      9:        0x107c53c4b - std::sys::imp::thread::Thread::new::thread_start::h48c72bb09587cbc3
      10:     0x7fff92b07898 - _pthread_body
      11:     0x7fff92b07729 - _pthread_start"}}%

**Comment by whimboo** [comment] 2018-02-12 10:25
Here Firefox crashed, and it might be that you hit a path which isn't working that well with your very old OS X release. 

Would you mind running a debug build of Firefox Nightly and attach another trace log for it? The build can be found here: https://queue.taskcluster.net/v1/task/XIdWSNUIQlOQ8Eqw0QUJng/runs/0/artifacts/public/build/target.dmg

Thanks.

**Comment by yb66** [comment] 2018-02-12 14:38
> very old OS X release

That gave me chuckle :smiley:

Thanks, I've attached the log. It died soon after starting it.

Regards,
iain

[trace-log-for-firefox-60-nightly-debug.txt](https://github.com/mozilla/geckodriver/files/1716597/trace-log-for-firefox-60-nightly-debug.txt)

**Comment by fwilhe** [comment] 2018-02-28 12:38
My ticket #1189 was marked as duplicate of this ticket, and I use latest Firefox shipped by Ubuntu. Would be glad to see progress here, as this currently prevents us from using Firefox for our automated tests.

**Comment by nobism** [comment] 2018-03-05 23:43
My issue, #1163 was also marked as duplicate of this ticket (shouldn't it be the other way around??). Anyway, it'd be nice to get this working, surely the latest versions of firefox, selenium and geckodriver should work together.

**Comment by whimboo** [comment] 2018-03-06 08:29
@yb66 thanks and sorry for the delay in my response. This is clearly a crash in Firefox. Could you please have a look if the rust profile as created by geckodriver remains? If yes, there is a `minidumps` folder in that profile which contains some files. If you can send them to me that would be great.

**Comment by whimboo** [comment] 2018-04-12 13:56
@premkamban your problem is unrelated given that the exit code is 0 and not 1 as covered by this issue. You are most likely affected by issue #1134.

**Comment by whimboo** [comment] 2019-01-30 08:47
Closing due to inactivity.

**Closed by whimboo** 2019-01-30 08:47 UTC
Labels: firefox
