### ISSUE TITLE
Repeated hover does't work

### ISSUE THREAD

**Issue by lnsight** [mozilla/geckodriver#1507] opened 2019-02-18 15:06 UTC
## System

* Version: 0.24.0
* Platform: Ubuntu 18.04.2 LTS
* Firefox: 65.0.1-67.0a1
* Selenium: 3.141.0

## Testcase
I found this bug in capybara test:
```rb
find_link('Label').hover # successful
<going to other page>
<going back>
find_link('Label').hover # does nothing (without any errors)
```
This case reproduced in https://gist.github.com/lnsight/1440b63dd3fbbaf4c612a0714342f66b

## Trace-level log

https://gist.github.com/lnsight/4dfcce03fe3c700a8f146d2570409338

**Comment by whimboo** [comment] 2019-02-19 08:04
Could you please attach a [trace-level log] from geckodriver? Read more about reporting actionable bugs in our [contribution guidelines].

[trace-level log]: https://firefox-source-docs.mozilla.org/testing/geckodriver/geckodriver/TraceLogs.html
[contribution guidelines]: https://firefox-source-docs.mozilla.org/testing/geckodriver/geckodriver/Bugs.html

**Comment by lnsight** [comment] 2019-02-19 09:10
Trace-level log has been attached.

**Comment by whimboo** [comment] 2019-02-19 13:10
There are tons of execute script calls in that log. Please create a minimized testcase best without any JS framework, or Javascript involved which still reproduces this problem. A trace log from such an execution would be good to have.

**Comment by twalpole** [comment] 2019-02-19 20:38
@whimboo The JS is the Selenium isDisplayed JS atom - it can basically be ignored for the purpose of that trace log.

**Comment by acikojevic** [comment] 2019-02-20 13:05
I can confirm this issues exists in version 0.24.0

Here is trace log for faulty hover action:

```
1550667700455   webdriver::server       DEBUG   -> POST /session/8b376101-c195-4417-a0bd-7d758a793260/actions {
  "actions": [
    {
      "id": "default mouse",
      "type": "pointer",
      "parameters": {
        "pointerType": "mouse"
      },
      "actions": [
        {
          "duration": 100,
          "x": 0,
          "y": 0,
          "type": "pointerMove",
          "origin": {
            "ELEMENT": "1605e335-c19d-40b8-860e-d17e68cea29d",
            "element-6066-11e4-a52e-4f735466cecf": "1605e335-c19d-40b8-860e-d17e68cea29d"
          }
        }
      ]
    }
  ]
}
1550667700457   Marionette      DEBUG   0 -> [0,90,"WebDriver:PerformActions",{"actions":[{"actions":[{"duration":100,"origin":{"element-6066-11e4-a52e-4f735466cecf":"160 ... e68cea29d"},"type":"pointerMove","x":0,"y":0}],"id":"default mouse","parameters":{"pointerType":"mouse"},"type":"pointer"}]}]
1550667700570   Marionette      DEBUG   0 <- [1,90,null,{"value":null}]
1550667700570   webdriver::server       DEBUG   <- 200 OK {"value":null}
```

**Comment by snowymike** [comment] 2019-03-13 16:27
this may be the same issue i sent to the selenium users google group at https://groups.google.com/forum/#!topic/selenium-users/JYJKHUa0hdM

my focus issues began with Firefox 65.  64.0 worked fine.  65.0.2 32-bit works fine.  65.0.2 64-bit does not.

@acikojevic did you by chance try 65 32-bit to see if that works?  if it does, i think our issues are identical.

**Comment by snowymike** [comment] 2019-03-21 12:34
Firefox 66.0, 64-bit, has the same problem

**Comment by snowymike** [comment] 2019-03-21 12:35
@whimboo is there still reporter feedback you are looking for on this one or is @acikojevic 's trace log sufficient?

**Comment by whimboo** [comment] 2019-03-25 09:42
@snowymike we are currently limit in doing work on geckodriver, sorry. So any additional feedback from you and others would be welcome. Given that 64 was working for you, it would be good to know when during the Firefox 65 development process the issue started for you. Maybe you could check the beta versions of Firefox and tell me in which of those it started for you? It would make it easier to pinpoint the underlying change. Those builds can be found at http://archive.mozilla.org/pub/firefox/releases/.

**Comment by snowymike** [comment] 2019-03-25 12:51
@whimboo i'll try to narrow down which 65 beta broke things.  i just tried 66.0.1 today, focus still messed up there.

**Comment by snowymike** [comment] 2019-03-25 13:15
it's broken in the first 65 beta i see at that link, 65.0b3, http://archive.mozilla.org/pub/firefox/releases/65.0b3/win64/en-US/

![image](https://user-images.githubusercontent.com/7119031/54922386-670b2280-4ede-11e9-9848-f697f4e587f6.png)

it was tricky to avoid auto-update happening.  unchecking the Mozilla Maintenance service during install wasn't enough to block it.  i ended up unchecking launch firefox at install completion, such that the first run of firefox was through geckodriver, as the way to keep the version at 65.0b3.

**Comment by whimboo** [comment] 2019-03-25 14:52
Mind also testing the devedition releases which would be beta 1 and 2? You can find those here: https://archive.mozilla.org/pub/devedition/releases/

This seems to be similar to https://bugzilla.mozilla.org/show_bug.cgi?id=1538486.

**Comment by snowymike** [comment] 2019-03-25 17:32
beta 1 also broken

**Comment by snowymike** [comment] 2019-04-01 12:57
@whimboo any other info that would be helpful for me to provide?

**Comment by snowymike** [comment] 2019-05-02 13:18
not fixed in 66.0.3 either.

any update on this issue?  i haven't seen anything new posted here or at https://bugzilla.mozilla.org/show_bug.cgi?id=1538486 in the last month.

**Comment by whimboo** [comment] 2019-05-03 08:48
Sorry, but I'm currently working on a different project. So I don't have the time to follow on all the bugs/issues for geckodriver.

What would be necessary now is a regression test based on Nightly versions of Firefox. That would help us to pinpoint the change in behavior to a single day, and that might indicate which change caused it. 

Based on the [release calendar](https://wiki.mozilla.org/Release_Management/Calendar) Firefox 65 was on mozilla-central from 2018-10-22 to 2018-12-10. A bisect for those builds would be necessary. Would you mind doing that?

We have a tool called [mozregression](https://github.com/mozilla/mozregression) where you could automate that, or you can use [mozdownload](https://pypi.python.org/pypi/mozdownload) to grab specific versions of Firefox Nightly.

Thanks!

**Comment by snowymike** [comment] 2019-05-03 18:39
i'll need something i can run on windows.  looking at the mozregression and mozdownload links you sent, i'm not certain how precisely i'd get an installer for 64-bit windows for a certain date.  if you can share the commands for how i'd get, for example, a 2018-11-10 build of Firefox 65 for 64-bit windows, i'll give it a shot.

**Comment by JessefSpecialisterren** [comment] 2019-05-06 08:15
@snowymike Direct downloads of older nightlies can be found at https://archive.mozilla.org/pub/firefox/nightly/2018/ , but automating the regression test should save you a lot of clicking through installers and stuff 😉. There's a windows installer for mozregression as documented at https://mozilla.github.io/mozregression/install.html  , and there's a quick start video tutorial at https://mozilla.github.io/mozregression/quickstart.html

**Comment by whimboo** [comment] 2019-05-06 09:01
In the case you don't want to use mozregression, for mozdownload just use `mozdownload -t daily --date 2018-11-10`. The command will automatically pick the correct platform based on what you are working with. If not there is still `-p win64` available to force Windows 64bit binaries. Thanks!

**Comment by snowymike** [comment] 2019-05-06 17:17
it's broken in the very first nightly build of 65

https://archive.mozilla.org/pub/firefox/nightly/2018/10/2018-10-22-22-07-34-mozilla-central/firefox-65.0a1.en-US.win64.installer.exe

it works properly in the final nightly build of 64

https://archive.mozilla.org/pub/firefox/nightly/2018/10/2018-10-22-10-00-55-mozilla-central/firefox-64.0a1.en-US.win64.installer.exe

**Comment by whimboo** [comment] 2019-05-07 06:34
Thanks a lot @snowymike! Now lets move further investigation to the before-mentioned bug.

**Comment by snowymike** [comment] 2019-05-08 14:39
i don't have a bugzilla account to post it there, but fyi, the moz:useNonSpecCompliantPointerOrigin setting discussed at https://bugzilla.mozilla.org/show_bug.cgi?id=1538486 does avoid the focus problem in my test.  @whimboo would you mind reporting that there?

i added this one line
```
		options.setCapability("moz:useNonSpecCompliantPointerOrigin", true);
```

to my existing method below

```
	private static FirefoxOptions getGeckoFirefoxOptions(String locale) {
		FirefoxOptions options = new FirefoxOptions();
		FirefoxProfile profile = new FirefoxProfile();
		profile.setPreference("intl.accept_languages", locale);
		// avoid the dialog that appears when saving zip files (e.g. for export)
		profile.setPreference("browser.helperApps.neverAsk.saveToDisk", "application/zip");
		options.setCapability(FirefoxDriver.PROFILE, profile);
		options.setCapability("moz:useNonSpecCompliantPointerOrigin", true);
		return options;
	}
```

and that worked in Firefox 66.0.5 64-bit Windows

**Comment by whimboo** [comment] 2019-05-09 06:35
Thanks! I will add a comment on the bug for that.

**Comment by whimboo** [comment] 2023-03-10 20:52
Since this bug was laying around for a while and users were forced to set the `moz:useNonSpecCompliantPointerOrigin` capability, I was trying to reproduce the problem again but I'm not able to with a recent Nightly build of Firefox.

@snowymike, @acikojevic or @Insight do you still run into it with `moz:useNonSpecCompliantPointerOrigin` set to `false`?

**Comment by whimboo** [comment] 2023-03-10 21:18
Actually I was able to reproduce it with a Firefox 78 build. More testing revealed that this issue is gone since the Firefox 84 release. For more details see https://bugzilla.mozilla.org/show_bug.cgi?id=1538486.

**Closed by whimboo** 2023-03-10 21:18 UTC
Labels: marionette

**Comment by snowymike** [comment] 2023-03-10 22:31
@whimboo so no need for 
```
options.setCapability("moz:useNonSpecCompliantPointerOrigin", true);
```
in builds 84 or newer, correct?

**Comment by whimboo** [comment] 2023-03-13 07:41
@snowymike yes that would be correct. I would appreciate if you could test your specific example(s) and report back. Thanks!

**Comment by jeremy-of-laurel** [comment] 2023-11-08 18:33
Hi @whimboo ,

This is still broken as of Firefox 119 and geckodriver 0.33.0. Additionally, the workaround using the above capability no longer works because it is no longer supported as of version 116.

So currently, versions 116 and later are not testable on my end because many of my tests perform multiple hovers on the same element. The only workaround I have for now is to remain on version 115, which isn't a great long term solution.

Any additional attention to this issue would be greatly appreciated.

**Comment by whimboo** [comment] 2023-11-09 08:05
@jeremy-of-laurel would you mind filing a new issue for it and if possible attaching a testcase that could be used to reproduce - maybe even with some lightweight HTML? 

Note that we were asking via various channels if anyone is still using this capability but we didn't get any reply. As such we decided to remove it due to no known problems with the WebDriver API. When you provided the details we can clearly have a look.

**Comment by luke-hill** [comment] 2024-01-17 16:35
FYI I'm aware this is semi-ancient. But I've found a similar use case. I was originally directed after googling a bug for capybara and found this.

I think "part" of the issue, is that chrome hovering works differently (It seems), to firefox. I've been discussing in #selenium on slack to see if the issue boils down to your "current" focus point being identical to the requested "hover point"

Can I ask whimboo......

If I am "on" element A, i.e. it's highlighted in the background. But no dropdown is there, should hovering on element A be permissible. It is on chrome.

**Comment by luke-hill** [comment] 2024-03-26 10:37
Any news on this @whimboo - Could we get this re-opened as this has regressed?

**Comment by whimboo** [comment] 2024-04-09 06:36
@luke-hill would you mind filing a new issue for your problem? Also a minimized HTML with such a dropdown would be kinda helpful.
