### ISSUE TITLE
Certification error "Your connection is not secure"

### ISSUE THREAD

**Issue by manjunatha-mr** [mozilla/geckodriver#216] opened 2016-09-06 12:47 UTC
Not able to close the certification error "Your connection is not secure" by adding below capabilities and profile.

ProfilesIni allProfiles = new ProfilesIni();
		FirefoxProfile myProfile = new FirefoxProfile();
		myProfile.setAcceptUntrustedCertificates(true);
		myProfile.setAssumeUntrustedCertificateIssuer(false);
		WebDriver driver=new FirefoxDriver(myProfile);

DesiredCapabilities capabilities = new DesiredCapabilities();
		capabilities.setCapability(CapabilityType.ACCEPT_SSL_CERTS, true);
		WebDriver driver = new FirefoxDriver(capabilities);

profile.setAcceptUntrustedCertificates(true);
                profile.setAssumeUntrustedCertificateIssuer(true);
                capability2.setCapability(FirefoxDriver.PROFILE, profile);

We are using below versions:
 Geckodriver v0.10.0. 
Selenium: 3.0.0 beta-3 and 
Firefox: 48.0.2

**Comment by andreastt** [comment] 2016-09-06 13:04
Duplicate of https://github.com/mozilla/geckodriver/issues/93.

**Closed by andreastt** 2016-09-06 13:04 UTC

**Comment by mbn217** [comment] 2017-01-10 21:07
same for me , I facing this problem as of now

**Comment by andreastt** [comment] 2017-01-11 12:34
@mbn217 Ensure you’re using the very latest Firefox Nightly.
