### ISSUE TITLE
class constructors must be invoked with |new|

### ISSUE THREAD

**Issue by joshbruning** [mozilla/geckodriver#995] opened 2017-10-03 17:26 UTC
We're experiencing several errors like this (Firefox 56+):
org.openqa.selenium.WebDriverException: TypeError: class constructors must be invoked with |new|

Mostly this one is causing us grief:
http://searchfox.org/mozilla-central/source/testing/marionette/driver.js#2708

Also see many others just looking at the code:
http://searchfox.org/mozilla-central/source/testing/marionette/driver.js#207
http://searchfox.org/mozilla-central/source/testing/marionette/driver.js#223
http://searchfox.org/mozilla-central/source/testing/marionette/driver.js#3323

I believe code that reads like:
throw UnknownError("Unable to find cookie");

Should be modified to be like:
throw new UnknownError("Unable to find cookie");

**Comment by joshbruning** [comment] 2017-10-03 17:28
Will all such issues be fixed in https://bugzilla.mozilla.org/show_bug.cgi?id=1405325 - or just the cookie one?

**Comment by andreastt** [comment] 2017-10-03 17:37
Duplicate of https://github.com/mozilla/geckodriver/issues/989.

**Comment by whimboo** [comment] 2017-10-05 19:15
@andreastt this is not a dupe per se. Your patches on [bug 1405325](https://bugzilla.mozilla.org/show_bug.cgi?id=1405325) do not care of all the other cases.

**Comment by whimboo** [comment] 2017-10-05 19:25
@joshbruning, thank you for filing the issue. I created [bug 1406150](https://bugzilla.mozilla.org/show_bug.cgi?id=1406150) to get this fixed.

**Comment by whimboo** [comment] 2019-01-30 08:41
This has been already fixed in Marionette for Firefox 57.

**Closed by whimboo** 2019-01-30 08:41 UTC
Labels: marionette
