### ISSUE TITLE
Firefox exits immediately with the message "Tried to run command without establishing a connection"

### ISSUE THREAD

**Issue by sethfowler** [mozilla/geckodriver#1512] opened 2019-02-28 01:53 UTC
Firefox is now exiting immediately on startup for me; my test code doesn't even get a chance to start running. The message from the trace log is "Tried to run command without establishing a connection". This is a new problem that just started for me; it may be related to Firefox 65, but I'm not sure.

I was originally on geckodriver 0.23. I updated to 0.24, but it made no difference.

## System

* Version: 0.24 (also happens on 0.23)
* Platform: macOS 10.14.2
* Firefox: 65.0.1
* Selenium: npm's `selenium-webdriver 4.0.0-alpha.1`

## Stacktrace

This seems like the relevant portion of the log:

```
1551317984754	webdriver::server	DEBUG	-> DELETE /session/61eeb140-c3d4-ed4a-90a1-ccce919411c0
1551317984755	Marionette	DEBUG	0 -> [0,2,"Marionette:Quit",{"flags":["eForceQuit"]}]
1551317984756	Marionette	INFO	Stopped listening on port 62935
1551317984818	Marionette	DEBUG	0 <- [1,2,null,{"cause":"shutdown"}]
1551317984896	webdriver::server	DEBUG	Deleting session
1551317984908	Marionette	DEBUG	0 -> [0,3,"Marionette:Quit",{"flags":["eForceQuit"]}]
1551317984909	Marionette	DEBUG	0 <- [1,3,{"error":"invalid session id","message":"Tried to run command without establishing a connection","stacktrace":"WebDriver ... et@chrome://marionette/content/server.js:236:8\n_onJSONObjectReady/<@chrome://marionette/content/transport.js:490:9\n"},null]
```

## Trace-level log

For geckodriver 0.23:
[trace-log.txt](https://github.com/mozilla/geckodriver/files/2913019/trace-log.txt)

For geckodriver 0.24:
[trace-log-0-24.txt](https://github.com/mozilla/geckodriver/files/2913028/trace-log-0-24.txt)

**Comment by andreastt** [comment] 2019-02-28 15:46
It looks like geckodriver is calling `Maironette:Quit` twice, which means the session is not being reset after this: https://searchfox.org/mozilla-central/rev/2a6f3dde00801374d3b2a704232de54a132af389/testing/geckodriver/src/marionette.rs#312

This _I believe_ is https://bugzilla.mozilla.org/show_bug.cgi?id=1403510. This is related to the problem reported in https://github.com/mozilla/geckodriver/issues/732, because it also manifests if you delete the session twice.

**Comment by whimboo** [comment] 2019-03-04 11:06
Dupe of #732.

**Closed by whimboo** 2019-03-04 11:06 UTC
