### ISSUE TITLE
WebDriverException: Message: Process unexpectedly closed with status: 4

### ISSUE THREAD

**Issue by bobotzzz** [mozilla/geckodriver#1118] opened 2017-12-30 21:19 UTC
how can I pass over this error?
## System
* Version: geckodriver 0.19.1
* Platform: rPi3 raspbian stretch
* Firefox: 57.0.3 build1
* Selenium: selenium 3.8.0

## Testcase

import requests
from selenium import webdriver
from pyvirtualdisplay import Display
from selenium.webdriver import FirefoxOptions

from pagetwo import seleniumLogic

duration = 2 #seconds
#duration == 2000 #milliseconds for windows
freq = 440  # Hz

options = FirefoxOptions()
options.add_argument("--headless")
display = Display(visible=0, size=(1920,1080))
display.start()

driver = webdriver.Firefox(firefox_options = options) #  here is the fail 

## Stacktrace:

pi@raspberrypi:~/work/thegreatstart $ time python runnerpagetwo.py 
Traceback (most recent call last):
  File "runnerpagetwo.py", line 17, in <module>
    driver = webdriver.Firefox(firefox_options = options)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/firefox/webdriver.py", line 158, in __init__
    keep_alive=True)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/webdriver.py", line 154, in __init__
    self.start_session(desired_capabilities, browser_profile)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/webdriver.py", line 243, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/webdriver.py", line 311, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/errorhandler.py", line 237, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: Process unexpectedly closed with status: 4

## geckodriver log:

1514668009591	geckodriver	INFO	geckodriver 0.19.1
1514668009637	geckodriver	INFO	Listening on 127.0.0.1:40433
1514668011659	mozrunner::runner	INFO	Running command: "/usr/bin/firefox" "-marionette" "--headless" "-profile" "/tmp/rust_mozprofile.sX2hCCkyz7rp"
*** You are running in headless mode.
1514668017670	Marionette	INFO	Enabled via --marionette
ExceptionHandler::GenerateDump cloned child ExceptionHandler::WaitForContinueSignal waiting for continue signal...
5580
ExceptionHandler::SendContinueSignalToChild sent continue signal to child
[Child 5563, Chrome_ChildThread] WARNING: pipe error (27): Connection reset by peer: file /build/firefox-AV6KPu/firefox-57.0.3+build1/ipc/chromium/src/chrome/common/ipc_channel_posix.cc, line 353

**Comment by andreastt** [comment] 2018-01-02 12:43
This seems to be a duplicate of either https://github.com/mozilla/geckodriver/issues/1020 or https://github.com/mozilla/geckodriver/issues/1088, except this happens when run in headless mode.

**Closed by andreastt** 2018-01-02 12:43 UTC

**Comment by whimboo** [comment] 2018-01-04 11:09
@bobotzzz does raspbian have the gtk packages installed? If not you are most likely affected by issue #1037. As such you cannot use the headless mode yet.
