### ISSUE TITLE
Firefox does not use the expected profile and client certificate

### ISSUE THREAD

**Issue by hurrikam** [mozilla/geckodriver#1906] opened 2021-07-05 13:49 UTC
## Description

Hi,
none of the solutions/workarounds discussed in similar issues has worked for me. When using `geckodriver` (and Selenium), I'm still unable to have Firefox using the expected profile settings and the pre-configured client SSL certificate.

As a prerequisite, I've followed these steps:

1. Create a new Firefox profile called `automation`
2. Goto `about:profiles` and launched a new window using the profile
3. Imported the client SSL certificate needed to open our test website, under `Settings -> Privacy & Security ->  Certificates -> View Certificates... -> Your Certificates`
4. Confirmed I can manually navigate to that website in the current window (even after closing and relaunching Firefox) 

In order to use the cert with the Selenium JS bindings, I have:

1. Zipped the profile folder `/Users/hurrikam/Library/Application Support/Firefox/Profiles/6v2obh7k.automation`. I've tried both zipping the folder itself, then just its content.
2. Used the `Testcase` steps below to create a WebDriver instance capable of opening the test website

NOTE: I've also added the `security.default_personal_cert` entry to the `prefs.js` file of the test profile, before zipping it.

## System

* Version: 0.29.1 (970ef713fe58 2021-04-08 23:34 +0200)
* Platform: macOS Big Sur 11.4 (20F71)
* Firefox: 89.0.2 (64-bit)
* Selenium: selenium-webdriver 4.0.0-beta.4 (NPM package)

## Testcase

```
const { readFileSync } = require('fs');
const serverUrl = 'http://localhost:4444/wd/hub';
const platform = 'MAC';
    const profileZipData = readFileSync('/Users/hurrikam/Library/Application Support/Firefox/Profiles/6v2obh7k.automation.zip');
    const profileZipBase64 = profileZipData.toString('base64');
    const options = new firefox.Options()
        .set('profile', profileZipBase64)
        .setPreference('media.gmp-manager.updateEnabled', true)
        .setPreference('security.default_personal_cert', 'Select Automatically')
    return new Builder()
        .usingServer(serverUrl)
        .withCapabilities(Capabilities.firefox()
            .setPlatform(platform)
        )
        .setFirefoxOptions(options)
        .build();
```

## Stacktrace

The Selenium Server hub instance shows:

```
14:21:53.503 INFO [RequestHandler.process] - Got a request to create a new session: Capabilities {browserName: firefox, moz:debuggerAddress: true, moz:firefoxOptions: {prefs: {media.gmp-manager.updateEnabled: true, security.default_personal_cert: Select Automatically}}, platformName: mac, profile: UEsDBBQAAAAAAK1x5VIAAAAAAAA...}
14:21:53.506 INFO [TestSlot.getNewSession] - Trying to create a new session on test slot {server:CONFIG_UUID=446f004e-dc1f-463c-ad5f-fdbdeb8c59b4, seleniumProtocol=WebDriver, browserName=firefox, maxInstances=1, platformName=MAC, platform=MAC}
```

The Selenium Server node instance shows:

```
Capabilities are: {
  "browserName": "firefox",
  "moz:debuggerAddress": true,
  "moz:firefoxOptions": {
    "prefs": {
      "media.gmp-manager.updateEnabled": true,
      "security.default_personal_cert": "Select Automatically"
    }
  },
  "platformName": "mac",
  "profile": "UEsDBBQAAAA....AAAAA="
}
14:21:53.657 INFO [ActiveSessionFactory.lambda$apply$11] - Matched factory org.openqa.selenium.grid.session.remote.ServicedSession$Factory (provider: org.openqa.selenium.firefox.GeckoDriverService)
1625491313682	geckodriver	INFO	Listening on 127.0.0.1:43504
1625491314713	mozrunner::runner	INFO	Running command: "/Applications/Firefox.app/Contents/MacOS/firefox-bin" "--marionette" "--remote-debugging-port" "0" "-foreground" "-no-remote" "-profile" "/var/folders/tn/93kh5f5s3896fzpmvy4d6fbr0000gp/T/rust_mozprofileMse2LP"
1625491315147	Marionette	INFO	Marionette enabled
2021-07-05 14:21:55.754 firefox-bin[35567:8167202] Warning: Expected min height of view: (<NSButton: 0x12dedec00>) to be less than or equal to 30 but got a height of 32.000000. This error will be logged once per view in violation.
...
2021-07-05 14:21:55.757 firefox-bin[35567:8167202] Warning: Expected min height of view: (<NSPopoverTouchBarItemButton: 0x12e152400>) to be less than or equal to 30 but got a height of 32.000000. This error will be logged once per view in violation.
...
console.warn: SearchSettings: "get: No settings file exists, new profile?" (new NotFoundError("Could not open the file at /var/folders/tn/93kh5f5s3896fzpmvy4d6fbr0000gp/T/rust_mozprofileMse2LP/search.json.mozlz4", (void 0)))
DevTools listening on ws://localhost:52062/devtools/browser/697aad29-f842-ff4d-8bd7-bc0acde8580c
1625491316953	Marionette	INFO	Listening on port 52034
14:21:57.016 INFO [ProtocolHandshake.createSession] - Detected dialect: W3C
14:21:57.037 INFO [RemoteSession$Factory.lambda$performHandshake$0] - Started new session 4de10b29-6dea-7146-a6be-55b944b03daa (org.openqa.selenium.firefox.GeckoDriverService)
```

**Please note** that the `search.json.mozlz4` exists inside the original profile folder (and the zipped profile).

**Comment by whimboo** [comment] 2021-07-14 15:04
Hi @hurrikam. I had a look at your code as shown above, and noticed that the `profile` capability has been added at the top-level. Instead it needs to be under [moz:firefoxOptions](https://developer.mozilla.org/en-US/docs/Web/WebDriver/Capabilities/firefoxOptions#profile). Please check if that fixes the problem for you. Thanks.

**Comment by whimboo** [comment] 2021-07-14 15:05
Well hereby I'm referring to the log output:
```
Capabilities are: {
  "browserName": "firefox",
  "moz:debuggerAddress": true,
  "moz:firefoxOptions": {
    "prefs": {
      "media.gmp-manager.updateEnabled": true,
      "security.default_personal_cert": "Select Automatically"
    }
  },
  "platformName": "mac",
  "profile": "UEsDBBQAAAA....AAAAA="
}
```

**Comment by bjm34980** [comment] 2021-07-17 08:35
I think I can join this thread as I have a similar problem.
   using Selenium.WebDriver.GeckoDriver.Win64 0.29.1
   and Selenium.WebDriver 4.0 beta4

    Dim oProfMgr = New SFF.FirefoxProfileManager        ' get desired profile from existing
    Call LogDebug("New", "Available profiles " & Profiles_List())  ' checking desired profile is indeed available among the existing profiles

    Const PROF_FILE As String = "Marionette"                 ' the desired profile
    Dim oMyProfile = oProfMgr.GetProfile(PROF_FILE)
    oMyProfile.DeleteAfterUse = False

    Dim oFFopts = New SFF.FirefoxOptions With {             ' create FF options
      .PageLoadStrategy = S.PageLoadStrategy.Normal,
      .Profile = oMyProfile}

    FFD = New SFF.FirefoxDriver(oFFopts)              ' laucnh Driver

Firefox will use temporary profile using this code (no error raised)
the documentation I found on Capabilities is confusing as it seems to be evolving

can you tell me what is the correct way to proceed
thanks in advance

**Comment by whimboo** [comment] 2022-01-03 11:58
No reply from reporter. Closing the issue.

**Closed by whimboo** 2022-01-03 11:58 UTC
Labels: awaiting reporter feedback

**Comment by tobeitgit** [comment] 2024-04-02 10:46
Good afternoon,

I'm not the original reporter but **this issue is still reproducible**. Same problem happens when we're setting the capability [moz:firefoxOptions](https://developer.mozilla.org/en-US/docs/Web/WebDriver/Capabilities/firefoxOptions#profile) with a value, for example, in our case: `{"args": ["-profile", "/home/juan/.mozilla/firefox/85uv6w5r.automation"]}`.

```
def setup_method():
    logging.basicConfig(filename='/home/juan/lmd.log', level=logging.DEBUG)
    logger = logging.getLogger('selenium')
    logger.setLevel(logging.DEBUG)

    options = Options()
    if platform.system() == "Windows":
        options.binary_location = r"C:\Program Files\Mozilla Firefox\firefox.exe"
    else:
        options.binary_location = r"/home/juan/firefox/firefox"
    options.headless = False
    options.set_capability("moz:firefoxOptions", '{"args": ["-profile", "/home/juan/.mozilla/firefox/'
                                                 '85uv6w5r.automation"]}')
    driver = webdriver.Firefox(options=options)
    driver.implicitly_wait(25)
    return driver
```

Here's is the debug level log (`lmd.log`):

```
DEBUG:selenium.webdriver.common.selenium_manager:Selenium Manager binary found at: /home/juan/ToBeIT/selenium-python/venv/lib/python3.11/site-packages/selenium/webdriver/common/linux/selenium-manager
DEBUG:selenium.webdriver.common.selenium_manager:Executing process: /home/juan/ToBeIT/selenium-python/venv/lib/python3.11/site-packages/selenium/webdriver/common/linux/selenium-manager --browser firefox --browser-path /home/juan/firefox/firefox --debug --language-binding python --output json
DEBUG:selenium.webdriver.common.selenium_manager:Found geckodriver 0.34.0 in PATH: /usr/local/bin/geckodriver
DEBUG:selenium.webdriver.common.selenium_manager:Running command: /home/juan/firefox/firefox -v
DEBUG:selenium.webdriver.common.selenium_manager:Output: "Mozilla Firefox 124.0.1"
DEBUG:selenium.webdriver.common.selenium_manager:Detected browser: firefox 124.0.1
DEBUG:selenium.webdriver.common.selenium_manager:Required driver: geckodriver 0.34.0
DEBUG:selenium.webdriver.common.selenium_manager:Driver path: /usr/local/bin/geckodriver
DEBUG:selenium.webdriver.common.selenium_manager:Browser path: /home/juan/firefox/firefox
DEBUG:selenium.webdriver.common.selenium_manager:Using driver at: /usr/local/bin/geckodriver
DEBUG:selenium.webdriver.common.service:Started executable: `/usr/local/bin/geckodriver` in a child process with pid: 27766 using 0 to output -3
DEBUG:selenium.webdriver.remote.remote_connection:POST http://localhost:53733/session {'capabilities': {'firstMatch': [{}], 'alwaysMatch': {'browserName': 'firefox', 'acceptInsecureCerts': True, 'moz:debuggerAddress': True, 'pageLoadStrategy': <PageLoadStrategy.normal: 'normal'>, 'moz:firefoxOptions': {'binary': '/home/juan/firefox/firefox'}, 'browserVersion': None}}}
DEBUG:urllib3.connectionpool:Starting new HTTP connection (1): localhost:53733
DEBUG:urllib3.connectionpool:http://localhost:53733 "POST /session HTTP/1.1" 200 719
DEBUG:selenium.webdriver.remote.remote_connection:Remote response: status=200 | data={"value":{"sessionId":"d76e2ee0-887d-4fa5-99b2-27308b32618d","capabilities":{"acceptInsecureCerts":true,"browserName":"firefox","browserVersion":"124.0.1","moz:accessibilityChecks":false,"moz:buildID":"20240321230221","moz:debuggerAddress":"127.0.0.1:48261","moz:geckodriverVersion":"0.34.0","moz:headless":false,"moz:platformVersion":"6.1.0-18-amd64","moz:processID":27769,"moz:profile":"/tmp/rust_mozprofilezS0zDm","moz:shutdownTimeout":60000,"moz:webdriverClick":true,"moz:windowless":false,"pageLoadStrategy":"normal","platformName":"linux","proxy":{},"setWindowRect":true,"strictFileInteractability":false,"timeouts":{"implicit":0,"pageLoad":300000,"script":30000},"unhandledPromptBehavior":"dismiss and notify"}}} | headers=HTTPHeaderDict({'content-type': 'application/json; charset=utf-8', 'cache-control': 'no-cache', 'content-length': '719', 'date': 'Tue, 02 Apr 2024 10:19:45 GMT'})
DEBUG:selenium.webdriver.remote.remote_connection:Finished Request
DEBUG:selenium.webdriver.remote.remote_connection:POST http://localhost:53733/session/d76e2ee0-887d-4fa5-99b2-27308b32618d/timeouts {'implicit': 25000}
DEBUG:urllib3.connectionpool:http://localhost:53733 "POST /session/d76e2ee0-887d-4fa5-99b2-27308b32618d/timeouts HTTP/1.1" 200 14
DEBUG:selenium.webdriver.remote.remote_connection:Remote response: status=200 | data={"value":null} | headers=HTTPHeaderDict({'content-type': 'application/json; charset=utf-8', 'cache-control': 'no-cache', 'content-length': '14', 'date': 'Tue, 02 Apr 2024 10:19:48 GMT'})
DEBUG:selenium.webdriver.remote.remote_connection:Finished Request
DEBUG:selenium.webdriver.remote.remote_connection:POST http://localhost:53733/session/d76e2ee0-887d-4fa5-99b2-27308b32618d/window/rect {'x': None, 'y': None, 'width': 1920, 'height': 703}
DEBUG:urllib3.connectionpool:http://localhost:53733 "POST /session/d76e2ee0-887d-4fa5-99b2-27308b32618d/window/rect HTTP/1.1" 200 51
DEBUG:selenium.webdriver.remote.remote_connection:Remote response: status=200 | data={"value":{"x":-45,"y":7,"width":1920,"height":703}} | headers=HTTPHeaderDict({'content-type': 'application/json; charset=utf-8', 'cache-control': 'no-cache', 'content-length': '51', 'date': 'Tue, 02 Apr 2024 10:19:48 GMT'})
DEBUG:selenium.webdriver.remote.remote_connection:Finished Request
```

Browser is started just fine with the specified profile, but none of the personal certificates previous added appear under `Settings -> Privacy & Security ->  Certificates -> View Certificates... -> Your Certificates` when automating with Selenium:

![imatge](https://github.com/mozilla/geckodriver/assets/39725967/813a6044-f447-42d7-b65c-e3fb936805c7)

As a consequence,  authentication using a certificate personal doesn't work.

However, it appears if we start the browser as normal:

![imatge](https://github.com/mozilla/geckodriver/assets/39725967/63fdad13-1fe7-44b1-a64c-49d1c640e95c)

**Comment by whimboo** [comment] 2024-04-02 11:40
@tobeitgit as you can see by the following debug line Selenium is not sending the correct payload of the new session capabilities:

> DEBUG:selenium.webdriver.remote.remote_connection:POST http://localhost:53733/session {'capabilities': {'firstMatch': [{}], 'alwaysMatch': {'browserName': 'firefox', 'acceptInsecureCerts': True, 'moz:debuggerAddress': True, 'pageLoadStrategy': <PageLoadStrategy.normal: 'normal'>, 'moz:firefoxOptions': {'binary': '/home/juan/firefox/firefox'}, 'browserVersion': None}}}

There is no `--profile` argument included for `moz:firefoxOptions` and as such geckodriver creates as expected a new temporary profile.

**Comment by tobeitgit** [comment] 2024-04-03 12:44
**Problem is solved** by specifying a Firefox profile using the following code:

```
def setup_method(profile):
    options = Options()
    if platform.system() == "Windows":
        options.binary_location = r"C:\Program Files\Mozilla Firefox\firefox.exe"
    else:
        options.binary_location = r"/usr/bin/firefox"
    options.headless = False
    options.profile = FirefoxProfile("/home/juan/.mozilla/firefox/85uv6w5r.automation")
    driver = webdriver.Firefox(options=options)
    driver.implicitly_wait(25)
    return driver
```

Debug level log (`lmd.log`) shows that it's working as expected:

```
DEBUG:selenium.webdriver.common.selenium_manager:Selenium Manager binary found at: /home/juan/ToBeIT/selenium-python/venv/lib/python3.11/site-packages/selenium/webdriver/common/linux/selenium-manager
DEBUG:selenium.webdriver.common.selenium_manager:Executing process: /home/juan/ToBeIT/selenium-python/venv/lib/python3.11/site-packages/selenium/webdriver/common/linux/selenium-manager --browser firefox --browser-path /home/juan/firefox/firefox --debug --language-binding python --output json
DEBUG:selenium.webdriver.common.selenium_manager:Found geckodriver 0.34.0 in PATH: /usr/local/bin/geckodriver
DEBUG:selenium.webdriver.common.selenium_manager:Running command: /home/juan/firefox/firefox -v
DEBUG:selenium.webdriver.common.selenium_manager:Output: "Mozilla Firefox 124.0.2"
DEBUG:selenium.webdriver.common.selenium_manager:Detected browser: firefox 124.0.2
DEBUG:selenium.webdriver.common.selenium_manager:Required driver: geckodriver 0.34.0
DEBUG:selenium.webdriver.common.selenium_manager:Driver path: /usr/local/bin/geckodriver
DEBUG:selenium.webdriver.common.selenium_manager:Browser path: /home/juan/firefox/firefox
DEBUG:selenium.webdriver.common.selenium_manager:Using driver at: /usr/local/bin/geckodriver
DEBUG:selenium.webdriver.common.service:Started executable: `/usr/local/bin/geckodriver` in a child process with pid: 12291 using 0 to output -3
DEBUG:selenium.webdriver.remote.remote_connection:POST http://localhost:40531/session {'capabilities': {'firstMatch': [{}], 'alwaysMatch': {'browserName': 'firefox', 'acceptInsecureCerts': True, 'moz:debuggerAddress': True, 'pageLoadStrategy': <PageLoadStrategy.normal: 'normal'>, 'browserVersion': None, 'moz:firefoxOptions': {'binary': '/home/juan/firefox/firefox', 'profile': 'UEsDBBQAAAAIAHFmglgLMOijhQAAACABAAAXAAAAc2Vzc2lvbkNoZWNrcG9pbnRzLmpzb251kEEOwjAMBP+SM/4AvzGtUywFJzgb...'}}}}
DEBUG:urllib3.connectionpool:Starting new HTTP connection (1): localhost:40531
DEBUG:urllib3.connectionpool:http://localhost:40531 "POST /session HTTP/1.1" 200 719
DEBUG:selenium.webdriver.remote.remote_connection:Remote response: status=200 | data={"value":{"sessionId":"1ecc6806-38fd-4fe2-b077-08e7a82df178","capabilities":{"acceptInsecureCerts":true,"browserName":"firefox","browserVersion":"124.0.2","moz:accessibilityChecks":false,"moz:buildID":"20240401114208","moz:debuggerAddress":"127.0.0.1:42807","moz:geckodriverVersion":"0.34.0","moz:headless":false,"moz:platformVersion":"6.1.0-18-amd64","moz:processID":12294,"moz:profile":"/tmp/rust_mozprofilewt76d8","moz:shutdownTimeout":60000,"moz:webdriverClick":true,"moz:windowless":false,"pageLoadStrategy":"normal","platformName":"linux","proxy":{},"setWindowRect":true,"strictFileInteractability":false,"timeouts":{"implicit":0,"pageLoad":300000,"script":30000},"unhandledPromptBehavior":"dismiss and notify"}}} | headers=HTTPHeaderDict({'content-type': 'application/json; charset=utf-8', 'cache-control': 'no-cache', 'content-length': '719', 'date': 'Wed, 03 Apr 2024 10:36:39 GMT'})
DEBUG:selenium.webdriver.remote.remote_connection:Finished Request
DEBUG:selenium.webdriver.remote.remote_connection:POST http://localhost:40531/session/1ecc6806-38fd-4fe2-b077-08e7a82df178/timeouts {'implicit': 25000}
DEBUG:urllib3.connectionpool:http://localhost:40531 "POST /session/1ecc6806-38fd-4fe2-b077-08e7a82df178/timeouts HTTP/1.1" 200 14
DEBUG:selenium.webdriver.remote.remote_connection:Remote response: status=200 | data={"value":null} | headers=HTTPHeaderDict({'content-type': 'application/json; charset=utf-8', 'cache-control': 'no-cache', 'content-length': '14', 'date': 'Wed, 03 Apr 2024 10:36:42 GMT'})
DEBUG:selenium.webdriver.remote.remote_connection:Finished Request
DEBUG:selenium.webdriver.remote.remote_connection:POST http://localhost:40531/session/1ecc6806-38fd-4fe2-b077-08e7a82df178/window/rect {'x': None, 'y': None, 'width': 1920, 'height': 703}
DEBUG:urllib3.connectionpool:http://localhost:40531 "POST /session/1ecc6806-38fd-4fe2-b077-08e7a82df178/window/rect HTTP/1.1" 200 53
DEBUG:selenium.webdriver.remote.remote_connection:Remote response: status=200 | data={"value":{"x":-45,"y":147,"width":1920,"height":703}} | headers=HTTPHeaderDict({'content-type': 'application/json; charset=utf-8', 'cache-control': 'no-cache', 'content-length': '53', 'date': 'Wed, 03 Apr 2024 10:36:42 GMT'})
DEBUG:selenium.webdriver.remote.remote_connection:Finished Request
```

Value `profile` with a Base64 zip profile is automatically added to `moz:firefoxOptions`.
