### ISSUE TITLE
ContextClick is not working in FireFox v54

### ISSUE THREAD

**Issue by GothAr** [mozilla/geckodriver#801] opened 2017-06-27 18:58 UTC
## Platform and application details
* Platform: Windows 10 Enterprise 1703 (OS build 15063.413)
* Firefox: 54.0 (32-bit)
* Selenium: 3.4.0 (C# binding)

## Steps to reproduce
Download NUnit test project from 
[ContextClickInFF.zip](https://github.com/mozilla/geckodriver/files/1106285/ContextClickInFF.zip)
Open it in VS 2015
Build
Run unit tests

- [ ] https://github.com/mozilla/geckodriver page that is used in attached project

- [ ] [geckodriver.txt](https://github.com/mozilla/geckodriver/files/1106449/geckodriver.txt) log file

**Comment by whimboo** [comment] 2017-06-29 05:26
Dupe of issue #660.

**Closed by whimboo** 2017-06-29 05:26 UTC
