### ISSUE TITLE
Getting a WinError 10053 in geckodriver v0.21

### ISSUE THREAD

**Issue by GraceAredel** [mozilla/geckodriver#1369] opened 2018-09-10 12:39 UTC
## System

* Version: geckodriver v0.21
* Platform: Windows 10
* Firefox: 63.0b4 64bit
* Selenium: Webdriver v3.14

## Testcase

What I try to do in PyCharm Python Console to run the driver: 
`from selenium import webdriver
profile = webdriver.FirefoxProfile()
profile.accept_untrusted_certs = True
wd = webdriver.Firefox(executable_path="C:\\Users\\user\\geckodriver.exe", firefox_profile=profile)
url = "https://website-address.com/"
wd.get(url)`

After that a browser opens with my link. but _sometimes_ I still get a WinError 10053, i.e.:
1. In console I write `wd.find_element_by_xpath('xpath').send_keys('mail@mail.com')` and it works just fine.
2. Then I write `wd.find_element_by_xpath('xpath').send_keys('numbers')` aaaand here's the stacktrace:

## Stacktrace

```
Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "C:\Users\user\project\venv\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 393, in find_element_by_xpath
    return self.find_element(by=By.XPATH, value=xpath)
  File "C:\Users\user\project\venv\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 966, in find_element
    'value': value})['value']
  File "C:\Users\user\project\venv\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 318, in execute
    response = self.command_executor.execute(driver_command, params)
  File "C:\Users\user\project\venv\lib\site-packages\selenium\webdriver\remote\remote_connection.py", line 472, in execute
    return self._request(command_info[0], url, body=data)
  File "C:\Users\user\project\venv\lib\site-packages\selenium\webdriver\remote\remote_connection.py", line 495, in _request
    self._conn.request(method, parsed_url.path, body, headers)
  File "C:\Users\user\AppData\Local\Programs\Python\Python36\lib\http\client.py", line 1239, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "C:\Users\user\AppData\Local\Programs\Python\Python36\lib\http\client.py", line 1285, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "C:\Users\user\AppData\Local\Programs\Python\Python36\lib\http\client.py", line 1234, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "C:\Users\user\AppData\Local\Programs\Python\Python36\lib\http\client.py", line 1065, in _send_output
    self.send(chunk)
  File "C:\Users\user\AppData\Local\Programs\Python\Python36\lib\http\client.py", line 986, in send
    self.sock.sendall(data)
ConnectionAbortedError: [WinError 10053] An established connection was aborted by the software in your host machine
```
Please help me to understand and fix this issue.

## Trace-level log

[geckodriver.log](https://github.com/mozilla/geckodriver/files/2366633/geckodriver.log)

**Comment by GraceAredel** [comment] 2018-09-10 12:40
P.S. First I had another issue using geckodriver v0.20 and I wrote about it [here](https://stackoverflow.com/questions/52222110/cannot-run-firefox-geckodriver-properly-from-pycharm-python-console/), but after upgrading the driver I got this.

**Comment by whimboo** [comment] 2018-09-10 13:09
Looks like a dupe of #1305.

**Closed by whimboo** 2018-09-10 13:09 UTC
