### ISSUE TITLE
New Error on Geckodriver (Probably due to new update?)-> OSError: [Errno 86] Bad CPU type in executable: '/Users/InstaPy/assets/geckodriver' 

### ISSUE THREAD

**Issue by KartarC** [mozilla/geckodriver#1933] opened 2021-09-16 23:15 UTC
## System

* Version: v0.30.0
* Platform: MacOS Catalina 10.15.6
* Firefox:  72.0.2
* Selenium:  3.141.0

## Testcase

Running an InstaPy bot, working great since this morning, and encountered this error. code is simple and has been working since last night. This morning, it stopped working. Probably after "geckodriver auto-install" installed the new version (I'm assuming). 

## Stacktrace

OSError: [Errno 86] Bad CPU type in executable: '/Users/kartarC/InstaPy/assets/geckodriver'

## Trace-level log

Workspace in use: "/Users/kartarC/InstaPy"
Traceback (most recent call last):
  File "/Users/kartarC/Library/Application Support/JetBrains/PyCharmCE2020.1/scratches/quickstart2.py", line 24, in <module>
    session = InstaPy(username='xxxxxxxx', password='xxxxxxxx', headless_browser=True)
  File "/Users/kartarC/PycharmProjects/InstaPy/venv/lib/python3.7/site-packages/instapy/instapy.py", line 340, in __init__
    geckodriver_log_level,
  File "/Users/kartarC/PycharmProjects/InstaPy/venv/lib/python3.7/site-packages/instapy/browser.py", line 127, in set_selenium_local_session
    options=firefox_options,
  File "/Users/kartarC/PycharmProjects/InstaPy/venv/lib/python3.7/site-packages/selenium/webdriver/firefox/webdriver.py", line 164, in __init__
    self.service.start()
  File "/Users/kartarC/PycharmProjects/InstaPy/venv/lib/python3.7/site-packages/selenium/webdriver/common/service.py", line 76, in start
    stdin=PIPE)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/subprocess.py", line 775, in __init__
    restore_signals, start_new_session)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/subprocess.py", line 1522, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
OSError: [Errno 86] Bad CPU type in executable: '/Users/kartarC/InstaPy/assets/geckodriver'

<img width="624" alt="Screen Shot 2021-09-16 at 7 14 52 PM" src="https://user-images.githubusercontent.com/39412314/133697233-a5621031-1375-4981-849f-b2b211d06bb4.png">

**Comment by mattalat** [comment] 2021-09-16 23:53
I have also seen this issue with the following context:

Version: 0.30.0
Platform: MacOS 11.6 (Big Sur)
Firefox: 92.0
Selenium: Ruby, selenium-webdriver 3.142.7

Downgrading to 0.29.1 fixes it.

**Comment by mattalat** [comment] 2021-09-16 23:54
Looks like this is a duplicate of #1932. Sorry for the noise!

**Comment by KartarC** [comment] 2021-09-17 01:23
@mattalat thanks! I'm trying to downgrade to 29.1. Not sure how to do on Pycharm?

**Comment by KartarC** [comment] 2021-09-17 02:12
> Looks like this is a duplicate of #1932. Sorry for the noise!

I checked this out. looks like it has been fixed but then it would have auto-installed as I downloaded the geckodriver_autoinstaller. The error is still there. :(

**Comment by whimboo** [comment] 2021-09-17 04:30
Dupe if #1932.

There is no geckodriver_autoinstaller that we ship. If it's a different project please file an issue there if something is broken. Thanks.

**Closed by whimboo** 2021-09-17 04:30 UTC
