### ISSUE TITLE
Firefox memory leak

### ISSUE THREAD

**Issue by JanVomlel** [mozilla/geckodriver#1558] opened 2019-05-23 13:57 UTC
## System

* Version: v0.24.0-win64
* Platform: Windows 10
* Firefox: 60.7.0esr
* Selenium: 3.141.59

## Testcase
This simple code causes firefox consume more and more memory. That is why our long running tests crashe.

    package cz.aipsafe.safe.test.www.tests;

    import org.openqa.selenium.By;
    import org.openqa.selenium.WebDriver;
    import org.openqa.selenium.firefox.FirefoxDriver;
    import org.testng.annotations.Test;

    public class RepeatSimpleTest {
        @Test
        public void repeat() {
            System.setProperty("webdriver.gecko.driver", "....\\gecko-driver-64\\geckodriver.exe");
            WebDriver driver = new FirefoxDriver();
            while(true) {
                driver.get("https://google.com");
                driver.findElements(By.xpath("//body"));
            }
        }
    }

**Comment by andreastt** [comment] 2019-05-23 16:15
Thanks for reporting this! I believe this may be a duplicate of https://github.com/mozilla/geckodriver/issues/181, because the steps look really similar.

It would be good if you could comment over there whether it happens if you just navigate, or if it only happens when you locate an element so we can pinpoint the cause more clearly.

**Closed by andreastt** 2019-05-23 16:15 UTC
