### ISSUE TITLE
geckodriver 0.30.0 - macos x86_64 and arm64 are interchanged.

### ISSUE THREAD

**Issue by pbi-qfs** [mozilla/geckodriver#1932] opened 2021-09-16 15:26 UTC
## System

* Version: 0.30.0
* Platform: macOS

- https://github.com/mozilla/geckodriver/releases/download/v0.30.0/geckodriver-v0.30.0-macos-aarch64.tar.gz contains the executable file for x86_64
- https://github.com/mozilla/geckodriver/releases/download/v0.30.0/geckodriver-v0.30.0-macos.tar.gz contains the executable for arm64 processors

The names of the tar files suggest it otherwise...

**Comment by whimboo** [comment] 2021-09-16 19:46
Thanks a lot for letting us know about that! I checked and you are totally correct. I'm sorry that this happened, and it has been fixed now.

**Closed by whimboo** 2021-09-16 19:46 UTC
Labels: geckodriver

**Comment by lunohodov** [comment] 2021-09-17 05:57
@whimboo It looks like nothing changed in the [0.30 release](https://github.com/mozilla/geckodriver/releases/tag/v0.30.0) since @pbi-qfs created this issue. I downloaded the linked binaries and ran `file` on both of them. The archs are still interchanged.

I'm confused by your comment that the problem is resolved. Please advise.

Thank you!

**Comment by Uepsilon** [comment] 2021-09-17 09:01
it was either github cache or it was just updated but it seems to be fixed now. at least for me. file sizes of the archives swapped and they are now as expect..

many thanks 👍

**Comment by whimboo** [comment] 2021-09-17 09:05
I renamed both artifacts yesterday, re-downloaded myself and ran the binary, which was working fine. Using `file` I was indeed able to see the wrong architecture. This is kinda puzzling!

As such I decided to re-upload the files, and can confirm that it's working correctly now, and `file` is reporting the right platform.

**Comment by whimboo** [comment] 2021-09-28 19:53
Not sure why there was a new report for this already fixed issue, but I tested again both binaries, and `file` still reports the correct architecture for me.
