### ISSUE TITLE
When I open a new tab in firefox, driver.get(url) sometimes does not return results.

### ISSUE THREAD

**Issue by xihangalpha** [mozilla/geckodriver#1313] opened 2018-06-27 12:27 UTC
## System
* Version: 
* Platform: 
* Firefox: 
* Selenium: 

Code (for example):
ActionChains(driver).key_down(Keys.CONTROL).send_keys("t").key_up(Keys.CONTROL).perform()
driver.switch_to_window(driver.window_handles[-1])
driver.get(url)

Sometimes, Firefox can open new tab, but it stops and can not further navigate to the targeted website. In rest cases, Firefox can perform the task successfully.
What is the problem? Can anyone help?

**Comment by xihangalpha** [comment] 2018-06-27 12:28
System:

Firefox 52
Selenium 3.8.1
geckodriver 0.16.0
Windows Vista

**Comment by whimboo** [comment] 2018-06-28 12:06
First, such an action is not possible. Via Ctrl+T no new tab can be opened because the permissions are outside those for web content. So I don't see how a new tab even sometimes can be opened that way. 

Dupe of issue #786.

**Closed by whimboo** 2018-06-28 12:06 UTC

**Comment by xihangalpha** [comment] 2018-07-09 23:01
OK. Maybe I have to try realize this action in another way.

**Comment by whimboo** [comment] 2018-07-24 18:49
You can use a call to `execute_script` and call `window.open()` there. By default Firefox will open a new tab.
