### ISSUE TITLE
Unble to close the firefox browser instance or session using driver.quit() command 

### ISSUE THREAD

**Issue by Ravindran1** [mozilla/geckodriver#975] opened 2017-09-27 15:34 UTC
## System
* Version: 0.18.0
* Platform: Mac
* Firefox: 52
* Selenium: 3.5.3

**Comment by andreastt** [comment] 2017-09-27 15:58
Duplicate of https://github.com/mozilla/geckodriver/issues/966?

**Closed by andreastt** 2017-09-27 15:58 UTC
