### ISSUE TITLE
Unknown command `performActions`

### ISSUE THREAD

**Issue by igrishaev** [mozilla/geckodriver#437] opened 2017-01-18 21:11 UTC
Hi team,
I cannot run the `performActions` API properly. When I send an HTTP request to the running geckodriver instance as follows:

```
POST /session/bd51f7eb-d58f-f94b-8a2e-b2fe49b79327/actions
{:actions [{:type "pointer" :actions [{:type "pointerDown" :button 123}]}]}
```

I get the response:

```
404 "{\"error\":\"unknown command\",\"message\":\"performActions\"}"
```

I examined webdriver-rust code and found it passes the data properly, but nevertheless there is an error. Can anyone give me a clue? Thanks.  

Gecko driver version 0.13.0
Firefox Version 50.1.0
Mac Os El Captain 10.11.6 (15G31)

**Comment by andreastt** [comment] 2017-01-18 22:46
Duplicate of https://github.com/mozilla/geckodriver/issues/233.

**Closed by andreastt** 2017-01-18 22:46 UTC
