### ISSUE TITLE
Is there an issue with Application Insights since v57 (13. Sep. 2017)?

### ISSUE THREAD

**Issue by curtisy1** [mozilla/geckodriver#964] opened 2017-09-20 15:32 UTC
## System
* Version: 0.19.0
* Platform: Windows 10
* Firefox: Devtools/Nightly
* Selenium: dotNet 3.5.2

## Testcase

Just a general question, but if you need a testcase, I'll see if I can trigger this in my company's readonly account. Basically what happens since September 13th is that after navigating from one page to another using Selenium's driver.navigate.gotourl(), the page get's stuck in interactive mode and loads forever. Hence all test would fail. For now I could circumvent this using Devtools instead of Nigthly, but with 57 released for Devtools today, I can't run my tests anymore because most of them rely on Contextclicks (which was fixed from 56+). The thing that I found is that apparently it's always the same URL I get stuck on, namely az416426.vo.msecnd.net. I've attached a trace level log, however as it gets stuck on the get operation, i'm not sure if there's much use to it.

## Stacktrace

I'll add this later, don't have it at hand right now

## Trace-level log

Is attached
[TraceLog.txt](https://github.com/mozilla/geckodriver/files/1318263/TraceLog.txt)

**Comment by andreastt** [comment] 2017-09-22 12:38
I don’t see any DOM load events being logged after this:

    1505920839976   geckodriver::marionette TRACE   -> 58:[0,111,"get",{"url":"http://localhost:53294//Tour/Order"}]

This could mean that http://localhost:53294//Tour/Order never loads or that Marionette has reached a non-recoverable state. Unfortunately, without a document which reproduces this behaviour I’m not sure there is much we can do.

**Comment by curtisy1** [comment] 2017-09-22 13:04
Yeah, I figured that as well. I suspect the latter because loading http://localhost:53294//Tour/Order and going through the test case manually in a freshly started firefox instance works perfectly fine. I'll see what I can do to reproduce this in a readonly context so you can maybe reproduce this somehow as well.

**Comment by whimboo** [comment] 2017-09-26 07:28
@curtisy1 does the hang also happen when this command is the only one which gets executed by the test? Also please do not cut off the log afterward. I would like to see what happens when you manually close Firefox or abort the test.

Further you are saying that a Nightly build from Sep 12th is working? If yes would you mind to tell us which exact nightly builds you are using for testing that? We ship two Nightlies per day, and to reduce the number of changes it would be good to know the revisions of both. You can get this by opening `about:buildconfig` and copying the above link.

Thanks.

**Comment by curtisy1** [comment] 2017-09-26 09:27
It's the first thing that happens after the login, so basically there's not
much before that apart from custom waits (for a spinner and jQuery). I'm
getting back to trying the September 12 builds once I'm at work this
afternoon. Thanks for the help so far I really appreciate it.

**Comment by whimboo** [comment] 2017-09-26 10:39
Btw. you can find older Nightly builds here:
https://archive.mozilla.org/pub/firefox/nightly/2017/09/

Look at any folder name containing `mozilla-central`. So those are most likely what you want:

https://archive.mozilla.org/pub/firefox/nightly/2017/09/2017-09-12-01-36-00-mozilla-central/
https://archive.mozilla.org/pub/firefox/nightly/2017/09/2017-09-12-10-01-39-mozilla-central/
https://archive.mozilla.org/pub/firefox/nightly/2017/09/2017-09-12-22-03-43-mozilla-central/
https://archive.mozilla.org/pub/firefox/nightly/2017/09/2017-09-13-10-01-25-mozilla-central/
https://archive.mozilla.org/pub/firefox/nightly/2017/09/2017-09-13-22-01-21-mozilla-central/

**Comment by curtisy1** [comment] 2017-09-26 12:52
@whimboo With the versions above, only the first one successfully runs through the test. The others fail at the exact same place as the previous version from September 13. The last working version for me was hence [this one](https://hg.mozilla.org/mozilla-central/rev/bda524beac249b64aa36016800502a34073bf35a), while [the following one](https://hg.mozilla.org/mozilla-central/rev/b0e945eed81db8bf076daf64e381c514f70144f0).

I've also gotten some logs after closing Firefox as you requested. This is the output in addition to what I already gave above. Manually aborting the test leaves both Firefox and geckodriver open, so no new commands get added below the get operation.
[Trace_CloseBrowser.txt](https://github.com/mozilla/geckodriver/files/1333153/Trace_CloseBrowser.txt)

Interestingly, I've reproduced this on another page which fails to load as well, so I might be able to provide a reproducable testcase hopefully.

**Comment by whimboo** [comment] 2017-09-27 08:39
Ok, so that's a good information and results in the following [list of changes](https://hg.mozilla.org/mozilla-central/pushloghtml?fromchange=bda524beac249b64aa36016800502a34073bf35a&tochange=b0e945eed81db8bf076daf64e381c514f70144f0) between those two builds.

The list of changes are still too much. So further testing would be necessary. But before that please check if turning the preference `network.preload` to `false` makes a difference for you. If not please also turn `layout.css.servo.enabled` to false.

If both don't work please test the following build: 
32bit: https://queue.taskcluster.net/v1/task/Qspwzi7gRU-sv1j-HRSp-g/runs/0/artifacts/public/build/target.zip
64 bit: https://queue.taskcluster.net/v1/task/JU5F2LRrSCmFeT4C9mpKHA/runs/0/artifacts/public/build/target.zip

Maybe try a debug build too which would give more details information:

32bit: https://queue.taskcluster.net/v1/task/P16izqaaReOTA4JeW2gSAA/runs/0/artifacts/public/build/target.zip
64 bit: https://queue.taskcluster.net/v1/task/RW9nPH9mT6icGPdofKCDpw/runs/0/artifacts/public/build/target.zip

**Comment by whimboo** [comment] 2017-09-27 08:41
> Interestingly, I've reproduced this on another page which fails to load as well, so I might be able to provide a reproducable testcase hopefully.

If that works I would be totally interested in that page!

**Comment by curtisy1** [comment] 2017-10-04 12:25
@whimboo Sorry for the late reply, I haven't been able to work due to a cold and a bunch of free days in Germany. I tested the options you suggested but I can't seem to get any step further. The Trace log also stays the same.

The standard build you posted had the same issue while the debug version seems to run fine so far. I guess I need to run my tests a couple more times to say for sure, but it's looking promising so far.

I'm still working on getting this error to work reliably (as ironically as this may sound). So a test case should hopefully be done by the end of this week.

Thanks for the help so far, I really appreciate it.

**Comment by whimboo** [comment] 2017-10-04 13:47
Did you remove parts of the debug log? Especially those lines between requesting a `get` and until that call returns? I don't see any corresponding lines in there. It directly continues with the call to `executeScript`. But maybe it' just not a trace log.

Anyway if both builds are failing it is fine. I just want to make sure it is reproducible for those CI builds too. Did you had the chance to test the two preferences as I mentioned? Were there any difference?

**Comment by curtisy1** [comment] 2017-10-04 15:12
You're right, this isn't a trace log. Just the debug lines following after the browser hangs on the GET operation, sorry for the confusion. I'll attach a new trace log tomorrow when I'm at work again.

The preferences didn't help unfortunately. I tested with the CI builds as well as with the "normal" Nightly version to no avail. The same thing still happens.

**Comment by whimboo** [comment] 2017-10-04 19:19
Ok, good. So checking this [list of changes](https://hg.mozilla.org/mozilla-central/pushloghtml?fromchange=bda524beac249b64aa36016800502a34073bf35a&tochange=175f1366daee) I feel that maybe [bug 1398601] could have an impact here which enabled JSM global sharing.

Would you mind to test with such an affected build and updating your test, so that the preference `jsloader.shareGlobal` is set to `false`? If that also doesn't work some more checks would have to be done and I can give you pointers.

**Comment by curtisy1** [comment] 2017-10-05 11:44
Alright, so if I got this correct it still doesn't work. I tested both builds from [this commit](https://hg.mozilla.org/mozilla-central/rev/fe7465d53091) with the preference ```jsloader.shareGlobal``` set to ```false```. The "first release with" version did not work, while the "last release without version" worked. I've attached two tracelogs, one with the debug version you previously sent me and one of the version published in relation to that bug.

[Tracelog_Debugbuild.txt](https://github.com/mozilla/geckodriver/files/1359143/Tracelog_Debugbuild.txt)
[Tracelog_Bug.txt](https://github.com/mozilla/geckodriver/files/1359144/Tracelog_Bug.txt)

**Comment by whimboo** [comment] 2017-10-12 20:22
@curtisy1 thank you for the logs. I had a look at those and I cannot see that you flipped the preference `jsloader.shareGlobal` to false. Did you miss that?

Otherwise I find the following order of commands strange:

```
1507198080608   geckodriver::marionette TRACE   -> 60:[0,145,"get",{"url":"http://localhost:53294//Login/Logout"}]
1507198080610   Marionette      TRACE   0 -> [0,145,"get",{"url":"http://localhost:53294//Login/Logout"}]
...
1507198140611   webdriver::server       DEBUG   -> POST /session/7ae35c02-e537-46d9-8ef9-f48bc32855d3/execute/sync {"script":"return jQuery.active == 0","args":[]}
```

@andreastt do you have an idea why we are sending another command while `get` has not been finished yet?

**Comment by whimboo** [comment] 2017-10-12 20:37
@curtisy1 to get closer it might be very helpful if you could continue testing builds. I setup the following query for Treeherder, which will again give you all the changes in the above range, and the appropriate build to run. I will quickly describe how to run the investigation.

1. Open https://treeherder.mozilla.org/#/jobs?repo=autoland&fromchange=a57eaa7832b2&tochange=9232bc78ae68&filter-searchStr=build%20windows
2. Try the oldest and newest builds, and ensure that the oldest works and the newest fails
2.a) To get the build click the green `2+` next to the platform you want to test. As best take an opt build
2.b) Then click the green `B`, and find the target.dmg in the panel which opens at the bottom
3. Now bisect the range by picking the build from the middle of all changesets
4. Divide the range step by step until you found the first changeset which shows the issue

To make it easier to see which changesets are remaining you can update the `tochange` and `fromchange` parameters in the url, given the test status of the current changeset. If it passed update `fromchange` otherwise `tochange`.

**Comment by curtisy1** [comment] 2017-10-12 20:54
@whimboo regarding the "script return jQuery active == 0" POST, that looks
like my custom wait that I use because Selenium itself doesn't wait for
Ajax calls and the like. Since the page gets stuck in interactive mode
though and it worked in the builds before, I don't think that's the
problem. I'll still provide the method for clarification when at work
tomorrow.

On another note, I noticed I can change the webdriver.load.strategy to
unstable. Might that help with something?

I'll try what you suggested tomorrow and report back.

Am Do., 12. Okt. 2017, 22:37 schrieb Henrik Skupin <notifications@github.com

**Comment by curtisy1** [comment] 2017-10-13 08:48
@whimboo Alright, I tested the builds using the steps you mentioned. The first build that fails is [269426fcc3f3](https://hg.mozilla.org/integration/autoland/rev/269426fcc3f39673ae0b4aa167ac00d8534542ca) which I guess could make sense since Application Insights is a tail request?

I attached another log taken with this build and ```jsloader.shareGlobal``` set to ```false```
[Tracelog_269426fcc3f3.txt](https://github.com/mozilla/geckodriver/files/1381925/Tracelog_269426fcc3f3.txt)

**Comment by whimboo** [comment] 2017-10-13 13:38
Ok, so the Ajax thing is new and it would have been of help if mentioned earlier. Anyway, it looks still suspicious because the `get` command was used, and it has to return before any other command can be send. I cannot explain that actually.

It's great to see that you figured out the changset which is causing that. I have to admit that I don't know anything about application insight, and as such I would simply propose that you are filing a bug on Bugzilla about this problem. It should be in the [networking component](https://bugzilla.mozilla.org/enter_bug.cgi?product=Core&component=Networking). When you let me know the bug number after the creation I can set all the necessary flags and let people know about. Given that it is a regression in 57 we still have a bit of time to get it fixed before the actual release. Something which would drastically help developers is a good testcase to get it reproduced. If you have a chance to also create one, that would be fantastic. Otherwise describe exactly what you are doing and which results you get.

**Comment by curtisy1** [comment] 2017-10-13 14:41
Thanks for the help so far! I filed a bug at bugzilla now, see [here](https://bugzilla.mozilla.org/show_bug.cgi?id=1408411). I'm trying to work on a testcase over the weekend since after that school's coming up.

**Comment by whimboo** [comment] 2017-10-13 16:08
Great. So lets move the conversation over to that bug now. Which also means that it's not really a geckodriver issue and I can close this issue now.

**Closed by whimboo** 2017-10-13 16:08 UTC
Labels: waiting for reporter feedback
