### ISSUE TITLE
Entity not found when attepting to initialize FirefoxDriver

### ISSUE THREAD

**Issue by Zamolxe00** [mozilla/geckodriver#91] opened 2016-06-15 09:13 UTC
Details:
Window 10
VS 2015
geckodriver-v0.8.0-win32

I am attempting to run a simple selenium test, the wires exe starts and then I get entity not found error
Am using it in a browser factory.

Tried to use it with autofac config but was unable to initialize Marionette from there. Any help would be much appreciated.
Autofac sample:   

```
   <component name="Firefox" type="OpenQA.Selenium.Firefox.FirefoxDriver, WebDriver" service="OpenQA.Selenium.IWebDriver, WebDriver" instance-scope="per-dependency">
        <parameters>
          <parameter name="FirefoxOptions" value="new FirefoxOptions()" />
        </parameters>
      </component>
```

```
Stack:
   at OpenQA.Selenium.Remote.RemoteWebDriver.UnpackAndThrowOnError(Response errorResponse)
   at OpenQA.Selenium.Remote.RemoteWebDriver.Execute(String driverCommandToExecute, Dictionary`2 parameters)
   at OpenQA.Selenium.Remote.RemoteWebDriver.StartSession(ICapabilities desiredCapabilities)
   at OpenQA.Selenium.Remote.RemoteWebDriver..ctor(ICommandExecutor commandExecutor, ICapabilities desiredCapabilities)
   at OpenQA.Selenium.Firefox.FirefoxDriver..ctor(FirefoxOptions options)
   at PD_Selenium_Specflow.Helpers.WrapperFactory.BrowserFactory.InitBrowser(String browserName) in F:\repairinformation\Viewer\AutomationSelenium\ProdemandDesktop\PD_Selenium_Specflow\Helpers\WrapperFactory\BrowserFactory.cs:line 38
   at PD_Selenium_Specflow.Steps.LoginSteps.GivenIHaveLaunchedTheApplication() in F:\repairinformation\Viewer\AutomationSelenium\ProdemandDesktop\PD_Selenium_Specflow\Steps\LoginSteps.cs:line 49
   at lambda_method(Closure , IContextManager )
```

**Comment by foneox** [comment] 2016-06-15 09:24
I'm having the same issue

Firefox 47.0 , Win 10, VS 2015, geckodriver-v0.8.0-win32

I simply try to get new instance of FirefoxDriver: 
```
FirefoxOptions options = new FirefoxOptions{IsMarionette = true};
IWebDriver driver =  new FirefoxDriver(options);
```

```
System.InvalidOperationException was unhandled by user code
  HResult=-2146233079
  Message=entity not found
  Source=WebDriver
  StackTrace:
       at OpenQA.Selenium.Remote.RemoteWebDriver.UnpackAndThrowOnError(Response errorResponse)
       at OpenQA.Selenium.Remote.RemoteWebDriver.Execute(String driverCommandToExecute, Dictionary`2 parameters)
       at OpenQA.Selenium.Remote.RemoteWebDriver.StartSession(ICapabilities desiredCapabilities)
       at OpenQA.Selenium.Remote.RemoteWebDriver..ctor(ICommandExecutor commandExecutor, ICapabilities desiredCapabilities)
       at OpenQA.Selenium.Firefox.FirefoxDriver..ctor(FirefoxOptions options)
```

**Comment by andreastt** [comment] 2016-06-15 09:29
I think this is a duplicate of #61.

**Comment by foneox** [comment] 2016-06-15 09:44
This magic has fixed the issue somehow:
```
FirefoxDriverService service = FirefoxDriverService.CreateDefaultService();
service.FirefoxBinaryPath = @"C:\Program Files (x86)\Mozilla Firefox\firefox.exe";
IWebDriver driver = new FirefoxDriver(service);
```

**Comment by Zamolxe00** [comment] 2016-06-15 11:03
Thanks, that fixed my issue, would of liked it to work as documented :). Appreciate the help.

Cheers,
Dan

**Comment by andreastt** [comment] 2016-06-15 12:32
@foneox @Zamolxe00 I think the issu

**Comment by Zamolxe00** [comment] 2016-06-15 12:39
Odd thing is I used` var driver = new FirefoxDriver(new FirefoxOptions());` for driver initialization. I would not expect dealing with RemotewebDriver in this case.

**Comment by ianceicys** [comment] 2016-06-16 20:47
I found this issue and I used the suggested workaround. 
` //Create the reference for our browser
            FirefoxDriverService service = FirefoxDriverService.CreateDefaultService();
            service.FirefoxBinaryPath = @"C:\Program Files (x86)\Mozilla Firefox\firefox.exe";
            IWebDriver driver = new FirefoxDriver(service);`

I am seeing an issue where driver.Close(); does not close the firefox browser. 

Here is a 2min video with the repo steps:
https://www.youtube.com/watch?v=punDJFEmazY

Here is my Git repo with the sample test that exhibits the issue. 
https://github.com/ianceicys/SeleniumTests

How can I get the driver.close to work with FireFox 47.

**Comment by foneox** [comment] 2016-06-17 08:06
@ianceicys I was able to replicate your issue. But looks like it is not related to the described above. Can you please create it in the separate thread?

**Closed** 2017-01-04 01:43 UTC
Labels: selenium

**Comment by rravichandar** [comment] 2017-07-14 15:17
Hi, 

I am still having this issue when using 
 FirefoxDriverService service = FirefoxDriverService.CreateDefaultService();
                        service.FirefoxBinaryPath = @"C:\Program Files\Mozilla Firefox\firefox.exe";
                       driver = new FirefoxDriver(service);

The error I receive is
OpenQA.Selenium.WebDriverException: The HTTP request to the remote WebDriver server for URL http://localhost:52220/session timed out after 60 seconds. ---> System.Net.WebException: Die Anfrage wurde abgebrochen: Timeout für Vorgang überschritten.
   bei System.Net.HttpWebRequest.GetResponse()
   bei OpenQA.Selenium.Remote.HttpCommandExecutor.CreateResponse(WebRequest request)
   --- Ende der internen Ausnahmestapelüberwachung ---
   bei OpenQA.Selenium.Remote.HttpCommandExecutor.CreateResponse(WebRequest request)
   bei OpenQA.Selenium.Remote.HttpCommandExecutor.Execute(Command commandToExecute)
   bei OpenQA.Selenium.Remote.DriverServiceCommandExecutor.Execute(Command commandToExecute)
   bei OpenQA.Selenium.Remote.RemoteWebDriver.Execute(String driverCommandToExecute, Dictionary`2 parameters)
   bei OpenQA.Selenium.Remote.RemoteWebDriver.StartSession(ICapabilities desiredCapabilities)
   bei OpenQA.Selenium.Remote.RemoteWebDriver..ctor(ICommandExecutor commandExecutor, ICapabilities desiredCapabilities)
   bei OpenQA.Selenium.Firefox.FirefoxDriver..ctor(FirefoxDriverService service).

The error appears when using Firefox with IIS.
Versions IIS: 10.0.15063.0
firefox:  55.0b9 (64-Bit)
firefox driver:  Selenium.Firefox.WebDriver.0.18.0 (Installed from Nuget package manager)

**Comment by andreastt** [comment] 2017-07-17 19:25
@rravichandar It’s not really possible to say way the HTTP request from Selenium times out. You should at least look at the trace-level geckodriver log to see if that reveals anything.

**Comment by rravichandar** [comment] 2017-07-18 13:25
Hi @andreastt ,

Could you please tell me how can I get the trace-level geckodriver log? As I am running from IIS, the geckodriver and firefox runs in background and I just get this exception returned. Thanks!

**Comment by andreastt** [comment] 2017-07-18 15:09
@rravichandar You need to set a capability `{"moz:firefoxOptions": {"log": {"level": "trace"}}}` or append `-vv` to the geckodriver command line. This is also documented in the README.

**Comment by andreastt** [comment] 2017-07-18 15:10
Also I need to add, you should really file a new issue instead of resurrecting a closed issue.

**Comment by rravichandar** [comment] 2017-07-19 15:33
I created the new issue here:
https://github.com/mozilla/geckodriver/issues/830
