### ISSUE TITLE
Permission denied to access property "apply" - when executing javascript in Angular2 based page

### ISSUE THREAD

**Issue by hzieechenwei** [mozilla/geckodriver#446] opened 2017-01-26 02:20 UTC
Hi all,

## Steps to reproduce -
1. Download the QuickStart seed from angular websit.    https://github.com/angular/quickstart/archive/master.zip

2. Follow instruction to start example site on your machine. https://angular.io/docs/ts/latest/guide/setup.html#!#download
Node.js is required.

3. Write code to open "Hello World" page with selenium then execute js.
`            var driver = new FirefoxDriver(new FirefoxOptions { UseLegacyImplementation = false });
            driver.Url = "http://localhost:3000/";
            driver.ExecuteScript("return document.readyState;");`

Error message return from geckodriver: Permission denied to access property "invoke".

And it works fine with IE driver and Chrome driver.

**Comment by andreastt** [comment] 2017-01-26 15:34
This might be a duplicate of https://github.com/mozilla/geckodriver/issues/389. Unfortunately I don’t have Node.js nor the desire to start HTTPDs to reproduce an issue.

**Closed by andreastt** 2017-01-26 15:34 UTC

**Comment by SumithraMetro** [comment] 2017-04-11 12:16
Hi,

I just want to add gecko driver in my coding for browser stack. how to add them under capability.? Can anyone help me.
