### ISSUE TITLE
TimedPromise timed out after 500ms

### ISSUE THREAD

**Issue by aharui** [mozilla/geckodriver#1608] opened 2019-08-28 00:12 UTC
## System

* Version: 0.24.0
* Platform: macOS
* Firefox: 68.0.2 (64-bit)
* Selenium: 3.141.59

## Testcase

See attached.
[marionette.zip](https://github.com/mozilla/geckodriver/files/3548547/marionette.zip)

I've tried to reduce this test case, but cannot figure out how.  I can force the timeout by running lots of script code, but the script in reduced test cases always completes where in this larger test case the click does not seem to run script code.

Unzip and run (with Java)
```
java -Dwebdriver.gecko.driver=<path to>geckodriver -classpath .:<path to>selenium/client-combined-3.141.59.jar:<path to>selenium/libs/byte-buddy-1.8.15.jar:<path to>selenium/libs/commons-exec-1.3.jar:<path to>selenium/libs/guava-25.0-jre.jar:<path to>selenium/libs/okhttp-3.11.0.jar:<path to>selenium/libs/okio-1.14.0.jar TimedPromiseBugMustella file:///<path to this folder>/mustella/index.html 
```
## Stacktrace

```	
    TimedPromise timed out after 500 ms: stacktrace:
bail@chrome://marionette/content/sync.js:223:64
```

## Trace-level log

See attached.
[TraceLevelLog.txt](https://github.com/mozilla/geckodriver/files/3548545/TraceLevelLog.txt)

I wasn't sure whether to re-open #1584 or not.

**Comment by whimboo** [comment] 2019-08-28 08:52
This warning actually comes from [flushing the event loop](https://searchfox.org/mozilla-release/rev/23e7dc8dbb6044e9077d224138a09a88f3e6c47f/testing/marionette/interaction.js#412).

If that really hides that an element hasn't been clicked, we should allow the promise to raise a timeout error. With that in-place we might get more reports of broken behavior, but at least could see where fixes would be necessary. @andreastt what do you think?

Note that I cannot run the test given that the example HTML file doesn't show any content. So maybe it was wrongly saved.

**Comment by andreastt** [comment] 2019-09-02 11:05
The problem is that I don’t know under what circumstances `window.setTimeout(…, 0)` would _not_ fire, possibly we are missing a state check for something:

```js
  let spinEventLoop = resolve => {
    unloadEv = resolve;
    clickEv = () => {
      if (win.closed) {
        resolve();
      } else {
        win.setTimeout(resolve, 0);
      }
    };

    win.addEventListener("unload", unloadEv, { mozSystemGroup: true });
    el.addEventListener("click", clickEv, { mozSystemGroup: true });
  };
```

(Above code from https://searchfox.org/mozilla-central/rev/9415ecf29ba1acbef9381335e0ecde5916ca4073/testing/marionette/interaction.js#406-418.)

We know there are a number of users affected by this problem, so making it throw will cause test cases that are currently working to start erroring, so I’m not sure that making it throw will improve the situation since we are none the wiser as to _why_ this is happening.

A reproducible test case with some added logging to `spinEventLoop` might be a better approach however.

**Comment by aharui** [comment] 2019-09-04 06:00
Let me know if you need help getting my test case to run.  If I understand the responses so far, the issue may not be the way the timeout is set to fire, but rather, the timeout is an indication that in some cases, calling RemoteWebElement.click() does not actually dispatch a 'click' event that the JavaScript code sees.  So if you can get my test case to run in your debuggers, the thing to debug is the code paths for how RemoteWebElement.click() ends up dispatching a 'click' event in the browser

**Comment by whimboo** [comment] 2020-01-03 08:07
@aharui would you mind running your tests again with a recent [Firefox Nightly build](https://www.mozilla.org/en-US/firefox/channel/desktop/#nightly)? It provides more information about the stack now, which will help us to find the code using the `TimedPromise`. Thanks.

**Comment by PiotrZgadzaj** [comment] 2020-04-02 20:00
We have same problem with our test suite since upgrading Firefox to 65/66. Sometimes interactions with the page does not impact what is displayed in the browser. In case of such problems, i'm sure that browser send the request to the server, because i see it in the logs, also the response is correct, however because of some reason, browser does not render the response and logs following messages:

1585665376991	Marionette	WARN	TimedPromise timed out after 500 ms: stacktrace:
bail@chrome://marionette/content/sync.js:224:64

Do you know if newer FF are also affected by that? for example 70 or 71?

**Comment by mirao** [comment] 2020-04-07 11:20
> Do you know if newer FF are also affected by that? for example 70 or 71?

@PiotrZgadzaj Yes I can see it with FF 74, geckodriver 0.26, Selenium 3.141.59 on Ubuntu 18.04:
```
1586257529499	Marionette	WARN	TimedPromise timed out after 10 ms: stacktrace:
TimedPromise/<@chrome://marionette/content/sync.js:244:13
TimedPromise@chrome://marionette/content/sync.js:229:10
Sleep@chrome://marionette/content/sync.js:282:10
dispatchPause@chrome://marionette/content/action.js:1482:10
toEvents/<@chrome://marionette/content/action.js:1156:16
action.dispatchTickActions@chrome://marionette/content/action.js:1060:35
action.dispatch/chainEvents<@chrome://marionette/content/action.js:1028:20
1586257560558	Marionette	WARN	TimedPromise timed out after 500 ms: stacktrace:
TimedPromise/<@chrome://marionette/content/sync.js:244:13
TimedPromise@chrome://marionette/content/sync.js:229:10
interaction.flushEventLoop@chrome://marionette/content/interaction.js:416:10
webdriverClickElement@chrome://marionette/content/interaction.js:182:31
```

**Comment by PiotrZgadzaj** [comment] 2020-04-07 18:30
I will try with newest nightly Build which is available. For me, problem started showing up after upgrade from FF64 to FF65. It occurs in scenario where ajax request returns new iframe for the page. Browser simply do not update the DOM. In our tests, we run multiple tests one after another, on same browser instance. When the problem occurs, it keeps occuring for few tests in a row and then  suddenly browser/marionette recovers itself and everything is fine again

**Comment by whimboo** [comment] 2020-04-08 07:49
@mirao your reported warning is not relevant and expected to happen. The call to Sleep as it is done in your case shouldn't show the warning and stack at all. There is https://bugzilla.mozilla.org/show_bug.cgi?id=1606637 to get this fixed.

@PiotrZgadzaj if you are still able to reproduce please send the stack for the TimedPromise. Thanks.

**Comment by sharadsamant12** [comment] 2020-06-08 12:08
Geeting an issue after updating firefox 77.0.1 (64-bit)
verifypageTitle (firefox) org.openqa.selenium.WebDriverException: Failed to convert data to an object
Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:25:48'
System info: host: 'DESKTOP-AJ6U95Q', ip: '192.168.0.106', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '13.0.1'
Driver info: org.openqa.selenium.firefox.FirefoxDriver
Capabilities {acceptInsecureCerts: true, browserName: firefox, browserVersion: 77.0.1, javascriptEnabled: true, moz:accessibilityChecks: false, moz:buildID: 20200602222727, moz:geckodriverVersion: 0.26.0, moz:headless: false, moz:processID: 652, moz:profile: C:\Users\sharad\AppData\Loc..., moz:shutdownTimeout: 60000, moz:useNonSpecCompliantPointerOrigin: false, moz:webdriverClick: true, pageLoadStrategy: normal, platform: WINDOWS, platformName: WINDOWS, platformVersion: 10.0, rotatable: false, setWindowRect: true, strictFileInteractability: false, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}, unhandledPromptBehavior: dismiss and notify}
Session ID: 556d8d4c-0704-4c43-8b64-21f13815f288
*** Element info: {Using=tag name, value=textarea}
	at org.openqa.selenium.remote.http.W3CHttpResponseCodec.createException(W3CHttpResponseCodec.java:187)
	at org.openqa.selenium.remote.http.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:122)
	at org.openqa.selenium.remote.http.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:49)
	at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:158)
	at org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:83)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:552)
	at org.openqa.selenium.remote.RemoteWebDriver.findElement(RemoteWebDriver.java:323)
	at org.openqa.selenium.remote.RemoteWebDriver.findElementByTagName(RemoteWebDriver.java:396)
	at org.openqa.selenium.By$ByTagName.findElement(By.java:320)
	at org.openqa.selenium.remote.RemoteWebDriver.findElement(RemoteWebDriver.java:315)
	at crossBrowsers.VerifyTitle.verifypageTitle(VerifyTitle.java:136)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1507)
... Removed 32 stack frames

**Comment by DudaGod** [comment] 2020-07-15 10:39
Hello guys.

I have the same problem in firefox@67 and I created a repository with a reproducible bug in the test - https://github.com/DudaGod/firefox-timed-promise-bug. Can you look at it?

Thank you.

**Comment by DudaGod** [comment] 2020-07-17 09:18
Can you explain why is my comment is marked as off-topic?

**Comment by whimboo** [comment] 2020-07-21 11:02
There is no need for "me too" comments. As I have layed out above in my last comment the issue is known, and as long as this referenced bug hasn't been fixed you won't see a change in behavior. Also there is no better solution than `off-topic` available when hiding such comments.

**Comment by sfilimonau** [comment] 2020-08-27 20:43
Having similar timed out logs. Can only assume this to be the reason for my issue which can be checked at amazon site. After entering value in the search field expect drop down with search results to remain open. But it always closes.

The issue was replicating in about 50% of runs when was trying to run the code with trace logs recording. 

System
Version: geckodriver v0.27.0
Platform: Windows 10
Firefox: Firefox Browser 80.0 (64-bit)
Selenium-java: 3.141.59

Test case code.


```
System.setProperty("webdriver.gecko.driver", "....geckodriver.exe");
		WebDriver driver = new FirefoxDriver();
		driver.manage().window().maximize();
		driver.get("https://www.amazon.com/");
		Actions a = new Actions(driver);
		WebElement move = driver.findElement(By.xpath("//a[contains(@id,'nav-link-accountList')]"));
		a.moveToElement(driver.findElement(By.xpath("//*[@id='twotabsearchtextbox']"))).click().keyDown(Keys.SHIFT).sendKeys("hello").build().perform();
```

[FFlogs.txt](https://github.com/mozilla/geckodriver/files/5138707/FFlogs.txt)

**Comment by whimboo** [comment] 2020-09-09 19:36
This issue is fixed now and will no longer occur with the next Firefox Nightly build. I also requested an uplift for Firefox 81 beta.

**Closed by whimboo** 2020-09-09 19:36 UTC
Labels: awaiting reporter feedback
