### ISSUE TITLE
ActionChains: move_to_element.perform() followed by click(on_element=elem).perform() does not work because dropdown disappears

### ISSUE THREAD

**Issue by PDKCbus** [mozilla/geckodriver#1522] opened 2019-03-14 14:47 UTC
## System

https://github.com/SeleniumHQ/docker-selenium/releases/tag/3.141.59-krypton

Selenium: 3.141.59
Mozilla Firefox: 65.0.2
GeckoDriver: 0.24.0

## Testcase

Steps: 
1) navigate to a page that has a link in a dropdown that isn't visible until the parent object is hovered over. 
2) declare element --> `driver.find_element_by whatever`
2)` hover = ActionChains(self.driver)`
3) `hover.move_to_element(element).perform()` <-- parent dropdown now visible, showing target link
4) declare target element --> `driver.find_element_by whatever`
5) `hover.move_to_element(target_element).perform()`
**DROPDOWN MENU DISAPPEARS**, next attempted click will get return `rect is undefined` error

## Stacktrace

`{WebDriverException}Message: TypeError: rect is undefined`

**Comment by whimboo** [comment] 2019-03-14 14:52
Dupe of #1269.

**Closed by whimboo** 2019-03-14 14:52 UTC
