### ISSUE TITLE
open https web failed by "Your connection is not secure"

### ISSUE THREAD

**Issue by tonynii** [mozilla/geckodriver#428] opened 2017-01-11 05:47 UTC
In order to help us efficiently investigate your issue, please provide the following information:

## Firefox Version
48.0

## Platform
Windows
python 3.5
selenium 3.0.2
geckodriver 0.13

## Steps to reproduce -
1. open https://routerlogin.com (this is local https)
2. have below error info, browser page show "Your connection is not secure"

    open browser: https://www.routerlogin.com 
    13:39:27.063 FAIL WebDriverException: Message: Error loading page
     13:39:27.063 DEBUG Traceback (most recent call last):

  File "C:\Users\****\AppData\Local\Programs\Python\Python35\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 248, in get
    self.execute(Command.GET, {'url': url})
  File "C:\Users\****\AppData\Local\Programs\Python\Python35\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 236, in execute
    self.error_handler.check_response(response)
  File "C:\Users\****\AppData\Local\Programs\Python\Python35\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 192, in check_response
    raise exception_class(message, screen, stacktrace)

**Comment by andreastt** [comment] 2017-01-11 12:47
Duplicate of https://github.com/mozilla/geckodriver/issues/93.

**Closed by andreastt** 2017-01-11 12:47 UTC
