### ISSUE TITLE
org.openqa.selenium.WebDriverException: permission denied while creating a RemoteWebDriver

### ISSUE THREAD

**Issue by stephenle13** [mozilla/geckodriver#1473] opened 2019-01-12 10:52 UTC
* Version: 0.23.0 - win 32
* Platform: Windows
* Firefox: 60.2.2esr (32-bit)
* Selenium: 3.14.0

## Testcase
Hello Expert team,

I have an issue when migrating firefox ESR version 52 to 60.
- Before migration, I used geckodriver 0.16.1 and set capability marionette is false.
`DesiredCapabilities capabilities =
				new DesiredCapabilities(DesiredCapabilities.firefox().getBrowserName(), "ESR", Platform.ANY);
		capabilities.setCapability("marionette", false);
		capabilities.setCapability(CapabilityType.UNEXPECTED_ALERT_BEHAVIOUR, UnexpectedAlertBehaviour.ACCEPT);
		capabilities.setCapability(CapabilityType.HAS_NATIVE_EVENTS, false);
		capabilities.setCapability(CapabilityType.LOGGING_PREFS, Configuration.getLoginPreferences());
		capabilities.setCapability(FirefoxDriver.BINARY, Configuration.getESRBinPath());
		capabilities.setCapability(FirefoxDriver.PROFILE, getProfile());
        driver = new RemoteWebDriver(new URL("http://localhost:4444/wd/hub"), capabilities);`

and ESR 52 was started ok and navigated to expected URL that I want to test without an error.

- After upgraded to ESR 60, I used geckodriver 0.23.0 and set capability marionette is true. Browser started ok, but it directly opens profile path instead of my testing url.

![image](https://user-images.githubusercontent.com/46622594/51072158-b89d6280-168e-11e9-91a0-49ac1b0fbf6a.png)

As I read in geckodriver release page, it mentioned that "geckodriver now recommends Firefox 53 and greater" since 0.18.0. So upgrading from ESR 52 to 60 is a huge change, could you please help and let me know how can I adapt it? I guess I missed something in node config.json file :(

## My node config.json
{
  "capabilities":
  [
    {
      "browserName": "firefox",
      "maxInstances": 5,
      "seleniumProtocol": "WebDriver",
      "firefox_binary": "C:\\Program Files (x86)\\Mozilla Firefox\\firefox.exe"
    },
    {
      "browserName": "firefox",
      "version": "ESR",
      "maxInstances": 1,
      "seleniumProtocol": "WebDriver",
      "firefox_binary": "C:\\Program Files (x86)\\secutix\\Whymper_V3\\Whymper_V3.exe",
	  "marionette": true,
	  "alwaysMatch": {
		"moz:firefoxOptions": {
			"log": {
			"level": "trace"
			}
		}
	   }
    },
    {
      "browserName": "chrome",
      "maxInstances": 5,
      "seleniumProtocol": "WebDriver"
    },
    {
      "browserName": "internet explorer",
      "maxInstances": 1,
      "seleniumProtocol": "WebDriver"
    }
  ],
  "proxy": "org.openqa.grid.selenium.proxy.DefaultRemoteProxy",
  "maxSession": 5,
  "port": 5555,
  "register": true,
  "registerCycle": 5000,
  "hub": "http://localhost:4444",
  "nodeStatusCheckTimeout": 5000,
  "nodePolling": 5000,
  "role": "node",
  "unregisterIfStillDownAfter": 60000,
  "downPollingLimit": 2,
  "debug": false,
  "servlets" : [],
  "withoutServlets": [],
  "custom": {}
}

## Stacktrace

This is stacktrace on my local  
org.openqa.selenium.WebDriverException: permission denied
Build info: version: '3.14.0', revision: 'aacccce0', time: '2018-08-02T20:13:22.693Z'
System info: host: 'PC18799', ip: '192.168.230.105', os.name: 'Windows 10', os.arch: 'x86', os.version: '10.0', java.version: '1.8.0_121'
Driver info: driver.version: unknown
remote stacktrace: 
Command duration or timeout: 3.04 seconds
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
	at java.lang.reflect.Constructor.newInstance(Unknown Source)
	at org.openqa.selenium.remote.ErrorHandler.createThrowable(ErrorHandler.java:214)
	at org.openqa.selenium.remote.ErrorHandler.throwIfResponseFailed(ErrorHandler.java:166)
	at org.openqa.selenium.remote.JsonWireProtocolResponse.lambda$new$0(JsonWireProtocolResponse.java:53)
	at org.openqa.selenium.remote.JsonWireProtocolResponse.lambda$getResponseFunction$2(JsonWireProtocolResponse.java:91)
	at org.openqa.selenium.remote.ProtocolHandshake.lambda$createSession$0(ProtocolHandshake.java:123)
	at java.util.stream.ReferencePipeline$3$1.accept(Unknown Source)
	at java.util.Spliterators$ArraySpliterator.tryAdvance(Unknown Source)
	at java.util.stream.ReferencePipeline.forEachWithCancel(Unknown Source)
	at java.util.stream.AbstractPipeline.copyIntoWithCancel(Unknown Source)
	at java.util.stream.AbstractPipeline.copyInto(Unknown Source)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source)
	at java.util.stream.FindOps$FindOp.evaluateSequential(Unknown Source)
	at java.util.stream.AbstractPipeline.evaluate(Unknown Source)
	at java.util.stream.ReferencePipeline.findFirst(Unknown Source)
	at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:126)
	at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:73)
	at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:136)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:545)
	at org.openqa.selenium.remote.RemoteWebDriver.startSession(RemoteWebDriver.java:209)
	at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:132)
	at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:145)
	at com.secutix.SeleniumGrid.setUp(SeleniumGrid.java:47)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:24)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:86)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:459)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:675)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:382)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:192)

## Trace-level log

17:43:05.360 INFO [GridLauncherV3.launch] - Selenium build info: version: '3.14.0', revision: 'aacccce0'
17:43:05.368 INFO [GridLauncherV3$3.launch] - Launching a Selenium Grid node on port 5555
2019-01-12 17:43:05.468:INFO::main: Logging initialized @314ms to org.seleniumhq.jetty9.util.log.StdErrLog
17:43:05.564 INFO [SeleniumServer.boot] - Selenium Server is up and running on port 5555
17:43:05.565 INFO [GridLauncherV3$3.launch] - Selenium Grid node is up and ready to register to the hub
17:43:05.610 INFO [SelfRegisteringRemote$1.run] - Starting auto registration thread. Will try to register every 5000 ms.
17:43:05.612 INFO [SelfRegisteringRemote.registerToHub] - Registering the node to the hub: http://localhost:4444/grid/register
17:43:05.825 INFO [SelfRegisteringRemote.registerToHub] - The node is registered to the hub and ready to use
17:43:12.753 INFO [ActiveSessionFactory.apply] - Capabilities are: {
  "browserName": "firefox",
  "firefox_binary": "C:\\Program Files (x86)\\secutix\\Whymper_V3\\Whymper_V3.exe",
  "firefox_profile": "UEsDBBQACAgIAGaNLE4AAAAAAAAAAAAAAAAHAAAAdXNlci5qc+VXTW\u002fjNhC991csfGqBFWsn3QLdntxNFigQNMW6wV4MEBQ1shhTJMuhLPvfd6iPOIllycm1J8sUv2bmvTdPFYLnzkP+4yz1tqZ\u002fDEUOzbMyG1YKXQsPDIxINWSzjx9yoRF++v2H6rgyE4HmOOtDXFKA0KFo\u002fzOatFNyYn1\u002fcgHagV86hywee8AlblluvYSL1xnY0RMtQ7GDf+yNwi2tnQnntJIiKGt+3pmMlZjAXoL++OH5mxIHBvfJ2eGhPfbDg5lFXiIfeqfx5UC8n3Vg9qWm2EsRMLF5TknMrKxKMJRUCl9kWACEUrPmd\u002fYyMwZCbf2WFSE45gqFxSGJr51ATDSYTSgoLVefPg0nNG5PPxkEkAGyr8pjWFJ1pY6VCL56DQBbElL2XBbelsBReuUC95XhQZVxyfV8+KAgUmQEMHNvvmiLE3XObG20FVQ+YcQmQrWw9fcCzIrwF7E3vNzRpVzAeBgvbSb0BJphF6zVyMB7wp41aPVzAJ+Gj2pjrKGslVCm4FfNXxyPBQGRqo3BErs8IFWW53RRLr3A4u14j4j5qpr6\u002fO\u002fQ3udFK9Mmgk4O4I3QEeRv1qo8wv1bZYaLUEOaeUVZ50JKIJhXhhCBRBMuwQccRMgTghU6LQ6Q3S7mq78sMSoW7JfhyTSU3ZvvyhDucTFnig6yD9\u002fumhKntgqfUy3MdnbKxTYgLrTmj20ZXEz28N32ThEMaS6rCxVAKwy0wb+V8ucYEumxVYF1KtOzkYKLHBlNgBZUGBKGcQpi5HPlWEFq4mhvXoOWUVkqH0s6O1P\u002fJ33IrSb9uqNITgEQoWEa6rHKERqAGapDfnigKW9ub5WL592OxgKy8iocCFYa6Ilh8EoGbr3aKMOdJSocxvluoCbtYl3wI6V\u002fcdF2ZxYHV1VaqkZv\u002fm4Glw1yL2vng9uMRvwkcV0VYwVp5pkWcCQthVk3YD8tGkkCzYNEtN5A25qnB55BLiodhjW5T7tE14Ft+LaneBiFZo99IgrJffAH1raXZv7V1NyLbNBJm5OxNcY+d2PNRIu8fbhbsmsmjgU+Tc2j2Im2RY92tddl7Mk4jsHeeUhBkrODJMJI6OQiH3iaLw+PjQMZvOAm35PmeJpwlbU2MbkknpZNMZLx2zwJPdN2w\u002frVeddj5ef1GumeRlXlek0zcL2mxgG53Sfd3ORqvvgtmS+SxVXcYnYWd6IK0anGu6wkUSHq9GLaMd0TaSYxnWort42mX4Q9BOFl0TFhCqYla\u002fnKsqp0o1gi3l7ErhcwtpR7r7LhhnIiq6\u002f19HoYly2nkl5QCNyhmrBq3dwzYtlZ31PP++v8DJ44mfBo947GgUS1arrPaOYiTIYv8YzRtu30jTX+03xp3etZ0961bN7ob0ZpNBsepecdPnypyf2QjScx1DCFHXJx5DdkAXJ704r4H+2bt\u002fsBJrJMxZjFRHd8yefu8RI6t1PH2Tz48fzej2bafhMHu2+P0Wb7jOpNOmP+yVmnSkdyGLUpgj5jL54t7U98Tz\u002fgPU\u002fpOyO0DWoWv4A8vMrR0WjGDybiHX32TDjNoyzpHCvXeq6jB\u002fwPUEsHCIR3MjKUBAAAvhAAAFBLAQIUABQACAgIAGaNLE6EdzIylAQAAL4QAAAHAAAAAAAAAAAAAAAAAAAAAAB1c2VyLmpzUEsFBgAAAAABAAEANQAAAMkEAAAAAA==",
  "loggingPrefs": {
    "browser": "WARNING",
    "driver": "WARNING",
    "server": "WARNING"
  },
  "marionette": true,
  "nativeEvents": false,
  "unexpectedAlertBehaviour": "accept",
  "unhandledPromptBehavior": "accept",
  "version": "ESR"
}
17:43:12.780 INFO [ActiveSessionFactory.lambda$apply$11] - Matched factory org.openqa.selenium.remote.server.ServicedSession$Factory (provider: org.openqa.selenium.firefox.GeckoDriverService)
1547289793371   mozrunner::runner       INFO    Running command: "C:\\Program Files (x86)\\secutix\\Whymper_V3\\Whymper_V3.exe" "-marionette" "-foreground" "-no-remote" "-profile" "C:\\Users\\pdl\\AppData\\Local\\Temp\\rust_mozprofile.Js6Dt7xsMdIJ"

**Comment by andreastt** [comment] 2019-01-13 12:45
There’s so much Selenium specific stuff in this setup that it’s hard to tell exactly what is the problem. Does this reproduce without going through RemoteWebDriver? I.e. what happens if you start a FirefoxDriver directly, without any special configuration?

I think we need to reduce the test case to find out what the problem is.

**Comment by whimboo** [comment] 2019-01-14 16:57
Why did you set the marionette flag to `false` when using geckodriver with Firefox 52? You shouldn't do that because it wouldn't use geckodriver but the old FirefoxDriver implementation.

So I would suggest to set this flag to `true`, and to make use of geckodriver in Firefox 52. I assume you will see similar problems then. Try to fix those before upgrading to Firefox 60 or a newer geckodriver release. Also you should bump geckodriver to version 0.17 which is the last release that supports Firefox 52 and has bug fixes and new features included.

**Comment by whimboo** [comment] 2019-01-30 09:09
@stephenle13 do you have any updates for us? How does it work with Marionette enabled? Thanks.

**Comment by whimboo** [comment] 2019-02-19 15:17
No further response from reporter. Closing the issue.

**Closed by whimboo** 2019-02-19 15:17 UTC
Labels: waiting for reporter feedback

**Comment by stephenle13** [comment] 2019-02-25 11:50
Hello,

Sorry for the delay.
I tested with gecko v0.17, ff esr 52 and it has the issue - firefox opens with a blank page, it doesn't redirect to test url.

**Here is my config:**
**hub:** java -jar selenium-server-standalone-3.14.0.jar -role hub
**node:** java -Dwebdriver.gecko.driver=C:\selenium\drivers\geckodriver_win32\geckodriver.exe -jar selenium-server-standalone-3.14.0.jar -role node -nodeConfig nodeConfig.json

**nodeConfig.js:**
{
  "capabilities":
  [
    {
      "browserName": "firefox",
      "maxInstances": 5,
      "seleniumProtocol": "WebDriver",
      "firefox_binary": "C:\\Program Files (x86)\\Mozilla Firefox\\firefox.exe"
    },
    {
      "browserName": "firefox",
      "version": "ESR",
      "maxInstances": 1,
      "seleniumProtocol": "WebDriver",
      "firefox_binary": "C:\\Program Files (x86)\\secutix\\Whymper_V2\\Whymper_V2.exe",
	  "marionette": true
    },
    {
      "browserName": "chrome",
      "maxInstances": 5,
      "seleniumProtocol": "WebDriver"
    },
    {
      "browserName": "internet explorer",
      "maxInstances": 1,
      "seleniumProtocol": "WebDriver"
    }
  ],
  "proxy": "org.openqa.grid.selenium.proxy.DefaultRemoteProxy",
  "maxSession": 5,
  "port": 5555,
  "register": true,
  "registerCycle": 5000,
  "hub": "http://localhost:4444",
  "nodeStatusCheckTimeout": 5000,
  "nodePolling": 5000,
  "role": "node",
  "unregisterIfStillDownAfter": 60000,
  "downPollingLimit": 2,
  "debug": false,
  "servlets" : [],
  "withoutServlets": [],
  "custom": {}
}

**My sample test:**
  
System.setProperty("webdriver.gecko.driver","C:\\selenium\\drivers\\geckodriver_win32\\geckodriver.exe");    	
    	final DesiredCapabilities capabilities =
				new DesiredCapabilities(DesiredCapabilities.firefox().getBrowserName(), "ESR", Platform.ANY);
		capabilities.setCapability("marionette", true);	
		capabilities.setCapability(FirefoxDriver.BINARY, Configuration.getESRBinPath());
         WebDriver driver;
         Wait<WebDriver> wait;
         driver = new RemoteWebDriver(new URL("http://localhost:4444/wd/hub"), capabilities);//true to enable the JS
         wait = new WebDriverWait(driver, 10);
         final String url = "https://www.google.com/";

         try {
             driver.navigate().to(url);
         } finally {
             driver.close();
         }
    	

![image](https://user-images.githubusercontent.com/46622594/53334951-c819f780-392c-11e9-93b0-1f34ace9701a.png)

**Comment by whimboo** [comment] 2019-02-26 15:44
Firefox doesn't show any indication of automation in the address bar (usually a robot and diagonal stripes). As such Marionette has not been enabled. You will have to check your Selenium client if it is correctly setting up the usage of geckodriver. Also a [trace log](https://firefox-source-docs.mozilla.org/testing/geckodriver/geckodriver/TraceLogs.html) would have been helpful.

**Comment by stephenle13** [comment] 2019-02-27 05:24
Hello @whimboo ,

Looks like a robot and diagonal stripes just appears with new firefox version (not in firefox 52.0). I tried with the latest firefox ESR version 60, the issue is gone, but had another issue with permission denied. :(

I see there is a difference betwen firefox ESR and firefox kit ESR which is provided by my current project.

Using gecko version 0.17, 0.21, 0.24, 
+ test with firefox ESR version 60.5.2esr (32-bit) -> it works
![image](https://user-images.githubusercontent.com/46622594/53467477-f4e32180-3a88-11e9-8089-5d56eedfe75d.png)

**trace log A:**
12:08:11.206 INFO [SelfRegisteringRemote.registerToHub] - The node is registered to the hub and ready to use
12:14:24.975 INFO [ActiveSessionFactory.apply] - Capabilities are: {
  "acceptInsecureCerts": true,
  "browserName": "firefox",
  "firefox_binary": "C:\\Program Files (x86)\\Mozilla Firefox\\firefox.exe",
  "marionette": true,
  "moz:firefoxOptions": {
    "binary": "C:\\Program Files (x86)\\Mozilla Firefox\\firefox.exe"
  },
  "version": ""
}
12:14:24.978 INFO [ActiveSessionFactory.lambda$apply$11] - Matched factory org.openqa.selenium.remote.server.ServicedSession$Factory (provider: org.openqa.selenium.firefox.GeckoDriverService)
1551244465520   mozrunner::runner       INFO    Running command: "C:\\Program Files (x86)\\Mozilla Firefox\\firefox.exe" "-marionette" "-foreground" "-no-remote" "-profile" "C:\\Users\\pdl\\AppData\\Local\\Temp\\rust_mozprofile.EIgsh8lalGs4"
1551244466889   Marionette      INFO    Listening on port 51978
1551244467139   Marionette      WARN    TLS certificate errors will be ignored for this session
12:14:27.182 INFO [ProtocolHandshake.createSession] - Detected dialect: W3C
12:14:27.196 INFO [RemoteSession$Factory.lambda$performHandshake$0] - Started new session 528601b0-589d-42c1-be3a-5e220b07e95e (org.openqa.selenium.firefox.GeckoDriverService)
[Child 18000, Chrome_ChildThread] WARNING: pipe error: 109: file z:/build/build/src/ipc/chromium/src/chrome/common/ipc_channel_win.cc, line 332
[Child 18000, Chrome_ChildThread] WARNING: pipe error: 109: file z:/build/build/src/ipc/chromium/src/chrome/common/ipc_channel_win.cc, line 332
*** UTM:SVC TimerManager:registerTimer called after profile-before-change notification. Ignoring timer registration for id: telemetry_modules_ping
[GPU 16660, Chrome_ChildThread] WARNING: pipe error: 109: file z:/build/build/src/ipc/chromium/src/chrome/common/ipc_channel_win.cc, line 332

###!!! [Child][MessageChannel::SendAndWait] Error: Channel error: cannot send/recv

12:14:35.295 INFO [ActiveSessions$1.onStop] - Removing session 528601b0-589d-42c1-be3a-5e220b07e95e (org.openqa.selenium.firefox.GeckoDriverService)


+ test with firefox kit ESR version 60.2.2esr (32-bit) -> it doesn't work, firefox opens but fails by permission denied error.

![image](https://user-images.githubusercontent.com/46622594/53467648-abdf9d00-3a89-11e9-8fcc-3550c518e225.png)

**trace log B** - there is no response from Marionette :(
12:17:22.764 INFO [ActiveSessionFactory.apply] - Capabilities are: {
  "browserName": "firefox",
  "firefox_binary": "C:\\Program Files (x86)\\secutix\\Whymper_V3\\Whymper_V3.exe",
  "marionette": true,
  "version": "ESR"
}
12:17:22.765 INFO [ActiveSessionFactory.lambda$apply$11] - Matched factory org.openqa.selenium.remote.server.ServicedSession$Factory (provider: org.openqa.selenium.firefox.GeckoDriverService)
1551244643285   mozrunner::runner       INFO    Running command: "C:\\Program Files (x86)\\secutix\\Whymper_V3\\Whymper_V3.exe" "-marionette" "-foreground" "-no-remote" "-profile" "C:\\Users\\pdl\\AppData\\Local\\Temp\\rust_mozprofile.qWrmBnwcrIsu"


In trace log A, when starting official firefox ESR, capability are:
![image](https://user-images.githubusercontent.com/46622594/53467773-30322000-3a8a-11e9-923d-4445d9c1eb9c.png)

but in trace log B, when starting firefox ESR kit, they are:
![image](https://user-images.githubusercontent.com/46622594/53467798-46d87700-3a8a-11e9-87ba-35f8bfe9a97e.png)

I don't know if it causes the problem.

**My selenium client code:**
 String driverPath = "C:\\selenium\\drivers\\geckodriver_win32\\geckodriver.exe";
public WebDriver driver;
System.out.println("******** " + driverPath);
System.setProperty("webdriver.gecko.driver", driverPath);

/*TEST WITH FIREFOX ESR VER 60.*/
//DesiredCapabilities capabilities =  DesiredCapabilities.firefox();
        
/*TEST WITH FIREFOX KIT ESR VER 60.*/
DesiredCapabilities capabilities =
				new DesiredCapabilities(DesiredCapabilities.firefox().getBrowserName(), "ESR", Platform.ANY);
capabilities.setCapability("marionette", true);
capabilities.setCapability(FirefoxDriver.BINARY, Configuration.getESRBinPath());

driver = new RemoteWebDriver(
new URL("http://localhost:4444/wd/hub"),
capabilities);

**Comment by whimboo** [comment] 2019-02-27 08:04
I don't know what Firefox KIT ESR is, but it's not something we ship. Is that some internal build or officially downloadable? If they are making changes, the problem would have to be solved with them.

**Comment by PavelGermanovich** [comment] 2019-03-12 12:51
having the common issue
