### ISSUE TITLE
Hang when navigation request removes the current browsing context

### ISSUE THREAD

**Issue by rshanley-micro-focus** [mozilla/geckodriver#918] opened 2017-09-01 09:55 UTC
## System
* Version: 0.18.0
* Platform: Windows 10
* Firefox: 55.0.2
* Selenium: Java binding, 3.5.2

### mainpage.html:

```
<html>
    <head></head>
    <body>
        <p>hello, welcome to this iframe test page</p>
        <iframe src="page1.html" height="200" width="300"></iframe>
    </body>
</html>
```

### page1.html

```
<html>
    <head></head>
    <body>
        <p>hello, welcome to page 1</p>
        <a href="page2.html">page two</a>
    </body>
</html>
```

### page2.html

```
<html>
    <head></head>
    <body>
        <p>hello, welcome to page 2</p>
        <a href="page1.html">page one</a>
    </body>
</html>
```

### TestIFrameAndBack.java

```
import org.openqa.selenium.WebDriver;
import org.junit.Before;
import org.openqa.selenium.firefox.FirefoxDriver;
import java.util.concurrent.TimeUnit;
import org.junit.Test;
import org.openqa.selenium.By;
import org.junit.After;

public class TestIFrameAndBack {

	private WebDriver driver;

	@Before
	public void setup() {
		//TODO: Replace property with path to your geckodriver.exe
		System.setProperty("webdriver.gecko.driver", "....");
		driver = new FirefoxDriver();
		driver.manage().timeouts().implicitlyWait(5, TimeUnit.SECONDS);
	}

	@Test
	public void myTestCaseName() {
		driver.get("http://localhost:8000/mainpage.html");
		driver.switchTo().frame(driver.findElement(By.xpath("//iframe[@src=\"page1.html\"]")));
		driver.findElement(By.linkText("page two")).click();
		driver.switchTo().parentFrame();

		driver.navigate().back();//webdriver hangs here!
	}

	@After
	public void tearDown() {
		if (driver != null) {
			driver.quit();
		}
	}

}
```

## Stacktrace

```
org.openqa.selenium.WebDriverException: Failed to decode response from marionette
Build info: version: '3.5.3', revision: 'a88d25fe6b', time: '2017-08-29T12:42:44.417Z'
System info: ..., os.name: 'Windows 10', os.arch: 'x86', os.version: '10.0', java.version: '1.8.0_144'
Driver info: org.openqa.selenium.firefox.FirefoxDriver
Capabilities [{..., rotatable=false, timeouts={implicit=0, pageLoad=300000, script=30000}, pageLoadStrategy=normal, platform=XP, specificationLevel=0, moz:accessibilityChecks=false, acceptInsecureCerts=false, browserVersion=55.0.2, platformVersion=10.0, moz:processID=4304, browserName=firefox, javascriptEnabled=true, platformName=XP}]
Session ID: a9639af0-5ef1-4584-b53c-4fbdc1df1f46
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
	at java.lang.reflect.Constructor.newInstance(Unknown Source)
	at org.openqa.selenium.remote.http.W3CHttpResponseCodec.createException(W3CHttpResponseCodec.java:185)
	at org.openqa.selenium.remote.http.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:120)
	at org.openqa.selenium.remote.http.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:49)
	at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:164)
	at org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:82)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:646)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:703)
	at org.openqa.selenium.remote.RemoteWebDriver$RemoteNavigation.back(RemoteWebDriver.java:946)
	at TestIFrameAndBack.myTestCaseName(TestIFrameAndBack.java:28)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:86)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:459)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:678)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:382)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:192)

org.openqa.selenium.SessionNotCreatedException: Tried to run command without establishing a connection
Build info: version: '3.5.3', revision: 'a88d25fe6b', time: '2017-08-29T12:42:44.417Z'
System info: ... os.name: 'Windows 10', os.arch: 'x86', os.version: '10.0', java.version: '1.8.0_144'
Driver info: org.openqa.selenium.firefox.FirefoxDriver
Capabilities [{..., rotatable=false, timeouts={implicit=0, pageLoad=300000, script=30000}, pageLoadStrategy=normal, platform=XP, specificationLevel=0, moz:accessibilityChecks=false, acceptInsecureCerts=false, browserVersion=55.0.2, platformVersion=10.0, moz:processID=4304, browserName=firefox, javascriptEnabled=true, platformName=XP}]
Session ID: a9639af0-5ef1-4584-b53c-4fbdc1df1f46
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
	at java.lang.reflect.Constructor.newInstance(Unknown Source)
	at org.openqa.selenium.remote.http.W3CHttpResponseCodec.createException(W3CHttpResponseCodec.java:185)
	at org.openqa.selenium.remote.http.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:120)
	at org.openqa.selenium.remote.http.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:49)
	at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:164)
	at org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:82)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:646)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:703)
	at org.openqa.selenium.remote.RemoteWebDriver.quit(RemoteWebDriver.java:542)
	at TestIFrameAndBack.tearDown(TestIFrameAndBack.java:34)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
```

## Trace-level log

```
1504260311969	geckodriver::marionette	DEBUG	Connected to Marionette on localhost:59329
1504260311973	Marionette	DEBUG	Accepted connection 0 from 127.0.0.1:59336
1504260311974	geckodriver::marionette	TRACE	<- {"applicationType":"gecko","marionetteProtocol":3}
1504260311974	geckodriver::marionette	TRACE	-> 62:[0,1,"newSession",{"capabilities":{"desiredCapabilities":{}}}]
1504260311977	Marionette	TRACE	0 -> [0,1,"newSession",{"capabilities":{"desiredCapabilities":{}}}]
1504260311983	Marionette	CONFIG	Matched capabilities: {"browserName":"firefox","browserVersion":"55.0.2","platformName":"windows_nt","platformVersion":"10.0","pageLoadStrategy":"normal","acceptInsecureCerts":false,"timeouts":{"implicit":0,"pageLoad":300000,"script":30000},"rotatable":false,"specificationLevel":0,"moz:processID":13340,"moz:profile":"C:\\Users\\RAYMON~1.COR\\AppData\\Local\\Temp\\rust_mozprofile.VGyLEyjxn41U","moz:accessibilityChecks":false}
1504260312033	Marionette	DEBUG	loaded listener.js
1504260312043	Marionette	TRACE	0 <- [1,1,null,{"sessionId":"16f33e3b-87f2-4db5-82e0-11544d25b13f","capabilities":{"browserName":"firefox","browserVersion":"55.0.2","platformName":"windows_nt","platformVersion":"10.0","pageLoadStrategy":"normal","acceptInsecureCerts":false,"timeouts":{"implicit":0,"pageLoad":300000,"script":30000},"rotatable":false,"specificationLevel":0,"moz:processID":13340,"moz:profile":"C:\\Users\\RAYMON~1.COR\\AppData\\Local\\Temp\\rust_mozprofile.VGyLEyjxn41U","moz:accessibilityChecks":false}}]
1504260312044	geckodriver::marionette	TRACE	<- [1,1,null,{"sessionId":"16f33e3b-87f2-4db5-82e0-11544d25b13f","capabilities":{"browserName":"firefox","browserVersion":"55.0.2","platformName":"windows_nt","platformVersion":"10.0","pageLoadStrategy":"normal","acceptInsecureCerts":false,"timeouts":{"implicit":0,"pageLoad":300000,"script":30000},"rotatable":false,"specificationLevel":0,"moz:processID":13340,"moz:profile":"C:\\Users\\RAYMON~1.COR\\AppData\\Local\\Temp\\rust_mozprofile.VGyLEyjxn41U","moz:accessibilityChecks":false}}]
1504260312045	webdriver::server	DEBUG	<- 200 OK {"value": {"sessionId":"16f33e3b-87f2-4db5-82e0-11544d25b13f","capabilities":{"acceptInsecureCerts":false,"browserName":"firefox","browserVersion":"55.0.2","moz:accessibilityChecks":false,"moz:processID":13340,"moz:profile":"C:\\Users\\RAYMON~1.COR\\AppData\\Local\\Temp\\rust_mozprofile.VGyLEyjxn41U","pageLoadStrategy":"normal","platformName":"windows_nt","platformVersion":"10.0","rotatable":false,"specificationLevel":0,"timeouts":{"implicit":0,"pageLoad":300000,"script":30000}}}}
Sep 01, 2017 12:05:12 PM org.openqa.selenium.remote.ProtocolHandshake createSession
INFO: Detected dialect: W3C
1504260312088	webdriver::server	DEBUG	-> POST /session/16f33e3b-87f2-4db5-82e0-11544d25b13f/timeouts {"implicit":5000}
1504260312089	geckodriver::marionette	TRACE	-> 37:[0,2,"setTimeouts",{"implicit":5000}]
1504260312091	Marionette	TRACE	0 -> [0,2,"setTimeouts",{"implicit":5000}]
1504260312092	Marionette	TRACE	0 <- [1,2,null,{}]
1504260312092	geckodriver::marionette	TRACE	<- [1,2,null,{}]
1504260312092	webdriver::server	DEBUG	<- 200 OK {"value": {}}
1504260312097	webdriver::server	DEBUG	-> POST /session/16f33e3b-87f2-4db5-82e0-11544d25b13f/url {"url":"http://localhost:8000/mainpage.html"}
1504260312097	geckodriver::marionette	TRACE	-> 57:[0,3,"get",{"url":"http://localhost:8000/mainpage.html"}]
1504260312099	Marionette	TRACE	0 -> [0,3,"get",{"url":"http://localhost:8000/mainpage.html"}]
1504260312101	Marionette	DEBUG	Received DOM event "beforeunload" for "about:blank"
1504260312363	Marionette	DEBUG	Received DOM event "pagehide" for "about:blank"
1504260312364	Marionette	DEBUG	Received DOM event "unload" for "about:blank"
1504260312368	Marionette	DEBUG	Received DOM event "DOMContentLoaded" for "http://localhost:8000/mainpage.html"
1504260312402	Marionette	DEBUG	Received DOM event "DOMContentLoaded" for "http://localhost:8000/page1.html"
1504260312405	Marionette	DEBUG	Received DOM event "pageshow" for "http://localhost:8000/page1.html"
1504260312406	Marionette	DEBUG	Received DOM event "pageshow" for "http://localhost:8000/mainpage.html"
1504260312407	Marionette	TRACE	0 <- [1,3,null,{}]
1504260312412	geckodriver::marionette	TRACE	<- [1,3,null,{}]
1504260312412	webdriver::server	DEBUG	<- 200 OK {"value": {}}
1504260312423	webdriver::server	DEBUG	-> POST /session/16f33e3b-87f2-4db5-82e0-11544d25b13f/element {"value":"//iframe[@src=\"page1.html\"]","using":"xpath"}
1504260312424	geckodriver::marionette	TRACE	-> 77:[0,4,"findElement",{"using":"xpath","value":"//iframe[@src=\"page1.html\"]"}]
1504260312425	Marionette	TRACE	0 -> [0,4,"findElement",{"using":"xpath","value":"//iframe[@src=\"page1.html\"]"}]
1504260312430	Marionette	TRACE	0 <- [1,4,null,{"value":{"element-6066-11e4-a52e-4f735466cecf":"731b2ca3-edab-4e91-b9ac-b1dabc5bcd5e","ELEMENT":"731b2ca3-edab-4e91-b9ac-b1dabc5bcd5e"}}]
1504260312432	geckodriver::marionette	TRACE	<- [1,4,null,{"value":{"element-6066-11e4-a52e-4f735466cecf":"731b2ca3-edab-4e91-b9ac-b1dabc5bcd5e","ELEMENT":"731b2ca3-edab-4e91-b9ac-b1dabc5bcd5e"}}]
1504260312432	webdriver::server	DEBUG	<- 200 OK {"value":{"element-6066-11e4-a52e-4f735466cecf":"731b2ca3-edab-4e91-b9ac-b1dabc5bcd5e"}}
1504260312436	webdriver::server	DEBUG	-> POST /session/16f33e3b-87f2-4db5-82e0-11544d25b13f/frame {"id":{"ELEMENT":"731b2ca3-edab-4e91-b9ac-b1dabc5bcd5e","element-6066-11e4-a52e-4f735466cecf":"731b2ca3-edab-4e91-b9ac-b1dabc5bcd5e"}}
1504260312437	geckodriver::marionette	TRACE	-> 72:[0,5,"switchToFrame",{"element":"731b2ca3-edab-4e91-b9ac-b1dabc5bcd5e"}]
1504260312439	Marionette	TRACE	0 -> [0,5,"switchToFrame",{"element":"731b2ca3-edab-4e91-b9ac-b1dabc5bcd5e"}]
1504260312477	Marionette	TRACE	0 <- [1,5,null,{}]
1504260312477	geckodriver::marionette	TRACE	<- [1,5,null,{}]
1504260312477	webdriver::server	DEBUG	<- 200 OK {"value": {}}
1504260312481	webdriver::server	DEBUG	-> POST /session/16f33e3b-87f2-4db5-82e0-11544d25b13f/element {"value":"page two","using":"link text"}
1504260312481	geckodriver::marionette	TRACE	-> 60:[0,6,"findElement",{"using":"link text","value":"page two"}]
1504260312483	Marionette	TRACE	0 -> [0,6,"findElement",{"using":"link text","value":"page two"}]
1504260312486	Marionette	TRACE	0 <- [1,6,null,{"value":{"element-6066-11e4-a52e-4f735466cecf":"ca5afd2a-e236-49c6-8221-e424d7fb2d16","ELEMENT":"ca5afd2a-e236-49c6-8221-e424d7fb2d16"}}]
1504260312486	geckodriver::marionette	TRACE	<- [1,6,null,{"value":{"element-6066-11e4-a52e-4f735466cecf":"ca5afd2a-e236-49c6-8221-e424d7fb2d16","ELEMENT":"ca5afd2a-e236-49c6-8221-e424d7fb2d16"}}]
1504260312486	webdriver::server	DEBUG	<- 200 OK {"value":{"element-6066-11e4-a52e-4f735466cecf":"ca5afd2a-e236-49c6-8221-e424d7fb2d16"}}
1504260312490	webdriver::server	DEBUG	-> POST /session/16f33e3b-87f2-4db5-82e0-11544d25b13f/element/ca5afd2a-e236-49c6-8221-e424d7fb2d16/click {"id":"ca5afd2a-e236-49c6-8221-e424d7fb2d16"}
1504260312491	geckodriver::marionette	TRACE	-> 66:[0,7,"clickElement",{"id":"ca5afd2a-e236-49c6-8221-e424d7fb2d16"}]
1504260312493	Marionette	TRACE	0 -> [0,7,"clickElement",{"id":"ca5afd2a-e236-49c6-8221-e424d7fb2d16"}]
1504260312513	Marionette	DEBUG	Received DOM event "beforeunload" for "http://localhost:8000/page1.html"
1504260312519	Marionette	DEBUG	Received DOM event "pagehide" for "http://localhost:8000/page1.html"
1504260312520	Marionette	DEBUG	Received DOM event "unload" for "http://localhost:8000/page1.html"
1504260312525	Marionette	DEBUG	Received DOM event "DOMContentLoaded" for "http://localhost:8000/page2.html"
1504260312528	Marionette	DEBUG	Received DOM event "pageshow" for "http://localhost:8000/page2.html"
1504260312529	Marionette	TRACE	0 <- [1,7,null,{}]
1504260312533	geckodriver::marionette	TRACE	<- [1,7,null,{}]
1504260312533	webdriver::server	DEBUG	<- 200 OK {"value": {}}
1504260312536	webdriver::server	DEBUG	-> POST /session/16f33e3b-87f2-4db5-82e0-11544d25b13f/frame/parent {}
1504260312536	geckodriver::marionette	TRACE	-> 30:[0,8,"switchToParentFrame",{}]
1504260312538	Marionette	TRACE	0 -> [0,8,"switchToParentFrame",{}]
1504260312539	Marionette	TRACE	0 <- [1,8,null,{}]
1504260312540	geckodriver::marionette	TRACE	<- [1,8,null,{}]
1504260312540	webdriver::server	DEBUG	<- 200 OK {"value": {}}
1504260312543	webdriver::server	DEBUG	-> POST /session/16f33e3b-87f2-4db5-82e0-11544d25b13f/back {}
1504260312543	geckodriver::marionette	TRACE	-> 17:[0,9,"goBack",{}]
1504260312545	Marionette	TRACE	0 -> [0,9,"goBack",{}]
1504260312552	Marionette	DEBUG	Received DOM event "pagehide" for "http://localhost:8000/page2.html"
```

**Comment by andreastt** [comment] 2017-09-01 20:11
Thanks for the detailed bug report. It is great that you included a trace-level log!

**Comment by whimboo** [comment] 2017-09-07 14:55
You cannot switch to the parent frame and then navigate backward. Reason is that you are in a different browsing context, and as such we cannot recognize any page load events.

So this is basically issue #874.

**Comment by codingphil** [comment] 2017-09-12 10:06
@whimboo I would not agree. According to the webdriver spec "Back" is independent of whether the current browsing context is the iframe or the root context.

https://www.w3.org/TR/webdriver/#back

> The Back command causes the browser to traverse one step backward in the joint session history of the current top-level browsing context. This is equivalent to pressing the back button in the browser chrome or calling window.history.back.

So I see no reason why "Back" cannot handle the navigation in the iframe (-> https://html.spec.whatwg.org/#joint-session-history)

**Comment by whimboo** [comment] 2017-09-14 20:06
The problem here is not initiating the `back` navigation, but to detect and monitor the page load. That is the reason why we do not return. 

But I just noticed that we had a change for the spec beginning of June via https://github.com/w3c/webdriver/pull/932, which says that we should return when the current browsing context is no longer available. I haven't had a look at that part of the spec for a long time.

So this should actually cover your case here, and we indeed have to update Marionette for this case.

**Comment by whimboo** [comment] 2017-09-14 20:12
To add, this can actually happen to any navigation request. I filed [bug 1400005](https://bugzilla.mozilla.org/show_bug.cgi?id=1400005) to get this fixed in Marionette.

**Comment by codingphil** [comment] 2017-09-15 07:07
After calling "Back" the iframe should contain the content of page 1, correct?

**Comment by whimboo** [comment] 2017-09-15 07:08
Yes, but the original browsing context (window, document) should be stale. I will create different testcases and check how we can solve that on the mentioned bug.

**Comment by whimboo** [comment] 2019-01-08 22:10
I revisited this issue and the problem is that calling `back` via the driver will cause a page navigation in the frame but not the top-browsing context. But given that the top-browsing context has been switched to with the command right before, the navigation cannot be seen.

In such a case the test should be responsible to switch to the correct frame again before calling `back`. If that is not done the navigation command will certainly end-up with a timeout error.

To fix the problem the code should look like that:

```
frame = driver.findElement(By.xpath("//iframe[@src=\"page1.html\"]"))
driver.switchTo().frame(frame);
driver.findElement(By.linkText("page two")).click();
driver.switchTo().parentFrame();
[..]
driver.switchTo().frame(frame);
driver.navigate().back();
```
That won't cause a page load timeout, but will return once the history navigation has been completed.

@andreastt, I assume we can close this issue?

**Comment by whimboo** [comment] 2021-02-22 08:04
This was fixed with my patch on https://bugzilla.mozilla.org/show_bug.cgi?id=1612831 for Firefox 82.

**Closed by whimboo** 2021-02-22 08:04 UTC
Labels: marionette
