### ISSUE TITLE
WebElement.sendKeys() does not trigger focus event on Mac

### ISSUE THREAD

**Issue by codingphil** [mozilla/geckodriver#1152] opened 2018-01-31 09:51 UTC
## System
* Version: 0.19.1
* Platform: MacOS High Sierra 10.13.2
* Firefox: 58.0.1 (64-bit)
* Selenium: 3.8.1 (Java)

## Testcase

The following JUnit test case **fails for Firefox on MacOS** because `WebElement.sendKeys()` does not trigger the focus event.
The test **succeeds** for Firefox 58 and Edge **on Windows** and also for **Chrome on MacOS**.
The test fails too with Firefox Nightly 60.0a1 (2018-01-30) (64-bit) on MacOS.

```java
  @Test
  public void testSendKeysSimpleLetterToTextFieldEvents() {
    webDriver.navigate().to("http://localhost/testEventOrder2.html");
    WebElement textField = webDriver.findElementById("testText");

    textField.sendKeys("a");

    List<Map> events = (List<Map>) webDriver.executeScript("return allEvents");

    Map focusEvent = events.get(0);
    assertEquals("focus", focusEvent.get("type")); // <<==== FAILS

    Map keyDownEvent = events.get(1);
    assertEquals("keydown", keyDownEvent.get("type"));
    assertEquals(65l, keyDownEvent.get("keyCode"));
    assertEquals(65l, keyDownEvent.get("which"));

    Map keyPressEvent = events.get(2);
    assertEquals("keypress", keyPressEvent.get("type"));
    assertEquals(65l, keyDownEvent.get("keyCode"));
    assertEquals(97l, keyPressEvent.get("which"));

    Map keyUpEvent = events.get(3);
    assertEquals("keyup", keyUpEvent.get("type"));
    assertEquals(65l, keyDownEvent.get("keyCode"));
    assertEquals(65l, keyUpEvent.get("which"));
  }
```
Used HTML page:
[testEventOrder2-html.zip](https://github.com/mozilla/geckodriver/files/1680870/testEventOrder2-html.zip)

## Stacktrace

```java
org.junit.ComparisonFailure: expected:<[focus]> but was:<[keydown]>
	at org.junit.Assert.assertEquals(Assert.java:115)
	at org.junit.Assert.assertEquals(Assert.java:144)
	at SendKeysTests.testSendKeysSimpleLetterToTextFieldEvents(SendKeysTests.java:485)
```

## Trace-level log

[testSendKeysSimpleLetterToTextFieldEvents_geckodriver_trace_log.txt](https://github.com/mozilla/geckodriver/files/1681009/testSendKeysSimpleLetterToTextFieldEvents_geckodriver_trace_log.txt)

**Comment by andreastt** [comment] 2018-01-31 12:00
I made some changes to focussing behaviour in https://bugzilla.mozilla.org/show_bug.cgi?id=1432864, but I wouldn’t expect this to cause `focus` _not_ to fire. Can you test with the very latest Nightly from yesterday/today and see if it is still a problem?

We have [a WPT test case for Element Send Keys](https://searchfox.org/mozilla-central/source/testing/web-platform/tests/webdriver/tests/element_send_keys/form_controls.py) that asserts that the event is being fired. If the latest Nightly does not have a fix, can you provide an HTML document that reproduces the problem?

**Comment by philipl-micro-focus** [comment] 2018-01-31 15:04
I already tested with Firefox Nightly 60.0a1 (2018-01-30) (64-bit) on MacOS and the test fails too for this FF version.

In the original issue description above I includes the test HTML page [testEventOrder2.html](https://github.com/mozilla/geckodriver/files/1680870/testEventOrder2-html.zip) with which the issue can be reproduced easily (just host it on localhost or on the file system).

**Comment by codingphil** [comment] 2018-01-31 16:51
Maybe this is related/duplicate of https://github.com/mozilla/geckodriver/issues/906 ?

I found out that if I manually click on the browser window after it was started the focus event get fired.
This also affects the "select" event for the text field.

Maybe the geckodriver does not start Firefox so that it has the focus or the internal webdriver related code should not depend on the fact, that Firefox does not have the focus?

**Comment by whimboo** [comment] 2018-02-01 11:18
geckodriver starts Firefox without the `-foreground` option. Can you please add that option to the `args` list inside of `moz:firefoxOptions` and check if that fixes your problem? In such a case we can mark this issue indeed as dupe of #906.

**Comment by codingphil** [comment] 2018-02-01 12:08
Adding "--foreground" as commandline fixed it. Thanks!

**Comment by whimboo** [comment] 2018-02-01 12:37
Great. So closing as dupe of #906.

**Closed by whimboo** 2018-02-01 12:37 UTC
Labels: waiting for reporter feedback

**Comment by testphreak** [comment] 2018-03-20 22:23
@whimboo and @andreastt, I sincerely don't mean to hijack this thread, but I couldn't find an answer online, hence posting here. I am running into the focus issue with FF `59.0.1` as described in this issue. Could you show the right way to pass the `-foreground` option to geckodriver using the Java binding? Here's what I tried, but didn't seem to work:

```java
MutableCapabilities capabilities = new MutableCapabilities();

FirefoxOptions firefoxOptions = new FirefoxOptions();
firefoxOptions.addArguments("-foreground");
firefoxOptions.setCapability("moz:firefoxOptions", firefoxOptions);

capabilities = firefoxOptions.merge(capabilities);
URL seleniumURL = null;
try {
         seleniumURL = new URL(hubUrl);
 } catch (MalformedURLException e) {
         e.printStackTrace();
 }

RemoteWebDriver webDriver = new RemoteWebDriver(seleniumURL, capabilities);
```
Also does [this](https://github.com/SeleniumHQ/selenium/blob/master/java/client/src/org/openqa/selenium/firefox/XpiDriverService.java#L114) mean that WebDriver already starts Firefox in the foreground?
