### ISSUE TITLE
Selenium Ruby bindings using Marionette not setting dropdown value properly

### ISSUE THREAD

**Issue by danqa** [mozilla/geckodriver#178] opened 2016-08-12 14:54 UTC
I have the following code:

```
def select_from_dropdown_selenium(element, option)
  dropdown = $driver.find_element(:css, "#{element}")
  select_list = Selenium::WebDriver::Support::Select.new(dropdown)
  select_list.select_by(:value, option)
end
```

Works perfectly in chrome and firefox pre Marionette. Using the 3.0.0.Beta2.1 ruby gem for selenium. Added Marionette to my path. Using Marionette the dropdown opens but the value is not selected, the dropdown just remain open and doesn't do anything.

**Comment by andreastt** [comment] 2016-08-12 15:20
Duplicate of https://github.com/mozilla/geckodriver/issues/94.

**Closed by andreastt** 2016-08-12 15:20 UTC
