### ISSUE TITLE
Selenium 3.5.0-GeckoDriver : getPlatform() method and map.get("platform") method returns different results for Platform through geckodriver

### ISSUE THREAD

**Issue by Debanjan-B** [mozilla/geckodriver#895] opened 2017-08-23 08:21 UTC
`getPlatform()` method and `map.get("platform")` method returns different results for `Platform` through geckodriver.

**`cap.getPlatform().toString()`** returns `Platform` as **`XP`** while **`map.get("platform")`** returns `Platform` as **`ANY`**

## System
* GeckoDriver Version: 0.18.0
* Platform: Windows8 Pro, 64 bit
* Firefox: Firefox: 55.0.2 (64-bit)
* Selenium: 3.5.0

## Testcase

Minimum Code Block:

	package demo;

	import java.util.Map;

	import org.openqa.selenium.Capabilities;
	import org.openqa.selenium.WebDriver;
	import org.openqa.selenium.firefox.FirefoxDriver;
	import org.openqa.selenium.remote.RemoteWebDriver;

	public class WEBDRIVER_Platform
	{
		public static void main(String[] args) 
		{
			String attribute = "platform";
			System.setProperty("webdriver.gecko.driver", "C:\\Utility\\BrowserDrivers\\geckodriver.exe");
			WebDriver driver = new FirefoxDriver();
			Capabilities cap = ((RemoteWebDriver) driver).getCapabilities();
			System.out.println("Platform is : "+cap.getPlatform().toString());
			Map<String, ?> map = cap.asMap();
			Object value = map.get(attribute);
			System.out.println("Key : " + attribute + " Value :"+ value);
		}
	}

## Stacktrace

Console output:

    Platform is : XP
    Key : platform Value :ANY

**Comment by andreastt** [comment] 2017-08-23 23:33
I think (?) this is a duplicate of https://github.com/mozilla/geckodriver/issues/897

**Closed by andreastt** 2017-08-23 23:33 UTC

**Comment by Debanjan-B** [comment] 2017-08-24 04:04
@andreastt Here is the detailed analysis for you:

The `Capabilities` Class returns a `Map<String, ?>` type of object which includes capabilities like `platform`, and `platformName`.

Issue #897 deals with the capability **`platformName`** which should have been **`windows`** but **`geckodriver`** is returning **`windows_nt`** which is altogether a separate Bug.

This issue tries to highlight the inconsistency regarding the `platform` parameter like, if we analyze the raw  `Map<String, ?>` type of object returned by `getCapabilities()` method, the key **platform** returns a value **`ANY`** where as the direct wrapper method `getPlatform()` returns a value **`XP`**

Maybe, @AutomatedTester and @shs96c can help us with a more deeper analysis if both/any of them are wrong/correct.

**Comment by andreastt** [comment] 2017-08-24 07:55
That sounds like a client API issue.
