### ISSUE TITLE
Firefox crash when run galen check command with firefox 50

### ISSUE THREAD

**Issue by vickeyhuang** [mozilla/geckodriver#363] opened 2016-11-24 11:51 UTC
galen check homepage.gspec --url http://testapp.galenframework.com/ --size 1024x768 --htmlreport report
testcase run well but in the end happen firefox crash.

log output：
[Child 82531] ###!!! ABORT: Aborting on channel error.: file /builds/slave/m-rel-m64-00000000000000000000/build/src/ipc/glue/MessageChannel.cpp, line 2056

**Comment by SimonN** [comment] 2016-11-26 23:04
I have sporadic segfaults during normal browsing. I could do nothing but read a static webpage, yet Firefox crashes sporadically out of the blue. The console output shows the same error:
```
[Child 2870] ###!!! ABORT: Aborting on channel error.: file /build/firefox/src/firefox-50.0/ipc/glue/MessageChannel.cpp, line 2056
```
Archlinux, Firefox 50.0, no crashes yet after the system update on 2016-11-21, but now random crashes since my system update on 2016-11-25. Firefox itself wasn't updated on the 25th, but maybe it relies on a dependency? Update log:
```
[2016-11-25 19:23] [PACMAN] starting full system upgrade
[2016-11-25 19:43] [ALPM] transaction started
[2016-11-25 19:43] [ALPM] upgraded ncurses (6.0-4 -> 6.0+20161112-1)
[2016-11-25 19:43] [ALPM] upgraded bash (4.4-1 -> 4.4.005-1)
[2016-11-25 19:43] [ALPM] upgraded xz (5.2.2-1 -> 5.2.2-2)
[2016-11-25 19:43] [ALPM] upgraded imagemagick (6.9.6.4-1 -> 6.9.6.5-1)
[2016-11-25 19:43] [ALPM] upgraded iputils (20160308.0db72a4-1 -> 20161105.1f2bb12-1)
[2016-11-25 19:43] [ALPM] upgraded libsynctex (2016.41290-7 -> 2016.41290-8)
[2016-11-25 19:43] [ALPM] upgraded linux (4.8.8-2 -> 4.8.10-1)
[2016-11-25 19:43] [ALPM-SCRIPTLET] >>> Updating module dependencies. Please wait ...
[2016-11-25 19:43] [ALPM] upgraded protobuf (2.6.1-2 -> 3.0.2-2)
[2016-11-25 19:43] [ALPM] upgraded mumble (1.2.17-1 -> 1.2.17-2)
[2016-11-25 19:43] [ALPM] upgraded nvidia (375.20-1 -> 375.20-3)
[2016-11-25 19:43] [ALPM-SCRIPTLET] In order to use nvidia module, reboot the system.
[2016-11-25 19:43] [ALPM] upgraded tslib (1.1-1 -> 1.2-1)
[2016-11-25 19:43] [ALPM] upgraded qt5-base (5.7.0-3 -> 5.7.0-6)
[2016-11-25 19:43] [ALPM] upgraded obs-studio (0.16.5-1 -> 0.16.6-1)
[2016-11-25 19:43] [ALPM] warning: /etc/pacman.d/mirrorlist installed as /etc/pacman.d/mirrorlist.pacnew
[2016-11-25 19:43] [ALPM] upgraded pacman-mirrorlist (20161114-1 -> 20161121-1)
[2016-11-25 19:43] [ALPM] upgraded texlive-bin (2016.41290-7 -> 2016.41290-8)
[2016-11-25 19:43] [ALPM] upgraded texlive-core (2016.42515-1 -> 2016.42515-2)
```

**Comment by AutomatedTester** [comment] 2016-11-28 14:55
Unfortunately this bug report doesnt really have anything actionable steps. Please can someone add a [concise reproducible test case](http://sscce.org/).

**Comment by SimonN** [comment] 2016-11-30 02:48
I'm sorry for my false alarm: My crash came from a defective RAM stick that coincided exactly with my last Arch Linux system update. Stick removed, crashes gone!

I can't shed more light on Vickey Huang's the original issue.

**Comment by andreastt** [comment] 2016-12-08 20:33
Duplicate of https://github.com/mozilla/geckodriver/issues/210.

**Closed by andreastt** 2016-12-08 20:33 UTC
Labels: waiting on info

**Comment by smoking-gun** [comment] 2017-02-08 08:43
encouter the same error constantly using 

Java Client   <-----> Windows installed Firefox 

Windows version: Windows 7 Professional Service Pack 1
Firefox Version:  51.0.1 (64-bit)

Steps:
1. Start selenium hub on Windows
c:\selenium>java -jar selenium-server-standalone-3.0.1.jar -role hub
15:53:32.913 INFO - Selenium build info: version: '3.0.1', revision: '1969d75'
15:53:32.915 INFO - Launching Selenium Grid hub
2017-02-08 15:53:33.903:INFO::main: Logging initialized @1477ms
15:53:33.927 INFO - Will listen on 4444
2017-02-08 15:53:34.022:INFO:osjs.Server:main: jetty-9.2.15.v20160210
2017-02-08 15:53:34.083:INFO:osjsh.ContextHandler:main: Started o.s.j.s.ServletContextHandler@17776a8{/,null,AVAILABLE}
2017-02-08 15:53:34.122:INFO:osjs.ServerConnector:main: Started ServerConnector@5b2e813{HTTP/1.1}{0.0.0.0:4444}
2017-02-08 15:53:34.125:INFO:osjs.Server:main: Started @1699ms
15:53:34.127 INFO - Nodes should register to http://172.28.22.88:4444/grid/register/
15:53:34.128 INFO - Selenium Grid hub is up and running

2. Start Selemium node on same Windows:
c:\selenium>java -jar selenium-server-standalone-3.0.1.jar -role hub
15:53:32.913 INFO - Selenium build info: version: '3.0.1', revision: '1969d75'
15:53:32.915 INFO - Launching Selenium Grid hub
2017-02-08 15:53:33.903:INFO::main: Logging initialized @1477ms
15:53:33.927 INFO - Will listen on 4444
2017-02-08 15:53:34.022:INFO:osjs.Server:main: jetty-9.2.15.v20160210
2017-02-08 15:53:34.083:INFO:osjsh.ContextHandler:main: Started o.s.j.s.ServletContextHandler@17776a8{/,null,AVAILABLE}
2017-02-08 15:53:34.122:INFO:osjs.ServerConnector:main: Started ServerConnector@5b2e813{HTTP/1.1}{0.0.0.0:4444}
2017-02-08 15:53:34.125:INFO:osjs.Server:main: Started @1699ms
15:53:34.127 INFO - Nodes should register to http://172.28.22.88:4444/grid/register/
15:53:34.128 INFO - Selenium Grid hub is up and running

3. Run java program:

   public void queryGoogle() throws Exception {
    	FirefoxProfile fp = new FirefoxProfile();
    	DesiredCapabilities dc = DesiredCapabilities.firefox();
    	dc.setCapability(FirefoxDriver.PROFILE, fp);    	
        WebDriver driver = new RemoteWebDriver(new URL("http://172.28.22.88:4444/wd/hub"), dc);        
        driver.get("http://www.google.com");
        WebElement input_q = driver.findElement(By.xpath("//input[@name='q']"));
        if(input_q != null) {
        	input_q.sendKeys("Selenium");
        }        
        driver.close();
        driver.quit();
    }

4. Error encounted:
16:01:35.658 INFO - Detected dialect: W3C
16:01:35.705 INFO - Done: [new session: Capabilities [{marionette=true, firefoxOptions=org.openqa.selenium.firefox.FirefoxOptions@25fdfccc, browserName=firefox, moz:firefoxOptions=org.openqa.selenium.
firefox.FirefoxOptions@25fdfccc, version=, platform=ANY, firefox_profile=UEsDBBQACAgIAA6ESEoAAAAAAAAAA...}]]
16:01:35.870 INFO - Executing: [get: http://www.google.com])
16:01:41.728 INFO - Done: [get: http://www.google.com]
16:01:41.754 INFO - Executing: [find element: By.xpath: //input[@name='q']])
16:01:41.802 INFO - Done: [find element: By.xpath: //input[@name='q']]
16:01:41.861 INFO - Executing: [send keys: 0 [[FirefoxDriver: firefox on XP (39c7df8c-4594-43a5-9edd-9331d5c7a469)] -> xpath: //input[@name='q']], [Selenium]])
16:01:42.075 INFO - Done: [send keys: 0 [[FirefoxDriver: firefox on XP (39c7df8c-4594-43a5-9edd-9331d5c7a469)] -> xpath: //input[@name='q']], [Selenium]]
16:01:42.092 INFO - Executing: [close window])
16:01:42.136 INFO - Done: [close window]
16:01:42.159 INFO - Executing: [delete session: ca395a06-e8c9-49cd-adf2-c28ab1e3d000])
[Child 5676] ###!!! ABORT: Aborting on channel error.: file c:/builds/moz2_slave/m-rel-w64-00000000000000000000/build/src/ipc/glue/MessageChannel.cpp, line 2056
16:01:43.651 ERROR - Unable to kill process with PID 5024
16:01:43.653 INFO - Done: [delete session: ca395a06-e8c9-49cd-adf2-c28ab1e3d000]

**Comment by smoking-gun** [comment] 2017-02-08 08:48
c:\webdriver>geckodriver.exe -V
geckodriver 0.14.0

The source code of this program is available at
https://github.com/mozilla/geckodriver.

This program is subject to the terms of the Mozilla Public License 2.0.
You can obtain a copy of the license at https://mozilla.org/MPL/2.0/.
