### ISSUE TITLE
gecokdriver doesn't work with custom profile

### ISSUE THREAD

**Issue by bolds07** [mozilla/geckodriver#1612] opened 2019-09-08 20:06 UTC
## System

* Version: v0.24.0
* Platform: windows 10 pro
* Firefox: 69.0 (64-bit)
* Selenium: 4.0.0-alpha-2 (i´ve tested with 3.41 also)

## Testcase

If i do set the profile folder into firefoxoptions the geckdriver doesn´t work
the program runs
firefox opens
but no functions called on the firefoxdriver will result in any actions taken... it simple doesn't respond to commands
while that firefox windows is opened and i can manually navigate to any page i want

it happens when setting ANY custom profile folder, if the folder doesn't exist, firefox will create and populate it with many files... but the selenium wont work anyway
if i set it to a previous create profile folder it will happen the same

if i simple comment the line  `fo.addArguments("-profile", "D:\\Area de Trabalho\\asdasd");` the program runs fine

i need to use several profiles for my case, and they must be elsewhere than the temp folder

how can i do it

```
 	System.setProperty("webdriver.gecko.driver", "D:\\Dropbox\\Workspace\\geckodriver.exe");
		new File("D:\\Area de Trabalho\\asdasd").mkdir();
		FirefoxOptions fo = new FirefoxOptions();
		fo.setLogLevel(FirefoxDriverLogLevel.TRACE);
	//	fo.addArguments("-marionette-port 51149");
	 fo.addArguments("-profile", "D:\\Area de Trabalho\\asdasd");
		new FirefoxDriver(fo).get("https://www.facebook.com.br");
```
 

## Trace-level log

```
1567972629840	mozrunner::runner	INFO	Running command: "C:\\Program Files\\Mozilla Firefox\\firefox.exe" "-marionette" "-profile" "D:\\Area de Trabalho\\asdasd" "-foreground" "-no-remote"
1567972629843	geckodriver::marionette	DEBUG	Waiting 60s to connect to browser on 127.0.0.1:52033
1567972690729	mozrunner::runner	DEBUG	Killing process 18740
1567972690729	webdriver::server	DEBUG	<- 500 Internal Server Error {"value":{"error":"unknown error","message":"connection refused","stacktrace":""}}
Exception in thread "main" org.openqa.selenium.WebDriverException: connection refused
Build info: version: '4.0.0-alpha-1', revision: 'd1d3728cae', time: '2019-04-24T13:42:21'
System info: host: 'BOLDS-A62', ip: '192.168.142.1', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '12.0.2'
Driver info: driver.version: MasterDriver
remote stacktrace: 
```

**Comment by whimboo** [comment] 2019-09-09 08:00
Dupe of #1058.

**Closed by whimboo** 2019-09-09 08:00 UTC

**Comment by bolds07** [comment] 2019-09-19 16:56
@whimboo this is not even close to be duplicate of the referred issue and i had read it before

since im the last comment says that version 0.22 SOLVED the referred issue and as stated im using version 0.24, plus i've tried with and without explicit setting the marionette port

so it is not a duplicate, is a valid still existing BUG OF GECKODRIVER

now if you are just here to close issues at glance wihtout even checking or asking for more info what is the point of this whole bullshit?

**Comment by andreastt** [comment] 2019-09-20 21:15
If you disagree it’s not a duplicate of https://github.com/mozilla/geckodriver/issues/1058 you have to underbuild that argument with a miniscule of evidence. There is no comment on the referenced bug that says that the underlying issue has been fixed.

I took another look at your issue report and agree with the conclusion from above. The fundamental issue here is that geckodriver never writes the Marionette port to `marionette.port` in the custom profile. Neither the randomised port it uses by the default or the value given to `--marionette-port <port>` is picked up. This causes Firefox to be launched with Marionette on port 2828 and geckodriver attempting to connect to it on another.

I also want to give you a friendly reminder that any contribution you make to the Mozilla community is subject to the [Mozilla Community Participation Guidelines](https://www.mozilla.org/en-US/about/governance/policies/participation/) and that means being respectful of the time other contributors put into this project.
