### ISSUE TITLE
Double click does not execute and does not give error.

### ISSUE THREAD

**Issue by WonderWoman01** [mozilla/geckodriver#556] opened 2017-03-20 17:24 UTC
## Firefox Version
52.0.1 (64-bit)    
Gecko driver 15     

## Platform
MAC OS    
Selenium WebDriver 3.3.1
Guava version 21

## Issue 
DoubleClick does not seem to execute but I don't receive any error messages.  My code errors on different steps.  The code below is suppose to open a record once the record is opened then it should proceed to the next set of code.  The next set of code is inputting text which is where it is failing because it can't find the field.

##The following are example of the code I've been trying without success.       
Example 1 (Original code that use to work)   
Actions action = new Actions(driver)   
WebElement recordTitle=wait90Located(By.xpath("//div[contains(text(),'" + adTitle + "')]"));    
CommonStuff.performDoubleclick(action, driver, recordTitle);   

##Example 2
Actions action = new Actions(driver)
WebElement recordTitle=wait90Located(By.xpath("//div[contains(text(),'" + adTitle + "')]")); 
action.moveToElement(recordTitle).doubleClick().perform();

##Example 3
Actions action = new Actions(driver)
WebElement recordTitle=wait90Located(By.xpath("//div[contains(text(),'" + adTitle + "')]")); 
action.moveToElement(recordTitle).doubleClick()build()..perform();

##Example 4
Actions action = new Actions(driver)
WebElement recordTitle=wait90Located(By.xpath("//div[contains(text(),'" + adTitle + "')]")); 
action.moveToElement(recordTitle).doubleClick(recordTitle).perform();

##Example 5
Actions action = new Actions(driver)
WebElement recordTitle=wait90Located(By.xpath("//div[contains(text(),'" + adTitle + "')]")); 
action.click(recordTitle);
action.click(recordTitle);

CODE FOR COMMONSTUFF
public static void performDoubleClick(Actions action, WebDriver driver, WebElement elementToDoubleClickOn) {
 

	if(driver instanceof SafariDriver) {
		  try {
			Thread.sleep(3000);
		  } catch (InterruptedException e) {
// TODO Auto-generated catch block
			e.printStackTrace();
		  }	
		 
		  JavascriptExecutor js = (JavascriptExecutor) driver;
		  Point point = elementToDoubleClickOn.getLocation();
		  int x = point.x;
		  int y = point.y;
	
		  String script = "var targLink = document.elementFromPoint(" + x + "," + y + "); var clickEvent  = document.createEvent ('MouseEvents'); clickEvent.initEvent ('dblclick', true, true); targLink.dispatchEvent (clickEvent);";
			  		  
		  System.out.println(script);
		  js.executeScript(script);	
			  
	} else {
		  action.doubleClick(elementToDoubleClickOn).perform();
	}
  }
*********************************************************************************

 I do not have or know how to get a log for geckodriver for this.

**Comment by adriens** [comment] 2017-03-21 03:14
It seems i have the same issue : @WonderWoman01 are you still stuck on this issue ?

**Comment by WonderWoman01** [comment] 2017-03-21 13:26
Yes, do you have any suggestions?

**Comment by adriens** [comment] 2017-03-21 21:25
For now, i have none, hopefully i'll give it a try on firefox on a windows station...

**Comment by adriens** [comment] 2017-03-21 21:25
I have created an issue also see https://github.com/mozilla/geckodriver/issues/558

**Comment by andreastt** [comment] 2017-03-23 12:49
Duplicate of https://github.com/mozilla/geckodriver/issues/159.

**Closed by andreastt** 2017-03-23 12:49 UTC
