### ISSUE TITLE
v0.10.0 may be broken for firefox 48.0.2

### ISSUE THREAD

**Issue by zhtaoang** [mozilla/geckodriver#234] opened 2016-09-20 07:05 UTC
I am using selenium 3 beta 3 and v0.10.0 of geckodriver. Stopped working after updated firefox to version 48.0.2 on both OS X El Capitan and Windows 10.

**Comment by lturi** [comment] 2016-09-22 14:46
What doesn't work? Are you getting error messages? 

For what it's worth, I ran into a similar issue where an update to firefox and selenium "broke" my tests, and found that I needed to refresh all libs from selenium 3.0.0 beta 3 in my project, and it started working again.

**Comment by viictorh** [comment] 2016-09-23 13:40
I'm using selenium 3 beta 3 and v0.10.0 of geckodriver, Firefox 48.0.02 windows 7 and not working too.
It opens firefox browser but completely blank, after about 1 minute, get the following error on java console:

> 

> org.openqa.selenium.firefox.NotConnectedException: Unable to connect to host 127.0.0.1 on port 7055 after 45000 ms. Firefox console output:
> "updateKey":null,"optionsURL":null,"optionsType":null,"aboutURL":null,"icons":{"32":"icon.png","48":"icon.png"},"iconURL":null,"icon64URL":null,"defaultLocale":{"name":"Default","description":"The default theme.","creator":"Mozilla","homepageURL":null,"contributors":["Mozilla Contributors"]},"visible":true,"active":true,"userDisabled":false,"appDisabled":false,"descriptor":"C:\\Program Files (x86)\\Mozilla Firefox\\browser\\extensions\\{972ce4c6-7e08-4474-a285-3208198ce6fd}.xpi","installDate":1472744440181,"updateDate":1472744440181,"applyBackgroundUpdates":1,"skinnable":true,"size":21905,"sourceURI":null,"releaseNotesURI":null,"softDisabled":false,"foreignInstall":false,"hasBinaryComponents":false,"strictCompatibility":true,"locales":[],"targetApplications":[{"id":"{ec8030f7-c20a-464f-9b0e-13a3a9e97384}","minVersion":"48.0.2","maxVersion":"48.0.2"}],"targetPlatforms":[],"seen":true}
> 1474637945987	addons.xpi	DEBUG	getModTime: Recursive scan of {972ce4c6-7e08-4474-a285-3208198ce6fd}
> 1474637945987	DeferredSave.extensions.json	DEBUG	Save changes
> 1474637945987	addons.xpi	DEBUG	Updating database with changes to installed add-ons
> 1474637945987	addons.xpi-utils	DEBUG	Updating add-on states
> 1474637945989	addons.xpi-utils	DEBUG	Writing add-ons list
> 1474637945992	addons.xpi	DEBUG	Registering manifest for C:\Program Files (x86)\Mozilla Firefox\browser\features\e10srollout@mozilla.org.xpi
> 1474637945993	addons.xpi	DEBUG	Calling bootstrap method startup on e10srollout@mozilla.org version 1.1
> 1474637945993	addons.xpi	DEBUG	Registering manifest for C:\Program Files (x86)\Mozilla Firefox\browser\features\firefox@getpocket.com.xpi
> 1474637945994	addons.xpi	DEBUG	Calling bootstrap method startup on firefox@getpocket.com version 1.0.4
> 1474637945994	addons.xpi	DEBUG	Registering manifest for C:\Program Files (x86)\Mozilla Firefox\browser\features\loop@mozilla.org.xpi
> 1474637945995	addons.xpi	DEBUG	Calling bootstrap method startup on loop@mozilla.org version 1.4.4
> 1474637946012	addons.manager	DEBUG	Registering shutdown blocker for XPIProvider
> 1474637946013	addons.manager	DEBUG	Provider finished startup: XPIProvider
> 1474637946013	addons.manager	DEBUG	Starting provider: LightweightThemeManager
> 1474637946013	addons.manager	DEBUG	Registering shutdown blocker for LightweightThemeManager
> 1474637946013	addons.manager	DEBUG	Provider finished startup: LightweightThemeManager
> 1474637946013	addons.manager	DEBUG	Starting provider: GMPProvider
> 1474637946020	addons.manager	DEBUG	Registering shutdown blocker for GMPProvider
> 1474637946021	addons.manager	DEBUG	Provider finished startup: GMPProvider
> 1474637946021	addons.manager	DEBUG	Starting provider: PluginProvider
> 1474637946021	addons.manager	DEBUG	Registering shutdown blocker for PluginProvider
> 1474637946021	addons.manager	DEBUG	Provider finished startup: PluginProvider
> 1474637946021	addons.manager	DEBUG	Completed startup sequence
> 1474637947804	addons.manager	DEBUG	Starting provider: <unnamed-provider>
> 1474637947804	addons.manager	DEBUG	Registering shutdown blocker for <unnamed-provider>
> 1474637947804	addons.manager	DEBUG	Provider finished startup: <unnamed-provider>
> 1474637948039	DeferredSave.extensions.json	DEBUG	Write succeeded
> 1474637948039	addons.xpi-utils	DEBUG	XPI Database saved, setting schema version preference to 17
> 1474637948039	DeferredSave.extensions.json	DEBUG	Starting timer
> 1474637948047	addons.repository	DEBUG	No addons.json found.
> 1474637948048	DeferredSave.addons.json	DEBUG	Save changes
> 1474637948051	DeferredSave.addons.json	DEBUG	Starting timer
> 1474637948308	addons.manager	DEBUG	Starting provider: PreviousExperimentProvider
> 1474637948308	addons.manager	DEBUG	Registering shutdown blocker for PreviousExperimentProvider
> 1474637948308	addons.manager	DEBUG	Provider finished startup: PreviousExperimentProvider
> 1474637948314	DeferredSave.extensions.json	DEBUG	Starting write
> 1474637948316	DeferredSave.addons.json	DEBUG	Starting write
> 1474637948433	DeferredSave.extensions.json	DEBUG	Write succeeded
> 1474637948437	DeferredSave.addons.json	DEBUG	Write succeeded
> 
> 	at org.openqa.selenium.firefox.internal.NewProfileExtensionConnection.start(NewProfileExtensionConnection.java:113)
> 	at org.openqa.selenium.firefox.FirefoxDriver.startClient(FirefoxDriver.java:314)
> 	at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:117)
> 	at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:231)
> 	at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:219)
> 	at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:214)
> 	at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:210)
> 	at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:123)
> 	at br.com.voxage.test.FirstTestCase.main(FirstTestCase.java:39)
> org.openqa.selenium.WebDriverException: Failed to connect to binary FirefoxBinary(C:\Program Files (x86)\Mozilla Firefox\firefox.exe) on port 7055; process output follows: 
> "updateKey":null,"optionsURL":null,"optionsType":null,"aboutURL":null,"icons":{"32":"icon.png","48":"icon.png"},"iconURL":null,"icon64URL":null,"defaultLocale":{"name":"Default","description":"The default theme.","creator":"Mozilla","homepageURL":null,"contributors":["Mozilla Contributors"]},"visible":true,"active":true,"userDisabled":false,"appDisabled":false,"descriptor":"C:\\Program Files (x86)\\Mozilla Firefox\\browser\\extensions\\{972ce4c6-7e08-4474-a285-3208198ce6fd}.xpi","installDate":1472744440181,"updateDate":1472744440181,"applyBackgroundUpdates":1,"skinnable":true,"size":21905,"sourceURI":null,"releaseNotesURI":null,"softDisabled":false,"foreignInstall":false,"hasBinaryComponents":false,"strictCompatibility":true,"locales":[],"targetApplications":[{"id":"{ec8030f7-c20a-464f-9b0e-13a3a9e97384}","minVersion":"48.0.2","maxVersion":"48.0.2"}],"targetPlatforms":[],"seen":true}
> 1474637945987	addons.xpi	DEBUG	getModTime: Recursive scan of {972ce4c6-7e08-4474-a285-3208198ce6fd}
> 1474637945987	DeferredSave.extensions.json	DEBUG	Save changes
> 1474637945987	addons.xpi	DEBUG	Updating database with changes to installed add-ons
> 1474637945987	addons.xpi-utils	DEBUG	Updating add-on states
> 1474637945989	addons.xpi-utils	DEBUG	Writing add-ons list
> 1474637945992	addons.xpi	DEBUG	Registering manifest for C:\Program Files (x86)\Mozilla Firefox\browser\features\e10srollout@mozilla.org.xpi
> 1474637945993	addons.xpi	DEBUG	Calling bootstrap method startup on e10srollout@mozilla.org version 1.1
> 1474637945993	addons.xpi	DEBUG	Registering manifest for C:\Program Files (x86)\Mozilla Firefox\browser\features\firefox@getpocket.com.xpi
> 1474637945994	addons.xpi	DEBUG	Calling bootstrap method startup on firefox@getpocket.com version 1.0.4
> 1474637945994	addons.xpi	DEBUG	Registering manifest for C:\Program Files (x86)\Mozilla Firefox\browser\features\loop@mozilla.org.xpi
> 1474637945995	addons.xpi	DEBUG	Calling bootstrap method startup on loop@mozilla.org version 1.4.4
> 1474637946012	addons.manager	DEBUG	Registering shutdown blocker for XPIProvider
> 1474637946013	addons.manager	DEBUG	Provider finished startup: XPIProvider
> 1474637946013	addons.manager	DEBUG	Starting provider: LightweightThemeManager
> 1474637946013	addons.manager	DEBUG	Registering shutdown blocker for LightweightThemeManager
> 1474637946013	addons.manager	DEBUG	Provider finished startup: LightweightThemeManager
> 1474637946013	addons.manager	DEBUG	Starting provider: GMPProvider
> 1474637946020	addons.manager	DEBUG	Registering shutdown blocker for GMPProvider
> 1474637946021	addons.manager	DEBUG	Provider finished startup: GMPProvider
> 1474637946021	addons.manager	DEBUG	Starting provider: PluginProvider
> 1474637946021	addons.manager	DEBUG	Registering shutdown blocker for PluginProvider
> 1474637946021	addons.manager	DEBUG	Provider finished startup: PluginProvider
> 1474637946021	addons.manager	DEBUG	Completed startup sequence
> 1474637947804	addons.manager	DEBUG	Starting provider: <unnamed-provider>
> 1474637947804	addons.manager	DEBUG	Registering shutdown blocker for <unnamed-provider>
> 1474637947804	addons.manager	DEBUG	Provider finished startup: <unnamed-provider>
> 1474637948039	DeferredSave.extensions.json	DEBUG	Write succeeded
> 1474637948039	addons.xpi-utils	DEBUG	XPI Database saved, setting schema version preference to 17
> 1474637948039	DeferredSave.extensions.json	DEBUG	Starting timer
> 1474637948047	addons.repository	DEBUG	No addons.json found.
> 1474637948048	DeferredSave.addons.json	DEBUG	Save changes
> 1474637948051	DeferredSave.addons.json	DEBUG	Starting timer
> 1474637948308	addons.manager	DEBUG	Starting provider: PreviousExperimentProvider
> 1474637948308	addons.manager	DEBUG	Registering shutdown blocker for PreviousExperimentProvider
> 1474637948308	addons.manager	DEBUG	Provider finished startup: PreviousExperimentProvider
> 1474637948314	DeferredSave.extensions.json	DEBUG	Starting write
> 1474637948316	DeferredSave.addons.json	DEBUG	Starting write
> 1474637948433	DeferredSave.extensions.json	DEBUG	Write succeeded
> 1474637948437	DeferredSave.addons.json	DEBUG	Write succeeded
> 
> Build info: version: 'unknown', revision: 'c7b525d', time: '2016-09-01 14:52:30 -0700'
> System info: host: 'WVOX-000805', ip: '172.16.0.138', os.name: 'Windows 7', os.arch: 'amd64', os.version: '6.1', java.version: '1.8.0_72'
> Driver info: driver.version: FirefoxDriver
> 	at org.openqa.selenium.firefox.internal.NewProfileExtensionConnection.start(NewProfileExtensionConnection.java:125)
> 	at org.openqa.selenium.firefox.FirefoxDriver.startClient(FirefoxDriver.java:314)
> 	at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:117)
> 	at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:231)
> 	at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:219)
> 	at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:214)
> 	at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:210)
> 	at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:123)
> 	at br.com.voxage.test.FirstTestCase.main(FirstTestCase.java:39)
> Caused by: org.openqa.selenium.firefox.NotConnectedException: Unable to connect to host 127.0.0.1 on port 7055 after 45000 ms. Firefox console output:
> "updateKey":null,"optionsURL":null,"optionsType":null,"aboutURL":null,"icons":{"32":"icon.png","48":"icon.png"},"iconURL":null,"icon64URL":null,"defaultLocale":{"name":"Default","description":"The default theme.","creator":"Mozilla","homepageURL":null,"contributors":["Mozilla Contributors"]},"visible":true,"active":true,"userDisabled":false,"appDisabled":false,"descriptor":"C:\\Program Files (x86)\\Mozilla Firefox\\browser\\extensions\\{972ce4c6-7e08-4474-a285-3208198ce6fd}.xpi","installDate":1472744440181,"updateDate":1472744440181,"applyBackgroundUpdates":1,"skinnable":true,"size":21905,"sourceURI":null,"releaseNotesURI":null,"softDisabled":false,"foreignInstall":false,"hasBinaryComponents":false,"strictCompatibility":true,"locales":[],"targetApplications":[{"id":"{ec8030f7-c20a-464f-9b0e-13a3a9e97384}","minVersion":"48.0.2","maxVersion":"48.0.2"}],"targetPlatforms":[],"seen":true}
> 1474637945987	addons.xpi	DEBUG	getModTime: Recursive scan of {972ce4c6-7e08-4474-a285-3208198ce6fd}
> 1474637945987	DeferredSave.extensions.json	DEBUG	Save changes
> 1474637945987	addons.xpi	DEBUG	Updating database with changes to installed add-ons
> 1474637945987	addons.xpi-utils	DEBUG	Updating add-on states
> 1474637945989	addons.xpi-utils	DEBUG	Writing add-ons list
> 1474637945992	addons.xpi	DEBUG	Registering manifest for C:\Program Files (x86)\Mozilla Firefox\browser\features\e10srollout@mozilla.org.xpi
> 1474637945993	addons.xpi	DEBUG	Calling bootstrap method startup on e10srollout@mozilla.org version 1.1
> 1474637945993	addons.xpi	DEBUG	Registering manifest for C:\Program Files (x86)\Mozilla Firefox\browser\features\firefox@getpocket.com.xpi
> 1474637945994	addons.xpi	DEBUG	Calling bootstrap method startup on firefox@getpocket.com version 1.0.4
> 1474637945994	addons.xpi	DEBUG	Registering manifest for C:\Program Files (x86)\Mozilla Firefox\browser\features\loop@mozilla.org.xpi
> 1474637945995	addons.xpi	DEBUG	Calling bootstrap method startup on loop@mozilla.org version 1.4.4
> 1474637946012	addons.manager	DEBUG	Registering shutdown blocker for XPIProvider
> 1474637946013	addons.manager	DEBUG	Provider finished startup: XPIProvider
> 1474637946013	addons.manager	DEBUG	Starting provider: LightweightThemeManager
> 1474637946013	addons.manager	DEBUG	Registering shutdown blocker for LightweightThemeManager
> 1474637946013	addons.manager	DEBUG	Provider finished startup: LightweightThemeManager
> 1474637946013	addons.manager	DEBUG	Starting provider: GMPProvider
> 1474637946020	addons.manager	DEBUG	Registering shutdown blocker for GMPProvider
> 1474637946021	addons.manager	DEBUG	Provider finished startup: GMPProvider
> 1474637946021	addons.manager	DEBUG	Starting provider: PluginProvider
> 1474637946021	addons.manager	DEBUG	Registering shutdown blocker for PluginProvider
> 1474637946021	addons.manager	DEBUG	Provider finished startup: PluginProvider
> 1474637946021	addons.manager	DEBUG	Completed startup sequence
> 1474637947804	addons.manager	DEBUG	Starting provider: <unnamed-provider>
> 1474637947804	addons.manager	DEBUG	Registering shutdown blocker for <unnamed-provider>
> 1474637947804	addons.manager	DEBUG	Provider finished startup: <unnamed-provider>
> 1474637948039	DeferredSave.extensions.json	DEBUG	Write succeeded
> 1474637948039	addons.xpi-utils	DEBUG	XPI Database saved, setting schema version preference to 17
> 1474637948039	DeferredSave.extensions.json	DEBUG	Starting timer
> 1474637948047	addons.repository	DEBUG	No addons.json found.
> 1474637948048	DeferredSave.addons.json	DEBUG	Save changes
> 1474637948051	DeferredSave.addons.json	DEBUG	Starting timer
> 1474637948308	addons.manager	DEBUG	Starting provider: PreviousExperimentProvider
> 1474637948308	addons.manager	DEBUG	Registering shutdown blocker for PreviousExperimentProvider
> 1474637948308	addons.manager	DEBUG	Provider finished startup: PreviousExperimentProvider
> 1474637948314	DeferredSave.extensions.json	DEBUG	Starting write
> 1474637948316	DeferredSave.addons.json	DEBUG	Starting write
> 1474637948433	DeferredSave.extensions.json	DEBUG	Write succeeded
> 1474637948437	DeferredSave.addons.json	DEBUG	Write succeeded
> 
> 	at org.openqa.selenium.firefox.internal.NewProfileExtensionConnection.start(NewProfileExtensionConnection.java:113)
> 	... 8 more

**Comment by andreastt** [comment] 2016-09-23 17:55
@viictorh We can’t really debug what the problem is unless you include a verbose log from geckodriver. Please start it with `-vv`.

**Comment by FlorianSchaetz** [comment] 2016-09-28 08:34
Selenium also stopped working for us here with FF 49.0 (same result, test opens FF, blank page, nothing happens, Selenium times out). Unfortunately, I have no idea how to give -vv to the geckodriver from java, so I cannot help with a log, sorry, just wanted to add 49.0 to the "problem".

**Comment by elgalu** [comment] 2016-09-30 01:27
In your tests, you need to set `capabilities['marionette'] = True` or `capabilities.set('marionette', true);` (depending on your webdriver language bindings) if you are still using selenium 2 bindings.

All note one thing is the version of the selenium server and another the language bindings.

**Comment by FlorianSchaetz** [comment] 2016-09-30 04:54
The tests **stopped** working. This implies, they worked before. Which implies that yes, I am already setting the marionette capability.

**Comment by cgoldberg** [comment] 2016-09-30 14:55
> The tests stopped working. This implies, they worked before.
 
before what?  what *exactly* changed?

> Which implies that yes, I am already setting the marionette capability

A previously working configuration on some unspecified versions does *not* imply use of marionette.   Did you set it explicitly in your code or not?

**Comment by FlorianSchaetz** [comment] 2016-09-30 14:58
Before FF 49. That's the only thing that has changed on my machine, Selenium, WebDriver, etc. are all the same. The build server, which runs a FF 45, still works fine.
And yes, that's what I wanted to clarify: Before that, with the older FF version, it worked. And yes, I did set it explicitly in my code.

**Comment by cyberchucktx** [comment] 2016-10-12 21:42
Using FF 49.0.1 on MacOSX 10.11.6 (15G1004) (El Capitaine). I am trying to use node's selenium-webdriver example (see attachment). 

I haven't tried this node.js code with an older version of Firefox yet. 

I get the same result as others have reported: test opens FF, blank page, nothing happens, Selenium times out. 

This same code works with Safari and Chrome on Mac. 

I don't know how to set flags on 'geckodriver' from within the node.js code, or if there are any log files I can find somewhere. 

[selenium-firefox1.js.zip](https://github.com/mozilla/geckodriver/files/525695/selenium-firefox1.js.zip)

**Comment by andreastt** [comment] 2016-12-16 01:44
As we are unable to reproduce this, I’m going to have to close it. If you disagree, I’m happy to reopen once sufficient logging information has been added that makes it reproducible.

**Closed by andreastt** 2016-12-16 01:44 UTC
