### ISSUE TITLE
Implement an endpoint for installing addons

### ISSUE THREAD

**Issue by jgraham** [mozilla/geckodriver#597] opened 2017-04-03 15:57 UTC
Marionette exposes an API for installing and uninstalling addons. We should add this as a custom endpoint for geckodriver, much like we currently do for e.g. switching to chrome context.

**Comment by jgraham** [comment] 2017-04-03 15:57
@mjzffr Do you fancy having a go at this? I don't think it's too hard; just follow the approach of the other custom commands.

**Comment by andreastt** [comment] 2017-04-03 16:01
Duplicate of https://github.com/mozilla/geckodriver/issues/211.

**Closed by andreastt** 2017-04-03 16:01 UTC
