### ISSUE TITLE
Firefox.exe - application error appear when closing Selenium Session 

### ISSUE THREAD

**Issue by sanjapa** [mozilla/geckodriver#375] opened 2016-12-02 15:18 UTC
The issue was reproduced on:
OS:  
Windows Server 2012 RC 2 Standard
Browser Version:  
50.0.2
Gecko WebDriver Version: 
0.11.1
Selenium Server: 3.0.1

Expected Behavior: Selenium Session should close normally, without getting any application errors from Firefox 
Actual Behavior: When closing the Selenium Session, the following error message appear: The exception Breakpoint A brakpoint has been reached. (0x80000003) occurred in the application at location 0x65e900ef
Click OK to terminate the program
![image](https://cloud.githubusercontent.com/assets/7271821/20838795/6787d0c2-b8aa-11e6-8467-0c9afa58006e.png)

Steps to reproduce: 
1. Start your selenium test using Gecko driver (I am using Nightwatch framework)
2. At the end of the test, close the selenium session using appropriate command
Selenium code: webdriver.quit()

`15:08:02.977 INFO - Done: [get text: 21 [[FirefoxDriver: firefox on XP (39daf1dc
-978b-4fd0-aa9a-ec091e46b544)] -> xpath: //*[@id="page-wrapper"]/div[1]/s4i-tab-
control/div/div/div/div/div[2]/div[1]/div[2]]]
15:08:03.307 INFO - Executing: [delete session: 122415d9-6b1a-40fc-925e-fcde4e62
6a69])
[Child 5568] ###!!! ABORT: Aborting on channel error.: file c:/builds/moz2_slave
/m-rel-w64-00000000000000000000/build/src/ipc/glue/MessageChannel.cpp, line 2056

15:08:04.620 ERROR - Unable to kill process with PID 4772
15:08:04.620 INFO - Done: [delete session: 122415d9-6b1a-40fc-925e-fcde4e626a69]`

** Note: The issue is not happening when using Firefox 47.0, without using gecko driver on the same machine

**Comment by oscarcarlsson** [comment] 2016-12-06 07:57
I've seen the same issue on a very similar setup with Windows Server 2012 R2, latest Firefox & geckodriver 0.11.1 with Selenium 3.0.1. I can still run tests but the popups are very annoying and might lead to issues further down the road.

**Comment by mosaadm** [comment] 2016-12-07 08:57
I am using Windows Server 2012 R2, latest Firefox & geckodriver 0.11.1 with Selenium 3.0.1 and I have the same popup. Also If I started tests from jenkins nothing works and I get this error 

```
###!!! [Parent][MessageChannel] Error: (msgtype=0x2E007D,name=PBrowser::Msg_Destroy) Channel error: cannot send/recv

JavaScript error: resource://app/modules/ContentCrashHandlers.jsm, line 75: TypeError: browser.permanentKey is not a non-null object

###!!! [Parent][MessageChannel] Error: (msgtype=0x2E007D,name=PBrowser::Msg_Destroy) Channel error: cannot send/recv

org.openqa.selenium.remote.ProtocolHandshake createSession
INFORMATION: Detected dialect: W3C

###!!! [Parent][MessageChannel] Error: (msgtype=0x2E007D,name=PBrowser::Msg_Destroy) Channel error: cannot send/recv
```

**Comment by sandeepsajiru** [comment] 2016-12-07 09:49
Hitting this on Windows 8.1 as well while running a Selenium test with firefox that simply launches and quits the browser.

```
package in.beingzero.selenium.artifact;
import org.openqa.selenium.firefox.FirefoxDriver;
public class Test {
	public static void main(String[] args) {
		FirefoxDriver fd = new FirefoxDriver();
		fd.quit();
	}
}
```

Errors seen in eclipse **Console** View 
```
1481103681904	geckodriver	INFO	Listening on 127.0.0.1:40303
Dec 07, 2016 1:41:22 AM org.openqa.selenium.remote.ProtocolHandshake createSession
INFO: Attempting bi-dialect session, assuming Postel's Law holds true on the remote end
1481103682647	mozprofile::profile	INFO	Using profile path C:\Users\Sandeep\AppData\Local\Temp\rust_mozprofile.DGSFlTy6V9Tv
1481103682653	geckodriver::marionette	INFO	Starting browser C:\Program Files (x86)\Mozilla Firefox\firefox.exe
1481103682663	geckodriver::marionette	INFO	Connecting to Marionette on localhost:60837
1481103683343	Marionette	INFO	Listening on port 60837
Dec 07, 2016 1:41:25 AM org.openqa.selenium.remote.ProtocolHandshake createSession
INFO: Detected dialect: W3C
[Child 3504] ###!!! ABORT: Aborting on channel error.: file c:/builds/moz2_slave/m-rel-w32-00000000000000000000/build/src/ipc/glue/MessageChannel.cpp, line 2056

```

**Comment by tedcohen** [comment] 2016-12-07 23:06
Same issue. Would add that:
 - It happens with either the quit or the close method.
  - It happens both running under eclipse or standalone 
 -  no surprise the instances of geckodriver and filrefox accumulate
    until I manually terminate them one way or another.

I am not a cpp programmer but do have access to visual studio which I think includes a cpp compiler.
If someone would teach me how to build the geckodriver with the tools that I have, I am sure that I cold find the issue, The rub is that I am sure the other contributors can find and fix faster than they could teach me to build it.  Let me know if I can help in any way.

**Comment by tedcohen** [comment] 2016-12-08 10:25
I am thrilled to report that I FF 50.0.2 became available recently. I downloaded and installed it and this issue disappeared.

**Comment by oscarcarlsson** [comment] 2016-12-08 10:51
I still have the same issue as before, running Firefox 50.0.2.6177

Problem signature:
  Problem Event Name:	APPCRASH
  Application Name:	firefox.exe
  Application Version:	50.0.2.6177
  Application Timestamp:	583e4e01
  Fault Module Name:	mozglue.dll
  Fault Module Version:	50.0.2.6177
  Fault Module Timestamp:	583e4dd4
  Exception Code:	80000003
  Exception Offset:	00000000000100ef
  OS Version:	6.3.9600.2.0.0.272.7
  Locale ID:	1033
  Additional Information 1:	8406
  Additional Information 2:	84066008ed393277e1a1a51b9b1b869c
  Additional Information 3:	fb2c
  Additional Information 4:	fb2ce9700d5b135ebd82ee0a1701b619

**Comment by andreastt** [comment] 2016-12-09 00:13
Duplicate of https://github.com/mozilla/geckodriver/issues/210.

**Closed by andreastt** 2016-12-09 00:13 UTC

**Comment by shristi7** [comment] 2017-01-04 21:47
Receiving this error on Windows server 2012 R2 with FF latest version 50.1.0 and Selenium 3.0

**Comment by ant-howell** [comment] 2017-01-12 15:21
Also seeing this on Windows 8 Pro, FF 50.1.0 and Selenium 3.0. Exactly the same error that has been recently.

**Comment by rbaconryx** [comment] 2017-01-12 22:36
Same problem, Windows 2012 R2, FF 50.1.0
Python 2.7 script executing latest Selenium/Webdriver

**Comment by andreastt** [comment] 2017-01-18 15:13
This is a duplicate. Locking.
