### ISSUE TITLE
Unable to recognize platform capabilities VISTA or WIN10, but works with WINDOWS only

### ISSUE THREAD

**Issue by IgorBM** [mozilla/geckodriver#1218] opened 2018-03-15 11:00 UTC
## System

* Version: 0.20.0
* Platform: Win7
* Firefox: FF 59
* Selenium: 3.11.0

the same behavior was when using:
* Version: 0.19.1
* Platform: Win7
* Firefox: 58.0.2
* Selenium:  3.9.1

## Testcase
in properties file:
`browserType=firefox`
`browserVersion=ANY`
`osName=VISTA`

When I change osName to WINDOWS tests are able to run, if I use VISTA or WIN10 I've got the stacktrace below.

I need to run my tests either on Win7 node or on Win10, so for Chrome and for FF versions below 47 VISTA and WIN10 work well.

in SeleniumFactory.java:
`System.setProperty("webdriver.gecko.driver", "c:\\Selenium\\geckodriver.exe");
System.setProperty("webdriver.firefox.bin", "C:\\Program Files\\Mozilla Firefox\\firefox.exe");
FirefoxOptions firefoxOptions = new FirefoxOptions();
firefoxOptions.addPreference("enableNativeEvents", true);
firefoxOptions.setCapability(CapabilityType.VERSION, browserVersion);
firefoxOptions.setCapability(CapabilityType.PLATFORM_NAME, Platform.valueOf(osName));
firefoxOptions.setCapability(CapabilityType.PLATFORM, Platform.valueOf(osName));
firefoxOptions.setBinary("C:\\Program Files\\Mozilla Firefox\\firefox.exe");
firefoxOptions.setCapability("acceptInsecureCerts", true);
firefoxOptions.setLogLevel(FirefoxDriverLogLevel.TRACE);
WebDriver firefoxDriver = new FirefoxDriver(firefoxOptions);`

## Stacktrace

Caused by: org.openqa.selenium.SessionNotCreatedException: Unable to find a matching set of capabilities
Build info: version: '3.6.0', revision: '6fbf3ec767', time: '2017-09-27T15:28:36.4Z'
System info: host: 'IGOR', ip: '172.16.99.240', os.name: 'Windows 7', os.arch: 'amd64', os.version: '6.1', java.version: '1.8.0_77'
Driver info: driver.version: FirefoxDriver
remote stacktrace: 
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.openqa.selenium.remote.W3CHandshakeResponse.lambda$new$0(W3CHandshakeResponse.java:57)
	at org.openqa.selenium.remote.W3CHandshakeResponse.lambda$getResponseFunction$2(W3CHandshakeResponse.java:104)
	at org.openqa.selenium.remote.ProtocolHandshake.lambda$createSession$0(ProtocolHandshake.java:123)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
	at java.util.Spliterators$ArraySpliterator.tryAdvance(Spliterators.java:958)
	at java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:126)
	at java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:498)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:485)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.FindOps$FindOp.evaluateSequential(FindOps.java:152)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.findFirst(ReferencePipeline.java:464)
	at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:126)
	at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:73)
	at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:136)
	at org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:83)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:545)
	at org.openqa.selenium.remote.RemoteWebDriver.startSession(RemoteWebDriver.java:209)
	at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:132)
	at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:120)
	at com.ixl.aqa.factory.SeleniumFactory.getWebDriver(SeleniumFactory.java:201)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:162)
	... 50 more
1521109634493	geckodriver	INFO	geckodriver 0.20.0
1521109634505	geckodriver	INFO	Listening on 127.0.0.1:27520
 Failed to instantiate [org.openqa.selenium.WebDriver]: Factory method 'getWebDriver' threw exception; nested exception is org.openqa.selenium.SessionNotCreatedException: Unable to find a matching set of capabilities

## Trace-level log

1521124414888	geckodriver::marionette	TRACE	-> 301:[0,1,"newSession",{"acceptInsecureCerts":true,"browserName":"firefox","capabilities":{"desiredCapabilities":{"acceptInsecureCerts":true,"browserName":"firefox","moz:useNonSpecCompliantPointerOrigin":true,"platformName":"windows"}},"moz:useNonSpecCompliantPointerOrigin":true,"platformName":"windows"}]
1521124414888	Marionette	TRACE	0 -> [0,1,"newSession",{"acceptInsecureCerts":true,"browserName":"firefox","capabilities":{"desiredCapabilities":{"acceptInsecureC ... ompliantPointerOrigin":true,"platformName":"windows"}},"moz:useNonSpecCompliantPointerOrigin":true,"platformName":"windows"}]
1521124414890	Marionette	WARN	TLS certificate errors will be ignored for this session
1521124414956	Marionette	DEBUG	Register listener.js for window 4294967297
1521124414960	Marionette	TRACE	0 <- [1,1,null,{"sessionId":"49f403fa-4393-43ea-baf4-f0704c9f79b1","capabilities":{"browserName":"firefox","browserVersion":"59.0" ... \AppData\\Local\\Temp\\rust_mozprofile.MwBRcNgbm9wz","moz:useNonSpecCompliantPointerOrigin":true,"moz:webdriverClick":true}}]
1521124414963	geckodriver::marionette	TRACE	<- [1,1,null,{"sessionId":"49f403fa-4393-43ea-baf4-f0704c9f79b1","capabilities":{"browserName":"firefox","browserVersion":"59.0","platformName":"windows_nt","platformVersion":"6.1","pageLoadStrategy":"normal","acceptInsecureCerts":true,"timeouts":{"implicit":0,"pageLoad":300000,"script":30000},"rotatable":false,"moz:accessibilityChecks":false,"moz:headless":false,"moz:processID":7036,"moz:profile":"C:\\Users\\Igor\\AppData\\Local\\Temp\\rust_mozprofile.MwBRcNgbm9wz","moz:useNonSpecCompliantPointerOrigin":true,"moz:webdriverClick":true}}]
1521124414964	webdriver::server	DEBUG	<- 200 OK {"value": {"sessionId":"49f403fa-4393-43ea-baf4-f0704c9f79b1","capabilities":{"acceptInsecureCerts":true,"browserName":"firefox","browserVersion":"59.0","moz:accessibilityChecks":false,"moz:headless":false,"moz:processID":7036,"moz:profile":"C:\\Users\\Igor\\AppData\\Local\\Temp\\rust_mozprofile.MwBRcNgbm9wz","moz:useNonSpecCompliantPointerOrigin":true,"moz:webdriverClick":true,"pageLoadStrategy":"normal","platformName":"windows_nt","platformVersion":"6.1","rotatable":false,"timeouts":{"implicit":0,"pageLoad":300000,"script":30000}}}}

**Comment by IgorBM** [comment] 2018-03-15 14:36
Looks like Windows 7 is determined as `"platformName":"windows_nt"` by the driver

**Comment by dylanlive** [comment] 2018-03-16 03:50
This might be a duplicate of https://github.com/mozilla/geckodriver/issues/1030

**Comment by andreastt** [comment] 2018-03-16 17:24
Thanks! Yes it is.

**Closed by andreastt** 2018-03-16 17:24 UTC

**Comment by IgorBM** [comment] 2018-03-16 18:38
No,it isn't. "platformName": "windows" works for me. VISTA and WIN10 members from enum Platform seems to be not implemented.

**Comment by IgorBM** [comment] 2018-03-16 18:47
but I agree with @andreastt in the last comment of #1030 ,  because we also have platform explicitly set in node config (e.g. to WIN10) and we're experiencing this issue anyway, so this looks like a general issue with matching capabilities

**Comment by andreastt** [comment] 2018-03-17 10:07
FWIW the spec only mandates that we should support _well-recognised_ platform names, such as `windows`. This means `VISTA` and `WIN10` are out of scope. I suspect the whole Platform enum you refer to makes incorrect assumptions about the reality.

**Comment by IgorBM** [comment] 2018-03-17 12:53
Platform enum is from package org.openqa.selenium Platform.java; It worked perfectly with Firefox driver in FF below version 47, and it still work with chromedriver. I really do not understand point of view that following the spec shall broke working tests and affect thousands of test automation developers. Now I face about different 4 bugs in gecko, and while this one is not of high importance, several other are real blockers for my tests.

**Comment by chitayta** [comment] 2019-07-03 14:09
My wonder is that lastly it only accepts 'Windows' as 'platformName' capability? 
I am experiencing this issue with gecko latest version (0.24.0) and Firefox version 67.
I expected to run selenium using firefox with specific platforms ('VISTA', 'WIN10', 'WIN7', etc.) rather than the general one ('Windows') but got no luck.

I also tried with Chromedriver and it works and accepts these values as expected.
Thanks :)
