### ISSUE TITLE
folder upload is not working in selenium python with geckodriver (it works fine in chromedriver)

### ISSUE THREAD

**Issue by Parth2501** [mozilla/geckodriver#1993] opened 2022-03-04 06:05 UTC
## System

* Version: 0.30.0
* Platform: macOS Monterey 12.1, windows10
* Firefox: 97.0.1
* Selenium: 4.1.0

## Testcase
<html>
<body>
<input id="folder_upload" webkitdirectory="" mozdirectory="" type="file" multiple="">
</body>
</html>

## Stacktrace

Traceback (most recent call last):
  File "/Users/parth/PycharmProjects/seleniumProject/session_remote.py", line 60, in <module>
    elem.send_keys("/Users/parth/bin")
  File "/Users/parth/PycharmProjects/seleniumProject/venv/lib/python3.8/site-packages/selenium/webdriver/remote/webelement.py", line 540, in send_keys
    self._execute(Command.SEND_KEYS_TO_ELEMENT,
  File "/Users/parth/PycharmProjects/seleniumProject/venv/lib/python3.8/site-packages/selenium/webdriver/remote/webelement.py", line 710, in _execute
    return self._parent.execute(command, params)
  File "/Users/parth/PycharmProjects/seleniumProject/venv/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 424, in execute
    self.error_handler.check_response(response)
  File "/Users/parth/PycharmProjects/seleniumProject/venv/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 247, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.InvalidArgumentException: Message: File not found: /Users/parth/bin
Stacktrace:
WebDriverError@chrome://remote/content/shared/webdriver/Errors.jsm:183:5
InvalidArgumentError@chrome://remote/content/shared/webdriver/Errors.jsm:312:5
interaction.uploadFiles@chrome://remote/content/marionette/interaction.js:539:13

## Trace-level log
see the attchment
[folder_upload.log](https://github.com/mozilla/geckodriver/files/8183377/folder_upload.log)

**Comment by whimboo** [comment] 2022-03-04 16:56
Duplicate of issue #1788.

**Closed by whimboo** 2022-03-04 16:56 UTC
