### ISSUE TITLE
Switching between windows throwing error. 

### ISSUE THREAD

**Issue by sukhjinder-sdei** [mozilla/geckodriver#1370] opened 2018-09-11 13:24 UTC
## System

* Version: 0.21.0
* Platform: Windows 10 Pro 
* Firefox: 62.0
* Selenium: 3.12.0

## Testcase
We have default  window  and there is a link inside the frame once click on the link it opens another tab 
then we switich using  driver.switchTo().window(win); 
Expected : It should switch 
Actual:
org.openqa.selenium.WebDriverException: java.net.SocketException: Software caused connection abort: 

## Stacktrace
org.openqa.selenium.WebDriverException: java.net.SocketException: Software caused connection abort: recv failed

**Comment by whimboo** [comment] 2018-09-13 14:03
@sukhjinder-sdei the requested trace log hasn't been attached to to this issue. As such there is nothing we can do. So please check https://firefox-source-docs.mozilla.org/testing/geckodriver/geckodriver/TraceLogs.html, and attach it here.

Also please show the code example which triggers this, and the Selenium strack trace.

**Comment by sukhjinder-sdei** [comment] 2018-09-17 04:46
@whimboo Thanks for your reply, I have resolved this issue.

This issue is arising only when we have switched to frame and then we need to switch to another window.

The solution is first to switch back to default content and then move to another window.

Although this need to be improved/fixed.

**Comment by hariharanravichandran** [comment] 2018-09-17 14:00
@sukhjinder-sdei I am also facing this issue. 

1. My application webpage has 3 JSPs embedded in 3 frames. 
2. user is making action in second frame and he is getting an alert.
3. He accepts the alert. 
Focus is not returned to the second frame. Instead, It has thrown NoSuchElementException.

Please help on this. 
geckodriver =  0.22
Firefox = 60.0.1

**Comment by whimboo** [comment] 2018-09-18 06:15
@hariharanravichandran, your issue is different and as best should be filed as separate issue. As such I will hide your comment on this issue. But before you file a new issue please check with the latest Firefox 63 Beta release if it now works. Because a patch landed for that release which should improve that.

**Comment by whimboo** [comment] 2018-09-18 06:16
@sukhjinder-sdei I would still be interested to get the trace log as requested above. We have tests which are getting run for each commit, but those don't show this problem. So hopefully your trace logs can help me to understand what's going on. Thanks!

**Comment by whimboo** [comment] 2018-11-20 13:21
This should just be https://bugzilla.mozilla.org/show_bug.cgi?id=1305822.

**Comment by whimboo** [comment] 2020-10-23 09:31
Actually this is a duplicate of issue #610.

**Closed by whimboo** 2020-10-23 09:31 UTC
Labels: marionette
