### ISSUE TITLE
driver.manage().window().maximize() works incorrectly in Firefox driver;

### ISSUE THREAD

**Issue by DOlllDb** [mozilla/geckodriver#993] opened 2017-10-03 15:19 UTC
## System
Version: 0.19 (win x64)
Platform: Windows 7 x64
Firefox: 56.0 (x64)
Selenium: 3.5.3
Testcase

## Testcase
public static void main(String[] args) {
    WebDriver driver = new FirefoxDriver();
   driver.manage().window().maximize();
   driver.manage().window().maximize();
   ...
   driver.manage().window().maximize();
   driver.manage().window().maximize();
}

## Result
When firefox is maximized and I call a maximize() then Firefox window shrinks, when I call maximize again, it maximizes, if I call maximize again, it shinks again. And so on and on.
So to sum it up, on maximized windows webdriver's maximize method works incorrectly.

## Workaround
for it to work properly I had to make something like that:
private static int compareDimensions(Dimension dim1, Dimension dim2) {
    if (dim1.equals(dim2)) 
        return 0;
    else if (dim1.height >= dim2.height || dim1.width >= dim2.width)
        return 1;
    else
        return -1;
}

public static void maximize(WebDriver driver) {
    Dimension before = driver.manage().window().getSize();
    driver.manage().window().maximize();
    if (compareDimensions(before, driver.manage().window().getSize()) > 0)
        driver.manage().window().maximize();
}

**Comment by andreastt** [comment] 2017-10-03 16:08
This was fixed in Firefox 57.

**Closed by andreastt** 2017-10-03 16:08 UTC

**Comment by warpech** [comment] 2017-10-16 09:30
For own reference: looks like duplicate of https://github.com/mozilla/geckodriver/issues/900
