### ISSUE TITLE
Calling driver.quit() fails on "Aborting on channel error."

### ISSUE THREAD

**Issue by juperala** [mozilla/geckodriver#387] opened 2016-12-09 14:04 UTC
Firefox version: 50.0.2 (also seems to occur with any Firefox 48+ version)
Geckodriver: v0.11.1
Platform: Windows 7 64bit
Selenium Java libraries: 3.0.1

After updating to Selenium 3 and Geckodriver we have been experiencing random failures on calling driver.quit(). In case of failures (approximately 20-60% of test runs) the Firefox prompts an error dialog and error is shown in geckodriver log:

![capture](https://cloud.githubusercontent.com/assets/4807576/21052430/b83ddd62-be2d-11e6-8339-51d1f1ead4fd.PNG)

> [Child 11304] ###!!! ABORT: Aborting on channel error.: file c:/builds/moz2_slave/m-rel-w64-00000000000000000000/build/src/ipc/glue/MessageChannel.cpp, line 2056
> joulukuuta 09, 2016 4:15:36 IP. org.openqa.selenium.os.UnixProcess destroy
> SEVERE: Unable to kill process with PID 12796

The example test code causing these random failures:

```
package test;
import java.util.concurrent.TimeUnit;
import org.junit.After;
import org.junit.Before;
import org.junit.Test;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;

public class SeleniumTest {
    private WebDriver driver;
    @Before
    public void before() {
        driver = new FirefoxDriver();
        driver.manage().window().maximize();
        driver.manage().timeouts().implicitlyWait(5, TimeUnit.SECONDS);
    }
    @After
    public void tearDown() throws InterruptedException {
        driver.manage().deleteAllCookies();
        driver.quit();
    }
    @Test
    public void test1() throws InterruptedException {
        driver.get("http://www.google.com");
        driver.findElement(By.name("btnI")).click();
    }
}
```

Anyone experienced anything similar?

**Comment by juperala** [comment] 2016-12-12 20:00
Tested also on Windows 10 (Firefox 50.0.2, Geckodriver 0.11.1).

With this configuration the Firefox does shutdown without hanging on error dialog (which makes issue less blocking). However, in the geckodriver log similar errors are shown during driver.quit() indicating failure to close Firefox process gracefully:

> [Child 11888] ###!!! ABORT: Aborting on channel error.: file c:/builds/moz2_slave/m-rel-w32-00000000000000000000/build/src/ipc/glue/MessageChannel.cpp, line 2056
> joulukuuta 12, 2016 9:49:28 IP. org.openqa.selenium.os.UnixProcess destroy
> SEVERE: Unable to kill process with PID 5964

Also, on some executions geckodriver log showed different types of errors while calling driver.quit():

> [Child 13296] ###!!! ABORT: Aborting on channel error.: file c:/builds/moz2_slave/m-rel-w32-00000000000000000000/build/src/ipc/glue/MessageChannel.cpp, line 2056
> ###!!! [Child][MessageChannel] Error: (msgtype=0x420003,name=PCompositable::Msg_Destroy) Channel error: cannot send/recv
> ###!!! [Child][MessageChannel] Error: (msgtype=0x1060003,name=PTexture::Msg_Destroy) Channel error: cannot send/recv
> ###!!! [Child][MessageChannel] Error: (msgtype=0x420003,name=PCompositable::Msg_Destroy) Channel error: cannot send/recv
> ###!!! [Child][MessageChannel] Error: (msgtype=0x1060003,name=PTexture::Msg_Destroy) Channel error: cannot send/recv
> ###!!! [Child][MessageChannel] Error: (msgtype=0x420003,name=PCompositable::Msg_Destroy) Channel error: cannot send/recv
> ###!!! [Child][MessageChannel] Error: (msgtype=0x1060003,name=PTexture::Msg_Destroy) Channel error: cannot send/recv
> ###!!! [Child][MessageChannel] Error: (msgtype=0x420003,name=PCompositable::Msg_Destroy) Channel error: cannot send/recv

Not exactly sure whether this is an geckodriver, Firefox or Selenium issue? Any ideas?

**Comment by andreastt** [comment] 2016-12-13 15:49
Duplicate of https://github.com/mozilla/geckodriver/issues/210.

**Closed by andreastt** 2016-12-13 15:49 UTC

**Comment by qfyxixi** [comment] 2017-01-15 16:28
Firefox version: 50.1.0
Geckodriver: v0.11.1-win64
Platform: Windows 7 64bit
Selenium Java libraries: 3.0.1
The example test code causing these failures:
---
	import org.openqa.selenium.WebDriver;
	import org.openqa.selenium.firefox.FirefoxDriver;
	import org.openqa.selenium.remote.DesiredCapabilities;
	public class FirefoxTestBaidu {
		public static void main(String[] args) {
			System.setProperty("webdriver.firefox.driver", "C:\\Program Files (x86)\\Mozilla Firefox\\firefox.exe");
			System.setProperty("webdriver.gecko.driver", "C:\\Users\\book\\tool\\geckodriver.exe");
			DesiredCapabilities capabilities = DesiredCapabilities.firefox();
			capabilities.setCapability("marionette", true);
			WebDriver dr = new FirefoxDriver(capabilities);

			dr.get("http://www.baidu.com");
			try {

				Thread.sleep(300);

			} catch (InterruptedException e) {

				// TODO Auto-generated catch block

				e.printStackTrace();

			}
			dr.quit();
		}
	}

---
 In case of failures (approximately 100% of test runs) ,the Firefox prompts an error dialog and error is shown in geckodriver log:

![image](https://cloud.githubusercontent.com/assets/8800871/21964151/a84a5004-db81-11e6-90f0-a59c2d4f29f2.png)

[Child 7244] ###!!! ABORT: Aborting on channel error.: file c:/builds/moz2_slave/m-rel-w32-00000000000000000000/build/src/ipc/glue/MessageChannel.cpp, line 2056
[NPAPI 1428] ###!!! ABORT: Aborting on channel error.: file c:/builds/moz2_slave/m-rel-w32-00000000000000000000/build/src/ipc/glue/MessageChannel.cpp, line 2056
Jan 16, 2017 12:20:37 AM org.openqa.selenium.os.UnixProcess destroy
SEVERE: Unable to kill process with PID 11820

Inspired by  @juperala ,
After comment:dr.quit(); 
The example test code running without failure

![image](https://cloud.githubusercontent.com/assets/8800871/21964210/a1a69202-db82-11e6-8b09-f8591dc38829.png)
