### ISSUE TITLE
Firefox is not launched (FF CI version)

### ISSUE THREAD

**Issue by drasticdreamer** [mozilla/geckodriver#1320] opened 2018-07-03 18:26 UTC
## System

Version: geckodriver 0.21.0
Platform: Windows 7 32 bit
Firefox: 60.0.2
Selenium: Selenium 3.12.0

## Testcase

I mistakenly closed the https://github.com/mozilla/geckodriver/issues/1297 thread. I have extracted and tried again. Please see the attached trace log created with the FF CI version.
[NewTrace.txt](https://github.com/mozilla/geckodriver/files/2160591/NewTrace.txt)

Thanks,
-D

**Comment by whimboo** [comment] 2018-07-04 07:20
Dupe of issue #1297.

**Closed by whimboo** 2018-07-04 07:20 UTC
