### ISSUE TITLE
Unable to launch firefox48 with custom profile using geckodriver

### ISSUE THREAD

**Issue by furqanmlk** [mozilla/geckodriver#194] opened 2016-08-24 17:49 UTC
## Expected Behavior -

geckodriver should be able to launch Firefox48 with custom profile
## Step to reproduce -

01: Zip default profile folder

02: Getting default profile location
string prof = (@"...\AppData\Roaming\Mozilla\Firefox\Profiles\6uqm9vnl.default.zip");

03: Converting to base64-encoded string
var prof1 = System.Text.Encoding.UTF8.GetBytes(prof);
var prof2 = System.Convert.ToBase64String(prof1);
FirefoxProfile profile = new FirefoxProfile(prof2);

04: Initializing FirefoxDriver
new FirefoxDriver(profile);
## Actual Behavior -

geckodriver still launches new profile

**Comment by AutomatedTester** [comment] 2016-09-15 23:00
Have you tried this using FirefoxOptions?

**Comment by krmahadevan** [comment] 2016-09-25 15:27
@AutomatedTester Is `FirefoxOptions` a .NET specific class ? I can't seem to find it in the Java bindings. I also don't seem to find a code path within the Java bindings of FirefoxDriver which makes use of a firefox profile that was passed via the constructor in spawning the browser.

**Comment by andreastt** [comment] 2016-09-25 22:12
I’m interpreting this as that the .NET bindings do not assign the profile to the correct capability when speaking to Marionette. Perhaps it does not do the conformance negotiation or perhaps there is an unrelated bug.

Furthermore, `FirefoxOptions` is a new concept (and unrelated to this issue) which will be introduced in the next version of geckodriver. It’s an attempt from our side to create some level of similarity between chromedriver and geckodriver.

**Comment by AutomatedTester** [comment] 2016-09-26 00:06
@andreastt what you are talking about is tangental to what I mentioned. FirefoxOptions has been around for a while, just adding it to a specific capability is new.

@krmahadevan .NET, Ruby and Python definitely have it. I thought Java had it. Please raise a bug on Selenium for it to be added.

**Comment by andreastt** [comment] 2016-09-26 10:13
The FirefoxOptions helper utility class was only added fairly recently to the Python and Ruby bindings, but it’s not the cause of the problem described initially in this bug.

**Comment by andreastt** [comment] 2016-12-16 01:48
Closing this as we are unable to reproduce any longer. If you disagree, please add enough information so that we can reproduce the issue.

**Closed by andreastt** 2016-12-16 01:48 UTC
