### ISSUE TITLE
v0.26.0 exception on start: System.InvalidOperationException: Unable to find a matching set of capabilities (SessionNotCreated)

### ISSUE THREAD

**Issue by hheexx** [mozilla/geckodriver#1631] opened 2019-10-12 00:09 UTC
## System

* Version: 0.26
* Platform:  Windows 10
* Firefox: 70b14
* Selenium: .NET 3.141

## Testcase

Replaced 0.25 with 0.26.
Exception thrown on Firefox start.

## Stacktrace

System.InvalidOperationException: Unable to find a matching set of capabilities (SessionNotCreated)

**Comment by andreastt** [comment] 2019-10-12 00:22
Could you please attach a [trace-level log] from geckodriver? Read more about reporting actionable bugs in our [contribution guidelines].

[trace-level log]: https://firefox-source-docs.mozilla.org/testing/geckodriver/TraceLogs.html
[contribution guidelines]: https://firefox-source-docs.mozilla.org/testing/geckodriver/Bugs.html

**Comment by hheexx** [comment] 2019-10-12 00:42
Problem is between x32 and x64.
x64 works but x32 throws this exception.

**Comment by whimboo** [comment] 2019-10-12 09:24
If geckodriver doesn't start then it is issue #1617, which we haven't fixed yet. Otherwise I assume that you are not specifying any path to Firefox, and used the win32 geckodriver binary on a Windows 10 64 bit system? I just uploaded the win64 geckodriver binary, and it should all work now.

@hheexx, can you please confirm?

**Comment by hheexx** [comment] 2019-10-12 18:08
Works with 64, that was a problem....

**Comment by whimboo** [comment] 2019-10-12 18:43
Great. So it's a dupe of issue #1630.

**Closed by whimboo** 2019-10-12 18:43 UTC
Labels: geckodriver, waiting for reporter feedback
