### ISSUE TITLE
Geckodriver giving error with status code -7 in Kali linux in Android

### ISSUE THREAD

**Issue by Code-With-Alex** [mozilla/geckodriver#1970] opened 2021-12-15 15:21 UTC
## System
 I'm using geckodriver in a python program using webdriver on a Kali Linux installed on Android 11. it is giving the following error-
## Error
-----------------------------------------------------------------------------
Traceback (most recent call last):
  File "/root/a.py", line 9, in <module>
    driver = webdriver.Firefox()
  File "/usr/local/lib/python3.9/dist-packages/selenium/webdriver/firefox/webdriver.py", line 174, in __init__
    self.service.start()
  File "/usr/local/lib/python3.9/dist-packages/selenium/webdriver/common/service.py", line 98, in start
    self.assert_process_still_running()
  File "/usr/local/lib/python3.9/dist-packages/selenium/webdriver/common/service.py", line 110, in assert_process_still_running
    raise WebDriverException(
selenium.common.exceptions.WebDriverException: Message: Service geckodriver unexpectedly exited. Status code was: -7
------------------------------------------------------------------------------

* Version: 0.30.0
* Platform: Kali Linux on Android 11 (aarch64 GNU/Linux)
* Firefox: 78.14.Oesr(64-bit)
* Selenium: 4.1.0

## Python code-
from selenium import webdriver
driver = webdriver.Firefox()
driver.get("http://www.python.org")
----------------------------------------------------------------------

**Comment by whimboo** [comment] 2021-12-16 07:36
This is a duplicate of issue #1969. If you can reproduce and provide the requested information on that other ticket I'm happy to reopen #1969.

**Closed by whimboo** 2021-12-16 07:36 UTC

**Comment by Code-With-Alex** [comment] 2021-12-22 02:46
I had not seen any such issue previously..
Its unresolved till now if u can't resolve it then don't close it

**Comment by Xehia** [comment] 2022-10-23 22:59
I have the same issue with Ubuntu in Android, still no solutions?
