### ISSUE TITLE
contextmenu event not triggered after dispatching pointerdown

### ISSUE THREAD

**Issue by muthu90ec** [mozilla/geckodriver#772] opened 2017-06-06 21:40 UTC
In order to help us efficiently investigate your issue, please provide the following information:

## Platform and application details
* Platform: Win/OSX/Linux
* Selenium: 3.4.0

## Steps to reproduce
		new Actions(getDefaultBrowserDriver()).moveToElement(el)
				.contextClick(el).build().perform();
This should trigger contextmenu event

- [ ] Reproducable testcase:
    document.getElementById("menu1").addEventListener('contextmenu',
            function(ev) {
                ev.preventDefault();
                document.getElementById('output').innerHTML = 'success';
                return false;
            }, false);
    document.getElementById("menu1").addEventListener('contextmenu',
            function(ev) {
                ev.preventDefault();
                var str = "";
                for (property in ev) {
                      str += (property + '=' + ev[property] + "<br/>");
                }
                document.getElementById('events').innerHTML = str;
                return false;
            }, false);

- [ ] A trace level log:
"{
    \"actions\": [
        {
            \"actions\": [
                {
                    \"duration\": 100,
                    \"origin\": {
                        \"element-6066-11e4-a52e-4f735466cecf\": \"257ed5e5-fe06-4061-aeff-275842cf9a5e\"
                    },
                    \"type\": \"pointerMove\",
                    \"x\": 0,
                    \"y\": 0
                },
                {
                    \"duration\": 100,
                    \"origin\": {
                        \"element-6066-11e4-a52e-4f735466cecf\": \"257ed5e5-fe06-4061-aeff-275842cf9a5e\"
                    },
                    \"type\": \"pointerMove\",
                    \"x\": 0,
                    \"y\": 0
                },
                {
                    \"button\": 2,
                    \"type\": \"pointerDown\"
                },
                {
                    \"button\": 2,
                    \"type\": \"pointerUp\"
                }
            ],
            \"id\": \"default mouse\",
            \"parameters\": {
                \"pointerType\": \"mouse\"
            },
            \"type\": \"pointer\"
        }
    ]
}"

The Geckodriver is sending the pointerevents to marionette, Marionette also dispatches the mousedown event. Because I could verify event.button ===2 on capturing the mousedown event, But this does not generate the 'contextmenu' event at all, which is concerning.

**Comment by andreastt** [comment] 2017-06-07 10:39
I suspect this was fixed by https://bugzilla.mozilla.org/show_bug.cgi?id=1367430.

**Comment by muthu90ec** [comment] 2017-06-07 13:05
I went through https://bugzilla.mozilla.org/show_bug.cgi?id=1367430

The above link you forwarded was for issue ctrl + click should result in MouseEvent, But the issue I mentioned is different, the mouse pointerDown button 2 is not generating a contextmenu event?

**Comment by andreastt** [comment] 2017-06-07 13:10
@muthu90ec Can you explain how it is different? My thinking was that maintaining keyboard modifier state when emitting the mouse event would cause the `contextmenu` event to fire.

Maybe @mjzffr can provide some insight. It is possible we need to fire that event explicitly if testing/marionette/event.js does not handle it for us.

**Comment by muthu90ec** [comment] 2017-06-07 15:03
To clarify this I tried 	new Actions(getDefaultBrowserDriver()).moveToElement(el)
			.contextClick(el).build().perform();
on the latest firefox nightly
https://ftp.mozilla.org/pub/firefox/nightly/latest-mozilla-central/
and did not see the 'contextmenu' event fire on pointerdown button 2

**Comment by mjzffr** [comment] 2017-06-07 15:21
I filed https://bugzilla.mozilla.org/show_bug.cgi?id=1370403 a couple of days ago -- I think we need to take care of contextmenu ourselves in event.js

**Comment by andreastt** [comment] 2017-06-07 16:25
Right, I’ll reopen this.

**Comment by muthu90ec** [comment] 2017-06-07 17:28
Thanks

**Comment by jimevans** [comment] 2017-06-10 10:20
To this outsider, this report sounds very similar, symptom-wise to #660.

**Comment by andreastt** [comment] 2017-06-10 23:40
Closing as duplicate of https://github.com/mozilla/geckodriver/issues/660, which has a better description.

**Closed by andreastt** 2017-06-10 23:40 UTC
Labels: marionette
