### ISSUE TITLE
Unable to view shockwave flash plugin in the Selenium launches firefox 57

### ISSUE THREAD

**Issue by michealarun** [mozilla/geckodriver#1102] opened 2017-12-15 11:09 UTC
## System
* Version: 
* Platform: 
* Firefox: 
* Selenium:

**Comment by michealarun** [comment] 2017-12-15 11:11
Can anyone reply to this if you find any solution?

**Comment by andreastt** [comment] 2017-12-16 14:52
Duplicate of https://github.com/mozilla/geckodriver/issues/1103.

**Closed by andreastt** 2017-12-16 14:52 UTC
