### ISSUE TITLE
selenium.common.exceptions.WebDriverException: Message: Can not connect to the Service geckodriver

### ISSUE THREAD

**Issue by ShaolongHu** [mozilla/geckodriver#270] opened 2016-10-10 14:34 UTC
1. selenium 3.0.0b3
2. geckodriver-v0.11.1-linux64.tar.gz       unpacked to /bin /usr/bin
3. firefox 48.02
4. code:

from selenium import webdriver
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

caps = DesiredCapabilities.FIREFOX
caps["marionette"] = True
caps["binary"] = "/usr/bin/firefox"
driver = webdriver.Firefox(capabilities=caps)

4. running:

Traceback (most recent call last):
  File "test.py", line 3, in <module>
    browser = webdriver.Firefox()
  File "/usr/lib/python2.7/site-packages/selenium/webdriver/firefox/webdriver.py", line 68, in __init__
    self.service.start()
  File "/usr/lib/python2.7/site-packages/selenium/webdriver/common/service.py", line 92, in start
    raise WebDriverException("Can not connect to the Service %s" % self.path)
selenium.common.exceptions.WebDriverException: Message: Can not connect to the Service geckodriver

Any idea?

Bests,

**Comment by andreastt** [comment] 2016-10-10 14:46
Can you please paste the contents of the _geckodriver.log_ file from your current working directory?

**Comment by ShaolongHu** [comment] 2016-10-10 14:51
@andreastt 

# cat geckodriver.log 
1476111009361	geckodriver	INFO	Listening on 127.0.0.1:58451

**Comment by andreastt** [comment] 2016-10-10 15:09
I’m not able to reproduce this with selenium-3.0.0b3 off pip. It looks like geckodriver is starting successfully on the port the Python client is requesting it to, and that the client subsequently fails to connect on that port.

**Comment by AutomatedTester** [comment] 2016-10-11 21:34
linking https://github.com/SeleniumHQ/selenium/issues/2903

**Comment by andreastt** [comment] 2016-10-15 12:56
Closing this as I cannot reproduce.

**Closed by andreastt** 2016-10-15 12:56 UTC
Labels: selenium

**Comment by rsuciu-gsg** [comment] 2016-11-03 13:28
Reproducing for my team, using selenium 3.0.1 on Mac OS Sierra.
Tests fail to start with error:
Traceback (most recent call last):
File "test.py", line 4, in <module>
driver = webdriver.Firefox()
File "/Users/sbhide/Desktop/virtualenv/lib/python3.5/site-packages/selenium/webdriver/firefox/webdriver.py", line 135, in init
self.service.start()
File "/Users/username/Desktop/virtualenv/lib/python3.5/site-packages/selenium/webdriver/common/service.py", line 92, in start
raise WebDriverException("Can not connect to the Service %s" % self.path)
selenium.common.exceptions.WebDriverException: Message: Can not connect to the Service geckodriver

Any idea on what the problem might be? Please note that the same happens for chromedriver.

**Comment by jgraham** [comment] 2016-11-03 14:09
If it's happening for multiple drivers it sounds like a selenium issue.

**Comment by rsuciu-gsg** [comment] 2016-11-03 14:27
I'll report this for Selenium, thank you.

**Comment by dongxiexidian** [comment] 2016-12-06 06:01
same problem
python 2.7.12
selenium up-to-date
geckodriver path:/usr/local/bin/geckodriver
geckodriver.log - INFO Listening on 127.0.0.1:39921

**Comment by andreastt** [comment] 2016-12-09 02:02
@dongxiexidian If you had read the actual comments on this issue before commenting, you would have realised this is a Selenium issue.

**Comment by xxdd10** [comment] 2017-10-24 09:06
windows7 64
python 3.6
selenium 3.6
geckodriver 0.9 

I resolved it . 
remove the comment on hosts file
C:\Windows\System32\drivers\etc\hosts
127.0.0.1       localhost

^0^
