### ISSUE TITLE
Take Screenshot captures current frame instead of parent document

### ISSUE THREAD

**Issue by hariharanravichandran** [mozilla/geckodriver#1385] opened 2018-09-24 08:28 UTC
## System

* Version: 0.22.0
* Platform: Win7
* Firefox: 60.0.2
* Selenium: 3.12

## Testcase
Our Web application pages have many frames in it. Source of frames is some other jsp or html.
When we run our test in firefox, driver is taking screenshot of the particular frame instead of taking the screenshot of the browser window. And we face one more issue. When we do some action in a frame, Popup alert will come. Driver is not handling those popups. Even if it handles those popups, focus of webdriver is not switched back the frame in the webpage.

**Comment by andreastt** [comment] 2018-09-24 12:28
Let’s limit each issue to one problem. [According to the specification](https://w3c.github.io/webdriver/#take-screenshot), it does indeed sound like a bug that it takes a screenshot of the current frame. It should be taking the screenshot of the current top-level browsing context, which is the parent document. I’ve filed https://bugzilla.mozilla.org/show_bug.cgi?id=1493650 about this.

Regarding the second popup issue, please file a separate bug with reproducible steps.

**Comment by whimboo** [comment] 2019-01-16 14:35
Dupe of issue #936.

**Closed by whimboo** 2019-01-16 14:35 UTC
Labels: marionette
