### ISSUE TITLE
Firefox busted due to invalid binary path

### ISSUE THREAD

**Issue by vick1245** [mozilla/geckodriver#1082] opened 2017-11-29 15:55 UTC
## System
* Version: 0.19
* Platform: windows 764 bit
* Firefox: 52.2.0
* Selenium: 3.7.1
* Eclipse: Neon .3 release(4.6.3)
*JDK:1.9

-->

## Stacktrace

1511969010622	geckodriver	INFO	Listening on 127.0.0.1:38957
1511969012745	geckodriver::marionette	INFO	Starting browser \\?\C:\Program Files\Mozilla Firefox\firefox.exe with args ["-marionette"]
1511969016999	addons.manager	ERROR	startup failed: [Exception... "Component returned failure code: 0x80070057 (NS_ERROR_ILLEGAL_VALUE) [nsIFile.create]"  nsresult: "0x80070057 (NS_ERROR_ILLEGAL_VALUE)"  location: "JS frame :: resource://gre/modules/FileUtils.jsm :: FileUtils_getDir :: line 70"  data: no] Stack trace: FileUtils_getDir()@resource://gre/modules/FileUtils.jsm:70 < FileUtils_getFile()@resource://gre/modules/FileUtils.jsm:42 < AddonManagerInternal.validateBlocklist()@resource://gre/modules/AddonManager.jsm:700 < AddonManagerInternal.startup()@resource://gre/modules/AddonManager.jsm:870 < this.AddonManagerPrivate.startup()@resource://gre/modules/AddonManager.jsm:3033 < amManager.prototype.observe()@resource://gre/components/addonManager.js:65
JavaScript error: resource://gre/modules/AddonManager.jsm, line 1677: NS_ERROR_NOT_INITIALIZED: AddonManager is not initialized
1511969020347	Marionette	INFO	Listening on port 2281
1511969020913	Marionette	WARN	TLS certificate errors will be ignored for this session
JavaScript error: resource://gre/modules/AddonManager.jsm, line 2585: NS_ERROR_NOT_INITIALIZED: AddonManager is not initialized
Nov 29, 2017 8:53:47 PM org.openqa.selenium.remote.ProtocolHandshake createSession
INFO: Detected dialect: W3C
JavaScript error: resource://gre/modules/FileUtils.jsm, line 70: NS_ERROR_ILLEGAL_VALUE: Component returned failure code: 0x80070057 (NS_ERROR_ILLEGAL_VALUE) [nsIFile.create]
1511969085611	addons.productaddons	WARN	Failed downloading XML, status: 0, reason: error
1511969085900	addons.productaddons	WARN	Failed downloading via XHR, status: 0, reason: error
1511969086136	addons.productaddons	WARN	Failed downloading via XHR, status: 0, reason: error
JavaScript error: resource://app/modules/WindowsJumpLists.jsm, line 403: NS_ERROR_FILE_NOT_FOUND: Component returned failure code: 0x80520012 (NS_ERROR_FILE_NOT_FOUND) [nsIJumpListShortcut.app]
JavaScript error: resource://app/modules/WindowsJumpLists.jsm, line 403: NS_ERROR_FILE_NOT_FOUND: Component returned failure code: 0x80520012 (NS_ERROR_FILE_NOT_FOUND) [nsIJumpListShortcut.app]
Exception in thread "main" org.openqa.selenium.TimeoutException: Error loading page, timed out (onDOMContentLoaded)
Build info: version: '3.7.1', revision: '8a0099a', time: '2017-11-06T21:07:36.161Z'
System info: host: 'VIVEK-PC', ip: '10.104.45.214', os.name: 'Windows 7', os.arch: 'amd64', os.version: '6.1', java.version: '1.8.0_101'
Driver info: org.openqa.selenium.firefox.FirefoxDriver
Capabilities {acceptInsecureCerts: true, browserName: firefox, browserVersion: 52.5.0, javascriptEnabled: true, moz:accessibilityChecks: false, moz:processID: 7748, moz:profile: C:\Users\Vivek\AppData\Loca..., pageLoadStrategy: normal, platform: XP, platformName: XP, platformVersion: 6.1, rotatable: false, specificationLevel: 0, timeouts: {implicit: 0, page load: 300000, script: 30000}}
Session ID: 7c97347b-3e89-415c-ba5a-f8dc4b123b99
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
	at java.lang.reflect.Constructor.newInstance(Unknown Source)
	at org.openqa.selenium.remote.http.W3CHttpResponseCodec.createException(W3CHttpResponseCodec.java:187)
	at org.openqa.selenium.remote.http.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:122)
	at org.openqa.selenium.remote.http.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:49)
	at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:164)
	at org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:83)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:600)
	at org.openqa.selenium.remote.RemoteWebDriver.get(RemoteWebDriver.java:324)
	at com.Libraries.FirefoxProfile.main(FirefoxProfile.java:12)

**Comment by curtisy1** [comment] 2017-11-29 16:23
52.2.0
This is most likely the problem, since official supported versions are Firefox 55 and above. Consider to update your Firefox if possible.

**Comment by vick1245** [comment] 2017-11-29 16:38
Mozilla ESR ====> browser 64 bit

**Comment by curtisy1** [comment] 2017-11-29 20:35
@vick1245 Sorry, but I fail to see how the 64-bit ESR release is relevant here. The [release notes]() clearly state that ** with geckodriver v0.19.0 the following versions are recommended: Firefox 55.0 (and greater)**. Since you're on a version below 55.0, the cause is most likely the Firefox version you use

Be it an ESR or not, is there any reason that prevents you from updating?

**Comment by whimboo** [comment] 2017-11-29 20:39
This is not geckodriver 0.19 which you are using here but at maximum 0.16. I see this because the failure as it can be seen in the tracelog has been fixed with the 0.17 release, and since 0.18 geckodriver prints out its version.

This is a dupe of issue #702.

**Closed by whimboo** 2017-11-29 20:39 UTC
