### ISSUE TITLE
Getting the text of a non-displayed element returns ""

### ISSUE THREAD

**Issue by dom96** [mozilla/geckodriver#1277] opened 2018-05-19 12:14 UTC
## System

* Version: 0.20.1
* Platform: macOS
* Firefox: 60.0.1
* Selenium: Not using Selenium, custom client

## Testcase

Sorry I don't have a test case for this.

## Stacktrace

No stacktrace.

## Trace-level log

```
geckodriver: 1526731626132	webdriver::server	DEBUG	-> POST /session/379d2aae-d62f-1f4c-b913-7688f850de05/element {"using":"css selector","value":"#main-navbar .menu-right div.tile-content"}
geckodriver: 1526731626139	webdriver::server	DEBUG	<- 200 OK {"value":{"element-6066-11e4-a52e-4f735466cecf":"323b5853-080d-b646-a0d4-ec51bfc641c4"}}
geckodriver: 1526731626154	webdriver::server	DEBUG	-> GET /session/379d2aae-d62f-1f4c-b913-7688f850de05/element/323b5853-080d-b646-a0d4-ec51bfc641c4/text 
geckodriver: 1526731626161	webdriver::server	DEBUG	<- 200 OK {"value":""}
geckodriver: 1526731627170	webdriver::server	DEBUG	-> POST /session/379d2aae-d62f-1f4c-b913-7688f850de05/element {"using":"css selector","value":"#main-navbar .menu-right div.tile-content"}
geckodriver: 1526731627173	webdriver::server	DEBUG	<- 200 OK {"value":{"element-6066-11e4-a52e-4f735466cecf":"323b5853-080d-b646-a0d4-ec51bfc641c4"}}
geckodriver: 1526731627175	webdriver::server	DEBUG	-> GET /session/379d2aae-d62f-1f4c-b913-7688f850de05/element/323b5853-080d-b646-a0d4-ec51bfc641c4/text 
geckodriver: 1526731627180	webdriver::server	DEBUG	<- 200 OK {"value":"admin"}
geckodriver: 1526731627183	webdriver::server	DEBUG	-> DELETE /session/379d2aae-d62f-1f4c-b913-7688f850de05 
geckodriver: 1526731627277	webdriver::server	DEBUG	Deleting session
geckodriver: *** UTM:SVC TimerManager:registerTimer called after profile-before-change notification. Ignoring timer registration for id: telemetry_modules_ping
geckodriver: 1526731627837	geckodriver::marionette	DEBUG	Browser process stopped with exit status exit code: 0
geckodriver: 1526731627858	webdriver::server	DEBUG	<- 200 OK {"value": {}}
```

----

This is possibly a question rather than a bug report. I am unsure what the expected behaviour here is, but the current behaviour surprised me. If this is expected then feel free to close.

I've requested the text of an element that is inside a hidden ``<ul>``. Geckodriver returns "" for this request until the ``<ul>`` ``display`` property is no longer "none". That's what the trace shows (I requested the text every second and then manually caused the ``<ul>`` to become visible in this instance).

**Comment by andreastt** [comment] 2018-05-19 15:37
[According to the specification](https://w3c.github.io/webdriver/#dfn-get-element-text), this appears to be the correct behaviour because it is relying on the [`bot.dom.getVisibleText`](https://w3c.github.io/webdriver/#dfn-bot-dom-getvisibletext) atom from Selenium without running any visibility checks first.

**Comment by whimboo** [comment] 2018-05-24 19:27
I think that https://output.jsbin.com/zazudazawe/2 demonstrates that the text is always available. The question is why we call the atom `bot.dom.getVisibleText` text. @shs96c mind having a look?

**Comment by AutomatedTester** [comment] 2018-06-12 21:00
As mentioned https://github.com/mozilla/geckodriver/issues/1277#issuecomment-390412963 this is by design so closing

**Closed by AutomatedTester** 2018-06-12 21:00 UTC
