### ISSUE TITLE
Release build 0.31.0 not available on github -- was it removed?

### ISSUE THREAD

**Issue by bopolissimus** [mozilla/geckodriver#2012] opened 2022-05-05 00:27 UTC
## System

* Version: 0.31.0
* Platform: github repository
* Firefox: not relevant
* Selenium: not relevant

## Trace-level log

WebDriverManager (https://github.com/bonigarcia/webdrivermanager) refers to geckodriver 0.31.0.  So does this geckodriver issue (implying that 0.31.0 existed in the past):

https://github.com/mozilla/geckodriver/issues/2010

However, as of right now (00:25:18 UTC Thursday, 5 May 2022)

  https://github.com/mozilla/geckodriver

and 

  https://api.github.com/repos/mozilla/geckodriver/releases

both show the latest version as 0.30.0.

Was 0.31.0 removed by mistake? or was it purposeful (and I should ask webdrivermanager maintainer to go back to using 0.30.0)?

**Comment by bopolissimus** [comment] 2022-05-05 00:37
And https://github.com/mozilla/geckodriver/releases/tag/v0.31.0 does exist. Just not referenced or available from the api or main github geckodriver page.

**Comment by whimboo** [comment] 2022-05-05 06:26
It's a dupe of issue #2009.

**Closed by whimboo** 2022-05-05 06:26 UTC
