### ISSUE TITLE
0.15.0 with selenium 3.2.0 and firefox 52.0 (32-bit) windows not working well

### ISSUE THREAD

**Issue by jpschewe** [mozilla/geckodriver#524] opened 2017-03-09 15:20 UTC
In order to help us efficiently investigate your issue, please provide the following information:

## Firefox Version
From the "About" dialog.
52.0 (32-bit) 
## Platform
windows

## Steps to reproduce -
My tests work fine with geckodriver 0.14.0 and selenium 3.0.1.
I also tested with geckodriver 0.14.0 and selenium 3.2.0 and found no problems.

Below are the error messages that I receive when using geckodriver 0.15.0 with selenium 3.2.0. What other debugging information can I get for you to help debug this issue?
```
org.openqa.selenium.SessionNotCreatedException: Unable to create new remote session. desired capabilities = Capabilities [{marionette=true, firefoxOptions=org.openqa.selenium.firefox.FirefoxOptions@5e7cd6cc, browserName=firefox, moz:firefoxOptions=org.openqa.selenium.firefox.FirefoxOptions@5e7cd6cc, version=, platform=ANY}], required capabilities = Capabilities [{}]
Build info: version: 'unknown', revision: '1969d75', time: '2016-10-18 09:43:45 -0700'
System info: host: 'fll-build', ip: '192.168.42.15', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_112'
Driver info: driver.version: FirefoxDriver
	at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:91)
	at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:141)
	at org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:82)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:601)
	at org.openqa.selenium.remote.RemoteWebDriver.startSession(RemoteWebDriver.java:241)
	at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:128)
	at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:259)
	at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:247)
	at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:242)
	at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:238)
	at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:127)
```

**Comment by jgraham** [comment] 2017-03-09 15:55
You need to upgrade to Selenium 3.3 (it is released but not listed except on the GitHub page)

**Comment by jpschewe** [comment] 2017-03-09 16:06
Which github page? All I see is 3.1.0: https://github.com/SeleniumHQ/selenium/releases

**Comment by jgraham** [comment] 2017-03-09 16:16
https://github.com/SeleniumHQ/selenium/releases/tag/selenium-3.3.0

For some reason it didn't get added to releases.

**Comment by jpschewe** [comment] 2017-03-09 17:08
Hmm, I don't see a built release of that anywhere, so I'll need to stick with geckodriver 0.14.0 until selenium 3.3.0 is officially released. Thank you for the  information.

**Comment by andreastt** [comment] 2017-03-09 21:43
Duplicate of https://github.com/mozilla/geckodriver/issues/523.

**Closed by andreastt** 2017-03-09 21:43 UTC

**Comment by jpschewe** [comment] 2017-03-19 01:09
I just tried selenium 3.3.0 with geckodriver 0.15.0 and it still failed.
http://mtu.net/jenkins/view/FLL-SW/job/fll-sw-feature-branches/1353/testReport/junit/fll.web/FullTournamentTest/testFullTournament/

**Comment by andreastt** [comment] 2017-03-23 00:09
Locking.
