### ISSUE TITLE
‘invalid cookie domain’ error is missing from Marionette’s error lookup

### ISSUE THREAD

**Issue by uscengineer** [mozilla/geckodriver#782] opened 2017-06-12 23:03 UTC
* Platform: OSX 10.12.5
* Firefox: 53.0.3
* Selenium: 3.4.0

Our site currently uses .top.level.domain for the session cookie domain. However this throws an error in firefox with protractor: 
`JavascriptError: SyntaxError: identifier starts immediately after numeric literal`

If I remove the dot it will insert the cookie but it leads to odd behavior since our site is expecting the dot.  This also works as expected on chrome. It would be nice to be able to use firefox for our automated tests.

**Comment by andreastt** [comment] 2017-06-13 14:26
Can you please include a trace-level log from geckodriver to help us diagnose this problem?

I’ve recently done some work on the Marionette cookie service, and I should say that it’s not entirely clear from the WebDriver specification exactly how cookies should work.

**Comment by uscengineer** [comment] 2017-06-13 18:38
Is this what you are looking for?

`11:36:31.731 INFO - Executing: [add cookie: _session_id=BAh7CEkiD3Nlc3Npb25faWQGOgZFVEkiJTExOGMyNDUxYzM5ODQxMWE0ZDA2ODU4NzkyZWFlMjZiBjsAVEkiGnBlcnNpc3RlbnRfc2Vzc2lvbl9pZAY7AEZJIik3YzYwZTIyMC04MGIwLTRlYWEtOTk5Ni0xOWEyYTI3ZTE5MTEGOwBGSSIZd2FyZGVuLnVzZXIudXNlci5rZXkGOwBUWwhJIglVc2VyBjsARlsGaQPTdJRJIiIkMmEkMTAkOVJFY3M5YjhVS21tRzdrcG1lSy5tTwY7AFQ%3D--d381f27f17d3fa3784dbdcdcf4a77821bc52aa22; path=/; domain=.my.example.com])
*************************
A coding exception was thrown and uncaught in a Task.

Full message: ReferenceError: InvalidCookieDomainError is not defined
Full stack: add@chrome://marionette/content/cookies.js:80:7
addCookie@chrome://marionette/content/listener.js:1595:3
dispatch/</req<@chrome://marionette/content/listener.js:367:22
TaskImpl_run@resource://gre/modules/Task.jsm:319:42
TaskImpl@resource://gre/modules/Task.jsm:277:3
asyncFunction@resource://gre/modules/Task.jsm:252:14
Task_spawn@resource://gre/modules/Task.jsm:166:12
dispatch/<@chrome://marionette/content/listener.js:363:15

*************************
11:36:31.749 WARN - Exception thrown
org.openqa.selenium.WebDriverException: ReferenceError: InvalidCookieDomainError is not defined
Build info: version: '3.4.0', revision: 'unknown', time: 'unknown'
System info: host: 'THC1036.local', ip: '10.8.64.96', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.12.5', java.version: '1.8.0_121'
Driver info: org.openqa.selenium.firefox.FirefoxDriver
Capabilities [{moz:profile=/var/folders/73/0k0qxvcj44jgp12yslkbhp6h0000gp/T/rust_mozprofile.R1WuKVWuzOqh, rotatable=false, timeouts={implicit=0.0, pageLoad=300000.0, script=30000.0}, pageLoadStrategy=normal, platform=ANY, specificationLevel=0.0, moz:accessibilityChecks=false, acceptInsecureCerts=false, browserVersion=53.0.3, platformVersion=16.6.0, moz:processID=56570.0, browserName=firefox, javascriptEnabled=true, platformName=darwin}]
Session ID: 2dfbc335-f2a5-4a40-996f-0f6f737f5f08
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.openqa.selenium.remote.http.W3CHttpResponseCodec.createException(W3CHttpResponseCodec.java:150)
	at org.openqa.selenium.remote.http.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:115)
	at org.openqa.selenium.remote.http.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:45)
	at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:164)
	at org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:82)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:637)
	at org.openqa.selenium.remote.RemoteWebDriver$RemoteWebDriverOptions.addCookie(RemoteWebDriver.java:764)
	at org.openqa.selenium.support.events.EventFiringWebDriver$EventFiringOptions.addCookie(EventFiringWebDriver.java:514)
	at org.openqa.selenium.remote.server.handler.AddCookie.call(AddCookie.java:43)
	at org.openqa.selenium.remote.server.handler.AddCookie.call(AddCookie.java:31)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at org.openqa.selenium.remote.server.DefaultSession$1.run(DefaultSession.java:176)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
11:36:31.749 WARN - Exception: ReferenceError: InvalidCookieDomainError is not defined
Build info: version: '3.4.0', revision: 'unknown', time: 'unknown'
System info: host: 'THC1036.local', ip: '10.8.64.96', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.12.5', java.version: '1.8.0_121'
Driver info: org.openqa.selenium.firefox.FirefoxDriver
Capabilities [{moz:profile=/var/folders/73/0k0qxvcj44jgp12yslkbhp6h0000gp/T/rust_mozprofile.R1WuKVWuzOqh, rotatable=false, timeouts={implicit=0.0, pageLoad=300000.0, script=30000.0}, pageLoadStrategy=normal, platform=ANY, specificationLevel=0.0, moz:accessibilityChecks=false, acceptInsecureCerts=false, browserVersion=53.0.3, platformVersion=16.6.0, moz:processID=56570.0, browserName=firefox, javascriptEnabled=true, platformName=darwin}]
Session ID: 2dfbc335-f2a5-4a40-996f-0f6f737f5f08
11:36:31.769 INFO - Executing: [delete session: deb6bf91-2674-48bd-be90-b429278fc300])
1497378991772	Marionette	INFO	New connections will no longer be accepted
11:36:31.892 INFO - Done: [delete session: deb6bf91-2674-48bd-be90-b429278fc300]
11:36:31.898 INFO - Executing: [new session: Capabilities [{gridlasticUser=, count=1, browserName=firefox, alwaysMatch={moz:firefoxOptions={log={level=trace}}}, video=, maxInstances=1, moz:firefoxOptions={}, version=, platform=WINDOWS, shardTestFiles=false, gridlasticKey=}]])
11:36:31.899 INFO - Creating a new session for Capabilities [{gridlasticUser=, count=1, browserName=firefox, alwaysMatch={moz:firefoxOptions={log={level=trace}}}, video=, maxInstances=1, moz:firefoxOptions={}, version=, platform=WINDOWS, shardTestFiles=false, gridlasticKey=}]
1497378991910	geckodriver	INFO	Listening on 127.0.0.1:39461
1497378991976	geckodriver::marionette	INFO	Starting browser /Applications/Firefox.app/Contents/MacOS/firefox-bin with args ["-marionette"]
1497378993580	Marionette	INFO	Listening on port 52403
11:36:33.897 INFO - Detected dialect: W3C
11:36:33.900 INFO - Done: [new session: Capabilities [{gridlasticUser=, count=1, browserName=firefox, alwaysMatch={moz:firefoxOptions={log={level=trace}}}, video=, maxInstances=1, moz:firefoxOptions={}, version=, platform=WINDOWS, shardTestFiles=false, gridlasticKey=}]]
11:36:33.907 INFO - Executing: [take screenshot])
11:36:33.907 INFO - Executing: [script wait: 60000])
11:36:33.927 INFO - Done: [take screenshot]
11:36:33.931 INFO - Done: [script wait: 60000]
11:36:33.948 INFO - Executing: [delete session: 6cccdbf8-4cbc-4865-a5a6-2713e409ba8f])`

**Comment by andreastt** [comment] 2017-06-14 11:56
Yes, thanks, that helps.

It looks like `InvalidCookieDomainError` was implement only recently, and it is only available in Firefox 55 or greater, judging by https://bugzilla.mozilla.org/show_bug.cgi?id=1362990. Please retry with a more modern Firefox.

**Comment by uscengineer** [comment] 2017-06-14 19:48
@andreastt here is the error with Firefox 55

12:45:54.495 INFO - Executing: [add cookie: _session_id=BAh7CEkiD3Nlc3Npb25faWQGOgZFVEkiJWE2MThiN2Q4ODBlMTNjZDBlMzdiYjZjMWZhYzE2ZmQzBjsAVEkiGnBlcnNpc3RlbnRfc2Vzc2lvbl9pZAY7AEZJIik0ZThhNDVmZC0wNGE0LTQ2Y2MtYjJkMy00YTkwYzc1OThkNmMGOwBGSSIZd2FyZGVuLnVzZXIudXNlci5rZXkGOwBUWwhJIglVc2VyBjsARlsGaQMOdZRJIiIkMmEkMTAkNm1qbDBPaDRnL2ZEYXZqa1lDUXJGLgY7AFQ%3D--59d322e98c5072ce7bc855e9c8ba48e3ae67b8d9; path=/; domain=.my.domain.com])
JavaScript error: chrome://marionette/content/error.js, line 246: TypeError: Not of WebDriverError descent: invalid cookie domain
12:47:01.624 INFO - Executing: [delete session: dd15c5be-366e-44eb-b78b-716dcfd6a839])

**Comment by andreastt** [comment] 2017-06-15 12:32
I think I see the problem. The `[InvalidCookieDomainError](https://searchfox.org/mozilla-central/rev/c49a70b53f67dd5550eec8a08793805f2aca8d42/testing/marionette/error.js#330-335)` is not listed in the `STATUSES` map at the bottom of testing/marionette/error.js.

**Comment by andreastt** [comment] 2017-06-15 12:38
I patched this in https://bugzilla.mozilla.org/show_bug.cgi?id=1373218.

**Comment by whimboo** [comment] 2017-06-19 21:37
This is fixed now for Firefox 55 and 56.

**Closed by whimboo** 2017-06-19 21:37 UTC
Labels: marionette

**Comment by aldaris** [comment] 2017-09-19 11:28
Could this fix be the root cause of #823 ?
