### ISSUE TITLE
Working in debug mode but not in run mode

### ISSUE THREAD

**Issue by Sourabh25** [mozilla/geckodriver#384] opened 2016-12-07 18:23 UTC
If you are having an issue with GeckoDriver starting up, please make sure that your client bindings support using it.

## Meta -
OS:  Windows 8
Browser Version:  49

## Expected Behavior -
seleniumWait(30).until(ExpectedConditions.titleContains(strMsgToChk));
it working fine for chrome. it should work fine for Firefox too

## Actual Behavior -
 For firefox it is working only in debug mode but when I am excuting the entire script, this is failing.

GeckoDriver Logs:

Log from the Geckodriver
1481136775833	addons.productaddons	INFO	sending request to: https://aus5.mozilla.org/update/3/GMP/49.0.2/20161019084923/WINNT_x86-msvc-x64/en-US/release/Windows_NT%206.1.1.0%20(x64)/default/default/update.xml
1481136776491	addons.productaddons	INFO	Completed downloading document
1481136776776	addons.productaddons	INFO	downloadXHR File download. status=200
1481136776782	addons.productaddons	INFO	Downloaded file will be saved to C:\Users\mdk918\AppData\Local\Temp\tmpaddon-783adc
1481136778485	addons.productaddons	INFO	downloadXHR File download. status=200
1481136778491	addons.productaddons	INFO	Downloaded file will be saved to C:\Users\mdk918\AppData\Local\Temp\tmpaddon-b3a66e
1481136788073	addons.xpi	DEBUG	Calling bootstrap method shutdown on firebug@software.joehewitt.com version 2.0.17
1481136788074	addons.xpi	DEBUG	Calling bootstrap method shutdown on e10srollout@mozilla.org version 1.3
1481136788074	addons.xpi	DEBUG	Calling bootstrap method shutdown on firefox@getpocket.com version 1.0.4
1481136788075	addons.xpi	DEBUG	Calling bootstrap method shutdown on webcompat@mozilla.org version 1.0

**Comment by andreastt** [comment] 2016-12-08 20:31
What is ‘debug’ mode?

**Comment by Sourabh25** [comment] 2016-12-08 20:43
I refer debug mode as execute step by step manually. Like in eclipse we have two modes such as Run As and Debug As. So we we execute with breakpoints, the code is working fine but not when we are trying to execute the entire script in one go.
Please let me know if you need any more information. Thanks

**Comment by andreastt** [comment] 2016-12-08 21:52
OK. Without more information it’s not possible to reproduce this. I’m going to close this, but happy to reopen if enough relevant information proves this is a real bug.

**Closed by andreastt** 2016-12-08 21:52 UTC
Labels: waiting on info

**Comment by Sourabh25** [comment] 2016-12-08 23:06
what additional information you are looking for. Kindly update

**Comment by jgraham** [comment] 2016-12-08 23:11
A minimal HTML file containing just what's needed to see the problem, and a trace-level geckodriver log running against that HTML file.

**Comment by Sourabh25** [comment] 2016-12-08 23:18
blockquote, div.yahoo_quoted { margin-left: 0 !important; border-left:1px #715FFA solid !important; padding-left:1ex !important; background-color:white !important; } I think it won't be appropriate to share the HTML file. I will try to reproduce the issue in some other website.
Thanks,Sourabh


Sent from Yahoo Mail for iPhone


On Thursday, December 8, 2016, 6:11 PM, jgraham <notifications@github.com> wrote:


A minimal HTML file containing just what's needed to see the problem, and a trace-level geckodriver log running against that HTML file.

**Comment by jgraham** [comment] 2016-12-08 23:24
A minimal HTML file shouldn't be your production site, unless you can't reproduce it otherwise. For example if you were having problems changing the selection in a `<select>` element, a minimal HTML file might be:

    <select>
        <option>FAIL</option>
        <option>PASS</option>
    </select>

and nothing else. The log would show us what you tried to run against that file, and it would be clear what the expected behaviour is.

**Comment by Sourabh25** [comment] 2016-12-09 17:06
[myTestClass.txt](https://github.com/mozilla/geckodriver/files/642771/myTestClass.txt)
[SampleHTML.txt](https://github.com/mozilla/geckodriver/files/642772/SampleHTML.txt)

Please find attached my Test and HTML code. Please let me know if you find something. The script is getting hanged on  
wait.until(ExpectedConditions.titleContains("Capital One 360 - Login - Password"));

**Comment by Sourabh25** [comment] 2016-12-12 14:21
Provided the info needed. Could you please update on this. Thanks

**Comment by ramakrishnareddymandhala** [comment] 2018-01-04 09:32
I am also getting same error. What could you be the root cause.

**Comment by whimboo** [comment] 2018-01-04 10:45
What does hang mean? The instance of `WebDriverWait` is setup to return after 10s.

Also you still haven't added any trace level logs: https://firefox-source-docs.mozilla.org/testing/geckodriver/geckodriver/TraceLogs.html

**Comment by pxnQAD** [comment] 2019-07-01 18:37
Hi All,

I am also facing this issue. 

Environment: Pycharm with Python 3.7 using selenium 3.14.0

frame = self.driver.find_element_by_id("cke_10_contents").find_element_by_tag_name("iframe")

When debug mode it works perfectly.
When run mode, below error:
class 'selenium.common.exceptions.NoSuchElementException'
'no such element: Unable to locate element:
{"method":"id","selector":"cke_10_contents"}
(Session info: chrome=75.0.3770.100)
(Driver info: chromedriver=2.46.628402 (536cd7adbad73a3783fdc2cab92ab2ba7ec361e1),platform=Windows NT 10.0.17134 x86_64)',None, None)

**Comment by whimboo** [comment] 2019-07-02 12:19
@pxnQAD, this is the wrong bug tracker! You are using chromedriver and as such you should report this to Google.
