### ISSUE TITLE
v0.26 binary is broken on alpine linux

### ISSUE THREAD

**Issue by peterzernia** [mozilla/geckodriver#1679] opened 2020-01-28 10:29 UTC
## System

* Version: 0.26
* Platform: python:3-alpine docker container

I was installing the latest release of the geckodriver into my alpine linux docker container, and after v0.26 came out, the driver binary broke as explained in this comment:

https://github.com/mozilla/geckodriver/issues/1643#issuecomment-557529452

my install script:

```
json=$(curl -s https://api.github.com/repos/mozilla/geckodriver/releases/latest)
if [[ $(uname) == "Linux" ]]; then
    url=$(echo "$json" | jq -r '.assets[].browser_download_url | select(contains("linux64"))')
else
    exit 1
fi
curl -s -L "$url" | tar -xz
chmod +x geckodriver
mv geckodriver "/usr/local/bin"
```

selenium error: `WebDriverException: Message: 'geckodriver' executable needs to be in PATH.`

Downgrading to v0.25 fixes the issue

**Comment by whimboo** [comment] 2020-02-03 13:51
What happens when you manually run the binary, means outside of Selenium?

**Comment by peterzernia** [comment] 2020-02-03 14:03
It says the binary doesn't exist.

I added glibc to the alpine docker container, which now allows v0.26 to run in the container while v0.25 still runs without glibc.

**Comment by whimboo** [comment] 2020-02-03 14:57
Ah, so can you please have a look if the following binary works without glibc?

https://firefox-ci-tc.services.mozilla.com/api/queue/v1/task/A3iclKj9QBajC3HVGyPHDA/runs/0/artifacts/public/build/target.common.tests.tar.gz

Extract geckdriver from that file. It is located under `/bin`. Does it work?

**Comment by peterzernia** [comment] 2020-02-06 12:08
Trying to run it throws the error `geckodriver: not found`, but once glibc is installed it runs

**Comment by whimboo** [comment] 2020-02-07 12:50
Ok, so I assume something changed maybe within the rust compiler, or a build setting. We didn't land anything for the [0.26 release](https://bugzilla.mozilla.org/show_bug.cgi?id=1573798) which would have added the dependency for it. Only for toolchain builds we made a change, but the binary from the above link to `target.common.tests.tar.gz` is not such a build.

Note that for Windows we have https://bugzilla.mozilla.org/show_bug.cgi?id=1584530 which is about a temporary dependency on MSVC runtime. But on Linux isn't glibc essential to have? And shouldn't we have it dynamically linked? @froydnj what do you think?

**Comment by froydnj** [comment] 2020-02-07 14:41
> I added glibc to the alpine docker container, which now allows v0.26 to run in the container while v0.25 still runs without glibc.

Is alpine some sort of musl-only, statically-linked distro?

Anyway, the `file not found` error is probably the least helpful error when trying to execute a program.  What that message is trying to tell you is that one of the dynamic libraries the executable depends on doesn't exist.  That would explain why installing the `glibc` package fixed things, because the 0.26 `geckodriver` (presumably) depends on `libc.so.6` existing somewhere, or other similar files.

And indeed, looking at the binaries with `ldd`:

```
froydnj@hawkeye:/opt/extra/froydnj$ tar xf /opt/build/froydnj/tmp/geckodriver-v0.26.0-linux64.tar.gz 
froydnj@hawkeye:/opt/extra/froydnj$ ldd geckodriver 
	linux-vdso.so.1 =>  (0x00007fffa982a000)
	libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007f0dd16b7000)
	librt.so.1 => /lib/x86_64-linux-gnu/librt.so.1 (0x00007f0dd14af000)
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f0dd1292000)
	libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007f0dd107a000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f0dd0cb0000)
	/lib64/ld-linux-x86-64.so.2 (0x00007f0dd1ecc000)
	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f0dd09a7000)
froydnj@hawkeye:/opt/extra/froydnj$ tar xf /opt/build/froydnj/tmp/geckodriver-v0.25.0-linux64.tar.gz 
froydnj@hawkeye:/opt/extra/froydnj$ ldd geckodriver 
	not a dynamic executable
```

So it seems that the 0.25 release was statically linked (and therefore didn't depend on glibc) whereas the 0.26 release was not.  @whimboo, did something change during the 0.26 development cycle in terms of how the releases were built?  Docker images or something like that?

**Comment by TheRealD00dle** [comment] 2020-04-13 21:31
I can confirm this issue described above. Version 0.26 is not working on Alpine while 0.25 does. I didn't try installing glibc though. Using 0.25 for now. 

If you need help testing solutions just ping me.

**Comment by whimboo** [comment] 2020-06-03 18:19
@froydnj thank you for the check! Indeed it's a regression and I filed https://bugzilla.mozilla.org/show_bug.cgi?id=1643099 now. Sorry for the delay. We will have it fixed for the 0.27 release.

**Comment by whimboo** [comment] 2020-06-29 21:08
@peterzernia or @TheRealD00dle can you please try these builds if they work for you now? If that the case we will release it soon with 0.27.

Linux32: https://treeherder.mozilla.org/#/jobs?repo=try&revision=f35819177798c7ed3227fa297d6f0ed22f62943b&searchStr=build&selectedTaskRun=aqQ_aBoLRMSssWu8iRElPQ.0
Linux64: https://treeherder.mozilla.org/#/jobs?repo=try&revision=f35819177798c7ed3227fa297d6f0ed22f62943b&searchStr=build&selectedTaskRun=GnZhAioBTg2yhw1RAT-VwQ.0

Then click the 'Job Details' pane at the bottom, and download the geckodriver.tar.gz file. Please let me know if that works for you now. At least `ldd` shows it's not dynamically linked anymore.

**Comment by whimboo** [comment] 2020-07-01 07:09
This is fixed now and will be shipped with the next geckodriver release. If you want to test just grab a signed nightly build of geckodriver:

Linux32: https://firefox-ci-tc.services.mozilla.com/api/queue/v1/task/Y58Qg25XTy-cP1MzXzguxg/runs/0/artifacts/public/build/geckodriver.tar.gz
Linux64: https://firefox-ci-tc.services.mozilla.com/api/queue/v1/task/Lw-y4Y_WSd62yyRvzvXEtA/runs/0/artifacts/public/build/geckodriver.tar.gz

**Closed by whimboo** 2020-07-01 07:09 UTC
Labels: geckodriver
