### ISSUE TITLE
A new driver connects to an already existing session of Firefox

### ISSUE THREAD

**Issue by nirp1981** [mozilla/geckodriver#76] opened 2016-06-09 09:12 UTC
1.open a new session of firefox throught the driver .
2.stop the test but leave the firefox window open,
3.run : 
@Test
	public void test1() throws Exception{
		WebDriver _driver; 
		DesiredCapabilities dc = DesiredCapabilities.firefox();
		OSUtils.setSystemProperty("webdriver.firefox.bin", "C:\\FirefoxOfficial\\firefox.exe");
		OSUtils.setSystemProperty("webdriver.gecko.driver","C:\\Wires\\wires.exe");
		_driver = new MarionetteDriver(dc);
		_driver.navigate().to("https://www.google.com/");
	}

The result:
=> 
A new session of firefox is opened, but the navigation occurs on the old already exited session. 
I used wires 0.7.1 , and tried firefox 46 & 47.

**Comment by andreastt** [comment] 2016-06-09 10:59
Can you clarify what “stop the test but leave the Firefox window open” means? It sounds like your geckodriver/wires executable does not shut down when your program stops running.

**Comment by AutomatedTester** [comment] 2016-06-09 11:01
Looks like a duplicate of #42

**Closed by AutomatedTester** 2016-06-09 11:01 UTC
