### ISSUE TITLE
Crash with message "Process unexpectedly closed with status: 1"

### ISSUE THREAD

**Issue by fwilhe** [mozilla/geckodriver#1189] opened 2018-02-27 12:52 UTC
## System

* Version: 0.19.1
* Platform: Docker container of Ubuntu 17.10 on macOS 10.13.3 (17D47) with Docker Version 17.12.0-ce-mac49 (21995)
* Firefox: Mozilla Firefox 58.0.2 (Installed from Ubuntu repo)
* Selenium: 3.9.1.

This issue is probably related to #1172

## Testcase

`Dockerfile`:

```
FROM ubuntu:17.10
RUN apt-get update && \
    apt-get install -y firefox default-jre npm nodejs && \
    rm -rf /var/lib/apt/lists/* /var/cache/apt/*
COPY . code
WORKDIR /code
RUN rm -rf node_modules && npm install
CMD ./node_modules/geckodriver/bin/geckodriver --version && \
    ./node_modules/nightwatch/bin/nightwatch
```

`nightwatch.conf.js`:

```
const seleniumServer = require('selenium-server');
const geckodriver = require("geckodriver");

const options = {
    src_folders: "page_objects",
    page_objects_path: 'page_objects',
    selenium: {
        "start_process": true,
        "server_path": seleniumServer.path,
        "log_path": "",
        "port": 4444,
        "cli_args": {
            "webdriver.gecko.driver": geckodriver.path
        }
    },
    test_settings: {
        default: {
            selenium_port: 4444,
            selenium_host: '127.0.0.1',
            default_path_prefix: "/wd/hub",
            desiredCapabilities: {
                browserName: "firefox",
                javascriptEnabled: true,
                acceptSslCerts: true,
                acceptInsecureCerts: true,
                marionette: true,
                "moz:firefoxOptions": {
                    "log": {
                        "level": "trace"
                    }
                }
            }
        }
    }
}

module.exports = options;
```

`package.json`:

```
{
  "name": "geckodriver-issue",
  "private": true,
  "devDependencies": {
    "geckodriver": "^1.10.0",
    "nightwatch": "^0.9.19",
    "selenium-server": "^3.9.1"
  }
}
```

`page_objects/demo.js`:

```
module.exports = {
    'demo test google' : function (client) {
        client
          .url('http://google.com')
          .waitForElementPresent('body', 1000);
      }
};
```

Fully running example: https://github.com/fwilhe/geckodriver-issue

## Stacktrace

```
remote stacktrace: stack backtrace:
   0:           0x4edb3c - backtrace::backtrace::trace::hc4bd56a2f176de7e
   1:           0x4edb72 - backtrace::capture::Backtrace::new::he3b2a15d39027c46
   2:           0x440ac8 - webdriver::error::WebDriverError::new::ha0fbd6d1a1131b43
   3:           0x4487ce - geckodriver::marionette::MarionetteHandler::create_connection::hf0532ddb9e159684
   4:           0x428570 - <webdriver::server::Dispatcher<T, U>>::run::h2119c674d7b88193
   5:           0x4029b9 - std::sys_common::backtrace::__rust_begin_short_backtrace::h21d98a9ff86d4c25
   6:           0x40be65 - std::panicking::try::do_call::h5cff0c9b18cfdbba
   7:           0x5e6a6c - panic_unwind::__rust_maybe_catch_panic
                        at /checkout/src/libpanic_unwind/lib.rs:99
   8:           0x41eb22 - <F as alloc::boxed::FnBox<A>>::call_box::h413eb1d9d9f1c473
   9:           0x5df13b - alloc::boxed::{{impl}}::call_once<(),()>
                        at /checkout/src/liballoc/boxed.rs:692
                         - std::sys_common::thread::start_thread
                        at /checkout/src/libstd/sys_common/thread.rs:21
                         - std::sys::imp::thread::{{impl}}::new::thread_start
                        at /checkout/src/libstd/sys/unix/thread.rs:84',
```

## Trace-level log

```
15:29:23.437 INFO - Selenium build info: version: '3.9.1', revision: '63f7b50'
15:29:23.440 INFO - Launching a standalone Selenium Server on port 4444
2018-02-27 15:29:23.602:INFO::main: Logging initialized @638ms to org.seleniumhq.jetty9.util.log.StdErrLog
2018-02-27 15:29:23.778:INFO:osjs.Server:main: jetty-9.4.7.v20170914, build timestamp: 2017-11-21T21:27:37Z, git hash: 82b8fb23f757335bb3329d540ce37a2a2615f0a8
2018-02-27 15:29:23.810:WARN:osjs.SecurityHandler:main: ServletContext@o.s.j.s.ServletContextHandler@61f8bee4{/,null,STARTING} has uncovered http methods for path: /
2018-02-27 15:29:23.816:INFO:osjsh.ContextHandler:main: Started o.s.j.s.ServletContextHandler@61f8bee4{/,null,AVAILABLE}
2018-02-27 15:29:23.854:INFO:osjs.AbstractConnector:main: Started ServerConnector@50f05a95{HTTP/1.1,[http/1.1]}{0.0.0.0:4444}
2018-02-27 15:29:23.855:INFO:osjs.Server:main: Started @890ms
15:29:23.855 INFO - Selenium Server is up and running on port 4444
2018-02-27 15:29:24.122:INFO:osjshC.ROOT:qtp110456297-14: org.openqa.selenium.remote.server.WebDriverServlet-3e6fa38a: Initialising WebDriverServlet
15:29:24.225 INFO - Found handler: org.openqa.selenium.remote.server.commandhandler.BeginSession@5a111b1e
15:29:24.230 INFO - /session: Executing POST on /session (handler: BeginSession)
15:29:24.361 INFO - Capabilities are: Capabilities {acceptInsecureCerts: true, acceptSslCerts: true, browserName: firefox, javascriptEnabled: true, marionette: true, moz:firefoxOptions: {log: {level: trace}}, name: Demo}
15:29:24.363 INFO - Capabilities {acceptInsecureCerts: true, acceptSslCerts: true, browserName: firefox, javascriptEnabled: true, marionette: true, moz:firefoxOptions: {log: {level: trace}}, name: Demo} matched class org.openqa.selenium.remote.server.ServicedSession$Factory (provider: org.openqa.selenium.firefox.GeckoDriverService)
1519745364420	geckodriver	INFO	geckodriver 0.19.1
1519745364422	geckodriver	INFO	Listening on 127.0.0.1:8450
1519745364823	mozrunner::runner	INFO	Running command: "/usr/bin/firefox" "-marionette" "-profile" "/tmp/rust_mozprofile.J2tNE3I5s3qt"
1519745364824	geckodriver::marionette	TRACE	  connection attempt 0/600
Error: no DISPLAY environment variable specified
1519745364927	webdriver::server	DEBUG	<- 500 Internal Server Error {"value":{"error":"unknown error","message":"Process unexpectedly closed with status: 1","stacktrace":"stack backtrace:\n   0:           0x4edb3c - backtrace::backtrace::trace::hc4bd56a2f176de7e\n   1:           0x4edb72 - backtrace::capture::Backtrace::new::he3b2a15d39027c46\n   2:           0x440ac8 - webdriver::error::WebDriverError::new::ha0fbd6d1a1131b43\n   3:           0x4487ce - geckodriver::marionette::MarionetteHandler::create_connection::hf0532ddb9e159684\n   4:           0x428570 - <webdriver::server::Dispatcher<T, U>>::run::h2119c674d7b88193\n   5:           0x4029b9 - std::sys_common::backtrace::__rust_begin_short_backtrace::h21d98a9ff86d4c25\n   6:           0x40be65 - std::panicking::try::do_call::h5cff0c9b18cfdbba\n   7:           0x5e6a6c - panic_unwind::__rust_maybe_catch_panic\n                        at /checkout/src/libpanic_unwind/lib.rs:99\n   8:           0x41eb22 - <F as alloc::boxed::FnBox<A>>::call_box::h413eb1d9d9f1c473\n   9:           0x5df13b - alloc::boxed::{{impl}}::call_once<(),()>\n                        at /checkout/src/liballoc/boxed.rs:692\n                         - std::sys_common::thread::start_thread\n                        at /checkout/src/libstd/sys_common/thread.rs:21\n                         - std::sys::imp::thread::{{impl}}::new::thread_start\n                        at /checkout/src/libstd/sys/unix/thread.rs:84"}}
```

**Comment by andreastt** [comment] 2018-02-27 14:10
Could you please attach a [trace-level log] from geckodriver? Read more about reporting actionable bugs in our [contribution guidelines].

[trace-level log]: https://searchfox.org/mozilla-central/source/testing/geckodriver/doc/TraceLogs.md
[contribution guidelines]: https://searchfox.org/mozilla-central/source/testing/geckodriver/CONTRIBUTING.md#reporting-bugs

**Comment by fwilhe** [comment] 2018-02-27 15:34
Hello @andreastt,

thanks for the hint, I was unaware that the trace is not written to stdout. I updated the issue accordingly.

Best regards,
Florian

**Comment by AutomatedTester** [comment] 2018-02-28 11:20
Duplicate of #1172

**Closed by AutomatedTester** 2018-02-28 11:20 UTC

**Comment by whimboo** [comment] 2018-03-06 08:24
This is not a dupe of issue #1172 but just a problem with running the tests. Please see the following line in the trace log:

> Error: no DISPLAY environment variable specified

Without a DISPLAY specified the tests cannot be run. So fix that or use headless mode.
