### ISSUE TITLE
Stable Firefox Version with a new geckodriver Patch 0.27.0?

### ISSUE THREAD

**Issue by Easyside** [mozilla/geckodriver#1759] opened 2020-08-10 17:49 UTC
Witch firefox version is stable with 0.2.7.0 ??? without error JavaScript error: resource://gre/modules/XULStore.jsm ..

**Comment by whimboo** [comment] 2020-08-11 13:18
That is not a problem with geckodriver but just an error as raised by Firefox. We cannot hide those for the moment. See issue #1046 where this is a dupe of. Otherwise always check https://firefox-source-docs.mozilla.org/testing/geckodriver/Support.html for supported Firefox releases.

**Closed by whimboo** 2020-08-11 13:18 UTC
