### ISSUE TITLE
Page opened through the driver lost field focus

### ISSUE THREAD

**Issue by altus34** [mozilla/geckodriver#394] opened 2016-12-13 05:17 UTC
## Firefox Version
50.0.2

## Platform
Linux

## Steps to reproduce -
Open a page with Firefox where a field in a form have the focus by default ex: https://www.google.ca
(the search input have the focus)

Open the same page through the driver and the focus is not here.

**Comment by andreastt** [comment] 2016-12-29 14:42
I cannot reproduce this:

```
>>> m.navigate("https://www.google.ca")
1483022426614	Marionette	TRACE	conn2 -> [0,5,"get",{"url":"https://www.google.ca"}]
>>> 1483022427093	Marionette	TRACE	conn2 <- [1,5,null,{}]

>>> el = m.execute_script("return document.activeElement", sandbox=None)
1483022481247	Marionette	TRACE	conn2 -> [0,7,"executeScript",{"scriptTimeout":null,"newSandbox":true,"args":[],"filename":"<stdin>","script":"return document.activeElement","sandbox":null,"line":1}]
1483022481251	Marionette	TRACE	conn2 <- [1,7,null,{"value":{"element-6066-11e4-a52e-4f735466cecf":"7e740b86-66a5-4bd5-a481-0da1d674f6b2","ELEMENT":"7e740b86-66a5-4bd5-a481-0da1d674f6b2"}}]

>>> el.tag_name
u'input'
>>> 1483022496268	Marionette	TRACE	conn2 -> [0,9,"getElementTagName",{"id":"7e740b86-66a5-4bd5-a481-0da1d674f6b2"}]
1483022496269	Marionette	TRACE	conn2 <- [1,9,null,{"value":"input"}]
```

**Comment by altus34** [comment] 2017-01-04 04:11
Sorry to come back to you but your test is not enough.

Can you just open the page https://www.google.ca with Firefox and look that the input field have the focus.
After open the same page with selenium => m.navigate("https://www.google.ca")

Have you the focus on the field ?

FF: 50.0.2
Geckodriver: geckodriver-v0.12.0-linux64
OS: Linux

Thanks

**Comment by andreastt** [comment] 2017-01-04 07:55
Yes, as is proven by my snippet.

**Comment by altus34** [comment] 2017-01-04 16:59
No you script prove just that document.activeElement return to you the input.
Ok so improve the test a little bit ;)

Try this:
 1 -  Execute the call of this script : "document.activeElement" 
We expect to have the input selected.
 2 - Now call this script: "document.querySelectorAll(':focus')"

In the case 2 I expect to have an array who contain one element, the same has the first call.
This is not the case with the geckodriver and it's the case with the chromedriver and edgedriver for exemple.

It's very simple to verify in fact. Just open the page with m.navigate("https://www.google.ca")
and type text on your keyboard. The text is added in your URL bar which is focused (you can see a red border).

Can you explain me ?

Thanks

**Comment by andreastt** [comment] 2017-01-04 19:35
OK, I think you are right that `document.activeElement` and `document.querySelector(":focus")` are different concepts. With some careful testing, ensuring not to invoke focus in any way, I’m able to reproduce this on Linux too.

It seems that the root cause is that we somehow focus the address bar after opening the first window. To ensure proper focus is given to the web content frame (the `<xul:browser>` element), we ought to focus this after creating a session and upon navigation.

I filed [bug 1328676](https://bugzilla.mozilla.org/show_bug.cgi?id=1328676) to fix this.

**Comment by altus34** [comment] 2017-01-04 20:29
I've a very large test suite to test pretty all features expected for selenium if you want ;)

**Comment by andreastt** [comment] 2017-01-09 16:44
This has now landed on Nightly (53) and Aurora/ESR (52).

**Closed by andreastt** 2017-01-09 16:44 UTC
Labels: marionette
