### ISSUE TITLE
Selenium 3.x double click not working

### ISSUE THREAD

**Issue by mrunalgosar** [mozilla/geckodriver#767] opened 2017-06-04 16:24 UTC
## Steps to reproduce -
Selenium 3.x is unable to perform double click operation.

## Test code:
```
public class GeckoTest {
    public static void main(String[] args) throws IOException {
        System.setProperty("webdriver.gecko.driver","I:\\jetbrainsworkspace\\src\\test\\resources\\geckodriver.exe");
        FirefoxBinary binary = new FirefoxBinary(new File("D:\\installations\\browsers\\ff\\52.0.2_32\\firefox.exe"));
        FirefoxOptions options = new FirefoxOptions();
        options.setBinary(binary);
        options.setLogLevel(Level.ALL);
        WebDriver browser = new FirefoxDriver(options);
        browser.manage().timeouts().pageLoadTimeout(10, TimeUnit.SECONDS);
        browser.manage().timeouts().implicitlyWait(10,TimeUnit.SECONDS);
        browser.get("https://examples.sencha.com/extjs/6.0.1/examples/classic/ticket-app/index.html");
        WebDriverWait wait = new WebDriverWait(browser,20,3000);
        wait.until(ExpectedConditions.visibilityOfElementLocated(By.name("password"))).sendKeys("sometext");
        wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath(".//span[text()='Login']"))).click();
        WebElement ele = wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath(".//div[text()='Fiant adipiscing clari nunc molestie per placerat vero insitam; ullamcorper saepius etiam claritatem quod.']")));
        Actions builder = new Actions(browser);
        builder.doubleClick(ele).build().perform();
        browser.close();
    }
}
```
## Logs: As attached 
[Logs.docx](https://github.com/mozilla/geckodriver/files/1050508/Logs.docx)

**Comment by andreastt** [comment] 2017-06-05 09:12
What do you mean exactly that it “does not work”? Unfortunately I can’t open the logs because I don’t have Microsoft Word. Please attach a plain text fail with a trace-level log from geckodriver.

The WebDriver specification, which geckodriver implements, does not explicitly define a double click primitive, so I suspect that this is an issue in the Selenium shim.

**Comment by AutomatedTester** [comment] 2017-06-05 11:06
duplicate of #661

**Closed by AutomatedTester** 2017-06-05 11:06 UTC
Labels: selenium, waiting for reporter feedback

**Comment by rscwcd** [comment] 2017-06-09 10:49
@AutomatedTester : Everywhere I can see, everyone is just closing this issue without having a confirmation of availability of proper solution to the issue.

**Comment by crazydude552** [comment] 2017-07-31 13:56
Even for me the double click in Actions class not working... I am using Selenium3.4.0 , firefox 52.0 est version. Even in chrome i have same issue....double click event not working... Any solution

i have used

WebElement d=driver.findElement(By.xpath("//*[@id='messageFilterTable']"));
			
			action.doubleClick(d).build().perform();

I have tried even
action.moveToElement(d).doubleClick().build().perform(); but no use

**Comment by andreastt** [comment] 2017-07-31 14:43
Locking because it’s a duplicate.
