### ISSUE TITLE
Extension does not working on firefox version 64

### ISSUE THREAD

**Issue by lequangphuong** [mozilla/geckodriver#1501] opened 2019-02-12 06:38 UTC
## System

* Version: v0.23.0
* Platform: Windows 10 64bit
* Firefox:  Quantum 64.0.2 (64bit)
* Selenium: 3.12.0

## Testcase

  final File extFile = Paths.get(extPath, "firefox", "extension.xpi").toFile();
       
       
        final FirefoxProfile ffProfile = new FirefoxProfile();
     
         ffProfile.addExtension(extFile);
       
        //Enable web socket communication
        ffProfile.setPreference("network.websocket.allowInsecureFromHTTPS", true);
        ffProfile.setPreference("devtools.toolbox.footer.height", 0);
        ffProfile.setPreference("devtools.devedition.promo.enabled", false);
        ffProfile.setPreference("devtools.devedition.promo.shown", false);
        options.addArguments("-devtools");
        options.setProfile(ffProfile);
        final WebDriver driver = new FirefoxDriver(options);

## Stacktrace
549953076526	addons.xpi	DEBUG	New add-on webcompat-reporter@mozilla.org in app-system-defaults
1549953076526	addons.xpi	DEBUG	New add-on webcompat@mozilla.org in app-system-defaults
1549953076527	addons.xpi	DEBUG	scanForChanges changed: true, state: {}
1549953076531	addons.xpi-utils	DEBUG	Error: Synchronously loading the add-ons database(resource://gre/modules/addons/XPIDatabase.jsm:1360:15) JS Stack trace: syncLoadDB@XPIDatabase.jsm:1360:15
checkForChanges@XPIProvider.jsm:2554:9
startup@XPIProvider.jsm:2134:25
callProvider@AddonManager.jsm:203:12
_startProvider@AddonManager.jsm:651:5
startup@AddonManager.jsm:804:9
startup@AddonManager.jsm:2774:5
observe@addonManager.js:66:9
1549953076531	addons.xpi-utils	DEBUG	Starting async load of XPI database D:\AppData\Local\Temp\rust_mozprofile.9pcz4ZAjlraK\extensions.json
1549953076555	addons.xpi-utils	DEBUG	New add-on admin@domain.com installed in app-profile
*** Blocklist::_loadFileInternal: blocklist is disabled
1549953076656	addons.xpi-utils	WARN	Add-on admin@domain.com is not correctly signed.
1549953076656	addons.xpi-utils	WARN	Add-on admin@domain.com is not correctly signed.
1549953076656	addons.xpi-utils	WARN	addMetadata: Add-on admin@domain.com is invalid: Error: Extension admin@domain.com is not correctly signed(resource://gre/modules/addons/XPIDatabase.jsm:2426:17) JS Stack trace: addMetadata@XPIDatabase.jsm:2426:17
processFileChanges@XPIDatabase.jsm:2769:21
checkForChanges@XPIProvider.jsm:2556:34
startup@XPIProvider.jsm:2134:25
callProvider@AddonManager.jsm:203:12
_startProvider@AddonManager.jsm:651:5
startup@AddonManager.jsm:804:9
startup@AddonManager.jsm:2774:5
observe@addonManager.js:66:9

**Comment by whimboo** [comment] 2019-02-12 10:58
What kind of extension is that you are trying to install here? Is it one based on the webextension API? If not it won't work with Firefox 64 anymore. Also note that the log above shows that the addon is not correctly signed:

> 1549953076656 addons.xpi-utils WARN Add-on [admin@domain.com](mailto:admin@domain.com) is not correctly signed.

Without signing you can only install extensions temporarily. But that AFAIR doesn't work with the Selenium profile instance. You would have to use https://firefox-source-docs.mozilla.org/testing/geckodriver/geckodriver/Capabilities.html#firefox-capabilities to setup a custom profile with already the extension installed, or the extension command of geckodriver if the Selenium binding (which one are you using?) supports it like https://seleniumhq.github.io/selenium/docs/api/py/webdriver_firefox/selenium.webdriver.firefox.webdriver.html#selenium.webdriver.firefox.webdriver.WebDriver.install_addon for the Python bindings.

**Comment by Julioevm** [comment] 2019-03-07 15:41
I'm having the same issue as the Op, but I did sign the extension using https://addons.mozilla.org and a developer account. On firefox > 64 I get the same message of the extension not being correctly signed. I can install it on the desktop browser without problems.
On the code I use the addExtension() method of the FirefoxProfile Class for java. Am I missing something?

**Comment by whimboo** [comment] 2019-03-08 07:57
This issue might be related or a dupe of #1517.

**Comment by whimboo** [comment] 2019-06-27 08:00
No reply from reporter. As such closing the issue.

**Closed by whimboo** 2019-06-27 08:00 UTC
Labels: waiting for reporter feedback
